DGtal: DGtal::HyperRectDomain< TSpace > Class Template Reference
DGtal::HyperRectDomain< TSpace > Class Template Reference
Aim: Parallelepidec region of a digital space, model of a 'CDomain'.
#include <DGtal/kernel/domains/HyperRectDomain.h>
Data Structures
struct ConstSubRange
Aim: range through some subdomain of all the points in the domain. Defines a constructor taking a domain in parameter plus some additional parameters to specify the subdomain, begin and end methods returning ConstIterator, and rbegin and rend methods returning ConstReverseIterator.
Public Types
typedef HyperRectDomain< TSpace > Self
typedef TSpace Space
typedef HyperRectDomain< Space > Domain
typedef Space::Point Point
typedef Space::Integer Integer
typedef Space::Vector Vector
typedef Space::Dimension Dimension
typedef Space::Size Size
typedef Point::Coordinate Coordinate
typedef HyperRectDomain_Iterator< Point > Iterator
Typedef of domain iterators.
typedef HyperRectDomain_ReverseIterator< Iterator > ReverseIterator
typedef Iterator ConstIterator
typedef ReverseIterator ConstReverseIterator
typedef functors::IsWithinPointPredicate< Point > Predicate
Public Member Functions
BOOST_STATIC_CONSTANT (Dimension, dimension=Space::dimension)
HyperRectDomain ()
HyperRectDomain (const Point &lowerPoint, const Point &upperPoint)
HyperRectDomain (const typename Space::RealPoint &lowerPoint, const typename Space::RealPoint &upperPoint)
~HyperRectDomain ()
HyperRectDomain (const HyperRectDomain &other)
HyperRectDomain & operator= (const HyperRectDomain &other)
const ConstIterator & begin () const
ConstIterator begin (const Point &aPoint) const
const ConstIterator & end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
ConstSubRange subRange (const std::vector< Dimension > &permutation) const
ConstSubRange subRange (const std::vector< Dimension > &permutation, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim1, Dimension adim2, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim1, Dimension adim2, Dimension adim3, const Point &startingPoint) const
ConstSubRange subRange (std::initializer_list< Dimension > permutation)
ConstSubRange subRange (std::initializer_list< Dimension > permutation, const Point &startingPoint)
Size size () const
const Point & lowerBound () const
const Point & upperBound () const
bool isInside (const Point &p) const
bool isEmpty () const
const Predicate & predicate () const
std::string className () const
void selfDisplay (std::ostream &out) const
bool isValid () const
Data Fields
Point myLowerBound
The lowest point of the space diagonal.
Point myUpperBound
The highest point of the space diagonal.
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
Private Attributes
Predicate myPredicate
"IsInside" predicate.
ConstIterator myIteratorBegin
Begin iterator.
ConstIterator myIteratorEnd
End iterator.
Detailed Description
template<typename TSpace>
class DGtal::HyperRectDomain< TSpace >
Aim: Parallelepidec region of a digital space, model of a 'CDomain'.
Description of class 'HyperRectDomain'
The following code snippet demonstrates how to use HyperRectDomain
 #include <DGtal/kernel/Space.h>
 #include <DGtal/kernel/domains/HyperRectDomain.h>
...
//We create a digital Space based on 'int' integers and in dimension 4
typedef DGtal::Space<4> Space4D;
typedef Space4D::TPoint Point4D;
const int rawA[ ] = { 1, 2, 3 ,4};
const int rawB[ ] = { 5, 5, 3 ,4};
Point4D A (rawA);
Point4D B (rawB);
//Domain construction from two points
DGtal::HyperRectDomain<Space4D> myDomain (A, B);
//We iterate on the Domain points and print out the point coordinates.
std::copy (myDomain.begin(),
            myDomain.end(),
            std::ostream_iterator<Point4D> ( std::cout, " " ) );
More informations can be found in the module page about Digital Spaces, Points, Vectors and Domains .
Note
Since DGtal 1.1, HyperRectDomain provides random-access iterators. It can be use to easily split the domain, for example for parallelization purpose. See the dedicated section Scanning an HyperRectDomain in parallel and the example file (and benchmark) exampleHyperRectDomainParallelScan.cpp .
See also
testHyperRectDomain.cpp
Examples
doc-examples/demo-kernel-1.cpp, doc-examples/kernelDomain.cpp, doc-examples/range.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/volumes/dvcm-2d.cpp, io/viewers/demo-kernel-2.cpp, and topology/3dBorderExtraction.cpp.
Definition at line 99 of file HyperRectDomain.h.
Member Typedef Documentation
ConstIterator
template<typename TSpace > Iterator DGtal::HyperRectDomain< TSpace >::ConstIterator
Definition at line 125 of file HyperRectDomain.h.
ConstReverseIterator
template<typename TSpace > ReverseIterator DGtal::HyperRectDomain< TSpace >::ConstReverseIterator
Definition at line 126 of file HyperRectDomain.h.
Coordinate
template<typename TSpace > Point::Coordinate DGtal::HyperRectDomain< TSpace >::Coordinate
Definition at line 118 of file HyperRectDomain.h.
Dimension
template<typename TSpace > Space::Dimension DGtal::HyperRectDomain< TSpace >::Dimension
Definition at line 116 of file HyperRectDomain.h.
Domain
template<typename TSpace > HyperRectDomain<Space> DGtal::HyperRectDomain< TSpace >::Domain
Definition at line 112 of file HyperRectDomain.h.
Integer
template<typename TSpace > Space::Integer DGtal::HyperRectDomain< TSpace >::Integer
Definition at line 114 of file HyperRectDomain.h.
Iterator
template<typename TSpace > HyperRectDomain_Iterator<Point> DGtal::HyperRectDomain< TSpace >::Iterator
Typedef of domain iterators.
Definition at line 123 of file HyperRectDomain.h.
Point
template<typename TSpace > Space::Point DGtal::HyperRectDomain< TSpace >::Point
Definition at line 113 of file HyperRectDomain.h.
Predicate
template<typename TSpace > functors::IsWithinPointPredicate<Point> DGtal::HyperRectDomain< TSpace >::Predicate
Definition at line 128 of file HyperRectDomain.h.
ReverseIterator
template<typename TSpace > HyperRectDomain_ReverseIterator<Iterator> DGtal::HyperRectDomain< TSpace >::ReverseIterator
Definition at line 124 of file HyperRectDomain.h.
Self
template<typename TSpace > HyperRectDomain<TSpace> DGtal::HyperRectDomain< TSpace >::Self
Definition at line 106 of file HyperRectDomain.h.
Size
template<typename TSpace > Space::Size DGtal::HyperRectDomain< TSpace >::Size
Definition at line 117 of file HyperRectDomain.h.
Space
template<typename TSpace > TSpace DGtal::HyperRectDomain< TSpace >::Space
Definition at line 110 of file HyperRectDomain.h.
Vector
template<typename TSpace > Space::Vector DGtal::HyperRectDomain< TSpace >::Vector
Definition at line 115 of file HyperRectDomain.h.
Constructor & Destructor Documentation
HyperRectDomain() [1/4]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain ()
Default Constructor.
HyperRectDomain() [2/4]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain (const Point & lowerPoint, const Point & upperPoint)
Constructor from two points
Parameters
lowerPoint and
upperPoint defining the space diagonal.
HyperRectDomain() [3/4]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain (const typename Space::RealPoint & lowerPoint, const typename Space::RealPoint & upperPoint)
Constructor from two points
Parameters
lowerPoint and
upperPoint with real coordinates and that define the space diagonal.
The domain actualy defined is the smallest domain with integer bounds that contains the two given points.
~HyperRectDomain()
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::~HyperRectDomain ()
Destructor.
HyperRectDomain() [4/4]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain (const HyperRectDomain< TSpace > & other)
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
begin() [1/2]
template<typename TSpace > const ConstIterator & DGtal::HyperRectDomain< TSpace >::begin () const inline
begin method.
Returns
ConstIterator on the beginning of the range.
Definition at line 176 of file HyperRectDomain.h.
      {
        return myIteratorBegin;
      }
References DGtal::HyperRectDomain< TSpace >::myIteratorBegin.
Referenced by displayPredicate(), displaySimplicityTable(), displaySimplicityTable(), generateRefImage(), lightBetween(), localDualVolume(), main(), main(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), Object3D(), pointsInStandardPlane(), DGtal::HyperRectDomain< TSpace >::rbegin(), DGtal::HyperRectDomain< TSpace >::rend(), DGtal::ImageFactoryFromHDF5< TImageContainer >::requestImage(), SCENARIO(), TEST_CASE(), TEST_CASE(), TEST_CASE(), testBoard2D(), testComparison(), testDigitalSetDomain(), testDigitalSetDraw(), testDisplayDT3d(), testDistanceTransformation3D(), testDistanceTransformND(), testDraw(), testExpander(), testImageAdapter(), testImageOnRef(), testIterator(), testKanungo2D(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testSetFromImage(), testSimplePoints3D(), testVoronoiMap(), and testWriteAndRead().
begin() [2/2]
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::begin (const Point & aPoint) const inline
begin method from a given point.
Parameters
aPoint the initial point.
Returns
a ConstIterator initialized to aPoint.
Precondition
aPoint must belong to the range.
Definition at line 187 of file HyperRectDomain.h.
      {
        ASSERT_MSG(
            isInside(aPoint) || aPoint == myLowerBound || aPoint == myUpperBound,
            "The point must be inside the domain or be equal to one of his bound."
        );
        return ConstIterator(aPoint, myLowerBound, myUpperBound);
      }
References aPoint(), DGtal::HyperRectDomain< TSpace >::isInside(), DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
BOOST_CONCEPT_ASSERT()
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >)) private
BOOST_STATIC_CONSTANT()
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::BOOST_STATIC_CONSTANT (Dimension , dimension = Space::dimension)
className()
template<typename TSpace > std::string DGtal::HyperRectDomain< TSpace >::className () const
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
Referenced by checkCut(), checkOutputConvexHullBorder(), displaySimplicityTable(), displaySimplicityTable(), drawArithmeticalDSL(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleUpdate(), main(), main(), main(), showGreedySegmantation(), specificTestLatticePolytope2D(), testBIGINTEGERSpace(), testBoard2D(), testBoard2DCustomStyle(), testBoard3D(), testBreadthFirstPropagation(), testCellDrawOnBoard(), testDepthFirstPropagation(), testDigitalSetBoardSnippet(), testDigitalSetDraw(), testDigitization(), testDistancePropagation(), testDraw(), testDSS4drawing(), testDSS8drawing(), testLatticePolytope2D(), testLayers(), testObjectBorder(), testSetTable(), testSimpleExpander(), testSimplePoints2D(), and testSurfelAdjacency().
end()
template<typename TSpace > const ConstIterator & DGtal::HyperRectDomain< TSpace >::end () const inline
end method.
Returns
ConstIterator on the end of the range.
Definition at line 201 of file HyperRectDomain.h.
      {
        return myIteratorEnd;
      }
References DGtal::HyperRectDomain< TSpace >::myIteratorEnd.
Referenced by displayPredicate(), displaySimplicityTable(), displaySimplicityTable(), generateRefImage(), lightBetween(), localDualVolume(), main(), main(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), Object3D(), pointsInStandardPlane(), DGtal::HyperRectDomain< TSpace >::rbegin(), DGtal::ImageFactoryFromHDF5< TImageContainer >::requestImage(), SCENARIO(), TEST_CASE(), TEST_CASE(), TEST_CASE(), testBoard2D(), testComparison(), testDigitalSetDomain(), testDigitalSetDraw(), testDisplayDT3d(), testDistanceTransformation3D(), testDistanceTransformND(), testDraw(), testExpander(), testImageAdapter(), testImageOnRef(), testIterator(), testKanungo2D(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testSetFromImage(), testSimplePoints3D(), testVoronoiMap(), and testWriteAndRead().
isEmpty()
template<typename TSpace > bool DGtal::HyperRectDomain< TSpace >::isEmpty () const
Returns
true if the domain is empty.
Referenced by TEST_CASE(), and TEST_CASE().
isInside()
template<typename TSpace > bool DGtal::HyperRectDomain< TSpace >::isInside (const Point & p) const
Parameters
p any point.
Returns
'true' if point [p] is inside this domain.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), main(), main(), and DGtal::HyperRectDomain< TSpace >::rbegin().
isValid()
template<typename TSpace > bool DGtal::HyperRectDomain< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Referenced by TEST_CASE().
lowerBound()
template<typename TSpace > const Point & DGtal::HyperRectDomain< TSpace >::lowerBound () const
Returns the lowest point of the space diagonal.
Referenced by alphaShape(), DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter(), calcPointModuloDomain(), cmpTranslatedFFT(), getComplex(), DGtal::Shortcuts< TKSpace >::getKSpace(), laplace_sphere(), laplacian(), main(), main(), main(), Object3D(), sum_fn_on_domain(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), testCombinatorialSurface(), testDigitalSetBoundary(), testDigitalSetSelector(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testGenericReader(), testIterator(), testIteratorHelperImpl(), testObjectGraph(), testOrderingDigitalSurfaceFacesAroundVertex(), and testUmbrellaComputer().
operator=()
template<typename TSpace > HyperRectDomain & DGtal::HyperRectDomain< TSpace >::operator= (const HyperRectDomain< TSpace > & other)
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
predicate()
template<typename TSpace > const Predicate & DGtal::HyperRectDomain< TSpace >::predicate () const
Returns
a const reference to the "IsInside" predicate.
NB: Could have used template class DomainPredicate but, for performance reason, directly used the IsWithinPointPredicate which fits perfectly.
Referenced by example(), and main().
rbegin() [1/2]
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rbegin () const inline
reverse begin method.
Returns
ConstIterator on the beginning of the reverse range.
Definition at line 210 of file HyperRectDomain.h.
      {
        return ConstReverseIterator(end());
      }
References DGtal::HyperRectDomain< TSpace >::end().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), and testIterator().
rbegin() [2/2]
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rbegin (const Point & aPoint) const inline
reverse begin method from a given point.
Parameters
aPoint the initial point.
Returns
a ConstIterator initialized to aPoint.
Precondition
aPoint must belong to the range.
Definition at line 221 of file HyperRectDomain.h.
      {
        ASSERT_MSG(
            isInside(aPoint) || aPoint == myLowerBound || aPoint == myUpperBound,
            "The point must be inside the domain or be equal to one of his bound."
        );
        ConstIterator it(begin(aPoint)); ++it;
        return ConstReverseIterator(it);
      }
References aPoint(), DGtal::HyperRectDomain< TSpace >::begin(), DGtal::HyperRectDomain< TSpace >::isInside(), DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
rend()
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rend () const inline
reverse end method.
Returns
ConstIterator on the end of the reverse range.
Definition at line 236 of file HyperRectDomain.h.
      {
        return ConstReverseIterator(begin());
      }
References DGtal::HyperRectDomain< TSpace >::begin().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), and testIterator().
selfDisplay()
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
size()
template<typename TSpace > Size DGtal::HyperRectDomain< TSpace >::size () const inline
Returns
the size (number of points) of the HyperRectDomain
Definition at line 565 of file HyperRectDomain.h.
      {
        Size res = 1;
        for(Dimension i=0; i < Space::dimension; ++i)
          res *= static_cast<Size>(NumberTraits<Coordinate>::castToUInt64_t(myUpperBound[i] - myLowerBound[i] + 1));
        return res;
      }
References DGtal::SpaceND< dim, TInteger >::dimension, DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
Referenced by ArrayImageAdapter_example(), main(), main(), main(), moduleImages_example(), SCENARIO(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), test_image(), test_range_constRange(), and testSetFromImage().
subRange() [1/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (const std::vector< Dimension > & permutation) const inline
get a subRange.
Parameters
permutation a vector containing the dimensions used for the subrange. Dimensions are iterated in the given order.
Returns
a sub-range of the domain for the given permutation.
Definition at line 472 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, permutation, myLowerBound);
      }
References DGtal::HyperRectDomain< TSpace >::myLowerBound.
Referenced by DGtal::ImageFactoryFromHDF5< TImageContainer >::flushImage(), main(), TEST_CASE(), TEST_CASE_METHOD(), and testIterator().
subRange() [2/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (const std::vector< Dimension > & permutation, const Point & startingPoint) const inline
get a subRange from an initial point.
Parameters
permutation a vector containing the dimensions used for the subrange. Dimensions are iterated in the given order.
startingPoint the initial point.
Returns
a sub-range of the domain for the given permutation.
Precondition
startingPoint must belong to the range.
Definition at line 485 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, permutation, startingPoint);
      }
subRange() [3/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim, const Point & startingPoint) const inline
get a subRange of one dimension.
Parameters
adim the dimension of the subrange.
startingPoint the initial point.
Returns
a sub-range of the domain for the given dimension.
Precondition
startingPoint must belong to the range.
Definition at line 498 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, adim, startingPoint);
      }
subRange() [4/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim1, Dimension adim2, const Point & startingPoint) const inline
get a subRange of two dimensions.
Parameters
adim1 the first dimension of the subrange.
adim2 the second dimension of the subrange.
startingPoint the initial point.
Returns
a sub-range of the domain for the given two dimensions.
Precondition
startingPoint must belong to the range.
Definition at line 512 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, adim1, adim2, startingPoint);
      }
subRange() [5/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim1, Dimension adim2, Dimension adim3, const Point & startingPoint) const inline
get a subRange of three dimensions.
Parameters
adim1 the first dimension of the subrange.
adim2 the second dimension of the subrange.
adim3 the third dimension of the subrange.
startingPoint the initial point.
Returns
a sub-range of the domain for the given three dimensions.
Precondition
startingPoint must belong to the range.
Definition at line 527 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, adim1, adim2, adim3, startingPoint);
      }
subRange() [6/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (std::initializer_list< Dimension > permutation) inline
get a subRange.
Parameters
permutation an initializer_list containing the dimensions used for the subrange. Dimensions are iterated in the given order.
Returns
a sub-range of the domain for the given permutation.
Definition at line 539 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, permutation, myLowerBound);
      }
References DGtal::HyperRectDomain< TSpace >::myLowerBound.
subRange() [7/7]
template<typename TSpace > ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (std::initializer_list< Dimension > permutation, const Point & startingPoint) inline
get a subRange from an initial point.
Parameters
permutation an initializer_list containing the dimensions used for the subrange. Dimensions are iterated in the given order.
startingPoint the initial point.
Returns
a sub-range of the domain for the given permutation.
Precondition
startingPoint must belong to the range.
Definition at line 552 of file HyperRectDomain.h.
      {
        return ConstSubRange(*this, permutation, startingPoint);
      }
upperBound()
template<typename TSpace > const Point & DGtal::HyperRectDomain< TSpace >::upperBound () const
Returns the highest point of the space diagonal.
Referenced by alphaShape(), DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter(), calcPointModuloDomain(), cmpTranslatedFFT(), getComplex(), DGtal::Shortcuts< TKSpace >::getKSpace(), laplace_sphere(), laplacian(), main(), main(), main(), main(), Object3D(), TEST_CASE(), testCombinatorialSurface(), testDigitalSetBoundary(), testDigitalSetSelector(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testGenericReader(), testIterator(), testIteratorHelperImpl(), testObjectGraph(), testOrderingDigitalSurfaceFacesAroundVertex(), and testUmbrellaComputer().
Field Documentation
myIteratorBegin
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::myIteratorBegin private
Begin iterator.
Definition at line 652 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin().
myIteratorEnd
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::myIteratorEnd private
End iterator.
Definition at line 654 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::end().
myLowerBound
template<typename TSpace > Point DGtal::HyperRectDomain< TSpace >::myLowerBound
The lowest point of the space diagonal.
Definition at line 642 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), DGtal::HyperRectDomain< TSpace >::rbegin(), DGtal::HyperRectDomain< TSpace >::size(), DGtal::HyperRectDomain< TSpace >::subRange(), and DGtal::HyperRectDomain< TSpace >::subRange().
myPredicate
template<typename TSpace > Predicate DGtal::HyperRectDomain< TSpace >::myPredicate private
"IsInside" predicate.
Definition at line 649 of file HyperRectDomain.h.
myUpperBound
template<typename TSpace > Point DGtal::HyperRectDomain< TSpace >::myUpperBound
The highest point of the space diagonal.
Definition at line 644 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), DGtal::HyperRectDomain< TSpace >::rbegin(), and DGtal::HyperRectDomain< TSpace >::size().
The documentation for this class was generated from the following file:
HyperRectDomain.h