DGtal: DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > Class Template Reference
DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > Class Template Reference
Aim: Image adapter for generic arrays with sub-domain view capability.
#include <DGtal/images/ArrayImageAdapter.h>
Public Types
using Self = ArrayImageAdapter<TArrayIterator, HyperRectDomain<TSpace> >
Self type.
using ArrayIterator = TArrayIterator
The given random-access iterator's type.
using Value = typename std::iterator_traits<ArrayIterator>::value_type
The value type stored in the image.
using Reference = typename std::iterator_traits<ArrayIterator>::reference
Mutable reference type.
using ConstReference = const Reference
Constant reference type.
using Domain = HyperRectDomain<TSpace>
Domain type.
using Point = typename Domain::Point
Point type.
using Dimension = typename Domain::Dimension
Dimension type.
using Size = typename Domain::Size
Size type.
using Vector = typename Domain::Vector
Vector type.
using Vertex = Point
Vertex type.
using Integer = typename Domain::Integer
Integer type.
using Linearizer = DGtal::Linearizer<Domain, ColMajorStorage>
Linearization of the points.
using Iterator = typename IteratorCompletionTraits<Self>::Iterator
Mutable iterator based on ArrayImageIterator.
using ConstIterator = typename IteratorCompletionTraits<Self>::ConstIterator
Constant iterator base on ArrayImageIterator.
Public Types inherited from DGtal::IteratorCompletion< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >
typedef IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >::Iterator Iterator
Mutable iterator type.
typedef IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >::ConstIterator ConstIterator
Constant iterator type.
typedef IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >::DistanceFunctor DistanceFunctor
Type of the functor calculating the distance between iterators.
typedef boost::reverse_iterator< Iterator > ReverseIterator
Mutable reverse iterator type.
typedef boost::reverse_iterator< ConstIterator > ConstReverseIterator
Constant reverse iterator type.
typedef SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor > Range
Mutable range type.
typedef SimpleRandomAccessConstRangeFromPoint< ConstIterator, DistanceFunctor > ConstRange
Constant range type.
typedef std::ptrdiff_t Difference
Type of the distance between two iterators.
Public Member Functions
BOOST_STATIC_CONSTANT (Dimension, dimension=Domain::dimension)
Rank of the space.
ArrayImageAdapter ()
ArrayImageAdapter (ArrayIterator anArrayIterator, Domain const &aFullDomain, Domain const &aViewDomain)
ArrayImageAdapter (ArrayIterator anArrayIterator, Domain const &aFullDomain)
ArrayImageAdapter (Self const &other, Domain const &aViewDomain)
Domain domain () const
Domain fullDomain () const
Value getValue (Point const &aPoint) const
void setValue (Point const &aPoint, Value aValue)
Value operator() (Point const &aPoint) const
Iterator begin ()
ConstIterator begin () const
ConstIterator cbegin () const
Iterator end ()
ConstIterator end () const
ConstIterator cend () const
Reference dereference (Point const &, typename Point::Coordinate aFullIndex)
ConstReference dereference (Point const &, typename Point::Coordinate aFullIndex) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::IteratorCompletion< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >
ReverseIterator rbegin ()
ConstReverseIterator rbegin () const
ConstReverseIterator crbegin () const
ReverseIterator rend ()
ConstReverseIterator rend () const
ConstReverseIterator crend () const
Range range ()
ConstRange constRange () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::RandomAccessTraversalConcept< TArrayIterator >))
Private Attributes
ArrayIterator myArrayIterator
Pointer to the allocated memory.
Domain myFullDomain
Definition (full) domain.
Domain myViewDomain
Viewable domain.
Friends
template<class >
class ArrayImageIterator
Additional Inherited Members
Protected Member Functions inherited from DGtal::IteratorCompletion< ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > > >
~IteratorCompletion ()
Protected destructor to avoid memory leak.
Detailed Description
template<typename TArrayIterator, typename TSpace>
class DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >
Aim: Image adapter for generic arrays with sub-domain view capability.
Description of template class 'ArrayImageAdapter'
This creates an image (concepts::CImage compatible) given a random-access iterator (that can be a T* pointer) that fully spans an array of data, and two domains:
the definition (full) domain whose size is equal to the data size.
the viewable domain, a subset of the full-domain, on which the image is accessible. This adapted image is writable iff the given iterator is mutable.
The available iterators for this image can return the corresponding point and are faster than using an iterator over the domain (see ArrayImageIterator). Reverse iterators and ranges are defined in the inherited class IteratorCompletion.
Some helpers are available (see makeArrayImageAdapterFromIterator and makeArrayImageAdapterFromImage) for easy construction (with template deduction) from an iterator or an CConstImage model.
It is important to note that, since this class only adapts an already existing storage to an image, all copy operations (constructor and operator) lead to shallow copies.
The following code snippet demonstrates how to use ArrayImageAdapter from converting a native C-array to an image:
  using Space = SpaceND<2>;
  using Domain = HyperRectDomain<Space>;
  using Point = Domain::Point;
  using Value = double;
  const Domain domain( Point(0, 1), Point(4, 3) );
  Value* data = new Value[ domain.size() ];
  // Convert this allocated memory to a CImage model.
  ArrayImageAdapter< Value*, Domain > image( data, domain );
  // Alternative syntax using the helpers:
  // auto image = makeArrayImageAdapterFromIterator( data, domain );
  // Fill the image with first coordinate of the point
  for ( auto it = image.begin(); it != image.end(); ++it )
    {
      *it = it.getPoint()[0];
    }
  // Get a constant view on a sub-domain.
  const Domain sub_domain( Point(1, 1), Point(3, 2) );
  ArrayImageAdapter< Value const*, Domain > cst_image( data, domain, sub_domain );
  // Alternative syntax using the helpers:
  // auto const cst_image = makeArrayImageAdapterFromImage( image, sub_domain );
  // Display it.
  for ( auto value : cst_image )
    {
      std::cout << value << " ";
    }
  std::cout << std::endl;
Another usage example is illustrated in the image module documentation, ArrayImageAdapter.
Remarks
The given random-access iterator can be either mutable or constant.
Warning
The array must be column-major ordered (but row-major order could be later accepted via template parameter, if needed ?)
The domain must be an HyperRectDomain.
Template Parameters
TArrayIterator Type of a random-access iterator over the datas (can be a T* pointer).
TSpace Type of the space associated to the HyperRectDomain (auto-deduced from TDomain template, see ArrayImageAdapter).
See also
makeArrayImageAdapterFromIterator
makeArrayImageAdapterFromImage
exampleArrayImageAdapter.cpp
Definition at line 116 of file ArrayImageAdapter.h.
Member Typedef Documentation
ArrayIterator
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayIterator = TArrayIterator
The given random-access iterator's type.
Definition at line 126 of file ArrayImageAdapter.h.
ConstIterator
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ConstIterator = typename IteratorCompletionTraits<Self>::ConstIterator
Constant iterator base on ArrayImageIterator.
Definition at line 146 of file ArrayImageAdapter.h.
ConstReference
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ConstReference = const Reference
Constant reference type.
Definition at line 129 of file ArrayImageAdapter.h.
Dimension
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Dimension = typename Domain::Dimension
Dimension type.
Definition at line 134 of file ArrayImageAdapter.h.
Domain
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Domain = HyperRectDomain<TSpace>
Domain type.
Definition at line 132 of file ArrayImageAdapter.h.
Integer
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Integer = typename Domain::Integer
Integer type.
Definition at line 138 of file ArrayImageAdapter.h.
Iterator
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Iterator = typename IteratorCompletionTraits<Self>::Iterator
Mutable iterator based on ArrayImageIterator.
Definition at line 145 of file ArrayImageAdapter.h.
Linearizer
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Linearizer = DGtal::Linearizer<Domain, ColMajorStorage>
Linearization of the points.
Definition at line 141 of file ArrayImageAdapter.h.
Point
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Point = typename Domain::Point
Point type.
Definition at line 133 of file ArrayImageAdapter.h.
Reference
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Reference = typename std::iterator_traits<ArrayIterator>::reference
Mutable reference type.
Definition at line 128 of file ArrayImageAdapter.h.
Self
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Self = ArrayImageAdapter<TArrayIterator, HyperRectDomain<TSpace> >
Self type.
Definition at line 125 of file ArrayImageAdapter.h.
Size
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Size = typename Domain::Size
Size type.
Definition at line 135 of file ArrayImageAdapter.h.
Value
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Value = typename std::iterator_traits<ArrayIterator>::value_type
The value type stored in the image.
Definition at line 127 of file ArrayImageAdapter.h.
Vector
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Vector = typename Domain::Vector
Vector type.
Definition at line 136 of file ArrayImageAdapter.h.
Vertex
template<typename TArrayIterator , typename TSpace > using DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::Vertex = Point
Vertex type.
Definition at line 137 of file ArrayImageAdapter.h.
Constructor & Destructor Documentation
ArrayImageAdapter() [1/4]
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter () inline
Default constructor.
Empty allocated memory on empty domains.
Definition at line 152 of file ArrayImageAdapter.h.
        : myArrayIterator{nullptr}
        , myFullDomain{}
        , myViewDomain{}
        {}
ArrayImageAdapter() [2/4]
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter (ArrayIterator anArrayIterator, Domain const & aFullDomain, Domain const & aViewDomain) inline
Constructor from iterator, full domain and viewable domain.
Parameters
anArrayIterator A random-access iterator on the datas.
aFullDomain The domain span by the given iterator.
aViewDomain The viewable domain of this image.
Definition at line 164 of file ArrayImageAdapter.h.
          : myArrayIterator(anArrayIterator)
          , myFullDomain{ aFullDomain }
          , myViewDomain{ aViewDomain }
        {
          ASSERT_MSG(
                 aFullDomain.lowerBound().isLower( aViewDomain.lowerBound() )
              && aFullDomain.upperBound().isUpper( aViewDomain.upperBound() ),
              "The viewable domain must be included into the full domain."
          );
        }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::isLower(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::isUpper(), DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
ArrayImageAdapter() [3/4]
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter (ArrayIterator anArrayIterator, Domain const & aFullDomain) inline
Constructor from iterator and full domain.
The viewable domain is then the full domain.
Parameters
anArrayIterator A random-access iterator on the datas.
aFullDomain The domain span by the given iterator.
Definition at line 183 of file ArrayImageAdapter.h.
          : ArrayImageAdapter( anArrayIterator, aFullDomain, aFullDomain )
        {
        }
ArrayImageAdapter() [4/4]
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::ArrayImageAdapter (Self const & other, Domain const & aViewDomain) inline
Copy constructor with other viewable domain.
The full domain will be the same as the copied ArrayImageAdapter. Only the viewable domain will be modified.
Warning
Since this class in only a view on a independant storage, it does a shallow copy.
Parameters
other An another ArrayImageAdapter instance.
aViewDomain A new viewable domain for this image.
Definition at line 197 of file ArrayImageAdapter.h.
          : ArrayImageAdapter( other.myArrayIterator, other.myFullDomain, aViewDomain )
        {}
Member Function Documentation
begin() [1/2]
template<typename TArrayIterator , typename TSpace > Iterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::begin () inline
Returns
a mutable iterator pointing to the lower bound of the viewable domain.
Definition at line 266 of file ArrayImageAdapter.h.
        {
          return Iterator{ this, myFullDomain, myViewDomain };
        }
begin() [2/2]
template<typename TArrayIterator , typename TSpace > ConstIterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::begin () const inline
Returns
a constant iterator pointing to the lower bound of the viewable domain.
Definition at line 275 of file ArrayImageAdapter.h.
        {
          return ConstIterator{ this, myFullDomain, myViewDomain };
        }
BOOST_CONCEPT_ASSERT()
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::BOOST_CONCEPT_ASSERT ((boost_concepts::RandomAccessTraversalConcept< TArrayIterator >)) private
BOOST_STATIC_CONSTANT()
template<typename TArrayIterator , typename TSpace > DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::BOOST_STATIC_CONSTANT (Dimension , dimension = Domain::dimension)
Rank of the space.
cbegin()
template<typename TArrayIterator , typename TSpace > ConstIterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::cbegin () const inline
Returns
a constant iterator pointing to the lower bound of the viewable domain.
Definition at line 284 of file ArrayImageAdapter.h.
        {
          return ConstIterator{ this, myFullDomain, myViewDomain };
        }
cend()
template<typename TArrayIterator , typename TSpace > ConstIterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::cend () const inline
Returns
a constant iterator pointing after the upper bound of the viewable domain.
Definition at line 311 of file ArrayImageAdapter.h.
        {
          return ConstIterator{ this, myFullDomain, myViewDomain, true };
        }
dereference() [1/2]
template<typename TArrayIterator , typename TSpace > Reference DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::dereference (Point const & , typename Point::Coordinate aFullIndex) inline
Dereference of a mutable iterator.
Parameters
[in] aFullIndex Linearized index of the point.
Returns
a mutable reference to the value associated to the point.
Definition at line 325 of file ArrayImageAdapter.h.
        {
          ASSERT_MSG(
              aFullIndex >= 0 && static_cast<typename Domain::Size>(aFullIndex) < myFullDomain.size(),
              "linearized index out of bounds !"
          );
          return myArrayIterator[aFullIndex];
        }
dereference() [2/2]
template<typename TArrayIterator , typename TSpace > ConstReference DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::dereference (Point const & , typename Point::Coordinate aFullIndex) const inline
Dereference of a constant iterator.
Parameters
[in] aFullIndex Linearized index of the point.
Returns
a constant reference to the value associated to the point.
Definition at line 340 of file ArrayImageAdapter.h.
        {
          ASSERT_MSG(
              aFullIndex >= 0 && static_cast<typename Domain::Size>(aFullIndex) < myFullDomain.size(),
              "linearized index out of bounds !"
          );
          return myArrayIterator[aFullIndex];
        }
domain()
template<typename TArrayIterator , typename TSpace > Domain DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::domain () const inline
Returns
the image viewable domain.
Definition at line 205 of file ArrayImageAdapter.h.
        {
          return myViewDomain;
        }
end() [1/2]
template<typename TArrayIterator , typename TSpace > Iterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::end () inline
Returns
an mutable iterator pointing after the upper bound of the viewable domain.
Definition at line 293 of file ArrayImageAdapter.h.
        {
          return Iterator{ this, myFullDomain, myViewDomain, true };
        }
end() [2/2]
template<typename TArrayIterator , typename TSpace > ConstIterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::end () const inline
Returns
a constant iterator pointing after the upper bound of the viewable domain.
Definition at line 302 of file ArrayImageAdapter.h.
        {
          return ConstIterator{ this, myFullDomain, myViewDomain, true };
        }
fullDomain()
template<typename TArrayIterator , typename TSpace > Domain DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::fullDomain () const inline
Returns
the full domain where the allocated memory is defined.
Definition at line 214 of file ArrayImageAdapter.h.
        {
          return myFullDomain;
        }
getValue()
template<typename TArrayIterator , typename TSpace > Value DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::getValue (Point const & aPoint) const inline
Reads a value given a point lying inside the full domain.
Parameters
[in] aPoint The point.
Returns
a constant value.
Definition at line 225 of file ArrayImageAdapter.h.
        {
          ASSERT_MSG(
              myFullDomain.isInside(aPoint),
              "The point is outside the full domain."
          );
          return myArrayIterator[ Linearizer::getIndex(aPoint, myFullDomain) ];
        }
References aPoint().
isValid()
template<typename TArrayIterator , typename TSpace > bool DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 364 of file ArrayImageAdapter.h.
        {
          return true;
        }
operator()()
template<typename TArrayIterator , typename TSpace > Value DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::operator() (Point const & aPoint) const inline
Reads a value given a point lying inside the full domain.
Parameters
[in] aPoint The point.
Returns
a constant value.
Definition at line 257 of file ArrayImageAdapter.h.
        {
          return getValue(aPoint);
        }
References aPoint().
selfDisplay()
template<typename TArrayIterator , typename TSpace > void DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 355 of file ArrayImageAdapter.h.
        {
          out << "[ArrayImageAdapter] with full domain " << myFullDomain << " and viewable domain " << myViewDomain;
        }
setValue()
template<typename TArrayIterator , typename TSpace > void DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::setValue (Point const & aPoint, Value aValue) inline
Sets a value given a point lying inside the full domain.
Parameters
[in] aPoint The point.
[in] aValue The value.
Definition at line 241 of file ArrayImageAdapter.h.
        {
          ASSERT_MSG(
              myFullDomain.isInside(aPoint),
              "The point is outside the full domain."
          );
          myArrayIterator[ Linearizer::getIndex(aPoint, myFullDomain) ] = aValue;
        }
References aPoint().
Friends And Related Symbol Documentation
ArrayImageIterator
template<typename TArrayIterator , typename TSpace > template<class > friend class ArrayImageIterator friend
Definition at line 144 of file ArrayImageAdapter.h.
Field Documentation
myArrayIterator
template<typename TArrayIterator , typename TSpace > ArrayIterator DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::myArrayIterator private
Pointer to the allocated memory.
Definition at line 371 of file ArrayImageAdapter.h.
myFullDomain
template<typename TArrayIterator , typename TSpace > Domain DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::myFullDomain private
Definition (full) domain.
Definition at line 372 of file ArrayImageAdapter.h.
myViewDomain
template<typename TArrayIterator , typename TSpace > Domain DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::myViewDomain private
Viewable domain.
Definition at line 373 of file ArrayImageAdapter.h.
The documentation for this class was generated from the following file:
ArrayImageAdapter.h