DGtal: DGtal::MPolynomial< n, TRing, TAlloc > Class Template Reference
DGtal::MPolynomial< n, TRing, TAlloc > Class Template Reference
Aim: Represents a multivariate polynomial, i.e. an element of \(K[X_0, ..., X_{n-1}] \), where K is some ring or field.
#include <DGtal/math/MPolynomial.h>
Public Types
typedef TRing Ring
typedef TAlloc Alloc
typedef MPolynomial< n - 1, Ring, Alloc > MPolyNM1
typedef IVector< MPolyNM1, typename Alloc::template rebind< MPolyNM1 >::other,(n >1) > Storage
typedef Storage::Size Size
Public Member Functions
void normalize ()
MPolynomial (const Alloc &allocator=Alloc())
MPolynomial (const Ring &v, const Alloc &allocator=Alloc())
MPolynomial (const MPolyNM1 &pdm1, const Alloc &)
template<typename Ring2 , typename Alloc2 >
MPolynomial (const MPolynomial< n, Ring2, Alloc2 > &p, const Alloc &allocator=Alloc())
template<typename Ring2 , typename Alloc2 >
MPolynomial & operator= (const MPolynomial< n, Ring2, Alloc2 > &p)
void swap (MPolynomial &p)
Alloc getAllocator () const
int degree () const
const MPolyNM1 & leading () const
bool isZero () const
MPolyNM1 & operator[] (Size i)
const MPolyNM1 & operator[] (Size i) const
MPolynomialEvaluator< n, Ring, Alloc, Ring > operator() (const Ring &x) const
template<typename Ring2 >
MPolynomialEvaluator< n, Ring, Alloc, Ring2 > operator() (const Ring2 &x) const
MPolynomial operator* (const Ring &v) const
MPolynomial operator/ (const Ring &v) const
MPolynomial & operator*= (const MPolynomial &p)
MPolynomial & operator*= (const Ring &v)
MPolynomial & operator/= (const Ring &v)
MPolynomial operator- () const
MPolynomial operator+ (const MPolynomial &q) const
MPolynomial operator- (const MPolynomial &q) const
MPolynomial & operator+= (const MPolynomial &q)
MPolynomial & operator-= (const MPolynomial &q)
MPolynomial operator+ (const MPolyNM1 &q) const
MPolynomial operator- (const MPolyNM1 &q) const
MPolynomial operator+ (const Ring &v) const
MPolynomial operator- (const Ring &v) const
MPolynomial & operator+= (const MPolyNM1 &q)
MPolynomial & operator-= (const MPolyNM1 &q)
MPolynomial & operator+= (const Ring &v)
MPolynomial & operator-= (const Ring &v)
MPolynomial operator* (const MPolynomial &p) const
bool operator== (const MPolynomial &q) const
bool operator!= (const MPolynomial &q) const
bool operator== (const Ring &v) const
bool operator!= (const Ring &v) const
void selfDisplay (std::ostream &s, int N=n) const
bool isValid () const
Private Member Functions
MPolynomial (bool, Size s, const Alloc &)
Private Attributes
Storage myValue
Static Private Attributes
static MPolyNM1 myZeroPolynomial
The zero polynomial of n-1 variables for a n-multivariate polynomial.
Friends
template<int NN, int nn, typename TT , typename AA >
class MPolynomialDerivativeComputer
template<int nn, typename TT , typename AA , typename SS >
class MPolynomialEvaluator
template<int nn, typename TT , typename HLHL , typename AA , typename SS >
class MPolynomialEvaluatorImpl
void euclidDiv (const MPolynomial< 1, TRing, TAlloc > &f, const MPolynomial< 1, TRing, TAlloc > &g, MPolynomial< 1, TRing, TAlloc > &q, MPolynomial< 1, TRing, TAlloc > &r)
MPolynomial operator* (const Ring &v, const MPolynomial &p)
Detailed Description
template<int n, typename TRing, class TAlloc>
class DGtal::MPolynomial< n, TRing, TAlloc >
Aim: Represents a multivariate polynomial, i.e. an element of \(K[X_0, ..., X_{n-1}] \), where K is some ring or field.
Description of template class 'MPolynomial'
Monomials are products of power of variables, like xy^2z^3. Polynomials in n variables are constructed recursively with polynomials in n - 1 variables.
There is a specialization for polynomials with no indeterminates, i.e. constants.
See also
dgtal_multivariate_polynomial
Template Parameters
n the number of variables or indeterminates.
TRing the type chosen for the polynomial, defines also the type of the coefficents (generally int, float or double).
TAlloc is an allocator for TRing, for example std::allocator<TRing>; this is also the default parameter. Usually this parameter does not needs to be changed.
This class is a backport from Spielwiese.
Author
Felix Fontein (felix.nosp@m.@fon.nosp@m.tein..nosp@m.de), University of Zurich, Switzerland
Examples
math/polynomial-derivative.cpp, math/polynomial-read.cpp, math/polynomial2-derivative.cpp, and topology/trackImplicitPolynomialSurfaceToOFF.cpp.
Definition at line 964 of file MPolynomial.h.
Member Typedef Documentation
Alloc
template<int n, typename TRing , class TAlloc > TAlloc DGtal::MPolynomial< n, TRing, TAlloc >::Alloc
Definition at line 985 of file MPolynomial.h.
MPolyNM1
template<int n, typename TRing , class TAlloc > MPolynomial< n - 1, Ring, Alloc > DGtal::MPolynomial< n, TRing, TAlloc >::MPolyNM1
Definition at line 986 of file MPolynomial.h.
Ring
template<int n, typename TRing , class TAlloc > TRing DGtal::MPolynomial< n, TRing, TAlloc >::Ring
Definition at line 984 of file MPolynomial.h.
Size
template<int n, typename TRing , class TAlloc > Storage::Size DGtal::MPolynomial< n, TRing, TAlloc >::Size
Definition at line 996 of file MPolynomial.h.
Storage
template<int n, typename TRing , class TAlloc > IVector< MPolyNM1, typename Alloc::template rebind<MPolyNM1 >::other, (n>1) > DGtal::MPolynomial< n, TRing, TAlloc >::Storage
The type for the vector storing polynomials coefficients. For 0 or 1 variables, uses a standard vector, for more variables, uses a specific vector of pointers to polynomials, with adequate allocators. This is for efficiency purposes.
Definition at line 995 of file MPolynomial.h.
Constructor & Destructor Documentation
MPolynomial() [1/5]
template<int n, typename TRing , class TAlloc > DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial (bool , Size s, const Alloc &) inline private
Private constructor for initializing an array of size s.
Definition at line 1014 of file MPolynomial.h.
      : myValue(s)
    {}
Referenced by DGtal::MPolynomial< 0, TRing, TAlloc >::operator*(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator+(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator-(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator-(), and DGtal::MPolynomial< 0, TRing, TAlloc >::operator/().
MPolynomial() [2/5]
template<int n, typename TRing , class TAlloc > DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial (const Alloc & allocator = Alloc()) inline
Constructs a zero polynomial
Definition at line 1045 of file MPolynomial.h.
      : myValue( allocator )
    {}
MPolynomial() [3/5]
template<int n, typename TRing , class TAlloc > DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial (const Ring & v, const Alloc & allocator = Alloc()) inline
Constructs a constant polynomial with constant term v.
Definition at line 1052 of file MPolynomial.h.
      : myValue( 1, MPolyNM1( v ), allocator )
    {}
MPolynomial() [4/5]
template<int n, typename TRing , class TAlloc > DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial (const MPolyNM1 & pdm1, const Alloc &) inline
Constructs a polynomial of type MPolynomial<n, Ring> which is initialized with a polynomial of type MPolynomial<n-1, Ring>.
Definition at line 1060 of file MPolynomial.h.
      : myValue( 1, pdm1 )
    {}
MPolynomial() [5/5]
template<int n, typename TRing , class TAlloc > template<typename Ring2 , typename Alloc2 > DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial (const MPolynomial< n, Ring2, Alloc2 > & p, const Alloc & allocator = Alloc()) inline
Casts a polynomial of type MPolynomial<n, Ring2, Alloc2> to a polynomial of type MPolynomial<n, Ring, Alloc>.
Definition at line 1070 of file MPolynomial.h.
      : myValue( p.degree() + 1, MPolyNM1(), allocator )
    {
      for ( Size i = 0; i < myValue.size(); ++i )
        myValue[i] = p[i];
      normalize();
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
Member Function Documentation
degree()
template<int n, typename TRing , class TAlloc > int DGtal::MPolynomial< n, TRing, TAlloc >::degree () const inline
Returns
the degree of this polynomial. If this is the zero polynomial, the degree is -1.
Definition at line 1119 of file MPolynomial.h.
    {
      return (int)(myValue.size() - 1);
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
Referenced by DGtal::EhrhartPolynomial< TSpace, TInteger >::countInterior(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*(), DGtal::EhrhartPolynomial< TSpace, TInteger >::remainderInterior(), and testMPolynomial().
getAllocator()
template<int n, typename TRing , class TAlloc > Alloc DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator () const inline
Returns
the allocator for this object.
Definition at line 1107 of file MPolynomial.h.
    {
        return myValue.getAllocator();
    }
References DGtal::IVector< T, TAlloc, usePointers >::getAllocator(), and DGtal::MPolynomial< n, TRing, TAlloc >::myValue.
Referenced by DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*(), and DGtal::MPolynomial< n, TRing, TAlloc >::operator-().
isValid()
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
isZero()
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::isZero () const inline
Tests whether this polynomial is the zero polynomial.
Definition at line 1137 of file MPolynomial.h.
    {
      return myValue.size() == 0;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
Referenced by DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*(), and DGtal::MPolynomial< n, TRing, TAlloc >::selfDisplay().
leading()
template<int n, typename TRing , class TAlloc > const MPolyNM1 & DGtal::MPolynomial< n, TRing, TAlloc >::leading () const inline
Returns
the leading term (of type MPolynomial<n-1, Ring>) of the first indeterminate. Returns 0 (of type MPolynomial<n-1, Ring>) in case of the zero polynomial.
Definition at line 1129 of file MPolynomial.h.
    {
      return myValue.size() ? myValue.back() : myZeroPolynomial;
    }
References DGtal::IVector< T, TAlloc, usePointers >::back(), DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::myZeroPolynomial, and DGtal::IVector< T, TAlloc, usePointers >::size().
Referenced by testMPolynomial().
normalize()
template<int n, typename TRing , class TAlloc > void DGtal::MPolynomial< n, TRing, TAlloc >::normalize () inline
Adjusts the size of myValue that the leading term and degree can be computed trivially. This must be called only after calls to the non-const operator[], in which the degree of the polynomial has potentially been changed.
Definition at line 1025 of file MPolynomial.h.
    {
      Size dp1 = myValue.size();
      while ( dp1 )
        {
          if (myValue[dp1 - 1].isZero())
            --dp1;
          else
            break;
        }
      if (dp1 < myValue.size())
        myValue.resize(dp1);
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::isZero(), DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
Referenced by DGtal::MPolynomialDerivativeComputer< N, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomialDerivativeComputer< 0, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), and DGtal::MPolynomial< n, TRing, TAlloc >::operator=().
operator!=() [1/2]
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::operator!= (const MPolynomial< n, TRing, TAlloc > & q) const inline
Inequality operator.
Parameters
q any polynomial of the same type as this.
Returns
'true' iff this polynomial is different from q.
Definition at line 1505 of file MPolynomial.h.
    {
      return !(*this == q);
    }
operator!=() [2/2]
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::operator!= (const Ring & v) const inline
Inequality operator with a constant.
Parameters
v any value in the ring.
Returns
'true' iff this polynomial is different from v.
Definition at line 1529 of file MPolynomial.h.
    {
      return !(*this == v);
    }
operator()() [1/2]
template<int n, typename TRing , class TAlloc > MPolynomialEvaluator< n, Ring, Alloc, Ring > DGtal::MPolynomial< n, TRing, TAlloc >::operator() (const Ring & x) const inline
Evaluation in x.
Parameters
x a value in the ring.
Returns
a functor for performing this evaluation
Definition at line 1169 of file MPolynomial.h.
    {
      return MPolynomialEvaluator<n, Ring, Alloc, Ring>( *this, x );
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomialEvaluator.
operator()() [2/2]
template<int n, typename TRing , class TAlloc > template<typename Ring2 > MPolynomialEvaluator< n, Ring, Alloc, Ring2 > DGtal::MPolynomial< n, TRing, TAlloc >::operator() (const Ring2 & x) const inline
Evaluation in x of type Ring2.
Template Parameters
Ring2 another ring (like a polynomial with less variables).
Parameters
x a value in this ring.
Returns
a functor for performing this evaluation
Definition at line 1183 of file MPolynomial.h.
    {
      return MPolynomialEvaluator<n, Ring, Alloc, Ring2>( *this, x );
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomialEvaluator.
operator*() [1/2]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator* (const MPolynomial< n, TRing, TAlloc > & p) const inline
Multiplies the polynomial with another polynomial.
Parameters
p any polynomial of the same type.
Returns
the corresponding polynomial.
Todo
Multiplication could be optimized for monovariate polynomials.
Definition at line 1467 of file MPolynomial.h.
    {
      int d = p.degree() + degree();
      if (d < -1)
        d = -1;
      MPolynomial r( true, d + 1, getAllocator() );
      if (!isZero() && !p.isZero())
        for ( Size i = 0; i < r.myValue.size(); ++i )
          for ( Size j = 0; j < myValue.size(); ++j )
            if (i < j + p.myValue.size())
              r[i] += myValue[j] * p[i - j];
      r.normalize();
      return r;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::degree(), DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator(), DGtal::MPolynomial< n, TRing, TAlloc >::isZero(), DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator*() [2/2]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator* (const Ring & v) const inline
Multiply by constant.
Parameters
v any value in the ring.
Returns
the corresponding polynomial.
Definition at line 1196 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      for ( Size i = 0; i < myValue.size(); ++i )
        r[i] *= v;
      return r;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator*=() [1/2]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator*= (const MPolynomial< n, TRing, TAlloc > & p) inline
Self-multiplication by other polynomial.
Parameters
p any polynomial of the same type.
Returns
a reference to this.
Definition at line 1222 of file MPolynomial.h.
    {
      return *this = *this * p;
    }
operator*=() [2/2]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator*= (const Ring & v) inline
Self-multiplication by a constant.
Parameters
v any value in the ring.
Returns
a reference to this.
Definition at line 1232 of file MPolynomial.h.
    {
      MPolynomial r( *this );
      for ( Size i = 0; i < myValue.size(); ++i )
        myValue[i] *= v;
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator+() [1/3]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator+ (const MPolyNM1 & q) const inline
Computes the sum of this polynomial with a polynomial with one less variable.
Parameters
q any polynomial with n-1 indeterminates in the same ring.
Returns
the corresponding polynomial.
Definition at line 1346 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < 1)
        r.myValue.resize(1);
      r[0] += q;
      r.normalize();
      return r;
    }
operator+() [2/3]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator+ (const MPolynomial< n, TRing, TAlloc > & q) const inline
Computes the sum of two polynomials.
Parameters
q any polynomial of this type.
Returns
the corresponding polynomial.
Definition at line 1283 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < q.myValue.size())
        r.myValue.resize(q.myValue.size());
      for ( Size i = 0; i < q.myValue.size(); ++i )
        r[i] += q[i];
      r.normalize();
      return r;
    }
operator+() [3/3]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator+ (const Ring & v) const inline
Addition with a constant.
Parameters
v any value in the ring.
Returns
the corresponding polynomial.
Definition at line 1377 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < 1)
        r.myValue.resize(1);
      r[0] += v;
      r.normalize();
      return r;
    }
operator+=() [1/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator+= (const MPolyNM1 & q) inline
Self-addition of this polynomial with a polynomial with one less variable.
Parameters
q any polynomial with n-1 indeterminates in the same ring.
Returns
a reference to this.
Definition at line 1408 of file MPolynomial.h.
    {
      if (myValue.size() < 1)
        myValue.resize(1);
      myValue[0] += q;
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator+=() [2/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator+= (const MPolynomial< n, TRing, TAlloc > & q) inline
Adds q to this polynomial.
Parameters
q any polynomial of this type.
Returns
a reference to this.
Definition at line 1315 of file MPolynomial.h.
    {
      if (myValue.size() < q.myValue.size())
        myValue.resize(q.myValue.size());
      for ( Size i = 0; i < q.myValue.size(); ++i )
        myValue[i] += q[i];
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator+=() [3/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator+= (const Ring & v) inline
Self-addition of a constant.
Parameters
v any value in the ring.
Returns
a reference to this.
Definition at line 1437 of file MPolynomial.h.
    {
      if (myValue.size() < 1)
        myValue.resize(1);
      myValue[0] += v;
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator-() [1/4]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator- () const inline
Returns
the additive inverse of the polynomial.
Definition at line 1270 of file MPolynomial.h.
    {
      MPolynomial r( true, myValue.size(), getAllocator() );
      for ( Size i = 0; i < myValue.size(); ++i )
        r[i] = -myValue[i];
      return r;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator(), DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator-() [2/4]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator- (const MPolyNM1 & q) const inline
Computes the difference of this polynomial with a polynomial with one less variable.
Parameters
q any polynomial with n-1 indeterminates in the same ring.
Returns
the corresponding polynomial.
Definition at line 1362 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < 1)
        r.myValue.resize(1);
      r[0] -= q;
      r.normalize();
      return r;
    }
operator-() [3/4]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator- (const MPolynomial< n, TRing, TAlloc > & q) const inline
Computes the difference of two polynomials.
Parameters
q any polynomial of this type.
Returns
the corresponding polynomial.
Definition at line 1299 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < q.myValue.size())
        r.myValue.resize(q.myValue.size());
      for ( Size i = 0; i < q.myValue.size(); ++i )
        r[i] -= q[i];
      r.normalize();
      return r;
    }
operator-() [4/4]
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator- (const Ring & v) const inline
Difference to a constant.
Parameters
v any value in the ring.
Returns
the corresponding polynomial.
Definition at line 1392 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      if (r.myValue.size() < 1)
        r.myValue.resize(1);
      r[0] -= v;
      r.normalize();
      return r;
    }
operator-=() [1/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator-= (const MPolyNM1 & q) inline
Self-subtraction of this polynomial with a polynomial with one less variable.
Parameters
q any polynomial with n-1 indeterminates in the same ring.
Returns
a reference to this.
Definition at line 1423 of file MPolynomial.h.
    {
      if (myValue.size() < 1)
        myValue.resize(1);
      myValue[0] -= q;
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator-=() [2/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator-= (const MPolynomial< n, TRing, TAlloc > & q) inline
Subtracts q from this polynomial.
Parameters
q any polynomial of this type.
Returns
a reference to this.
Definition at line 1330 of file MPolynomial.h.
    {
      if (myValue.size() < q.myValue.size())
        myValue.resize(q.myValue.size());
      for ( Size i = 0; i < q.myValue.size(); ++i )
        myValue[i] -= q[i];
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator-=() [3/3]
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator-= (const Ring & v) inline
Self-subtraction of a constant.
Parameters
v any value in the ring.
Returns
a reference to this.
Definition at line 1451 of file MPolynomial.h.
    {
      if (myValue.size() < 1)
        myValue.resize(1);
      myValue[0] -= v;
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator/()
template<int n, typename TRing , class TAlloc > MPolynomial DGtal::MPolynomial< n, TRing, TAlloc >::operator/ (const Ring & v) const inline
Divide by constant.
Parameters
v any value in the ring.
Returns
the corresponding polynomial.
Definition at line 1209 of file MPolynomial.h.
    {
      MPolynomial r(*this);
      for ( Size i = 0; i < myValue.size(); ++i )
        r[i] /= v;
      return r;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator/=()
template<int n, typename TRing , class TAlloc > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator/= (const Ring & v) inline
Self-division by a constant.
Parameters
v any value in the ring.
Returns
a reference to this.
Definition at line 1245 of file MPolynomial.h.
    {
      for ( Size i = 0; i < myValue.size(); ++i )
        myValue[i] /= v;
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator=()
template<int n, typename TRing , class TAlloc > template<typename Ring2 , typename Alloc2 > MPolynomial & DGtal::MPolynomial< n, TRing, TAlloc >::operator= (const MPolynomial< n, Ring2, Alloc2 > & p) inline
Copies a polynomial of type MPolynomial<n, Ring2, Alloc2> to this polynomial (of type MPolynomial<n, Ring, Alloc>).
Definition at line 1085 of file MPolynomial.h.
    {
      myValue.resize(p.degree() + 1);
      for ( Size i = 0; i < myValue.size(); ++i )
        myValue[i] = p[i];
      normalize();
      return *this;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator==() [1/2]
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::operator== (const MPolynomial< n, TRing, TAlloc > & q) const inline
Equality operator.
Parameters
q any polynomial of the same type as this.
Returns
'true' iff this polynomial is equal to q.
Definition at line 1490 of file MPolynomial.h.
    {
      if (myValue.size() != q.myValue.size())
        return false;
      for (Size i = 0; i < myValue.size(); ++i)
        if (myValue[i] != q[i])
          return false;
      return true;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator==() [2/2]
template<int n, typename TRing , class TAlloc > bool DGtal::MPolynomial< n, TRing, TAlloc >::operator== (const Ring & v) const inline
Equality operator with a constant.
Parameters
v any value in the ring.
Returns
'true' iff this polynomial is equal to v.
Definition at line 1515 of file MPolynomial.h.
    {
      if ((v == 0) && (myValue.size() == 0))
        return true;
      if (myValue.size() != 1)
        return false;
      return myValue[0] == v;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator[]() [1/2]
template<int n, typename TRing , class TAlloc > MPolyNM1 & DGtal::MPolynomial< n, TRing, TAlloc >::operator[] (Size i) inline
Returns
a reference to the i-th coefficient. If i > degree(), the array myValue is enlarged. Afterwards, one should better call normalize() to make sure future operations are correct.
Definition at line 1147 of file MPolynomial.h.
    {
      if (i >= myValue.size())
        myValue.resize(i + 1);
      return myValue[i];
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::IVector< T, TAlloc, usePointers >::resize(), and DGtal::IVector< T, TAlloc, usePointers >::size().
operator[]() [2/2]
template<int n, typename TRing , class TAlloc > const MPolyNM1 & DGtal::MPolynomial< n, TRing, TAlloc >::operator[] (Size i) const inline
Returns
a reference to the i-th coefficient, or zero if i > degree().
Definition at line 1157 of file MPolynomial.h.
    {
      return i < myValue.size() ? myValue[i] : myZeroPolynomial;
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, DGtal::MPolynomial< n, TRing, TAlloc >::myZeroPolynomial, and DGtal::IVector< T, TAlloc, usePointers >::size().
selfDisplay()
template<int n, typename TRing , class TAlloc > void DGtal::MPolynomial< n, TRing, TAlloc >::selfDisplay (std::ostream & s, int N = n) const inline
Prints this polynomial to the stream s. N gives the number of variables; this is needed for recursive printing.
Parameters
s the output stream where the object is written.
N the number of variables.
Definition at line 1546 of file MPolynomial.h.
    {
      if (isZero())
        s << (Ring) 0;
      else
        {
          Size nonzero = 0;
          for (Size i = 0; i < myValue.size(); ++i)
            if (!myValue[i].isZero())
              ++nonzero;
          if (nonzero > 1) s << "(";
          bool first = true;
          for (Size i = 0; i < myValue.size(); ++i)
            if (!myValue[i].isZero())
              {
                if (first) first = false;
                else       s << " + ";
                myValue[i].selfDisplay(s, N);
                if (i > 0)
                  {
                    s << " ";
                    s << "X_" << N - n;
                    if (i > 1) s << "^" << i;
                  }
              }
          if (nonzero > 1)
            s << ")";
        }
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::isZero(), DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
swap()
template<int n, typename TRing , class TAlloc > void DGtal::MPolynomial< n, TRing, TAlloc >::swap (MPolynomial< n, TRing, TAlloc > & p) inline
Swaps two polynomials.
Parameters
p the polynomial to exchange with.
Definition at line 1099 of file MPolynomial.h.
    {
        myValue.swap(p.myValue);
    }
References DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::swap().
Friends And Related Symbol Documentation
euclidDiv
template<int n, typename TRing , class TAlloc > void euclidDiv (const MPolynomial< 1, TRing, TAlloc > & f, const MPolynomial< 1, TRing, TAlloc > & g, MPolynomial< 1, TRing, TAlloc > & q, MPolynomial< 1, TRing, TAlloc > & r) friend
Forward declaration, to be able to declare this as a friend.
MPolynomialDerivativeComputer
template<int n, typename TRing , class TAlloc > template<int NN, int nn, typename TT , typename AA > friend class MPolynomialDerivativeComputer friend
Definition at line 969 of file MPolynomial.h.
MPolynomialEvaluator
template<int n, typename TRing , class TAlloc > template<int nn, typename TT , typename AA , typename SS > friend class MPolynomialEvaluator friend
Definition at line 978 of file MPolynomial.h.
Referenced by DGtal::MPolynomial< n, TRing, TAlloc >::operator()(), and DGtal::MPolynomial< n, TRing, TAlloc >::operator()().
MPolynomialEvaluatorImpl
template<int n, typename TRing , class TAlloc > template<int nn, typename TT , typename HLHL , typename AA , typename SS > friend class MPolynomialEvaluatorImpl friend
Definition at line 981 of file MPolynomial.h.
operator*
template<int n, typename TRing , class TAlloc > MPolynomial operator* (const Ring & v, const MPolynomial< n, TRing, TAlloc > & p) friend
Multiplication by a constant from the left.
Parameters
v any value in the ring.
p any polynomial of this type.
Returns
the corresponding polynomial.
Definition at line 1259 of file MPolynomial.h.
    {
      MPolynomial r(p);
      for ( Size i = 0; i < p.myValue.size(); ++i )
        r[i] *= v;
      return r;
    }
Field Documentation
myValue
template<int n, typename TRing , class TAlloc > Storage DGtal::MPolynomial< n, TRing, TAlloc >::myValue private
The vector storing polynomials coefficients. For 0 or 1 variables, uses a standard vector, for more variables, uses a specific vector of pointers to polynomials, with adequate allocators. This is for efficiency purposes.
Definition at line 1008 of file MPolynomial.h.
Referenced by DGtal::MPolynomialDerivativeComputer< N, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomialDerivativeComputer< 0, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomial< n, TRing, TAlloc >::degree(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::evaluate(), DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator(), DGtal::MPolynomial< n, TRing, TAlloc >::isZero(), DGtal::MPolynomial< 0, TRing, TAlloc >::isZero(), DGtal::MPolynomial< n, TRing, TAlloc >::leading(), DGtal::MPolynomial< n, TRing, TAlloc >::MPolynomial(), DGtal::MPolynomial< n, TRing, TAlloc >::normalize(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator const Ring &(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1(), DGtal::MPolynomialEvaluator< 1, TRing, TAlloc, TX >::operator X(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator!=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator()(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator*(), DGtal::MPolynomial< n, TRing, TAlloc >::operator*=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator*=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator+(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator+=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator-(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator-(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator-=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator/(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator/(), DGtal::MPolynomial< n, TRing, TAlloc >::operator/=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator/=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator=(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator=(), DGtal::MPolynomial< n, TRing, TAlloc >::operator==(), DGtal::MPolynomial< n, TRing, TAlloc >::operator==(), DGtal::MPolynomial< 0, TRing, TAlloc >::operator==(), DGtal::MPolynomial< n, TRing, TAlloc >::operator[](), DGtal::MPolynomial< n, TRing, TAlloc >::operator[](), DGtal::MPolynomial< n, TRing, TAlloc >::selfDisplay(), DGtal::MPolynomial< 0, TRing, TAlloc >::selfDisplay(), DGtal::MPolynomial< n, TRing, TAlloc >::swap(), and DGtal::MPolynomial< 0, TRing, TAlloc >::swap().
myZeroPolynomial
template<int n, typename TRing , class TAlloc > MPolyNM1 DGtal::MPolynomial< n, TRing, TAlloc >::myZeroPolynomial static private
The zero polynomial of n-1 variables for a n-multivariate polynomial.
Definition at line 1001 of file MPolynomial.h.
Referenced by DGtal::MPolynomial< n, TRing, TAlloc >::leading(), and DGtal::MPolynomial< n, TRing, TAlloc >::operator[]().
The documentation for this class was generated from the following file:
MPolynomial.h