DGtal: DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor > Class Template Reference
DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor > Class Template Reference
Aim: model of CBidirectionalRangeFromPoint that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
#include <DGtal/base/SimpleRandomAccessRangeFromPoint.h>
Public Types
typedef DistanceFunctor::Point Point
typedef TIterator Iterator
typedef TConstIterator ConstIterator
typedef std::reverse_iterator< Iterator > ReverseIterator
typedef std::reverse_iterator< ConstIterator > ConstReverseIterator
typedef TIterator OutputIterator
typedef std::reverse_iterator< Iterator > ReverseOutputIterator
typedef DGtal::Circulator< Iterator > Circulator
typedef std::reverse_iterator< Circulator > ReverseCirculator
typedef DGtal::Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator< ConstCirculator > ConstReverseCirculator
Public Member Functions
SimpleRandomAccessRangeFromPoint (const TIterator &itb, const TIterator &ite, const DistanceFunctor &aDistance)
SimpleRandomAccessRangeFromPoint (const SimpleRandomAccessRangeFromPoint &other)
SimpleRandomAccessRangeFromPoint & operator= (const SimpleRandomAccessRangeFromPoint &other)
~SimpleRandomAccessRangeFromPoint ()
bool isValid () const
void selfDisplay (std::ostream &out) const
std::string className () const
Iterator begin ()
Iterator begin (const Point &aPoint)
ConstIterator begin () const
ConstIterator begin (const Point &aPoint) const
Iterator end ()
ConstIterator end () const
OutputIterator outputIterator ()
OutputIterator outputIterator (const Point &aPoint)
ReverseOutputIterator routputIterator ()
ReverseOutputIterator routputIterator (const Point &aPoint)
ReverseIterator rbegin ()
ReverseIterator rbegin (const Point &aPoint)
ReverseIterator rend ()
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
Circulator c ()
ReverseCirculator rc ()
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TIterator >))
BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TConstIterator >))
BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< DistanceFunctor, typename DistanceFunctor::Difference, typename DistanceFunctor::Point >))
Private Attributes
TIterator myBegin
TIterator myEnd
DistanceFunctor myDistance
Detailed Description
template<typename TConstIterator, typename TIterator, typename DistanceFunctor>
class DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >
Aim: model of CBidirectionalRangeFromPoint that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
Template Parameters
TIterator the type of the iterator to adapt (at least bidirectional)
DistanceFunctor type of distance from point functor for random access container models. Models must have a Point and a Difference inner types. operator() returns a number of type Difference on instances of Point)
See also
RangeAdapter
Definition at line 73 of file SimpleRandomAccessRangeFromPoint.h.
Member Typedef Documentation
Circulator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::Circulator<Iterator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::Circulator
Definition at line 95 of file SimpleRandomAccessRangeFromPoint.h.
ConstCirculator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::Circulator<ConstIterator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ConstCirculator
Definition at line 98 of file SimpleRandomAccessRangeFromPoint.h.
ConstIterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > TConstIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ConstIterator
Definition at line 87 of file SimpleRandomAccessRangeFromPoint.h.
ConstReverseCirculator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::reverse_iterator<ConstCirculator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ConstReverseCirculator
Definition at line 99 of file SimpleRandomAccessRangeFromPoint.h.
ConstReverseIterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::reverse_iterator<ConstIterator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ConstReverseIterator
Definition at line 90 of file SimpleRandomAccessRangeFromPoint.h.
Iterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > TIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::Iterator
Definition at line 86 of file SimpleRandomAccessRangeFromPoint.h.
OutputIterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > TIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::OutputIterator
Definition at line 92 of file SimpleRandomAccessRangeFromPoint.h.
Point
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DistanceFunctor::Point DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::Point
Definition at line 84 of file SimpleRandomAccessRangeFromPoint.h.
ReverseCirculator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::reverse_iterator<Circulator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ReverseCirculator
Definition at line 96 of file SimpleRandomAccessRangeFromPoint.h.
ReverseIterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::reverse_iterator<Iterator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ReverseIterator
Definition at line 89 of file SimpleRandomAccessRangeFromPoint.h.
ReverseOutputIterator
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::reverse_iterator<Iterator> DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::ReverseOutputIterator
Definition at line 93 of file SimpleRandomAccessRangeFromPoint.h.
Constructor & Destructor Documentation
SimpleRandomAccessRangeFromPoint() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::SimpleRandomAccessRangeFromPoint (const TIterator & itb, const TIterator & ite, const DistanceFunctor & aDistance) inline
Standard constructor from two iterators and one functor.
Parameters
itb begin iterator.
ite end iterator.
aDistance functor used to adapt on-the-fly the elements of the range
Definition at line 111 of file SimpleRandomAccessRangeFromPoint.h.
          : myBegin ( itb ), myEnd ( ite ), myDistance ( aDistance ) {}
SimpleRandomAccessRangeFromPoint() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::SimpleRandomAccessRangeFromPoint (const SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor > & other) inline
Copy constructor.
Parameters
other the iterator to clone.
Definition at line 120 of file SimpleRandomAccessRangeFromPoint.h.
          : myBegin ( other.myBegin ), myEnd ( other.myEnd ),
          myDistance ( other.myDistance ) {}
~SimpleRandomAccessRangeFromPoint()
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::~SimpleRandomAccessRangeFromPoint () inline
Destructor. Does nothing.
Definition at line 144 of file SimpleRandomAccessRangeFromPoint.h.
{}
Member Function Documentation
begin() [1/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > Iterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin () inline
Iterator service.
Returns
begin iterator
Definition at line 203 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return Iterator ( myBegin );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin.
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c().
begin() [2/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 223 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstIterator ( myBegin );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin.
begin() [3/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > Iterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin (const Point & aPoint) inline
Iterator service.
Parameters
aPoint a Point
Returns
begin iterator at aPoint
Definition at line 214 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return Iterator ( myBegin ) + myDistance ( aPoint );
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
begin() [4/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin (const Point & aPoint) const inline
Iterator service.
Parameters
aPoint a Point
Returns
begin iterator at aPoint
Definition at line 234 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstIterator ( myBegin ) + myDistance ( aPoint );
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
BOOST_CONCEPT_ASSERT() [1/3]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TConstIterator >)) private
BOOST_CONCEPT_ASSERT() [2/3]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TIterator >)) private
BOOST_CONCEPT_ASSERT() [3/3]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< DistanceFunctor, typename DistanceFunctor::Difference, typename DistanceFunctor::Point >)) private
c() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > Circulator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c () inline
Mutable circulator service.
Returns
a circulator
Definition at line 358 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return Circulator ( this->begin(), this->begin(), this->end() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end().
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rc(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rc().
c() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstCirculator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c () const inline
Constant circulator service.
Returns
a constant circulator
Definition at line 376 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstCirculator ( this->begin(), this->begin(), this->end() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end().
className()
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > std::string DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 172 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return "SimpleRandomAccessRangeFromPoint";
      }
end() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > Iterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end () inline
Iterator service.
Returns
end iterator
Definition at line 243 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return Iterator ( myEnd );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myEnd.
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::routputIterator().
end() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end () const inline
Iterator service.
Returns
end iterator
Definition at line 252 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstIterator ( myEnd );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myEnd.
isValid()
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > bool DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 150 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return true;
      }
operator=()
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > SimpleRandomAccessRangeFromPoint & DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::operator= (const SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor > & other) inline
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
Definition at line 129 of file SimpleRandomAccessRangeFromPoint.h.
      {
        if ( this != &other )
        {
          myBegin = other.myBegin;
          myEnd = other.myEnd;
          myDistance = other.myDistance;
        }
        return *this;
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myEnd.
outputIterator() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > OutputIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator () inline
OutputIterator service.
Returns
an output iterator on the first elements
Definition at line 261 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return OutputIterator ( myBegin );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin.
Referenced by testImage().
outputIterator() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > OutputIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator (const Point & aPoint) inline
OutputIterator service.
Parameters
aPoint a point
Returns
an output iterator on the point
Definition at line 271 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return OutputIterator ( myBegin ) + myDistance ( aPoint ) ;
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
rbegin() [1/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin () inline
Iterator service.
Returns
rbegin iterator
Definition at line 299 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseIterator ( this->end() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end().
rbegin() [2/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 329 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstReverseIterator ( this->end() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end().
rbegin() [3/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin (const Point & aPoint) inline
Iterator service.
Parameters
aPoint a Point
Returns
rbegin iterator at aPoint
Definition at line 309 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseIterator ( myBegin + myDistance ( aPoint ) + 1 );
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
rbegin() [4/4]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin (const Point & aPoint) const inline
Iterator service.
Parameters
aPoint a Point
Returns
rbegin iterator at aPoint
Definition at line 339 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstReverseIterator ( myBegin + myDistance ( aPoint ) + 1 );
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
rc() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseCirculator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rc () inline
Reverse mutable circulator service.
Returns
a reverse circulator
Definition at line 367 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseCirculator ( this->c() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c().
rc() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstReverseCirculator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rc () const inline
Reverse constant circulator service.
Returns
a reverse constant circulator
Definition at line 385 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstReverseCirculator ( this->c() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c().
rend() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rend () inline
Iterator service.
Returns
rend iterator
Definition at line 319 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseIterator ( myBegin );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin.
rend() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 349 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ConstReverseIterator ( myBegin );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin.
routputIterator() [1/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseOutputIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::routputIterator () inline
ReverseOutputIterator service.
Returns
an output itertor on the first elements
Definition at line 280 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseOutputIterator ( this->end() );
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end().
routputIterator() [2/2]
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > ReverseOutputIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::routputIterator (const Point & aPoint) inline
ReverseOutputIterator service.
Parameters
aPoint a point
Returns
an output iterator on the point
Definition at line 290 of file SimpleRandomAccessRangeFromPoint.h.
      {
        return ReverseOutputIterator ( myBegin + myDistance ( aPoint ) + 1 ) ;
      }
References aPoint(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance.
selfDisplay()
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > void DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 160 of file SimpleRandomAccessRangeFromPoint.h.
      {
        typedef typename IteratorCirculatorTraits<Iterator>::Value Value;
        out << "[SimpleRandomAccessRangeFromPoint]" << std::endl;
        out << "\t";
        std::copy ( myBegin, myEnd, std::ostream_iterator<Value> ( out, ", " ) );
        out << std::endl;
      }
References DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myEnd.
Field Documentation
myBegin
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > TIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myBegin private
Begin underlying iterator
Definition at line 184 of file SimpleRandomAccessRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::operator=(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rend(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rend(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::routputIterator(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::selfDisplay().
myDistance
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > DistanceFunctor DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myDistance private
Underlying distance function
Definition at line 193 of file SimpleRandomAccessRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::operator=(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::rbegin(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::routputIterator().
myEnd
template<typename TConstIterator , typename TIterator , typename DistanceFunctor > TIterator DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::myEnd private
End underlying iterator
Definition at line 188 of file SimpleRandomAccessRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::end(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::operator=(), and DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::selfDisplay().
The documentation for this class was generated from the following file:
SimpleRandomAccessRangeFromPoint.h