DGtal: DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency > Class Template Reference
DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency > Class Template Reference
Aim: This class is a wrapper around ArithmeticalDSS that is devoted to the dynamic recognition of digital straight segments (DSS) along any sequence of digital points.
#include <DGtal/geometry/curves/ArithmeticalDSSComputer.h>
Public Types
typedef TIterator ConstIterator
typedef IteratorCirculatorTraits< ConstIterator >::Value Point
typedef IteratorCirculatorTraits< TIterator >::Value::Coordinate Coordinate
typedef TInteger Integer
typedef ArithmeticalDSS< Coordinate, Integer, adjacency > DSS
typedef DSS Primitive
typedef Point Vector
typedef ArithmeticalDSSComputer< ConstIterator, TInteger, adjacency > Self
typedef ArithmeticalDSSComputer< ReverseIterator< ConstIterator >, TInteger, adjacency > Reverse
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
BOOST_CONCEPT_ASSERT ((boost_concepts::ForwardTraversalConcept< ConstIterator >))
BOOST_STATIC_ASSERT ((Point::dimension==2))
BOOST_CONCEPT_ASSERT ((concepts::CInteger< Coordinate >))
BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >))
BOOST_STATIC_ASSERT ((concepts::ConceptUtils::SameType< Point, typename DSS::Point >::value))
ArithmeticalDSSComputer ()
ArithmeticalDSSComputer (const ConstIterator &it)
void init (const ConstIterator &it)
ArithmeticalDSSComputer (const ArithmeticalDSSComputer &other)
ArithmeticalDSSComputer & operator= (const ArithmeticalDSSComputer &other)
Self getSelf () const
Reverse getReverse () const
bool operator== (const ArithmeticalDSSComputer &other) const
bool operator!= (const ArithmeticalDSSComputer &other) const
~ArithmeticalDSSComputer ()
bool isExtendableFront ()
bool isExtendableBack ()
bool extendFront ()
bool extendBack ()
bool retractFront ()
bool retractBack ()
const Primitive & primitive () const
Integer a () const
Integer b () const
Integer mu () const
Integer omega () const
Point Uf () const
Point Ul () const
Point Lf () const
Point Ll () const
Point back () const
Point front () const
ConstIterator begin () const
ConstIterator end () const
bool isValid () const
Integer remainder (const ConstIterator &it) const
Integer remainder (const Point &aPoint) const
Integer position (const ConstIterator &it) const
Integer position (const Point &aPoint) const
bool isInDSL (const Point &aPoint) const
bool isInDSL (const ConstIterator &it) const
bool isInDSS (const Point &aPoint) const
bool isInDSS (const ConstIterator &it) const
void selfDisplay (std::ostream &out) const
Protected Attributes
DSS myDSS
ConstIterator myBegin
ConstIterator myEnd
Detailed Description
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8>
class DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >
Aim: This class is a wrapper around ArithmeticalDSS that is devoted to the dynamic recognition of digital straight segments (DSS) along any sequence of digital points.
See Digital straight lines and segments for further details. See also classes NaiveDSS8Computer and StandardDSS4Computer, which are aliases of this class.
Template Parameters
TIterator type of iterator on 2d digital points, at least readable and forward.
TInteger type of integers used for the computation of remainders, which is a model of CInteger.
adjacency an unsigned integer equal to 4 for standard (simply 4-connected) DSS or 8 for naive (simply 8-connected) DSS (default).
This class is a model of CDynamicBidirectionalSegmentComputer. It is also default constructible, copy constructible, assignable and equality comparable.
See also
ArithmeticalDSS NaiveDSS StandardDSS
exampleArithmeticalDSS.cpp exampleArithmeticalDSSComputer.cpp
Examples
geometry/curves/convex-and-concave-parts.cpp, geometry/curves/exampleArithmeticalDSSComputer.cpp, and geometry/curves/greedy-dss-decomposition.cpp.
Definition at line 86 of file ArithmeticalDSSComputer.h.
Member Typedef Documentation
ConstIterator
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> TIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ConstIterator
Type of iterator, at least readable and forward
Definition at line 95 of file ArithmeticalDSSComputer.h.
Coordinate
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> IteratorCirculatorTraits<TIterator>::Value::Coordinate DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Coordinate
Type of coordinate
Definition at line 108 of file ArithmeticalDSSComputer.h.
DSS
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ArithmeticalDSS<Coordinate, Integer, adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::DSS
Type of objects that represents DSSs
Definition at line 120 of file ArithmeticalDSSComputer.h.
Integer
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Integer
Type of integer, devoted to remainders (and intercepts)
Definition at line 114 of file ArithmeticalDSSComputer.h.
Point
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> IteratorCirculatorTraits<ConstIterator>::Value DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point
Type of 2d digital point
Definition at line 102 of file ArithmeticalDSSComputer.h.
Primitive
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DSS DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Primitive
Type of primitive representation, defined as an alias of DSS
Definition at line 127 of file ArithmeticalDSSComputer.h.
Reverse
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ArithmeticalDSSComputer<ReverseIterator<ConstIterator>,TInteger,adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Reverse
Definition at line 135 of file ArithmeticalDSSComputer.h.
Self
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ArithmeticalDSSComputer<ConstIterator,TInteger,adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Self
Definition at line 134 of file ArithmeticalDSSComputer.h.
Vector
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Vector
Type of vector, defined as an alias of point
Definition at line 132 of file ArithmeticalDSSComputer.h.
Constructor & Destructor Documentation
ArithmeticalDSSComputer() [1/3]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer ()
Default constructor. not valid
ArithmeticalDSSComputer() [2/3]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer (const ConstIterator & it)
Constructor with initialisation
Parameters
it an iterator on 2D points
See also
init
ArithmeticalDSSComputer() [3/3]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other)
Copy constructor.
Parameters
other the object to clone.
~ArithmeticalDSSComputer()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::~ArithmeticalDSSComputer () inline
Destructor.
Definition at line 202 of file ArithmeticalDSSComputer.h.
{};
Member Function Documentation
a()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::a () const
Returns
a-parameter of the DSS
b()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::b () const
Returns
b-parameter of the DSS
back()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::back () const
Returns
the first point of the DSS.
begin()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::begin () const
Returns
begin iterator of the DSS range.
Referenced by checkSubArithmeticDSS(), and checkSubStandardDSLQ0().
BOOST_CONCEPT_ASSERT() [1/4]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((boost_concepts::ForwardTraversalConcept< ConstIterator >))
BOOST_CONCEPT_ASSERT() [2/4]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
BOOST_CONCEPT_ASSERT() [3/4]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< Coordinate >))
BOOST_CONCEPT_ASSERT() [4/4]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >))
BOOST_STATIC_ASSERT() [1/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_STATIC_ASSERT ((concepts::ConceptUtils::SameType< Point, typename DSS::Point >::value))
BOOST_STATIC_ASSERT() [2/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_STATIC_ASSERT ((Point::dimension==2))
end()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::end () const
Returns
end iterator of the DSS range.
Referenced by testDSSreco().
extendBack()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendBack ()
Tests whether the current DSS can be extended at the back. Computes the parameters of the extended DSS if yes.
Returns
'true' if yes, 'false' otherwise.
extendFront()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendFront ()
Tests whether the current DSS can be extended at the front. Computes the parameters of the extended DSS if yes.
Returns
'true' if yes, 'false' otherwise.
Referenced by testDSSreco().
front()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::front () const
Returns
the last point of the DSS.
getReverse()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Reverse DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::getReverse () const
Returns
a default-constructed instance of Reverse
getSelf()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Self DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::getSelf () const
Returns
a default-constructed instance of Self
init()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> void DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::init (const ConstIterator & it)
Initialisation.
Parameters
it an iterator on 2D points
Examples
geometry/curves/exampleArithmeticalDSSComputer.cpp.
Referenced by main(), testDSSreco(), and testIsInsideForOneQuadrant().
isExtendableBack()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isExtendableBack ()
Tests whether the current DSS can be extended at the back.
Returns
'true' if yes, 'false' otherwise.
isExtendableFront()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isExtendableFront ()
Tests whether the current DSS can be extended at the front.
Returns
'true' if yes, 'false' otherwise.
isInDSL() [1/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSL (const ConstIterator & it) const
Checks whether a point is in the bounding DSL of minimal parameters
Parameters
it an iterator on the point to be checked
Returns
'true' if yes, 'false' otherwise
isInDSL() [2/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSL (const Point & aPoint) const
Checks whether a point is in the bounding DSL of minimal parameters
Parameters
aPoint the point to be checked
Returns
'true' if yes, 'false' otherwise
isInDSS() [1/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSS (const ConstIterator & it) const
Checks whether a point belongs to the DSS or not
Parameters
it an iterator on the point to be checked
Returns
'true' if yes, 'false' otherwise
isInDSS() [2/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSS (const Point & aPoint) const
Checks whether a point belongs to the DSS or not
Parameters
aPoint the point to be checked
Returns
'true' if yes, 'false' otherwise
isValid()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Referenced by testDSSreco().
Lf()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Lf () const
Returns
first lower leaning point.
Ll()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Ll () const
Returns
last lower leaning point.
mu()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::mu () const
Returns
mu-parameter of the DSS
omega()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::omega () const
Returns
omega-parameter of the DSS
operator!=()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator!= (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) const
Difference operator.
Parameters
other the object to compare with.
Returns
'false' if equal 'true' otherwise
operator=()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ArithmeticalDSSComputer & DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator= (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other)
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
operator==()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator== (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) const
Equality operator.
Parameters
other the object to compare with.
Returns
'true' if the DSS representations and the ranges of the two objects match, 'false' otherwise
position() [1/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::position (const ConstIterator & it) const
Computes the position of a point (that does not necessarily belong to the DSS)
Parameters
it an iterator on points
Returns
the position of *it.
position() [2/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::position (const Point & aPoint) const
Computes the position of a point (that does not necessarily belong to the DSS)
Parameters
aPoint the point whose position is returned
Returns
the position of aPoint.
primitive()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> const Primitive & DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::primitive () const
Returns
the current DSS representation. NB: since we return a const reference, you must copy the result, if you want to keep it beyond the object's existence.
remainder() [1/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::remainder (const ConstIterator & it) const
Computes the remainder of a point (that does not necessarily belong to the DSS)
Parameters
it an iterator on points
Returns
the remainder of *it.
remainder() [2/2]
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::remainder (const Point & aPoint) const
Computes the remainder of a point (that does not necessarily belong to the DSS)
Parameters
aPoint the point whose remainder is returned
Returns
the remainder
retractBack()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::retractBack ()
Removes the back point of the DSS if it has more than two points
Returns
'true' if the back point is removed, 'false' otherwise.
retractFront()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::retractFront ()
Removes the front point of the DSS if it has more than two points
Returns
'true' if the front point is removed, 'false' otherwise.
selfDisplay()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> void DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Uf()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Uf () const
Returns
first upper leaning point.
Ul()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Ul () const
Returns
last upper leaning point.
Field Documentation
myBegin
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myBegin protected
begin iterator
Definition at line 393 of file ArithmeticalDSSComputer.h.
myDSS
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DSS DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myDSS protected
DSS representation
Definition at line 389 of file ArithmeticalDSSComputer.h.
myEnd
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myEnd protected
end iterator
Definition at line 397 of file ArithmeticalDSSComputer.h.
The documentation for this class was generated from the following file:
ArithmeticalDSSComputer.h