DGtal: DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType > Class Template Reference
DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType > Class Template Reference
Aim: model of CConstBidirectionalRange that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
#include <DGtal/base/ConstRangeAdapter.h>
Public Types
typedef ConstIteratorAdapter< TIterator, TFunctor, TReturnType > ConstIterator
typedef ReverseIterator< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef ReverseIterator< ConstCirculator > ConstReverseCirculator
typedef IteratorCirculatorTraits< ConstIterator >::Difference Difference
Public Member Functions
ConstRangeAdapter (const TIterator &itb, const TIterator &ite, const TFunctor &aFunctor)
ConstRangeAdapter (const TIterator &itb, const TIterator &ite, const TFunctor *aFunctorPtr)
ConstRangeAdapter (const ConstRangeAdapter &other)
~ConstRangeAdapter ()
bool isValid () const
Difference size () const
void selfDisplay (std::ostream &out) const
std::string className () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< TIterator >))
BOOST_CONCEPT_ASSERT ((boost_concepts::BidirectionalTraversalConcept< TIterator >))
ConstRangeAdapter & operator= (const ConstRangeAdapter &other)
Difference size (const TIterator &itb, const TIterator &ite, RandomAccessCategory) const
Difference size (const TIterator &itb, const TIterator &ite, BidirectionalCategory) const
Private Attributes
TIterator myBegin
TIterator myEnd
const TFunctor * myFunctor
bool myFlagIsOwned
Detailed Description
template<typename TIterator, typename TFunctor, typename TReturnType>
class DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >
Aim: model of CConstBidirectionalRange that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
Template Parameters
TIterator the type of the iterator to adapt (at least bidirectional).
Moreover, the provided (circular)iterator is adapted with a functor f given at construction so that operator* calls f(*it), instead of calling directly operator* of the underlying iterator it.
Template Parameters
TFunctor the type of functor that transforms the pointed element into another one
TReturnType the type of the element returned by the underlying functor.
NB: the underlying functor is stored in the range as aliasing pointer in order to avoid copies. As a consequence the pointed object must exist and must not be deleted during the use of the range.
See also
ConstIteratorAdapter BasicFunctors.h BasicPointFunctors.h SCellsFunctors.h
Examples
geometry/curves/estimation/exampleCurvature.cpp, and geometry/tools/exampleAlphaShape.cpp.
Definition at line 86 of file ConstRangeAdapter.h.
Member Typedef Documentation
ConstCirculator
template<typename TIterator , typename TFunctor , typename TReturnType > Circulator<ConstIterator> DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstCirculator
Definition at line 98 of file ConstRangeAdapter.h.
ConstIterator
template<typename TIterator , typename TFunctor , typename TReturnType > ConstIteratorAdapter<TIterator,TFunctor,TReturnType> DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstIterator
Definition at line 95 of file ConstRangeAdapter.h.
ConstReverseCirculator
template<typename TIterator , typename TFunctor , typename TReturnType > ReverseIterator<ConstCirculator> DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstReverseCirculator
Definition at line 99 of file ConstRangeAdapter.h.
ConstReverseIterator
template<typename TIterator , typename TFunctor , typename TReturnType > ReverseIterator<ConstIterator> DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstReverseIterator
Definition at line 96 of file ConstRangeAdapter.h.
Difference
template<typename TIterator , typename TFunctor , typename TReturnType > IteratorCirculatorTraits<ConstIterator>::Difference DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::Difference
Definition at line 101 of file ConstRangeAdapter.h.
Constructor & Destructor Documentation
ConstRangeAdapter() [1/3]
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstRangeAdapter (const TIterator & itb, const TIterator & ite, const TFunctor & aFunctor) inline
Standard constructor from two iterators and one functor (stored as an aliasing pointer).
Parameters
itb begin iterator.
ite end iterator.
aFunctor functor used to adapt on-the-fly the elements of the range
Definition at line 112 of file ConstRangeAdapter.h.
      : myBegin(itb), myEnd(ite), myFunctor(&aFunctor), myFlagIsOwned(false) {}
ConstRangeAdapter() [2/3]
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstRangeAdapter (const TIterator & itb, const TIterator & ite, const TFunctor * aFunctorPtr) inline
Standard constructor from two iterators and one pointer on a functor (stored as an owning pointer).
Parameters
itb begin iterator.
ite end iterator.
aFunctorPtr pointer on a functor used to adapt on-the-fly the elements of the range
Definition at line 124 of file ConstRangeAdapter.h.
      : myBegin(itb), myEnd(ite), myFunctor(aFunctorPtr), myFlagIsOwned(true) {}
ConstRangeAdapter() [3/3]
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstRangeAdapter (const ConstRangeAdapter< TIterator, TFunctor, TReturnType > & other) inline
Copy constructor.
Parameters
other the iterator to clone.
Definition at line 132 of file ConstRangeAdapter.h.
      : myBegin(other.myBegin), myEnd(other.myEnd), myFlagIsOwned(other.myFlagIsOwned)
      {
  if (myFlagIsOwned)
    myFunctor = new TFunctor( *other.myFunctor ); //owned copy
  else
    myFunctor = other.myFunctor; //copy of the alias
      }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFlagIsOwned, and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFunctor.
~ConstRangeAdapter()
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::~ConstRangeAdapter () inline
Destructor. Does nothing.
Definition at line 144 of file ConstRangeAdapter.h.
      {
        if (myFlagIsOwned) delete myFunctor;
      }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFlagIsOwned, and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFunctor.
Member Function Documentation
begin()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 222 of file ConstRangeAdapter.h.
{
      return ConstIterator( myBegin, *myFunctor );
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myBegin, and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFunctor.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::c(), DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rend(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::selfDisplay().
BOOST_CONCEPT_ASSERT() [1/2]
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::BOOST_CONCEPT_ASSERT ((boost_concepts::BidirectionalTraversalConcept< TIterator >)) private
BOOST_CONCEPT_ASSERT() [2/2]
template<typename TIterator , typename TFunctor , typename TReturnType > DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< TIterator >)) private
c()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstCirculator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::c () const inline
Circulator service. Prodives a circulator such that *c() == *begin()
Returns
a circulator
See also
rc method
Definition at line 257 of file ConstRangeAdapter.h.
{
      return ConstCirculator( this->begin(), this->begin(), this->end() );
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end().
Referenced by compare(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rc().
className()
template<typename TIterator , typename TFunctor , typename TReturnType > std::string DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 180 of file ConstRangeAdapter.h.
    {
      return "ConstRangeAdapter";
    }
end()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end () const inline
Iterator service.
Returns
end iterator
Definition at line 230 of file ConstRangeAdapter.h.
{
      return ConstIterator( myEnd, *myFunctor );
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myEnd, and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFunctor.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::c(), DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rbegin(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::selfDisplay().
isValid()
template<typename TIterator , typename TFunctor , typename TReturnType > bool DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 153 of file ConstRangeAdapter.h.
{ return true; }
operator=()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstRangeAdapter & DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::operator= (const ConstRangeAdapter< TIterator, TFunctor, TReturnType > & other) private
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
rbegin()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstReverseIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 238 of file ConstRangeAdapter.h.
{
      return ConstReverseIterator(this->end());
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end().
rc()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstReverseCirculator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rc () const inline
Circulator service. Provides a reverse circulator such that *rc() == *c() == *begin()
Returns
a reverse circulator
See also
c method
begin method
Definition at line 269 of file ConstRangeAdapter.h.
{
      //implemented so that *rc() == *c()
      ConstCirculator tmp = this->c();
      ++tmp;
      return ConstReverseCirculator( tmp );
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::c().
rend()
template<typename TIterator , typename TFunctor , typename TReturnType > ConstReverseIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 246 of file ConstRangeAdapter.h.
{
      return ConstReverseIterator(this->begin());
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin().
selfDisplay()
template<typename TIterator , typename TFunctor , typename TReturnType > void DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 169 of file ConstRangeAdapter.h.
    {
      out << "[ConstRangeAdapter]" << std::endl;
      out << "\t";
      std::copy( this->begin(), this->end(), std::ostream_iterator<TReturnType>(out, ", ") );
      out << std::endl;
    }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end().
size() [1/3]
template<typename TIterator , typename TFunctor , typename TReturnType > Difference DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size () const inline
Returns
the size of the range.
Definition at line 158 of file ConstRangeAdapter.h.
      {
        typedef typename IteratorCirculatorTraits<TIterator>::Category Category;
        return size( myBegin, myEnd, Category() );
      }
References DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myBegin, DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myEnd, and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size().
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size().
size() [2/3]
template<typename TIterator , typename TFunctor , typename TReturnType > Difference DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size (const TIterator & itb, const TIterator & ite, BidirectionalCategory) const inline private
Get the size of [itb, ite)
Parameters
itb begin iterator
ite end iterator
Returns
the size of the range. NB: in O(ite-itb)
Definition at line 297 of file ConstRangeAdapter.h.
      {
        TIterator it = itb;
        unsigned int d = 0;
        for ( ; it != ite; ++it, ++d)
          {}
        return d;
      }
size() [3/3]
template<typename TIterator , typename TFunctor , typename TReturnType > Difference DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size (const TIterator & itb, const TIterator & ite, RandomAccessCategory) const inline private
Get the size of [itb, ite)
Parameters
itb begin iterator
ite end iterator
Returns
the size of the range. NB: in O(1)
Definition at line 285 of file ConstRangeAdapter.h.
      {
        return (ite-itb);
      }
Field Documentation
myBegin
template<typename TIterator , typename TFunctor , typename TReturnType > TIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myBegin private
Begin underlying iterator
Definition at line 191 of file ConstRangeAdapter.h.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size().
myEnd
template<typename TIterator , typename TFunctor , typename TReturnType > TIterator DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myEnd private
End underlying iterator
Definition at line 195 of file ConstRangeAdapter.h.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::size().
myFlagIsOwned
template<typename TIterator , typename TFunctor , typename TReturnType > bool DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFlagIsOwned private
bool equal to true if myFunctor is owned
Definition at line 203 of file ConstRangeAdapter.h.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstRangeAdapter(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::~ConstRangeAdapter().
myFunctor
template<typename TIterator , typename TFunctor , typename TReturnType > const TFunctor* DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::myFunctor private
Pointer on the underlying functor
Definition at line 199 of file ConstRangeAdapter.h.
Referenced by DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::begin(), DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::ConstRangeAdapter(), DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::end(), and DGtal::ConstRangeAdapter< TIterator, TFunctor, TReturnType >::~ConstRangeAdapter().
The documentation for this class was generated from the following file:
ConstRangeAdapter.h