DGtal: exampleBoundedLatticePolytopeCount4D.cpp File Reference
exampleBoundedLatticePolytopeCount4D.cpp File Reference
DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/geometry/volumes/ConvexityHelper.h"
#include "DGtal/geometry/volumes/BoundedLatticePolytope.h"
Functions
int main (int argc, char *argv[])
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2022/06/19
An example file named exampleBoundedLatticePolytopeCount4D.
This file is part of the DGtal library.
Definition in file exampleBoundedLatticePolytopeCount4D.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 62 of file exampleBoundedLatticePolytopeCount4D.cpp.
{
  int N  = argc > 1 ? atoi( argv[ 1 ] ) : 10;  // nb of polytopes
  int nb = argc > 2 ? atoi( argv[ 2 ] ) : 10;   // nb points per polytope
  int R  = argc > 3 ? atoi( argv[ 3 ] ) : 50;   // max diameter of shape
  typedef int64_t                              Integer;
  typedef DGtal::ConvexityHelper< 4, Integer > Helper;
  typedef Helper::LatticePolytope              Polytope;
  typedef Polytope::Point                      Point;
  // Compute all polytopes
  DGtal::trace.beginBlock( "Compute 4D polytopes" );
  std::vector< Polytope > polytopes;
  int sum_nb_facets = 0;
  for ( int i = 0; i < N; i++ )
    {
      std::vector< Point > V;
      for ( int i = 0; i < nb; i++ ) {
        Point p( rand() % (2*R+1) - R, rand() % (2*R+1) - R,
                 rand() % (2*R+1) - R, rand() % (2*R+1) - R );
        V.push_back( p );
      }
      Polytope P = Helper::computeLatticePolytope( V );
      sum_nb_facets += P.nbHalfSpaces();
      polytopes.push_back( P );
    }
  double t1 = DGtal::trace.endBlock();
  DGtal::trace.info() << "Computed " << N
               << " 4D polytopes with " << ( sum_nb_facets / (double) N )
               << " facets on average, in " << t1 << " ms." << std::endl;
  // Count interior points (slow method)
  DGtal::trace.beginBlock( "Compute number of lattice points within polytope (slow)" );
  std::size_t slow_nb = 0;
  std::vector< Integer > slow_counts;
  for ( const auto& P : polytopes )
    {
      const auto nb = P.countByScanning();
      slow_nb      += nb;
      slow_counts.push_back( nb );
    }
  double t2 = DGtal::trace.endBlock();
  // Count interior points (fast method)
  DGtal::trace.beginBlock( "Compute number of lattice points within polytope (fast)" );
  std::size_t fast_nb = 0;
  std::vector< Integer > fast_counts;
  for ( const auto& P : polytopes )
    {
      const auto nb = P.count();
      fast_nb      += nb;
      fast_counts.push_back( nb );
    }
  double t3 = DGtal::trace.endBlock();
  bool ok = std::equal( slow_counts.cbegin(), slow_counts.cend(), fast_counts.cbegin() );
  DGtal::trace.info() << "Computed inside points is " << ( ok ? "OK" : "ERROR" ) << std::endl;
  DGtal::trace.info() << "Reference method computed " << slow_nb
                      << " points in " << t2 << " ms." << std::endl;
  DGtal::trace.info() << "Fast method computed " << fast_nb
                      << " points in " << t3 << " ms." << std::endl;
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.