DGtal: examplePlaneProbingParallelepipedEstimator.cpp File Reference
examplePlaneProbingParallelepipedEstimator.cpp File Reference
DGtal Examples
#include <iostream>
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/surfaces/DigitalPlanePredicate.h"
#include "DGtal/geometry/surfaces/estimation/PlaneProbingParallelepipedEstimator.h"
Typedefs
using DigitalPlane = DigitalPlanePredicate<Z3i::Space>
using Point = DigitalPlane::Vector
using Integer = Point::Coordinate
using Vector = DigitalPlane::Point
using Estimator = PlaneProbingParallelepipedEstimator<DigitalPlane, ProbingMode::R1>
Functions
int main (int argc, const char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jocelyn Meyron (jocel.nosp@m.yn.m.nosp@m.eyron.nosp@m.@lir.nosp@m.is.cn.nosp@m.rs.f.nosp@m.r) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2020/12/09
An example file that shows how to construct and use a DGtal::PlaneProbingParallelepipedEstimator on an analytical digital plane.
This file is part of the DGtal library.
Definition in file examplePlaneProbingParallelepipedEstimator.cpp.
Typedef Documentation
DigitalPlane
using DigitalPlane = DigitalPlanePredicate<Z3i::Space>
Definition at line 42 of file examplePlaneProbingParallelepipedEstimator.cpp.
Estimator
using Estimator = PlaneProbingParallelepipedEstimator<DigitalPlane, ProbingMode::R1>
Definition at line 46 of file examplePlaneProbingParallelepipedEstimator.cpp.
Integer
typedef Z3i::Integer Integer = Point::Coordinate
Examples
arithmetic/approximation.cpp, arithmetic/convergents-biginteger.cpp, arithmetic/extended-euclid.cpp, arithmetic/fraction.cpp, arithmetic/pattern.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/exampleDSLSubsegment.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount4D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, io/viewers/viewer3D-7-stdplane.cpp, and io/viewers/viewer3D-7bis-stdplane.cpp.
Definition at line 44 of file examplePlaneProbingParallelepipedEstimator.cpp.
Point
using Point = DigitalPlane::Vector
Definition at line 43 of file examplePlaneProbingParallelepipedEstimator.cpp.
Vector
typedef PC::Vector Vector = DigitalPlane::Point
Examples
arithmetic/lower-integer-convex-hull.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, and io/viewDualSurface.cpp.
Definition at line 45 of file examplePlaneProbingParallelepipedEstimator.cpp.
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 50 of file examplePlaneProbingParallelepipedEstimator.cpp.
{
  const int height = (argc > 1) ? std::atoi(argv[1]) : 2;
  std::cout << "height=" << height << std::endl;
  Vector n(2, 6, 15);
  DigitalPlane plane(n, -height, n.norm1());
  Point o(0, 0, 0);
  Integer bound = n.norm1() + 1;
  std::array<Point, 3> m = { Point(1, 0, 0), Point(0, 1, 0), Point(0, 0, 1) };
  Estimator estimator(o, m, plane, bound);
  int it = 0;
  while (estimator.advance()) {
      it++;
      std::cout << "state=" << estimator.getState() << ", isInReverseState=" << estimator.isInReverseState() << std::endl;
      std::clog << "it = " << it << " "
          << estimator.m(0) << " " << estimator.m(1) << " " << estimator.m(2) << " "
          << estimator.getNormal() << std::endl;
  }
  ASSERT(estimator.getNormal() == n);
  return 0;
}
References DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::advance(), DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::getNormal(), DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::getState(), DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::isInReverseState(), and DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::m().