DGtal: exampleRigidtransformation2d.cpp File Reference
exampleRigidtransformation2d.cpp File Reference
DGtal Examples
#include <iostream>
#include <cmath>
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ConstImageAdapter.h"
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/io/writers/GenericWriter.h"
#include "DGtal/images/RigidTransformation2D.h"
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, France
Date
2014/06/28
An example file named rigidtransformation2d.
This file is part of the DGtal library.
Definition in file exampleRigidtransformation2d.cpp.
Function Documentation
main()
int main (int , char **)
[def]
[def]
[trans]
[trans] [init_domain_helper]
[init_domain_helper]
[domain]
[domain]
[backward]
[backward]
[forward]
[forward]
Definition at line 61 of file exampleRigidtransformation2d.cpp.
{
  typedef ImageSelector<Domain, unsigned char >::Type Image;
  typedef ForwardRigidTransformation2D < Space > ForwardTrans;
  typedef BackwardRigidTransformation2D < Space > BackwardTrans;
  typedef ConstImageAdapter<Image, Domain, BackwardTrans, Image::Value, Identity > MyImageBackwardAdapter;
  typedef DomainRigidTransformation2D < Domain, ForwardTrans > MyDomainTransformer;
  typedef MyDomainTransformer::Bounds Bounds;
  trace.beginBlock ( "Example rigidtransformation2d" );
    ForwardTrans forwardTrans( RealPoint ( 5, 5 ), M_PI_4, RealVector( 3, -3 ) );
    BackwardTrans backwardTrans( RealPoint ( 5, 5 ), M_PI_4, RealVector( 3, -3 ) );
    MyDomainTransformer domainTransformer ( forwardTrans );
    Identity idD;
    Image image = PGMReader<Image>::importPGM ( examplesPath + "samples/church.pgm" );
    Bounds bounds = domainTransformer ( image.domain() );
    Domain transformedDomain ( bounds.first, bounds.second );
    trace.beginBlock ( "Backward - Eulerian model" );
      MyImageBackwardAdapter backwardImageAdapter ( image, transformedDomain , backwardTrans, idD );
      backwardImageAdapter >> "backward_transform.pgm";
    trace.endBlock();
    trace.beginBlock( "Forward - Lagrangian model" );
      Image forwardTransformedImage ( transformedDomain );
      for ( Domain::ConstIterator it = image.domain().begin(); it != image.domain().end(); ++it )
      {
        forwardTransformedImage.setValue ( forwardTrans ( *it ), image ( *it ) );
      }
      forwardTransformedImage >> "forward_transform.pgm";
    trace.endBlock();
  trace.endBlock();
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), DGtal::Image< TImageContainer >::setValue(), and DGtal::trace.