DGtal: exampleFunctorHolder.cpp File Reference
exampleFunctorHolder.cpp File Reference
DGtal Examples
An example file for DGtal::functors::FunctorHolder and DGtal::functors::holdFunctor.
#include <iostream>
#include <numeric>
#include <iterator>
#include <utility>
#include "DGtal/base/FunctorHolder.h"
#include "DGtal/kernel/PointVector.h"
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/io/readers/GenericReader.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/kernel/BasicPointPredicates.h"
Functions
double signed_dist_to_unit_circle (DGtal::PointVector< 2, double > const &pt)
[signed_dist_to_unit_circle]
template<typename Point >
Point::Component templated_signed_dist_to_unit_circle (Point const &pt)
[signed_dist_to_unit_circle]
template<typename T >
decltype(DGtal::functors::holdFunctor(Binarizer< T >(128))) get_trivial_binarizer ()
template<typename Iterator >
auto get_mean_binarizer_from_range (Iterator first, Iterator last) -> decltype(DGtal::functors::holdFunctor(Binarizer< decltype(*first/std::distance(first, last))>(0)))
[Returning a FunctorHolder]
template<typename Image >
auto get_mean_binarizer_from_an_image (std::string const &file_name) -> decltype(get_mean_binarizer_from_range(std::declval< Image >().begin(), std::declval< Image >().end()))
[Returning a FunctorHolder using trailing return]
template<typename T >
Binarizer< T > makeBinarizer (T const &v)
[Returning a FunctorHolder using trailing return and declval]
template<typename PointFunctor , typename Predicate >
DGtal::functors::PointFunctorPredicate< PointFunctor, Predicate > makePointFunctorPredicate_Example (PointFunctor const &aFun, Predicate const &aPred)
[Factory of Binarizer]
template<typename PointFunctor , typename Predicate >
DGtal::functors::PointFunctorPredicate< typename std::decay< PointFunctor >::type, typename std::decay< Predicate >::type > makePointFunctorPredicate_Example2 (PointFunctor &&aFun, Predicate &&aPred)
[Factory of PointFunctorPredicate]
int main ()
[Factory of PointFunctorPredicate using perfect forwarding]
Detailed Description
An example file for DGtal::functors::FunctorHolder and DGtal::functors::holdFunctor.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Roland Denis (denis.nosp@m.@mat.nosp@m.h.uni.nosp@m.v-ly.nosp@m.on1.f.nosp@m.r) CNRS, Institut Camille Jordan (UMR 5208), Université Lyon 1, France
Date
2018/07/17
This file is part of the DGtal library.
Definition in file exampleFunctorHolder.cpp.
Function Documentation
get_mean_binarizer_from_an_image()
template<typename Image > auto get_mean_binarizer_from_an_image (std::string const & file_name) -> decltype(get_mean_binarizer_from_range(std::declval<Image>().begin(), std::declval<Image>().end()))
[Returning a FunctorHolder using trailing return]
[Returning a FunctorHolder using trailing return and declval]
Definition at line 123 of file exampleFunctorHolder.cpp.
{
  Image const image = DGtal::GenericReader<Image>::import(file_name);
  return get_mean_binarizer_from_range(image.begin(), image.end());
}
References get_mean_binarizer_from_range(), and DGtal::GenericReader< TContainer, Tdim, TValue >::import().
Referenced by main().
get_mean_binarizer_from_range()
template<typename Iterator > auto get_mean_binarizer_from_range (Iterator first, Iterator last) -> decltype(DGtal::functors::holdFunctor(Binarizer<decltype(*first / std::distance(first, last))>(0)))
[Returning a FunctorHolder]
[Returning a FunctorHolder using trailing return]
Definition at line 110 of file exampleFunctorHolder.cpp.
{
  using value_type = typename std::iterator_traits<Iterator>::value_type;
  auto const mean = std::accumulate(first, last, value_type(0));
  auto const size = std::distance(first, last);
  return DGtal::functors::holdFunctor(Binarizer<decltype(mean / size)>(mean / size));
}
References DGtal::functors::holdFunctor().
Referenced by get_mean_binarizer_from_an_image(), and main().
get_trivial_binarizer()
template<typename T > decltype(DGtal::functors::holdFunctor(Binarizer< T >(128))) get_trivial_binarizer () inline
Definition at line 102 of file exampleFunctorHolder.cpp.
{
  return DGtal::functors::holdFunctor( Binarizer<T>(128) );
}
References DGtal::functors::holdFunctor().
Referenced by main().
main()
int main (void)
[Factory of PointFunctorPredicate using perfect forwarding]
[Holding a function]
[Holding a function]
[Holding a templated function]
[Holding a templated function]
[Holding a function through a lambda]
[Holding a function through a lambda]
[Holding a templated function through a lambda]
[Holding a templated function through a lambda]
[Holding a functor by lvalue ref]
[Holding a functor by lvalue ref]
[Holding a functor by rvalue ref]
[Holding a functor by rvalue ref]
[Holding a functor by moving it]
[Holding a functor by moving it]
[Holding a lambda]
[Holding a lambda]
[Holding a non-unary lambda]
[Holding a non-unary lambda]
[Copying a functor by lvalue ref]
[Copying a functor by lvalue ref]
[Copying a lambda by rvalue ref]
[Copying a lambda by rvalue ref]
[Storing a FunctorHolder]
[Storing a FunctorHolder]
[Passing a FunctorHolder]
[Passing a FunctorHolder]
[Returning a FunctorHolder in caller]
[Returning a FunctorHolder in caller]
[Returning a FunctorHolder using trailing return in caller]
[Returning a FunctorHolder using trailing return in caller]
[Using the Binarizer factory]
[Using the Binarizer factory]
[Using the PointFunctorPredicate factory]
[Using the PointFunctorPredicate factory]
Definition at line 204 of file exampleFunctorHolder.cpp.
{
  // Holding a function
  {
    std::cout << "Holding a function" << std::endl;
    auto fn = DGtal::functors::holdFunctor( signed_dist_to_unit_circle );
    using Point = DGtal::PointVector<2, double>;
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a templated function" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto fn = DGtal::functors::holdFunctor( templated_signed_dist_to_unit_circle<Point> );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a function through a lambda" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto fn = DGtal::functors::holdFunctor( [] (Point const& pt) { return signed_dist_to_unit_circle(pt); } );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a templated function through a lambda" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto fn = DGtal::functors::holdFunctor( [] (Point const& pt) { return templated_signed_dist_to_unit_circle(pt); } );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
#if __cplusplus >= 201402L
  {
    std::cout << "Holding a templated function through a C++14 lambda" << std::endl;
    auto fn = DGtal::functors::holdFunctor( [] (auto const& pt) { return templated_signed_dist_to_unit_circle(pt); } );
    using Point = DGtal::PointVector<2, double>;
    std::cout << fn( Point(1, 1) ) << std::endl; // <- template parameter is resolved to Point
  }
#endif
  // Holding a functor
  {
    std::cout << "Holding a functor by (lvalue) reference" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    SignedDistToCircle<Point> dist(Point(0, 1), 2);
    auto fn = DGtal::functors::holdFunctor( dist );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a functor by rvalue reference" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto fn = DGtal::functors::holdFunctor( SignedDistToCircle<Point>( Point(0, 1), 2 ) );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a functor by moving it" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    SignedDistToCircle<Point> dist(Point(0, 1), 2);
    auto fn = DGtal::functors::holdFunctor( std::move(dist) );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  // Holding a lambda
  {
    std::cout << "Holding a lambda" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    Point center(0, 1);
    double radius = 2;
    auto fn = DGtal::functors::holdFunctor(
        [&center, &radius] (Point const& pt) {
            return (pt - center).norm() - radius;
        }
    );
    std::cout << fn( Point(1, 1) ) << std::endl;
  }
  {
    std::cout << "Holding a non-unary lambda" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto dist = [] (Point const& pt, Point const& center, double radius)
      {
        return (pt - center).norm() - radius;
      };
    auto fn = DGtal::functors::holdFunctor( dist );
    std::cout << fn( Point(1, 1), Point(0, 1), 2 ) << std::endl;
  }
  // Copying
  {
    std::cout << "Copying a functor held by lvalue reference" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    SignedDistToCircle<Point> dist(Point(0, 1), 2);
    auto fn = DGtal::functors::holdFunctor( dist );
    auto fn2 = fn;
    std::cout << fn( Point(1, 1) ) << std::endl;  // Output: -1
    std::cout << fn2( Point(1, 1) ) << std::endl; // Output: -1
    dist.radius = 3; // fn and fn2 both refer to the same functor dist.
    std::cout << fn( Point(1, 1) ) << std::endl;  // Output: -2
    std::cout << fn2( Point(1, 1) ) << std::endl; // Output: -2
  }
  {
    std::cout << "Copying a lambda held by rvalue reference" << std::endl;
    int init_cnt = 0;
    auto fn = DGtal::functors::holdFunctor( [init_cnt] () mutable { return ++init_cnt; } );
    std::cout << fn() << std::endl;  // Output: 1
    auto fn2 = fn;
    std::cout << fn2() << std::endl; // Output: 2
    std::cout << fn() << std::endl;  // Output: 3
  }
  // Type of FunctorHolder
  {
    std::cout << "Storing a FunctorHolder" << std::endl;
    using Point = DGtal::PointVector<2, double>;
    auto fn = DGtal::functors::holdFunctor( SignedDistToCircle<Point>( Point(0, 1), 2 ) );
  }
  {
    std::cout << "Passing a FunctorHolder" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = DGtal::functors::holdFunctor( [] (Image::Value v) { return v <= 135; } );
    DGtal::functors::PointFunctorPredicate<Image, decltype(binarizer)> predicate(image, binarizer);
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  {
    std::cout << "Returning a functor" << std::endl;
    auto binarizer = get_trivial_binarizer<int>();
    std::cout << "binarizer(120) = " << binarizer(120) << std::endl;
  }
  {
    std::cout << "Returning a functor using trailing return syntax" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = get_mean_binarizer_from_range(image.begin(), image.end());
    DGtal::functors::PointFunctorPredicate<Image, decltype(binarizer)> predicate(image, binarizer);
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  {
    std::cout << "Returning a functor using trailing return syntax and declval" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    auto binarizer = get_mean_binarizer_from_an_image<Image>(filename);
    std::cout << "binarizer(120) = " << binarizer(120) << std::endl;
  }
  #if __cplusplus >= 201402L
  {
    std::cout << "Returning a functor using auto in C++14" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = get_mean_binarizer_from_range_cpp14(image.begin(), image.end());
    DGtal::functors::PointFunctorPredicate<Image, decltype(binarizer)> predicate(image, binarizer);
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  #endif
  {
    std::cout << "Usage of Binarizer factory" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = DGtal::functors::holdFunctor( makeBinarizer(135) );
    DGtal::functors::PointFunctorPredicate<Image, decltype(binarizer)> predicate(image, binarizer);
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  #if __cplusplus >= 201703L
  {
    std::cout << "Binarizer factory using deduction guides of C++17" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = DGtal::functors::holdFunctor( Binarizer(135) ); // Binarizer template parameter is not specified.
    DGtal::functors::PointFunctorPredicate<Image, decltype(binarizer)> predicate(image, binarizer);
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  #endif
  {
    std::cout << "Usage of PointFunctorPredicate factory" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = DGtal::functors::holdFunctor( makeBinarizer(135) );
    auto predicate = makePointFunctorPredicate_Example( image, binarizer );
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  {
    std::cout << "Usage of PointFunctorPredicate factory with perfect forwarding" << std::endl;
    //image import
    using Image = DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, int>;
    using Point = Image::Point;
    std::string filename =  examplesPath + "samples/contourS.pgm";
    Image image = DGtal::PGMReader<Image>::importPGM(filename);
    auto binarizer = DGtal::functors::holdFunctor( makeBinarizer(135) );
    auto predicate = makePointFunctorPredicate_Example2( image, binarizer );
    Point const pt(50, 25);
    std::cout << "binarizer(" << image( pt ) << ") = " << predicate( pt ) << std::endl;
  }
  return 0;
}
References get_mean_binarizer_from_an_image(), get_mean_binarizer_from_range(), get_trivial_binarizer(), DGtal::functors::holdFunctor(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), makeBinarizer(), makePointFunctorPredicate_Example(), makePointFunctorPredicate_Example2(), signed_dist_to_unit_circle(), and templated_signed_dist_to_unit_circle().
makeBinarizer()
template<typename T > Binarizer< T > makeBinarizer (T const & v) inline
[Returning a FunctorHolder using trailing return and declval]
[Factory of Binarizer]
Definition at line 148 of file exampleFunctorHolder.cpp.
{
  return Binarizer<T>(v);
}
Referenced by main().
makePointFunctorPredicate_Example()
template<typename PointFunctor , typename Predicate > DGtal::functors::PointFunctorPredicate< PointFunctor, Predicate > makePointFunctorPredicate_Example (PointFunctor const & aFun, Predicate const & aPred)
[Factory of Binarizer]
[Factory of PointFunctorPredicate]
Definition at line 176 of file exampleFunctorHolder.cpp.
{
  return DGtal::functors::PointFunctorPredicate<PointFunctor, Predicate>( aFun, aPred );
}
Referenced by main().
makePointFunctorPredicate_Example2()
template<typename PointFunctor , typename Predicate > DGtal::functors::PointFunctorPredicate< typename std::decay< PointFunctor >::type, typename std::decay< Predicate >::type > makePointFunctorPredicate_Example2 (PointFunctor && aFun, Predicate && aPred)
[Factory of PointFunctorPredicate]
[Factory of PointFunctorPredicate using perfect forwarding]
Definition at line 191 of file exampleFunctorHolder.cpp.
{
  return DGtal::functors::PointFunctorPredicate<
      typename std::decay<PointFunctor>::type,
      typename std::decay<Predicate>::type
  >(
    std::forward<PointFunctor>(aFun),
    std::forward<Predicate>(aPred)
  );
}
Referenced by main().
signed_dist_to_unit_circle()
double signed_dist_to_unit_circle (DGtal::PointVector< 2, double > const & pt) inline
[signed_dist_to_unit_circle]
Definition at line 52 of file exampleFunctorHolder.cpp.
{
  return pt.norm() - 1.;
}
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm().
Referenced by main().
templated_signed_dist_to_unit_circle()
template<typename Point > Point::Component templated_signed_dist_to_unit_circle (Point const & pt) inline
[signed_dist_to_unit_circle]
[Templated signed_dist_to_unit_circle]
Definition at line 62 of file exampleFunctorHolder.cpp.
{
  return pt.norm() - typename Point::Component(1);
}
Referenced by main().