DGtal: fullConvexityCollapsiblePoints2D.cpp File Reference
fullConvexityCollapsiblePoints2D.cpp File Reference
DGtal Examples
#include <vector>
#include "DGtal/shapes/Shapes.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/geometry/volumes/DigitalConvexity.h"
#include "DGtal/geometry/volumes/NeighborhoodConvexityAnalyzer.h"
#include "DGtal/helpers/Shortcuts.h"
#include "ConfigExamples.h"
Typedefs
typedef DigitalConvexity< KSpace > DConv
typedef Shortcuts< KSpace > SH2
typedef NeighborhoodConvexityAnalyzer< KSpace, 1 > NCA1
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/06/22
An example file named fullConvexityCollapsiblePoints2D.
This file is part of the DGtal library.
Definition in file fullConvexityCollapsiblePoints2D.cpp.
Typedef Documentation
DConv
typedef DigitalConvexity< KSpace > DConv
Examples
geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, and geometry/volumes/fullConvexityLUT2D.cpp.
Definition at line 56 of file fullConvexityCollapsiblePoints2D.cpp.
NCA1
typedef NeighborhoodConvexityAnalyzer<KSpace,1> NCA1
Examples
geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, and geometry/volumes/fullConvexityLUT2D.cpp.
Definition at line 58 of file fullConvexityCollapsiblePoints2D.cpp.
SH2
typedef Shortcuts<KSpace> SH2
Examples
geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, and geometry/volumes/fullConvexityLUT2D.cpp.
Definition at line 57 of file fullConvexityCollapsiblePoints2D.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 61 of file fullConvexityCollapsiblePoints2D.cpp.
{
  double noise = argc > 1 ? atof( argv[ 1 ] ) : 0.1;
  auto params  = SH2::defaultParameters();
  params( "noise", noise )( "thresholdMin", 128 );
  auto g_image = SH2::makeGrayScaleImage( examplesPath + "samples/contourS.pgm" );
  auto b_image = SH2::makeBinaryImage   ( g_image, params );
  Board2D board;
  Domain image_domain = b_image->domain();
  NCA1 nca1( image_domain.lowerBound(), image_domain.upperBound() );
  for ( auto p : image_domain )
    {
      nca1.setCenter( p, (*b_image) );
      bool simple = nca1.isFullyConvexCollapsible();
      if ( (*b_image)( p ) )
        board << CustomStyle( p.className(),
                              simple
                              ? new CustomColors( Color( 0, 0, 0 ),
                                                  Color( 10, 255, 10 ) )
                              : new CustomColors( Color( 0, 0, 0 ),
                                                  Color( 255, 10, 10 ) ) );
      else
        board << CustomStyle( p.className(),
                              simple
                              ? new CustomColors( Color( 0, 0, 0 ),
                                                  Color( 180, 255, 180 ) )
                              : new CustomColors( Color( 0, 0, 0 ),
                                                  Color( 255, 180, 180 ) ) );
      board << p;
    }
  board.saveEPS( "contour-fcvx-collapsible.eps" );
  return 0;
}
References DGtal::Shortcuts< TKSpace >::defaultParameters(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), DGtal::HyperRectDomain< TSpace >::lowerBound(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeGrayScaleImage(), LibBoard::Board::saveEPS(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::setCenter(), and DGtal::HyperRectDomain< TSpace >::upperBound().