DGtal: imageBasicSubsampling.cpp File Reference
imageBasicSubsampling.cpp File Reference
DGtal Examples
#include <iostream>
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/kernel/BasicPointFunctors.h"
#include "DGtal/images/ConstImageAdapter.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/io/readers/GenericReader.h"
#include "DGtal/io/writers/GenericWriter.h"
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2014/05/21
An example file named imageBasicSubsampling.
This file is part of the DGtal library.
Definition in file imageBasicSubsampling.cpp.
Function Documentation
main()
int main (int , char **)
[imageBasicSubsamplingType2D]
[imageBasicSubsamplingType2D]
[imageBasicSubsamplingType3D]
[imageBasicSubsamplingType3D]
[imageBasicSubsamplingSubSampler2D]
[imageBasicSubsamplingSubSampler2D]
[imageBasicSubsamplingConstImageAdapterSubSampling2D]
[imageBasicSubsamplingConstImageAdapterSubSampling2D]
[imageBasicSubsamplingExport2D]
[imageBasicSubsamplingExport2D]
[imageBasicSubsamplingSubSampler3D]
[imageBasicSubsamplingSubSampler3D]
[imageBasicSubsamplingConstImageAdapterSubSampling3D]
[imageBasicSubsamplingConstImageAdapterSubSampling3D]
[imageBasicSubsamplingExport3D]
[imageBasicSubsamplingExport3D]
Definition at line 63 of file imageBasicSubsampling.cpp.
{
  typedef ImageContainerBySTLVector < Z2i::Domain, unsigned char> Image2D;
  typedef ConstImageAdapter<Image2D,  Image2D::Domain,
                            functors::BasicDomainSubSampler<Image2D::Domain>,
                            Image2D::Value,
                            functors::Identity > ConstImageAdapterForSubSampling;
  typedef ImageContainerBySTLVector < Z3i::Domain, unsigned char> Image3D;
  typedef ConstImageAdapter<Image3D,  Image3D::Domain,
                            functors::BasicDomainSubSampler<Image3D::Domain>,
                            Image3D::Value,
                            functors::Identity > ConstImageAdapterForSubSampling3D;
  trace.beginBlock ( "Example imageBasicSubsampling" );
  std::string imageFilename3D = examplesPath + "samples/Al.100.vol";
  std::string imageFilename2D = examplesPath + "samples/church.pgm";
  Image3D image3D = GenericReader<Image3D>::import( imageFilename3D );
  Image2D image2D = GenericReader<Image2D>::import( imageFilename2D );
  for (unsigned int i=1; i<=20; i*=2){
    std::vector<Z2i::Domain::Size> aGridSize2D;
    aGridSize2D.push_back(i);
    aGridSize2D.push_back(i);
    // Construction of the functor for the 2D domain subsampling from a given grid size and shift.
    DGtal::functors::BasicDomainSubSampler<Image2D::Domain> subSampler2D(image2D.domain(), aGridSize2D, Z2i::Point(0 ,0));
    functors::Identity df;
    // Get the new domain produces from the subsampler and define the ConstImageAdapter:
    Image2D::Domain subSampledDomain2D  = subSampler2D.getSubSampledDomain();
    ConstImageAdapterForSubSampling subsampledImage2D (image2D, subSampledDomain2D, subSampler2D, df);
    stringstream outputname;
    outputname << "subSampledImage"<< i<< "x"<< i << ".pgm" ;
    GenericWriter<ConstImageAdapterForSubSampling>::exportFile(outputname.str(), subsampledImage2D );
    trace.info() << "Exporting 2D subsampled image by grid size :" << i << "x"<< i<< " in "<< outputname.str() << std::endl;
  }
  for (unsigned int i=1; i<=20; i*=2){
    std::vector<Z3i::Domain::Size> aGridSize3D;
    aGridSize3D.push_back(i);
    aGridSize3D.push_back(i);
    aGridSize3D.push_back(i);
        // Construction of the functor for the 3D domain subsampling from a given grid size and shift.
    DGtal::functors::BasicDomainSubSampler<Image3D::Domain> subSampler3D(image3D.domain(), aGridSize3D, Z3i::Point(0 ,0, 0));
    DGtal::functors::Identity df;
    // Get the new domain produces from the subsampler and define the ConstImageAdapter:
    Image3D::Domain subSampledDomain3D  = subSampler3D.getSubSampledDomain();
    ConstImageAdapterForSubSampling3D subsampledImage3D (image3D, subSampledDomain3D, subSampler3D, df);
    stringstream outputname3D;
    outputname3D << "subSampledImage3D"<< i<< "x"<< i << ".vol" ;
    GenericWriter<ConstImageAdapterForSubSampling3D>::exportFile(outputname3D.str(), subsampledImage3D );
    trace.info() << "Exporting 3D subsampled image by grid size :" << i << "x"<< i<< "x"<< i<< " in "<< outputname3D.str() << std::endl;
  }
  trace.endBlock();
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::GenericWriter< TContainer, Tdim, TValue, TFunctor >::exportFile(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::getSubSampledDomain(), DGtal::GenericReader< TContainer, Tdim, TValue >::import(), DGtal::Trace::info(), and DGtal::trace.