DGtal: DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator Struct Reference
DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator Struct Reference
#include <DGtal/topology/CubicalComplex.h>
Public Types
typedef boost::iterator_facade< Iterator, Cell const, std::forward_iterator_tag > Base
typedef Iterator Self
typedef Base::value_type Value
typedef Base::pointer Pointer
typedef Base::reference Reference
typedef Base::difference_type DifferenceType
Public Member Functions
Iterator ()
Default iterator. Invalid.
Iterator (Alias< CubicalComplex > cc, Dimension d)
Iterator (Alias< CubicalComplex > cc, Dimension d, CellMapIterator it)
Private Member Functions
void nextDimension ()
void increment ()
bool equal (const Iterator &other) const
Cell const & dereference () const
Dimension dimension () const
Private Attributes
CubicalComplex * myCC
Dimension myD
CellMapIterator myIt
CellMapIterator myItEnd
Friends
class CubicalComplex
class boost::iterator_core_access
Detailed Description
template<typename TKSpace, typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type>
struct DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator
A mutable iterator class to visit all the cells (and not their datas) of the complex. A model of boost::ForwardIterator. Note that, as for associative container, values are not modifiable.
Definition at line 411 of file CubicalComplex.h.
Member Typedef Documentation
Base
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> boost::iterator_facade< Iterator, Cell const, std::forward_iterator_tag > DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Base
Definition at line 418 of file CubicalComplex.h.
DifferenceType
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::difference_type DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::DifferenceType
Definition at line 423 of file CubicalComplex.h.
Pointer
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::pointer DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Pointer
Definition at line 421 of file CubicalComplex.h.
Reference
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::reference DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Reference
Definition at line 422 of file CubicalComplex.h.
Self
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Iterator DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Self
Definition at line 419 of file CubicalComplex.h.
Value
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::value_type DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Value
Definition at line 420 of file CubicalComplex.h.
Constructor & Destructor Documentation
Iterator() [1/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator () inline
Default iterator. Invalid.
Definition at line 426 of file CubicalComplex.h.
: myCC(0), myD(0) {}
Iterator() [2/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator (Alias< CubicalComplex > cc, Dimension d) inline
Constructor from complex cc and cell dimension d.
Parameters
cc any valid cubical complex that is aliased in the iterator.
d the dimension of the starting cell.
Definition at line 435 of file CubicalComplex.h.
        : myCC( &cc ), myD( d )
      {
        if ( myD <= myCC->dimension )
          {
            myIt    = myCC->begin( myD );
            myItEnd = myCC->end( myD );
            nextDimension();
          }
        else
          {
            myD     = myCC->dimension + 1;
            myIt    = myCC->end( myCC->dimension );
            myItEnd = myCC->end( myCC->dimension );
          }
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::begin(), DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myD, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myItEnd, and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
Iterator() [3/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator (Alias< CubicalComplex > cc, Dimension d, CellMapIterator it) inline
Detailed constructor from complex cc, cell dimension d and iterators.
Parameters
cc any valid cubical complex that is aliased in the iterator.
d the dimension of the starting cell (0<=d<=dimension).
it an iterator pointing on a cell of the complex.
Definition at line 459 of file CubicalComplex.h.
        : myCC( &cc ), myD( d ), myIt( it )
      {
        ASSERT( d <= myCC->dimension );
        myItEnd = myCC->end( d );
        nextDimension();
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myItEnd, and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
Member Function Documentation
dereference()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Cell const & DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dereference () const inline private
Definition at line 493 of file CubicalComplex.h.
      {
        return myIt->first;
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt.
dimension()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Dimension DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dimension () const inline private
Definition at line 498 of file CubicalComplex.h.
      {
        return myD;
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myD.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator().
equal()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> bool DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::equal (const Iterator & other) const inline private
Definition at line 488 of file CubicalComplex.h.
      {
        return ( myD == other.myD ) && ( myIt == other.myIt );
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myD, and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt.
increment()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> void DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::increment () inline private
Definition at line 481 of file CubicalComplex.h.
      {
        ASSERT( myCC != 0 );
        ++myIt;
        nextDimension();
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt, and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
nextDimension()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> void DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension () inline private
Definition at line 471 of file CubicalComplex.h.
      {
        while ( myIt == myItEnd )
          {
            if ( ++myD > myCC->dimension ) break;
            myIt    = myCC->begin( myD );
            myItEnd = myCC->end( myD );
          }
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::begin(), DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myD, DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt, and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myItEnd.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::increment(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator().
Friends And Related Symbol Documentation
boost::iterator_core_access
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> friend class boost::iterator_core_access friend
Definition at line 469 of file CubicalComplex.h.
CubicalComplex
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> friend class CubicalComplex friend
Definition at line 415 of file CubicalComplex.h.
Field Documentation
myCC
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> CubicalComplex* DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myCC private
Definition at line 504 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::increment(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
myD
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Dimension DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myD private
Definition at line 505 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::equal(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
myIt
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> CellMapIterator DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myIt private
Definition at line 506 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::dereference(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::equal(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::increment(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
myItEnd
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> CellMapIterator DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::myItEnd private
Definition at line 507 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::Iterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::Iterator::nextDimension().
The documentation for this struct was generated from the following file:
CubicalComplex.h