DGtal: DGtal::concepts::CDigitalSurfaceEmbedder< T > Struct Template Reference
DGtal::concepts::CDigitalSurfaceEmbedder< T > Struct Template Reference
DGtal Concepts
Aim: A digital surface embedder is a specialized mapping from signed cells to Euclidean points. It adds inner types to functor as well as a method to access the digital surface.
#include <DGtal/topology/CDigitalSurfaceEmbedder.h>
Public Types
typedef T::KSpace KSpace
typedef T::Surface Surface
typedef T::SCell SCell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Types inherited from DGtal::concepts::CSCellEmbedder< T >
typedef T::KSpace KSpace
typedef T::SCell SCell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_USAGE (CDigitalSurfaceEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CSCellEmbedder< T >
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename KSpace::SCell >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CSCellEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CUnaryFunctor< T, T::SCell, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Surface mySurface
Detailed Description
template<typename T>
struct DGtal::concepts::CDigitalSurfaceEmbedder< T >
Aim: A digital surface embedder is a specialized mapping from signed cells to Euclidean points. It adds inner types to functor as well as a method to access the digital surface.
Description of concept 'CDigitalSurfaceEmbedder'
Refinement of
CSCellEmbedder<T>
Associated types
KSpace: the cellular grid space
SCell: same as KSpace::SCell
RealPoint: the type of Euclidean point
Surface: a digital surface, some concrete DigitalSurface<X>.
Argument: type of the argument, same as SCell
Value: type of value, same as RealPoint
Notation
X : A type that is a model of CDigitalSurfaceEmbedder
x : object of type X
p : object of type SCell
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Accessor to surface x.surface() Surface return the associated digital surface
Invariants
Models
Notes
Template Parameters
T the type that should be a model of CDigitalSurfaceEmbedder.
Definition at line 96 of file CDigitalSurfaceEmbedder.h.
Member Typedef Documentation
Argument
template<typename T > T::Argument DGtal::concepts::CDigitalSurfaceEmbedder< T >::Argument
Definition at line 104 of file CDigitalSurfaceEmbedder.h.
KSpace
template<typename T > T::KSpace DGtal::concepts::CDigitalSurfaceEmbedder< T >::KSpace
Definition at line 100 of file CDigitalSurfaceEmbedder.h.
RealPoint
template<typename T > T::RealPoint DGtal::concepts::CDigitalSurfaceEmbedder< T >::RealPoint
Definition at line 103 of file CDigitalSurfaceEmbedder.h.
SCell
template<typename T > T::SCell DGtal::concepts::CDigitalSurfaceEmbedder< T >::SCell
Definition at line 102 of file CDigitalSurfaceEmbedder.h.
Surface
template<typename T > T::Surface DGtal::concepts::CDigitalSurfaceEmbedder< T >::Surface
Definition at line 101 of file CDigitalSurfaceEmbedder.h.
Value
template<typename T > T::Value DGtal::concepts::CDigitalSurfaceEmbedder< T >::Value
Definition at line 105 of file CDigitalSurfaceEmbedder.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CDigitalSurfaceEmbedder< T >::BOOST_CONCEPT_USAGE (CDigitalSurfaceEmbedder< T >) inline
Definition at line 113 of file CDigitalSurfaceEmbedder.h.
  {
    checkConstConstraints();
  }
References DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints () const inline
Definition at line 118 of file CDigitalSurfaceEmbedder.h.
  { // operator()
    // ConceptUtils::sameType( myRP, myX( myP ) );
    ConceptUtils::sameType( mySurface, myX.surface() );
  }
References DGtal::concepts::CDigitalSurfaceEmbedder< T >::mySurface, DGtal::concepts::CDigitalSurfaceEmbedder< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CDigitalSurfaceEmbedder< T >::BOOST_CONCEPT_USAGE().
Field Documentation
mySurface
template<typename T > Surface DGtal::concepts::CDigitalSurfaceEmbedder< T >::mySurface private
Definition at line 128 of file CDigitalSurfaceEmbedder.h.
Referenced by DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CDigitalSurfaceEmbedder< T >::myX private
Definition at line 125 of file CDigitalSurfaceEmbedder.h.
Referenced by DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CDigitalSurfaceEmbedder.h