DGtal: LibBoard::Transform Struct Reference
LibBoard::Transform Struct Reference abstract
base class for transforms.
#include <Board/Transforms.h>
Public Member Functions
Transform ()
virtual ~Transform ()
virtual double mapX (double x) const
virtual double mapY (double y) const =0
virtual void apply (double &x, double &y) const
virtual double scale (double x) const
virtual double rounded (double x) const
virtual void setBoundingBox (const Rect &rect, const double pageWidth, const double pageHeight, const double margin)=0
Static Public Member Functions
static double round (const double &x)
Protected Attributes
double _scale
double _deltaX
double _deltaY
double _height
Detailed Description
base class for transforms.
The base class for transforms.
Definition at line 31 of file Transforms.h.
Constructor & Destructor Documentation
Transform()
LibBoard::Transform::Transform () inline
Definition at line 6 of file Transforms.h.
                   {
struct Rect;
struct Shape;
struct ShapeList;
struct Transform {
public:
  inline Transform();
  virtual ~Transform() { };
  virtual double mapX( double x ) const;
  virtual double mapY( double y ) const = 0;
  virtual void apply( double & x, double & y ) const;
  virtual double scale( double x ) const;
  virtual double rounded( double x ) const;
  virtual void setBoundingBox( const Rect & rect,
             const double pageWidth,
             const double pageHeight,
             const double margin ) = 0;
  static inline double round( const double & x );
protected:
  double _scale;
  double _deltaX;
  double _deltaY;
  double _height;
};
struct TransformEPS : public Transform {
public:
  double mapY( double y ) const;
  void setBoundingBox( const Rect & rect,
           const double pageWidth,
           const double pageHeight,
           const double margin );
};
struct TransformFIG : public Transform {
public:
  inline TransformFIG();
  double rounded( double x ) const;
  double mapY( double y ) const;
  int mapWidth( double width ) const;
  void setBoundingBox( const Rect & rect,
           const double pageWidth,
           const double pageHeight,
           const double margin );
  void setDepthRange( const ShapeList & shapes );
  int mapDepth( int depth ) const;
private:
  int _maxDepth;
  int _minDepth;
};
struct TransformSVG : public Transform {
public:
  double rounded( double x ) const;
  double mapY( double y ) const;
  double mapWidth( double width ) const;
  void setBoundingBox( const Rect & rect,
           const double pageWidth,
           const double pageHeight,
           const double margin );
};
#ifdef WITH_CAIRO
struct TransformCairo : public Transform {
public:
  double rounded( double x ) const;
  double mapY( double y ) const;
  double mapWidth( double width ) const;
  void setBoundingBox( const Rect & rect,
           const double pageWidth,
           const double pageHeight,
           const double margin );
};
#endif
struct TransformTikZ : public TransformSVG {
};
#include "Transforms.ih"
} // namespace LibBoard
#endif /* _TRANSFORMS_H_ */
~Transform()
virtual LibBoard::Transform::~Transform () inline virtual
Definition at line 34 of file Transforms.h.
{ };
Member Function Documentation
apply()
void LibBoard::Transform::apply (double & x, double & y) const virtual
Definition at line 51 of file Transforms.cpp.
{
  x = mapX( x );
  y = mapY( y );
}
References mapX(), and mapY().
mapX()
double LibBoard::Transform::mapX (double x) const virtual
Definition at line 39 of file Transforms.cpp.
{
  return rounded( x * _scale + _deltaX );
}
References _deltaX, _scale, and rounded().
Referenced by apply().
mapY()
virtual double LibBoard::Transform::mapY (double y) const pure virtual
Implemented in LibBoard::TransformCairo, LibBoard::TransformEPS, LibBoard::TransformFIG, and LibBoard::TransformSVG.
Referenced by apply().
round()
double LibBoard::Transform::round (const double & x) inline static
Definition at line 15 of file Transforms.h.
Referenced by LibBoard::TransformFIG::mapDepth(), LibBoard::TransformCairo::mapWidth(), LibBoard::TransformFIG::mapWidth(), LibBoard::TransformSVG::mapWidth(), rounded(), LibBoard::TransformCairo::rounded(), LibBoard::TransformFIG::rounded(), and LibBoard::TransformSVG::rounded().
rounded()
double LibBoard::Transform::rounded (double x) const virtual
Reimplemented in LibBoard::TransformCairo, LibBoard::TransformFIG, and LibBoard::TransformSVG.
Definition at line 33 of file Transforms.cpp.
{
  return Transform::round( 1000000*x ) / 1000000;
}
References round().
Referenced by mapX(), LibBoard::TransformEPS::mapY(), and scale().
scale()
double LibBoard::Transform::scale (double x) const virtual
Definition at line 45 of file Transforms.cpp.
{
  return rounded( x * _scale );
}
References _scale, and rounded().
setBoundingBox()
virtual void LibBoard::Transform::setBoundingBox (const Rect & rect, const double pageWidth, const double pageHeight, const double margin) pure virtual
Implemented in LibBoard::TransformCairo, LibBoard::TransformEPS, LibBoard::TransformFIG, and LibBoard::TransformSVG.
Field Documentation
_deltaX
double LibBoard::Transform::_deltaX protected
Definition at line 49 of file Transforms.h.
Referenced by mapX(), LibBoard::TransformCairo::setBoundingBox(), LibBoard::TransformEPS::setBoundingBox(), LibBoard::TransformFIG::setBoundingBox(), and LibBoard::TransformSVG::setBoundingBox().
_deltaY
double LibBoard::Transform::_deltaY protected
Definition at line 50 of file Transforms.h.
Referenced by LibBoard::TransformCairo::mapY(), LibBoard::TransformEPS::mapY(), LibBoard::TransformFIG::mapY(), LibBoard::TransformSVG::mapY(), LibBoard::TransformCairo::setBoundingBox(), LibBoard::TransformEPS::setBoundingBox(), LibBoard::TransformFIG::setBoundingBox(), and LibBoard::TransformSVG::setBoundingBox().
_height
double LibBoard::Transform::_height protected
Definition at line 51 of file Transforms.h.
Referenced by LibBoard::TransformCairo::mapY(), LibBoard::TransformFIG::mapY(), LibBoard::TransformSVG::mapY(), LibBoard::TransformCairo::setBoundingBox(), LibBoard::TransformEPS::setBoundingBox(), LibBoard::TransformFIG::setBoundingBox(), and LibBoard::TransformSVG::setBoundingBox().
_scale
double LibBoard::Transform::_scale protected
Definition at line 48 of file Transforms.h.
Referenced by mapX(), LibBoard::TransformCairo::mapY(), LibBoard::TransformEPS::mapY(), LibBoard::TransformFIG::mapY(), LibBoard::TransformSVG::mapY(), scale(), LibBoard::TransformCairo::setBoundingBox(), LibBoard::TransformEPS::setBoundingBox(), LibBoard::TransformFIG::setBoundingBox(), and LibBoard::TransformSVG::setBoundingBox().
The documentation for this struct was generated from the following files:
Transforms.h
Transforms.cpp