DGtal: DGtal::concepts::C3DParametricCurve< T > Struct Template Reference
DGtal::concepts::C3DParametricCurve< T > Struct Template Reference
DGtal Concepts
Aim:
#include <DGtal/geometry/curves/parametric/C3DParametricCurve.h>
Public Types
typedef T::Space Space
typedef T::RealPoint RealPoint
typedef T::Point Point
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CSpace< Space >))
BOOST_STATIC_ASSERT ((Space::dimension==3))
BOOST_CONCEPT_USAGE (C3DParametricCurve)
virtual void checkConstConstraints () const
Protected Attributes
T self
RealPoint x
Point y
double c
Detailed Description
template<typename T>
struct DGtal::concepts::C3DParametricCurve< T >
Aim:
Description of concept '3DParametricCurve'
Refinement of
Associated types
Notation
X : A type that is a model of 3DParametricCurve
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Invariants
Models
A dummy model (for concept checking) is C3DParametricCurveArchetype.
Notes
Template Parameters
T the type that should be a model of 3DParametricCurve.
Definition at line 87 of file C3DParametricCurve.h.
Member Typedef Documentation
Point
template<typename T > T::Point DGtal::concepts::C3DParametricCurve< T >::Point
Definition at line 93 of file C3DParametricCurve.h.
RealPoint
template<typename T > T::RealPoint DGtal::concepts::C3DParametricCurve< T >::RealPoint
Definition at line 92 of file C3DParametricCurve.h.
Space
template<typename T > T::Space DGtal::concepts::C3DParametricCurve< T >::Space
Definition at line 91 of file C3DParametricCurve.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::C3DParametricCurve< T >::BOOST_CONCEPT_ASSERT ((concepts::CSpace< Space >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::C3DParametricCurve< T >::BOOST_CONCEPT_USAGE (C3DParametricCurve< T >) inline
Definition at line 97 of file C3DParametricCurve.h.
    {
        // check const methods.
        checkConstConstraints();
    }
References DGtal::concepts::C3DParametricCurve< T >::checkConstConstraints().
BOOST_STATIC_ASSERT()
template<typename T > DGtal::concepts::C3DParametricCurve< T >::BOOST_STATIC_ASSERT ((Space::dimension==3))
checkConstConstraints()
template<typename T > virtual void DGtal::concepts::C3DParametricCurve< T >::checkConstConstraints () const inline virtual
Reimplemented in DGtal::concepts::C3DParametricCurveDecorator< T >.
Definition at line 102 of file C3DParametricCurve.h.
    {
        ConceptUtils::sameType( x , self.xp ( 0.1f ) );
        ConceptUtils::sameType( x , self.x ( 0.1f ) );
    }
References DGtal::concepts::ConceptUtils::sameType(), and DGtal::concepts::C3DParametricCurve< T >::self.
Referenced by DGtal::concepts::C3DParametricCurve< T >::BOOST_CONCEPT_USAGE().
Field Documentation
c
template<typename T > double DGtal::concepts::C3DParametricCurve< T >::c protected
Definition at line 112 of file C3DParametricCurve.h.
self
template<typename T > T DGtal::concepts::C3DParametricCurve< T >::self protected
Definition at line 109 of file C3DParametricCurve.h.
Referenced by DGtal::concepts::C3DParametricCurve< T >::checkConstConstraints().
x
template<typename T > RealPoint DGtal::concepts::C3DParametricCurve< T >::x protected
Definition at line 110 of file C3DParametricCurve.h.
y
template<typename T > Point DGtal::concepts::C3DParametricCurve< T >::y protected
Definition at line 111 of file C3DParametricCurve.h.
The documentation for this struct was generated from the following file:
C3DParametricCurve.h