DGtal: DGtal::SetFromImage< TSet > Struct Template Reference
DGtal::SetFromImage< TSet > Struct Template Reference
Aim: Define utilities to convert a digital set into an image.
#include <DGtal/images/imagesSetsUtils/SetFromImage.h>
Public Types
typedef TSet Set
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CDigitalSet< Set >))
Static Public Member Functions
template<typename Image , typename ForegroundPredicate >
static void append (Set &aSet, const ForegroundPredicate &isForeground, typename Image::Domain::ConstIterator itBegin, typename Image::Domain::ConstIterator itEnd)
template<typename Image >
static void append (Set &aSet, const Image &aImage, const typename Image::Value minVal, const typename Image::Value maxVal, typename Image::Domain::ConstIterator itBegin, typename Image::Domain::ConstIterator itEnd)
template<typename Image , typename ForegroundPredicate >
static void append (Set &aSet, const Image &aImage, const ForegroundPredicate &isForeground)
template<typename Image >
static void append (Set &aSet, const Image &aImage, const typename Image::Value minVal, const typename Image::Value maxVal)
Detailed Description
template<typename TSet>
struct DGtal::SetFromImage< TSet >
Aim: Define utilities to convert a digital set into an image.
Description of template class 'SetFromImage'
Template Parameters
TSet an model of CImageContainer concept.
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, graph/volDistanceTraversal.cpp, io/digitalSetFromVol.cpp, io/display3DToOFF.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dBorderExtractionImg.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/digitalSurfaceSlice.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, and tutorial-examples/freemanChainFromImage.cpp.
Definition at line 63 of file SetFromImage.h.
Member Typedef Documentation
Set
template<typename TSet > TSet DGtal::SetFromImage< TSet >::Set
Definition at line 65 of file SetFromImage.h.
Member Function Documentation
append() [1/4]
template<typename TSet > template<typename Image , typename ForegroundPredicate > static void DGtal::SetFromImage< TSet >::append (Set & aSet, const ForegroundPredicate & isForeground, typename Image::Domain::ConstIterator itBegin, typename Image::Domain::ConstIterator itEnd) static
Append an Image value set to an existing Set (maybe empty).
Precondition
the ForegroundPredicate instance must have been created on the image aImage.
Parameters
aSet the set (maybe empty) to which points are added.
isForeground instance of ForegroundPredicate to decide
itBegin starting point in the input image Domain.
itEnd ending point in the input image domain. which points to copy.
Referenced by DGtal::SetFromImage< TSet >::append(), DGtal::SetFromImage< TSet >::append(), DGtal::SetFromImage< TSet >::append(), main(), main(), main(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), and testPNMReader().
append() [2/4]
template<typename TSet > template<typename Image , typename ForegroundPredicate > static void DGtal::SetFromImage< TSet >::append (Set & aSet, const Image & aImage, const ForegroundPredicate & isForeground) inline static
Append an Image value set to an existing Set (maybe empty).
Precondition
the ForegroundPredicate instance must have been created on the image aImage.
Parameters
aSet the set (maybe empty) to which points are added.
aImage image to convert to a Set.
isForeground instance of ForegroundPredicate to decide which points to copy.
Definition at line 125 of file SetFromImage.h.
    {
      typename Image::Domain domain=aImage.domain();
      append<Image,ForegroundPredicate>(aSet,isForeground,domain.begin(),domain.end());
    }
References DGtal::SetFromImage< TSet >::append(), DGtal::Image< TImageContainer >::domain(), and domain.
append() [3/4]
template<typename TSet > template<typename Image > static void DGtal::SetFromImage< TSet >::append (Set & aSet, const Image & aImage, const typename Image::Value minVal, const typename Image::Value maxVal) inline static
Append an Image value set to an existing Set (maybe empty). This method will construct a default ForegroundPredicate instance as a simple thresholding (SimpleForegroundPredicate) of values in ]minVal,maxVal].
Parameters
aSet the set (maybe empty) to which points are added.
aImage image to convert to a Set.
minVal minimum value of the thresholding
maxVal maximum value of the thresholding
Definition at line 146 of file SetFromImage.h.
    {
      functors::IntervalForegroundPredicate<Image> isForeground(aImage,minVal,maxVal);
      append(aSet,aImage,isForeground);
    }
References DGtal::SetFromImage< TSet >::append().
append() [4/4]
template<typename TSet > template<typename Image > static void DGtal::SetFromImage< TSet >::append (Set & aSet, const Image & aImage, const typename Image::Value minVal, const typename Image::Value maxVal, typename Image::Domain::ConstIterator itBegin, typename Image::Domain::ConstIterator itEnd) inline static
Append an Image value set to an existing Set (maybe empty). This method will construct a default ForegroundPredicate instance as a simple thresholding (SimpleForegroundPredicate) of values in ]minVal,maxVal].
Parameters
aSet the set (maybe empty) to which points are added.
aImage the image.
minVal minimum value of the thresholding
maxVal maximum value of the thresholding
itBegin starting point in the input image Domain.
itEnd ending point in the input image domain.
Definition at line 102 of file SetFromImage.h.
    {
      functors::IntervalForegroundPredicate<Image> isForeground(aImage,minVal,maxVal);
      append(aSet, isForeground,itBegin,itEnd);
    }
References DGtal::SetFromImage< TSet >::append().
BOOST_CONCEPT_ASSERT()
template<typename TSet > DGtal::SetFromImage< TSet >::BOOST_CONCEPT_ASSERT ((concepts::CDigitalSet< Set >))
The documentation for this struct was generated from the following file:
SetFromImage.h