DGtal: DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator Struct Reference
DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator Struct Reference
#include <DGtal/topology/CubicalComplex.h>
Public Types
typedef boost::iterator_facade< ConstIterator, Cell const, std::forward_iterator_tag > Base
typedef ConstIterator Self
typedef Base::value_type Value
typedef Base::pointer Pointer
typedef Base::reference Reference
typedef Base::difference_type DifferenceType
Public Member Functions
ConstIterator ()
Default iterator. Invalid.
ConstIterator (ConstAlias< CubicalComplex > cc, Dimension d)
ConstIterator (ConstAlias< CubicalComplex > cc, Dimension d, CellMapConstIterator it)
Private Member Functions
void nextDimension ()
void increment ()
bool equal (const ConstIterator &other) const
Cell const & dereference () const
Dimension dimension () const
Private Attributes
const CubicalComplex * myCC
Dimension myD
CellMapConstIterator myIt
CellMapConstIterator myItEnd
Friends
class CubicalComplex
class boost::iterator_core_access
Detailed Description
template<typename TKSpace, typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type>
struct DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator
An non-mutable iterator class to visit all the cells (and not their datas) of the complex. A model of boost::ForwardIterator.
Definition at line 306 of file CubicalComplex.h.
Member Typedef Documentation
Base
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> boost::iterator_facade< ConstIterator, Cell const, std::forward_iterator_tag > DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::Base
Definition at line 313 of file CubicalComplex.h.
DifferenceType
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::difference_type DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::DifferenceType
Definition at line 318 of file CubicalComplex.h.
Pointer
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::pointer DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::Pointer
Definition at line 316 of file CubicalComplex.h.
Reference
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::reference DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::Reference
Definition at line 317 of file CubicalComplex.h.
Self
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> ConstIterator DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::Self
Definition at line 314 of file CubicalComplex.h.
Value
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Base::value_type DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::Value
Definition at line 315 of file CubicalComplex.h.
Constructor & Destructor Documentation
ConstIterator() [1/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator () inline
Default iterator. Invalid.
Definition at line 321 of file CubicalComplex.h.
: myCC(0), myD(0) {}
ConstIterator() [2/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator (ConstAlias< CubicalComplex > cc, Dimension d) inline
Constructor from complex cc and cell dimension d. If the dimension is lower or equal to the dimension of the complex,
Parameters
cc any valid cubical complex that is aliased in the iterator.
d the dimension of the starting cell.
Definition at line 331 of file CubicalComplex.h.
        : myCC( &cc ), myD( d )
      {
        if ( myD <= myCC->dimension )
          {
            myIt    = myCC->begin( myD );
            myItEnd = myCC->end( myD );
            nextDimension();
          }
        else
          {
            myD     = myCC->dimension + 1;
            myIt    = myCC->end( myCC->dimension );
            myItEnd = myCC->end( myCC->dimension );
          }
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::begin(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myD, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myItEnd, and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
ConstIterator() [3/3]
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator (ConstAlias< CubicalComplex > cc, Dimension d, CellMapConstIterator it) inline
Detailed constructor from complex cc, cell dimension d and iterators.
Parameters
cc any valid cubical complex that is aliased in the iterator.
d the dimension of the starting cell (0<=d<=dimension).
it an iterator pointing on a cell of the complex.
Definition at line 355 of file CubicalComplex.h.
        : myCC( &cc ), myD( d ), myIt( it )
      {
        ASSERT( d <= myCC->dimension );
        myItEnd = myCC->end( d );
        nextDimension();
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myItEnd, and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
Member Function Documentation
dereference()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Cell const & DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dereference () const inline private
Definition at line 389 of file CubicalComplex.h.
      {
        return myIt->first;
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt.
dimension()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Dimension DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dimension () const inline private
Definition at line 394 of file CubicalComplex.h.
      {
        return myD;
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myD.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator().
equal()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> bool DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::equal (const ConstIterator & other) const inline private
Definition at line 384 of file CubicalComplex.h.
      {
        return ( myD == other.myD ) && ( myIt == other.myIt );
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myD, and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt.
increment()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> void DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::increment () inline private
Definition at line 377 of file CubicalComplex.h.
      {
        ASSERT( myCC != 0 );
        ++myIt;
        nextDimension();
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt, and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
nextDimension()
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> void DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension () inline private
Definition at line 367 of file CubicalComplex.h.
      {
        while ( myIt == myItEnd )
          {
            if ( ++myD > myCC->dimension ) break;
            myIt    = myCC->begin( myD );
            myItEnd = myCC->end( myD );
          }
      }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::begin(), DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::end(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myCC, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myD, DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt, and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myItEnd.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::increment().
Friends And Related Symbol Documentation
boost::iterator_core_access
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> friend class boost::iterator_core_access friend
Definition at line 365 of file CubicalComplex.h.
CubicalComplex
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> friend class CubicalComplex friend
Definition at line 310 of file CubicalComplex.h.
Field Documentation
myCC
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> const CubicalComplex* DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myCC private
Definition at line 400 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::increment(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
myD
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> Dimension DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myD private
Definition at line 401 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dimension(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::equal(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
myIt
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> CellMapConstIterator DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myIt private
Definition at line 402 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::dereference(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::equal(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::increment(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
myItEnd
template<typename TKSpace , typename TCellContainer = typename TKSpace::template CellMap< CubicalCellData >::Type> CellMapConstIterator DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::myItEnd private
Definition at line 403 of file CubicalComplex.h.
Referenced by DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::ConstIterator(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::ConstIterator::nextDimension().
The documentation for this struct was generated from the following file:
CubicalComplex.h