DGtal: testModuloComputer.cpp File Reference
testModuloComputer.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/arithmetic/ModuloComputer.h"
#include "DGtal/kernel/NumberTraits.h"
Functions
bool testModuloComputer ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2010/07/07
Functions for testing class ModuloComputer.
This file is part of the DGtal library.
Definition in file testModuloComputer.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 88 of file testModuloComputer.cpp.
{
  trace.beginBlock ( "Testing class ModuloComputer" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testModuloComputer(); // && ... other tests
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testModuloComputer(), and DGtal::trace.
testModuloComputer()
bool testModuloComputer ()
Example of a test. To be completed.
Definition at line 48 of file testModuloComputer.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Testing block ..." );
  //Construct an arithmetic modulo 15
  ModuloComputer< int > modular(15);
  typedef NumberTraits< int >::UnsignedVersion myUnsignedInteger;
  myUnsignedInteger a;
  a = modular.cast( 2 );   //a contains the value 2
  nbok += (a == 2) ? 1 : 0;
  nb++;
  trace.info() << "a= "<<a<<std::endl;
  a = modular.cast( -1 );  //a contains the value 14
  nbok += (a== 14) ? 1 : 0;
  nb++;
  trace.info() << "a= "<<a<<std::endl;
  modular.increment( a ); //a contains the value 0
  nbok += (a== 0) ? 1 : 0;
  nb++;
  trace.info() << "a= "<<a<<std::endl;
  nbok += 1;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.endBlock();
  return nbok == nb;
}
References DGtal::Trace::beginBlock(), DGtal::ModuloComputer< TInteger >::cast(), DGtal::Trace::endBlock(), DGtal::ModuloComputer< TInteger >::increment(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().