DGtal: testITKDicomReader.cpp File Reference
testITKDicomReader.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtalCatch.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ImageContainerByITKImage.h"
#include "DGtal/io/readers/ITKDicomReader.h"
#include <itkGDCMSeriesFileNames.h>
Functions
std::vector< std::string > getFirstDicomSerieFileNames (const std::string &path)
template<typename Image >
void testImportDICOM ()
template<typename PixelType >
void testSpatialInformation ()
TEST_CASE ("Testing ITKReader")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Boris Mansencal (boris.nosp@m..man.nosp@m.senca.nosp@m.l@la.nosp@m.bri.f.nosp@m.r) LaBRI (CNRS, UMR 5800, University of Bordeaux, Bordeaux-INP), France
Date
2019/02/05
Functions for testing class ITKDicomReader.
This file is part of the DGtal library.
Definition in file testITKDicomReader.cpp.
Function Documentation
getFirstDicomSerieFileNames()
std::vector< std::string > getFirstDicomSerieFileNames (const std::string & path)
Definition at line 61 of file testITKDicomReader.cpp.
{
  typedef itk::GDCMSeriesFileNames NamesGeneratorType;
  NamesGeneratorType::Pointer nameGenerator = NamesGeneratorType::New();
  nameGenerator->SetUseSeriesDetails( true );
  nameGenerator->SetDirectory( path );
  typedef itk::GDCMSeriesFileNames::SeriesUIDContainerType SeriesIdContainer;
  const SeriesIdContainer & seriesUID = nameGenerator->GetSeriesUIDs();
  if (! seriesUID.empty() )
  {
    return nameGenerator->GetFileNames( *(seriesUID.begin()) );
  }
  return std::vector<std::string>();
}
Referenced by testImportDICOM(), and testSpatialInformation().
TEST_CASE()
TEST_CASE ("Testing ITKReader")
Definition at line 128 of file testITKDicomReader.cpp.
{
  // Default image selector = STLVector
  SECTION(
  "Testing ITKDicomReader with 8 bits ImageContainerBySTLVector images" )
  {
    typedef ImageContainerBySTLVector<Z3i::Domain, unsigned char> Image;
    testImportDICOM<Image>();
  }
  SECTION(
  "Testing ITKDicomReader with 8 bits ImageContainerByITKImage images" )
  {
    typedef ImageContainerByITKImage<Z3i::Domain, unsigned char> Image;
    testImportDICOM<Image>();
  }
  SECTION(
  "Testing ITKDicomReader with 16 bits ImageContainerBySTLVector images" )
  {
    typedef ImageContainerBySTLVector<Z3i::Domain, uint16_t> Image;
    testImportDICOM<Image>();
  }
  SECTION(
  "Testing ITKDicomReader with 16 bits ImageContainerByITKImage images" )
  {
    typedef ImageContainerByITKImage<Z3i::Domain, uint16_t> Image;
    testImportDICOM<Image>();
  }
  SECTION(
  "Testing behavior of ITKDicomReader on empty filenames vector" )
  {
    typedef ImageContainerBySTLVector<Z3i::Domain, unsigned char> Image;
    std::vector<std::string> filenames;
    bool caughtException = false;
    try
    {
      Image im = ITKDicomReader<Image>::importDICOM(filenames);
    }
    catch(exception &)
    {
      caughtException = true;
      trace.info() <<"Exception was correctly caught" << std::endl;
    }
    REQUIRE( caughtException == true);
  }
  SECTION(
  "Testing ITKDicomReader with 8 bits ImageContainerByITKImage images keeps spatial information" )
  {
    testSpatialInformation<unsigned char>();
  }
  SECTION(
  "Testing ITKDicomReader with 16 bits ImageContainerByITKImage images keeps spatial information" )
  {
    testSpatialInformation<int16_t>();
  }
}
References DGtal::ITKDicomReader< TImage >::importDICOM(), DGtal::Trace::info(), REQUIRE(), SECTION(), testImportDICOM(), testSpatialInformation(), and DGtal::trace.
testImportDICOM()
template<typename Image > void testImportDICOM ()
Definition at line 81 of file testITKDicomReader.cpp.
{
  std::vector<std::string> fileNames = getFirstDicomSerieFileNames( testPath + "samples/dicomSample" );
  Image image = ITKDicomReader<Image>::importDICOM( fileNames );
  unsigned int nbVal=0, nbPos = 0;
  typename Image::ConstRange r = image.constRange();
  for ( typename Image::ConstRange::ConstIterator it=r.begin(), itend=r.end() ; it != itend ; ++it )
    {
      ++nbVal;
      if ( (*it) > 0 ) ++nbPos;
    }
  REQUIRE( ( nbVal==2130048 && nbPos==296030 ) );
}
References getFirstDicomSerieFileNames(), DGtal::ITKDicomReader< TImage >::importDICOM(), and REQUIRE().
Referenced by TEST_CASE().
testSpatialInformation()
template<typename PixelType > void testSpatialInformation ()
Definition at line 99 of file testITKDicomReader.cpp.
{
  std::vector<std::string> fileNames = getFirstDicomSerieFileNames( testPath + "samples/dicomSample" );
  typedef ImageContainerByITKImage<Z3i::Domain, PixelType> DGtalImage;
  DGtalImage img = ITKDicomReader<DGtalImage>::importDICOM( fileNames );
  typename DGtalImage::ITKImagePointer dgtal_itk = img.getITKImagePointer();
  typedef itk::Image<PixelType, 3> ItkImage;
  typedef itk::ImageSeriesReader<ItkImage> ItkReader;
  typename ItkReader::Pointer reader = ItkReader::New();
  reader->SetFileNames( fileNames );
  reader->Update();
  typename ItkImage::Pointer itk = reader->GetOutput();
  INFO( "Checking spacing" )
  REQUIRE( dgtal_itk->GetSpacing() == itk->GetSpacing() );
  INFO( "Checking origin" )
  REQUIRE( dgtal_itk->GetOrigin() == itk->GetOrigin() );
  INFO( "Checking direction" )
  REQUIRE( dgtal_itk->GetDirection() == itk->GetDirection() );
}
References getFirstDicomSerieFileNames(), DGtal::ITKDicomReader< TImage >::importDICOM(), and REQUIRE().
Referenced by TEST_CASE().