DGtal: testBasicMathFunctions.cpp File Reference
testBasicMathFunctions.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/math/BasicMathFunctions.h"
Functions
bool testBasicMathFunctions ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/10/26
Functions for testing class BasicMathFunctions.
This file is part of the DGtal library.
Definition in file testBasicMathFunctions.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 95 of file testBasicMathFunctions.cpp.
{
  trace.beginBlock ( "Testing class BasicMathFunctions" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testBasicMathFunctions(); // && ... other tests
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testBasicMathFunctions(), and DGtal::trace.
testBasicMathFunctions()
bool testBasicMathFunctions ()
Example of a test. To be completed.
Definition at line 46 of file testBasicMathFunctions.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Testing power by  squaring ..." );
  trace.info() << "power(5,4)= "<< functions::power(5,4) <<std::endl;
  nbok += (functions::power(5,4)==625) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.info() << "power(5.0,4)= "<< functions::power(5.0,4) <<std::endl;
  nbok += (functions::power(5,4)==625.0) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Testing roundToUpperPowerOfTwo ..." );
  trace.info() << "roundToUpperPowerOfTwo(200)= "<< functions::roundToUpperPowerOfTwo(200) <<std::endl;
  nbok += (functions::roundToUpperPowerOfTwo(200)==256) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.info() << "roundToUpperPowerOfTwo(1000)= "<< functions::roundToUpperPowerOfTwo(1000) <<std::endl;
  nbok += (functions::roundToUpperPowerOfTwo(1000)==1024) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.info() << "power(5.0,4)= "<< functions::power(5.0,4) <<std::endl;
  nbok += (functions::power(5,4)==625.0) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") " << std::endl;
  trace.endBlock();
  return nbok == nb;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::functions::power(), DGtal::functions::roundToUpperPowerOfTwo(), and DGtal::trace.
Referenced by main().