DGtal: benchmarkHyperRectDomain.cpp File Reference
benchmarkHyperRectDomain.cpp File Reference
DGtal Test Files | DGtal Test Files | DGtal Test Files
#include <iostream>
#include <numeric>
#include <chrono>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/PointVector.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtalCatch.h"
Functions
void tic ()
Starts timer.
double toc ()
Ends timer and return elapsed time.
TEST_CASE_METHOD (BenchDomain, "Benchmarking HyperRectDomain iterators using custom implementation")
Variables
auto tic_timer = std::chrono::high_resolution_clock::now()
Timer used in tic and toc.
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Roland Denis (rolan.nosp@m.d.de.nosp@m.nis@m.nosp@m.ath..nosp@m.univ-.nosp@m.lyon.nosp@m.1.fr)
Date
2019/10/14
This file is part of the DGtal library
Definition in file benchmarkHyperRectDomain.cpp.
Function Documentation
TEST_CASE_METHOD()
TEST_CASE_METHOD (BenchDomain , "Benchmarking HyperRectDomain iterators using custom implementation")
Definition at line 89 of file benchmarkHyperRectDomain.cpp.
{
  SECTION("Domain forward traversal")
    {
      Point check;
      double duration;
      for (std::size_t i = 0; i < N; ++i)
        {
          tic();
          for (auto const& pt : domain)
            check += pt;
          duration = toc();
        }
      trace.info() << "Domain traversal: " << duration << " s ; " << (domain.size()/duration*1e-9) << " Gpts/s ; check = " << check << std::endl;
    }
  SECTION("Domain reverse traversal")
    {
      Point check;
      double duration;
      for (std::size_t i = 0; i < N; ++i)
        {
          tic();
          for (auto it = domain.rbegin(), it_end = domain.rend(); it != it_end; ++it)
            check += *it;
          duration = toc();
        }
      trace.info() << "Domain reverse traversal: " << duration << " s ; " << (domain.size()/duration*1e-9) << " Gpts/s ; check = " << check << std::endl;
    }
  SECTION("Benchmarking domain traversal using subRange")
    {
      Point check;
      double duration;
      for (std::size_t i = 0; i < N; ++i)
        {
          tic();
          for (auto const& pt : domain.subRange(dimensions))
            check += pt;
          duration = toc();
        }
      trace.info() << "Domain traversal using subRange: " << duration << " s ; " << (domain.size()/duration*1e-9) << " Gpts/s ; check = " << check << std::endl;
    }
  SECTION("Benchmarking domain reverse traversal using subRange")
    {
      Point check;
      const auto range = domain.subRange(dimensions);
      double duration;
      for (std::size_t i = 0; i < N; ++i)
        {
          tic();
          for (auto it = range.rbegin(), it_end = range.rend(); it != it_end; ++it)
            check += *it;
          duration = toc();
        }
      trace.info() << "Domain reverse traversal using subRange: " << duration << " s ; " << (domain.size()/duration*1e-9) << " Gpts/s ; check = " << check << std::endl;
    }
}
References domain, DGtal::Trace::info(), DGtal::HyperRectDomain< TSpace >::rbegin(), DGtal::HyperRectDomain< TSpace >::rend(), SECTION(), DGtal::HyperRectDomain< TSpace >::size(), DGtal::HyperRectDomain< TSpace >::subRange(), tic(), toc(), and DGtal::trace.
tic()
void tic ()
Starts timer.
Definition at line 50 of file benchmarkHyperRectDomain.cpp.
{
  tic_timer = std::chrono::high_resolution_clock::now();
}
References tic_timer.
Referenced by DGtal::QuickHull< TKernel >::computeConvexHull(), DGtal::QuickHull< TKernel >::setInput(), and TEST_CASE_METHOD().
toc()
double toc ()
Ends timer and return elapsed time.
Definition at line 56 of file benchmarkHyperRectDomain.cpp.
{
  const auto toc_timer = std::chrono::high_resolution_clock::now();
  const std::chrono::duration<double> time_span = toc_timer - tic_timer;
  return time_span.count();
}
References tic_timer.
Referenced by TEST_CASE_METHOD().
Variable Documentation
tic_timer
auto tic_timer = std::chrono::high_resolution_clock::now()
Timer used in tic and toc.
Definition at line 47 of file benchmarkHyperRectDomain.cpp.
Referenced by tic(), and toc().