DGtal: DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator Class Reference
DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator Class Reference
#include <DGtal/images/ImageContainerBySTLVector.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef Value value_type
typedef ptrdiff_t difference_type
typedef Value * pointer
typedef Value & reference
Public Member Functions
SpanIterator (const Point &p, const Dimension aDim, ImageContainerBySTLVector< Domain, Value > *aMap)
void setValue (const Value aVal)
const Value & operator* ()
bool operator== (const SpanIterator &it) const
bool operator!= (const SpanIterator &it) const
void next ()
void prev ()
SpanIterator & operator++ ()
SpanIterator & operator++ (int)
SpanIterator & operator-- ()
SpanIterator & operator-- (int)
Private Attributes
Size myPos
Current Point in the domain.
ImageContainerBySTLVector< Domain, Value > * myMap
Copy of the underlying images.
Dimension myDimension
Dimension on which the iterator must iterate.
Size myShift
Padding variable.
Friends
class ImageContainerBySTLVector< Domain, Value >
Detailed Description
template<typename TDomain, typename TValue>
class DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator
Specific SpanIterator on ImageContainerBySTLVector.
Definition at line 307 of file ImageContainerBySTLVector.h.
Member Typedef Documentation
difference_type
template<typename TDomain , typename TValue > typedef ptrdiff_t DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::difference_type
Definition at line 317 of file ImageContainerBySTLVector.h.
iterator_category
template<typename TDomain , typename TValue > typedef std::bidirectional_iterator_tag DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::iterator_category
Todo:
construct a RANDOM-ACCESS iterator
Definition at line 315 of file ImageContainerBySTLVector.h.
pointer
template<typename TDomain , typename TValue > typedef Value* DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::pointer
Definition at line 318 of file ImageContainerBySTLVector.h.
reference
template<typename TDomain , typename TValue > typedef Value& DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::reference
Definition at line 319 of file ImageContainerBySTLVector.h.
value_type
template<typename TDomain , typename TValue > typedef Value DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::value_type
Definition at line 316 of file ImageContainerBySTLVector.h.
Constructor & Destructor Documentation
SpanIterator()
template<typename TDomain , typename TValue > DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::SpanIterator (const Point & p, const Dimension aDim, ImageContainerBySTLVector< Domain, Value > * aMap) inline
Constructor.
Parameters
p starting point of the SpanIterator
aDim specifies the dimension along which the iterator will iterate
aMap pointer to the imageContainer
Definition at line 328 of file ImageContainerBySTLVector.h.
                                                                      :  myMap ( aMap ), myDimension ( aDim )
      {
        myPos = aMap->linearized ( p );
        //We compute the myShift quantity
        myShift = 1;
        for ( Dimension k = 0; k < myDimension  ; k++ )
          myShift *= aMap->myExtent[k];
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::linearized(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myDimension, DGtal::ImageContainerBySTLVector< TDomain, TValue >::myExtent, DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos, and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myShift.
Member Function Documentation
next()
template<typename TDomain , typename TValue > void DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::next () inline
Implements the next() method: we move on step forward.
Definition at line 391 of file ImageContainerBySTLVector.h.
      {
        myPos += myShift;
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos, and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myShift.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator++().
operator!=()
template<typename TDomain , typename TValue > bool DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator!= (const SpanIterator & it) const inline
Operator !=
Returns
true if this and it are different.
Definition at line 381 of file ImageContainerBySTLVector.h.
      {
        return ( myPos != it.myPos );
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos.
operator*()
template<typename TDomain , typename TValue > const Value & DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator* () inline
operator* on SpanIterators.
Returns
the value associated to the current position.
Definition at line 359 of file ImageContainerBySTLVector.h.
      {
        return ( *myMap ) [ myPos ];
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myMap, and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos.
operator++() [1/2]
template<typename TDomain , typename TValue > SpanIterator & DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator++ () inline
Operator ++ (++it)
Definition at line 412 of file ImageContainerBySTLVector.h.
      {
        this->next();
        return *this;
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::next().
operator++() [2/2]
template<typename TDomain , typename TValue > SpanIterator & DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator++ (int) inline
Operator ++ (it++)
Definition at line 423 of file ImageContainerBySTLVector.h.
      {
        SpanIterator tmp = *this;
        ++*this;
        return tmp;
      }
operator--() [1/2]
template<typename TDomain , typename TValue > SpanIterator & DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator-- () inline
Operator – (–it)
Definition at line 435 of file ImageContainerBySTLVector.h.
      {
        this->prev();
        return *this;
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::prev().
operator--() [2/2]
template<typename TDomain , typename TValue > SpanIterator & DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator-- (int) inline
Operator – (it–)
Definition at line 446 of file ImageContainerBySTLVector.h.
      {
        SpanIterator tmp = *this;
        --*this;
        return tmp;
      }
operator==()
template<typename TDomain , typename TValue > bool DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator== (const SpanIterator & it) const inline
Operator ==.
Returns
true if this and it are equals.
Definition at line 370 of file ImageContainerBySTLVector.h.
      {
        return ( myPos == it.myPos );
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos.
prev()
template<typename TDomain , typename TValue > void DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::prev () inline
Implements the prev() method: we move on step backward.
Definition at line 401 of file ImageContainerBySTLVector.h.
      {
        ASSERT ( ( long int ) myPos - myShift > 0 );
        myPos -= myShift;
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos, and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myShift.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator--().
setValue()
template<typename TDomain , typename TValue > void DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::setValue (const Value aVal) inline
Set a value at a SpanIterator position.
Parameters
aVal the value to set.
Definition at line 348 of file ImageContainerBySTLVector.h.
      {
        ( *myMap ) [ myPos ] = aVal;
      }
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::setValue().
Friends And Related Function Documentation
ImageContainerBySTLVector< Domain, Value >
template<typename TDomain , typename TValue > friend class ImageContainerBySTLVector< Domain, Value > friend
Definition at line 530 of file ImageContainerBySTLVector.h.
Field Documentation
myDimension
template<typename TDomain , typename TValue > Dimension DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myDimension private
Dimension on which the iterator must iterate.
Definition at line 461 of file ImageContainerBySTLVector.h.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::SpanIterator().
myMap
template<typename TDomain , typename TValue > ImageContainerBySTLVector<Domain, Value>* DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myMap private
Copy of the underlying images.
Definition at line 458 of file ImageContainerBySTLVector.h.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator*().
myPos
template<typename TDomain , typename TValue > Size DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myPos private
Current Point in the domain.
Definition at line 455 of file ImageContainerBySTLVector.h.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::next(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator!=(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator*(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::operator==(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::prev(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::setValue(), and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::SpanIterator().
myShift
template<typename TDomain , typename TValue > Size DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::myShift private
Padding variable.
Definition at line 464 of file ImageContainerBySTLVector.h.
Referenced by DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::next(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::prev(), and DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::SpanIterator().
The documentation for this class was generated from the following file:
ImageContainerBySTLVector.h