DGtal: DGtal::SphericalTriangle< TSpace > Class Template Reference
DGtal::SphericalTriangle< TSpace > Class Template Reference
Aim: Represent a triangle drawn onto a sphere of radius 1.
#include <DGtal/geometry/tools/SphericalTriangle.h>
Public Member Functions
~SphericalTriangle ()
SphericalTriangle (const RealVector &va, const RealVector &vb, const RealVector &vc, bool normalize=true)
Default constructor. The object is invalid.
SphericalTriangle (const SphericalTriangle &other)=default
SphericalTriangle & operator= (const SphericalTriangle &other)=default
const RealVector & A () const
const RealVector & B () const
const RealVector & C () const
void setA (const RealVector &va, bool normalize=true)
void setB (const RealVector &vb, bool normalize=true)
void setC (const RealVector &vc, bool normalize=true)
bool isDegenerate () const
Self polarTriangle () const
void interiorAngles (Scalar &alpha, Scalar &beta, Scalar &gamma) const
Scalar area () const
Scalar algebraicArea () const
Protected Attributes
RealVector myA
The point A of the triangle ABC, of unit length.
RealVector myB
The point B of the triangle ABC, of unit length.
RealVector myC
The point C of the triangle ABC, of unit length.
Private Types
typedef TSpace Space
typedef SphericalTriangle< Space > Self
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
typedef RealVector::Component Scalar
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
BOOST_STATIC_ASSERT ((Space::dimension==3))
Detailed Description
template<typename TSpace>
class DGtal::SphericalTriangle< TSpace >
Aim: Represent a triangle drawn onto a sphere of radius 1.
Description of class 'SphericalTriangle'
Template Parameters
TSpace any type of 3-dimensional digital space.
Definition at line 61 of file SphericalTriangle.h.
Member Typedef Documentation
RealPoint
template<typename TSpace > typedef Space::RealPoint DGtal::SphericalTriangle< TSpace >::RealPoint private
Definition at line 66 of file SphericalTriangle.h.
RealVector
template<typename TSpace > typedef Space::RealVector DGtal::SphericalTriangle< TSpace >::RealVector private
Definition at line 67 of file SphericalTriangle.h.
Scalar
template<typename TSpace > typedef RealVector::Component DGtal::SphericalTriangle< TSpace >::Scalar private
Definition at line 68 of file SphericalTriangle.h.
Self
template<typename TSpace > typedef SphericalTriangle<Space> DGtal::SphericalTriangle< TSpace >::Self private
Definition at line 65 of file SphericalTriangle.h.
Space
template<typename TSpace > typedef TSpace DGtal::SphericalTriangle< TSpace >::Space private
Definition at line 64 of file SphericalTriangle.h.
Constructor & Destructor Documentation
~SphericalTriangle()
template<typename TSpace > DGtal::SphericalTriangle< TSpace >::~SphericalTriangle () inline
Destructor.
Definition at line 79 of file SphericalTriangle.h.
{}
SphericalTriangle() [1/2]
template<typename TSpace > DGtal::SphericalTriangle< TSpace >::SphericalTriangle (const RealVector & va, const RealVector & vb, const RealVector & vc, bool normalize = true) inline
Default constructor. The object is invalid.
Definition at line 82 of file SphericalTriangle.h.
    {
      setA( va, normalize );
      setB( vb, normalize );
      setC( vc, normalize );
    }
References DGtal::SphericalTriangle< TSpace >::setA(), DGtal::SphericalTriangle< TSpace >::setB(), and DGtal::SphericalTriangle< TSpace >::setC().
SphericalTriangle() [2/2]
template<typename TSpace > DGtal::SphericalTriangle< TSpace >::SphericalTriangle (const SphericalTriangle< TSpace > & other) default
Copy constructor.
Parameters
other the object to clone.
Member Function Documentation
A()
template<typename TSpace > const RealVector & DGtal::SphericalTriangle< TSpace >::A () const inline
Returns
the point A of the spherical triangle.
Definition at line 104 of file SphericalTriangle.h.
{ return myA; }
References DGtal::SphericalTriangle< TSpace >::myA.
Referenced by DGtal::SphericalTriangle< TSpace >::interiorAngles().
algebraicArea()
template<typename TSpace > Scalar DGtal::SphericalTriangle< TSpace >::algebraicArea () const inline
Returns
the (signed) area of the spherical triangle (below 2pi).
Definition at line 217 of file SphericalTriangle.h.
    {
      Scalar     S = area();
      RealVector M = myA + myB + myC;
      RealVector X = ( myB - myA ).crossProduct( myC - myA );
      if ( M.norm1() <= 1e-8 || X.norm1() <= 1e-8 ) return 0.0;
      return M.dot( X ) < 0.0 ? -S : S;
    }
References DGtal::SphericalTriangle< TSpace >::area(), DGtal::crossProduct(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::dot(), DGtal::SphericalTriangle< TSpace >::myA, DGtal::SphericalTriangle< TSpace >::myB, DGtal::SphericalTriangle< TSpace >::myC, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm1().
Referenced by DGtal::CorrectedNormalCurrentFormula< TRealPoint, TRealVector >::mu2InterpolatedU().
area()
template<typename TSpace > Scalar DGtal::SphericalTriangle< TSpace >::area () const inline
Returns
the (unsigned) area of the spherical triangle (below 2pi).
Definition at line 207 of file SphericalTriangle.h.
    {
      Scalar alpha, beta, gamma;
      if ( isDegenerate() ) return 0.0;
      interiorAngles( alpha, beta, gamma );
      return ( (alpha == 0.0) || (beta == 0.0) || (gamma == 0.0) )
               ? 0.0 : 2.0*M_PI - alpha - beta - gamma;
    }
References DGtal::SphericalTriangle< TSpace >::interiorAngles(), and DGtal::SphericalTriangle< TSpace >::isDegenerate().
Referenced by DGtal::SphericalTriangle< TSpace >::algebraicArea().
B()
template<typename TSpace > const RealVector & DGtal::SphericalTriangle< TSpace >::B () const inline
Returns
the point B of the spherical triangle.
Definition at line 106 of file SphericalTriangle.h.
{ return myB; }
References DGtal::SphericalTriangle< TSpace >::myB.
Referenced by DGtal::SphericalTriangle< TSpace >::interiorAngles().
BOOST_CONCEPT_ASSERT()
template<typename TSpace > DGtal::SphericalTriangle< TSpace >::BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >)) private
BOOST_STATIC_ASSERT()
template<typename TSpace > DGtal::SphericalTriangle< TSpace >::BOOST_STATIC_ASSERT ((Space::dimension==3)) private
C()
template<typename TSpace > const RealVector & DGtal::SphericalTriangle< TSpace >::C () const inline
Returns
the point C of the spherical triangle.
Definition at line 108 of file SphericalTriangle.h.
{ return myC; }
References DGtal::SphericalTriangle< TSpace >::myC.
Referenced by DGtal::SphericalTriangle< TSpace >::interiorAngles().
interiorAngles()
template<typename TSpace > void DGtal::SphericalTriangle< TSpace >::interiorAngles (Scalar & alpha, Scalar & beta, Scalar & gamma) const inline
Returns the interior angles of the spherical triangle ABC.
Parameters
[out] alpha the interior angle at vertex A.
[out] beta the interior angle at vertex B.
[out] gamma the interior angle at vertex C.
Definition at line 190 of file SphericalTriangle.h.
    {
      Self    T = polarTriangle();
      if ( T.A() == RealVector::zero || T.B() == RealVector::zero || T.C() == RealVector::zero )
        alpha = beta = gamma = 0.0;
      else
        {
          Scalar ca = std::max( -1.0, std::min( 1.0, T.B().dot( T.C() ) ) );
          Scalar cb = std::max( -1.0, std::min( 1.0, T.C().dot( T.A() ) ) );
          Scalar cc = std::max( -1.0, std::min( 1.0, T.A().dot( T.B() ) ) );
          alpha     = acos( ca );
          beta      = acos( cb );
          gamma     = acos( cc );
        }
    }
References DGtal::SphericalTriangle< TSpace >::A(), DGtal::SphericalTriangle< TSpace >::B(), DGtal::SphericalTriangle< TSpace >::C(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::dot(), DGtal::SphericalTriangle< TSpace >::polarTriangle(), and DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
Referenced by DGtal::SphericalTriangle< TSpace >::area().
isDegenerate()
template<typename TSpace > bool DGtal::SphericalTriangle< TSpace >::isDegenerate () const inline
Returns
'true' if the spherical triangle is too small or too thin.
Definition at line 158 of file SphericalTriangle.h.
    {
      Scalar d[ 3 ] = { ( myA - myB ).norm(),
                        ( myA - myC ).norm(),
                        ( myB - myC ).norm() };
      // Checks that the spherical triangle is small or thin.
      if ( ( d[ 0 ] < 1e-8 ) || ( d[ 1 ] < 1e-8 ) || ( d[ 2 ] < 1e-8 ) )
        return true;
      // Checks that the spherical triangle is flat.
      Dimension m = 0;
      if ( d[ 1 ] > d[ m ] ) m = 1;
      if ( d[ 2 ] > d[ m ] ) m = 2;
      return ( fabs( d[ m ] - d[ (m+1)%3 ] - d[ (m+2)%3 ] ) < 1e-8 );
    }
References DGtal::SphericalTriangle< TSpace >::myA, DGtal::SphericalTriangle< TSpace >::myB, and DGtal::SphericalTriangle< TSpace >::myC.
Referenced by DGtal::SphericalTriangle< TSpace >::area().
operator=()
template<typename TSpace > SphericalTriangle & DGtal::SphericalTriangle< TSpace >::operator= (const SphericalTriangle< TSpace > & other) default
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
polarTriangle()
template<typename TSpace > Self DGtal::SphericalTriangle< TSpace >::polarTriangle () const inline
Returns
the polar triangle associated with this triangle.
Definition at line 174 of file SphericalTriangle.h.
    {
      auto Ap = myB.crossProduct(myC);
      auto Bp = myC.crossProduct(myA);
      auto Cp = myA.crossProduct(myB);
      // Reorient points.
      if ( Ap.dot( myA ) < 0.0 ) Ap = -Ap;
      if ( Bp.dot( myB ) < 0.0 ) Bp = -Bp;
      if ( Cp.dot( myC ) < 0.0 ) Cp = -Cp;
      return Self( Ap, Bp, Cp, true );
    }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::crossProduct(), DGtal::SphericalTriangle< TSpace >::myA, DGtal::SphericalTriangle< TSpace >::myB, and DGtal::SphericalTriangle< TSpace >::myC.
Referenced by DGtal::SphericalTriangle< TSpace >::interiorAngles().
setA()
template<typename TSpace > void DGtal::SphericalTriangle< TSpace >::setA (const RealVector & va, bool normalize = true) inline
Sets the point A of the triangle.
Parameters
va the new point A
normalize if true, force normalization, otherwise va should be of unit length.
Definition at line 115 of file SphericalTriangle.h.
    {
      myA = va;
      if ( normalize )
        {
          Scalar n = myA.norm();
          if ( fabs( n ) > 1e-8 ) myA /= n;
          else myA = RealVector::zero;
        }
    }
References DGtal::SphericalTriangle< TSpace >::myA, DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm(), and DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
Referenced by DGtal::SphericalTriangle< TSpace >::SphericalTriangle().
setB()
template<typename TSpace > void DGtal::SphericalTriangle< TSpace >::setB (const RealVector & vb, bool normalize = true) inline
Sets the point B of the triangle.
Parameters
vb the new point B
normalize if true, force normalization, otherwise vb should be of unit length.
Definition at line 131 of file SphericalTriangle.h.
    {
      myB = vb;
      if ( normalize )
        {
          Scalar n = myB.norm();
          if ( fabs( n ) > 1e-8 ) myB /= n;
          else myB = RealVector::zero;
        }
    }
References DGtal::SphericalTriangle< TSpace >::myB, DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm(), and DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
Referenced by DGtal::SphericalTriangle< TSpace >::SphericalTriangle().
setC()
template<typename TSpace > void DGtal::SphericalTriangle< TSpace >::setC (const RealVector & vc, bool normalize = true) inline
Sets the point C of the triangle.
Parameters
vc the new point C
normalize if true, force normalization, otherwise vc should be of unit length.
Definition at line 146 of file SphericalTriangle.h.
    {
      myC = vc;
      if ( normalize )
        {
          Scalar n = myC.norm();
          if ( fabs( n ) > 1e-8 ) myC /= n;
          else myC = RealVector::zero;
        }
    }
References DGtal::SphericalTriangle< TSpace >::myC, DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm(), and DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
Referenced by DGtal::SphericalTriangle< TSpace >::SphericalTriangle().
Field Documentation
myA
template<typename TSpace > RealVector DGtal::SphericalTriangle< TSpace >::myA protected
The point A of the triangle ABC, of unit length.
Definition at line 231 of file SphericalTriangle.h.
Referenced by DGtal::SphericalTriangle< TSpace >::A(), DGtal::SphericalTriangle< TSpace >::algebraicArea(), DGtal::SphericalTriangle< TSpace >::isDegenerate(), DGtal::SphericalTriangle< TSpace >::polarTriangle(), and DGtal::SphericalTriangle< TSpace >::setA().
myB
template<typename TSpace > RealVector DGtal::SphericalTriangle< TSpace >::myB protected
The point B of the triangle ABC, of unit length.
Definition at line 233 of file SphericalTriangle.h.
Referenced by DGtal::SphericalTriangle< TSpace >::algebraicArea(), DGtal::SphericalTriangle< TSpace >::B(), DGtal::SphericalTriangle< TSpace >::isDegenerate(), DGtal::SphericalTriangle< TSpace >::polarTriangle(), and DGtal::SphericalTriangle< TSpace >::setB().
myC
template<typename TSpace > RealVector DGtal::SphericalTriangle< TSpace >::myC protected
The point C of the triangle ABC, of unit length.
Definition at line 235 of file SphericalTriangle.h.
Referenced by DGtal::SphericalTriangle< TSpace >::algebraicArea(), DGtal::SphericalTriangle< TSpace >::C(), DGtal::SphericalTriangle< TSpace >::isDegenerate(), DGtal::SphericalTriangle< TSpace >::polarTriangle(), and DGtal::SphericalTriangle< TSpace >::setC().
The documentation for this class was generated from the following file:
SphericalTriangle.h