DGtal: convex-and-concave-parts.cpp File Reference
convex-and-concave-parts.cpp File Reference
DGtal Examples
#include <cmath>
#include <iostream>
#include <sstream>
#include <fstream>
#include "DGtal/base/Common.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/geometry/curves/ArithmeticalDSSComputer.h"
#include "DGtal/geometry/curves/FreemanChain.h"
#include "DGtal/geometry/curves/SaturatedSegmentation.h"
#include "ConfigExamples.h"
Functions
template<typename Iterator , typename Board >
void drawCCP (const Iterator &itb, const Iterator &ite, Board &aBoard)
Function that draws the maximal segments with a color that depends on the local convexity:
template<typename Iterator , typename Board >
void segmentationIntoMaximalDSSs (const Iterator &itb, const Iterator &ite, Board &aBoard)
Perform a saturated segmentation into maximal digital straight segments of a given range of integer points and draw the result.
int main (int argc, char **argv)
Program that draws the maximal segments of digital curve whose chain code may be given as an argument. The chain code must be a sequence of characters belonging to the set {0,1,2,3}.
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2011/01/24
An example file named convex-and-concave-parts.
This file is part of the DGtal library.
Definition in file convex-and-concave-parts.cpp.
Function Documentation
drawCCP()
template<typename Iterator , typename Board > void drawCCP (const Iterator & itb, const Iterator & ite, Board & aBoard)
Function that draws the maximal segments with a color that depends on the local convexity:
blue in a convex part,
green in a concave part,
yellow in an inflection part (both convex and concave),
black in an end part (of a connected part).
Parameters
itb begin iterator on an ArithmeticalDSSComputer
ite end iterator on an ArithmeticalDSSComputer
aBoard board to draw
Template Parameters
Iterator a model of forward iterator and CSegmentComputerIterator
Board a Board2D type
Definition at line 95 of file convex-and-concave-parts.cpp.
{
  //choose the drawing mode
  aBoard << SetMode( "ArithmeticalDSS", "BoundingBox" );
  //prepare the drawing style and the pen color
  string aStyleName = "ArithmeticalDSS/BoundingBox";
  CustomPenColor* aPenColor;
  //for each maximal segment
  for (Iterator i(itb); i != ite; ++i) {
    //get the current maximal segment
    typedef typename Iterator::SegmentComputer::Primitive DSS;
    DSS maximalDSS = i->primitive();
    //if located at the end of a connected part
    if ( !(i.intersectNext() && i.intersectPrevious()) ) {
      aPenColor = new CustomPenColor( Color::Black );
      //otherwise
    } else {
      //get the points located before and after the maximal segment
      typedef typename DSS::Point Point;
      Point beforeFirst = *(--(i->begin()));
      Point afterLast = *(i->end());
      //remainders and bounds
      typedef typename DSS::Integer Integer;
      Integer r1 = maximalDSS.remainder(beforeFirst);
      Integer r2 = maximalDSS.remainder(afterLast);
      Integer mu = maximalDSS.mu();
      Integer omega = maximalDSS.omega();
      //configurations
      if ( (r1<=mu-1)&&(r2<=mu-1) ) {                    //concave
        aPenColor = new CustomPenColor( Color::Green);
      } else if ( (r1>=mu+omega)&&(r2>=mu+omega) ) {     //convex
        aPenColor = new CustomPenColor( Color::Blue );
      } else if ( (r1>=mu+omega)&&(r2<=mu-1) ) {         //convex to concave
        aPenColor = new CustomPenColor( Color::Yellow );
      } else if ( (r1<=mu-1)&&(r2>=mu+omega) ) {         //concave to convex
        aPenColor = new CustomPenColor( Color::Yellow );
      } else {                                           //pb
        aPenColor = new CustomPenColor( Color::Red );
      }
    }
    // draw the maximal segment on the board
    aBoard << CustomStyle( aStyleName, aPenColor )
           << maximalDSS;
  }
}
References DGtal::Color::Black, DGtal::Color::Blue, DGtal::Color::Green, DGtal::Color::Red, and DGtal::Color::Yellow.
Referenced by segmentationIntoMaximalDSSs().
main()
int main (int argc, char ** argv)
Program that draws the maximal segments of digital curve whose chain code may be given as an argument. The chain code must be a sequence of characters belonging to the set {0,1,2,3}.
Parameters
argc number of arguments
argv array of arguments
Returns
0
Definition at line 194 of file convex-and-concave-parts.cpp.
{
  trace.beginBlock ( "Example convex-and-concave-parts" );
  Board2D aBoard; //create a board
  //create a chain code
  string codes;
  if (argc >= 2) codes = argv[1];
  else codes = "030030330303303030300001010101101011010000030330303303030300001010110101011010000033";
  stringstream ss(stringstream::in | stringstream::out);
  ss << "0 0 " << codes << endl;
  FreemanChain<int> theContour( ss );
  trace.info() << "Processing of " << ss.str() << endl;
  //draw the digital contour
  aBoard
   << SetMode( "PointVector", "Grid" )
   << theContour;
  //draw the maximal segments
  segmentationIntoMaximalDSSs(theContour.begin(), theContour.end(), aBoard);
  //save the drawing
  aBoard.saveSVG("convex-and-concave-parts.svg");
  #ifdef WITH_CAIRO
    aBoard.saveCairo("convex-and-concave-parts.png");
  #endif
  trace.endBlock();
  return 0;
}
References DGtal::FreemanChain< TInteger >::begin(), DGtal::Trace::beginBlock(), DGtal::FreemanChain< TInteger >::end(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::saveCairo(), LibBoard::Board::saveSVG(), segmentationIntoMaximalDSSs(), and DGtal::trace.
segmentationIntoMaximalDSSs()
template<typename Iterator , typename Board > void segmentationIntoMaximalDSSs (const Iterator & itb, const Iterator & ite, Board & aBoard)
Perform a saturated segmentation into maximal digital straight segments of a given range of integer points and draw the result.
Parameters
itb begin iterator
ite end iterator
aBoard board to draw
Template Parameters
Iterator a model of forward iterator on digital points
Board a Board2D type
Definition at line 167 of file convex-and-concave-parts.cpp.
{
  typedef typename IteratorCirculatorTraits<Iterator>::Value::Coordinate Coordinate;
  //choose the primitive computer and the segmentation
  typedef ArithmeticalDSSComputer<Iterator,Coordinate,4> RecognitionAlgorithm;
  typedef SaturatedSegmentation<RecognitionAlgorithm> Segmentation;
  //create the segmentation
  RecognitionAlgorithm algo;
  Segmentation s(itb,ite,algo);
  //draw the result
  drawCCP(s.begin(), s.end(), aBoard);
}
References drawCCP().
Referenced by main().