DGtal: exampleSurfaceMesh.cpp File Reference
exampleSurfaceMesh.cpp File Reference
DGtal Examples
An example file for SurfaceMesh in 3D.
#include <string>
#include <iostream>
#include <fstream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/shapes/Mesh.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/shapes/SurfaceMeshHelper.h"
#include "DGtal/shapes/MeshHelpers.h"
#include "DGtal/graph/BreadthFirstVisitor.h"
#include "DGtal/io/readers/SurfaceMeshReader.h"
#include "DGtal/io/writers/SurfaceMeshWriter.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/io/Color.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
Functions
int main (int argc, char **argv)
Detailed Description
An example file for SurfaceMesh in 3D.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2020/07/15
This file is part of the DGtal library.
Definition in file exampleSurfaceMesh.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[exampleSurfaceMesh-typedef]
[exampleSurfaceMesh-typedef]
[exampleSurfaceMesh-read-mesh]
[exampleSurfaceMesh-read-mesh]
[exampleSurfaceMesh-make-torus]
[exampleSurfaceMesh-make-torus]
[exampleSurfaceMesh-make-pyramid]
[exampleSurfaceMesh-make-pyramid]
[exampleSurfaceMesh-graph-bft]
[exampleSurfaceMesh-graph-bft]
[exampleSurfaceMesh-write-obj]
[exampleSurfaceMesh-write-obj]
Definition at line 76 of file exampleSurfaceMesh.cpp.
{
  // The following typedefs are useful
  typedef SurfaceMesh< RealPoint, RealVector >       SurfMesh;
  typedef SurfaceMeshHelper< RealPoint, RealVector > Helper;
  typedef SurfMesh::Vertices                         Vertices;
  trace.beginBlock ( "Reading a mesh OBJ file" );
  SurfMesh    smesh;
  std::string S = examplesPath + "samples/spot.obj";
  std::ifstream input( S.c_str() );
  bool ok_read  =  SurfaceMeshReader< RealPoint, RealVector >::readOBJ( input, smesh );
  input.close();
  trace.info() << "Read " << ( ok_read ? "OK" : "ERROR" )
               << " mesh=" << smesh << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Building a torus" );
  auto torus_mesh = Helper::makeTorus
    ( 2.5, 0.5, RealPoint { 0.0, 0.0, 0.0 }, 40, 40, 0, Helper::NormalsType::NO_NORMALS );
  trace.endBlock();
  trace.beginBlock ( "Building a pyramid" );
  std::vector< RealPoint > positions =
    { { 0, 0, 5 }, { 1, 1, 3 }, { -1, 1, 3 }, { -1, -1, 3 }, { 1, -1, 3 } };
  std::vector< Vertices  > faces =
    { { 0, 1, 2 }, { 0, 2, 3 }, { 0, 3, 4 }, { 0, 4, 1 }, { 4, 3, 2, 1 } };
  auto pyramid_mesh = SurfMesh( positions.cbegin(), positions.cend(),
                                faces.cbegin(), faces.cend() );
  trace.endBlock();
  trace.beginBlock ( "Traversing a mesh by BF" );
  BreadthFirstVisitor< SurfMesh > visitor( smesh, 0 );
  std::vector<double>             distances( smesh.nbVertices() );
  double biggest_d = 0.0;
  while ( ! visitor.finished() )
    {
      auto v = visitor.current().first;  // current vertex
      auto d = visitor.current().second; // current distance
      biggest_d      = (double) d;
      distances[ v ] = biggest_d;
      visitor.expand();
    }
  trace.endBlock();
  trace.beginBlock ( "Colored output of BF traversal" );
  // Displaying faces colored by their distance to vertex 0.
  auto face_distances = smesh.computeFaceValuesFromVertexValues( distances );
  auto cmap = GradientColorMap< double >( 0.0, biggest_d, CMAP_JET );
  std::vector<Color> face_colors( smesh.nbFaces() );
  for ( SurfMesh::Face j = 0; j < smesh.nbFaces(); ++j )
    face_colors[ j ] = cmap( face_distances[ j ] );
  typedef SurfaceMeshWriter< RealPoint, RealVector > Writer;
  Writer::writeOBJ( "spot-bft.obj", smesh, face_colors );
  // Displaying three isolines.
  Writer::writeIsoLinesOBJ( "spot-iso-0_25.obj", smesh,
                            face_distances, distances, distances.back() * 0.25, 0.2 );
  Writer::writeIsoLinesOBJ( "spot-iso-0_5.obj",  smesh,
                            face_distances, distances, distances.back() * 0.5,  0.2 );
  Writer::writeIsoLinesOBJ( "spot-iso-0_75.obj", smesh,
                            face_distances, distances, distances.back() * 0.75, 0.2 );
  trace.endBlock();
  // Conversion to Mesh for easy display.
  Mesh< RealPoint > viewmesh(true);
  Mesh< RealPoint >  viewmesh2, viewmesh3;
  MeshHelpers::surfaceMesh2Mesh( smesh,      viewmesh , face_colors );
  MeshHelpers::surfaceMesh2Mesh( torus_mesh, viewmesh2 );
  MeshHelpers::surfaceMesh2Mesh( pyramid_mesh, viewmesh3 );
  QApplication application(argc,argv);
  Viewer3D<> viewer;
  viewer.show();
  viewer << viewmesh << viewmesh2 << viewmesh3;
  viewer << Viewer3D<>::updateDisplay;
  application.exec();
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::CMAP_JET, DGtal::SurfaceMesh< TRealPoint, TRealVector >::computeFaceValuesFromVertexValues(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), DGtal::Trace::endBlock(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), DGtal::Trace::info(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbFaces(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbVertices(), DGtal::SurfaceMeshReader< TRealPoint, TRealVector >::readOBJ(), DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::MeshHelpers::surfaceMesh2Mesh(), and DGtal::trace.