DGtal: exampleRationalBallQuickHull3D.cpp File Reference
exampleRationalBallQuickHull3D.cpp File Reference
DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/geometry/tools/QuickHull.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/io/writers/SurfaceMeshWriter.h"
Functions
double rand01 ()
[QuickHull3D-Includes]
int main (int argc, char *argv[])
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/01/01
An example file named exampleRationalBallQuickHull3D.
This file is part of the DGtal library.
Definition in file exampleRationalBallQuickHull3D.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
[QuickHull3D-Typedefs]
[QuickHull3D-Typedefs]
[QuickHull3D-Computation]
[QuickHull3D-Computation] [QuickHull3D-Timings]
[QuickHull3D-Timings]
[QuickHull3D-BuildMesh]
[QuickHull3D-BuildMesh]
[QuickHull3D-OutputMesh]
[QuickHull3D-OutputMesh]
Definition at line 63 of file exampleRationalBallQuickHull3D.cpp.
{
  int    nb = argc > 1 ? atoi( argv[ 1 ] ) : 100;  // nb points
  double  R = argc > 2 ? atof( argv[ 2 ] ) : 10.0; // radius of ball
  double precision = argc > 3 ? atof( argv[ 3 ] ) : 1024.0; // precision
  // (0) typedefs
  typedef DGtal::ConvexHullRationalKernel< 3 > Kernel3D;
  typedef DGtal::QuickHull< Kernel3D >         QuickHull3D;
  // (1) create range of random points in ball
  std::vector< RealPoint > V;
  const double R2 = R * R;
  for ( int i = 0; i < nb; ) {
    RealPoint p( rand01()*2.0*R - R, rand01()*2.0*R - R, rand01()*2.0*R - R );
    if ( p.squaredNorm() < R2 ) { V.push_back( p ); i++; }
  }
  // (2) compute convex hull
  Kernel3D kernel( precision );
  QuickHull3D hull( kernel );
  hull.setInput( V );
  hull.computeConvexHull();
  std::cout << "#points="    << hull.nbPoints()
            << " #vertices=" << hull.nbVertices()
            << " #facets="   << hull.nbFacets() << std::endl;
  double total_time = 0;
  std::for_each( hull.timings.cbegin(), hull.timings.cend(),
                 [&total_time] ( double t ) { total_time += t; } );
  std::cout << "purge duplicates= " << round(hull.timings[ 0 ]) << " ms." << std::endl;
  std::cout << "init simplex    = " << round(hull.timings[ 1 ]) << " ms." << std::endl;
  std::cout << "quickhull core  = " << round(hull.timings[ 2 ]) << " ms." << std::endl;
  std::cout << "compute vertices= " << round(hull.timings[ 3 ]) << " ms." << std::endl;
  std::cout << "total time      = " << round(total_time) << " ms." << std::endl;
  // (3) build mesh
  std::vector< RealPoint > positions;
  hull.getVertexPositions( positions );
  std::vector< std::vector< std::size_t > > facets;
  hull.getFacetVertices( facets );
  typedef DGtal::SurfaceMesh< RealPoint, RealVector> SMesh;
  SMesh mesh( positions.cbegin(), positions.cend(), facets.cbegin(), facets.cend() );
  // (4) output result as OBJ file
  std::ofstream out( "qhull.obj" );
  DGtal::SurfaceMeshWriter< RealPoint, RealVector >::writeOBJ( out, mesh );
  out.close();
  return 0;
}
References DGtal::QuickHull< TKernel >::computeConvexHull(), DGtal::QuickHull< TKernel >::getFacetVertices(), DGtal::QuickHull< TKernel >::getVertexPositions(), DGtal::QuickHull< TKernel >::nbFacets(), DGtal::QuickHull< TKernel >::nbPoints(), DGtal::QuickHull< TKernel >::nbVertices(), rand01(), DGtal::QuickHull< TKernel >::setInput(), DGtal::QuickHull< TKernel >::timings, and DGtal::SurfaceMeshWriter< TRealPoint, TRealVector >::writeOBJ().
rand01()
double rand01 ()
[QuickHull3D-Includes]
[QuickHull3D-Includes]
Definition at line 60 of file exampleRationalBallQuickHull3D.cpp.
{ return (double) rand() / (double) RAND_MAX; }
Referenced by main().