DGtal: exampleAlphaThickSegmentTgtCover.cpp File Reference
exampleAlphaThickSegmentTgtCover.cpp File Reference
DGtal Examples
#include <iostream>
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/curves/AlphaThickSegmentComputer.h"
#include "DGtal/geometry/curves/SaturatedSegmentation.h"
#include "DGtal/base/Circulator.h"
#include "DGtal/geometry/curves/SegmentComputerUtils.h"
#include "DGtal/io/boards/Board2D.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2015/11/08
An example file named exampleAlphaThickSegmentTgtCover.
This file is part of the DGtal library.
Definition in file exampleAlphaThickSegmentTgtCover.cpp.
Function Documentation
main()
int main (void)
[SaturatedAlphaThickCoverTypes]
[SaturatedAlphaThickCoverTypes]
[SaturatedAlphaThickCoverCirculator]
[SaturatedAlphaThickCoverCirculator]
[SaturatedAlphaThickCoverComputerSeg]
[SaturatedAlphaThickCoverComputerSeg]
[SaturatedAlphaThickCoverDisplay]
[SaturatedAlphaThickCoverDisplay]
[SaturatedAlphaThickCoverSingleInit]
[SaturatedAlphaThickCoverSingleInit]
[SaturatedAlphaThickCoverDisplaySingle]
[SaturatedAlphaThickCoverDisplaySingle]
Definition at line 67 of file exampleAlphaThickSegmentTgtCover.cpp.
{
  trace.beginBlock ( "Example of AlphaThickSegment tangential cover obtained from SaturatedSegmentation" );
  typedef std::vector<Z2i::RealPoint>::const_iterator RAConstIterator;
  typedef Circulator<RAConstIterator> ConstCirculator;
  typedef AlphaThickSegmentComputer<Z2i::RealPoint, ConstCirculator> AlphaThickSegmentComputer2D;
  typedef SaturatedSegmentation<AlphaThickSegmentComputer2D> AlphaSegmentation;
  Board2D aBoard, aBoard2;
  std::string file = examplesPath + "samples/contourSnoisy.sdp";
  std::vector<Z2i::RealPoint> aContour = PointListReader<Z2i::RealPoint>::getPointsFromFile (file);
  // displaying contour
  aBoard << SetMode(aContour[0].className(), "Grid");
  aBoard2 << SetMode(aContour[0].className(), "Grid");
  std::vector<LibBoard::Point> poly;
  for (unsigned int i = 0; i< aContour.size(); i++)  poly.push_back(LibBoard::Point(aContour[i][0], aContour[i][1]));
  aBoard.setPenColor(DGtal::Color(200, 200, 200));
  aBoard.fillPolyline(poly);
  aBoard2.setPenColor(DGtal::Color(200, 200, 200));
  aBoard2.fillPolyline(poly);
  Circulator<RAConstIterator> circulator (aContour.begin(), aContour.begin(), aContour.end());
  AlphaThickSegmentComputer2D computer(4, functions::Hull2D::EuclideanThickness);
  AlphaSegmentation segmentator(circulator, circulator, computer);
  AlphaSegmentation::SegmentComputerIterator i = segmentator.begin();
  AlphaSegmentation::SegmentComputerIterator end = segmentator.end();
  for ( ; i != end; ++i) {
    AlphaThickSegmentComputer2D current(*i);
    aBoard << SetMode(current.className(), "BoundingBox");
    aBoard << current;
  }
  aBoard.saveEPS("exampleAlphaThickSegmentTgtCover.eps");
  trace.endBlock();
  trace.beginBlock ( "Example of AlphaThickSegment tangential cover obtained for a single point" );
  // Displaying Tangential cover associated to a single point:
  unsigned int index = 80;
  firstMaximalSegment(computer, circulator+index, circulator, circulator);
  AlphaThickSegmentComputer2D first (computer);
  lastMaximalSegment(computer, circulator+index, circulator, circulator);
  AlphaThickSegmentComputer2D last (computer);
  aBoard2.setPenColor(DGtal::Color::Blue);
  aBoard2.fillCircle((*(circulator+index))[0], (*(circulator+index))[1], 1.0);
  while(first.end() != last.end()){
    aBoard2 << SetMode(first.className(), "BoundingBox");
    aBoard2 << first;
    nextMaximalSegment(first, circulator);
  }
  aBoard2 << last;
  stringstream name;
  name << "exampleAlphaThickSegmentTgtCoverPoint" << index<< ".eps";
  aBoard2.saveEPS(name.str().c_str());
  trace.endBlock();
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, DGtal::Trace::endBlock(), DGtal::functions::Hull2D::EuclideanThickness, LibBoard::Board::fillCircle(), LibBoard::Board::fillPolyline(), DGtal::firstMaximalSegment(), DGtal::PointListReader< TPoint >::getPointsFromFile(), DGtal::lastMaximalSegment(), DGtal::nextMaximalSegment(), LibBoard::Board::saveEPS(), LibBoard::Board::setPenColor(), and DGtal::trace.