DGtal: testShapeMoveCenter.cpp File Reference
testShapeMoveCenter.cpp File Reference
DGtal Test Files
#include <iostream>
#include <random>
#include "DGtalCatch.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/parametric/AccFlower2D.h"
#include "DGtal/shapes/parametric/Astroid2D.h"
#include "DGtal/shapes/parametric/Ball2D.h"
#include "DGtal/shapes/parametric/Ellipse2D.h"
#include "DGtal/shapes/parametric/Flower2D.h"
#include "DGtal/shapes/parametric/Lemniscate2D.h"
#include "DGtal/shapes/parametric/NGon2D.h"
#include "DGtal/shapes/implicit/ImplicitBall.h"
#include "DGtal/shapes/implicit/ImplicitHyperCube.h"
#include "DGtal/shapes/implicit/ImplicitNorm1Ball.h"
#include "DGtal/shapes/implicit/ImplicitRoundedHyperCube.h"
Typedefs
typedef Z2i::Space Space
typedef Z2i::Point Point
typedef Z2i::RealPoint RealPoint
typedef AccFlower2D< Space > AccFlower
typedef Astroid2D< Space > Astroid
typedef Ball2D< Space > Ball
typedef Ellipse2D< Space > Ellipse
typedef Flower2D< Space > Flower
typedef Lemniscate2D< Space > Lemniscate
typedef NGon2D< Space > NGon
typedef ImplicitBall< Space > BallImplicit
typedef ImplicitHyperCube< Space > HyperCubeImplicit
typedef ImplicitNorm1Ball< Space > Norm1BallImplicit
typedef ImplicitRoundedHyperCube< Space > RoundedHyperCubeImplicit
Functions
template<typename Shape >
Shape createShape (const RealPoint &center, const RealPoint &radii)
template<>
AccFlower createShape (const RealPoint &center, const RealPoint &radii)
template<>
Astroid createShape (const RealPoint &center, const RealPoint &radii)
template<>
Ball createShape (const RealPoint &center, const RealPoint &radii)
template<>
Ellipse createShape (const RealPoint &center, const RealPoint &radii)
template<>
Flower createShape (const RealPoint &center, const RealPoint &radii)
template<>
Lemniscate createShape (const RealPoint &center, const RealPoint &radii)
template<>
NGon createShape (const RealPoint &center, const RealPoint &radii)
template<>
BallImplicit createShape (const RealPoint &center, const RealPoint &radii)
template<>
HyperCubeImplicit createShape (const RealPoint &center, const RealPoint &radii)
template<>
Norm1BallImplicit createShape (const RealPoint &center, const RealPoint &radii)
template<>
RoundedHyperCubeImplicit createShape (const RealPoint &center, const RealPoint &radii)
std::uniform_real_distribution< double > unif (-1000000., 1000000.)
TEMPLATE_TEST_CASE ("Star shapes", "move() method", AccFlower, Astroid, Ball, Ellipse, Flower, Lemniscate, NGon, BallImplicit, HyperCubeImplicit, Norm1BallImplicit, RoundedHyperCubeImplicit)
Variables
std::default_random_engine re
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Adrien Krähenbühl (krahe.nosp@m.nbuh.nosp@m.l@uni.nosp@m.stra.nosp@m..fr) Laboratoire ICube, UMR 7357, Université de Strasbourg, France
Date
2019/07/08
Functions for testing the moveTo() method of star shapes.
This file is part of the DGtal library.
Definition in file testShapeMoveCenter.cpp.
Typedef Documentation
AccFlower
typedef AccFlower2D<Space> AccFlower
Definition at line 56 of file testShapeMoveCenter.cpp.
Astroid
typedef Astroid2D<Space> Astroid
Definition at line 57 of file testShapeMoveCenter.cpp.
Ball
typedef Ball2D<Space> Ball
Examples
dec/exampleHeatLaplace.cpp.
Definition at line 58 of file testShapeMoveCenter.cpp.
BallImplicit
typedef ImplicitBall<Space> BallImplicit
Definition at line 64 of file testShapeMoveCenter.cpp.
Ellipse
typedef Ellipse2D<Space> Ellipse
Definition at line 59 of file testShapeMoveCenter.cpp.
Flower
typedef Flower2D<Space> Flower
Definition at line 60 of file testShapeMoveCenter.cpp.
HyperCubeImplicit
typedef ImplicitHyperCube<Space> HyperCubeImplicit
Definition at line 65 of file testShapeMoveCenter.cpp.
Lemniscate
typedef Lemniscate2D<Space> Lemniscate
Definition at line 61 of file testShapeMoveCenter.cpp.
NGon
typedef NGon2D<Space> NGon
Definition at line 62 of file testShapeMoveCenter.cpp.
Norm1BallImplicit
typedef ImplicitNorm1Ball<Space> Norm1BallImplicit
Definition at line 66 of file testShapeMoveCenter.cpp.
Point
typedef Z2i::Point Point
Definition at line 53 of file testShapeMoveCenter.cpp.
RealPoint
typedef Z2i::RealPoint RealPoint
Definition at line 54 of file testShapeMoveCenter.cpp.
RoundedHyperCubeImplicit
typedef ImplicitRoundedHyperCube<Space> RoundedHyperCubeImplicit
Definition at line 67 of file testShapeMoveCenter.cpp.
Space
typedef Z2i::Space Space
Definition at line 52 of file testShapeMoveCenter.cpp.
Function Documentation
createShape() [1/12]
template<typename Shape > Shape createShape (const RealPoint & center, const RealPoint & radii)
createShape() [2/12]
template<> AccFlower createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 73 of file testShapeMoveCenter.cpp.
{
  return AccFlower( center, radii[0], radii[1], 12, 2. );
}
createShape() [3/12]
template<> Astroid createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 79 of file testShapeMoveCenter.cpp.
{
  return Astroid( center, radii[0], radii[1] );
}
createShape() [4/12]
template<> Ball createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 85 of file testShapeMoveCenter.cpp.
{
  return Ball( center, radii[0] );
}
createShape() [5/12]
template<> Ellipse createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 91 of file testShapeMoveCenter.cpp.
{
  return Ellipse( center, radii[0], radii[1], 2. );
}
createShape() [6/12]
template<> Flower createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 97 of file testShapeMoveCenter.cpp.
{
  return Flower( center, radii[0], radii[1], 5, 2. );
}
createShape() [7/12]
template<> Lemniscate createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 103 of file testShapeMoveCenter.cpp.
{
  return Lemniscate( center, radii[0] );
}
createShape() [8/12]
template<> NGon createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 109 of file testShapeMoveCenter.cpp.
{
  return NGon( center, radii[0], 20, 2. );
}
createShape() [9/12]
template<> BallImplicit createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 115 of file testShapeMoveCenter.cpp.
{
  return BallImplicit( center, radii[0] );
}
createShape() [10/12]
template<> HyperCubeImplicit createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 121 of file testShapeMoveCenter.cpp.
{
  return HyperCubeImplicit( center, radii[0] );
}
createShape() [11/12]
template<> Norm1BallImplicit createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 127 of file testShapeMoveCenter.cpp.
{
  return Norm1BallImplicit( center, radii[0] );
}
createShape() [12/12]
template<> RoundedHyperCubeImplicit createShape (const RealPoint & center, const RealPoint & radii)
Definition at line 133 of file testShapeMoveCenter.cpp.
{
  return RoundedHyperCubeImplicit( center, radii[0], 3. );
}
TEMPLATE_TEST_CASE()
TEMPLATE_TEST_CASE ("Star shapes" , "move() method" , AccFlower , Astroid , Ball , Ellipse , Flower , Lemniscate , NGon , BallImplicit , HyperCubeImplicit , Norm1BallImplicit , RoundedHyperCubeImplicit)
Definition at line 141 of file testShapeMoveCenter.cpp.
{
  const double centerX = unif(re);
  const double centerY = unif(re);
  const double radiusX = unif(re);
  const double radiusY = unif(re);
  TestType shape = createShape<TestType>( RealPoint(centerX, centerY), RealPoint(radiusX, radiusY) );
  SECTION("Center coordinates")
    {
      REQUIRE( shape.center() == RealPoint(centerX, centerY) );
    }
  SECTION("Change center position")
    {
      const double newCenterX = unif(re);
      const double newCenterY = unif(re);
      shape.moveTo( RealPoint( newCenterX, newCenterY ) );
      REQUIRE( shape.center() == RealPoint( newCenterX, newCenterY ) );
    }
}
References re, REQUIRE(), SECTION(), and unif().
unif()
std::uniform_real_distribution< double > unif (- 1000000., 1000000.)
Referenced by notNullRealPoint(), notNullValue(), TEMPLATE_TEST_CASE(), and TEST_CASE().
Variable Documentation
re
std::default_random_engine re
Definition at line 139 of file testShapeMoveCenter.cpp.
Referenced by notNullRealPoint(), notNullValue(), LibBoard::Ellipse::rotate(), TEMPLATE_TEST_CASE(), TEST_CASE(), testCurvature2d(), testEstimatorCache(), testGaussianCurvature3d(), testMeanCurvature3d(), and testPrincipalCurvatures3d().