DGtal: testLongvol.cpp File Reference
testLongvol.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/io/writers/LongvolWriter.h"
#include "DGtal/io/readers/LongvolReader.h"
Functions
bool testLongvol ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2011/06/11
Functions for testing class Longvol.
This file is part of the DGtal library.
Definition in file testLongvol.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 88 of file testLongvol.cpp.
{
  trace.beginBlock ( "Testing class Longvol" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testLongvol(); // && ... other tests
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testLongvol(), and DGtal::trace.
testLongvol()
bool testLongvol ()
Example of a test. To be completed.
Definition at line 50 of file testLongvol.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Testing Longvol writer ..." );
  Z3i::Point a(0,0,0);
  Z3i::Point b(15,15,15);
  Z3i::Point c(7,7,7);
  typedef ImageContainerBySTLVector<Z3i::Domain, DGtal::uint64_t> Image;
  Image image(Z3i::Domain(a,b));
  image.setValue(c,0X8899AABBCCDDEEFFull);
  LongvolWriter<Image>::exportLongvol("export-longvol.longvol",image);
  Image image2 =  LongvolReader<Image>::importLongvol("export-longvol.longvol");
  bool allFine= true;
  Image::ConstIterator ito = image.begin();
  for(Image::ConstIterator it = image2.begin(), itend=image2.end();
      it != itend; ++it, ++ito)
    allFine &= (*it) == (*ito);
  nbok += allFine ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") "
         << "true == true" << std::endl;
  trace.endBlock();
  return nbok == nb;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::LongvolWriter< TImage, TFunctor >::exportLongvol(), DGtal::LongvolReader< TImageContainer, TFunctor >::importLongvol(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().