DGtal: viewer3D-8bis-2Dimages.cpp File Reference
viewer3D-8bis-2Dimages.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/images/ImageHelper.h"
#include "ConfigExamples.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/kernel/BasicPointFunctors.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2013/11/18
An example file named viewer3D-8bis-2Dimages.
This file is part of the DGtal library.
Definition in file viewer3D-8bis-2Dimages.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[ExampleViewer3D2DImagesExtractImagesNonSliceType]
[ExampleViewer3D2DImagesExtractImagesNonSliceType]
[ExampleViewer3D2DImagesExtractImagesNonSliceParam]
[ExampleViewer3D2DImagesExtractImagesNonSliceParam]
[ExampleViewer3D2DImagesExtractImagesNonSliceExtract]
[ExampleViewer3D2DImagesExtractImagesNonSliceExtract]
[ExampleViewer3D2DImagesExtractImagesNonSliceDisplay]
[ExampleViewer3D2DImagesExtractImagesNonSliceDisplay]
Definition at line 55 of file viewer3D-8bis-2Dimages.cpp.
{
  typedef DGtal::ImageContainerBySTLVector<DGtal::Z3i::Domain,  unsigned char > Image3D;
  typedef DGtal::ConstImageAdapter<Image3D, Z2i::Domain, DGtal::functors::Point2DEmbedderIn3D<DGtal::Z3i::Domain>,
                                   Image3D::Value,  DGtal::functors::Identity >  ImageAdapterExtractor;
  QApplication application(argc,argv);
  typedef Viewer3D<> MyViewer;
  MyViewer viewer;
  viewer.show();
  std::string inputFilename = examplesPath + "samples/lobster.vol";
  Image3D imageVol = VolReader<Image3D>::importVol(inputFilename);
  DGtal::functors::Identity idV;
  DGtal::Z3i::Point ptCenter(50, 62, 28);
  const int IMAGE_PATCH_WIDTH = 20;
  // Setting the image domain of the resulting image to be displayed in 3D:
  DGtal::Z2i::Domain domainImage2D (DGtal::Z2i::Point(0,0),
                                    DGtal::Z2i::Point(IMAGE_PATCH_WIDTH, IMAGE_PATCH_WIDTH));
  unsigned int pos=0;
  for (double alpha = 0; alpha< 1.54; alpha+= 0.01){
    // Extracting images from 3D embeder
    DGtal::functors::Point2DEmbedderIn3D<DGtal::Z3i::Domain >  embedder(imageVol.domain(),
                                                                        ptCenter+DGtal::Z3i::Point(static_cast<int>(200.0*cos(alpha)),static_cast<int>(100.0*sin(alpha))),
                                                                        DGtal::Z3i::RealPoint(cos(alpha),sin(alpha),cos(2.0*alpha)),
                                                                        IMAGE_PATCH_WIDTH);
    ImageAdapterExtractor extractedImage(imageVol, domainImage2D, embedder, idV);
    //Display image and update its position with embeder
    viewer << extractedImage;
    viewer << DGtal::UpdateImage3DEmbedding<Z3i::Space, Z3i::KSpace>(pos,
                                                                     embedder(Z2i::RealPoint(0,0)),
                                                                     embedder(Z2i::RealPoint(IMAGE_PATCH_WIDTH,0)),
                                                                     embedder(domainImage2D.upperBound()),
                                                                     embedder(Z2i::RealPoint(0, IMAGE_PATCH_WIDTH)));
    pos++;
  }
  viewer << MyViewer::updateDisplay;
  return application.exec();
}
References IMAGE_PATCH_WIDTH, DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::Display3D< Space, KSpace >::updateDisplay, and DGtal::HyperRectDomain< TSpace >::upperBound().