DGtal: volDistanceTraversal.cpp File Reference
volDistanceTraversal.cpp File Reference
DGtal Examples
#include <iostream>
#include <queue>
#include <QImageReader>
#include "DGtal/base/BasicFunctors.h"
#include "DGtal/topology/CanonicSCellEmbedder.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/graph/DistanceBreadthFirstVisitor.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/LightImplicitDigitalSurface.h"
#include "DGtal/geometry/volumes/distance/LpMetric.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/io/Color.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
Functions
void usage (int, char **argv)
int main (int argc, char **argv)
Detailed Description
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/02/06
An example file named volDistanceTraversal.
This file is part of the DGtal library.
Definition in file volDistanceTraversal.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[volDistanceTraversal-readVol]
[volDistanceTraversal-readVol]
[volDistanceTraversal-KSpace]
[volDistanceTraversal-KSpace]
[volDistanceTraversal-SurfelAdjacency]
[volDistanceTraversal-SurfelAdjacency]
[volDistanceTraversal-SetUpDigitalSurface]
[volDistanceTraversal-SetUpDigitalSurface]
[volDistanceTraversal-ExtractingSurface]
[volDistanceTraversal-ExtractingSurface]
[volDistanceTraversal-DisplayingSurface]
[volDistanceTraversal-DisplayingSurface]
Definition at line 69 of file volDistanceTraversal.cpp.
{
  if ( argc < 4 )
    {
      usage( argc, argv );
      return 1;
    }
  std::string inputFilename = argv[ 1 ];
  unsigned int minThreshold = atoi( argv[ 2 ] );
  unsigned int maxThreshold = atoi( argv[ 3 ] );
  unsigned int idxP = (argc <= 4) ? 0 : atoi( argv[ 4 ] );
  trace.beginBlock( "Reading vol file into an image." );
  typedef ImageSelector < Domain, int>::Type Image;
  Image image = VolReader<Image>::importVol(inputFilename);
  DigitalSet set3d (image.domain());
  SetFromImage<DigitalSet>::append<Image>(set3d, image,
                                          minThreshold, maxThreshold);
  trace.endBlock();
  trace.beginBlock( "Construct the Khalimsky space from the image domain." );
  KSpace ks;
  bool space_ok = ks.init( image.domain().lowerBound(),
                           image.domain().upperBound(), true );
  if (!space_ok)
    {
      trace.error() << "Error in the Khamisky space construction."<<std::endl;
      return 2;
    }
  trace.endBlock();
  typedef SurfelAdjacency<KSpace::dimension> MySurfelAdjacency;
  MySurfelAdjacency surfAdj( true ); // interior in all directions.
  trace.beginBlock( "Set up digital surface." );
  typedef LightImplicitDigitalSurface<KSpace, DigitalSet >
    MyDigitalSurfaceContainer;
  typedef DigitalSurface<MyDigitalSurfaceContainer> MyDigitalSurface;
  SCell bel = Surfaces<KSpace>::findABel( ks, set3d, 100000 );
  MyDigitalSurfaceContainer* ptrSurfContainer =
    new MyDigitalSurfaceContainer( ks, set3d, surfAdj, bel );
  MyDigitalSurface digSurf( ptrSurfContainer ); // acquired
  trace.endBlock();
  // Find first bel.
  MyDigitalSurface::ConstIterator it = digSurf.begin();
  for ( idxP = idxP % digSurf.size(); idxP != 0; --idxP ) ++it;
  bel = *it;
  trace.beginBlock( "Extracting boundary by distance tracking from an initial bel." );
  typedef CanonicSCellEmbedder<KSpace> SCellEmbedder;
  typedef SCellEmbedder::Value RealPoint;
  typedef RealPoint::Coordinate Scalar;
  typedef LpMetric<Space> Distance;
  using DistanceToPoint = std::function<double(const Space::RealPoint &)>;
  typedef DGtal::functors::Composer<SCellEmbedder, DistanceToPoint, Scalar> VertexFunctor;
  typedef DistanceBreadthFirstVisitor< MyDigitalSurface, VertexFunctor, std::set<SCell> >
    MyDistanceVisitor;
  typedef MyDistanceVisitor::Node MyNode;
  typedef MyDistanceVisitor::Scalar MySize;
  SCellEmbedder embedder( ks );
  Distance distance(2.0);
  DistanceToPoint distanceToPoint = std::bind( distance, embedder( bel ), std::placeholders::_1 );
  VertexFunctor vfunctor( embedder, distanceToPoint );
  MyDistanceVisitor visitor( digSurf, vfunctor, bel );
  unsigned long nbSurfels = 0;
  MyNode node;
  while ( ! visitor.finished() )
    {
      node = visitor.current();
      ++nbSurfels;
      visitor.expand();
    }
  MySize maxDist = node.second;
  trace.endBlock();
  trace.beginBlock( "Displaying surface in Viewer3D." );
  QApplication application(argc,argv);
  Viewer3D<> viewer( ks );
  viewer.show();
  HueShadeColorMap<MySize,1> hueShade( 0, maxDist );
  MyDistanceVisitor visitor2( digSurf, vfunctor, bel );
  viewer << SetMode3D( bel.className(), "Basic" );
  viewer << CustomColors3D( Color::Black, Color::White )
         << bel;
  visitor2.expand();
  std::vector< MyDistanceVisitor::Node > layer;
  while ( ! visitor2.finished() )
    {
      MyNode n = visitor2.current();
      Color c = hueShade( n.second );
      viewer << CustomColors3D( Color::Red, c )
             << n.first;
      visitor2.expand();
    }
  viewer << Viewer3D<>::updateDisplay;
  trace.info() << "nb surfels = " << nbSurfels << std::endl;
  trace.endBlock();
  return application.exec();
}
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::begin(), DGtal::Trace::beginBlock(), DGtal::Color::Black, DGtal::SignedKhalimskyCell< dim, TInteger >::className(), DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::Color::Red, DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::size(), DGtal::trace, and DGtal::Color::White.
usage()
void usage (int , char ** argv)
Definition at line 61 of file volDistanceTraversal.cpp.
{
  std::cerr << "Usage: " << argv[ 0 ] << " <fileName.vol> <minT> <maxT> <idxP>" << std::endl;
  std::cerr << "\t - displays the Euclidean distance to the specified surfel on the boundary of the shape stored in vol file <fileName.vol>." << std::endl;
  std::cerr << "\t - the shape is defined implicitly: voxel v belongs to the shape iff its value I(v) follows minT < I(v) <= maxT." << std::endl;
  std::cerr << "\t - starts from the <idxP>-th surfel or first one if invalid." << std::endl;
}