DGtal: DGtal::Trace Class Reference
DGtal::Trace Class Reference
implementation of basic methods to trace out messages with indentation levels.
#include <DGtal/base/Trace.h>
Public Member Functions
Trace (TraceWriter &writer)
~Trace ()
void reset ()
void beginBlock (const std::string &keyword="")
double endBlock ()
std::ostream & info ()
std::ostream & warning ()
std::ostream & error ()
std::ostream & emphase ()
void progressBar (const double currentValue, const double maximalValue)
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Member Functions
Trace (const Trace &other)
Trace & operator= (const Trace &other)
Private Attributes
unsigned int myCurrentLevel
The indentation level.
std::string myCurrentPrefix
The indentation prefix string.
std::stack< std::string > myKeywordStack
A stack to store the block keywords.
TraceWriter & myWriter
A reference to the output writer.
std::stack< Clock * > myClockStack
A stack to store the block clocks.
int myProgressBarCurrent
Progress bar current position.
unsigned int myProgressBarRotation
Progress bar rotation position.
bool myStyle
True if the style has changed.
Detailed Description
implementation of basic methods to trace out messages with indentation levels.
Description of class 'Trace'
Aim:
Trace objects use a TraceWriter to switch between terminal and file outputs. Methods postfixed with "Debug" contain no code if the compilation flag DEBUG is not set.
For usage examples, see the testtrace.cpp file.
See also
testTrace.cpp
Todo
Create a default constructor on TraceWriterTerm(std::cerr)
Definition at line 73 of file Trace.h.
Constructor & Destructor Documentation
Trace() [1/2]
DGtal::Trace::Trace (TraceWriter & writer)
Constructor.
Parameters
writer the output writer that will receive the traces.
~Trace()
DGtal::Trace::~Trace ()
Destructor.
Trace() [2/2]
DGtal::Trace::Trace (const Trace & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
beginBlock()
void DGtal::Trace::beginBlock (const std::string & keyword = "")
Enter a new block and increase the indentation level
Parameters
keyword contains a label to the new block
Examples
dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusChladni.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, doc-examples/kernelDomain.cpp, doc-examples/range.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleDSLSubsegment.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleFrechetShortcut.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/curves/greedyAlphaThickDecomposition.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/examplePreimage.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/distance/voronoimap2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount4D.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/volDistanceTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleImageFactoryFromHDF5.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, images/exampleTiledImage.cpp, images/extract2DImagesFrom3D.cpp, images/extract2DImagesFrom3DandVisu.cpp, images/extract2DSlicesImagesFrom3D.cpp, images/imageBasicSubsampling.cpp, images/raw2HDF5.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/dgtalBoard3D-1-points.cpp, io/boards/exampleBezierCurve.cpp, io/boards/logoDGtal.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, shapes/exampleEuclideanShapesDecorator.cpp, shapes/exampleMeshVoxelizer.cpp, shapes/exampleSurfaceMesh.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-fillContours.cpp, topology/cubical-complex-collapse.cpp, topology/cubical-complex-illustrations.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/generateSimplicityTables3D.cpp, topology/homotopicThinning3D.cpp, topology/khalimskySpaceScanner.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/2DSliceImageFromVol.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, tutorial-examples/FMMErosion.cpp, and tutorial-examples/polyhedralizer.cpp.
Referenced by accuracyTest(), basicBidirectionalTest(), basicForwardTest(), basicRandomAccessTest(), basicTest(), basicTest2(), basicUsage(), checkCut(), checkExtendWithManyPoints(), checkManyPlanes(), checkWidth(), CompareToArithmetical(), comparisonLeftHull(), comparisonSubsegment(), comparisonSubsegment2(), compatibleStepsTest(), computeLaplace(), constructorsTest(), createDSSTest(), DGtal::VoxelComplex< TKSpace, TCellContainer >::criticalCliques(), drawArithmeticalDSL(), estimatorOnShapeDigitization(), example(), exampleArithmeticalDSLTypes(), exampleConstructors(), exampleImage3D(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleTiledImageFromHDF5_10blocks3D(), exampleTiledImageFromHDF5_1block3D(), exampleTiledImageFromImage_10blocks3D(), exampleTiledImageFromImage_1block3D(), exampleUpdate(), exhaustiveTestLatticePolytope2D(), greedySegmentationVisualTest(), HDF5_3D2vol(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initOperators(), initQuantities(), initQuantitiesCached(), laplacian(), main(), main(), main(), main(), mainTest(), moduleImages_example(), precompute(), randomTest2x2DetComputer(), rangeTest(), raw2HDF5_3D(), runATest(), SaturatedSegmentationTest(), SaturatedSegmentationVisualTest(), saveToObj(), showGreedySegmantation(), simpleTest2x2DetComputer(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveForEpsilon(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveGammaConvergence(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveOneAlternateStep(), specialCases(), stoppingCriterionTest(), test(), test2D_int32(), test3d(), test3dSurfaceHelper(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), test_g_f_fm1(), test_linear_ring(), test_linear_structure(), test_manual_operators_2d(), test_manual_operators_3d(), test_range_constRange(), testAdvance(), testAliasCases(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testAngleLinearMinimizer(), testAPI(), testArithm(), testBadKeySizes(), testBallQuad(), testBasicBoolFunctors(), testBasicFunctors(), testBasicMasks(), testBasicMathFunctions(), testBIGINTEGER(), testBIGINTEGERSpace(), testBinarySearch(), testBinomialConvolver(), testBoard2D(), testBoard3D(), testChamferSimple(), testCheckImageConcept(), testChessboard(), testChordNaivePlaneComputer(), testCloneCases(), testCloneTimings(), testCOBANaivePlaneComputer(), testCodesIterators(), testColor(), testColRow(), testCombinatorialSurface(), testCompareEstimator(), testCompareExactBruteForce(), testCompareExactInexact(), testCompareInexactBruteForce(), testComparison(), testComputeInterior(), testConcepts(), testConsistence(), testConstAliasCases(), testConstructor(), testConstructors(), testContinuedFractions(), testContourHelper(), testConvexHull2D(), testConvexHullCompThickness(), testCorner(), testCountedConstPtrOrConstPtrMemory(), testCountedPtr(), testCountedPtrCopy(), testCountedPtrMemory(), testCountedPtrOrPtrMemory(), testCreate(), testCube(), testCurvature2d(), testDetCofactor(), testDGtalBIGINTEGER(), testDigitalSetBoundary(), testDigitalSetDomain(), testDigitalSetDraw(), testDigitalSetSelector(), testDigitalShapesDecorator(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testDigitalTopologyZ2(), testDisplayDT2d(), testDisplayDT3d(), testDisplayDTFromCircle(), testDistancePropagation(), testDistanceTransformation(), testDistanceTransformation3D(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDistanceTransformND(), testDoubleOnSegment(), testDoubleShrink(), testDoubleShrinkHorizontal(), testDraw(), testDSLSubsegment(), testDSS4drawing(), testDSS8drawing(), testDSSreco(), testDTFromSet(), testDuvalPP(), testDuvalPPMod(), testEigenDecomposition(), testEmbedder(), testEstimatorCache(), testEuclideanShapesDecorator(), testExpander(), testExplicitDigitalSurface(), testExtendRetractFront(), testFileStream(), testFindABel(), testFitting(), testFLF(), testFrechetShortcut(), testGaussDigitizer(), testGaussianCurvature3d(), testGenericReader(), testGenericWriter(), testGetSetVal(), testGrayscaleColorMap(), testHashTree(), testHashTree2D(), testHDF5_3DReader(), testHDF5Reader(), testHiddenBy(), testHullFunctions2D(), testImage(), testImageAdapter(), testImageCopy(), testImageCopyShort(), testImageFromSet(), testImageScan(), DGtal::testImplicitDigitalSurface(), testImplicitDigitalSurface(), testImplicitShape(), testImplicitShape3D(), testIndent(), testInexactMetrics(), testInGeneralizedDiskOfGivenRadius(), testInGreedySegmentation(), testInHalfPlane(), testInitFraction(), testInteger(), testIntegerComputer(), testIntersection(), testInverse(), testIOException(), testIsInside(), testIteratorCirculatorTraits(), testIteratorCirculatorTraitsAndAdapters(), testIterators(), testITKImage(), testITKImageWithMetadata(), testITKImageWithShiftDomain(), testITKio(), testITKMethod(), testKanungo2D(), testLatticePolytope2D(), testLayers(), testLighterSternBrocot(), testLightExplicitDigitalSurface(), DGtal::testLightImplicitDigitalSurface(), testLightImplicitDigitalSurface(), testLightSternBrocot(), testLinearAlgebra(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), testLocalEstimatorFromFunctorAdapter(), testLocalGraphModel(), testLongvol(), testM1Matrix(), testMeanCurvature3d(), testMesh(), testMeshGeneration(), testMeshReader(), testMeshWriter(), testMetricAdjacency(), testMetrics(), testMiddle(), testModuloComputer(), testMorton(), testMPolynomial(), testMPolynomialSpeed(), testMultiWidth(), testNormaliation(), testNumberReader(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testOneBalancedWordComputer(), testOpenMP(), testOrderingDigitalSurfaceFacesAroundVertex(), testOwningOrAliasingPtr(), testPairs(), testPatchCreatePattern(), testPattern(), testPNM3DASCIIReader(), testPNM3DReader(), testPNMReader(), testPNMWriter(), testPointListReader(), testPointsIterators(), testPolarPointComparatorBy2x2DetComputer(), testPowerMapFromSites(), testPowerMetrics(), testPrincipalCurvatures3d(), testProgressBar(), testProjection(), testProjector(), testPublicSercives(), testQuadNorm(), testRange(), testRationalAngle(), testRayIntersection(), testRayQuadIntersection(), testRaySurface(), testRaySurfelIntersection(), testRecognition(), testReducedFraction(), testReverseDT(), testReverseDTL1(), testRWIssue254(), testSCellsFunctors(), testSegmentation(), testSegmentation(), testSegmentationLarger(), testSelfCheckConcept(), testSeparableMetricAdapter(), testSetFromImage(), testSetTable(), testShapes(), testShrink(), testSignal(), testSimple(), testSimple2D(), testSimple3D(), testSimple4D(), testSimpleExpander(), testSimpleMatrix(), testSimplePoints2D(), testSimplePoints3D(), testSimpleRandom2D(), testSimpleRandom3D(), testSimpleRegression(), testSimpleRegression2(), testSimpleRegression3(), testSimpleRegressionOrdered(), testSimplestFractionInBetween(), testSize(), testSliceImageFromFunctor(), testSort(), testSpanIterators(), testSpecialCase(), testSpecialCasesL2(), testSpecialCasesLp(), testSphericalAccumulator(), testSphericalMore(), testSphericalMoreIntegerDir(), testStabbingCircleComputer(), testStabbingLineComputer(), testStandardDSS6ComputerConceptChecking(), testStaticServices(), testStatistics(), testStatisticsSaving(), testSternBrocot(), testSubsegment(), testSubsegment2(), testSubStandardDSLQ0(), testThicknessDefinitions(), testTickedColorMap(), testTiledImage2D_int64(), testTiledImage3D_double(), testTimings(), testTrueLocalEstimatorOnShapeDigitization(), testUmbrellaComputer(), testVisualTubularMesh(), testVolReader(), testVoronoiCovarianceMeasure(), testVoronoiMap(), testVoronoiMapFromSites(), testWithLengthConstraint(), testWithoutLengthConstraint(), testWithoutLengthConstraint2(), DGtal::functions::thinningVoxelComplex(), unionComparisonTest(), unionTest(), updateTest(), and writeHDF5_3D_TILED().
emphase()
std::ostream & DGtal::Trace::emphase ()
Create a string with an indentation prefix for an emphased trace.
Returns
the cerr output stream with the prefix
Examples
geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/volumes/distance/exampleFMM3D.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, and tutorial-examples/FMMErosion.cpp.
Referenced by estimatorOnShapeDigitization(), main(), main(), main(), TEST_CASE(), testCompareEstimator(), testDoubleShrink(), testFileStream(), testIterator(), testSimple(), testTrueLocalEstimatorOnShapeDigitization(), testUnitSquare(), testUnitSquareCentroid(), and unionComparisonTest().
endBlock()
double DGtal::Trace::endBlock ()
Leave a current block, decrease the indentation level and display the associate keyword
Returns
the ellapsed time in the block in milliseconds (Class Clock).
Examples
dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusChladni.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, doc-examples/kernelDomain.cpp, doc-examples/range.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleDSLSubsegment.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleFrechetShortcut.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/curves/greedyAlphaThickDecomposition.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/examplePreimage.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/distance/voronoimap2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount4D.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/volDistanceTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleImageFactoryFromHDF5.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, images/exampleTiledImage.cpp, images/imageBasicSubsampling.cpp, images/raw2HDF5.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/dgtalBoard3D-1-points.cpp, io/boards/exampleBezierCurve.cpp, io/boards/logoDGtal.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, shapes/exampleEuclideanShapesDecorator.cpp, shapes/exampleMeshVoxelizer.cpp, shapes/exampleSurfaceMesh.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-fillContours.cpp, topology/cubical-complex-collapse.cpp, topology/cubical-complex-illustrations.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/generateSimplicityTables3D.cpp, topology/homotopicThinning3D.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/2DSliceImageFromVol.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, tutorial-examples/FMMErosion.cpp, and tutorial-examples/polyhedralizer.cpp.
Referenced by accuracyTest(), basicBidirectionalTest(), basicForwardTest(), basicRandomAccessTest(), basicTest(), basicTest2(), basicUsage(), checkCut(), checkExtendWithManyPoints(), checkManyPlanes(), checkWidth(), CompareToArithmetical(), comparisonLeftHull(), comparisonSubsegment(), comparisonSubsegment2(), compatibleStepsTest(), computeLaplace(), constructorsTest(), createDSSTest(), DGtal::VoxelComplex< TKSpace, TCellContainer >::criticalCliques(), drawArithmeticalDSL(), estimatorOnShapeDigitization(), example(), exampleArithmeticalDSLTypes(), exampleConstructors(), exampleImage3D(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleTiledImageFromHDF5_10blocks3D(), exampleTiledImageFromHDF5_1block3D(), exampleTiledImageFromImage_10blocks3D(), exampleTiledImageFromImage_1block3D(), exampleUpdate(), exhaustiveTestLatticePolytope2D(), greedySegmentationVisualTest(), HDF5_3D2vol(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initOperators(), initQuantities(), initQuantitiesCached(), laplacian(), main(), main(), main(), main(), mainTest(), moduleImages_example(), precompute(), randomTest2x2DetComputer(), rangeTest(), raw2HDF5_3D(), runATest(), SaturatedSegmentationTest(), SaturatedSegmentationVisualTest(), saveToObj(), showGreedySegmantation(), simpleTest2x2DetComputer(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveForEpsilon(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveGammaConvergence(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveOneAlternateStep(), specialCases(), stoppingCriterionTest(), test(), test2D_int32(), test3d(), test3dSurfaceHelper(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), test_g_f_fm1(), test_linear_ring(), test_linear_structure(), test_manual_operators_2d(), test_manual_operators_3d(), test_range_constRange(), testAdvance(), testAliasCases(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testAngleLinearMinimizer(), testAPI(), testArithm(), testBadKeySizes(), testBallQuad(), testBasicBoolFunctors(), testBasicFunctors(), testBasicMasks(), testBasicMathFunctions(), testBIGINTEGER(), testBIGINTEGERSpace(), testBinarySearch(), testBinomialConvolver(), testBoard2D(), testChamferSimple(), testCheckImageConcept(), testChessboard(), testChordNaivePlaneComputer(), testCloneCases(), testCloneTimings(), testCOBANaivePlaneComputer(), testCodesIterators(), testColor(), testColRow(), testCombinatorialSurface(), testCompareEstimator(), testCompareExactBruteForce(), testCompareExactInexact(), testCompareInexactBruteForce(), testComparison(), testComputeInterior(), testConcepts(), testConsistence(), testConstAliasCases(), testConstructor(), testConstructors(), testContinuedFractions(), testContourHelper(), testConvexHull2D(), testCorner(), testCountedConstPtrOrConstPtrMemory(), testCountedPtr(), testCountedPtrCopy(), testCountedPtrMemory(), testCountedPtrOrPtrMemory(), testCreate(), testCube(), testCurvature2d(), testDetCofactor(), testDGtalBIGINTEGER(), testDigitalSetBoundary(), testDigitalSetDomain(), testDigitalSetDraw(), testDigitalSetSelector(), testDigitalShapesDecorator(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testDigitalTopologyZ2(), testDisplayDT2d(), testDisplayDT3d(), testDisplayDTFromCircle(), testDistancePropagation(), testDistanceTransformation(), testDistanceTransformation3D(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDistanceTransformND(), testDoubleOnSegment(), testDoubleShrink(), testDoubleShrinkHorizontal(), testDraw(), testDSLSubsegment(), testDSS4drawing(), testDSS8drawing(), testDSSreco(), testDTFromSet(), testDuvalPP(), testDuvalPPMod(), testEigenDecomposition(), testEmbedder(), testEstimatorCache(), testEuclideanShapesDecorator(), testExpander(), testExplicitDigitalSurface(), testExtendRetractFront(), testFileStream(), testFitting(), testFLF(), testFrechetShortcut(), testGaussDigitizer(), testGaussianCurvature3d(), testGenericReader(), testGenericWriter(), testGetSetVal(), testGrayscaleColorMap(), testHashTree(), testHashTree2D(), testHDF5_3DReader(), testHDF5Reader(), testHiddenBy(), testHullFunctions2D(), testImage(), testImageAdapter(), testImageCopy(), testImageFromSet(), DGtal::testImplicitDigitalSurface(), testImplicitDigitalSurface(), testIndent(), testInexactMetrics(), testInGeneralizedDiskOfGivenRadius(), testInGreedySegmentation(), testInHalfPlane(), testInitFraction(), testInteger(), testIntegerComputer(), testInverse(), testIOException(), testIsInside(), testIteratorCirculatorTraits(), testIteratorCirculatorTraitsAndAdapters(), testIterators(), testITKImage(), testITKImageWithMetadata(), testITKio(), testITKMethod(), testKanungo2D(), testLatticePolytope2D(), testLighterSternBrocot(), testLightExplicitDigitalSurface(), DGtal::testLightImplicitDigitalSurface(), testLightImplicitDigitalSurface(), testLightSternBrocot(), testLinearAlgebra(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), testLocalEstimatorFromFunctorAdapter(), testLocalGraphModel(), testLongvol(), testM1Matrix(), testMeanCurvature3d(), testMesh(), testMeshGeneration(), testMeshReader(), testMeshWriter(), testMetricAdjacency(), testMetrics(), testMiddle(), testModuloComputer(), testMorton(), testMPolynomial(), testMPolynomialSpeed(), testMultiWidth(), testNormaliation(), testNumberReader(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testOneBalancedWordComputer(), testOpenMP(), testOrderingDigitalSurfaceFacesAroundVertex(), testOwningOrAliasingPtr(), testPairs(), testPatchCreatePattern(), testPattern(), testPNM3DASCIIReader(), testPNM3DReader(), testPNMReader(), testPNMWriter(), testPointListReader(), testPointsIterators(), testPolarPointComparatorBy2x2DetComputer(), testPowerMapFromSites(), testPowerMetrics(), testPrincipalCurvatures3d(), testProgressBar(), testProjection(), testProjector(), testPublicSercives(), testQuadNorm(), testRange(), testRationalAngle(), testRayIntersection(), testRayQuadIntersection(), testRaySurface(), testRaySurfelIntersection(), testRecognition(), testReducedFraction(), testReverseDT(), testReverseDTL1(), testRWIssue254(), testSCellsFunctors(), testSegmentation(), testSegmentation(), testSegmentationLarger(), testSelfCheckConcept(), testSeparableMetricAdapter(), testSetTable(), testShapes(), testShrink(), testSignal(), testSimple(), testSimple2D(), testSimple3D(), testSimple4D(), testSimpleExpander(), testSimpleMatrix(), testSimplePoints2D(), testSimplePoints3D(), testSimpleRandom2D(), testSimpleRandom3D(), testSimpleRegression(), testSimpleRegression2(), testSimpleRegression3(), testSimpleRegressionOrdered(), testSimplestFractionInBetween(), testSize(), testSliceImageFromFunctor(), testSort(), testSpanIterators(), testSpecialCasesL2(), testSpecialCasesLp(), testSphericalAccumulator(), testSphericalMore(), testSphericalMoreIntegerDir(), testStabbingCircleComputer(), testStabbingLineComputer(), testStandardDSS6ComputerConceptChecking(), testStaticServices(), testStatistics(), testStatisticsSaving(), testSternBrocot(), testSubsegment(), testSubsegment2(), testSubStandardDSLQ0(), testThicknessDefinitions(), testTickedColorMap(), testTiledImage2D_int64(), testTiledImage3D_double(), testTimings(), testTrueLocalEstimatorOnShapeDigitization(), testUmbrellaComputer(), testVisualTubularMesh(), testVolReader(), testVoronoiCovarianceMeasure(), testVoronoiMap(), testVoronoiMapFromSites(), testWithLengthConstraint(), testWithoutLengthConstraint(), testWithoutLengthConstraint2(), DGtal::functions::thinningVoxelComplex(), unionComparisonTest(), unionTest(), updateTest(), and writeHDF5_3D_TILED().
error()
std::ostream & DGtal::Trace::error ()
Create a string with an indentation prefix for an error trace. the string is postfixed by the keyword "[ERR]"
Returns
the cerr output stream with the prefix
Examples
examples/tutorial-examples/polyhedralizer.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-XY-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-XY-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-XY-3d.cpp, geometry/tools/checkLatticeBallQuickHull.cpp, geometry/tools/exampleLatticeBallDelaunay3D.cpp, geometry/tools/exampleRationalBallDelaunay3D.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/volDistanceTraversal.cpp, images/exampleImageFactoryFromHDF5.cpp, images/raw2HDF5.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/ctopo-2-3d.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/2DSliceImageFromVol.cpp, and tutorial-examples/polyhedralizer.cpp.
Referenced by DGtal::LatticeSetByIntervals< TSpace >::add(), DGtal::detail::BoundedLatticePolytopeSpecializer< N, TInteger >::addEdgeConstraint(), DGtal::detail::BoundedRationalPolytopeSpecializer< N, TInteger >::addEdgeConstraint(), DGtal::assert_failed(), DGtal::assert_failed_message(), DGtal::QuickHull< TKernel >::checkFacet(), DGtal::QuickHull< TKernel >::checkHull(), checkPowerMap(), checkVoronoi(), checkVoronoi(), DGtal::QuickHull< TKernel >::cleanFacets(), DGtal::ConvexCellComplex< TPoint >::computeFaceGeometry(), DGtal::QuickHull< TKernel >::computeSimplexConfiguration(), DGtal::detail::BoundedLatticePolytopeSpecializer< N, TInteger >::crossProduct(), DGtal::detail::BoundedRationalPolytopeSpecializer< N, TInteger >::crossProduct(), DGtal::LatticeSetByIntervals< TSpace >::equals(), DGtal::fatal_error_failed(), DGtal::fatal_error_failed_message(), DGtal::ImageFactoryFromHDF5< TImageContainer >::flushImage(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::GenericReader< TContainer, Tdim, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, Tdim, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 3, TValue >::importWithValueFunctor(), DGtal::LatticeSetByIntervals< TSpace >::includes(), laplacian(), main(), main(), DGtal::Shortcuts< TKSpace >::makeImplicitShape3D(), DGtal::Shortcuts< TKSpace >::makeLightDigitalSurface(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()(), DGtal::ShroudsRegularization< TDigitalSurfaceContainer >::precomputeTopology(), DGtal::QuickHull< TKernel >::processFacet(), raw2HDF5_3D(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::removeIndex(), DGtal::QuickHull< TKernel >::renumberInfiniteFacets(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::replaceIndex(), DGtal::ImageFactoryFromHDF5< TImageContainer >::requestImage(), SCENARIO(), DGtal::QuickHull< TKernel >::setInitialSimplex(), DGtal::LatticeSetByIntervals< TSpace >::subtract(), test_image(), testCurvature2d(), testDigitalSurfaceBoostGraphInterface(), testDistanceTransformND(), testDTFromSet(), testEstimatorCache(), testFileStream(), testGaussianCurvature3d(), testGetSetVal(), testIndent(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), testMeanCurvature3d(), testPrincipalCurvatures3d(), testRaySurface(), testSimple(), writeHDF5_2D(), writeHDF5_2D_TILED(), writeHDF5_3D_TILED(), and writeHDF5_3D_TILED_for_easy_reading().
info()
std::ostream & DGtal::Trace::info ()
Create a string with an indentation prefix for a normal trace.
Returns
the cerr output stream with the prefix
Examples
dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusChladni.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, doc-examples/kernelDomain.cpp, doc-examples/range.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/estimation/exampleLMST3DBy2D.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleFrechetShortcut.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/curves/exampleGridCurve3d.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-XY-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-XY-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-XY-3d.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/examplePreimage.cpp, geometry/tools/exampleQuickHull3D.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount4D.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/graphTraversal.cpp, graph/volDistanceTraversal.cpp, images/exampleImageFactoryFromHDF5.cpp, images/exampleTiledImage.cpp, images/imageBasicSubsampling.cpp, images/raw2HDF5.cpp, io/boards/dgtalBoard3D-1-points.cpp, io/boards/exampleBezierCurve.cpp, io/meshFromOFF.cpp, io/viewers/viewer3D-10-interaction.cpp, io/viewers/viewer3D-11-extension.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, shapes/exampleEuclideanShapesDecorator.cpp, shapes/exampleMeshVoxelizer.cpp, shapes/exampleSurfaceMesh.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-2-3d.cpp, topology/cubical-complex-collapse.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/khalimskySpaceScanner.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, tutorial-examples/FMMErosion.cpp, tutorial-examples/polyhedralizer.cpp, and tutorial-examples/volDTGranulo.cpp.
Referenced by accuracyTest(), alphaShape(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::ATSolver2D(), basicBidirectionalTest(), basicForwardTest(), basicRandomAccessTest(), basicTest(), basicTest2(), checkChordGenericStandardPlaneComputer(), checkCOBAGenericStandardPlaneComputer(), checkCut(), checkCvxHPlusHypercubeFullConvexity(), checkExtendWithManyPoints(), DGtal::QuickHull< TKernel >::checkHull(), checkImage(), checkManyPlanes(), checkSkelStarCvxHFullConvexity(), checkSubStandardDSLQ0(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::checkV0(), checkWidth(), DGtal::TimeStampMemoizer< TKey, TValue >::cleanUp(), comparisonLeftHull(), comparisonSubsegment2(), compatibleStepsTest(), DGtal::QuickHull< TKernel >::computeFacets(), DGtal::QuickHull< TKernel >::computeSimplexConfiguration(), DGtal::QuickHull< TKernel >::computeVertices(), constructorsTest(), convexHull(), DGtal::VoxelComplex< TKSpace, TCellContainer >::criticalCliques(), DGtal::Clone< T >::display(), display_operator_info(), displayAll(), displayRange(), DGtal::functors::SphereFittingEstimator< TSurfel, TEmbedder, TNormalVectorEstimatorCache >::eval(), example(), exampleArithmeticalDSLTypes(), exampleConstructors(), exampleImage3D(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleTiledImageFromHDF5_10blocks3D(), exampleTiledImageFromHDF5_1block3D(), exampleTiledImageFromImage_10blocks3D(), exampleTiledImageFromImage_1block3D(), exampleUpdate(), exhaustiveTestLatticePolytope2D(), extensionTest(), DGtal::ShortcutsGeometry< TKSpace >::getCTrivialNormalVectors(), DGtal::ShortcutsGeometry< TKSpace >::getIIGaussianCurvatures(), DGtal::ShortcutsGeometry< TKSpace >::getIIMeanCurvatures(), DGtal::ShortcutsGeometry< TKSpace >::getIINormalVectors(), DGtal::ShortcutsGeometry< TKSpace >::getIIPrincipalCurvaturesAndDirections(), DGtal::ShortcutsGeometry< TKSpace >::getVCMNormalVectors(), greedySegmentationVisualTest(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputScalarFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initInputVectorFieldU2(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::initOperators(), DGtal::UnorderedSetByBlock< Key, TSplitter, Hash, KeyEqual, UnorderedMapAllocator >::internal_trace_includes_by_iterator(), DGtal::UnorderedSetByBlock< Key, TSplitter, Hash, KeyEqual, UnorderedMapAllocator >::internal_trace_includes_by_map_iterator(), laplacian(), main(), main(), main(), main(), mainTest(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()(), DGtal::QuickHull< TKernel >::pickInitialSimplex(), precompute(), DGtal::QuickHull< TKernel >::processFacet(), DGtal::functors::SphereFittingEstimator< TSurfel, TEmbedder, TNormalVectorEstimatorCache >::pushSurfel(), randomTest2x2DetComputer(), rangeTest(), raw2HDF5_3D(), DGtal::ShroudsRegularization< TDigitalSurfaceContainer >::regularize(), retractionTest(), runATest(), SaturatedSegmentationTest(), SaturatedSegmentationVisualTest(), saveToObj(), SCENARIO(), SCENARIO(), SCENARIO(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::setUp(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::setUp(), simpleTest2x2DetComputer(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveForEpsilon(), DGtal::ATSolver2D< TKSpace, TLinearAlgebra >::solveOneAlternateStep(), specialCases(), stoppingCriterionTest(), DerivativeTester< Calculus, order >::test(), HodgeTester< Calculus, order >::test(), test(), test(), test2D_int32(), test3d(), test3dSurfaceHelper(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), test_g_f_fm1(), test_get(), test_image(), test_linear_ring(), test_linear_structure(), test_loopTick(), test_manual_operators_2d(), test_manual_operators_3d(), test_minimalTick(), test_MultipleLoop(), test_range_constRange(), test_RestartClock(), test_setVal(), testAdvance(), testAliasCases(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testAngleLinearMinimizer(), testAPI(), testArithm(), testBadKeySizes(), testBallQuad(), testBasicBoolFunctors(), testBasicFunctors(), testBasicMasks(), testBasicMathFunctions(), testBIGINTEGER(), testBIGINTEGERSpace(), testBinarySearch(), testBinomialConvolver(), testBoard2D(), testBoard3D(), testCeilFloorDiv(), testCFrac(), testChamferSimple(), testChessboard(), testChordNaivePlaneComputer(), testCloneCases(), testCloneTimings(), testCMAP(), testCOBANaivePlaneComputer(), testCodesIterators(), testCoefficientIntersection(), testColor(), testColRow(), testCombinatorialSurface(), testCompareEstimator(), testCompareExactBruteForce(), testCompareExactInexact(), testCompareInexactBruteForce(), testComparison(), testComputeInterior(), testConsistence(), testConstAliasCases(), testConstructor(), testConstructors(), testContinuedFraction(), testContinuedFractions(), testContourHelper(), testConvexHull2D(), testConvexHullCompThickness(), testCountedConstPtrOrConstPtrMemory(), testCountedPtr(), testCountedPtrCopy(), testCountedPtrMemory(), testCountedPtrOrPtrMemory(), testCreate(), testCube(), testDetCofactor(), testDGtalBIGINTEGER(), testDicomReader(), testDicomReaderFromDirectory(), testDigitalSet(), testDigitalSetBoundary(), testDigitalSetDomain(), testDigitalSetSelector(), testDigitalShapesDecorator(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testDigitalTopologyZ2(), testDisplayDT2d(), testDisplayDT3d(), testDisplayDTFromCircle(), testDistancePropagation(), testDistanceTransformation(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDistanceTransformND(), testDoubleOnSegment(), testDoubleShrink(), testDoubleShrinkHorizontal(), testDSLSubsegment(), testDSS4drawing(), testDSS8drawing(), testDSSreco(), testDuvalPP(), testDuvalPPMod(), testEigenDecomposition(), testEmbedder(), testEstimatorCache(), testEuclideanShapesDecorator(), testEval(), testExpander(), testExplicitDigitalSurface(), testExtendedEuclid(), testExtendRetractFront(), testFileStream(), testFindABel(), testFitting(), testFLF(), testFP(), testFrechetShortcut(), testGaussDigitizer(), testGCD(), testGenericReader(), testGenericWriter(), testGetSetVal(), testGrayscaleColorMap(), testHashTree(), testHashTree2D(), testHDF5_3DReader(), testHDF5Reader(), testHiddenBy(), testHullFunctions2D(), testImage(), testImageAdapter(), testImageCopy(), testImageCopyShort(), testImageFromSet(), DGtal::testImplicitDigitalSurface(), testImplicitDigitalSurface(), testIndent(), testInexactMetrics(), testInGeneralizedDiskOfGivenRadius(), testInHalfPlane(), testInitFraction(), testInteger(), testIntegerComputer(), testIntersection(), testInverse(), testIOException(), testIsInside(), testIterator(), testIteratorCirculatorTraits(), testIteratorCirculatorTraitsAndAdapters(), testIterators(), testITKImage(), testITKImageWithMetadata(), testITKImageWithShiftDomain(), testITKio(), testITKMethod(), testITKSpacingIO(), testKanungo2D(), testL1LengthEstimator(), testLatticePolytope2D(), testLighterSternBrocot(), testLightExplicitDigitalSurface(), DGtal::testLightImplicitDigitalSurface(), testLightImplicitDigitalSurface(), testLightSternBrocot(), testLinearAlgebra(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), testLocalEstimatorFromFunctorAdapter(), testLocalGraphModel(), testLongvol(), testM1Matrix(), testMesh(), testMeshGeneration(), testMeshReader(), testMeshWriter(), testMetricAdjacency(), testMetrics(), testMiddle(), testModuloComputer(), testMorton(), testMPolynomial(), testMPolynomialReader(), testMPolynomialReader2(), testMPolynomialSpeed(), testMultiWidth(), testNumberReader(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testOffset(), testOpenMP(), testOrderedAlphabet(), testOrderingDigitalSurfaceFacesAroundVertex(), testOwningOrAliasingPtr(), testPairs(), testPattern(), testPNM3DASCIIReader(), testPNM3DReader(), testPNMReader(), testPointListReader(), testPointsIterators(), testPolarPointComparatorBy2x2DetComputer(), testPowerMetrics(), testProgressBar(), testProjection(), testProjector(), testPublicSercives(), testQuadNorm(), testRange(), testRationalAngle(), testRayIntersection(), testRayQuadIntersection(), testRaySurface(), testRaySurfelIntersection(), testRecognition(), testReducedFraction(), testReverseDT(), testReverseDTL1(), testRWIssue254(), testSCellsFunctors(), testSegmentation(), testSegmentation(), testSegmentationLarger(), testSelfCheckConcept(), testSeparableMetricAdapter(), testSetFromImage(), testShrink(), testSignal(), testSimple(), testSimpleMatrix(), testSimplePoints3D(), testSimpleRegression(), testSimpleRegression2(), testSimpleRegression3(), testSimpleRegressionOrdered(), testSimplestFractionInBetween(), testSize(), testSliceImageFromFunctor(), testSort(), testSpanIterators(), testSpecialCase(), testSpecialCasesL2(), testSpecialCasesLp(), testSphericalAccumulator(), testSphericalMore(), testSphericalMoreIntegerDir(), testStabbingCircleComputer(), testStabbingLineComputer(), testStandardDSLQ0(), testStaticServices(), testStatistics(), testStatisticsSaving(), testSternBrocot(), testSubStandardDSLQ0(), testThicknessDefinitions(), testTickedColorMap(), testTiledImage2D_int64(), testTiledImage3D_double(), testTimings(), testTrueLocalEstimator(), testUmbrellaComputer(), testUnitSquare(), testUnitSquareCentroid(), testVal(), testValidBezout(), testVisualTubularMesh(), testVolReader(), testVoronoiCovarianceMeasure(), testVoronoiMap(), DGtal::functions::thinningVoxelComplex(), unionComparisonTest(), unionTest(), updateTest(), DGtal::WindingNumbersShape< TSpace >::WindingNumbersShape(), and writeHDF5_3D_TILED().
isValid()
bool DGtal::Trace::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
Trace & DGtal::Trace::operator= (const Trace & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
progressBar()
void DGtal::Trace::progressBar (const double currentValue, const double maximalValue)
Display a progress bar in the terminal.
Parameters
currentValue current step of the progress bar
maximalValue expected maximal value (must be >0)
Examples
dec/examplePropagation.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, and tutorial-examples/polyhedralizer.cpp.
Referenced by DGtal::functions::generateSimplicityTable(), DGtal::functions::generateVoxelComplexTable(), main(), and testProgressBar().
reset()
void DGtal::Trace::reset ()
Reset all the variables of the Trace object (indentation level and keyword stack)
selfDisplay()
void DGtal::Trace::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
warning()
std::ostream & DGtal::Trace::warning ()
Create a string with an indentation prefix for a warning trace. the string is postfixed by the keyword "[WRNG]"
Returns
the cerr output stream with the prefix
Examples
geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, and topology/homotopicThinning3D.cpp.
Referenced by DGtal::IntegerConverter< dim, DGtal::int32_t >::cast(), DGtal::IntegerConverter< dim, DGtal::int32_t >::cast(), DGtal::IntegerConverter< dim, DGtal::int64_t >::cast(), DGtal::QuickHull< TKernel >::check(), checkCvxHPlusHypercubeFullConvexity(), checkExtendWithManyPoints(), checkFullConvexityCharacterization(), checkProjectionFullConvexity(), checkSkelStarCvxHFullConvexity(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::computeVertexNormal(), DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::ConstImageAdapter(), DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::ConstImageAdapter(), DGtal::ShortcutsGeometry< TKSpace >::getVCMNormalVectors(), DGtal::ShortcutsGeometry< TKSpace >::getVectorsAngleDeviation(), DGtal::Image< TImageContainer >::Image(), DGtal::Image< TImageContainer >::Image(), DGtal::Image< TImageContainer >::Image(), DGtal::Image< TImageContainer >::Image(), DGtal::Image< TImageContainer >::Image(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::ImageAdapter(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::ImageAdapter(), DGtal::HalfEdgeDataStructure::isValid(), DGtal::HalfEdgeDataStructure::isValidTriangulation(), main(), main(), DGtal::Shortcuts< TKSpace >::makeIdxDigitalSurface(), DGtal::Shortcuts< TKSpace >::makeIdxDigitalSurface(), DGtal::Shortcuts< TKSpace >::makeLightDigitalSurface(), DGtal::HalfEdgeDataStructure::merge(), DGtal::CorrectedNormalCurrentFormula< TRealPoint, TRealVector >::mu2ConstantUAtVertex(), DGtal::functors::Point2DEmbedderIn3D< TDomain3D, TInteger >::operator()(), DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::operator=(), DGtal::Image< TImageContainer >::operator=(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::operator=(), test_g_f_fm1(), test_image(), testAPI(), testChessboard(), testCompareExactInexact(), testCreate(), testCurvature2d(), testDistanceTransformation(), testDistanceTransformation3D(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDoubleOnSegment(), testFileStream(), testGaussianCurvature3d(), testGetSetVal(), testIndent(), testInteger(), testIteratorHelperImpl(), testITKImage(), testITKMethod(), testMeanCurvature3d(), testMorton(), testPrincipalCurvatures3d(), testReverseDT(), testReverseDTL1(), testShrink(), testSimple(), and DGtal::WindingNumbersShape< TSpace >::WindingNumbersShape().
Field Documentation
myClockStack
std::stack<Clock*> DGtal::Trace::myClockStack private
A stack to store the block clocks.
Definition at line 189 of file Trace.h.
myCurrentLevel
unsigned int DGtal::Trace::myCurrentLevel private
The indentation level.
Definition at line 178 of file Trace.h.
myCurrentPrefix
std::string DGtal::Trace::myCurrentPrefix private
The indentation prefix string.
Definition at line 180 of file Trace.h.
myKeywordStack
std::stack<std::string> DGtal::Trace::myKeywordStack private
A stack to store the block keywords.
Definition at line 183 of file Trace.h.
myProgressBarCurrent
int DGtal::Trace::myProgressBarCurrent private
Progress bar current position.
Definition at line 192 of file Trace.h.
myProgressBarRotation
unsigned int DGtal::Trace::myProgressBarRotation private
Progress bar rotation position.
Definition at line 195 of file Trace.h.
myStyle
bool DGtal::Trace::myStyle private
True if the style has changed.
Definition at line 198 of file Trace.h.
myWriter
TraceWriter& DGtal::Trace::myWriter private
A reference to the output writer.
Definition at line 186 of file Trace.h.
The documentation for this class was generated from the following file:
Trace.h