DGtal: DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K > Class Template Reference
DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K > Class Template Reference
Aim: A class that models a \((2k+1)^d \) neighborhood and that provides services to analyse the convexity properties of a digital set within this neighborhood.
#include <DGtal/geometry/volumes/NeighborhoodConvexityAnalyzer.h>
Public Types
typedef NeighborhoodConvexityAnalyzer< TKSpace, K > Self
typedef TKSpace KSpace
typedef KSpace::Space Space
typedef KSpace::Integer Integer
typedef KSpace::Point Point
typedef KSpace::Vector Vector
typedef KSpace::Cell Cell
typedef std::vector< Point > PointRange
typedef HyperRectDomain< Space > Domain
typedef std::size_t Size
typedef std::bitset< functions::const_pow(2 *K+1, dimension) > Configuration
typedef std::bitset< 9 > BasicConfiguration
Static Public Attributes
static const Dimension dimension = KSpace::dimension
static const Size neigh_size = functions::const_pow(2*K+1, dimension)
static const Size middle = functions::const_middle(K, dimension)
static const bool false_positive = (dimension > 2) || (K > 1)
Protected Types
enum Computation {
FullConvexity_X_with_center = 0x1 , FullConvexity_X_without_center = 0x2 , FullConvexity_CompX_with_center = 0x4 , FullConvexity_CompX_without_center = 0x8 ,
Convexity_X_with_center = 0x10 , Convexity_X_without_center = 0x20 , Convexity_CompX_with_center = 0x40 , Convexity_CompX_without_center = 0x80
}
Enum types indicating the possible type of local computations.
Protected Attributes
Domain myDomain
The bounded domain in which computations are carried out.
DigitalConvexity< KSpace > myDigConv
The digital convexity that is used for checking full convexity.
Point myCenter
The current center of the neighborhood.
TimeStampMemoizer< Configuration, bool > myMemoizer
The memoizer.
bool myCenterInX
tells if the center belongs to X
Size myNbInX
The number of points of the neighborhood that belongs to X (center omitted).
Configuration myCfgX
Stores the local configuration for X (without the center)
std::vector< BasicConfiguration > myBasicCfgX
Stores the basic local configurations associated to myCfgX, for speed-up.
std::bitset< 512 > myBasicFullConvexityTable
Stores the full convexity property of the basic 3x3 neighborhood configurations.
std::bitset< 512 > myBasic0ConvexityTable
Stores the 0-convexity property of the basic 3x3 neighborhood configurations.
int myComputations
Stores which properties have already been computed.
int myResults
Stores the properties boolean values.
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >))
void computeBasicFullConvexityTable ()
bool checkBasicConfigurationsFullConvexity (bool compX, bool with_center) const
bool checkBasicConfigurations0Convexity (bool compX, bool with_center) const
void computeBasicConfigurations (Configuration cfg, std::vector< BasicConfiguration > &result) const
BasicConfiguration computeCentralBasicConfiguration (Configuration cfg, Dimension i, Dimension j) const
Standard services (construction, initialization, assignment)
~NeighborhoodConvexityAnalyzer ()=default
NeighborhoodConvexityAnalyzer ()=default
NeighborhoodConvexityAnalyzer (const Self &other)=default
NeighborhoodConvexityAnalyzer (Clone< KSpace > aKSpace, Size memoizer_size=0)
NeighborhoodConvexityAnalyzer (Point lo, Point hi, Size memoizer_size=0)
Self & operator= (const Self &other)=default
const KSpace & space () const
const Domain & domain () const
static int radius ()
static Size size ()
Neighborhood and convexity services
template<typename PointPredicate >
void setCenter (Point c, const PointPredicate &X)
Point center () const
Configuration configuration () const
bool isCenterInX () const
Tells if the current center belongs to the shape X.
bool isFullyConvexCollapsible ()
bool isLikelyNoise ()
bool is0ConvexCollapsible ()
bool isFullyConvex (bool with_center)
bool isComplementaryFullyConvex (bool with_center)
bool is0Convex (bool with_center)
bool isComplementary0Convex (bool with_center)
void getLocalX (std::vector< Point > &localX, bool with_center) const
void getLocalCompX (std::vector< Point > &localCompX, bool with_center) const
static Configuration makeConfiguration (Configuration current, bool complement, bool with_center)
Detailed Description
template<typename TKSpace, int K>
class DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >
Aim: A class that models a \((2k+1)^d \) neighborhood and that provides services to analyse the convexity properties of a digital set within this neighborhood.
Description of template class 'NeighborhoodConvexityAnalyzer'
It is a model of boost::CopyConstructible, boost::DefaultConstructible, boost::Assignable.
Template Parameters
TKSpace an arbitrary model of CCellularGridSpaceND.
K the parameter that determines the size of the neighborhood along all dimensions (spans 2K+1 points in each direction, hence the neighborhood cardinal is \((2K+1)^d \)).
Note
This quite a heavy class since it tries to optimize computations in several ways:
it builds look-up tables for 0-convexity and full convexity for the 2D 3x3 neighborhood case, and uses them afterwards.
it memorizes convexity computations (w/o center, w/o complement) while you stay at the same center point;
it checks full convexity on small 3x3 2D slices before checking global nD full convexity.
it memoizes the full convexity result, so frequent configurations are not recomputed.
you can switch on/off the memoizer at object construction (e.g. it is useless in 2D).
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, and geometry/volumes/fullConvexityThinning3D.cpp.
Definition at line 94 of file NeighborhoodConvexityAnalyzer.h.
Member Typedef Documentation
BasicConfiguration
template<typename TKSpace , int K> typedef std::bitset< 9 > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::BasicConfiguration
Definition at line 116 of file NeighborhoodConvexityAnalyzer.h.
Cell
template<typename TKSpace , int K> typedef KSpace::Cell DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Cell
Definition at line 105 of file NeighborhoodConvexityAnalyzer.h.
Configuration
template<typename TKSpace , int K> typedef std::bitset< functions::const_pow(2*K+1, dimension) > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Configuration
Definition at line 115 of file NeighborhoodConvexityAnalyzer.h.
Domain
template<typename TKSpace , int K> typedef HyperRectDomain<Space> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Domain
Definition at line 107 of file NeighborhoodConvexityAnalyzer.h.
Integer
template<typename TKSpace , int K> typedef KSpace::Integer DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Integer
Definition at line 102 of file NeighborhoodConvexityAnalyzer.h.
KSpace
template<typename TKSpace , int K> typedef TKSpace DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::KSpace
Definition at line 100 of file NeighborhoodConvexityAnalyzer.h.
Point
template<typename TKSpace , int K> typedef KSpace::Point DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Point
Definition at line 103 of file NeighborhoodConvexityAnalyzer.h.
PointRange
template<typename TKSpace , int K> typedef std::vector<Point> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::PointRange
Definition at line 106 of file NeighborhoodConvexityAnalyzer.h.
Self
template<typename TKSpace , int K> typedef NeighborhoodConvexityAnalyzer<TKSpace,K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Self
Definition at line 99 of file NeighborhoodConvexityAnalyzer.h.
Size
template<typename TKSpace , int K> typedef std::size_t DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Size
Definition at line 108 of file NeighborhoodConvexityAnalyzer.h.
Space
template<typename TKSpace , int K> typedef KSpace::Space DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Space
Definition at line 101 of file NeighborhoodConvexityAnalyzer.h.
Vector
template<typename TKSpace , int K> typedef KSpace::Vector DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::Vector
Definition at line 104 of file NeighborhoodConvexityAnalyzer.h.
Member Enumeration Documentation
Computation
template<typename TKSpace , int K> enum DGtal::NeighborhoodConvexityAnalyzer::Computation protected
Enum types indicating the possible type of local computations.
Enumerator
FullConvexity_X_with_center
FullConvexity_X_without_center
FullConvexity_CompX_with_center
FullConvexity_CompX_without_center
Convexity_X_with_center
Convexity_X_without_center
Convexity_CompX_with_center
Convexity_CompX_without_center
Definition at line 528 of file NeighborhoodConvexityAnalyzer.h.
                     {
      FullConvexity_X_with_center        = 0x1,
      FullConvexity_X_without_center     = 0x2,
      FullConvexity_CompX_with_center    = 0x4,
      FullConvexity_CompX_without_center = 0x8,
      Convexity_X_with_center            = 0x10,
      Convexity_X_without_center         = 0x20,
      Convexity_CompX_with_center        = 0x40,
      Convexity_CompX_without_center     = 0x80,
    };
Constructor & Destructor Documentation
~NeighborhoodConvexityAnalyzer()
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::~NeighborhoodConvexityAnalyzer () default
Destructor.
NeighborhoodConvexityAnalyzer() [1/4]
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer () default
Constructor. Invalid object.
NeighborhoodConvexityAnalyzer() [2/4]
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer (const Self & other) default
Copy constructor.
Parameters
other the object to clone.
NeighborhoodConvexityAnalyzer() [3/4]
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer (Clone< KSpace > aKSpace, Size memoizer_size = 0) inline
Constructor from cellular space.
Parameters
aKSpace any cellular grid space.
memoizer_size if 0, no memoizer is used (useless in 2D), otherwise it is the maximal number of memoized elements.
Definition at line 147 of file NeighborhoodConvexityAnalyzer.h.
      : myDigConv( aKSpace ), myMemoizer( memoizer_size )
    {
      myDomain       = Domain( myDigConv.space().lowerBound(),
                               myDigConv.space().upperBound() );
      myComputations = 0;
      myResults      = 0;
      computeBasicFullConvexityTable();
      trace.info() << "Size=" << size() << " middle=" << middle << std::endl;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::computeBasicFullConvexityTable(), DGtal::Trace::info(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::middle, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDomain, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size(), DGtal::DigitalConvexity< TKSpace >::space(), and DGtal::trace.
NeighborhoodConvexityAnalyzer() [4/4]
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer (Point lo, Point hi, Size memoizer_size = 0) inline
Constructor from lower and upper points.
Parameters
lo the lowest point of the domain (bounding box for computations).
hi the highest point of the domain (bounding box for computations).
memoizer_size if 0, no memoizer is used (useless in 2D), otherwise it is the maximal number of memoized elements.
Definition at line 166 of file NeighborhoodConvexityAnalyzer.h.
      : myDomain( lo, hi ), myDigConv( lo, hi ), myMemoizer( memoizer_size )
    {
      myComputations = 0;
      myResults      = 0;
      computeBasicFullConvexityTable();
      trace.info() << "Size=" << size() << " middle=" << middle << std::endl;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::computeBasicFullConvexityTable(), DGtal::Trace::info(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::middle, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size(), and DGtal::trace.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TKSpace , int K> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >)) private
center()
template<typename TKSpace , int K> Point DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::center () const inline
Returns
the current center.
Definition at line 225 of file NeighborhoodConvexityAnalyzer.h.
    {
      return myCenter;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCenter.
checkBasicConfigurations0Convexity()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurations0Convexity (bool compX, bool with_center) const private
For the current configuration, checks if all the 2D slices of the configuration are 0-convex (for speed-up). They must be all true for the global nD configuration to be 0-convex.
Parameters
compX when 'true', complements the configuration.
with_center when 'true', makes the center point part of the configuration
Returns
'true' if they are all 0-convex.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex().
checkBasicConfigurationsFullConvexity()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurationsFullConvexity (bool compX, bool with_center) const private
For the current configuration, checks if all the 2D slices of the configuration are fully convex (for speed-up). They must be all true for the global nD configuration to be fully convex.
Parameters
compX when 'true', complements the configuration.
with_center when 'true', makes the center point part of the configuration
Returns
'true' if they are all fully convex.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex().
computeBasicConfigurations()
template<typename TKSpace , int K> void DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::computeBasicConfigurations (Configuration cfg, std::vector< BasicConfiguration > & result) const private
Given a configuration cfg, outputs all the 2D slice configurations in result.
Parameters
[in] cfg any configuration in nD
[out] result the vector of all basic configurations (i.e. 3x3) within each possible 2D local slice.
computeBasicFullConvexityTable()
template<typename TKSpace , int K> void DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::computeBasicFullConvexityTable () private
Precomputes the table storing for each basic configuration if it is fully convex.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
computeCentralBasicConfiguration()
template<typename TKSpace , int K> BasicConfiguration DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::computeCentralBasicConfiguration (Configuration cfg, Dimension i, Dimension j) const private
Given a configuration cfg, returns the central 3x3 configuration of the 2D slice along coordinates i and j.
Parameters
[in] cfg any configuration in nD
[in] i any dimension
[in] j any other dimension
Returns
the central 3x3 configuration of the 2D slice along coordinates i and j.
configuration()
template<typename TKSpace , int K> Configuration DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::configuration () const inline
Returns
the current configuration.
Definition at line 231 of file NeighborhoodConvexityAnalyzer.h.
    {
      return myCfgX;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCfgX.
domain()
template<typename TKSpace , int K> const Domain & DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::domain () const inline
Returns
a const reference to the domain used by this object.
Definition at line 190 of file NeighborhoodConvexityAnalyzer.h.
    {
      return myDomain;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDomain.
getLocalCompX()
template<typename TKSpace , int K> void DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalCompX (std::vector< Point > & localCompX, bool with_center) const
Parameters
[in,out] localCompX as output, the set of points of the neighborhood not belonging to the shape
[in] with_center if 'true' adds the center point.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex().
getLocalX()
template<typename TKSpace , int K> void DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalX (std::vector< Point > & localX, bool with_center) const
Parameters
[in,out] localX as output, the set of points of the neighborhood belonging to the shape
[in] with_center if 'true' adds the center point.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), and main().
is0Convex()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex (bool with_center) inline
Tells if the shape is locally digitally 0-convex.
Parameters
with_center if 'true' add the center to the digital set.
Returns
'true' iff the local neighborhood of X (with/without the center) is 0 convex
Definition at line 424 of file NeighborhoodConvexityAnalyzer.h.
    {
      int mask = with_center
        ? FullConvexity_X_with_center : FullConvexity_X_without_center;
      if ( myComputations & mask ) return bool( myResults & mask );
      // Need to compute full convexity property
      bool ok = checkBasicConfigurations0Convexity( false, with_center );
      if ( ok && false_positive )
        { // need to do the true computation.
          std::vector< Point > localX;
          getLocalX( localX, with_center );
          ok = myDigConv.is0Convex( localX );
        }
      myComputations |= mask;
      if ( ok ) myResults |= mask;
      return ok;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurations0Convexity(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::false_positive, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_X_with_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_X_without_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalX(), DGtal::DigitalConvexity< TKSpace >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible().
is0ConvexCollapsible()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible () inline
Returns
'true' iff the center is locally 0-convex collapsible.
Definition at line 271 of file NeighborhoodConvexityAnalyzer.h.
    {
      if ( isCenterInX() )
        return ( myNbInX >= 1 ) // ( ! myLocalX.empty() )
          && is0Convex( true )
          && is0Convex( false );
      else
        return ( size() - myNbInX >= 2 ) // ( ! myLocalCompX.empty() )
          && isComplementary0Convex( true )
          && isComplementary0Convex( false );
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isCenterInX(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myNbInX, and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size().
Referenced by main().
isCenterInX()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isCenterInX () const inline
Tells if the current center belongs to the shape X.
Definition at line 237 of file NeighborhoodConvexityAnalyzer.h.
    {
      return myCenterInX;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCenterInX.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise().
isComplementary0Convex()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex (bool with_center) inline
Tells if the complementary of the shape is locally digitally 0-convex.
Parameters
with_center if 'true' add the center to the digital set.
Returns
'true' iff the local neighborhood of the complementary of X (with/without the center) is 0 convex
Definition at line 447 of file NeighborhoodConvexityAnalyzer.h.
    {
      int mask = with_center
        ? FullConvexity_CompX_with_center : FullConvexity_CompX_without_center;
      if ( myComputations & mask ) return bool( myResults & mask );
      // Need to compute full convexity property
      bool ok = checkBasicConfigurations0Convexity( true, with_center );
      if ( ok && false_positive )
        { // need to do the true computation.
          std::vector< Point > localCompX;
          getLocalCompX( localCompX, with_center );
          ok = myDigConv.is0Convex( localCompX );
        }
      myComputations |= mask;
      if ( ok ) myResults |= mask;
      return ok;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurations0Convexity(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::false_positive, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_CompX_with_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_CompX_without_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalCompX(), DGtal::DigitalConvexity< TKSpace >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible().
isComplementaryFullyConvex()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex (bool with_center) inline
Tells if the complementary of the shape is locally fully convex.
Parameters
with_center if 'true' add the center to the digital set.
Returns
'true' iff the local neighborhood of the complementary of X (with/without the center) is fully convex
Definition at line 355 of file NeighborhoodConvexityAnalyzer.h.
    {
      int mask = with_center
        ? FullConvexity_CompX_with_center : FullConvexity_CompX_without_center;
      if ( myComputations & mask ) return bool( myResults & mask );
      bool ok;
      // Check memoizer
      if ( myMemoizer.isValid() )
        {
          auto cfg = makeConfiguration( myCfgX, true, with_center );
          auto   p = myMemoizer.get( cfg );
          ok       = p.first; // may not be correct
          bool memoized = p.second;
          if ( ! memoized )
            {
              // Need to compute full convexity property
              ok = checkBasicConfigurationsFullConvexity( true, with_center );
              if ( ok && false_positive )
                { // need to do the true computation.
                  std::vector< Point > localCompX;
                  getLocalCompX( localCompX, with_center );
                  ok = myDigConv.isFullyConvex( localCompX );
                }
              myMemoizer.set( cfg, ok );
            }
        }
      else
        {
          // Need to compute full convexity property
          ok = checkBasicConfigurationsFullConvexity( true, with_center );
          if ( ok && false_positive )
            { // need to do the true computation.
              std::vector< Point > localCompX;
              getLocalCompX( localCompX, with_center );
              ok = myDigConv.isFullyConvex( localCompX );
            }
        }
      // bool memoized = false;
      // auto cfg = makeConfiguration( myCfgX, true, with_center );
      // // Check memoizer
      // if ( myMemoizer.isValid() )
      //   {
      //     auto   p = myMemoizer.get( cfg );
      //     ok       = p.first; // may not be correct
      //     memoized = p.second;
      //   }
      // if ( ! memoized )
      //   {
      //     // Need to compute full convexity property
      //     ok = checkBasicConfigurationsFullConvexity( true, with_center );
      //     if ( ok && false_positive )
      //       { // need to do the true computation.
      //         std::vector< Point > localCompX;
      //         getLocalCompX( localCompX, with_center );
      //         ok = myDigConv.isFullyConvex( localCompX );
      //       }
      //     if ( myMemoizer.isValid() )
      //       myMemoizer.set( cfg, ok );
      //   }
      myComputations |= mask;
      if ( ok ) myResults |= mask;
      return ok;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurationsFullConvexity(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::false_positive, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_CompX_with_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_CompX_without_center, DGtal::TimeStampMemoizer< TKey, TValue >::get(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalCompX(), DGtal::DigitalConvexity< TKSpace >::isFullyConvex(), DGtal::TimeStampMemoizer< TKey, TValue >::isValid(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::makeConfiguration(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCfgX, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myMemoizer, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults, and DGtal::TimeStampMemoizer< TKey, TValue >::set().
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise(), and main().
isFullyConvex()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex (bool with_center) inline
Tells if the shape X is locally fully convex.
Parameters
with_center if 'true' add the center to the digital set.
Returns
'true' iff the local neighborhood of X (with/without the center) is fully convex
Definition at line 288 of file NeighborhoodConvexityAnalyzer.h.
    {
      int mask = with_center
        ? FullConvexity_X_with_center : FullConvexity_X_without_center;
      if ( myComputations & mask ) return bool( myResults & mask );
      bool ok;
      // Check memoizer
      if ( myMemoizer.isValid() )
        {
          auto cfg = makeConfiguration( myCfgX, false, with_center );
          auto   p = myMemoizer.get( cfg );
          ok       = p.first; // may not be correct
          bool memoized = p.second;
          if ( ! memoized )
            {
              // Need to compute full convexity property
              ok = checkBasicConfigurationsFullConvexity( false, with_center );
              if ( ok && false_positive )
                { // need to do the true computation.
                  std::vector< Point > localX;
                  getLocalX( localX, with_center );
                  ok = myDigConv.isFullyConvex( localX );
                }
              myMemoizer.set( cfg, ok );
            }
        }
      else
        {
          ok = checkBasicConfigurationsFullConvexity( false, with_center );
          if ( ok && false_positive )
            { // need to do the true computation.
              std::vector< Point > localX;
              getLocalX( localX, with_center );
              ok = myDigConv.isFullyConvex( localX );
            }
        }
      // auto cfg = makeConfiguration( myCfgX, false, with_center );
      // // Check memoizer
      // if ( myMemoizer.isValid() )
      //   {
      //     auto   p = myMemoizer.get( cfg );
      //     ok       = p.first; // may not be correct
      //     memoized = p.second;
      //   }
      // if ( ! memoized )
      //   {
      //     // Need to compute full convexity property
      //     ok = checkBasicConfigurationsFullConvexity( false, with_center );
      //     if ( ok && false_positive )
      //       { // need to do the true computation.
      //         std::vector< Point > localX;
      //         getLocalX( localX, with_center );
      //         ok = myDigConv.isFullyConvex( localX );
      //       }
      //     if ( myMemoizer.isValid() )
      //       myMemoizer.set( cfg, ok );
      //   }
      myComputations |= mask;
      if ( ok ) myResults |= mask;
      return ok;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::checkBasicConfigurationsFullConvexity(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::false_positive, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_X_with_center, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::FullConvexity_X_without_center, DGtal::TimeStampMemoizer< TKey, TValue >::get(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalX(), DGtal::DigitalConvexity< TKSpace >::isFullyConvex(), DGtal::TimeStampMemoizer< TKey, TValue >::isValid(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::makeConfiguration(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCfgX, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myMemoizer, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults, and DGtal::TimeStampMemoizer< TKey, TValue >::set().
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise(), and main().
isFullyConvexCollapsible()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible () inline
Returns
'true' iff the center is locally fully convex collapsible.
Definition at line 243 of file NeighborhoodConvexityAnalyzer.h.
    {
      if ( isCenterInX() )
        return ( myNbInX >= 1 ) // ( ! myLocalX.empty() )
          && isFullyConvex( true )
          && isFullyConvex( false );
      else
        return ( size() - myNbInX >= 2 ) // ( ! myLocalCompX.empty() )
          && isComplementaryFullyConvex( true )
          && isComplementaryFullyConvex( false );
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isCenterInX(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myNbInX, and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size().
Referenced by main().
isLikelyNoise()
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise () inline
Returns
'true' iff the center point is likely noise.
Definition at line 256 of file NeighborhoodConvexityAnalyzer.h.
    {
      if ( isCenterInX() )
        return ( myNbInX >= 1 ) // ( ! myLocalX.empty() )
          && ! isFullyConvex( true )
          && isFullyConvex( false )
          && isComplementaryFullyConvex( true );
      else
        return ( size() - myNbInX >= 2 ) // ( ! myLocalCompX.empty() )
          && ! isComplementaryFullyConvex( true )
          && isComplementaryFullyConvex( false )
          && isFullyConvex( true );
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isCenterInX(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myNbInX, and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size().
makeConfiguration()
template<typename TKSpace , int K> static Configuration DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::makeConfiguration (Configuration current, bool complement, bool with_center) inline static
Builds the final configuration from the configuration current, by complementing it according to complement, and by adding its center point according to with_center.
Parameters
current any configuration (with empty center/middle bit)
complement when 'true', complements the configuration.
with_center when 'true', makes the center point part of the configuration
Returns
the corresponding configuration
Definition at line 473 of file NeighborhoodConvexityAnalyzer.h.
    {
      if ( complement )
        {
          current.flip(); // current = ~current;
          if ( ! with_center ) current.reset( middle );
          else current.set( middle );
        }
      else
        {
          if ( with_center ) current.set( middle );
        }
      return current;
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::middle.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex().
operator=()
template<typename TKSpace , int K> Self & DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::operator= (const Self & other) default
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
radius()
template<typename TKSpace , int K> static int DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::radius () inline static
Returns
the fixed parameter K of the neighborhood, which determines its size.
Definition at line 196 of file NeighborhoodConvexityAnalyzer.h.
    { return K; }
References K.
setCenter()
template<typename TKSpace , int K> template<typename PointPredicate > void DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::setCenter (Point c, const PointPredicate & X)
Place the center of the neighborhood at point c on shape X All subsequent computations and results are related to this point afterwards.
Template Parameters
PointPredicate an arbitrary model of concept::CPointPredicate
Parameters
c any point in the domain of the embedding space.
X a predicate associating a boolean to any point, which corresponds to a characteristic function of a digital subset X of the digital space.
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Referenced by main().
size()
template<typename TKSpace , int K> static Size DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size () inline static
Returns
the size of the neighborhood, that is all the point within the neighborhood except its center.
Definition at line 201 of file NeighborhoodConvexityAnalyzer.h.
    { return neigh_size; }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::neigh_size.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
space()
template<typename TKSpace , int K> const KSpace & DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::space () const inline
Returns
a const reference to the cellular grid space used by this object.
Definition at line 184 of file NeighborhoodConvexityAnalyzer.h.
    {
      return myDigConv.space();
    }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv, and DGtal::DigitalConvexity< TKSpace >::space().
Field Documentation
dimension
template<typename TKSpace , int K> const Dimension DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::dimension = KSpace::dimension static
Definition at line 110 of file NeighborhoodConvexityAnalyzer.h.
false_positive
template<typename TKSpace , int K> const bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::false_positive = (dimension > 2) || (K > 1) static
Definition at line 113 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex().
middle
template<typename TKSpace , int K> const Size DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::middle = functions::const_middle(K, dimension) static
Definition at line 112 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::makeConfiguration(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
myBasic0ConvexityTable
template<typename TKSpace , int K> std::bitset< 512 > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myBasic0ConvexityTable protected
Stores the 0-convexity property of the basic 3x3 neighborhood configurations.
Definition at line 525 of file NeighborhoodConvexityAnalyzer.h.
myBasicCfgX
template<typename TKSpace , int K> std::vector< BasicConfiguration > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myBasicCfgX protected
Stores the basic local configurations associated to myCfgX, for speed-up.
Definition at line 520 of file NeighborhoodConvexityAnalyzer.h.
myBasicFullConvexityTable
template<typename TKSpace , int K> std::bitset< 512 > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myBasicFullConvexityTable protected
Stores the full convexity property of the basic 3x3 neighborhood configurations.
Definition at line 523 of file NeighborhoodConvexityAnalyzer.h.
myCenter
template<typename TKSpace , int K> Point DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCenter protected
The current center of the neighborhood.
Definition at line 510 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::center().
myCenterInX
template<typename TKSpace , int K> bool DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCenterInX protected
tells if the center belongs to X
Definition at line 514 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isCenterInX().
myCfgX
template<typename TKSpace , int K> Configuration DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myCfgX protected
Stores the local configuration for X (without the center)
Definition at line 518 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::configuration(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex().
myComputations
template<typename TKSpace , int K> int DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myComputations protected
Stores which properties have already been computed.
Definition at line 539 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
myDigConv
template<typename TKSpace , int K> DigitalConvexity<KSpace> DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDigConv protected
The digital convexity that is used for checking full convexity.
Definition at line 508 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::space().
myDomain
template<typename TKSpace , int K> Domain DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myDomain protected
The bounded domain in which computations are carried out.
Definition at line 506 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::domain(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
myMemoizer
template<typename TKSpace , int K> TimeStampMemoizer< Configuration, bool > DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myMemoizer protected
The memoizer.
Definition at line 512 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex().
myNbInX
template<typename TKSpace , int K> Size DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myNbInX protected
The number of points of the neighborhood that belongs to X (center omitted).
Definition at line 516 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0ConvexCollapsible(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvexCollapsible(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isLikelyNoise().
myResults
template<typename TKSpace , int K> int DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::myResults protected
Stores the properties boolean values.
Definition at line 541 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::is0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementary0Convex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer(), and DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::NeighborhoodConvexityAnalyzer().
neigh_size
template<typename TKSpace , int K> const Size DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::neigh_size = functions::const_pow(2*K+1, dimension) static
Definition at line 111 of file NeighborhoodConvexityAnalyzer.h.
Referenced by DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::size().
The documentation for this class was generated from the following file:
NeighborhoodConvexityAnalyzer.h