DGtal: DGtal::Color Class Reference
DGtal::Color Class Reference
Structure representing an RGB triple with alpha component.
#include <DGtal/io/Color.h>
Public Member Functions
~Color ()=default
Color (const unsigned int aRgb, unsigned char aAlpha=255)
Color (const Color &aColor)=default
Color (const unsigned char aRedValue, const unsigned char aGreenValue, const unsigned char aBlueValue, const unsigned char aAlphaValue=255)
Color (unsigned char aGrayValue, unsigned char aAlphaValue=255)
Color ()
void red (const unsigned char aRedValue)
void green (const unsigned char aGreenValue)
void blue (const unsigned char aBlueValue)
void alpha (const unsigned char aAlphaValue)
unsigned char red () const
unsigned char green () const
unsigned char blue () const
unsigned char alpha () const
double r () const
double g () const
double b () const
double a () const
Color & setRGBi (const unsigned char aRedValue, const unsigned char aGreenValue, const unsigned char aBlueValue, const unsigned char aAlphaValue=255)
Color & setRGBA (DGtal::uint32_t aRGBA)
Color & setFromHSV (const double h, const double s, const double v)
std::array< double, 3 > getHSV () const
DGtal::uint32_t getRGB () const
DGtal::uint32_t getRGBA () const
bool valid () const
void selfDisplay (std::ostream &out) const
bool isValid () const
Color & setRGBf (float red, float green, float blue, float alpha=1.0)
bool operator== (const Color &aColor) const
bool operator!= (const Color &aColor) const
bool operator< (const Color &aColor) const
bool operator> (const Color &aColor) const
bool operator<= (const Color &aColor) const
bool operator>= (const Color &aColor) const
Color & operator+= (const Color &v)
Color operator+ (const Color &v) const
Color & operator-= (const Color &v)
Color operator- (const Color &v) const
Color & operator*= (const double coeff)
Color operator* (const double coeff) const
Color & operator= (const Color &pv)=default
void flushPostscript (std::ostream &) const
std::string svg () const
std::string svgAlpha (const char *aPrefix) const
std::string postscript () const
std::string tikz () const
Static Public Member Functions
static void HSVtoRGB (double &r, double &g, double &b, double h, const double s, const double v)
static void RGBtoHSV (double &h, double &s, double &v, const unsigned char r, const unsigned char g, const unsigned char b)
Static Public Attributes
static const Color None
static const Color Black
static const Color Gray
static const Color White
static const Color Red
static const Color Green
static const Color Lime
static const Color Blue
static const Color Cyan
static const Color Magenta
static const Color Yellow
static const Color Silver
static const Color Purple
static const Color Navy
static const Color Aqua
Private Member Functions
unsigned char clamp (const double value) const
Private Attributes
unsigned char myRed
unsigned char myGreen
unsigned char myBlue
unsigned char myAlpha
Detailed Description
Structure representing an RGB triple with alpha component.
Description of class 'Color'
Note
if compilation flag COLOR_WITH_ALPHA_ARITH is set, then the arithmetical operations on colors also consider the alpha-channel. Otherwise, the alpha channel is not changed when summing up to colors for instance.
Examples
dec/exampleDiscreteExteriorCalculusSolve.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/meshes/curvature-measures-icnc-3d.cpp, geometry/meshes/curvature-measures-icnc-XY-3d.cpp, geometry/meshes/curvature-measures-nc-3d.cpp, geometry/meshes/curvature-measures-nc-XY-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-XY-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-XY-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-XY-3d.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/distancetransform3D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/voronoimap2D.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/graphTraversal.cpp, graph/volDistanceTraversal.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/dgtalBoard3D-1-points.cpp, io/boards/dgtalBoard3D-6-clipping.cpp, io/boards/dgtalBoard3DTo2D-3-objects.cpp, io/boards/dgtalBoard3DTo2D-5-custom.cpp, io/boards/dgtalBoard3DTo2D-6.cpp, io/boards/logoDGtal.cpp, io/digitalSetFromPointList.cpp, io/meshFromOFF.cpp, io/viewDualSurface.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-5-custom.cpp, io/viewers/viewer3D-6-clipping.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, io/viewers/viewer3D-8-2DSliceImages.cpp, io/viewers/viewer3D-9-3Dimages.cpp, shapes/exampleEuclideanShapesDecorator.cpp, shapes/mesh3DConstructionAndVisualisation.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dBorderExtraction.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-1.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/ctopo-fillContours.cpp, topology/cubical-complex-illustrations.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/homotopicThinning3D.cpp, topology/khalimskySpaceScanner.cpp, topology/volBreadthFirstTraversal.cpp, topology/volScanBoundary.cpp, topology/volTrackBoundary.cpp, tutorial-examples/freemanChainFromImage.cpp, tutorial-examples/polyhedralizer.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 67 of file Color.h.
Constructor & Destructor Documentation
~Color()
DGtal::Color::~Color () default
Destructor.
Color() [1/5]
DGtal::Color::Color (const unsigned int aRgb, unsigned char aAlpha = 255)
Constructor.
Parameters
aRgb an unsigned int representing the color.
aAlpha color transparency (default value =255);
Definition at line 44 of file Color.cpp.
 :myAlpha( aAlphaValue )
{
  myRed = ( rgb & 0xFF0000u ) >> 16;
  myGreen = ( rgb & 0xFF00u ) >> 8;
  myBlue = rgb & 0xFF;
}
References myBlue, myGreen, and myRed.
Color() [2/5]
DGtal::Color::Color (const Color & aColor) default
Copy Constructor.
Parameters
aColor the color to copy.
Color() [3/5]
DGtal::Color::Color (const unsigned char aRedValue, const unsigned char aGreenValue, const unsigned char aBlueValue, const unsigned char aAlphaValue = 255) inline
Constructor from R, G, B and Alpha parameter.
Parameters
aRedValue red component
aGreenValue green component
aBlueValue blue component
aAlphaValue color transparency.
Definition at line 106 of file Color.h.
      : myRed(aRedValue),myGreen(aGreenValue),myBlue(aBlueValue),myAlpha(aAlphaValue) { }
Color() [4/5]
DGtal::Color::Color (unsigned char aGrayValue, unsigned char aAlphaValue = 255) inline
Constructor from gray scale value.
Parameters
aGrayValue the color gray value.
aAlphaValue color transparency (default value =255);.
Definition at line 120 of file Color.h.
      : myRed(aGrayValue),myGreen(aGrayValue), myBlue(aGrayValue), myAlpha(aAlphaValue) { }
Color() [5/5]
DGtal::Color::Color () inline
Default Constructor.
Definition at line 130 of file Color.h.
      : myRed(0),myGreen(0),myBlue(0), myAlpha(255)
    {
    }
Member Function Documentation
a()
double DGtal::Color::a () const
alpha() [1/2]
unsigned char DGtal::Color::alpha () const
alpha() [2/2]
void DGtal::Color::alpha (const unsigned char aAlphaValue)
b()
double DGtal::Color::b () const
Referenced by getHSV(), and setFromHSV().
blue() [1/2]
unsigned char DGtal::Color::blue () const
blue() [2/2]
void DGtal::Color::blue (const unsigned char aBlueValue)
Examples
io/viewers/viewer3D-8-2DSliceImages.cpp, io/viewers/viewer3D-9-3Dimages.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-2-3d.cpp, and topology/digitalSurfaceSlice.cpp.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), DGtal::Viewer3D< TSpace, TKSpace >::GLTextureImage::GLTextureImage(), LibBoard::GouraudTriangle::GouraudTriangle(), main(), DGtal::functors::BlueChannel::operator()(), DGtal::functors::MeanChannels::operator()(), and testGrayscaleColorMap().
clamp()
unsigned char DGtal::Color::clamp (const double value) const inline private
Clamp an int to [0,255]
Parameters
[in] value the value to clamp
Returns
the clamped value
Definition at line 450 of file Color.h.
    {
      return static_cast<unsigned char>(std::max( std::min(value, 255.0), 0.0));
    }
flushPostscript()
void DGtal::Color::flushPostscript (std::ostream & stream) const
Definition at line 142 of file Color.cpp.
{
  stream << ((double)myRed/255.0) << " "
   << ((double)myGreen/255.0) << " "
   << ((double)myBlue/255.0) << " srgb\n";
}
Referenced by LibBoard::Polyline::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), and LibBoard::Arc::flushPostscript().
g()
double DGtal::Color::g () const
Referenced by getHSV(), and setFromHSV().
getHSV()
std::array< double, 3 > DGtal::Color::getHSV () const inline
Returns
the HSV values of a DGtal::Color (array of three doubles).
Definition at line 192 of file Color.h.
    {
      double h,s,v;
      Color::RGBtoHSV(h,s,v, this->r(), this->g(), this->b());
      return {h,s,v};
    }
References b(), g(), r(), and RGBtoHSV().
getRGB()
DGtal::uint32_t DGtal::Color::getRGB () const
Returns
the unsigned integer (DGtal::uint32_t) coding each R, G, B canal on 8 bits starting from least significant bit.
Referenced by DGtal::functors::ColorRGBEncoder< TValue >::operator()().
getRGBA()
DGtal::uint32_t DGtal::Color::getRGBA () const
Returns
the unsigned integer (DGtal::uint32_t) coding each R, G, B, A canal on 8 bits starting from least significant bit.
green() [1/2]
unsigned char DGtal::Color::green () const
green() [2/2]
void DGtal::Color::green (const unsigned char aGreenValue)
Examples
io/viewers/viewer3D-8-2DSliceImages.cpp, io/viewers/viewer3D-9-3Dimages.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-2-3d.cpp, and topology/digitalSurfaceSlice.cpp.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), DGtal::Viewer3D< TSpace, TKSpace >::GLTextureImage::GLTextureImage(), LibBoard::GouraudTriangle::GouraudTriangle(), main(), DGtal::functors::GreenChannel::operator()(), DGtal::functors::MeanChannels::operator()(), and testGrayscaleColorMap().
HSVtoRGB()
static void DGtal::Color::HSVtoRGB (double & r, double & g, double & b, double h, const double s, const double v) static
Converts a color from the HSV (Hue,Saturation,Value) space to the RGB space.
Parameters
r The red component (out).
g The green component (out).
b The blue component (out).
h The hue of the color in [0..360)
s The saturation of the color in [0..1].
v The value of the color in [0..1].
Referenced by setFromHSV().
isValid()
bool DGtal::Color::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 235 of file Color.cpp.
{
    return true;
}
operator!=()
bool DGtal::Color::operator!= (const Color & aColor) const
Definition at line 96 of file Color.cpp.
{
  return myRed != aColor.myRed
    || myGreen != aColor.myGreen
    || myBlue != aColor.myBlue
    || myAlpha != aColor.myAlpha;
}
References myAlpha, myBlue, myGreen, and myRed.
operator*()
Color DGtal::Color::operator* (const double coeff) const inline
Multiplication by a scalar (component-wise)
Note
returned components are clamped to [0,255] interval.
Parameters
coeff the scalar.
Returns
a scaled color
Definition at line 364 of file Color.h.
    {
      Color c;
      c.myRed = clamp((double)this->myRed*coeff);
      c.myBlue = clamp((double)this->myBlue*coeff);
      c.myGreen = clamp((double)this->myGreen*coeff);
#ifdef COLOR_WITH_ALPHA_ARITH
      c.myAlpha =  clamp((double)this->myAlpha*coeff);
#else
      c.myAlpha  = this->myAlpha;
#endif
      return c;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator*=()
Color & DGtal::Color::operator*= (const double coeff) inline
Multiplication by a scalar (component-wise)
Note
returned components are clamped to [0,255] interval.
Parameters
coeff the scalar
Returns
the scaled color
Definition at line 345 of file Color.h.
    {
      this->myRed = clamp((double)this->myRed*coeff);
      this->myBlue = clamp((double)this->myBlue*coeff);
      this->myGreen = clamp((double)this->myGreen*coeff);
#ifdef COLOR_WITH_ALPHA_ARITH
      this->myAlpha =  clamp((double)this->myAlpha*coeff);
#endif
      return *this;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator+()
Color DGtal::Color::operator+ (const Color & v) const inline
Addition operator.
Note
returned components are clamped to [0,255] interval.
Parameters
v is the Color that gets added to *this.
Returns
a new Point that is the addition of 'this' to [v].
Definition at line 279 of file Color.h.
    {
      Color c;
      c.myRed = clamp((int)this->myRed + (int)v.myRed);
      c.myBlue =clamp((int)this->myBlue + (int)v.myBlue);
      c.myGreen = clamp((int)this->myGreen + (int)v.myGreen);
#ifdef COLOR_WITH_ALPHA_ARITH
      c.myAlpha = clamp((int)this->myAlpha + (int)v.myAlpha);
#else
      c.myAlpha = this->myAlpha ;
#endif
  return c;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator+=()
Color & DGtal::Color::operator+= (const Color & v) inline
Addition operator with assignement.
Note
returned components are clamped to [0,255] interval.
Parameters
v is the Color that gets added to *this.
Returns
a reference on 'this'.
Definition at line 259 of file Color.h.
    {
      this->myRed = clamp((int)this->myRed + (int)v.myRed);
      this->myBlue =  clamp((int)this->myBlue + (int)v.myBlue);
      this->myGreen =  clamp((int)this->myGreen + (int)v.myGreen);
#ifdef COLOR_WITH_ALPHA_ARITH
      this->myAlpha =  clamp((int)this->myAlpha + (int)v.myAlpha);
#endif
      return *this;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator-()
Color DGtal::Color::operator- (const Color & v) const inline
Substraction operator.
Note
returned components are clamped to [0,255] interval.
Parameters
v is the Color that gets substacted to *this.
Returns
a new Point that is the subtraction 'this'-[v].
Definition at line 321 of file Color.h.
    {
      Color c;
      c.myRed = clamp((int)this->myRed - (int)v.myRed);
      c.myBlue = clamp((int)this->myBlue - (int)v.myBlue);
      c.myGreen = clamp((int)this->myGreen - (int)v.myGreen);
#ifdef COLOR_WITH_ALPHA_ARITH
      c.myAlpha = clamp((int)this->myAlpha - (int)v.myAlpha);
#else
      c.myAlpha = this->myAlpha ;
#endif
      return c;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator-=()
Color & DGtal::Color::operator-= (const Color & v) inline
Substraction operator with assignement.
Note
returned components are clamped to [0,255] interval.
Parameters
v is the Point that gets substracted to *this.
Returns
a reference on 'this'.
Definition at line 302 of file Color.h.
    {
      this->myRed = clamp((int)this->myRed - (int)v.myRed);
      this->myBlue = clamp((int)this->myBlue - (int)v.myBlue);
      this->myGreen = clamp((int)this->myGreen - (int)v.myGreen);
#ifdef COLOR_WITH_ALPHA_ARITH
      this->myAlpha = clamp((int)this->myAlpha - (int)v.myAlpha);
#endif
      return *this;
    }
References myAlpha, myBlue, myGreen, and myRed.
operator<()
bool DGtal::Color::operator< (const Color & aColor) const
Definition at line 104 of file Color.cpp.
{
  if ( myRed < aColor.myRed )
    return true;
  if ( myRed == aColor.myRed ) {
    if ( myGreen < aColor.myGreen )
      return true;
    if ( myGreen == aColor.myGreen ) {
      if ( myBlue < aColor.myBlue )
  return true;
      if ( myBlue == aColor.myBlue )
  return myAlpha < aColor.myAlpha;
    }
  }
  return false;
}
References myAlpha, myBlue, myGreen, and myRed.
operator<=()
bool DGtal::Color::operator<= (const Color & aColor) const
Definition at line 128 of file Color.cpp.
{
  return this->operator<(aColor) || this->operator==(aColor);
}
References DGtal::operator<(), and DGtal::operator==().
operator=()
Color & DGtal::Color::operator= (const Color & pv) default
Assignement Operator
Parameters
pv the object to copy.
Returns
a reference on 'this'.
operator==()
bool DGtal::Color::operator== (const Color & aColor) const
Definition at line 87 of file Color.cpp.
{
  return myRed == aColor.myRed
    && myGreen == aColor.myGreen
    && myBlue == aColor.myBlue
    && myAlpha == aColor.myAlpha;
}
References myAlpha, myBlue, myGreen, and myRed.
operator>()
bool DGtal::Color::operator> (const Color & aColor) const
Definition at line 123 of file Color.cpp.
{
  return !this->operator<(aColor);
}
References DGtal::operator<().
operator>=()
bool DGtal::Color::operator>= (const Color & aColor) const
Definition at line 135 of file Color.cpp.
{
  return this->operator>(aColor) || this->operator==(aColor);
}
References DGtal::operator==(), and DGtal::operator>().
postscript()
string DGtal::Color::postscript () const
Definition at line 150 of file Color.cpp.
{
  char buffer[255];
  secured_sprintf( buffer, 255, "%.4f %.4f %.4f", myRed/255.0, myGreen/255.0, myBlue/255.0 );
  return buffer;
}
Referenced by LibBoard::Dot::flushPostscript(), LibBoard::Line::flushPostscript(), LibBoard::Arrow::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arc::flushPostscript(), and LibBoard::Text::flushPostscript().
r()
double DGtal::Color::r () const
Referenced by getHSV(), and setFromHSV().
red() [1/2]
unsigned char DGtal::Color::red () const
red() [2/2]
void DGtal::Color::red (const unsigned char aRedValue)
Examples
io/viewers/viewer3D-8-2DSliceImages.cpp, io/viewers/viewer3D-9-3Dimages.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-2-3d.cpp, and topology/digitalSurfaceSlice.cpp.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), DGtal::Viewer3D< TSpace, TKSpace >::GLTextureImage::GLTextureImage(), LibBoard::GouraudTriangle::GouraudTriangle(), main(), DGtal::functors::RedChannel::operator()(), DGtal::functors::MeanChannels::operator()(), and testGrayscaleColorMap().
RGBtoHSV()
static void DGtal::Color::RGBtoHSV (double & h, double & s, double & v, const unsigned char r, const unsigned char g, const unsigned char b) static
Converts a color from the RGB space to the HSV (Hue,Saturation,Value) space.
Parameters
h (out) The hue of the color in [0..360)
s (out) The saturation of the color in [0..1].
v (out) The value of the color in [0..1].
r The red component.
g The green component.
b The blue component.
Referenced by getHSV().
selfDisplay()
void DGtal::Color::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 225 of file Color.cpp.
{
  out << "[Color] RGBA("<<(int)myRed<<","<<(int)myGreen<<","<<(int)myBlue<<","<<(int)myAlpha<<")";
}
setFromHSV()
Color & DGtal::Color::setFromHSV (const double h, const double s, const double v) inline
Set the color from HSV values
Parameters
h hue
s saturation
v value
Returns
the color
Definition at line 184 of file Color.h.
    {
      double r,g,b;
      Color::HSVtoRGB(r,g,b,h,s,v);
      return this->setRGBf((float)r,(float)g,(float)b);
    }
References b(), g(), HSVtoRGB(), r(), and setRGBf().
setRGBA()
DGtal::Color & DGtal::Color::setRGBA (DGtal::uint32_t aRGBA)
Set the color parameter from an unsigned integer coding each canal.
Parameters
aRGBA an unsigned integer on 32 bits(DGtal::unit32_t) representing the color coded with 4 bits on each components R, G, B and Alpha value.
Returns
a reference on the itself.
Definition at line 54 of file Color.cpp.
{
  myRed = ( aRGBA & 0xFF000000u ) >> 24;
  myGreen = ( aRGBA & 0xFF0000u ) >> 16;
  myBlue = ( aRGBA & 0xFF00u ) >> 8;
  myAlpha = aRGBA & 0xFF;
  return *this;
}
setRGBf()
DGtal::Color & DGtal::Color::setRGBf (float red, float green, float blue, float alpha = 1.0)
Definition at line 65 of file Color.cpp.
{
  if ( aRedValue > 1.0f ) aRedValue = 1.0f;
  if ( aRedValue < 0.0f ) aRedValue = 0.0f;
  myRed = static_cast<unsigned char>( 255 * aRedValue );
  if ( aGreenValue > 1.0f ) aGreenValue = 1.0f;
  if ( aGreenValue < 0.0f ) aGreenValue = 0.0f;
  myGreen = static_cast<unsigned char>( 255 * aGreenValue );
  if ( aBlueValue > 1.0f ) aBlueValue = 1.0f;
  if ( aBlueValue < 0.0f ) aBlueValue = 0.0f;
  myBlue = static_cast<unsigned char>( 255 * aBlueValue );
  if ( aAlphaValue > 1.0f ) aAlphaValue = 1.0f;
  if ( aAlphaValue < 0.0f ) aAlphaValue = 0.0f;
  myAlpha = static_cast<unsigned char>( 255 * aAlphaValue );
  return *this;
}
Referenced by LibBoard::Board::setFillColorRGBf(), setFromHSV(), and LibBoard::Board::setPenColorRGBf().
setRGBi()
Color & DGtal::Color::setRGBi (const unsigned char aRedValue, const unsigned char aGreenValue, const unsigned char aBlueValue, const unsigned char aAlphaValue = 255)
Referenced by LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setPenColorRGBi(), and testColor().
svg()
string DGtal::Color::svg () const
Definition at line 158 of file Color.cpp.
{
  char buffer[255];
  if ( *this == DGtal::Color::None ) return "none";
  secured_sprintf( buffer, 255, "rgb(%d,%d,%d)",myRed, myGreen, myBlue );
  return buffer;
}
References None.
Referenced by LibBoard::Arrow::flushSVG(), LibBoard::Text::flushSVG(), and LibBoard::Shape::svgProperties().
svgAlpha()
string DGtal::Color::svgAlpha (const char * aPrefix) const
Return a an SVG parameter string for the opacity value.
Parameters
aPrefix A prefix string to be appended to the returned string if not empty.
Returns
An empty string if alpha == 255, otherwise the string <prefix>-opacity="<alpha-value>".
Definition at line 167 of file Color.cpp.
{
  char buffer[255];
  if ( myAlpha == 255 || *this == DGtal::Color::None ) return "";
  secured_sprintf( buffer, 255, " %s-opacity=\"%f\"", prefix, myAlpha/255.0f );
  return buffer;
}
References None.
Referenced by LibBoard::Arrow::flushSVG(), LibBoard::Text::flushSVG(), and LibBoard::Shape::svgProperties().
tikz()
string DGtal::Color::tikz () const
Return a string representation of the color usable in TikZ commands. Use the corresponding named color (or a mixture of a named color and black) for predefined colors. Use a mixture of red, green and blue for general colors.
Returns
a string representation of the color usable in TikZ commands.
Definition at line 176 of file Color.cpp.
{
  // see tex/generic/pgf/utilities/pgfutil-plain.def for color definitions
  char buffer[255];
  if ( *this == DGtal::Color::None ) return "none";
  if ( *this == DGtal::Color::Black ) return "black";
  if ( *this == DGtal::Color::Gray ) return "gray";
  if ( *this == DGtal::Color::White ) return "white";
  if ( *this == DGtal::Color::Red ) return "red";
  if ( *this == DGtal::Color::Green ) return "green!50!black";
  if ( *this == DGtal::Color::Lime ) return "green";
  if ( *this == DGtal::Color::Blue ) return "blue";
//  if (*this == DGtal::Color::Cyan) return "cyan";
//  if (*this == DGtal::Color::Magenta) return "magenta";
//  if (*this == DGtal::Color::Yellow) return "yellow";
  if ( *this == DGtal::Color::Silver ) return "white!75!black";
  if ( *this == DGtal::Color::Purple ) return "purple";
  if ( *this == DGtal::Color::Navy ) return "blue!50!black";
//  if (*this == DGtal::Color::Aqua) return "cyan"; // ???: Is Color::Aqua meant to be equal to Color::Cyan?
  secured_sprintf( buffer, 255, "{rgb,255:red,%d;green,%d;blue,%d}", myRed, myGreen, myBlue );
  return buffer;
}
References Black, Blue, Gray, Green, Lime, Navy, None, Purple, Red, Silver, and White.
Referenced by LibBoard::Shape::tikzProperties().
valid()
bool DGtal::Color::valid () const
Referenced by LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), and LibBoard::Board::saveFIG().
Field Documentation
Aqua
const DGtal::Color DGtal::Color::Aqua static
Definition at line 426 of file Color.h.
Black
const DGtal::Color DGtal::Color::Black static
Definition at line 413 of file Color.h.
Referenced by addColorMapSample(), drawCCP(), drawPolygon(), DGtal::Shortcuts< TKSpace >::getZeroTickedColorMap(), main(), saveToObj(), LibBoard::Board::State::State(), testBreadthFirstPropagation(), testCMAP(), testDepthFirstPropagation(), testDistancePropagation(), testGrayscaleColorMap(), and tikz().
Blue
const DGtal::Color DGtal::Color::Blue static
Examples
geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/tools/exampleConvexHull2D.cpp, topology/ctopo-fillContours.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 419 of file Color.h.
Referenced by convexHull(), drawCCP(), main(), showGreedySegmantation(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testConvexHullCompThickness(), testMeshGeneration(), testThicknessDefinitions(), testVisualTubularMesh(), and tikz().
Cyan
const DGtal::Color DGtal::Color::Cyan static
Definition at line 420 of file Color.h.
Referenced by main().
Gray
const DGtal::Color DGtal::Color::Gray static
Examples
geometry/curves/greedyAlphaThickDecomposition.cpp.
Definition at line 414 of file Color.h.
Referenced by main(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testThicknessDefinitions(), and tikz().
Green
const DGtal::Color DGtal::Color::Green static
Examples
geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 417 of file Color.h.
Referenced by drawCCP(), main(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testMeshGeneration(), testThicknessDefinitions(), and tikz().
Lime
const DGtal::Color DGtal::Color::Lime static
Definition at line 418 of file Color.h.
Referenced by tikz().
Magenta
const DGtal::Color DGtal::Color::Magenta static
Definition at line 421 of file Color.h.
Referenced by main(), and testAlphaThickSegmentConvexHullAndBox().
myAlpha
unsigned char DGtal::Color::myAlpha private
The opacity.
Definition at line 436 of file Color.h.
Referenced by operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
myBlue
unsigned char DGtal::Color::myBlue private
The blue component.
Definition at line 435 of file Color.h.
Referenced by Color(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
myGreen
unsigned char DGtal::Color::myGreen private
The green component.
Definition at line 434 of file Color.h.
Referenced by Color(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
myRed
unsigned char DGtal::Color::myRed private
The red component.
Definition at line 433 of file Color.h.
Referenced by Color(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
Navy
const DGtal::Color DGtal::Color::Navy static
Definition at line 425 of file Color.h.
Referenced by tikz().
None
const DGtal::Color DGtal::Color::None static
Examples
geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, and topology/ctopo-fillContours.cpp.
Definition at line 412 of file Color.h.
Referenced by addColorMapSample(), LibBoard::Board::drawArc(), LibBoard::Board::drawArrow(), LibBoard::Board::fillCircle(), LibBoard::Shape::filled(), LibBoard::Board::fillEllipse(), LibBoard::Board::fillPolyline(), LibBoard::Board::fillRectangle(), LibBoard::Board::fillTriangle(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::Polyline::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arc::flushPostscript(), main(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), DGtal::Shortcuts< TKSpace >::saveOFF(), LibBoard::Board::saveSVG(), LibBoard::Board::saveTikZ(), LibBoard::Board::State::State(), svg(), svgAlpha(), LibBoard::Shape::svgProperties(), testAlphaThickSegmentConvexHullAndBox(), testComputeInterior(), testMultiWidth(), testThicknessDefinitions(), and tikz().
Purple
const DGtal::Color DGtal::Color::Purple static
Definition at line 424 of file Color.h.
Referenced by testAlphaThickSegmentConvexHullAndBox(), testMeshReader(), testThicknessDefinitions(), and tikz().
Red
const DGtal::Color DGtal::Color::Red static
Examples
geometry/tools/exampleConvexHull2D.cpp, topology/ctopo-fillContours.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 416 of file Color.h.
Referenced by convexHull(), drawCCP(), drawPolygon(), laplacian(), main(), saveToObj(), specificTestLatticePolytope2D(), testAlphaThickSegmentConvexHullAndBox(), testBreadthFirstPropagation(), testCMAP(), testColor(), testComputeInterior(), testConvexHullCompThickness(), testDepthFirstPropagation(), testDisplay(), testDistancePropagation(), testMesh(), testMeshReader(), testShapes(), testThicknessDefinitions(), and tikz().
Silver
const DGtal::Color DGtal::Color::Silver static
Definition at line 423 of file Color.h.
Referenced by tikz().
White
const DGtal::Color DGtal::Color::White static
Definition at line 415 of file Color.h.
Referenced by main(), testGrayscaleColorMap(), testMesh(), testTickedColorMap(), and tikz().
Yellow
const DGtal::Color DGtal::Color::Yellow static
Examples
tutorial-examples/volDTGranulo.cpp.
Definition at line 422 of file Color.h.
Referenced by drawCCP(), main(), testAlphaThickSegmentConvexHullAndBox(), and testMeshGeneration().
The documentation for this class was generated from the following files:
Color.h
Color.cpp