DGtal: DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue > Class Template Reference
DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue > Class Template Reference
Aim: Functor that subsamples an initial domain by given a grid size and a shift vector. By this way, for a given point considered in a new domain, it allows to recover the point coordinates in the source domain. Such functor can be usefull to apply basic image subsampling in any dimensions by using ImageAdapter class.
#include <DGtal/kernel/BasicPointFunctors.h>
Public Types
typedef TDomain::Space Space
typedef TDomain::Size Size
typedef TDomain::Integer IntergerDom
typedef Space::Dimension Dimension
typedef Space::Point Point
Public Member Functions
BasicDomainSubSampler (const TDomain &aSourceDomain, const std::vector< TValue > &aGridSize, const Point &aGridShift)
Point operator() (const Point &aPoint) const
const TDomain & getSubSampledDomain ()
Private Attributes
TDomain mySourceDomain
TDomain myNewDomain
TDomain myGridSampleDomain
Point myGridShift
std::vector< TValue > myGridSize
Detailed Description
template<typename TDomain, typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size>
class DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >
Aim: Functor that subsamples an initial domain by given a grid size and a shift vector. By this way, for a given point considered in a new domain, it allows to recover the point coordinates in the source domain. Such functor can be usefull to apply basic image subsampling in any dimensions by using ImageAdapter class.
Description of template class 'BasicDomainSubSampler'
See also
tests/kernel/testBasicPointFunctors.cpp
Template Parameters
TDomain the type of the domain.
TInteger specifies the integer number type used to define the space.
TValue specify the type of the value which define the grid size (generally type int (default) when subsampling with large grid size and double to re sampling with grid size less than 1).
Examples
images/imageBasicSubsampling.cpp.
Definition at line 637 of file BasicPointFunctors.h.
Member Typedef Documentation
Dimension
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> typedef Space::Dimension DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::Dimension
Definition at line 643 of file BasicPointFunctors.h.
IntergerDom
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> typedef TDomain::Integer DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::IntergerDom
Definition at line 642 of file BasicPointFunctors.h.
Point
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> typedef Space::Point DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::Point
Definition at line 644 of file BasicPointFunctors.h.
Size
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> typedef TDomain::Size DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::Size
Definition at line 641 of file BasicPointFunctors.h.
Space
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> typedef TDomain::Space DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::Space
Definition at line 640 of file BasicPointFunctors.h.
Constructor & Destructor Documentation
BasicDomainSubSampler()
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::BasicDomainSubSampler (const TDomain & aSourceDomain, const std::vector< TValue > & aGridSize, const Point & aGridShift) inline
Constructor. Construct the functor from a source domain, a grid size, and a shift vector. The points of the resulting domain are defined as the upper left of the sampling grid.
Parameters
aSourceDomain the source domain.
aGridSize the subsampling grid size.
aGridShift the shift applied to the sampling grid.
Definition at line 657 of file BasicPointFunctors.h.
                                                   : mySourceDomain(aSourceDomain),
                                                     myGridShift(aGridShift),
                                                     myGridSize(aGridSize)
    {
      Point domainUpperBound=aSourceDomain.upperBound();
      Point domainLowerBound=aSourceDomain.lowerBound();
      for (Dimension dim=0; dim< Space::dimension; dim++){
        domainLowerBound[dim] = static_cast<IntergerDom>(floor(NumberTraits<IntergerDom>::castToDouble(domainLowerBound[dim]) /
                                                               NumberTraits<TValue>::castToDouble( aGridSize[dim] )));
        domainUpperBound[dim] = static_cast<IntergerDom>(floor(NumberTraits<IntergerDom>::castToDouble(domainUpperBound[dim]) /
                                                               NumberTraits<TValue>::castToDouble( aGridSize[dim] )));
      }
      myNewDomain = TDomain(domainLowerBound,
                            domainUpperBound);
      Point upperGrid;
      for (Dimension dim=0; dim < Space::dimension; dim++)
        upperGrid[dim] = myGridSize[dim];
      myGridSampleDomain = TDomain(Point::diagonal(0), upperGrid);
    };
References DGtal::PointVector< dim, Integer >::diagonal(), dim, DGtal::SpaceND< dim, TInteger >::dimension, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSampleDomain, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSize, and DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myNewDomain.
Member Function Documentation
getSubSampledDomain()
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> const TDomain & DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::getSubSampledDomain () inline
This method can be usefull to directely recover the new domain associated to the resulting subsampled domain.
Returns
the new subsampled domain.
Examples
images/imageBasicSubsampling.cpp.
Definition at line 726 of file BasicPointFunctors.h.
{
      return myNewDomain;
    }
References DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myNewDomain.
Referenced by main().
operator()()
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> Point DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator() (const Point & aPoint) const inline
The operator computes the coordinates of the point in the subsampled domain. By default it returns the first lower point of the window associated to the sampling grid. If the resulting point is outside the source domain it scans this window and returns a point belonging to the source domain. If such a point does not exits it return the point with null coordinates.
Parameters
aPoint a point which should belong to the new domain.
Returns
the point to be taken in the subsampled domain.
Definition at line 694 of file BasicPointFunctors.h.
    {
      Point ptRes = Point::diagonal(0);
      if(!myNewDomain.isInside(aPoint)){
        trace.error() << " The point is not in the source domain: "<<  aPoint << std::endl;
        return ptRes;
      }
      for (Dimension dim=0; dim< Space::dimension; dim++){
        ptRes[dim] = static_cast<TInteger>(floor(NumberTraits<TInteger>::castToDouble(aPoint[dim])*
                                                 NumberTraits<TValue>::castToDouble(myGridSize[dim])));
      }
      ptRes +=myGridShift;
      if(!mySourceDomain.isInside(ptRes)){
        // we are looking for a point inside the domain
        for(typename TDomain::ConstIterator it = myGridSampleDomain.begin();
            it!= myGridSampleDomain.end(); it++){
          if (mySourceDomain.isInside(ptRes+(*it)))
            return ptRes+(*it);
        }
      }
      return ptRes;
    }
References aPoint(), DGtal::PointVector< dim, Integer >::diagonal(), dim, DGtal::SpaceND< dim, TInteger >::dimension, DGtal::Trace::error(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSampleDomain, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridShift, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSize, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myNewDomain, DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::mySourceDomain, and DGtal::trace.
Field Documentation
myGridSampleDomain
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> TDomain DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSampleDomain private
Definition at line 734 of file BasicPointFunctors.h.
Referenced by DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::BasicDomainSubSampler(), and DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()().
myGridShift
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> Point DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridShift private
Definition at line 735 of file BasicPointFunctors.h.
Referenced by DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()().
myGridSize
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> std::vector<TValue> DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myGridSize private
Definition at line 736 of file BasicPointFunctors.h.
Referenced by DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::BasicDomainSubSampler(), and DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()().
myNewDomain
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> TDomain DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::myNewDomain private
Definition at line 732 of file BasicPointFunctors.h.
Referenced by DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::BasicDomainSubSampler(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::getSubSampledDomain(), and DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()().
mySourceDomain
template<typename TDomain , typename TInteger = DGtal::int32_t, typename TValue = typename TDomain::Size> TDomain DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::mySourceDomain private
Definition at line 731 of file BasicPointFunctors.h.
Referenced by DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()().
The documentation for this class was generated from the following file:
BasicPointFunctors.h