DGtal: curvature-measures-nc-3d.cpp File Reference
curvature-measures-nc-3d.cpp File Reference
DGtal Examples
#include <iostream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/shapes/SurfaceMeshHelper.h"
#include "DGtal/geometry/meshes/NormalCycleComputer.h"
#include "DGtal/io/writers/SurfaceMeshWriter.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/io/colormaps/QuantifiedColorMap.h"
Functions
DGtal::GradientColorMap< double > makeColorMap (double min_value, double max_value)
[curvature-measures-Includes]
void usage (int argc, char *argv[])
int main (int argc, char *argv[])
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/10/25
An example file named curvature-measures-nc-3d.
This file is part of the DGtal library.
Definition in file curvature-measures-nc-3d.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
[curvature-measures-Typedefs]
[curvature-measures-Typedefs]
[curvature-measures-SurfaceMesh]
[curvature-measures-SurfaceMesh]
[curvature-measures-CNC]
[curvature-measures-CNC]
[curvature-measures-estimations]
[curvature-measures-estimations]
[curvature-measures-check]
[curvature-measures-check]
[curvature-measures-output]
[curvature-measures-output]
Definition at line 120 of file curvature-measures-nc-3d.cpp.
{
  if ( argc <= 1 )
    {
      usage( argc, argv );
      return 0;
    }
  using namespace DGtal;
  using namespace DGtal::Z3i;
  typedef SurfaceMesh< RealPoint, RealVector >         SM;
  typedef NormalCycleComputer< RealPoint, RealVector > NC;
  typedef SurfaceMeshHelper< RealPoint, RealVector >   SMH;
  std::string input = argv[ 1 ];
  int    m = argc > 2 ? atoi( argv[ 2 ] ) : 20;  // nb latitude points
  int    n = argc > 3 ? atoi( argv[ 3 ] ) : 20;  // nb longitude points
  double R = argc > 4 ? atof( argv[ 4 ] ) : 0.5; // radius of measuring ball
  SM smesh;
  double exp_H_min = 0.0;
  double exp_H_max = 0.0;
  double exp_G_min = 0.0;
  double exp_G_max = 0.0;
  if ( input == "torus" )
    {
      const double big_radius   = 3.0;
      const double small_radius = 1.0;
      smesh = SMH::makeTorus( big_radius, small_radius,
                              RealPoint { 0.0, 0.0, 0.0 }, m, n, 0,
                              SMH::NormalsType::VERTEX_NORMALS );
      exp_H_min = ( 0.5 / ( small_radius - big_radius ) + 0.5 / small_radius );
      exp_H_max = ( 0.5 / ( big_radius + small_radius ) + 0.5 / small_radius );
      exp_G_min = ( 1.0 / ( small_radius - big_radius ) * 1.0 / small_radius );
      exp_G_max = ( 1.0 / ( big_radius + small_radius ) * 1.0 / small_radius );
    }
  else if ( input == "sphere" )
    {
      const double radius = 2.0;
      smesh = SMH::makeSphere( radius, RealPoint { 0.0, 0.0, 0.0 }, m, n,
                               SMH::NormalsType::VERTEX_NORMALS );
      exp_H_min = 1.0 / radius;
      exp_H_max = 1.0 / radius;
      exp_G_min = 1.0 / ( radius * radius );
      exp_G_max = 1.0 / ( radius * radius );
    }
  else if ( input == "lantern" )
    {
      const double radius = 2.0;
      smesh = SMH::makeLantern( radius, 1.0, RealPoint { 0.0, 0.0, 0.0 }, m, n,
                                SMH::NormalsType::VERTEX_NORMALS );
      exp_H_min = 0.5 / radius;
      exp_H_max = 0.5 / radius;
      exp_G_min = 0.0;
      exp_G_max = 0.0;
    }
  // builds a NormalCycleComputer object onto the mesh
  NC nc( smesh );
  // computes area, mean and Gaussian curvature measures
  auto mu0 = nc.computeMu0();
  auto mu1 = nc.computeMu1();
  auto mu2 = nc.computeMu2();
  // estimates mean (H) and Gaussian (G) curvatures by measure normalization.
  std::vector< double > H( smesh.nbFaces() );
  std::vector< double > G( smesh.nbFaces() );
  for ( auto f = 0; f < smesh.nbFaces(); ++f )
    {
      const auto b    = smesh.faceCentroid( f );
      const auto area = mu0.measure( b, R, f );
      H[ f ] = nc.meanCurvature    ( area, mu1.measure( b, R, f ) );
      G[ f ] = nc.GaussianCurvature( area, mu2.measure( b, R, f ) );
    }
  auto H_min_max = std::minmax_element( H.cbegin(), H.cend() );
  auto G_min_max = std::minmax_element( G.cbegin(), G.cend() );
  std::cout << "Expected mean curvatures:"
            << " min=" << exp_H_min << " max=" << exp_H_max
            << std::endl;
  std::cout << "Computed mean curvatures:"
            << " min=" << *H_min_max.first << " max=" << *H_min_max.second
            << std::endl;
  std::cout << "Expected Gaussian curvatures:"
            << " min=" << exp_G_min << " max=" << exp_G_max
            << std::endl;
  std::cout << "Computed Gaussian curvatures:"
            << " min=" << *G_min_max.first << " max=" << *G_min_max.second
            << std::endl;
  typedef SurfaceMeshWriter< RealPoint, RealVector > SMW;
  const auto colormapH = makeQuantifiedColorMap( makeColorMap( -0.625, 0.625 ) );
  const auto colormapG = makeQuantifiedColorMap( makeColorMap( -0.625, 0.625 ) );
  auto colorsH = SMW::Colors( smesh.nbFaces() );
  auto colorsG = SMW::Colors( smesh.nbFaces() );
  for ( auto i = 0; i < smesh.nbFaces(); i++ )
    {
      colorsH[ i ] = colormapH( H[ i ] );
      colorsG[ i ] = colormapG( G[ i ] );
    }
  SMW::writeOBJ( "example-nc-H", smesh, colorsH );
  SMW::writeOBJ( "example-nc-G", smesh, colorsG );
  return 0;
}
References makeColorMap().
makeColorMap()
DGtal::GradientColorMap< double > makeColorMap (double min_value, double max_value)
[curvature-measures-Includes]
[curvature-measures-Includes]
Definition at line 93 of file curvature-measures-nc-3d.cpp.
{
  DGtal::GradientColorMap< double > gradcmap( min_value, max_value );
  gradcmap.addColor( DGtal::Color( 0, 0, 255 ) );
  gradcmap.addColor( DGtal::Color( 0, 255, 255 ) );
  gradcmap.addColor( DGtal::Color( 255, 255, 255 ) );
  gradcmap.addColor( DGtal::Color( 255, 255, 0 ) );
  gradcmap.addColor( DGtal::Color( 255, 0, 0 ) );
  return gradcmap;
}
References DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::addColor().
Referenced by main().
usage()
void usage (int argc, char * argv[])
Definition at line 104 of file curvature-measures-nc-3d.cpp.
{
  std::cout << "Usage: " << std::endl
            << "\t" << argv[ 0 ] << " <shape> <m> <n> <R>" << std::endl
            << std::endl
            << "Computation of mean and Gaussian curvatures on a shape, " << std::endl
            << "using Normal cycle curvature measures (based on the"     << std::endl
            << "theory of Normal cycle)"                                 << std::endl
            << "- builds a <shape> in {torus,lantern,sphere}, with     " << std::endl
            << "  <m> latitude points and <n> longitude points."         << std::endl
            << "- <R> is the radius of the measuring balls."             << std::endl
            << "It produces several OBJ files to display mean and"       << std::endl
            << "Gaussian curvature estimation results: `example-cnc-H.obj`" << std::endl
            << "and `example-cnc-G.obj` as well as the associated MTL file." << std::endl;
}