DGtal: fileGridCurveRanges.cpp File Reference
fileGridCurveRanges.cpp File Reference
DGtal Examples
An example of reading and displaying a gridcurve and its ranges.
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/boards/Board2D.h"
Functions
int main ()
Detailed Description
An example of reading and displaying a gridcurve and its ranges.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr)
Date
2010/10/17
This file is part of the DGtal library.
Definition in file fileGridCurveRanges.cpp.
Function Documentation
main()
int main (void)
[fileGridCurveRanges-declaration]
[fileGridCurveRanges-declaration]
[fileGridCurveRanges-ex]
[fileGridCurveRanges-ex]
[fileGridCurveRanges-read]
[fileGridCurveRanges-read]
[fileGridCurveRanges-board]
[fileGridCurveRanges-board]
[fileGridCurveRanges-displayCurve]
[fileGridCurveRanges-displayCurve]
[fileGridCurveRanges-displayInnerPoints]
[fileGridCurveRanges-displayInnerPoints]
[fileGridCurveRanges-displayIncidentPoints]
[fileGridCurveRanges-displayIncidentPoints]
Definition at line 51 of file fileGridCurveRanges.cpp.
{
  Z2i::Curve c;
  std::string square = examplesPath + "samples/smallSquare.dat";
  std::fstream inputStream;
  inputStream.open (square.c_str(), std::ios::in);
  c.initFromVectorStream(inputStream);
  inputStream.close();
  DGtal::Board2D aBoard;
  //displaying domain
  Z2i::Point low(-1,-1);
  Z2i::Point up(3,3);
  Z2i::Domain aDomain( low,up );
  aBoard << SetMode(aDomain.className(), "Paving") << aDomain;
  aBoard << c;
  aBoard.saveEPS("DisplayGridCurveTuto.eps");
  Z2i::Curve::InnerPointsRange r1 = c.getInnerPointsRange();
  aBoard << r1;
  aBoard.saveEPS("DisplayInnerPointsTuto.eps");
  Z2i::Curve::IncidentPointsRange r2 = c.getIncidentPointsRange();
  aBoard << r2;
  aBoard.saveEPS("DisplayIncidentPointsTuto.eps");
  return 0;
}
References DGtal::HyperRectDomain< TSpace >::className(), DGtal::GridCurve< TKSpace >::getIncidentPointsRange(), DGtal::GridCurve< TKSpace >::getInnerPointsRange(), DGtal::GridCurve< TKSpace >::initFromVectorStream(), and LibBoard::Board::saveEPS().