DGtal: greedy-plane-segmentation-ex3.cpp File Reference
greedy-plane-segmentation-ex3.cpp File Reference
DGtal Examples
#include <iostream>
#include <vector>
#include <set>
#include <map>
#include <queue>
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/Display3D.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/io/DrawWithDisplay3DModifier.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/DigitalSetBoundary.h"
#include "DGtal/graph/BreadthFirstVisitor.h"
#include "DGtal/geometry/surfaces/COBANaivePlaneComputer.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
Typedefs
typedef DGtal::int64_t InternalInteger
typedef COBANaivePlaneComputer< Z3, InternalInteger > NaivePlaneComputer
typedef DigitalSetBoundary< KSpace, DigitalSet > MyDigitalSurfaceContainer
typedef DigitalSurface< MyDigitalSurfaceContainer > MyDigitalSurface
typedef MyDigitalSurface::ConstIterator ConstIterator
typedef MyDigitalSurface::Vertex Vertex
typedef MyDigitalSurface::SurfelSet SurfelSet
typedef SurfelSet::iterator SurfelSetIterator
typedef BreadthFirstVisitor< MyDigitalSurface > Visitor
Functions
bool operator< (const VertexSize &vs1, const VertexSize &vs2)
int main (int argc, char **argv)
[greedy-plane-segmentation-ex3-typedefs]
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/10/01
An example file named greedy-plane-segmentation-ex3.
This file is part of the DGtal library.
Definition in file greedy-plane-segmentation-ex3.cpp.
Typedef Documentation
ConstIterator
typedef MyDigitalSurface::ConstIterator ConstIterator
Definition at line 65 of file greedy-plane-segmentation-ex3.cpp.
InternalInteger
typedef DGtal::int64_t InternalInteger
Definition at line 59 of file greedy-plane-segmentation-ex3.cpp.
MyDigitalSurface
typedef DigitalSurface<MyDigitalSurfaceContainer> MyDigitalSurface
Definition at line 64 of file greedy-plane-segmentation-ex3.cpp.
MyDigitalSurfaceContainer
typedef DigitalSetBoundary<KSpace,DigitalSet> MyDigitalSurfaceContainer
Definition at line 63 of file greedy-plane-segmentation-ex3.cpp.
NaivePlaneComputer
typedef COBANaivePlaneComputer<Z3,InternalInteger> NaivePlaneComputer
Definition at line 60 of file greedy-plane-segmentation-ex3.cpp.
SurfelSet
typedef MyDigitalSurface::SurfelSet SurfelSet
Definition at line 67 of file greedy-plane-segmentation-ex3.cpp.
SurfelSetIterator
typedef SurfelSet::iterator SurfelSetIterator
Definition at line 68 of file greedy-plane-segmentation-ex3.cpp.
Vertex
typedef MyDigitalSurface::Vertex Vertex
Definition at line 66 of file greedy-plane-segmentation-ex3.cpp.
Visitor
typedef BreadthFirstVisitor<MyDigitalSurface> Visitor
Definition at line 69 of file greedy-plane-segmentation-ex3.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[greedy-plane-segmentation-ex3-typedefs]
[greedy-plane-segmentation-ex3-parseCommandLine]
[greedy-plane-segmentation-ex3-parseCommandLine]
[greedy-plane-segmentation-ex3-loadVolume]
[greedy-plane-segmentation-ex3-loadVolume]
[greedy-plane-segmentation-ex3-makeSurface]
[greedy-plane-segmentation-ex3-makeSurface]
[greedy-plane-segmentation-ex3-segment]
[greedy-plane-segmentation-ex3-segment]
[greedy-plane-segmentation-ex3-visualization]
[greedy-plane-segmentation-ex3-visualization]
[greedy-plane-segmentation-ex3-freeMemory]
[greedy-plane-segmentation-ex3-freeMemory]
Definition at line 95 of file greedy-plane-segmentation-ex3.cpp.
{
   trace.info() << "Segments the surface at given threshold within given volume into digital planes of rational width num/den." << std::endl;
  // Setting default options: ----------------------------------------------
  // input file used:
   string inputFilename =   examplesPath + "samples/Al.100.vol" ;
    trace.info() << "input file used " << inputFilename << std::endl;
  // parameter threshold
    unsigned int threshold = 0;
    trace.info() << "the value that defines the isosurface in the image (an integer between 0 and 255)= " << threshold<< std::endl;
   // parameter widthNum
   unsigned int widthNum = 1;
   trace.info() << "the numerator of the rational width (a non-null integer) =" << widthNum<< std::endl;
   // parameter widthDen
   unsigned int widthDen = 1;
   trace.info() << "the denominator of the rational width (a non-null integer)= " << widthDen<< std::endl;
  QApplication application(argc,argv);
  typedef ImageSelector < Domain, int>::Type Image;
  Image image = VolReader<Image>::importVol(inputFilename);
  DigitalSet set3d (image.domain());
  SetFromImage<DigitalSet>::append<Image>(set3d, image, threshold,255);
  trace.beginBlock( "Set up digital surface." );
  // We initializes the cellular grid space used for defining the
  // digital surface.
  KSpace ks;
  bool ok = ks.init( set3d.domain().lowerBound(),
                     set3d.domain().upperBound(), true );
  if ( ! ok ) std::cerr << "[KSpace.init] Failed." << std::endl;
  SurfelAdjacency<KSpace::dimension> surfAdj( true ); // interior in all directions.
  MyDigitalSurfaceContainer* ptrSurfContainer =
    new MyDigitalSurfaceContainer( ks, set3d, surfAdj );
  MyDigitalSurface digSurf( ptrSurfContainer ); // acquired
  trace.endBlock();
  Point p;
  Dimension axis;
  unsigned int j = 0;
  unsigned int nb = digSurf.size();
  // First pass to find biggest planes.
  trace.beginBlock( "1) Segmentation first pass. Computes all planes so as to sort vertices by the plane size." );
  std::map<Vertex,unsigned int> v2size;
  NaivePlaneComputer planeComputer;
  std::priority_queue<VertexSize> Q;
  std::vector<Point> layer;
  for ( ConstIterator it = digSurf.begin(), itE= digSurf.end(); it != itE; ++it )
    {
      if ( ( (++j) % 50 == 0 ) || ( j == nb ) ) trace.progressBar( j, nb );
      Vertex v = *it;
      axis = ks.sOrthDir( v );
      planeComputer.init( axis, 500, widthNum, widthDen );
      // The visitor takes care of all the breadth-first traversal.
      Visitor visitor( digSurf, v );
      layer.clear();
      Visitor::Size currentSize = visitor.current().second;
      while ( ! visitor.finished() )
        {
          Visitor::Node node = visitor.current();
          v = node.first;
          axis = ks.sOrthDir( v );
          p = ks.sCoords( ks.sDirectIncident( v, axis ) );
          if ( node.second != currentSize )
            {
              // std::cerr << "Layer " << currentSize << ", size=" << layer.size() << std::endl;
              bool isExtended = planeComputer.extend( layer.begin(), layer.end() );
              if ( ! isExtended )
                break;
              layer.clear();
              currentSize = node.second;
            }
          layer.push_back( p );
          visitor.expand();
        }
      // std::cerr << v << " -> " << planeComputer.size() << std::endl;
      Q.push( VertexSize( v, planeComputer.size() ) );
    }
  trace.endBlock();
  trace.beginBlock( "2) Segmentation second pass. Visits vertices from the one with biggest plane to the one with smallest plane." );
  std::set<Vertex> processedVertices;
  std::map<Vertex,SegmentedPlane*> v2plane;
  std::vector<SegmentedPlane*> segmentedPlanes;
  j = 0;
  while ( ! Q.empty() )
    {
      if ( ( (++j) % 50 == 0 ) || ( j == nb ) ) trace.progressBar( j, nb );
      Vertex v = Q.top().v;
      Q.pop();
      if ( processedVertices.find( v ) != processedVertices.end() ) // already in set
        continue; // process to next vertex
      SegmentedPlane* ptrSegment = new SegmentedPlane;
      segmentedPlanes.push_back( ptrSegment ); // to delete them afterwards.
      axis = ks.sOrthDir( v );
      ptrSegment->plane.init( axis, 500, widthNum, widthDen );
      // The visitor takes care of all the breadth-first traversal.
      Visitor visitor( digSurf, v );
      while ( ! visitor.finished() )
        {
          Visitor::Node node = visitor.current();
          v = node.first;
          if ( processedVertices.find( v ) == processedVertices.end() )
            { // Vertex is not in processedVertices
              axis = ks.sOrthDir( v );
              p = ks.sCoords( ks.sDirectIncident( v, axis ) );
              bool isExtended = ptrSegment->plane.extend( p );
              if ( isExtended )
                { // surfel is in plane.
                  processedVertices.insert( v );
                  v2plane[ v ] = ptrSegment;
                  visitor.expand();
                }
              else // surfel is not in plane and should not be used in the visit.
                visitor.ignore();
            }
          else // surfel is already in some plane.
            visitor.ignore();
        }
      // Assign random color for each plane.
      ptrSegment->color = Color( rand() % 256, rand() % 256, rand() % 256, 255 );
    }
  trace.endBlock();
  Viewer3D<> viewer( ks );
  viewer.show();
  Color col( 255, 255, 120 );
  for ( std::map<Vertex,SegmentedPlane*>::const_iterator
          it = v2plane.begin(), itE = v2plane.end();
        it != itE; ++it )
    {
      viewer << CustomColors3D( it->second->color, it->second->color );
      viewer << ks.unsigns( it->first );
    }
  viewer << Viewer3D<>::updateDisplay;
  for ( std::vector<SegmentedPlane*>::iterator
          it = segmentedPlanes.begin(), itE = segmentedPlanes.end();
        it != itE; ++it )
    delete *it;
  segmentedPlanes.clear();
  v2plane.clear();
  return application.exec();
}
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::begin(), DGtal::Trace::beginBlock(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::end(), DGtal::Trace::endBlock(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::extend(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::ignore(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::init(), DGtal::Trace::progressBar(), DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirectIncident(), DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::size(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::size(), DGtal::KhalimskySpaceND< dim, TInteger >::sOrthDir(), DGtal::trace, and DGtal::KhalimskySpaceND< dim, TInteger >::unsigns().
operator<()
bool operator< (const VertexSize & vs1, const VertexSize & vs2) inline
Definition at line 87 of file greedy-plane-segmentation-ex3.cpp.
{
  return vs1.size < vs2.size;
}