DGtal: imageGridCurveEstimator.cpp File Reference
imageGridCurveEstimator.cpp File Reference
DGtal Examples
An example of extracting a grid curve from an image iso-contour and estimating its length.
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/base/BasicFunctors.h"
#include "DGtal/kernel/BasicPointPredicates.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/curves/estimation/DSSLengthEstimator.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/geometry/curves/GreedySegmentation.h"
Functions
int main ()
Detailed Description
An example of extracting a grid curve from an image iso-contour and estimating its length.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr)
Date
2010/10/17
This file is part of the DGtal library.
Definition in file imageGridCurveEstimator.cpp.
Function Documentation
main()
int main (void)
[imageGridCurveEstimator-predicate]
[imageGridCurveEstimator-predicate]
[imageGridCurveEstimator-prepareTracking]
[imageGridCurveEstimator-prepareTracking]
[imageGridCurveEstimator-tracking]
[imageGridCurveEstimator-tracking]
[imageGridCurveEstimator-instantiation]
[imageGridCurveEstimator-instantiation]
[imageGridCurveEstimator-getRange]
[imageGridCurveEstimator-getRange]
[imageGridCurveEstimator-lengthEstimation]
[imageGridCurveEstimator-lengthEstimation]
Definition at line 69 of file imageGridCurveEstimator.cpp.
{
  //image import
  typedef DGtal::ImageContainerBySTLVector< Z2i::Domain, int> Image;
  std::string filename =  examplesPath + "samples/contourS.pgm";
  Image image = DGtal::PGMReader<Image>::importPGM(filename);
  //predicate from the image
  typedef DGtal::functors::IntervalThresholder<Image::Value> Binarizer;
  Binarizer b(1, 135);
  PointFunctorPredicate<Image,Binarizer> predicate(image, b);
  Z2i::KSpace ks;                                            //Khalimsky space
  ks.init( image.domain().lowerBound(), image.domain().upperBound(), true );
  SurfelAdjacency<2> sAdj( true );                           //adjacency
  //extraction of all the contours
  std::vector< std::vector< Z2i::SCell > > contours;
  Surfaces<Z2i::KSpace>
    ::extractAll2DSCellContours( contours, ks, sAdj, predicate );
  if (contours.size() > 0)
  {
    //init grid curve from the first retrieved contour
    Z2i::Curve c;
    c.initFromSCellsVector( contours.at(1) );
    //range of points
    typedef Z2i::Curve::PointsRange Range;
    Range r = c.getPointsRange();
    //length estimation based on a DSS segmentation
    DSSLengthEstimator< Range::ConstCirculator > DSSlength;
    trace.info() << "Length: " << DSSlength.eval(r.c(), r.c(), 1.) << std::endl;
    //DSS segmentation display
    typedef ArithmeticalDSSComputer<Range::ConstCirculator,int,4> SegmentComputer;
    typedef GreedySegmentation<SegmentComputer> Segmentation;
    Segmentation theSegmentation( r.c(), r.c(), SegmentComputer() );
    Segmentation::SegmentComputerIterator i = theSegmentation.begin();
    Segmentation::SegmentComputerIterator end = theSegmentation.end();
    DGtal::Board2D aBoard;
    aBoard << SetMode("PointVector", "Grid");
    for ( ; i != end; ++i) {
      SegmentComputer::Primitive dss = i->primitive();
      aBoard << SetMode(dss.className(), "Points") << dss;
      aBoard << SetMode(dss.className(), "BoundingBox") << dss;
    }
    aBoard.saveEPS("DisplayDSSSegmentationTuto3.eps");
  } else trace.info() << "no contour" << std::endl;
  return 0;
}
References DGtal::SaturatedSegmentation< TSegmentComputer >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::className(), DGtal::SaturatedSegmentation< TSegmentComputer >::end(), DGtal::DSSLengthEstimator< TConstIterator >::eval(), DGtal::GridCurve< TKSpace >::getPointsRange(), image(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GridCurve< TKSpace >::initFromSCellsVector(), LibBoard::Board::saveEPS(), and DGtal::trace.