DGtal: DGtal::functions::setops Namespace Reference
DGtal::functions::setops Namespace Reference
Functions
template<typename Container >
Container & operator-= (Container &S1, const Container &S2)
template<typename Container >
Container operator- (const Container &S1, const Container &S2)
template<typename Container >
Container operator| (const Container &S1, const Container &S2)
template<typename Container >
Container & operator|= (Container &S1, const Container &S2)
template<typename Container >
Container operator& (const Container &S1, const Container &S2)
template<typename Container >
Container & operator&= (Container &S1, const Container &S2)
template<typename Container >
Container operator^ (const Container &S1, const Container &S2)
template<typename Container >
Container & operator^= (Container &S1, const Container &S2)
Detailed Description
Contains set operator union |, intersection &, difference -, symmetric difference ^.
Function Documentation
operator&()
template<typename Container > Container DGtal::functions::setops::operator& (const Container & S1, const Container & S2) inline
Set intersection operation. Returns the set \(S1 \cap S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \cap S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1332 of file SetFunctions.h.
      {
        return makeIntersection( S1, S2 );
      }
References DGtal::functions::makeIntersection(), and operator&().
Referenced by operator&().
operator&=()
template<typename Container > Container & DGtal::functions::setops::operator&= (Container & S1, const Container & S2) inline
Set intersection operation. Updates the set S1 as \(S1 \cap S2 \).
Parameters
[in,out] S1 an input set, \(S1 \cap S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1346 of file SetFunctions.h.
      {
        return assignIntersection( S1, S2 );
      }
References DGtal::functions::assignIntersection().
operator-()
template<typename Container > Container DGtal::functions::setops::operator- (const Container & S1, const Container & S2) inline
Set difference operation. Returns the difference of S1 - S2.
Parameters
[in] S1 an input set
[in] S2 another input set.
Returns
the set S1 - S2.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1288 of file SetFunctions.h.
      {
        return makeDifference( S1, S2 );
      }
References DGtal::functions::makeDifference(), and operator-().
Referenced by operator-().
operator-=()
template<typename Container > Container & DGtal::functions::setops::operator-= (Container & S1, const Container & S2) inline
Set difference operation. Updates the set S1 as S1 - S2.
Parameters
[in,out] S1 an input set, S1 - S2 as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1272 of file SetFunctions.h.
      {
        return assignDifference( S1, S2 );
      }
References DGtal::functions::assignDifference().
operator^()
template<typename Container > Container DGtal::functions::setops::operator^ (const Container & S1, const Container & S2) inline
Set symmetric difference operation. Returns the set \(S1 \Delta S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \Delta S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1362 of file SetFunctions.h.
      {
        return makeSymmetricDifference( S1, S2 );
      }
References DGtal::functions::makeSymmetricDifference(), and operator^().
Referenced by operator^().
operator^=()
template<typename Container > Container & DGtal::functions::setops::operator^= (Container & S1, const Container & S2) inline
Set symmetric difference operation. Updates the set S1 as \(S1 \Delta S2 \).
Parameters
[in,out] S1 an input set, \(S1 \Delta S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1378 of file SetFunctions.h.
      {
        return assignSymmetricDifference( S1, S2 );
      }
References DGtal::functions::assignSymmetricDifference().
operator|()
template<typename Container > Container DGtal::functions::setops::operator| (const Container & S1, const Container & S2) inline
Set union operation. Returns the set \(S1 \cup S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \cup S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1303 of file SetFunctions.h.
      {
        return makeUnion( S1, S2 );
      }
References DGtal::functions::makeUnion().
operator|=()
template<typename Container > Container & DGtal::functions::setops::operator|= (Container & S1, const Container & S2) inline
Set union operation. Updates the set S1 as \(S1 \cup S2 \).
Parameters
[in,out] S1 an input set, \(S1 \cup S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1317 of file SetFunctions.h.
      {
        return assignUnion( S1, S2 );
      }
References DGtal::functions::assignUnion().