DGtal: obj-curvature-measures-icnc-3d.cpp File Reference
obj-curvature-measures-icnc-3d.cpp File Reference
DGtal Examples
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/shapes/SurfaceMeshHelper.h"
#include "DGtal/geometry/meshes/CorrectedNormalCurrentComputer.h"
#include "DGtal/io/readers/SurfaceMeshReader.h"
#include "DGtal/io/writers/SurfaceMeshWriter.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/io/colormaps/QuantifiedColorMap.h"
Functions
DGtal::GradientColorMap< double > makeColorMap (double min_value, double max_value)
[curvature-measures-Includes]
void usage (int argc, char *argv[])
int main (int argc, char *argv[])
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/10/25
An example file named obj-curvature-measures-icnc-3d.
This file is part of the DGtal library.
Definition in file obj-curvature-measures-icnc-3d.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
[curvature-measures-Typedefs]
[curvature-measures-Typedefs]
[curvature-measures-SurfaceMesh]
[curvature-measures-SurfaceMesh]
[curvature-measures-CNC]
[curvature-measures-CNC]
[curvature-measures-estimations]
[curvature-measures-estimations]
[curvature-measures-check]
[curvature-measures-check]
[curvature-measures-output]
[curvature-measures-output]
Definition at line 108 of file obj-curvature-measures-icnc-3d.cpp.
{
  if ( argc <= 1 )
    {
      usage( argc, argv );
      return 0;
    }
  using namespace DGtal;
  using namespace DGtal::Z3i;
  typedef SurfaceMesh< RealPoint, RealVector >                    SM;
  typedef CorrectedNormalCurrentComputer< RealPoint, RealVector > CNC;
  typedef SurfaceMeshReader< RealPoint, RealVector >              SMR;
  // OBJ file
  std::string input = argv[ 1 ];
  const double    R = argc > 2 ? atof( argv[ 2 ] ) : 0.0; // radius of measuring ball
  const double Hmax = argc > 3 ? atof( argv[ 3 ] ) : 5.0; // range mean curvature colormap
  const double Gmax = argc > 4 ? atof( argv[ 4 ] ) : 0.5*Hmax*Hmax; // range Gaussian curvature colormap
  SM smesh;
  std::ifstream obj_stream( input.c_str() );
  bool ok = SMR::readOBJ( obj_stream, smesh );
  if ( !ok )
    {
      trace.error() <<  "Unable to read file <" << input.c_str() << ">" << std::endl;
      return 1;
    }
  RealPoint lo = smesh.position( 0 );
  RealPoint up = smesh.position( 0 );
  for ( const auto& p : smesh.positions() )
    lo = lo.inf( p ), up = up.sup( p );
  const auto diameter = (up - lo).norm();
  trace.info() << "Mesh=" << smesh
               << " diameter=" << diameter
               << " radius=" << R << std::endl;
  // builds a CorrectedNormalCurrentComputer object onto the SurfaceMesh object
  CNC cnc( smesh );
  // computes normals if necessary
  if ( smesh.vertexNormals().empty() )
    {
      if ( smesh.faceNormals().empty() )
        smesh.computeFaceNormalsFromPositions();
      smesh.computeVertexNormalsFromFaceNormals();
    }
  // computes area, mean and Gaussian curvature measures
  auto mu0 = cnc.computeMu0();
  auto mu1 = cnc.computeMu1();
  auto mu2 = cnc.computeMu2();
  // estimates mean (H) and Gaussian (G) curvatures by measure normalization.
  std::vector< double > H( smesh.nbFaces() );
  std::vector< double > G( smesh.nbFaces() );
  for ( auto f = 0; f < smesh.nbFaces(); ++f )
    {
      const auto b    = smesh.faceCentroid( f );
      const auto area = mu0.measure( b, R, f );
      H[ f ] = cnc.meanCurvature    ( area, mu1.measure( b, R, f ) );
      G[ f ] = cnc.GaussianCurvature( area, mu2.measure( b, R, f ) );
    }
  auto H_min_max = std::minmax_element( H.cbegin(), H.cend() );
  auto G_min_max = std::minmax_element( G.cbegin(), G.cend() );
  std::cout << "Computed mean curvatures:"
            << " min=" << *H_min_max.first << " max=" << *H_min_max.second
            << std::endl;
  std::cout << "Computed Gaussian curvatures:"
            << " min=" << *G_min_max.first << " max=" << *G_min_max.second
            << std::endl;
  typedef SurfaceMeshWriter< RealPoint, RealVector > SMW;
  const auto colormapH = makeQuantifiedColorMap( makeColorMap( -Hmax, Hmax ) );
  const auto colormapG = makeQuantifiedColorMap( makeColorMap( -Gmax, Gmax ) );
  auto colorsH = SMW::Colors( smesh.nbFaces() );
  auto colorsG = SMW::Colors( smesh.nbFaces() );
  for ( auto i = 0; i < smesh.nbFaces(); i++ )
    {
      colorsH[ i ] = colormapH( H[ i ] );
      colorsG[ i ] = colormapG( G[ i ] );
    }
  SMW::writeOBJ( "example-cnc-H", smesh, colorsH );
  SMW::writeOBJ( "example-cnc-G", smesh, colorsG );
  return 0;
}
References DGtal::Trace::error(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::inf(), DGtal::Trace::info(), makeColorMap(), and DGtal::PointVector< dim, TEuclideanRing, TContainer >::sup().
makeColorMap()
DGtal::GradientColorMap< double > makeColorMap (double min_value, double max_value)
[curvature-measures-Includes]
[curvature-measures-Includes]
Definition at line 78 of file obj-curvature-measures-icnc-3d.cpp.
{
  DGtal::GradientColorMap< double > gradcmap( min_value, max_value );
  gradcmap.addColor( DGtal::Color( 0, 0, 255 ) );
  gradcmap.addColor( DGtal::Color( 0, 255, 255 ) );
  gradcmap.addColor( DGtal::Color( 255, 255, 255 ) );
  gradcmap.addColor( DGtal::Color( 255, 255, 0 ) );
  gradcmap.addColor( DGtal::Color( 255, 0, 0 ) );
  return gradcmap;
}
References DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::addColor().
Referenced by main().
usage()
void usage (int argc, char * argv[])
Definition at line 89 of file obj-curvature-measures-icnc-3d.cpp.
{
  std::cout << "Usage: " << std::endl
            << "\t" << argv[ 0 ] << " <filename.obj> <R> <Hmax> <Gmax>" << std::endl
            << std::endl
            << "Computation of mean and Gaussian curvatures on a mesh, " << std::endl
            << "using interpolated corrected curvature measures (based " << std::endl
            << "on the theory of corrected normal currents)."            << std::endl
            << "- builds the surface mesh from file <filename.obj>"      << std::endl
            << "- <R> is the radius of the measuring balls"              << std::endl
            << "- <Hmax> gives the colormap range [-Hmax,Hmax] for"      << std::endl
            << "  the output of mean curvature estimates"                << std::endl
            << "- <Gmax> gives the colormap range [-Gmax,Gmax] for"      << std::endl
            << "  the output of mean curvature estimates"                << std::endl
            << "It produces several OBJ files to display mean and"       << std::endl
            << "Gaussian curvature estimation results: `example-cnc-H.obj`" << std::endl
            << "and `example-cnc-G.obj` as well as the associated MTL file." << std::endl;
}