DGtal: DerivativeTester< Calculus, order > Struct Template Reference
DerivativeTester< Calculus, order > Struct Template Reference
#include </Users/davidcoeurjolly/Sources/DGtal/tests/dec/DECCommon.h>
Public Member Functions
BOOST_STATIC_ASSERT ((order<(int) Calculus::dimensionEmbedded - 1))
Static Public Member Functions
static bool test (const Calculus &calculus)
Detailed Description
template<typename Calculus, int order>
struct DerivativeTester< Calculus, order >
Definition at line 196 of file DECCommon.h.
Member Function Documentation
BOOST_STATIC_ASSERT()
template<typename Calculus , int order> DerivativeTester< Calculus, order >::BOOST_STATIC_ASSERT ((order<(int) Calculus::dimensionEmbedded - 1))
test()
template<typename Calculus , int order> static bool DerivativeTester< Calculus, order >::test (const Calculus & calculus) inline static
Definition at line 200 of file DECCommon.h.
    {
        DGtal::trace.info() << "testing primal derivative composition order " << order << std::endl;
        { // test primal composition
            typedef DGtal::LinearOperator<Calculus, order, DGtal::PRIMAL, order+1, DGtal::PRIMAL> FirstDerivative;
            FirstDerivative first_derivative = calculus.template derivative<order, DGtal::PRIMAL>();
            typedef DGtal::LinearOperator<Calculus, order+1, DGtal::PRIMAL, order+2, DGtal::PRIMAL> SecondDerivative;
            SecondDerivative second_derivative = calculus.template derivative<order+1, DGtal::PRIMAL>();
            typedef DGtal::LinearOperator<Calculus, order, DGtal::PRIMAL, order+2, DGtal::PRIMAL> DoubleDerivative;
            DoubleDerivative double_derivative = second_derivative * first_derivative;
            if (!is_all_zero(double_derivative.myContainer)) return false;
        }
        DGtal::trace.info() << "testing dual derivative composition order " << order << std::endl;
        { // test dual composition
            typedef DGtal::LinearOperator<Calculus, order, DGtal::DUAL, order+1, DGtal::DUAL> FirstDerivative;
            FirstDerivative first_derivative = calculus.template derivative<order, DGtal::DUAL>();
            typedef DGtal::LinearOperator<Calculus, order+1, DGtal::DUAL, order+2, DGtal::DUAL> SecondDerivative;
            SecondDerivative second_derivative = calculus.template derivative<order+1, DGtal::DUAL>();
            typedef DGtal::LinearOperator<Calculus, order, DGtal::DUAL, order+2, DGtal::DUAL> DoubleDerivative;
            DoubleDerivative double_derivative = second_derivative * first_derivative;
            if (!is_all_zero(double_derivative.myContainer)) return false;
        }
        /*
        DGtal::trace.info() << "testing liebnitz rule order " << order << std::endl;
        {
            typedef DGtal::LinearOperator<Calculus, order, DGtal::PRIMAL, order+1, DGtal::PRIMAL> Derivative;
            Derivative derivative = calculus.template derivative<order, DGtal::PRIMAL>();
            typedef DGtal::KForm<Calculus, order, DGtal::PRIMAL> InputForm;
            typedef DGtal::KForm<Calculus, order+1, DGtal::PRIMAL> OutputForm;
            InputForm alpha(calculus), beta(calculus), gamma(calculus);
            for (int kk=0; kk<calculus.kFormLength(order, DGtal::PRIMAL); kk++)
            {
                const double ak = static_cast<double>(random())/RAND_MAX;
                const double bk = static_cast<double>(random())/RAND_MAX;
                alpha.myContainer(kk) = ak;
                beta.myContainer(kk) = bk;
                gamma.myContainer(kk) = ak*bk;
            }
        }
        */
        return DerivativeTester<Calculus, order-1>::test(calculus);
    }
References DGtal::Trace::info(), DerivativeTester< Calculus, order >::test(), and DGtal::trace.
Referenced by DerivativeTester< Calculus, order >::test().
The documentation for this struct was generated from the following file:
DECCommon.h