DGtal: DGtal::NormalCycleFormula< TRealPoint, TRealVector > Struct Template Reference
DGtal::NormalCycleFormula< TRealPoint, TRealVector > Struct Template Reference
Aim: A helper class that provides static methods to compute normal cycle formulas of curvatures.
#include <DGtal/geometry/meshes/NormalCycleFormula.h>
Public Types
typedef TRealPoint RealPoint
typedef TRealVector RealVector
typedef RealVector::Component Scalar
typedef std::vector< RealPoint > RealPoints
typedef std::vector< RealVector > RealVectors
typedef SimpleMatrix< Scalar, 3, 3 > RealTensor
typedef std::size_t Size
typedef std::size_t Index
Static Public Member Functions
Formulas for curvature
static Scalar area (const RealPoints &pts)
static Scalar twiceMeanCurvature (const RealPoint &a, const RealPoint &b, const RealVector &right, const RealVector &left)
static Scalar gaussianCurvature (const RealPoint &a, const RealPoints &vtcs)
static Scalar gaussianCurvatureWithPairs (const RealPoint &a, const RealPoints &pairs)
static RealTensor anisotropicCurvatureH1 (const RealPoint &a, const RealPoint &b, const RealVector &right, const RealVector &left)
static RealTensor anisotropicCurvatureH2 (const RealPoint &a, const RealPoint &b, const RealVector &right, const RealVector &left)
Other geometric services
static RealPoint barycenter (const RealPoints &pts)
static RealVector normal (const RealPoint &a, const RealPoint &b, const RealPoint &c)
static Scalar area (const RealPoint &a, const RealPoint &b, const RealPoint &c)
static RealVector averageUnitVector (const RealVectors &vecs)
Static Public Attributes
static const Dimension dimension = RealPoint::dimension
Detailed Description
template<typename TRealPoint, typename TRealVector>
struct DGtal::NormalCycleFormula< TRealPoint, TRealVector >
Aim: A helper class that provides static methods to compute normal cycle formulas of curvatures.
Description of class 'NormalCycleFormula'
Template Parameters
TRealPoint any model of 3D RealPoint.
TRealVector any model of 3D RealVector.
Definition at line 64 of file NormalCycleFormula.h.
Member Typedef Documentation
Index
template<typename TRealPoint , typename TRealVector > typedef std::size_t DGtal::NormalCycleFormula< TRealPoint, TRealVector >::Index
Definition at line 73 of file NormalCycleFormula.h.
RealPoint
template<typename TRealPoint , typename TRealVector > typedef TRealPoint DGtal::NormalCycleFormula< TRealPoint, TRealVector >::RealPoint
Definition at line 66 of file NormalCycleFormula.h.
RealPoints
template<typename TRealPoint , typename TRealVector > typedef std::vector< RealPoint > DGtal::NormalCycleFormula< TRealPoint, TRealVector >::RealPoints
Definition at line 69 of file NormalCycleFormula.h.
RealTensor
template<typename TRealPoint , typename TRealVector > typedef SimpleMatrix< Scalar, 3, 3 > DGtal::NormalCycleFormula< TRealPoint, TRealVector >::RealTensor
Definition at line 71 of file NormalCycleFormula.h.
RealVector
template<typename TRealPoint , typename TRealVector > typedef TRealVector DGtal::NormalCycleFormula< TRealPoint, TRealVector >::RealVector
Definition at line 67 of file NormalCycleFormula.h.
RealVectors
template<typename TRealPoint , typename TRealVector > typedef std::vector< RealVector > DGtal::NormalCycleFormula< TRealPoint, TRealVector >::RealVectors
Definition at line 70 of file NormalCycleFormula.h.
Scalar
template<typename TRealPoint , typename TRealVector > typedef RealVector::Component DGtal::NormalCycleFormula< TRealPoint, TRealVector >::Scalar
Definition at line 68 of file NormalCycleFormula.h.
Size
template<typename TRealPoint , typename TRealVector > typedef std::size_t DGtal::NormalCycleFormula< TRealPoint, TRealVector >::Size
Definition at line 72 of file NormalCycleFormula.h.
Member Function Documentation
anisotropicCurvatureH1()
template<typename TRealPoint , typename TRealVector > static RealTensor DGtal::NormalCycleFormula< TRealPoint, TRealVector >::anisotropicCurvatureH1 (const RealPoint & a, const RealPoint & b, const RealVector & right, const RealVector & left) inline static
Computes the anisotropic measure \(\bar{H} \) at edge ab.
Parameters
a any point
b any point
right the normal vector at face xba where x is some vertex(ices)
left the normal vector at face yab where y is some vertex(ices)
Returns
the anisotropic curvature measure \(\bar{H} \) at edge ab.
Definition at line 159 of file NormalCycleFormula.h.
    {
      const RealVector diedre = right.crossProduct( left );
      const Scalar     length = std::max( 0.0, std::min( 1.0, diedre.norm() ) );
      const Scalar      angle = ( diedre.dot( b - a) > 0.0 )
        ? asin( length ) : - asin( length );
      RealVector          e_p = right + left;
      RealVector          e_m = right - left;
      const Scalar norm_e_p   = e_p.norm();
      const Scalar norm_e_m   = e_m.norm();
      e_p = norm_e_p > 1e-10 ? e_p / norm_e_p : RealVector::zero;
      e_m = norm_e_m > 1e-10 ? e_m / norm_e_m : RealVector::zero;
      const RealTensor T_p  =
        { e_p[ 0 ] * e_p[ 0 ], e_p[ 0 ] * e_p[ 1 ], e_p[ 0 ] * e_p[ 2 ],
          e_p[ 1 ] * e_p[ 0 ], e_p[ 1 ] * e_p[ 1 ], e_p[ 1 ] * e_p[ 2 ],
          e_p[ 2 ] * e_p[ 0 ], e_p[ 2 ] * e_p[ 1 ], e_p[ 2 ] * e_p[ 2 ] };
      const RealTensor T_m  =
        { e_m[ 0 ] * e_m[ 0 ], e_m[ 0 ] * e_m[ 1 ], e_m[ 0 ] * e_m[ 2 ],
          e_m[ 1 ] * e_m[ 0 ], e_m[ 1 ] * e_m[ 1 ], e_m[ 1 ] * e_m[ 2 ],
          e_m[ 2 ] * e_m[ 0 ], e_m[ 2 ] * e_m[ 1 ], e_m[ 2 ] * e_m[ 2 ] };
      return 0.5 * ( b - a ).norm()
        * ( ( angle - sin( angle ) ) * T_p + ( angle + sin( angle ) ) * T_m );
    }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
anisotropicCurvatureH2()
template<typename TRealPoint , typename TRealVector > static RealTensor DGtal::NormalCycleFormula< TRealPoint, TRealVector >::anisotropicCurvatureH2 (const RealPoint & a, const RealPoint & b, const RealVector & right, const RealVector & left) inline static
Computes the anisotropic measure \(\bar{\tilde{H}} \) at edge ab.
Parameters
a any point
b any point
right the normal vector at face xba where x is some vertex(ices)
left the normal vector at face yab where y is some vertex(ices)
Returns
the anisotropic curvature measure \(\bar{\tilde{H}} \) at edge ab.
Definition at line 192 of file NormalCycleFormula.h.
    {
      const RealVector diedre = right.crossProduct( left );
      const Scalar     length = std::max( 0.0, std::min( 1.0, diedre.norm() ) );
      const Scalar      angle = ( diedre.dot( b - a) > 0.0 )
        ? asin( length ) : - asin( length );
      const Scalar norm_ab = (b - a).norm();
      const RealVector   e = norm_ab > 1e-10 ? (b - a) / norm_ab : RealVector::zero;
      const RealTensor   T =
        { e[ 0 ] * e[ 0 ], e[ 0 ] * e[ 1 ], e[ 0 ] * e[ 2 ],
          e[ 1 ] * e[ 0 ], e[ 1 ] * e[ 1 ], e[ 1 ] * e[ 2 ],
          e[ 2 ] * e[ 0 ], e[ 2 ] * e[ 1 ], e[ 2 ] * e[ 2 ] };
      return ( 0.5 * norm_ab * angle ) * T; // JOL * 0.5
    }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::zero.
area() [1/2]
template<typename TRealPoint , typename TRealVector > static Scalar DGtal::NormalCycleFormula< TRealPoint, TRealVector >::area (const RealPoint & a, const RealPoint & b, const RealPoint & c) inline static
Computes triangle area
Parameters
a any point
b any point
c any point
Returns
the area of triangle abc
Definition at line 245 of file NormalCycleFormula.h.
    {
      return 0.5 * ( ( b - a ).crossProduct( c - a ) ).norm();
    }
References DGtal::crossProduct().
area() [2/2]
template<typename TRealPoint , typename TRealVector > static Scalar DGtal::NormalCycleFormula< TRealPoint, TRealVector >::area (const RealPoints & pts) inline static
Computes area of polygonal face pts.
Parameters
pts the (ccw ordered) points forming the vertices of a polygonal face.
Returns
the area of the given polygonal face.
Definition at line 85 of file NormalCycleFormula.h.
    {
      if ( pts.size() <  3 ) return 0.0;
      if ( pts.size() == 3 )
        return area( pts[ 0 ], pts[ 1 ], pts[ 2 ] );
      const RealPoint b = barycenter( pts );
      Scalar          a = 0.0;
      for ( Index i = 0; i < pts.size(); i++ )
        a += area( b, pts[ i ], pts[ (i+1)%pts.size() ] );
      return a;
    }
References DGtal::NormalCycleFormula< TRealPoint, TRealVector >::area(), and DGtal::NormalCycleFormula< TRealPoint, TRealVector >::barycenter().
Referenced by DGtal::NormalCycleFormula< TRealPoint, TRealVector >::area().
averageUnitVector()
template<typename TRealPoint , typename TRealVector > static RealVector DGtal::NormalCycleFormula< TRealPoint, TRealVector >::averageUnitVector (const RealVectors & vecs) inline static
Given a vector of unit vectors, returns their average unit vector.
Parameters
vecs any vector of vectors.
Returns
the average unit vector.
Definition at line 254 of file NormalCycleFormula.h.
    {
      RealVector avg;
      for ( auto v : vecs ) avg += v;
      auto avg_norm = avg.norm();
      return avg_norm != 0.0 ? avg / avg_norm : avg;
    }
barycenter()
template<typename TRealPoint , typename TRealVector > static RealPoint DGtal::NormalCycleFormula< TRealPoint, TRealVector >::barycenter (const RealPoints & pts) inline static
Given a vector of points, returns its barycenter.
Parameters
pts any vector of points
Returns
the barycenter of these points.
Definition at line 219 of file NormalCycleFormula.h.
    {
      RealPoint b;
      for ( auto p : pts ) b += p;
      b /= pts.size();
      return b;
    }
Referenced by DGtal::NormalCycleFormula< TRealPoint, TRealVector >::area().
gaussianCurvature()
template<typename TRealPoint , typename TRealVector > static Scalar DGtal::NormalCycleFormula< TRealPoint, TRealVector >::gaussianCurvature (const RealPoint & a, const RealPoints & vtcs) inline static
Computes the Gaussian curvature at point a with incident vertices vtcs.
Parameters
a any point
vtcs a range of points
Returns
the Gaussian curvature according to Normal Cycle formula.
Definition at line 124 of file NormalCycleFormula.h.
    {
      Scalar angle_sum = 0.0;
      for ( Size i = 0; i < vtcs.size(); i++ )
        angle_sum += acos( (vtcs[i] - a).getNormalized()
                           .dot( ( vtcs[(i+1)%vtcs.size()] - a ).getNormalized() ) );
      return 2.0 * M_PI - angle_sum;
    }
gaussianCurvatureWithPairs()
template<typename TRealPoint , typename TRealVector > static Scalar DGtal::NormalCycleFormula< TRealPoint, TRealVector >::gaussianCurvatureWithPairs (const RealPoint & a, const RealPoints & pairs) inline static
Computes the Gaussian curvature at point a with incident pairs of points pairs.
Parameters
a any point
pairs a range of points [x_0, y_0, x_1, y_1, etc] such that (a,x_i,y_i) is an incident face to a.
Returns
the Gaussian curvature according to Normal Cycle formula.
Definition at line 142 of file NormalCycleFormula.h.
    {
      Scalar angle_sum = 0.0;
      for ( Size i = 0; i < pairs.size(); i += 2 )
        angle_sum += acos( ( pairs[i] - a ).getNormalized()
                           .dot( ( pairs[i+1] - a ).getNormalized() ) );
      return 2.0 * M_PI - angle_sum;
    }
normal()
template<typename TRealPoint , typename TRealVector > static RealVector DGtal::NormalCycleFormula< TRealPoint, TRealVector >::normal (const RealPoint & a, const RealPoint & b, const RealPoint & c) inline static
Computes a unit normal vector to triangle abc
Parameters
a any point
b any point
c any point
Returns
the unit normal vector to abc, (ab x ac) / || ab x ac ||.
Definition at line 234 of file NormalCycleFormula.h.
    {
      return ( ( b - a ).crossProduct( c - a ) ).getNormalized();
    }
References DGtal::crossProduct().
twiceMeanCurvature()
template<typename TRealPoint , typename TRealVector > static Scalar DGtal::NormalCycleFormula< TRealPoint, TRealVector >::twiceMeanCurvature (const RealPoint & a, const RealPoint & b, const RealVector & right, const RealVector & left) inline static
Computes twice the mean curvature on edge ab given normal vectors right, left.
Parameters
a any point
b any point
right the normal vector at face xba where x is some vertex(ices)
left the normal vector at face yab where y is some vertex(ices)
Returns
twice the mean curvature according to Normal Cycle formula.
Definition at line 106 of file NormalCycleFormula.h.
    {
      const RealVector diedre = right.crossProduct( left );
      const Scalar n = std::min( 1.0, std::max( diedre.norm(), 0.0 ) );
      const Scalar angle = ( diedre.dot( b - a) < 0.0 )
        ? asin( n ) : - asin( n );
      return ( b - a ).norm() * angle;
    }
Field Documentation
dimension
template<typename TRealPoint , typename TRealVector > const Dimension DGtal::NormalCycleFormula< TRealPoint, TRealVector >::dimension = RealPoint::dimension static
Definition at line 74 of file NormalCycleFormula.h.
The documentation for this struct was generated from the following file:
NormalCycleFormula.h