DGtal: LibBoard::GouraudTriangle Struct Reference
LibBoard::GouraudTriangle Struct Reference
A triangle with shaded filling according to colors given for each vertex.
#include <Board/Shapes.h>
Public Member Functions
GouraudTriangle (const Point &p0, const DGtal::Color &color0, const Point &p1, const DGtal::Color &color1, const Point &p2, const DGtal::Color &color2, int subdivisions, int depth=-1)
GouraudTriangle (const Point &p0, float brightness0, const Point &p1, float brightness1, const Point &p2, float brightness2, const DGtal::Color &fillColor, int subdivisions, int depth=-1)
const std::string & name () const
Point center () const
GouraudTriangle & rotate (double angle, const Point &center)
GouraudTriangle rotated (double angle, const Point &center) const
GouraudTriangle & rotate (double angle)
GouraudTriangle rotated (double angle) const
GouraudTriangle translated (double dx, double dy) const
GouraudTriangle scaled (double sx, double sy) const
GouraudTriangle scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
GouraudTriangle * clone () const
Public Member Functions inherited from LibBoard::Polyline
Polyline (const std::vector< Point > &points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (const Path &path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
Point center () const
Polyline & operator<< (const Point &p)
Point & operator[] (const unsigned int n)
Polyline & rotate (double angle, const Point &center)
Polyline rotated (double angle, const Point &center) const
Polyline & rotate (double angle)
Polyline rotated (double angle) const
Polyline & translate (double dx, double dy)
Polyline translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Polyline scaled (double sx, double sy) const
Polyline scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Polyline * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
DGtal::Color _color0
DGtal::Color _color1
DGtal::Color _color2
int _subdivisions
Protected Attributes inherited from LibBoard::Polyline
Path _path
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A triangle with shaded filling according to colors given for each vertex.
The GouraudTriangle structure.
Definition at line 1223 of file Board/Shapes.h.
Constructor & Destructor Documentation
GouraudTriangle() [1/2]
LibBoard::GouraudTriangle::GouraudTriangle (const Point & p0, const DGtal::Color & color0, const Point & p1, const DGtal::Color & color1, const Point & p2, const DGtal::Color & color2, int subdivisions, int depth = -1)
Definition at line 2094 of file Shapes.cpp.
        : Polyline( std::vector<Point>(), true, DGtal::Color::None, DGtal::Color::None,
                    0.0f, SolidStyle, ButtCap, MiterJoin, depthValue ),
        _color0( color0 ), _color1( color1 ), _color2( color2 ), _subdivisions( subdivisions ) {
    _path << p0;
    _path << p1;
    _path << p2;
    Shape::_fillColor.red( ( color0.red() + color1.red() + color2.red() ) / 3 );
    Shape::_fillColor.green( ( color0.green() + color1.green() + color2.green() ) / 3 );
    Shape::_fillColor.blue( ( color0.blue() + color1.blue() + color2.blue() ) / 3 );
}
References LibBoard::Polyline::_path, DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
Referenced by clone(), flushPostscript(), flushSVG(), rotated(), rotated(), scaled(), scaled(), and translated().
GouraudTriangle() [2/2]
LibBoard::GouraudTriangle::GouraudTriangle (const Point & p0, float brightness0, const Point & p1, float brightness1, const Point & p2, float brightness2, const DGtal::Color & fillColor, int subdivisions, int depth = -1)
Definition at line 2111 of file Shapes.cpp.
        : Polyline( std::vector<Point>(), true, DGtal::Color::None, DGtal::Color::None,
                    0.0f, SolidStyle, ButtCap, MiterJoin, depthValue ),
    _color0( fill ), _color1( fill ), _color2( fill ), _subdivisions( subdivisions )
{
    _path << p0;
    _path << p1;
    _path << p2;
    _color0.red( static_cast<unsigned char>( std::min( 255.0f, _color0.red() * brightness0 ) ) );
    _color0.green( static_cast<unsigned char>( std::min( 255.0f, _color0.green() * brightness0 ) ) );
    _color0.blue( static_cast<unsigned char>( std::min( 255.0f, _color0.blue() * brightness0 ) ) );
    _color1.red( static_cast<unsigned char>( std::min( 255.0f, _color1.red() * brightness1 ) ) );
    _color1.green( static_cast<unsigned char>( std::min( 255.0f, _color1.green() * brightness1 ) ) );
    _color1.blue( static_cast<unsigned char>( std::min( 255.0f, _color1.blue() * brightness1 ) ) );
    _color2.red( static_cast<unsigned char>( std::min( 255.0f, _color2.red() * brightness2 ) ) );
    _color2.green( static_cast<unsigned char>( std::min( 255.0f, _color2.green() * brightness2 ) ) );
    _color2.blue( static_cast<unsigned char>( std::min( 255.0f, _color2.blue() * brightness2 ) ) );
    Shape::_fillColor.red( ( _color0.red() + _color1.red() + _color2.red() ) / 3 );
    Shape::_fillColor.green( ( _color0.green() + _color1.green() + _color2.green() ) / 3 );
    Shape::_fillColor.blue( ( _color0.blue() + _color1.blue() + _color2.blue() ) / 3 );
}
References _color0, _color1, _color2, LibBoard::Polyline::_path, DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
Member Function Documentation
center()
Point LibBoard::GouraudTriangle::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Definition at line 2140 of file Shapes.cpp.
{
    return ( _path[0] + _path[1] + _path[2] ) / 3.0;
}
References LibBoard::Polyline::_path.
Referenced by rotate(), and rotated().
clone()
GouraudTriangle * LibBoard::GouraudTriangle::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Definition at line 2194 of file Shapes.cpp.
{
    return new GouraudTriangle(*this);
}
References GouraudTriangle().
flushCairo()
void LibBoard::GouraudTriangle::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2299 of file Shapes.cpp.
{
}
flushFIG()
void LibBoard::GouraudTriangle::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Sends the Triangle to a FIG file format stream.
Warning! Because shading would generally require more colors in the colormap than allowed by the FIG file format, rendering a Gouraud triangle in an XFig file is the same as rendering a simple triangle whose filling color is the average of the vertex colors.
Parameters
stream output stream
transform transform
colormap colormap
Implements LibBoard::Shape.
Definition at line 2228 of file Shapes.cpp.
{
    DGtal::Color c( static_cast<unsigned char>((_color0.red() + _color1.red() + _color2.red() )/3.0),
             static_cast<unsigned char>((_color0.green() + _color1.green() + _color2.green())/3.0),
             static_cast<unsigned char>((_color0.blue() + _color1.blue() + _color2.blue())/3.0 ));
    Polyline( _path, DGtal::Color::None, c, 0.0f ).flushFIG( stream, transform, colormap );
    // if ( ! _subdivisions ) {
    // Polyline::flushFIG( stream, transform, colormap );
    // return;
    // }
// TODO : Handle extended colormap through clustering...
//   const Point & p0 = _points[0];
//   const Point & p1 = _points[1];
//   const Point & p2 = _points[2];
//   Point p01(0.5*(p0.x+p1.x), 0.5*(p0.y+p1.y));
//   DGtal::Color c01((_color0.red() + _color1.red())/2,
//        (_color0.green() + _color1.green())/2,
//        (_color0.blue() + _color1.blue())/2);
//   Point p12(0.5*(p1.x+p2.x), 0.5*(p1.y+p2.y));
//   DGtal::Color c12((_color1.red() + _color2.red())/2,
//        (_color1.green() + _color2.green())/2,
//        (_color1.blue() + _color2.blue())/2);
//   Point p20(0.5*(p2.x+p0.x), 0.5*(p2.y+p0.y));
//   DGtal::Color c20((_color2.red() + _color0.red())/2,
//        (_color2.green() + _color0.green())/2,
//        (_color2.blue() + _color0.blue())/2);
//   GouraudTriangle(p0, _color0, p20, c20, p01, c01, _subdivisions - 1, _depth).flushFIG(stream, transform, colormap);
//   GouraudTriangle(p1, _color1, p01, c01, p12, c12, _subdivisions - 1, _depth).flushFIG(stream, transform, colormap);
//   GouraudTriangle(p2, _color2, p20, c20, p12, c12, _subdivisions - 1, _depth).flushFIG(stream, transform, colormap);
//   GouraudTriangle(p01, c01, p12, c12, p20, c20,  _subdivisions - 1, _depth).flushFIG(stream, transform, colormap);
}
References _color0, _color1, _color2, LibBoard::Polyline::_path, DGtal::Color::blue(), DGtal::Color::green(), DGtal::Color::None, LibBoard::Polyline::Polyline(), and DGtal::Color::red().
flushPostscript()
void LibBoard::GouraudTriangle::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Sends the triangle to a Postscript document.
Parameters
stream output stream
transform transform
Implements LibBoard::Shape.
Definition at line 2199 of file Shapes.cpp.
{
    if ( ! _subdivisions ) {
        Polyline::flushPostscript( stream, transform );
        return;
    }
    const Point & p0 = _path[0];
    const Point & p1 = _path[1];
    const Point & p2 = _path[2];
    Point p01( 0.5*(p0.x+p1.x), 0.5*(p0.y+p1.y) );
    DGtal::Color c01( (_color0.red() + _color1.red())/2,
               (_color0.green() + _color1.green())/2,
               (_color0.blue() + _color1.blue())/2 );
    Point p12( 0.5*(p1.x+p2.x), 0.5*(p1.y+p2.y) );
    DGtal::Color c12( (_color1.red() + _color2.red())/2,
               (_color1.green() + _color2.green())/2,
               (_color1.blue() + _color2.blue())/2 );
    Point p20( 0.5*(p2.x+p0.x), 0.5*(p2.y+p0.y) );
    DGtal::Color c20( (_color2.red() + _color0.red())/2,
               (_color2.green() + _color0.green())/2,
               (_color2.blue() + _color0.blue())/2 );
    GouraudTriangle( p0, _color0, p20, c20, p01, c01, _subdivisions - 1, _depth ).flushPostscript( stream, transform );
    GouraudTriangle( p1, _color1, p01, c01, p12, c12, _subdivisions - 1, _depth ).flushPostscript( stream, transform );
    GouraudTriangle( p2, _color2, p20, c20, p12, c12, _subdivisions - 1, _depth ).flushPostscript( stream, transform );
    GouraudTriangle( p01, c01, p12, c12, p20, c20,  _subdivisions - 1, _depth ).flushPostscript( stream, transform );
}
References _color0, _color1, _color2, LibBoard::Shape::_depth, LibBoard::Polyline::_path, _subdivisions, DGtal::Color::blue(), LibBoard::Polyline::flushPostscript(), GouraudTriangle(), DGtal::Color::green(), DGtal::Color::red(), LibBoard::Point::x, and LibBoard::Point::y.
flushSVG()
void LibBoard::GouraudTriangle::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2265 of file Shapes.cpp.
{
    if ( ! _subdivisions ) {
        Polyline::flushSVG( stream, transform );
        return;
    }
    const Point & p0 = _path[0];
    const Point & p1 = _path[1];
    const Point & p2 = _path[2];
    Point p01( 0.5*(p0.x+p1.x), 0.5*(p0.y+p1.y) );
    DGtal::Color c01( (_color0.red() + _color1.red())/2,
               (_color0.green() + _color1.green())/2,
               (_color0.blue() + _color1.blue())/2 );
    Point p12( 0.5*(p1.x+p2.x), 0.5*(p1.y+p2.y) );
    DGtal::Color c12( (_color1.red() + _color2.red())/2,
               (_color1.green() + _color2.green())/2,
               (_color1.blue() + _color2.blue())/2 );
    Point p20( 0.5*(p2.x+p0.x), 0.5*(p2.y+p0.y) );
    DGtal::Color c20( (_color2.red() + _color0.red())/2,
               (_color2.green() + _color0.green())/2,
               (_color2.blue() + _color0.blue())/2 );
    GouraudTriangle( p0, _color0, p20, c20, p01, c01,
                     _subdivisions - 1, _depth ).flushSVG( stream, transform );
    GouraudTriangle( p1, _color1, p01, c01, p12, c12,
                     _subdivisions - 1, _depth ).flushSVG( stream, transform );
    GouraudTriangle( p2, _color2, p20, c20, p12, c12,
                     _subdivisions - 1, _depth ).flushSVG( stream, transform );
    GouraudTriangle( p01, c01, p12, c12, p20, c20,
                     _subdivisions - 1, _depth ).flushSVG( stream, transform );
}
References _color0, _color1, _color2, LibBoard::Shape::_depth, LibBoard::Polyline::_path, _subdivisions, DGtal::Color::blue(), LibBoard::Polyline::flushSVG(), GouraudTriangle(), DGtal::Color::green(), DGtal::Color::red(), LibBoard::Point::x, and LibBoard::Point::y.
flushTikZ()
void LibBoard::GouraudTriangle::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2306 of file Shapes.cpp.
{
  // FIXME: unimplemented
  stream << "% FIXME: GouraudTriangle::flushTikZ unimplemented" << std::endl;
}
name()
const std::string & LibBoard::GouraudTriangle::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Definition at line 2089 of file Shapes.cpp.
{
    return _name;
}
References _name.
rotate() [1/2]
GouraudTriangle & LibBoard::GouraudTriangle::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 2158 of file Shapes.cpp.
{
    return GouraudTriangle::rotate( angle, center() );
}
References center(), and rotate().
rotate() [2/2]
GouraudTriangle & LibBoard::GouraudTriangle::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 2145 of file Shapes.cpp.
{
    _path.rotate( angle, rotCenter );
    return *this;
}
References LibBoard::Polyline::_path, and LibBoard::Path::rotate().
Referenced by rotate(), rotated(), and rotated().
rotated() [1/2]
GouraudTriangle LibBoard::GouraudTriangle::rotated (double angle) const
Definition at line 2164 of file Shapes.cpp.
{
    return GouraudTriangle(*this).rotate( angle, center() );
}
References center(), GouraudTriangle(), and rotate().
rotated() [2/2]
GouraudTriangle LibBoard::GouraudTriangle::rotated (double angle, const Point & center) const
Definition at line 2152 of file Shapes.cpp.
{
    return GouraudTriangle(*this).rotate( angle, rotCenter );
}
References GouraudTriangle(), and rotate().
scaleAll()
void LibBoard::GouraudTriangle::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Definition at line 2188 of file Shapes.cpp.
{
    _path.scaleAll( s );
}
References LibBoard::Polyline::_path, and LibBoard::Path::scaleAll().
scaled() [1/2]
GouraudTriangle LibBoard::GouraudTriangle::scaled (double s) const
Definition at line 2182 of file Shapes.cpp.
{
    return static_cast<GouraudTriangle &>( GouraudTriangle(*this).scale( s, s ) );
}
References GouraudTriangle().
scaled() [2/2]
GouraudTriangle LibBoard::GouraudTriangle::scaled (double sx, double sy) const
Returns a scaled copy of the triangle.
Parameters
sx Scale factor along the x axis.
sy Scale factor along the y axis.
Returns
A scaled copy of the arrow.
Definition at line 2176 of file Shapes.cpp.
{
    return static_cast<GouraudTriangle &>( GouraudTriangle(*this).scale( sx, sy ) );
}
References GouraudTriangle().
translated()
GouraudTriangle LibBoard::GouraudTriangle::translated (double dx, double dy) const
Returns a translated copy of the triangle.
Parameters
dx The shift along the x axis.
dy The shift along the y axis.
Returns
A translated copy of the line.
Definition at line 2170 of file Shapes.cpp.
{
    return static_cast<GouraudTriangle &>( GouraudTriangle(*this).translate( dx, dy ) );
}
References GouraudTriangle().
Field Documentation
_color0
DGtal::Color LibBoard::GouraudTriangle::_color0 protected
Definition at line 1328 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and GouraudTriangle().
_color1
DGtal::Color LibBoard::GouraudTriangle::_color1 protected
Definition at line 1329 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and GouraudTriangle().
_color2
DGtal::Color LibBoard::GouraudTriangle::_color2 protected
Definition at line 1330 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and GouraudTriangle().
_name
const std::string LibBoard::GouraudTriangle::_name static private
The generic name of the shape.
Definition at line 1325 of file Board/Shapes.h.
Referenced by name().
_subdivisions
int LibBoard::GouraudTriangle::_subdivisions protected
Definition at line 1331 of file Board/Shapes.h.
Referenced by flushPostscript(), and flushSVG().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp