DGtal: LibBoard::Arc Struct Reference
LibBoard::Arc Struct Reference
An arc.
#include <Board/Shapes.h>
Public Member Functions
Arc (double x, double y, double radius, double angle1, double angle2, bool negative, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, int depthValue=-1)
const std::string & name () const
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Public Member Functions inherited from LibBoard::Circle
Circle (double x, double y, double radius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, int depthValue=-1)
const std::string & name () const
Point center () const
Circle & rotate (double angle, const Point &center)
Circle rotated (double angle, const Point &center) const
Circle & rotate (double angle)
Circle rotated (double angle) const
Circle & translate (double dx, double dy)
Circle translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Circle scaled (double sx, double sy) const
Circle scaled (double s) const
void scaleAll (double s)
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Circle * clone () const
Public Member Functions inherited from LibBoard::Ellipse
Ellipse (double x, double y, double xRadius, double yRadius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle lineStyle=SolidStyle, int depthValue=-1)
const std::string & name () const
Point center () const
Ellipse & rotate (double angle, const Point &center)
Ellipse rotated (double angle, const Point &center) const
Ellipse & rotate (double angle)
Ellipse rotated (double angle) const
Ellipse & translate (double dx, double dy)
Ellipse translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Ellipse scaled (double sx, double sy) const
Ellipse scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Ellipse * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
double _angle1
double _angle2
bool _negative
Protected Attributes inherited from LibBoard::Ellipse
Point _center
double _xRadius
double _yRadius
double _angle
bool _circle
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
An arc.
The arc structure.
Definition at line 1528 of file Board/Shapes.h.
Constructor & Destructor Documentation
Arc()
LibBoard::Arc::Arc (double x, double y, double radius, double angle1, double angle2, bool negative, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style = SolidStyle, int depthValue = -1) inline
Definition at line 1530 of file Board/Shapes.h.
    : Circle( x, y, radius, pen, fill, lineWidth, style, depthValue )
  { _angle1 = angle1; _angle2 = angle2; _negative = negative; }
References _angle1, _angle2, and _negative.
Member Function Documentation
flushCairo()
void LibBoard::Arc::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 1500 of file Shapes.cpp.
{
    cairo_save (cr);
      cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
      if (_negative) // important: here for Cairo we must inverse 'cairo_arc' and 'cairo_arc_negative' and change alpha with 2.*M_PI-alpha
  cairo_arc (cr, transform.mapX( _center.x ), transform.mapY( _center.y ), transform.scale( _xRadius ), 2.*M_PI-_angle1, 2.*M_PI-_angle2);
      else
  cairo_arc_negative (cr, transform.mapX( _center.x ), transform.mapY( _center.y ), transform.scale( _xRadius ), 2.*M_PI-_angle1, 2.*M_PI-_angle2);
      if ( filled() )
      {
  if ( _penColor != DGtal::Color::None )
    cairo_fill_preserve (cr);
  else
    cairo_fill (cr);
      }
      //
      if ( _penColor != DGtal::Color::None )
      {
  cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
  cairo_set_line_width (cr, _lineWidth);
  cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
  cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
  setCairoDashStyle (cr, _lineStyle);
  cairo_stroke (cr);
      }
    cairo_restore (cr);
}
References _angle1, _angle2, LibBoard::Ellipse::_center, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, _negative, LibBoard::Shape::_penColor, LibBoard::Ellipse::_xRadius, DGtal::Color::blue(), LibBoard::Shape::filled(), DGtal::Color::green(), DGtal::Color::None, DGtal::Color::red(), LibBoard::Shape::setCairoDashStyle(), LibBoard::Point::x, and LibBoard::Point::y.
flushPostscript()
void LibBoard::Arc::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 1539 of file Shapes.cpp.
{
//The arc is generated by sweeping a line segment of length r, and tied at the point (x-coord y-coord), in a counter-clockwise direction from an angle _angle1 to an angle _angle2.
//Thus, we have to swap _angle1 and _angle2 according to bool _negative
  double a1, a2;
  if (_negative == true)
  {
    a1 = _angle2;
    a2 = _angle1;
  }
  else
  {
    a1 = _angle1;
    a2 = _angle2;
  }
  stream << "\n% Arc\n";
    if ( filled() ) {
      stream << "gs "
             << transform.mapX( _center.x ) << " " << transform.mapY( _center.y ) << " "
             << transform.scale( _xRadius )<< " " << (a1*180/M_PI) << " "
             << (a2*180/M_PI) << " "<< "arc ";
      stream << " " << _fillColor.postscript() << " srgb";
      stream << " fill gr" << std::endl;
    }
    if ( _penColor != DGtal::Color::None ) {
      stream << "gs "
             << transform.mapX( _center.x ) << " " << transform.mapY( _center.y ) << " "
             << transform.scale( _xRadius )<< " " << (a1*180/M_PI) << " "
             << (a2*180/M_PI) << " "<< "arc ";
      _penColor.flushPostscript( stream );
      stream << " stroke gr" << std::endl;
    }
}
References _angle1, _angle2, LibBoard::Ellipse::_center, LibBoard::Shape::_fillColor, _negative, LibBoard::Shape::_penColor, LibBoard::Ellipse::_xRadius, LibBoard::Shape::filled(), DGtal::Color::flushPostscript(), DGtal::Color::None, DGtal::Color::postscript(), LibBoard::Point::x, and LibBoard::Point::y.
flushSVG()
void LibBoard::Arc::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 1579 of file Shapes.cpp.
{
double fx = _center.x + _xRadius*std::cos(_angle1);
double fy = _center.y + _xRadius*std::sin(_angle1);
double lx = _center.x + _xRadius*std::cos(_angle2);
double ly = _center.y + _xRadius*std::sin(_angle2);
stream << "<path ";
stream << svgProperties(transform) << " ";
//first point
stream << "d='M " << transform.mapX(fx);
stream << "," << transform.mapY(fy);
//arc
stream << " A " << transform.scale(_xRadius) << " " << transform.scale(_xRadius);
//something
stream << " 0";
//orientation and center position
if (_negative)
{
  if ( (std::cos(_angle1)*std::sin(_angle2) - std::sin(_angle1)*std::cos(_angle2))<0 )
  {
    stream << " 0 1";
  } else
  {
    stream << " 1 1";
  }
} else
{
  if ( (std::cos(_angle1)*std::sin(_angle2) - std::sin(_angle1)*std::cos(_angle2))<0 )
  {
    stream << " 1 0";
  } else
  {
    stream << " 0 0";
  }
}
//last point
stream << " " << transform.mapX(lx);
stream << "," << transform.mapY(ly);
stream << "' />";
}
References _angle1, _angle2, LibBoard::Ellipse::_center, _negative, LibBoard::Ellipse::_xRadius, LibBoard::Shape::svgProperties(), LibBoard::Point::x, and LibBoard::Point::y.
flushTikZ()
void LibBoard::Arc::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 1625 of file Shapes.cpp.
{
    stream << "\\path[" << tikzProperties(transform) << "] ("
           << transform.mapX( _center.x ) << ',' << transform.mapY( _center.y ) << ')'  // center
           << " +(" << -_angle1/M_PI*180. << ':' << transform.scale( _xRadius) << ')'   // first point of arc
           << " arc (" << -_angle1/M_PI*180. << ':' << -_angle2/M_PI*180. + _negative * 360. << ':' << transform.scale( _xRadius ) << ");"
           << std::endl;
}
References _angle1, _angle2, LibBoard::Ellipse::_center, _negative, LibBoard::Ellipse::_xRadius, LibBoard::Shape::tikzProperties(), LibBoard::Point::x, and LibBoard::Point::y.
name()
const std::string & LibBoard::Arc::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Definition at line 1493 of file Shapes.cpp.
{
    return _name;
}
References _name.
Field Documentation
_angle1
double LibBoard::Arc::_angle1 protected
Definition at line 1564 of file Board/Shapes.h.
Referenced by Arc(), flushCairo(), flushPostscript(), flushSVG(), and flushTikZ().
_angle2
double LibBoard::Arc::_angle2 protected
Definition at line 1565 of file Board/Shapes.h.
Referenced by Arc(), flushCairo(), flushPostscript(), flushSVG(), and flushTikZ().
_name
const std::string LibBoard::Arc::_name static private
The generic name of the shape.
Definition at line 1561 of file Board/Shapes.h.
Referenced by name().
_negative
bool LibBoard::Arc::_negative protected
Definition at line 1566 of file Board/Shapes.h.
Referenced by Arc(), flushCairo(), flushPostscript(), flushSVG(), and flushTikZ().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp