DGtal: DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData > Struct Template Reference
DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData > Struct Template Reference
#include <DGtal/shapes/TriangulatedSurface.h>
Public Types
typedef Index Argument
typedef TData Data
typedef std::vector< Data > Storage
Public Member Functions
IndexedPropertyMap ()
Default constructor. The object is invalid.
IndexedPropertyMap (const Self &aSurface, Size s, Data def_data=Data())
IndexedPropertyMap (const Self &aSurface, Storage &aStorage)
const Self & surface () const
const Data & operator() (Argument v) const
const Data & operator[] (Argument v) const
Data & operator[] (Argument v)
bool isValid () const
Size size () const
Storage & storage ()
const Storage & storage () const
Private Attributes
const Self * mySurface
The associated polygonal surface.
OwningOrAliasingPtr< Storage > myData
An owned or aliased pointer to the vector of data.
Detailed Description
template<typename TPoint>
template<typename TData>
struct DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >
This structure is used to define efficient maps between vertices and any data specified by type TData. The triangulated surface provides a default vertex map for vertex positions.
Template Parameters
TData the value type for the map.
See also
positions
makeVertexMap
Note
This property map uses a vector structure as storage.
Definition at line 128 of file TriangulatedSurface.h.
Member Typedef Documentation
Argument
template<typename TPoint > template<typename TData > typedef Index DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::Argument
Definition at line 129 of file TriangulatedSurface.h.
Data
template<typename TPoint > template<typename TData > typedef TData DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::Data
Definition at line 130 of file TriangulatedSurface.h.
Storage
template<typename TPoint > template<typename TData > typedef std::vector<Data> DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::Storage
Definition at line 131 of file TriangulatedSurface.h.
Constructor & Destructor Documentation
IndexedPropertyMap() [1/3]
template<typename TPoint > template<typename TData > DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::IndexedPropertyMap () inline
Default constructor. The object is invalid.
Definition at line 134 of file TriangulatedSurface.h.
: mySurface(0), myData(0) {}
IndexedPropertyMap() [2/3]
template<typename TPoint > template<typename TData > DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::IndexedPropertyMap (const Self & aSurface, Size s, Data def_data = Data()) inline
Creates an empty vertex property map
Parameters
aSurface the corresponding triangulated surface.
s one more than the maximal allowed index (i.e. nb of elements).
def_data the default value at initialization.
Definition at line 140 of file TriangulatedSurface.h.
        : mySurface( &aSurface ),
          myData( Storage( s, def_data ) )
      {}
IndexedPropertyMap() [3/3]
template<typename TPoint > template<typename TData > DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::IndexedPropertyMap (const Self & aSurface, Storage & aStorage) inline
Creates the IndexedPropertyMap that points to one that exists already.
Parameters
aSurface the corresponding triangulated surface.
aStorage the map to reference in this property map.
Note
This method is used to give to a user the map vertex -> position that is stored within the triangulated surface.
Definition at line 152 of file TriangulatedSurface.h.
        : mySurface( &aSurface ),
          myData( &aStorage, false )
      {}
Member Function Documentation
isValid()
template<typename TPoint > template<typename TData > bool DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid () const inline
Returns
if the object was properly initialized.
Definition at line 193 of file TriangulatedSurface.h.
{ return mySurface != 0; }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::mySurface.
Referenced by DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator()(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[](), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[](), and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::surface().
operator()()
template<typename TPoint > template<typename TData > const Data & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator() (Argument v) const inline
This object is a function : Argument -> Data
Parameters
v any index
Returns
the associated data
Definition at line 168 of file TriangulatedSurface.h.
      {
        ASSERT( isValid() && v < myData->size() );
        return (*myData)[ v ];
      }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData, and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::size().
operator[]() [1/2]
template<typename TPoint > template<typename TData > Data & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[] (Argument v) inline
mutable array access.
Parameters
v any index
Returns
the associated data
Definition at line 186 of file TriangulatedSurface.h.
      {
        ASSERT( isValid() && v < myData->size() );
        return (*myData)[ v ];
      }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData, and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::size().
operator[]() [2/2]
template<typename TPoint > template<typename TData > const Data & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[] (Argument v) const inline
Non-mutable array access.
Parameters
v any index
Returns
the associated data
Definition at line 177 of file TriangulatedSurface.h.
      {
        ASSERT( isValid() && v < myData->size() );
        return (*myData)[ v ];
      }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData, and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::size().
size()
template<typename TPoint > template<typename TData > Size DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::size () const inline
Returns
the size of the indexed map (i.e., size of associated vector).
Definition at line 196 of file TriangulatedSurface.h.
{ return myData->size(); }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData.
Referenced by DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator()(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[](), and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[]().
storage() [1/2]
template<typename TPoint > template<typename TData > Storage & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::storage () inline
Returns
a reference to the storage class (a vector of Data).
Definition at line 199 of file TriangulatedSurface.h.
{ return *myData; }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData.
storage() [2/2]
template<typename TPoint > template<typename TData > const Storage & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::storage () const inline
Returns
a const reference to the storage class (a vector of Data).
Definition at line 202 of file TriangulatedSurface.h.
{ return *myData; }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData.
surface()
template<typename TPoint > template<typename TData > const Self & DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::surface () const inline
Returns
the associated triangulated surface.
Definition at line 159 of file TriangulatedSurface.h.
      {
        ASSERT( isValid() );
        return *mySurface;
      }
References DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid(), and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::mySurface.
Field Documentation
myData
template<typename TPoint > template<typename TData > OwningOrAliasingPtr<Storage> DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::myData private
An owned or aliased pointer to the vector of data.
Definition at line 208 of file TriangulatedSurface.h.
Referenced by DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator()(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[](), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::operator[](), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::size(), DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::storage(), and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::storage().
mySurface
template<typename TPoint > template<typename TData > const Self* DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::mySurface private
The associated polygonal surface.
Definition at line 206 of file TriangulatedSurface.h.
Referenced by DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::isValid(), and DGtal::TriangulatedSurface< TPoint >::IndexedPropertyMap< TData >::surface().
The documentation for this struct was generated from the following file:
TriangulatedSurface.h