DGtal: DGtal::FrechetShortcut< TIterator, TInteger >::Tools Struct Reference
DGtal::FrechetShortcut< TIterator, TInteger >::Tools Struct Reference
#include <DGtal/geometry/curves/FrechetShortcut.h>
Static Public Member Functions
static bool isBetween (double i, double a, double b, double n)
static int circle_circle_intersection (double x0, double y0, double r0, double x1, double y1, double r1, double *xi, double *yi, double *xi_prime, double *yi_prime)
static int circleTangentPoints (double x, double y, double x1, double y1, double r1, double *xi, double *yi, double *xi_prime, double *yi_prime)
static double computeAngle (double x0, double y0, double x1, double y1)
static double angleVectVect (Vector u, Vector v)
static int computeChainCode (Point p, Point q)
static int computeOctant (Point p, Point q)
static int rot (int d, int quad)
static Vector chainCode2Vect (int d)
Detailed Description
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate>
struct DGtal::FrechetShortcut< TIterator, TInteger >::Tools
Definition at line 354 of file FrechetShortcut.h.
Member Function Documentation
angleVectVect()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static double DGtal::FrechetShortcut< TIterator, TInteger >::Tools::angleVectVect (Vector u, Vector v) inline static
Angle between two vectors
Parameters
u and
v two vectors
Returns
an angle
Definition at line 578 of file FrechetShortcut.h.
      {
        IntegerComputer<Integer> ic;
        return acos((double)ic.dotProduct(u,v)/(u.norm()*v.norm()));
      }
References DGtal::IntegerComputer< TInteger >::dotProduct().
chainCode2Vect()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static Vector DGtal::FrechetShortcut< TIterator, TInteger >::Tools::chainCode2Vect (int d) inline static
Converts a chain code into a vector
Parameters
d an int
Returns
a vector
Definition at line 689 of file FrechetShortcut.h.
    {
      Vector v;
      switch(d){
      case 0:{
        v[0] = 1;
        v[1] = 0;
        break;
      }
      case 1:{
        v[0] = 1;
        v[1] = 1;
        break;
      }
      case 2:{
        v[0] = 0;
        v[1] = 1;
        break;
      }
      case 3:{
        v[0] = -1;
        v[1] = 1;
        break;
      }
      case 4:{
        v[0] = -1;
        v[1] = 0;
        break;
      }
      case 5:{
        v[0] = -1;
        v[1] = -1;
        break;
      }
      case 6:{
        v[0] = 0;
        v[1] = -1;
        break;
      }
      case 7:{
        v[0] = 1;
        v[1] = -1;
        break;
      }
      }
      return v;
    }
circle_circle_intersection()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static int DGtal::FrechetShortcut< TIterator, TInteger >::Tools::circle_circle_intersection (double x0, double y0, double r0, double x1, double y1, double r1, double * xi, double * yi, double * xi_prime, double * yi_prime) inline static
Determine the points where two circles in a common plane intersect Parameters: three doubles per circle (center, radius), pointers to the two intersection points
Returns
0 if the circles do not intersect each other, 1 otherwise
Definition at line 400 of file FrechetShortcut.h.
      {
        // I. Sivignon 05/2024: fix to handle the case where r0=0 or
        // r1=0. Enables the case where error=0.
        // Other special cases where circles are tangent are treated
        // below.
        if(r0==0)
          {
            *xi = x0; *yi = y0;
            *xi_prime = x0 ; *yi_prime = y0;
            return 1;
          }
        else
          if(r1==0)
            {
              *xi = x1; *yi = y1;
              *xi_prime = x1 ; *yi_prime = y1;
              return 1;
            }
        double a, dx, dy, d, h, rx, ry;
        double x2, y2;
        /* dx and dy are the vertical and horizontal distances between
         * the circle centers.
         */
        dx = x1 - x0;
        dy = y1 - y0;
        /* Determine the straight-line distance between the centers. */
        //d = sqrt((dy*dy) + (dx*dx));
        d = hypot(dx,dy); // Suggested by Keith Briggs
        if((r0+r1)*(r0+r1)-((dy*dy)+(dx*dx)) < PRECISION)
          {  // I. Sivignon 05/2024: fix to handle the case where
             // circles are tangent but radii are non zero.
            double alpha= r0/d;
            *xi = x0 + dx*alpha;
            *yi = y0 + dy*alpha;
            *xi_prime = *xi; *yi_prime = *yi;
            return 1;
          }
        /* Check for solvability. */
        if (d > (r0 + r1))
        {
          /* no solution. circles do not intersect. */
          std::cerr  << "Warning : the two circles do not intersect -> should never happen" << std::endl;
          return 0; //I. Sivignon 05/2010 should never happen for our specific use.
        }
        if (d < fabs(r0 - r1))
          {
            /* no solution. one circle is contained in the other */
            return 0;
          }
        //   }
        /* 'point 2' is the point where the line through the circle
         * intersection points crosses the line between the circle
         * centers.
         */
        /* Determine the distance from point 0 to point 2. */
        a = ((r0*r0) - (r1*r1) + (d*d)) / (2.0 * d) ;
        /* Determine the coordinates of point 2. */
        x2 = x0 + (dx * a/d);
        y2 = y0 + (dy * a/d);
        /* Determine the distance from point 2 to either of the
       * intersection points.
       */
        h = sqrt((r0*r0) - (a*a));
        /* Now determine the offsets of the intersection points from
         * point 2.
         */
        rx = -dy * (h/d);
        ry = dx * (h/d);
        /* Determine the absolute intersection points. */
        *xi = x2 + rx;
        *xi_prime = x2 - rx;
        *yi = y2 + ry;
        *yi_prime = y2 - ry;
        return 1;
      }
Referenced by DGtal::FrechetShortcut< TIterator, TInteger >::Tools::circleTangentPoints().
circleTangentPoints()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static int DGtal::FrechetShortcut< TIterator, TInteger >::Tools::circleTangentPoints (double x, double y, double x1, double y1, double r1, double * xi, double * yi, double * xi_prime, double * yi_prime) inline static
Given a point X and a circle of center X1, compute the two points Xi and Xi' of the circle the tangent of which go through X. Since the triangle XXiX1 is a right triangle on Xi, the middle point M between X and X1 is equidistant to X, X1 and Xi. Thus, Xi belongs to the intersection of the circle (X1,r1) and the circle of center M and radius ||XX1||/2.
Parameters
[in] x the first coordinate of X.
[in] y the second coordinate of X.
[in] x1 the first coordinate of the circle center X1.
[in] y1 the second coordinate of the circle center X1.
[in] r1 the circle radius.
[out] xi pointer to the first coordinate of the first intersection point.
[out] yi pointer to the second coordinate of the first intersection point.
[out] xi_prime pointer to the first coordinate of the second intersection point.
[out] yi_prime pointer to the second coordinate of the second intersection point.
Returns
result of the call to circle_circle_intersection
Definition at line 515 of file FrechetShortcut.h.
      {
        double x0 = (x+x1)/2;
        double y0 = (y+y1)/2;
        double r0 = sqrt((x-x1)*(x-x1) + (y-y1)*(y-y1))/2;
        int res =
          circle_circle_intersection(x0,y0,r0,x1,y1,r1,xi,yi,xi_prime,yi_prime);
        return res;
      }
References DGtal::FrechetShortcut< TIterator, TInteger >::Tools::circle_circle_intersection().
computeAngle()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static double DGtal::FrechetShortcut< TIterator, TInteger >::Tools::computeAngle (double x0, double y0, double x1, double y1) inline static
Compute the angle of the line passing through two points. Angle in [0,2pi]
Parameters
x0 x0
y0 y0
x1 x1
y1 y1
Returns
an angle
Definition at line 540 of file FrechetShortcut.h.
      {
        double x = x1-x0;
        double y = y1-y0;
        if(x!=0)
          {
            double alpha = y/x;
            if(x>0 && y>=0)
              return atan(alpha);
            else
              if(x>0 && y<0)
                return atan(alpha)+2*M_PI;
              else
                if(x<0)
                  return atan(alpha)+M_PI;
          }
        else
          {
            if(y==0)
              return 0;
            else
              if(y>0)
                return M_PI_2;
              else
                return 3*M_PI_2;
          }
        return -1;
      }
computeChainCode()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static int DGtal::FrechetShortcut< TIterator, TInteger >::Tools::computeChainCode (Point p, Point q) inline static
Computes the chain code between two 8-connected pixels
Parameters
p and
q two points
Returns
an int
Definition at line 589 of file FrechetShortcut.h.
      {
        int d;
        Coordinate x2 = q[0];
        Coordinate y2 = q[1];
        Coordinate x1 = p[0];
        Coordinate y1 = p[1];
        if(x2-x1==0)
          if(y2-y1==1)
            d=2;
          else
            d=6;
        else
          if(x2-x1==1)
            if(y2-y1==0)
              d=0;
            else
              if(y2-y1==1)
                d=1;
              else
                d=7;
          else
            if(y2-y1==0)
              d=4;
            else
              if(y2-y1==1)
                d=3;
              else
                d=5;
        return d;
      }
computeOctant()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static int DGtal::FrechetShortcut< TIterator, TInteger >::Tools::computeOctant (Point p, Point q) inline static
Computes the octant of the direction pq
Parameters
p and
q two points
Returns
an int
Definition at line 627 of file FrechetShortcut.h.
    {
      int d = 0;
      Coordinate x = q[0]-p[0];
      Coordinate y = q[1]-p[1];
      if(x>=0)
        {
          if(y>=0)
            {
              if(x>y)
                d=0; // 0 <= y < x
              else
                if(x!=0)
                  d=1; // 0 <= x <= y
            }
          else
            {
              if(x>=abs(y))
                d=7; // 0 < abs(y) <= x
              else
                d=6; // 0 <= x < abs(y)
            }
        }
      if(x<=0)
        {
          if(y>0)
            if(abs(x)>=y)
              d=3; //
            else
              d=2;
          else
            {
              if(abs(x)>abs(y))
                d=4;
              else
                if(x!=0)
                  d=5;
            }
        }
      return d;
    }
isBetween()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static bool DGtal::FrechetShortcut< TIterator, TInteger >::Tools::isBetween (double i, double a, double b, double n) inline static
Determines if i is between a and b in the oriented toric space modulo n
Parameters
i i
a a
b b
n n
Returns
true if i is between a anb d, false otherwise
Definition at line 365 of file FrechetShortcut.h.
      {
        if(a<=b)
          return (i>=a && i<=b);
        else
          return ((i>=a && i<=n) || (i>=0 && i<=b));
      }
rot()
template<typename TIterator , typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate> static int DGtal::FrechetShortcut< TIterator, TInteger >::Tools::rot (int d, int quad) inline static
Rotate the chain code d to put it in the frame where the octant 'quad' is treated as the first octant.
Parameters
d a chain code
quad the octant
Returns
an int (the new chain code)
Definition at line 679 of file FrechetShortcut.h.
      {
        return (d-quad+8)%8;
      }
The documentation for this struct was generated from the following file:
FrechetShortcut.h