DGtal: testGaussDigitizer.cpp File Reference
testGaussDigitizer.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/parametric/Ball2D.h"
#include "DGtal/shapes/parametric/Astroid2D.h"
#include "DGtal/shapes/parametric/Ellipse2D.h"
#include "DGtal/shapes/parametric/Flower2D.h"
#include "DGtal/shapes/parametric/Lemniscate2D.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/curves/GridCurve.h"
#include "DGtal/shapes/CDigitalOrientedShape.h"
#include "DGtal/shapes/CDigitalBoundedShape.h"
Functions
bool testConcept ()
template<typename Space , typename Shape >
bool testDigitization (const Shape &aShape, double h, const string &fileName)
bool testGaussDigitizer ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2011/07/01
Functions for testing class GaussDigitizer.
This file is part of the DGtal library.
Definition in file testGaussDigitizer.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 220 of file testGaussDigitizer.cpp.
{
  trace.beginBlock ( "Testing class GaussDigitizer" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testConcept() && testGaussDigitizer(); // && ... other tests
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testConcept(), testGaussDigitizer(), and DGtal::trace.
testConcept()
bool testConcept ()
Gaussdigitizer is a model of CDigitalBoundedShape and CDigitalOrientedShape.
Definition at line 65 of file testGaussDigitizer.cpp.
{
  typedef GaussDigitizer<Z2i::Space,Ellipse2D< Z2i::Space > > Dig;
  BOOST_CONCEPT_ASSERT((concepts::CDigitalBoundedShape<Dig>));
  BOOST_CONCEPT_ASSERT((concepts::CDigitalOrientedShape<Dig>));
  return true;
}
Referenced by main().
testDigitization()
template<typename Space , typename Shape > bool testDigitization (const Shape & aShape, double h, const string & fileName)
Definition at line 76 of file testGaussDigitizer.cpp.
{
  typedef typename Space::Point Point;
  typedef typename Space::RealPoint RealPoint;
  typedef HyperRectDomain<Space> Domain;
  typedef typename DigitalSetSelector
    < Domain, BIG_DS + HIGH_ITER_DS + HIGH_BEL_DS >::Type MySet;
  // Creates a digitizer on the window (xLow, xUp).
  RealPoint xLow( -5.3, -4.3 );
  RealPoint xUp( 7.4, 4.7 );
  GaussDigitizer<Space,Shape> dig;
  dig.attach( aShape ); // attaches the shape.
  dig.init( aShape.getLowerBound(), aShape.getUpperBound(), h );
  // The domain size is given by the digitizer according to the window
  // and the step.
  Domain domain = dig.getDomain();
  MySet aSet( domain );
  // Creates a set from the digitizer.
  Shapes<Domain>::digitalShaper( aSet, dig );
  // Create cellular space
  typedef Z2i::KSpace KSpace;
  typedef Z2i::SCell SCell;
  KSpace K;
  bool ok = K.init( dig.getLowerBound(), dig.getUpperBound(), true );
  if (!ok)
    return false;
  SurfelAdjacency<KSpace::dimension> SAdj( true );
  // Extracts shape boundary
  SCell bel = Surfaces<KSpace>::findABel( K, dig, 10000 );
  // Getting the consecutive surfels of the 2D boundary
  std::vector<Point> points;
  Surfaces<KSpace>::track2DBoundaryPoints( points, K, SAdj, dig, bel );
  GridCurve<KSpace> gridcurve;
  gridcurve.initFromVector( points );
  // Display all
  Board2D board;
  board.setUnit( LibBoard::Board::UCentimeter );
  board << SetMode( domain.className(), "Paving" )
    << domain << aSet;
  board << SetMode( gridcurve.className(), "Edges" )
  << CustomStyle( bel.className(),
      new CustomColors( DGtal::Color( 255, 0, 0 ),
            DGtal::Color( 200, 0, 0 ) ) )
  << gridcurve;
  board.saveEPS( ( fileName + ".eps" ).c_str() );
  board.saveSVG( ( fileName + ".svg" ).c_str() );
  return true;
}
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::BIG_DS, DGtal::GridCurve< TKSpace >::className(), DGtal::HyperRectDomain< TSpace >::className(), DGtal::SignedKhalimskyCell< dim, TInteger >::className(), DGtal::Shapes< TDomain >::digitalShaper(), domain, DGtal::Surfaces< TKSpace >::findABel(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::Astroid2D< TSpace >::getLowerBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::Astroid2D< TSpace >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::HIGH_BEL_DS, DGtal::HIGH_ITER_DS, DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GridCurve< TKSpace >::initFromVector(), K, LibBoard::Board::saveEPS(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::Surfaces< TKSpace >::track2DBoundaryPoints(), and LibBoard::Board::UCentimeter.
Referenced by testGaussDigitizer().
testGaussDigitizer()
bool testGaussDigitizer ()
Example of a test. To be completed.
Definition at line 143 of file testGaussDigitizer.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Testing GaussDigitizer as a Digital Shape functor." );
  typedef Astroid2D< Z2i::Space > MyAstroid;
  MyAstroid astroid( 6.2, -2.1, 7.3, 4.9 );
  nbok += testDigitization<Z2i::Space,MyAstroid>
    ( astroid, 1.0, "gauss-astroid-1" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyAstroid>
    ( astroid, 0.5, "gauss-astroid-0_5" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyAstroid>
    ( astroid, 0.25, "gauss-astroid-0_25" ) ? 1 : 0;
  nb++;
  typedef Ball2D< Z2i::Space > MyBall;
  MyBall ball( 6.2, -2.1, 7.3 );
  nbok += testDigitization<Z2i::Space,MyBall>
    ( ball, 1.0, "gauss-ball-1" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyBall>
    ( ball, 0.5, "gauss-ball-0_5" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyBall>
    ( ball, 0.25, "gauss-ball-0_25" ) ? 1 : 0;
  nb++;
  typedef Ellipse2D< Z2i::Space > MyEllipse;
  MyEllipse ellipse( 1.2, 0.1, 4.0, 3.0, 0.3 );
  nbok += testDigitization<Z2i::Space,MyEllipse>
    ( ellipse, 1.0, "gauss-ellipse-1" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyEllipse>
    ( ellipse, 0.5, "gauss-ellipse-0_5" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyEllipse>
    ( ellipse, 0.25, "gauss-ellipse-0_25" ) ? 1 : 0;
  nb++;
  typedef Flower2D< Z2i::Space > MyFlower;
  MyFlower flower( 0.5, -2.3, 5.0, 0.7, 6, 0.3 );
  nbok += testDigitization<Z2i::Space,MyFlower>
    ( flower, 1.0, "gauss-flower-1" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyFlower>
    ( flower, 0.5, "gauss-flower-0_5" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyFlower>
    ( flower, 0.25, "gauss-flower-0_25" ) ? 1 : 0;
  nb++;
  typedef Lemniscate2D< Z2i::Space > MyLemniscate;
  MyLemniscate lemniscate( 0.5, -2.3, 5.0 );
  nbok += testDigitization<Z2i::Space,MyLemniscate>
    ( lemniscate, 1.0, "gauss-lemniscate-1" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyLemniscate>
    ( lemniscate, 0.5, "gauss-lemniscate-0_5" ) ? 1 : 0;
  nb++;
  nbok += testDigitization<Z2i::Space,MyLemniscate>
    ( lemniscate, 0.25, "gauss-lemniscate-0_25" ) ? 1 : 0;
  nb++;
  trace.info() << "(" << nbok << "/" << nb << ") "
         << "true == true" << std::endl;
  trace.endBlock();
  return nbok == nb;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDigitization(), and DGtal::trace.
Referenced by main().