DGtal: volBreadthFirstTraversal.cpp File Reference
volBreadthFirstTraversal.cpp File Reference
DGtal Examples
#include <iostream>
#include <queue>
#include <QImageReader>
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/DrawWithDisplay3DModifier.h"
#include "DGtal/io/Color.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/LightImplicitDigitalSurface.h"
#include "DGtal/io/viewers/Viewer3D.h"
Functions
void usage (int, char **argv)
int main (int argc, char **argv)
Detailed Description
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/02/06
An example file named qglViewer.
This file is part of the DGtal library.
Definition in file volBreadthFirstTraversal.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[volBreadthFirstTraversal-readVol]
[volBreadthFirstTraversal-readVol]
[volBreadthFirstTraversal-KSpace]
[volBreadthFirstTraversal-KSpace]
[volBreadthFirstTraversal-SurfelAdjacency]
[volBreadthFirstTraversal-SurfelAdjacency]
[volBreadthFirstTraversal-SetUpDigitalSurface]
[volBreadthFirstTraversal-SetUpDigitalSurface]
[volBreadthFirstTraversal-ExtractingSurface]
[volBreadthFirstTraversal-ExtractingSurface]
[volBreadthFirstTraversal-DisplayingSurface]
[volBreadthFirstTraversal-DisplayingSurface]
Definition at line 63 of file volBreadthFirstTraversal.cpp.
{
  if ( argc < 4 )
    {
      usage( argc, argv );
      return 1;
    }
  std::string inputFilename = argv[ 1 ];
  unsigned int minThreshold = atoi( argv[ 2 ] );
  unsigned int maxThreshold = atoi( argv[ 3 ] );
  trace.beginBlock( "Reading vol file into an image." );
  typedef ImageSelector < Domain, int>::Type Image;
  Image image = VolReader<Image>::importVol(inputFilename);
  DigitalSet set3d (image.domain());
  SetFromImage<DigitalSet>::append<Image>(set3d, image,
                                          minThreshold, maxThreshold);
  trace.endBlock();
  trace.beginBlock( "Construct the Khalimsky space from the image domain." );
  KSpace ks;
  bool space_ok = ks.init( image.domain().lowerBound(),
                           image.domain().upperBound(), true );
  if (!space_ok)
    {
      trace.error() << "Error in the Khamisky space construction."<<std::endl;
      return 2;
    }
  trace.endBlock();
  typedef SurfelAdjacency<KSpace::dimension> MySurfelAdjacency;
  MySurfelAdjacency surfAdj( true ); // interior in all directions.
  trace.beginBlock( "Set up digital surface." );
  typedef LightImplicitDigitalSurface<KSpace, DigitalSet >
    MyDigitalSurfaceContainer;
  typedef DigitalSurface<MyDigitalSurfaceContainer> MyDigitalSurface;
  SCell bel = Surfaces<KSpace>::findABel( ks, set3d, 100000 );
  MyDigitalSurfaceContainer* ptrSurfContainer =
    new MyDigitalSurfaceContainer( ks, set3d, surfAdj, bel );
  MyDigitalSurface digSurf( ptrSurfContainer ); // acquired
  trace.endBlock();
  trace.beginBlock( "Extracting boundary by tracking from an initial bel." );
  typedef BreadthFirstVisitor<MyDigitalSurface> MyBreadthFirstVisitor;
  typedef MyBreadthFirstVisitor::Node MyNode;
  typedef MyBreadthFirstVisitor::Size MySize;
  MyBreadthFirstVisitor visitor( digSurf, bel );
  unsigned long nbSurfels = 0;
  MyNode node;
  while ( ! visitor.finished() )
    {
      node = visitor.current();
      ++nbSurfels;
      visitor.expand();
    }
  MySize maxDist = node.second;
  trace.endBlock();
  trace.beginBlock( "Displaying surface in Viewer3D." );
  QApplication application(argc,argv);
  Viewer3D<> viewer;
  viewer.show();
  HueShadeColorMap<MySize,1> hueShade( 0, maxDist );
  MyBreadthFirstVisitor visitor2( digSurf, bel );
  viewer << CustomColors3D( Color::Black, Color::White )
         << ks.unsigns( bel );
  visitor2.expand();
  while ( ! visitor2.finished() )
    {
      node = visitor2.current();
      Color c = hueShade( node.second );
      viewer << CustomColors3D( Color::Red, c )
             << ks.unsigns( node.first );
      visitor2.expand();
    }
  viewer << Viewer3D<>::updateDisplay;
  trace.info() << "nb surfels = " << nbSurfels << std::endl;
  trace.endBlock();
  return application.exec();
}
References DGtal::Trace::beginBlock(), DGtal::Color::Black, DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::Color::Red, DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::trace, DGtal::KhalimskySpaceND< dim, TInteger >::unsigns(), and DGtal::Color::White.
usage()
void usage (int , char ** argv)
Definition at line 56 of file volBreadthFirstTraversal.cpp.
{
  std::cerr << "Usage: " << argv[ 0 ] << " <fileName.vol> <minT> <maxT>" << std::endl;
  std::cerr << "\t - displays the boundary of the shape stored in vol file <fileName.vol>." << std::endl;
  std::cerr << "\t - voxel v belongs to the shape iff its value I(v) follows minT <= I(v) <= maxT." << std::endl;
}