DGtal: ArrayLXY< Value, L, X, Y > Class Template Reference
ArrayLXY< Value, L, X, Y > Class Template Reference
Public Member Functions
ArrayLXY (Value invalid)
void clear ()
const Value & value (unsigned int l, unsigned int x, unsigned int y) const
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int, unsigned int)
unsigned long long area () const
Private Attributes
Value _data [L][X][Y]
Value _invalid
Detailed Description
template<typename Value, unsigned int L, unsigned int X, unsigned int Y>
class ArrayLXY< Value, L, X, Y >
Array[L][X][Y] of value. Brute-force. High memory consumption. Rather fast except when working with several labels.
Note that 4000*4000*16 is upper limit on my 8Gb laptop (2Gb). Note that 2000*2000*64 is upper limit on my 8Gb laptop (2Gb).
Definition at line 73 of file testLabelledMap-benchmark.cpp.
Constructor & Destructor Documentation
ArrayLXY()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> ArrayLXY< Value, L, X, Y >::ArrayLXY (Value invalid) inline
Definition at line 79 of file testLabelledMap-benchmark.cpp.
  {
    _invalid = invalid;
    clear();
  }
References _invalid, and clear().
Member Function Documentation
area()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned long long ArrayLXY< Value, L, X, Y >::area () const inline
Definition at line 147 of file testLabelledMap-benchmark.cpp.
  {
    return L * X * Y * sizeof( Value );
  }
References DGtal::L.
clear()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayLXY< Value, L, X, Y >::clear () inline
Definition at line 86 of file testLabelledMap-benchmark.cpp.
  {
    for ( unsigned int l = 0; l < L; ++l )
      for ( unsigned int y = 0; y < Y; ++y )
        for ( unsigned int x = 0; x < X; ++x )
          setValue( _invalid, l, x, y );
  }
References _invalid, DGtal::L, and setValue().
Referenced by ArrayLXY().
display()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayLXY< Value, L, X, Y >::display (ostream & , unsigned int , unsigned int , unsigned int) inline
Definition at line 143 of file testLabelledMap-benchmark.cpp.
  {}
erase()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayLXY< Value, L, X, Y >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 100 of file testLabelledMap-benchmark.cpp.
  {
    if ( _data[ l ][ x ][ y ] != _invalid )
      {
        _data[ l ][ x ][ y ] = _invalid;
        return 1;
      }
    return 0;
  }
References _data, and _invalid.
getLabels()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayLXY< Value, L, X, Y >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 126 of file testLabelledMap-benchmark.cpp.
  {
    labels.clear();
    for ( unsigned int l = 0; l < L; ++l )
      if ( hasLabel( l, x, y ) )
        labels.push_back( l );
  }
References hasLabel(), and DGtal::L.
hasLabel()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> bool ArrayLXY< Value, L, X, Y >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 121 of file testLabelledMap-benchmark.cpp.
  {
    return value( l, x, y ) != _invalid;
  }
References _invalid, and value().
Referenced by getLabels(), and nbLabels().
nbLabels()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayLXY< Value, L, X, Y >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 135 of file testLabelledMap-benchmark.cpp.
  {
    unsigned int nb = 0;
    for ( unsigned int l = 0; l < L; ++l )
      if ( hasLabel( l, x, y ) ) ++nb;
    return nb;
  }
References hasLabel(), and DGtal::L.
setValue()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayLXY< Value, L, X, Y >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 111 of file testLabelledMap-benchmark.cpp.
  {
    _data[ l ][ x ][ y ] = val;
  }
References _data.
Referenced by clear().
setValueNoNewLabel()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayLXY< Value, L, X, Y >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 116 of file testLabelledMap-benchmark.cpp.
  {
    _data[ l ][ x ][ y ] = val;
  }
References _data.
value()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> const Value & ArrayLXY< Value, L, X, Y >::value (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 95 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ l ][ x ][ y ];
  }
References _data.
Referenced by hasLabel().
Field Documentation
_data
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> Value ArrayLXY< Value, L, X, Y >::_data[L][X][Y] private
Definition at line 74 of file testLabelledMap-benchmark.cpp.
Referenced by erase(), setValue(), setValueNoNewLabel(), and value().
_invalid
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> Value ArrayLXY< Value, L, X, Y >::_invalid private
Definition at line 75 of file testLabelledMap-benchmark.cpp.
Referenced by ArrayLXY(), clear(), erase(), and hasLabel().
The documentation for this class was generated from the following file:
testLabelledMap-benchmark.cpp