DGtal: DGtal::Knot_4_1< TSpace > Class Template Reference
DGtal::Knot_4_1< TSpace > Class Template Reference
Aim: Implement a parametrized knot 4, 1.
#include <DGtal/geometry/curves/parametric/Knot_4_1.h>
Public Types
typedef TSpace Space
typedef TSpace::RealPoint RealPoint
typedef TSpace::Point Point
Public Member Functions
~Knot_4_1 ()
Knot_4_1 (long double scale_1, long double scale_2, long double scale_3)
RealPoint x (long double t) const
RealPoint xp (long double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
Knot_4_1 ()
Private Member Functions
Knot_4_1 (const Knot_4_1 &other)
Knot_4_1 & operator= (const Knot_4_1 &other)
Private Attributes
long double scale [3]
Detailed Description
template<typename TSpace>
class DGtal::Knot_4_1< TSpace >
Aim: Implement a parametrized knot 4, 1.
Description of class 'Knot_4_1'
Template Parameters
TSpace model of CSpace
Definition at line 59 of file Knot_4_1.h.
Member Typedef Documentation
Point
template<typename TSpace> typedef TSpace::Point DGtal::Knot_4_1< TSpace >::Point
Definition at line 65 of file Knot_4_1.h.
RealPoint
template<typename TSpace> typedef TSpace::RealPoint DGtal::Knot_4_1< TSpace >::RealPoint
Definition at line 64 of file Knot_4_1.h.
Space
template<typename TSpace> typedef TSpace DGtal::Knot_4_1< TSpace >::Space
Definition at line 63 of file Knot_4_1.h.
Constructor & Destructor Documentation
~Knot_4_1()
template<typename TSpace> DGtal::Knot_4_1< TSpace >::~Knot_4_1 () inline
Destructor.
Definition at line 70 of file Knot_4_1.h.
{}
Knot_4_1() [1/3]
template<typename TSpace> DGtal::Knot_4_1< TSpace >::Knot_4_1 (long double scale_1, long double scale_2, long double scale_3)
Constructor.
Parameters
scale_1 x-axis scaling factor
scale_2 y-axis scaling factor
scale_3 z-axis scaling factor
Referenced by Knot_4_1(), and operator=().
Knot_4_1() [2/3]
template<typename TSpace> DGtal::Knot_4_1< TSpace >::Knot_4_1 () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Knot_4_1() [3/3]
template<typename TSpace> DGtal::Knot_4_1< TSpace >::Knot_4_1 (const Knot_4_1< TSpace > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
References Knot_4_1().
Member Function Documentation
isValid()
template<typename TSpace> bool DGtal::Knot_4_1< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TSpace> Knot_4_1 & DGtal::Knot_4_1< TSpace >::operator= (const Knot_4_1< TSpace > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References Knot_4_1().
selfDisplay()
template<typename TSpace> void DGtal::Knot_4_1< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace> RealPoint DGtal::Knot_4_1< TSpace >::x (long double t) const
Parameters
t any value.
Returns
the vector (x(t), y(t), z(t))
xp()
template<typename TSpace> RealPoint DGtal::Knot_4_1< TSpace >::xp (long double t) const
Parameters
t any value.
Returns
the vector (x(t)', y(t)', z(t)')
Field Documentation
scale
template<typename TSpace> long double DGtal::Knot_4_1< TSpace >::scale[3] private
Definition at line 116 of file Knot_4_1.h.
The documentation for this class was generated from the following file:
Knot_4_1.h