DGtal: DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > Class Template Reference
DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > Class Template Reference
Aim: Computes the true quantity associated to a parametric shape or to a subrange associated to a parametric shape.
#include <DGtal/geometry/curves/estimation/TrueGlobalEstimatorOnPoints.h>
Public Types
typedef TConstIteratorOnPoints ConstIterator
typedef TParametricShape ParametricShape
typedef ParametricShape::RealPoint RealPoint
typedef TParametricShapeFunctor ParametricShapeFunctor
typedef ParametricShapeFunctor::Quantity Quantity
Public Member Functions
TrueGlobalEstimatorOnPoints ()
~TrueGlobalEstimatorOnPoints ()
TrueGlobalEstimatorOnPoints (const TrueGlobalEstimatorOnPoints &)=delete
TrueGlobalEstimatorOnPoints & operator= (const TrueGlobalEstimatorOnPoints &)=delete
void attach (const ParametricShape &aShape)
Quantity eval () const
Quantity eval (const ConstIterator &itb, const ConstIterator &ite, const double h=1.) const
bool isValid () const
Private Attributes
const ParametricShapeFunctor * myFunctorPtr
Parametric quantity functor.
Detailed Description
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor>
class DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >
Aim: Computes the true quantity associated to a parametric shape or to a subrange associated to a parametric shape.
Description of template class 'TrueGlobalEstimatorOnPoints'
Template Parameters
TConstIteratorOnPoints type of iterator on points used as query points.
TParametricShape type of the parametric shape.
TParametricShapeFunctor type of Functor used to evaluate the quantity.
Definition at line 71 of file TrueGlobalEstimatorOnPoints.h.
Member Typedef Documentation
ConstIterator
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TConstIteratorOnPoints DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ConstIterator
Definition at line 77 of file TrueGlobalEstimatorOnPoints.h.
ParametricShape
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TParametricShape DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ParametricShape
Definition at line 79 of file TrueGlobalEstimatorOnPoints.h.
ParametricShapeFunctor
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TParametricShapeFunctor DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ParametricShapeFunctor
Definition at line 82 of file TrueGlobalEstimatorOnPoints.h.
Quantity
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef ParametricShapeFunctor::Quantity DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::Quantity
Definition at line 83 of file TrueGlobalEstimatorOnPoints.h.
RealPoint
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef ParametricShape::RealPoint DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::RealPoint
Definition at line 80 of file TrueGlobalEstimatorOnPoints.h.
Constructor & Destructor Documentation
TrueGlobalEstimatorOnPoints() [1/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::TrueGlobalEstimatorOnPoints ()
Default constructor.
Referenced by operator=(), and TrueGlobalEstimatorOnPoints().
~TrueGlobalEstimatorOnPoints()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::~TrueGlobalEstimatorOnPoints ()
Destructor.
TrueGlobalEstimatorOnPoints() [2/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::TrueGlobalEstimatorOnPoints (const TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > &) delete
Copy constructor.
References TrueGlobalEstimatorOnPoints().
Member Function Documentation
attach()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> void DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::attach (const ParametricShape & aShape)
Attach a shape
Parameters
aShape parametric shape
eval() [1/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> Quantity DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::eval () const
Estimation computed on the total closed attached shape
Returns
the estimated quantity on the shape
eval() [2/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> Quantity DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::eval (const ConstIterator & itb, const ConstIterator & ite, const double h = 1.) const
Estimation on subrange [itb , ite)
Parameters
itb begin iterator
ite end iterator
h grid size (must be > 0).
Returns
the estimated quantity from itb till ite (excluded)
isValid()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> bool DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> TrueGlobalEstimatorOnPoints & DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::operator= (const TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > &) delete
Assignment operator.
References TrueGlobalEstimatorOnPoints().
Field Documentation
myFunctorPtr
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> const ParametricShapeFunctor* DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::myFunctorPtr private
Parametric quantity functor.
Definition at line 145 of file TrueGlobalEstimatorOnPoints.h.
The documentation for this class was generated from the following file:
TrueGlobalEstimatorOnPoints.h