DGtal: DGtal::PlaneProbingRNeighborhood< TPredicate > Class Template Reference
DGtal::PlaneProbingRNeighborhood< TPredicate > Class Template Reference
Aim: Represent a way to probe the R-neighborhood.
#include <DGtal/geometry/surfaces/estimation/PlaneProbingRNeighborhood.h>
Public Types
using Predicate = TPredicate
using Point = typename TPredicate::Point
using Triangle = typename PlaneProbingNeighborhood<TPredicate>::Triangle
using Integer = typename PlaneProbingNeighborhood<TPredicate>::Integer
using PointOnProbingRay = typename PlaneProbingNeighborhood<TPredicate>::PointOnProbingRay
using HexagonState = typename PlaneProbingNeighborhood<TPredicate>::HexagonState
Public Types inherited from DGtal::PlaneProbingNeighborhood< TPredicate >
enum class HexagonState { Empty , NonConvex , NonPlanar , Planar }
using Predicate = TPredicate
using Point = typename Predicate::Point
using Vector = Point
using Integer = typename Point::Coordinate
using Triangle = std::array<Vector, 3>
using Index = std::size_t
using PointOnProbingRay = detail::PointOnProbingRay<Integer,Index>
Public Member Functions
PlaneProbingRNeighborhood ()=delete
PlaneProbingRNeighborhood (Predicate const &aPredicate, Point const &aQ, Triangle const &aM)
~PlaneProbingRNeighborhood ()
PlaneProbingRNeighborhood (const PlaneProbingRNeighborhood &other)=delete
PlaneProbingRNeighborhood (PlaneProbingRNeighborhood &&other)=delete
PlaneProbingRNeighborhood & operator= (const PlaneProbingRNeighborhood &other)=delete
PlaneProbingRNeighborhood & operator= (PlaneProbingRNeighborhood &&other)=delete
virtual HexagonState hexagonState () override
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::PlaneProbingNeighborhood< TPredicate >
PlaneProbingNeighborhood ()=delete
PlaneProbingNeighborhood (Predicate const &aPredicate, Point const &aQ, Triangle const &aM)
virtual ~PlaneProbingNeighborhood ()
PlaneProbingNeighborhood (const PlaneProbingNeighborhood &other)=delete
PlaneProbingNeighborhood (PlaneProbingNeighborhood &&other)=delete
PlaneProbingNeighborhood & operator= (const PlaneProbingNeighborhood &other)=delete
PlaneProbingNeighborhood & operator= (PlaneProbingNeighborhood &&other)=delete
void setNeighbors (std::vector< PointOnProbingRay > const &aNeighbors)
virtual UpdateOperation closestCandidate ()
UpdateOperation getOperation (PointOnProbingRay const &aClosest) const
HexagonState classify (std::array< bool, 6 > const &aState) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
template<typename TPointAdapter>
TPointAdapter closestPointOnRayLogWithPredicate (TPointAdapter const &aRay) const
template<typename TPointAdapter>
TPointAdapter closestPointOnRayLinearWithPredicate (TPointAdapter const &aRay) const
Protected Member Functions inherited from DGtal::PlaneProbingNeighborhood< TPredicate >
template<class TPointAdapter>
TPointAdapter closestPointInList (std::vector< TPointAdapter > const &aPoints) const
bool isNeighbor (PointOnProbingRay const &aRay) const
bool isSmallest (Point const &aX, Point const &aY) const
template<class TPointAdapter>
Point relativePoint (TPointAdapter const &aPoint) const
template<class TPointAdapter>
Point absolutePoint (TPointAdapter const &aPoint) const
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CPointPredicate< TPredicate >))
Additional Inherited Members
Protected Attributes inherited from DGtal::PlaneProbingNeighborhood< TPredicate >
Predicate const & myPredicate
Point const & myQ
Triangle const & myM
std::vector< PointOnProbingRay > myCandidates
std::vector< PointOnProbingRay > myNeighbors
Static Protected Attributes inherited from DGtal::PlaneProbingNeighborhood< TPredicate >
static const PointOnProbingRay myNeighborhood [6]
Detailed Description
template<typename TPredicate>
class DGtal::PlaneProbingRNeighborhood< TPredicate >
Aim: Represent a way to probe the R-neighborhood.
Description of template class 'PlaneProbingRNeighborhood'
Template Parameters
TPredicate the probing predicate, a model of concepts::CPointPredicate.
Definition at line 62 of file PlaneProbingRNeighborhood.h.
Member Typedef Documentation
HexagonState
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::HexagonState = typename PlaneProbingNeighborhood<TPredicate>::HexagonState
Definition at line 73 of file PlaneProbingRNeighborhood.h.
Integer
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::Integer = typename PlaneProbingNeighborhood<TPredicate>::Integer
Definition at line 71 of file PlaneProbingRNeighborhood.h.
Point
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::Point = typename TPredicate::Point
Definition at line 69 of file PlaneProbingRNeighborhood.h.
PointOnProbingRay
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::PointOnProbingRay = typename PlaneProbingNeighborhood<TPredicate>::PointOnProbingRay
Definition at line 72 of file PlaneProbingRNeighborhood.h.
Predicate
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::Predicate = TPredicate
Definition at line 68 of file PlaneProbingRNeighborhood.h.
Triangle
template<typename TPredicate> using DGtal::PlaneProbingRNeighborhood< TPredicate >::Triangle = typename PlaneProbingNeighborhood<TPredicate>::Triangle
Definition at line 70 of file PlaneProbingRNeighborhood.h.
Constructor & Destructor Documentation
PlaneProbingRNeighborhood() [1/4]
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::PlaneProbingRNeighborhood () delete
Default constructor.
Referenced by operator=(), operator=(), PlaneProbingRNeighborhood(), and PlaneProbingRNeighborhood().
PlaneProbingRNeighborhood() [2/4]
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::PlaneProbingRNeighborhood (Predicate const & aPredicate, Point const & aQ, Triangle const & aM)
Constructor.
Parameters
aPredicate a probing predicate.
aQ the fixed point 'q'.
aM a frame composed of the three vectors.
~PlaneProbingRNeighborhood()
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::~PlaneProbingRNeighborhood ()
Destructor.
PlaneProbingRNeighborhood() [3/4]
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::PlaneProbingRNeighborhood (const PlaneProbingRNeighborhood< TPredicate > & other) delete
Copy constructor.
Parameters
other the object to clone.
References PlaneProbingRNeighborhood().
PlaneProbingRNeighborhood() [4/4]
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::PlaneProbingRNeighborhood (PlaneProbingRNeighborhood< TPredicate > && other) delete
Move constructor.
Parameters
other the object to move.
References PlaneProbingRNeighborhood().
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TPredicate> DGtal::PlaneProbingRNeighborhood< TPredicate >::BOOST_CONCEPT_ASSERT ((concepts::CPointPredicate< TPredicate >)) private
closestPointOnRayLinearWithPredicate()
template<typename TPredicate> template<typename TPointAdapter> TPointAdapter DGtal::PlaneProbingRNeighborhood< TPredicate >::closestPointOnRayLinearWithPredicate (TPointAdapter const & aRay) const protected
Finds the closest point on a given ray using a linear search.
Parameters
aRay a ray.
Returns
the closest point on the ray.
closestPointOnRayLogWithPredicate()
template<typename TPredicate> template<typename TPointAdapter> TPointAdapter DGtal::PlaneProbingRNeighborhood< TPredicate >::closestPointOnRayLogWithPredicate (TPointAdapter const & aRay) const protected
Finds the closest point on a given ray using an exponential march and a binary search.
Parameters
aRay a ray.
Returns
the closest point on the ray.
hexagonState()
template<typename TPredicate> virtual HexagonState DGtal::PlaneProbingRNeighborhood< TPredicate >::hexagonState () override virtual
Computes the current state of the neighborhood. This is the function that is overloaded for the different probing modes.
Returns
the hexagon state, see HexagonState.
Implements DGtal::PlaneProbingNeighborhood< TPredicate >.
Reimplemented in DGtal::PlaneProbingLNeighborhood< TPredicate >, and DGtal::PlaneProbingR1Neighborhood< TPredicate >.
isValid()
template<typename TPredicate> bool DGtal::PlaneProbingRNeighborhood< TPredicate >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=() [1/2]
template<typename TPredicate> PlaneProbingRNeighborhood & DGtal::PlaneProbingRNeighborhood< TPredicate >::operator= (const PlaneProbingRNeighborhood< TPredicate > & other) delete
Copy assignment operator.
Parameters
other the object to copy.
Returns
a reference on 'this'.
References PlaneProbingRNeighborhood().
operator=() [2/2]
template<typename TPredicate> PlaneProbingRNeighborhood & DGtal::PlaneProbingRNeighborhood< TPredicate >::operator= (PlaneProbingRNeighborhood< TPredicate > && other) delete
Move assignment operator.
Parameters
other the object to move.
Returns
a reference on 'this'.
References PlaneProbingRNeighborhood().
selfDisplay()
template<typename TPredicate> void DGtal::PlaneProbingRNeighborhood< TPredicate >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
The documentation for this class was generated from the following file:
PlaneProbingRNeighborhood.h