DGtal: DGtal::NGon2D< TSpace > Class Template Reference
DGtal::NGon2D< TSpace > Class Template Reference final
Aim: Model of the concept StarShaped represents any regular k-gon in the plane.
#include <DGtal/shapes/parametric/NGon2D.h>
Public Types
typedef TSpace Space
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
Public Types inherited from DGtal::StarShaped2D< TSpace >
typedef TSpace Space
typedef Space::RealPoint RealPoint
Public Member Functions
NGon2D ()=delete
NGon2D (const double x0, const double y0, const double r, const unsigned int k, const double phi)
NGon2D (const RealPoint &aPoint, const double r, const unsigned int k, const double phi)
NGon2D (const NGon2D &other)
NGon2D & operator= (const NGon2D &other)=delete
~NGon2D ()=default
RealPoint getLowerBound () const
RealPoint getUpperBound () const
RealPoint center () const
void moveTo (const RealPoint &newCenter)
double parameter (const RealPoint &p) const
RealPoint x (const double t) const
RealVector xp (const double t) const
RealVector xpp (const double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::StarShaped2D< TSpace >
StarShaped2D ()=default
StarShaped2D (const StarShaped2D &other)=delete
StarShaped2D & operator= (const StarShaped2D &other)=delete
virtual ~StarShaped2D ()=default
virtual RealPoint interiorPoint () const
Orientation orientation (const RealPoint &p) const
RealPoint tangent (const double t) const
RealPoint normal (const double t) const
double curvature (const double t) const
double arclength (const double t1, double t2, const unsigned int nb) const
RealPoint findIntersection (const RealPoint &inner, const RealPoint &outer, const double epsilon) const
RealPoint closestPointWithWitnesses (const RealPoint &p, const RealPoint &left, const RealPoint &right, const int step) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Attributes
RealPoint myCenter
double myRadius
unsigned int myK
double myPhi
Detailed Description
template<typename TSpace>
class DGtal::NGon2D< TSpace >
Aim: Model of the concept StarShaped represents any regular k-gon in the plane.
Description of template class 'NGon2D'
NB: A backport from ImaGene.
Definition at line 63 of file NGon2D.h.
Member Typedef Documentation
RealPoint
template<typename TSpace> typedef Space::RealPoint DGtal::NGon2D< TSpace >::RealPoint
Definition at line 69 of file NGon2D.h.
RealVector
template<typename TSpace> typedef Space::RealVector DGtal::NGon2D< TSpace >::RealVector
Definition at line 70 of file NGon2D.h.
Space
template<typename TSpace> typedef TSpace DGtal::NGon2D< TSpace >::Space
Definition at line 68 of file NGon2D.h.
Constructor & Destructor Documentation
NGon2D() [1/4]
template<typename TSpace> DGtal::NGon2D< TSpace >::NGon2D () delete
Constructor. Forbidden by default.
Referenced by NGon2D(), and operator=().
NGon2D() [2/4]
template<typename TSpace> DGtal::NGon2D< TSpace >::NGon2D (const double x0, const double y0, const double r, const unsigned int k, const double phi)
Constructor.
Parameters
x0 the x-coordinate of the circle center.
y0 the y-coordinate of the circle center.
r the radius of the circle.
k the number of faces of the k-gon.
phi the phase of the ngon (radian).
References phi().
NGon2D() [3/4]
template<typename TSpace> DGtal::NGon2D< TSpace >::NGon2D (const RealPoint & aPoint, const double r, const unsigned int k, const double phi)
Constructor.
Parameters
aPoint the circle center.
r the radius of the circle.
k the number of faces of the k-gon.
phi the phase of the ngon (radian).
References aPoint, and phi().
NGon2D() [4/4]
template<typename TSpace> DGtal::NGon2D< TSpace >::NGon2D (const NGon2D< TSpace > & other)
Copy constructor.
Parameters
other the object to clone.
References NGon2D().
~NGon2D()
template<typename TSpace> DGtal::NGon2D< TSpace >::~NGon2D () default
Destructor.
Member Function Documentation
center()
template<typename TSpace> RealPoint DGtal::NGon2D< TSpace >::center () const inline virtual
Returns
the center of the star-shaped object.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 143 of file NGon2D.h.
    {
      return myCenter;
    }
References myCenter.
getLowerBound()
template<typename TSpace> RealPoint DGtal::NGon2D< TSpace >::getLowerBound () const inline virtual
Returns
the lower bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 126 of file NGon2D.h.
    {
      return myCenter - myRadius;
    }
References myCenter, and myRadius.
getUpperBound()
template<typename TSpace> RealPoint DGtal::NGon2D< TSpace >::getUpperBound () const inline virtual
Returns
the upper bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 135 of file NGon2D.h.
    {
      return myCenter + myRadius;
    }
References myCenter, and myRadius.
isValid()
template<typename TSpace> bool DGtal::NGon2D< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
moveTo()
template<typename TSpace> void DGtal::NGon2D< TSpace >::moveTo (const RealPoint & newCenter) inline virtual
Modify the shape center
Parameters
newCenter the new center position
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 153 of file NGon2D.h.
    {
      myCenter = newCenter;
    }
References myCenter.
operator=()
template<typename TSpace> NGon2D & DGtal::NGon2D< TSpace >::operator= (const NGon2D< TSpace > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References NGon2D().
parameter()
template<typename TSpace> double DGtal::NGon2D< TSpace >::parameter (const RealPoint & p) const virtual
Parameters
p any point in the plane.
Returns
the angle parameter between 0 and 2*Pi corresponding to this point for the shape.
Implements DGtal::StarShaped2D< TSpace >.
selfDisplay()
template<typename TSpace> void DGtal::NGon2D< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace> RealPoint DGtal::NGon2D< TSpace >::x (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x(t),y(t)) which is the position on the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
xp()
template<typename TSpace> RealVector DGtal::NGon2D< TSpace >::xp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x'(t),y'(t)) which is the tangent to the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
xpp()
template<typename TSpace> RealVector DGtal::NGon2D< TSpace >::xpp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x''(t),y''(t)).
Implements DGtal::StarShaped2D< TSpace >.
Field Documentation
myCenter
template<typename TSpace> RealPoint DGtal::NGon2D< TSpace >::myCenter private
Center of the circle.
Definition at line 197 of file NGon2D.h.
Referenced by center(), getLowerBound(), getUpperBound(), and moveTo().
myK
template<typename TSpace> unsigned int DGtal::NGon2D< TSpace >::myK private
Number of sides of the ngon.
Definition at line 207 of file NGon2D.h.
myPhi
template<typename TSpace> double DGtal::NGon2D< TSpace >::myPhi private
Phase of the ngon (radian).
Definition at line 212 of file NGon2D.h.
myRadius
template<typename TSpace> double DGtal::NGon2D< TSpace >::myRadius private
Radius of the circle.
Definition at line 202 of file NGon2D.h.
Referenced by getLowerBound(), and getUpperBound().
The documentation for this class was generated from the following file:
NGon2D.h