DGtal: DGtal::CircleFrom2Points< TPoint > Class Template Reference
DGtal::CircleFrom2Points< TPoint > Class Template Reference
Aim: Represents a circle that passes through a given point and that is thus uniquely defined by two other points. It is able to return for any given point its signed distance to itself.
#include <DGtal/shapes/fromPoints/CircleFrom2Points.h>
Public Types
typedef TPoint::Coordinate Coordinate
typedef Coordinate Distance
typedef TPoint Point
typedef TPoint Vector
Public Member Functions
CircleFrom2Points (const Point &aPole)
CircleFrom2Points (const Point &aPole, const Point &aFirstPoint, const Point &aSecondPoint)
void init (const Point &aFirstPoint, const Point &aSecondPoint)
CircleFrom2Points (const CircleFrom2Points &other)
CircleFrom2Points & operator= (const CircleFrom2Points &other)
~CircleFrom2Points ()
void selfDisplay (std::ostream &out) const
bool isValid () const
Distance signedDistance (const Point &aP) const
void getParameters (double &cx, double &cy, double &r) const
const Point & pole () const
const Point & p () const
const Point & q () const
std::string className () const
Private Attributes
Point myPole
Point myP
Point myQ
Detailed Description
template<typename TPoint>
class DGtal::CircleFrom2Points< TPoint >
Aim: Represents a circle that passes through a given point and that is thus uniquely defined by two other points. It is able to return for any given point its signed distance to itself.
Template Parameters
TPoint a type of points.
Examples
geometry/tools/examplePreimage.cpp.
Definition at line 67 of file CircleFrom2Points.h.
Member Typedef Documentation
Coordinate
template<typename TPoint> typedef TPoint::Coordinate DGtal::CircleFrom2Points< TPoint >::Coordinate
Definition at line 73 of file CircleFrom2Points.h.
Distance
template<typename TPoint> typedef Coordinate DGtal::CircleFrom2Points< TPoint >::Distance
Definition at line 74 of file CircleFrom2Points.h.
Point
template<typename TPoint> typedef TPoint DGtal::CircleFrom2Points< TPoint >::Point
Definition at line 75 of file CircleFrom2Points.h.
Vector
template<typename TPoint> typedef TPoint DGtal::CircleFrom2Points< TPoint >::Vector
Definition at line 76 of file CircleFrom2Points.h.
Constructor & Destructor Documentation
CircleFrom2Points() [1/3]
template<typename TPoint> DGtal::CircleFrom2Points< TPoint >::CircleFrom2Points (const Point & aPole)
Constructor.
Parameters
aPole a point
Referenced by CircleFrom2Points(), and operator=().
CircleFrom2Points() [2/3]
template<typename TPoint> DGtal::CircleFrom2Points< TPoint >::CircleFrom2Points (const Point & aPole, const Point & aFirstPoint, const Point & aSecondPoint)
Constructor with initialization.
Parameters
aPole a point
aFirstPoint a point
aSecondPoint a second point
CircleFrom2Points() [3/3]
template<typename TPoint> DGtal::CircleFrom2Points< TPoint >::CircleFrom2Points (const CircleFrom2Points< TPoint > & other)
Copy constructor.
Parameters
other the object to clone.
References CircleFrom2Points().
~CircleFrom2Points()
template<typename TPoint> DGtal::CircleFrom2Points< TPoint >::~CircleFrom2Points ()
Destructor. Does nothing
Member Function Documentation
className()
template<typename TPoint> std::string DGtal::CircleFrom2Points< TPoint >::className () const
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
getParameters()
template<typename TPoint> void DGtal::CircleFrom2Points< TPoint >::getParameters (double & cx, double & cy, double & r) const
Computes the parameters of the circle
Parameters
cx returned x-coordinate of the circle
cy returned y-coordinate of the circle
r returned radius of the circle
init()
template<typename TPoint> void DGtal::CircleFrom2Points< TPoint >::init (const Point & aFirstPoint, const Point & aSecondPoint)
Init.
Parameters
aFirstPoint a point
aSecondPoint a second point
isValid()
template<typename TPoint> bool DGtal::CircleFrom2Points< TPoint >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TPoint> CircleFrom2Points & DGtal::CircleFrom2Points< TPoint >::operator= (const CircleFrom2Points< TPoint > & other)
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
References CircleFrom2Points().
p()
template<typename TPoint> const Point & DGtal::CircleFrom2Points< TPoint >::p () const inline
Returns
the second point through which the circle passes.
Definition at line 163 of file CircleFrom2Points.h.
    {
      return myP;
    };
References myP.
pole()
template<typename TPoint> const Point & DGtal::CircleFrom2Points< TPoint >::pole () const inline
Returns
the first (and not mutable) point through which the circle passes.
Definition at line 155 of file CircleFrom2Points.h.
    {
      return myPole;
    };
References myPole.
q()
template<typename TPoint> const Point & DGtal::CircleFrom2Points< TPoint >::q () const inline
Returns
the third point through which the circle passes.
Definition at line 171 of file CircleFrom2Points.h.
    {
      return myQ;
    };
References myQ.
selfDisplay()
template<typename TPoint> void DGtal::CircleFrom2Points< TPoint >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
signedDistance()
template<typename TPoint> Distance DGtal::CircleFrom2Points< TPoint >::signedDistance (const Point & aP) const
Computes the signed distance of aP to the circle
Parameters
aP the point to be tested.
Returns
the signed distance.
Field Documentation
myP
template<typename TPoint> Point DGtal::CircleFrom2Points< TPoint >::myP private
Second point through which the circle passes
Definition at line 200 of file CircleFrom2Points.h.
Referenced by p().
myPole
template<typename TPoint> Point DGtal::CircleFrom2Points< TPoint >::myPole private
First (and not mutable) point through which the circle passes
Definition at line 196 of file CircleFrom2Points.h.
Referenced by pole().
myQ
template<typename TPoint> Point DGtal::CircleFrom2Points< TPoint >::myQ private
Third point through which the circle passes
Definition at line 204 of file CircleFrom2Points.h.
Referenced by q().
The documentation for this class was generated from the following file:
CircleFrom2Points.h