DGtal: DGtal::MLPLengthEstimator< TConstIterator > Class Template Reference
DGtal::MLPLengthEstimator< TConstIterator > Class Template Reference
Aim: a model of CGlobalCurveEstimator that computes the length of a digital curve using its MLP (given by the FP)
#include <DGtal/geometry/curves/estimation/MLPLengthEstimator.h>
Public Types
typedef TConstIterator ConstIterator
typedef double Quantity
typedef FP< ConstIterator, int, 4 > FaithfulPolygon
typedef FaithfulPolygon::RealPoint Point
typedef FaithfulPolygon::RealVector Vector
Public Member Functions
MLPLengthEstimator ()=default
~MLPLengthEstimator ()=default
MLPLengthEstimator (const MLPLengthEstimator &other)=delete
MLPLengthEstimator & operator= (const MLPLengthEstimator &other)=delete
Quantity eval (const ConstIterator &itb, const ConstIterator &ite, const double h=1.) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Detailed Description
template<typename TConstIterator>
class DGtal::MLPLengthEstimator< TConstIterator >
Aim: a model of CGlobalCurveEstimator that computes the length of a digital curve using its MLP (given by the FP)
Description of template class 'MLPLengthEstimator'
Model of CGlobalCurveGeometricEstimator
Template Parameters
TConstIterator a model of CConstIteratorOnPoints.
Definition at line 69 of file MLPLengthEstimator.h.
Member Typedef Documentation
ConstIterator
template<typename TConstIterator> typedef TConstIterator DGtal::MLPLengthEstimator< TConstIterator >::ConstIterator
Definition at line 76 of file MLPLengthEstimator.h.
FaithfulPolygon
template<typename TConstIterator> typedef FP<ConstIterator,int,4> DGtal::MLPLengthEstimator< TConstIterator >::FaithfulPolygon
Definition at line 80 of file MLPLengthEstimator.h.
Point
template<typename TConstIterator> typedef FaithfulPolygon::RealPoint DGtal::MLPLengthEstimator< TConstIterator >::Point
Definition at line 81 of file MLPLengthEstimator.h.
Quantity
template<typename TConstIterator> typedef double DGtal::MLPLengthEstimator< TConstIterator >::Quantity
Definition at line 78 of file MLPLengthEstimator.h.
Vector
template<typename TConstIterator> typedef FaithfulPolygon::RealVector DGtal::MLPLengthEstimator< TConstIterator >::Vector
Definition at line 82 of file MLPLengthEstimator.h.
Constructor & Destructor Documentation
MLPLengthEstimator() [1/2]
template<typename TConstIterator> DGtal::MLPLengthEstimator< TConstIterator >::MLPLengthEstimator () default
Default Constructor.
Referenced by MLPLengthEstimator(), and operator=().
~MLPLengthEstimator()
template<typename TConstIterator> DGtal::MLPLengthEstimator< TConstIterator >::~MLPLengthEstimator () default
Destructor.
MLPLengthEstimator() [2/2]
template<typename TConstIterator> DGtal::MLPLengthEstimator< TConstIterator >::MLPLengthEstimator (const MLPLengthEstimator< TConstIterator > & other) delete
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
References MLPLengthEstimator().
Member Function Documentation
eval()
template<typename TConstIterator> Quantity DGtal::MLPLengthEstimator< TConstIterator >::eval (const ConstIterator & itb, const ConstIterator & ite, const double h = 1.) const
Computation of the l1 length of the curve. Complexity: O(|Range|)
Parameters
itb begin iterator
ite end iterator
h grid size (must be > 0).
Returns
the curve length.
Referenced by testL1LengthEstimator().
isValid()
template<typename TConstIterator> bool DGtal::MLPLengthEstimator< TConstIterator >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TConstIterator> MLPLengthEstimator & DGtal::MLPLengthEstimator< TConstIterator >::operator= (const MLPLengthEstimator< TConstIterator > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References MLPLengthEstimator().
selfDisplay()
template<typename TConstIterator> void DGtal::MLPLengthEstimator< TConstIterator >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
The documentation for this class was generated from the following file:
MLPLengthEstimator.h