DGtal: DGtal::IVector< T, TAlloc, true > Class Template Reference
DGtal::IVector< T, TAlloc, true > Class Template Reference
#include <DGtal/math/MPolynomial.h>
Public Types
typedef TAlloc Alloc
typedef std::allocator_traits< Alloc >::pointer TPointer
typedef std::vector< TPointer, typenamestd::allocator_traits< Alloc >::templaterebind_alloc< TPointer > >::size_type Size
Public Member Functions
IVector (const Alloc &allocator=Alloc())
IVector (Size aSize, const Alloc &allocator=Alloc())
IVector (Size aSize, const T &entry, const Alloc &allocator=Alloc())
IVector (const IVector &v)
~IVector ()
IVector & operator= (const IVector &v)
Size size () const
void resize (Size aSize, const T &entry=T())
const T & operator[] (Size i) const
T & operator[] (Size i)
const T & back () const
T & back ()
void swap (IVector &v)
Alloc get_allocator () const
Alloc getAllocator () const
Private Member Functions
void create (Size begin, Size end, const typename Alloc::value_type &entry)
void free (Size begin, Size end)
template<class A>
void copy_from (const std::vector< TPointer, A > &source)
Private Attributes
Alloc myAllocator
std::vector< TPointer, typename std::allocator_traits< Alloc >::template rebind_alloc< TPointer > > myVec
Detailed Description
template<typename T, typename TAlloc>
class DGtal::IVector< T, TAlloc, true >
Specialization that is using std::vector<T*>, but behaving like std::vector<T>.
Definition at line 805 of file MPolynomial.h.
Member Typedef Documentation
Alloc
template<typename T, typename TAlloc> typedef TAlloc DGtal::IVector< T, TAlloc, true >::Alloc
Definition at line 808 of file MPolynomial.h.
Size
template<typename T, typename TAlloc> typedef std::vector<TPointer,typenamestd::allocator_traits<Alloc>::templaterebind_alloc<TPointer>>::size_type DGtal::IVector< T, TAlloc, true >::Size
Definition at line 810 of file MPolynomial.h.
TPointer
template<typename T, typename TAlloc> typedef std::allocator_traits<Alloc>::pointer DGtal::IVector< T, TAlloc, true >::TPointer
Definition at line 809 of file MPolynomial.h.
Constructor & Destructor Documentation
IVector() [1/4]
template<typename T, typename TAlloc> DGtal::IVector< T, TAlloc, true >::IVector (const Alloc & allocator = Alloc()) inline
Definition at line 847 of file MPolynomial.h.
      : myAllocator(allocator), myVec(allocator)
    {}
References myAllocator, and myVec.
Referenced by IVector(), operator=(), and swap().
IVector() [2/4]
template<typename T, typename TAlloc> DGtal::IVector< T, TAlloc, true >::IVector (Size aSize, const Alloc & allocator = Alloc()) inline
Definition at line 851 of file MPolynomial.h.
      : myAllocator(allocator), myVec(aSize, 0, allocator)
    {
      create(0, aSize, T());
    }
References create(), myAllocator, and myVec.
IVector() [3/4]
template<typename T, typename TAlloc> DGtal::IVector< T, TAlloc, true >::IVector (Size aSize, const T & entry, const Alloc & allocator = Alloc()) inline
Definition at line 857 of file MPolynomial.h.
      : myAllocator(allocator), myVec(aSize, 0, allocator)
    {
      create(0, aSize, entry);
    }
References create(), myAllocator, and myVec.
IVector() [4/4]
template<typename T, typename TAlloc> DGtal::IVector< T, TAlloc, true >::IVector (const IVector< T, TAlloc, true > & v) inline
Definition at line 863 of file MPolynomial.h.
      : myVec(v.size())
    {
      copy_from(v.myVec);
    }
References copy_from(), IVector(), DGtal::IVector< T, TAlloc, usePointers >::myVec, myVec, and size().
~IVector()
template<typename T, typename TAlloc> DGtal::IVector< T, TAlloc, true >::~IVector () inline
Definition at line 869 of file MPolynomial.h.
    {
      free(0, (Size)myVec.size());
    }
References free(), and myVec.
Member Function Documentation
back() [1/2]
template<typename T, typename TAlloc> T & DGtal::IVector< T, TAlloc, true >::back () inline
Definition at line 915 of file MPolynomial.h.
    {
      return *myVec.back();
    }
References myVec.
back() [2/2]
template<typename T, typename TAlloc> const T & DGtal::IVector< T, TAlloc, true >::back () const inline
Definition at line 910 of file MPolynomial.h.
    {
      return *myVec.back();
    }
References myVec.
copy_from()
template<typename T, typename TAlloc> template<class A> void DGtal::IVector< T, TAlloc, true >::copy_from (const std::vector< TPointer, A > & source) inline private
Definition at line 837 of file MPolynomial.h.
    {
      for (Size i = 0; i < myVec.size(); ++i)
        {
          myVec[i] = myAllocator.allocate(sizeof(T));
          std::allocator_traits<Alloc>::construct(myAllocator, myVec[i], *source[i]);
        }
    }
References myAllocator, and myVec.
Referenced by IVector(), and operator=().
create()
template<typename T, typename TAlloc> void DGtal::IVector< T, TAlloc, true >::create (Size begin, Size end, const typename Alloc::value_type & entry) inline private
Definition at line 818 of file MPolynomial.h.
    {
      for (Size i = begin; i < end; ++i)
        {
          myVec[i] = myAllocator.allocate(sizeof(T));
          std::allocator_traits<Alloc>::construct(myAllocator, myVec[i], entry);
        }
    }
References myAllocator, and myVec.
Referenced by IVector(), IVector(), and resize().
free()
template<typename T, typename TAlloc> void DGtal::IVector< T, TAlloc, true >::free (Size begin, Size end) inline private
Definition at line 827 of file MPolynomial.h.
    {
      for (Size i = begin; i < end; ++i)
        {
          std::allocator_traits<Alloc>::destroy(myAllocator, myVec[i]);
          myAllocator.deallocate(myVec[i], sizeof(T));
        }
    }
References myAllocator, and myVec.
Referenced by operator=(), resize(), and ~IVector().
get_allocator()
template<typename T, typename TAlloc> Alloc DGtal::IVector< T, TAlloc, true >::get_allocator () const inline
Definition at line 925 of file MPolynomial.h.
    {
      return myVec.get_allocator();
    }
References myVec.
getAllocator()
template<typename T, typename TAlloc> Alloc DGtal::IVector< T, TAlloc, true >::getAllocator () const inline
Definition at line 930 of file MPolynomial.h.
    {
      return myVec.get_allocator();
    }
References myVec.
operator=()
template<typename T, typename TAlloc> IVector & DGtal::IVector< T, TAlloc, true >::operator= (const IVector< T, TAlloc, true > & v) inline
Definition at line 874 of file MPolynomial.h.
    {
      if (&v != this)
        {
          free(0, (Size)myVec.size());
          myVec.resize(v.size());
          copy_from(v.myVec);
        }
      return *this;
    }
References copy_from(), free(), IVector(), DGtal::IVector< T, TAlloc, usePointers >::myVec, myVec, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator[]() [1/2]
template<typename T, typename TAlloc> T & DGtal::IVector< T, TAlloc, true >::operator[] (Size i) inline
Definition at line 905 of file MPolynomial.h.
    {
      return *myVec[i];
    }
References myVec.
operator[]() [2/2]
template<typename T, typename TAlloc> const T & DGtal::IVector< T, TAlloc, true >::operator[] (Size i) const inline
Definition at line 900 of file MPolynomial.h.
    {
      return *myVec[i];
    }
References myVec.
resize()
template<typename T, typename TAlloc> void DGtal::IVector< T, TAlloc, true >::resize (Size aSize, const T & entry = T()) inline
Definition at line 890 of file MPolynomial.h.
    {
      Size oldsize = (Size)myVec.size();
      if (oldsize > aSize)
        free(aSize, oldsize);
      myVec.resize(aSize);
      if (oldsize < aSize)
        create(oldsize, aSize, entry);
    }
References create(), free(), and myVec.
size()
template<typename T, typename TAlloc> Size DGtal::IVector< T, TAlloc, true >::size () const inline
Definition at line 885 of file MPolynomial.h.
    {
      return (Size)myVec.size();
    }
References myVec.
Referenced by IVector().
swap()
template<typename T, typename TAlloc> void DGtal::IVector< T, TAlloc, true >::swap (IVector< T, TAlloc, true > & v) inline
Definition at line 920 of file MPolynomial.h.
    {
      myVec.swap(v.myVec);
    }
References IVector(), DGtal::IVector< T, TAlloc, usePointers >::myVec, and myVec.
Field Documentation
myAllocator
template<typename T, typename TAlloc> Alloc DGtal::IVector< T, TAlloc, true >::myAllocator private
Definition at line 813 of file MPolynomial.h.
Referenced by copy_from(), create(), free(), IVector(), IVector(), and IVector().
myVec
template<typename T, typename TAlloc> std::vector<TPointer, typename std::allocator_traits<Alloc>::template rebind_alloc<TPointer> > DGtal::IVector< T, TAlloc, true >::myVec private
Definition at line 814 of file MPolynomial.h.
Referenced by back(), back(), copy_from(), create(), free(), get_allocator(), getAllocator(), IVector(), IVector(), IVector(), IVector(), operator=(), operator[](), operator[](), resize(), size(), swap(), and ~IVector().
The documentation for this class was generated from the following file:
MPolynomial.h