DGtal: labelledMapBestParameters.cpp File Reference
labelledMapBestParameters.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/base/LabelledMap.h"
Functions
void usage ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2011/03/05
An example file named labelledMapBestParameters.
This file is part of the DGtal library.
Definition in file labelledMapBestParameters.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 50 of file labelledMapBestParameters.cpp.
{
  typedef double Data;
  if ( argc < 4 )
    {
      usage();
      return 1;
    }
  std::pair< unsigned int, unsigned int > res =
    DGtal::detail::argminLabelledMapMemoryUsageForGeometricDistribution<Data>
    ( atoi( argv[ 1 ] ), atof( argv[ 3 ] ), atof( argv[ 2 ] ) );
  cout << res.first << " " << res.second << endl;
  return 0;
}
References DGtal::detail::argminLabelledMapMemoryUsageForGeometricDistribution(), and usage().
usage()
void usage ()
Examples
arithmetic/approximation.cpp, arithmetic/convergents-biginteger.cpp, arithmetic/convergents.cpp, arithmetic/extended-euclid.cpp, arithmetic/fraction.cpp, arithmetic/lower-integer-convex-hull.cpp, arithmetic/pattern.cpp, geometry/meshes/curvature-comparator-ii-cnc-3d.cpp, geometry/meshes/curvature-measures-icnc-3d.cpp, geometry/meshes/curvature-measures-icnc-XY-3d.cpp, geometry/meshes/curvature-measures-nc-3d.cpp, geometry/meshes/curvature-measures-nc-XY-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-3d.cpp, geometry/meshes/digpoly-curvature-measures-cnc-XY-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-3d.cpp, geometry/meshes/obj-curvature-measures-icnc-XY-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-3d.cpp, geometry/meshes/vol-curvature-measures-icnc-XY-3d.cpp, graph/volDistanceTraversal.cpp, math/polynomial-derivative.cpp, math/polynomial2-derivative.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, and topology/volTrackBoundary.cpp.
Definition at line 40 of file labelledMapBestParameters.cpp.
{
  cerr << "Usage: ./labelledMapBestParameters <L> <p> <q>" << endl
       << "       Tries to find the best values N and M which will minimized" << endl
       << "       the memory usage of a LabelledMap, for the distribution" << endl
       << "       specified by the parameters." << endl
       << "       - L: max number of labels." << endl
       << "       - p: If there is a possibility to have a data, this probability is used to define a geometric distribution that defines the number of data (ie valid labels) at this place. The smaller, the higher is the expectation. 0.5 means E(X) = 1.." << endl
       << "       - q: probability that there is no data at this location." << endl;
}
Referenced by main(), and main().