DGtal: lower-integer-convex-hull.cpp File Reference
lower-integer-convex-hull.cpp File Reference
DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/arithmetic/LatticePolytope2D.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
Functions
void usage (int, char **argv)
int main (int argc, char **argv)
Detailed Description
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/02/06
An example file named lower-integer-convex-hull.
This file is part of the DGtal library.
Definition in file lower-integer-convex-hull.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Main.
[lower-integer-convex-hull-types]
[lower-integer-convex-hull-types]
[lower-integer-convex-hull-instantiation]
[lower-integer-convex-hull-instantiation]
[lower-integer-convex-hull-process]
[lower-integer-convex-hull-process]
[lower-integer-convex-hull-stats]
[lower-integer-convex-hull-stats]
Definition at line 67 of file lower-integer-convex-hull.cpp.
{
  if ( argc < 4 )
    {
      usage( argc, argv );
      return 0;
    }
  using namespace Z2i;
  typedef LatticePolytope2D<Space> CIP;
  CIP cip;
  cip.push_front( Point( -10, -10 ) );
  cip.push_front( Point( -10, 10 ) );
  cip.push_front( Point( 10, 10 ) );
  cip.push_front( Point( 10, -10 ) );
  Domain domain = cip.boundingBoxDomain();
  Board2D board;
  board << domain
        << CustomStyle( cip.className(),
                        new CustomColors( Color::Red, Color::None ) )
        << cip;
  board.saveEPS( "lower-integer-convex-hull.eps" );
  board.clear();
  int a = atoi( argv[ 1 ] );
  int b = atoi( argv[ 2 ] );
  int c = atoi( argv[ 3 ] );
  typedef LatticePolytope2D<Z2>::HalfSpace HalfSpace;
  HalfSpace hs( Vector( a, b ), c );
  cip.cut( hs );
  DigitalSet aSet( domain );
  Shapes<Domain>::makeSetFromPointPredicate( aSet, hs );
  board << domain
        << CustomStyle( aSet.className(),
                        new CustomColors( Color::Green, Color::Green ) )
        << SetMode( Point().className(), "Grid" )
        << aSet
        << CustomStyle( cip.className(),
                        new CustomColors( Color::Red, Color::None ) )
        << cip;
  board.saveEPS( "lower-integer-convex-hull-cut.eps" );
  std::cout << "Number of vertices        = " << cip.size() << std::endl;
  std::cout << "Area                      = " << (((double)cip.twiceArea())/2.0) << std::endl;
  std::cout << "Number of interior points = " << cip.numberInteriorPoints() << std::endl;
  std::cout << "Number of boundary points = " << cip.numberBoundaryPoints() << std::endl;
  return 0;
}
References DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::className(), LibBoard::Board::clear(), domain, DGtal::Color::Green, DGtal::Shapes< TDomain >::makeSetFromPointPredicate(), DGtal::Color::None, DGtal::LatticePolytope2D< TSpace, TSequence >::push_front(), DGtal::Color::Red, LibBoard::Board::saveEPS(), and usage().
usage()
void usage (int , char ** argv)
Definition at line 57 of file lower-integer-convex-hull.cpp.
{
  std::cerr << "Usage: " << argv[ 0 ] << " <a> <b> <c>" << std::endl;
  std::cerr << "\t - Cuts a square by ax+by <= c. Displays everything in files "
            << "lower-integer-convex-hull*.eps" << std::endl;
}