DGtal: mesh3DConstructionAndVisualisation.cpp File Reference
mesh3DConstructionAndVisualisation.cpp File Reference
DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/Mesh.h"
#include "DGtal/io/viewers/PolyscopeViewer.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2013/01/10
Example of Mesh construction and visualisation.
This file is part of the DGtal library.
Definition in file mesh3DConstructionAndVisualisation.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[MeshUseInitDisplay]
[MeshUseInitDisplay]
[MeshUseMeshCreation]
[MeshUseMeshConstructor]
[MeshUseMeshConstructor]
[MeshUseMeshAddingPoints]
[MeshUseMeshAddingPoints]
[MeshUseMeshAddingBasicFaces]
[MeshUseMeshAddingBasicFaces]
[MeshUseMeshAddingPolygonalFaces]
[MeshUseMeshAddingPolygonalFaces] [MeshUseMeshCreation]
[MeshUseDisplay]
[MeshUseDisplay]
Definition at line 53 of file mesh3DConstructionAndVisualisation.cpp.
{
  PolyscopeViewer<> viewer;
  // A mesh is constructed and faces are added from the vertex set.
  Mesh<Point> aMesh(true);
  aMesh.addVertex(Point(0,0,0));
  aMesh.addVertex(Point(1,0,0));
  aMesh.addVertex(Point(1,1,0));
  aMesh.addVertex(Point(0,0,1));
  aMesh.addVertex(Point(1,0,1));
  aMesh.addVertex(Point(1,1,1));
  aMesh.addVertex(Point(0,1,1));
  aMesh.addVertex(Point(0,1,0));
  aMesh.addVertex(Point(0,2,0));
  aMesh.addVertex(Point(0,3,1));
  aMesh.addVertex(Point(0,2,2));
  aMesh.addVertex(Point(0,1,2));
  aMesh.addVertex(Point(0,0,1));
  aMesh.addTriangularFace(0, 1, 2, Color(150,0,150,104));
  aMesh.addQuadFace(6,5,4,3, Color::Blue);
  Mesh<Point>::MeshFace listIndex;
  listIndex.push_back(7);
  listIndex.push_back(8);
  listIndex.push_back(9);
  listIndex.push_back(10);
  listIndex.push_back(11);
  listIndex.push_back(12);
  aMesh.addFace(listIndex, Color(150,150,0,54));
  viewer.drawColor(Color(150,0,0,254));
  viewer << aMesh;
  viewer.show();
  return 0;
}
References DGtal::Mesh< TPoint >::addFace(), DGtal::Mesh< TPoint >::addQuadFace(), DGtal::Mesh< TPoint >::addTriangularFace(), DGtal::Mesh< TPoint >::addVertex(), DGtal::Color::Blue, DGtal::Display3D< Space, KSpace >::drawColor(), and DGtal::PolyscopeViewer< Space, KSpace >::show().