DGtal: pConvexity-benchmark.cpp File Reference
pConvexity-benchmark.cpp File Reference
DGtal Examples
#include <iostream>
#include <vector>
#include <algorithm>
#include <chrono>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetBySTLSet.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/geometry/volumes/PConvexity.h"
#include "DGtal/geometry/volumes/DigitalConvexity.h"
Functions
double rand01 ()
template<Dimension dim>
void timingsPConvexity (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double pconvexity_probability=0.5)
template<Dimension dim>
void timingsFullConvexity (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double fconvexity_probability=0.5)
template<Dimension dim>
void timingsFullConvexityFast (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double fconvexity_probability=0.5)
template<Dimension dim>
void timingsPConvexityNonConvex (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t range)
template<Dimension dim>
void timingsFullConvexityNonConvex (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t range)
template<Dimension dim>
void timingsFullConvexityFastNonConvex (std::vector< std::tuple< std::size_t, double, bool > > &results, std::size_t nb_tries, std::size_t range)
void outputResults (Dimension dim, const std::vector< std::tuple< std::size_t, double, bool > > &results, const std::string &fname)
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2024/06/26
An example file named pConvexity-benchmark
This file is part of the DGtal library.
Definition in file pConvexity-benchmark.cpp.
Function Documentation
main()
int main (void)
Definition at line 391 of file pConvexity-benchmark.cpp.
{
  // P-convexity
  srand( 0 );
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsPConvexity<2>( R2, 50, 3, 100, 0.5 );
      timingsPConvexity<2>( R2, 50, 4, 200, 0.5 );
      timingsPConvexity<2>( R2, 50, 5, 400, 0.5 );
      timingsPConvexity<2>( R2, 50, 5, 600, 0.5 );
      timingsPConvexity<2>( R2, 50, 5, 800, 0.5 );
      timingsPConvexity<2>( R2, 25, 5,1200, 0.5 );
      timingsPConvexity<2>( R2, 25, 5,2000, 0.5 );
      outputResults( 2, R2, "timings-p-convexity-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsPConvexity<3>( R3, 50, 3, 10, 0.5 );
      timingsPConvexity<3>( R3, 50, 4, 20, 0.5 );
      timingsPConvexity<3>( R3, 50, 5, 40, 0.5 );
      timingsPConvexity<3>( R3, 50, 5, 80, 0.5 );
      timingsPConvexity<3>( R3, 25, 5, 160, 0.5 );
      timingsPConvexity<3>( R3, 25, 5, 320, 0.5 );
      outputResults( 3, R3, "timings-p-convexity-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsPConvexity<4>( R4, 50, 5, 10, 0.5 );
      timingsPConvexity<4>( R4, 50, 5, 15, 0.5 );
      timingsPConvexity<4>( R4, 50, 5, 20, 0.5 );
      timingsPConvexity<4>( R4, 50, 5, 30, 0.5 );
      timingsPConvexity<4>( R4, 25, 5, 40, 0.5 );
      timingsPConvexity<4>( R4, 25, 5, 60, 0.5 );
      timingsPConvexity<4>( R4, 15, 6, 80, 0.5 );
      timingsPConvexity<4>( R4, 15, 6, 100, 0.5 );
      timingsPConvexity<4>( R4, 15, 6, 120, 0.5 );
      outputResults( 4, R4, "timings-p-convexity-Z4.txt" );
    }
  // Full convexity
  srand( 0 );
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsFullConvexity<2>( R2, 50, 3, 100, 0.5 );
      timingsFullConvexity<2>( R2, 50, 4, 200, 0.5 );
      timingsFullConvexity<2>( R2, 50, 5, 400, 0.5 );
      timingsFullConvexity<2>( R2, 50, 5, 600, 0.5 );
      timingsFullConvexity<2>( R2, 50, 5, 800, 0.5 );
      timingsFullConvexity<2>( R2, 25, 5,1200, 0.5 );
      timingsFullConvexity<2>( R2, 25, 5,2000, 0.5 );
      outputResults( 2, R2, "timings-fc-convexity-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsFullConvexity<3>( R3, 50, 3, 10, 0.5 );
      timingsFullConvexity<3>( R3, 50, 4, 20, 0.5 );
      timingsFullConvexity<3>( R3, 50, 5, 40, 0.5 );
      timingsFullConvexity<3>( R3, 50, 5, 80, 0.5 );
      timingsFullConvexity<3>( R3, 25, 5, 160, 0.5 );
      timingsFullConvexity<3>( R3, 25, 5, 320, 0.5 );
      outputResults( 3, R3, "timings-fc-convexity-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsFullConvexity<4>( R4, 50, 5, 10, 0.5 );
      timingsFullConvexity<4>( R4, 50, 5, 15, 0.5 );
      timingsFullConvexity<4>( R4, 50, 5, 20, 0.5 );
      timingsFullConvexity<4>( R4, 50, 5, 30, 0.5 );
      timingsFullConvexity<4>( R4, 25, 5, 40, 0.5 );
      timingsFullConvexity<4>( R4, 25, 5, 60, 0.5 );
      timingsFullConvexity<4>( R4, 15, 6, 80, 0.5 );
      timingsFullConvexity<4>( R4, 10, 6, 100, 0.5 );
      timingsFullConvexity<4>( R4, 5, 6, 120, 0.5 );
      outputResults( 4, R4, "timings-fc-convexity-Z4.txt" );
    }
  // Full convexity fast
  srand( 0 );
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsFullConvexityFast<2>( R2, 50, 3, 100, 0.5 );
      timingsFullConvexityFast<2>( R2, 50, 4, 200, 0.5 );
      timingsFullConvexityFast<2>( R2, 50, 5, 400, 0.5 );
      timingsFullConvexityFast<2>( R2, 50, 5, 600, 0.5 );
      timingsFullConvexityFast<2>( R2, 50, 5, 800, 0.5 );
      timingsFullConvexityFast<2>( R2, 25, 5,1200, 0.5 );
      timingsFullConvexityFast<2>( R2, 25, 5,2000, 0.5 );
      outputResults( 2, R2, "timings-fcf-convexity-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsFullConvexityFast<3>( R3, 50, 3, 10, 0.5 );
      timingsFullConvexityFast<3>( R3, 50, 4, 20, 0.5 );
      timingsFullConvexityFast<3>( R3, 50, 5, 40, 0.5 );
      timingsFullConvexityFast<3>( R3, 50, 5, 80, 0.5 );
      timingsFullConvexityFast<3>( R3, 25, 5, 160, 0.5 );
      timingsFullConvexityFast<3>( R3, 25, 5, 320, 0.5 );
      outputResults( 3, R3, "timings-fcf-convexity-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsFullConvexityFast<4>( R4, 50, 5, 10, 0.5 );
      timingsFullConvexityFast<4>( R4, 50, 5, 15, 0.5 );
      timingsFullConvexityFast<4>( R4, 50, 5, 20, 0.5 );
      timingsFullConvexityFast<4>( R4, 50, 5, 30, 0.5 );
      timingsFullConvexityFast<4>( R4, 25, 5, 40, 0.5 );
      timingsFullConvexityFast<4>( R4, 25, 5, 60, 0.5 );
      timingsFullConvexityFast<4>( R4, 15, 6, 80, 0.5 );
      timingsFullConvexityFast<4>( R4, 10, 6, 100, 0.5 );
      timingsFullConvexityFast<4>( R4, 5, 6, 120, 0.5 );
      outputResults( 4, R4, "timings-fcf-convexity-Z4.txt" );
    }
  // P-convexity
  srand( 0 );
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsPConvexityNonConvex<2>( R2, 50,  100 );
      timingsPConvexityNonConvex<2>( R2, 50,  200 );
      timingsPConvexityNonConvex<2>( R2, 50,  400 );
      timingsPConvexityNonConvex<2>( R2, 50,  600 );
      timingsPConvexityNonConvex<2>( R2, 50,  800 );
      timingsPConvexityNonConvex<2>( R2, 50, 1200 );
      timingsPConvexityNonConvex<2>( R2, 50, 2000 );
      outputResults( 2, R2, "timings-p-convexity-ncvx-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsPConvexityNonConvex<3>( R3, 50,  20 );
      timingsPConvexityNonConvex<3>( R3, 50,  40 );
      timingsPConvexityNonConvex<3>( R3, 50,  80 );
      timingsPConvexityNonConvex<3>( R3, 50,  160 );
      timingsPConvexityNonConvex<3>( R3, 50,  320 );
      outputResults( 3, R3, "timings-p-convexity-ncvx-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsPConvexityNonConvex<4>( R4, 50,  10 );
      timingsPConvexityNonConvex<4>( R4, 50,  20 );
      timingsPConvexityNonConvex<4>( R4, 50,  30 );
      timingsPConvexityNonConvex<4>( R4, 40,  40 );
      timingsPConvexityNonConvex<4>( R4, 20,  50 );
      outputResults( 4, R4, "timings-p-convexity-ncvx-Z4.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsFullConvexityNonConvex<2>( R2, 50,  100 );
      timingsFullConvexityNonConvex<2>( R2, 50,  200 );
      timingsFullConvexityNonConvex<2>( R2, 50,  400 );
      timingsFullConvexityNonConvex<2>( R2, 50,  600 );
      timingsFullConvexityNonConvex<2>( R2, 50,  800 );
      timingsFullConvexityNonConvex<2>( R2, 50, 1200 );
      timingsFullConvexityNonConvex<2>( R2, 50, 2000 );
      outputResults( 2, R2, "timings-fc-convexity-ncvx-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsFullConvexityNonConvex<3>( R3, 50,  20 );
      timingsFullConvexityNonConvex<3>( R3, 50,  40 );
      timingsFullConvexityNonConvex<3>( R3, 50,  80 );
      timingsFullConvexityNonConvex<3>( R3, 40,  160 );
      timingsFullConvexityNonConvex<3>( R3, 25,  320 );
      outputResults( 3, R3, "timings-fc-convexity-ncvx-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsFullConvexityNonConvex<4>( R4, 50,  10 );
      timingsFullConvexityNonConvex<4>( R4, 50,  20 );
      timingsFullConvexityNonConvex<4>( R4, 50,  30 );
      timingsFullConvexityNonConvex<4>( R4, 40,  40 );
      timingsFullConvexityNonConvex<4>( R4, 20,  50 );
      outputResults( 4, R4, "timings-fc-convexity-ncvx-Z4.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R2;
      timingsFullConvexityFastNonConvex<2>( R2, 50,  100 );
      timingsFullConvexityFastNonConvex<2>( R2, 50,  200 );
      timingsFullConvexityFastNonConvex<2>( R2, 50,  400 );
      timingsFullConvexityFastNonConvex<2>( R2, 50,  600 );
      timingsFullConvexityFastNonConvex<2>( R2, 50,  800 );
      timingsFullConvexityFastNonConvex<2>( R2, 50, 1200 );
      timingsFullConvexityFastNonConvex<2>( R2, 50, 2000 );
      outputResults( 2, R2, "timings-fcf-convexity-ncvx-Z2.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R3;
      timingsFullConvexityFastNonConvex<3>( R3, 50,  20 );
      timingsFullConvexityFastNonConvex<3>( R3, 50,  40 );
      timingsFullConvexityFastNonConvex<3>( R3, 50,  80 );
      timingsFullConvexityFastNonConvex<3>( R3, 40,  160 );
      timingsFullConvexityFastNonConvex<3>( R3, 25,  320 );
      outputResults( 3, R3, "timings-fcf-convexity-ncvx-Z3.txt" );
    }
  if ( false )
    {
      std::vector< std::tuple< std::size_t, double, bool > > R4;
      timingsFullConvexityFastNonConvex<4>( R4, 50,  10 );
      timingsFullConvexityFastNonConvex<4>( R4, 50,  20 );
      timingsFullConvexityFastNonConvex<4>( R4, 50,  30 );
      timingsFullConvexityFastNonConvex<4>( R4, 40,  40 );
      timingsFullConvexityFastNonConvex<4>( R4, 20,  50 );
      outputResults( 4, R4, "timings-fcf-convexity-ncvx-Z4.txt" );
    }
  return 0;
}
References outputResults(), srand(), timingsFullConvexity(), timingsFullConvexityFast(), timingsFullConvexityFastNonConvex(), timingsFullConvexityNonConvex(), timingsPConvexity(), and timingsPConvexityNonConvex().
outputResults()
void outputResults (Dimension dim, const std::vector< std::tuple< std::size_t, double, bool > > & results, const std::string & fname)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 343 of file pConvexity-benchmark.cpp.
{
  std::ofstream output( fname );
  output << "# Results of " << results.size() << " P-convexity computations in Z"
         << dim << std::endl
         << "# Card(X) time(ms) p-convex?" << std::endl;
  for ( auto&& r : results )
    output << std::get<0>( r ) << " " << std::get<1>( r ) << " " << std::get<2>( r )
           << std::endl;
  output.close();
}
References dim.
Referenced by main().
rand01()
double rand01 ()
Examples
geometry/tools/exampleQuickHull3D.cpp, geometry/tools/exampleRationalBallQuickHull3D.cpp, and geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 70 of file pConvexity-benchmark.cpp.
{ return double(rand()) / double(RAND_MAX); }
Referenced by timingsFullConvexity(), timingsFullConvexityFast(), and timingsPConvexity().
timingsFullConvexity()
template<Dimension dim> void timingsFullConvexity (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double fconvexity_probability = 0.5)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 122 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " full convexities in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      // Create vertices
      std::vector< Point > V;
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        V.push_back( p );
      }
      // create 0-convex or fully convex set.
      std::vector< Point > X;
      bool force_fconvexity = rand01() < fconvexity_probability;
      if ( force_fconvexity )
        X = dconv.envelope( V );
      else
        {
          auto P = dconv.CvxH( V );
          P.getPoints( X );
        }
      // Analyse full convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_fconvex = dconv.isFullyConvex( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_fconvex ) );
      if ( force_fconvexity && ! is_fconvex )
        trace.warning() << "Invalid computation of either FC* or full convexity !" << std::endl;
    }
}
References dim, domain, dt, rand01(), and DGtal::trace.
Referenced by main().
timingsFullConvexityFast()
template<Dimension dim> void timingsFullConvexityFast (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double fconvexity_probability = 0.5)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 170 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " full convexities in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      // Create vertices
      std::vector< Point > V;
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        V.push_back( p );
      }
      // create 0-convex or fully convex set.
      std::vector< Point > X;
      bool force_fconvexity = rand01() < fconvexity_probability;
      if ( force_fconvexity )
        X = dconv.envelope( V );
      else
        {
          auto P = dconv.CvxH( V );
          P.getPoints( X );
        }
      // Analyse full convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_fconvex = dconv.isFullyConvexFast( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_fconvex ) );
      if ( force_fconvexity && ! is_fconvex )
        trace.warning() << "Invalid computation of either FC* or full convexity !" << std::endl;
    }
}
References dim, domain, dt, rand01(), and DGtal::trace.
Referenced by main().
timingsFullConvexityFastNonConvex()
template<Dimension dim> void timingsFullConvexityFastNonConvex (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t range)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 302 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " full convexities (fast) in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      double filling_probability = 0.1 + 0.9 * double( n ) / double( nb_tries );
      // Create vertices
      std::set< Point > S;
      std::size_t nb_vertices
        = std::size_t( filling_probability * ceil( pow( range, dim ) ) );
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        S.insert( p );
      }
      // create digital set.
      std::vector< Point > X( S.cbegin(), S.cend() );
      // Analyse full convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_fconvex = dconv.isFullyConvexFast( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_fconvex ) );
    }
}
References dim, domain, and dt.
Referenced by main().
timingsFullConvexityNonConvex()
template<Dimension dim> void timingsFullConvexityNonConvex (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t range)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 260 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " full convexities in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      double filling_probability = 0.1 + 0.9 * double( n ) / double( nb_tries );
      // Create vertices
      std::set< Point > S;
      std::size_t nb_vertices
        = std::size_t( filling_probability * ceil( pow( range, dim ) ) );
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        S.insert( p );
      }
      // create digital set.
      std::vector< Point > X( S.cbegin(), S.cend() );
      // Analyse full convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_fconvex = dconv.isFullyConvex( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_fconvex ) );
    }
}
References dim, domain, and dt.
Referenced by main().
timingsPConvexity()
template<Dimension dim> void timingsPConvexity (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t nb_vertices, std::size_t range, double pconvexity_probability = 0.5)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 74 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " P-convexities in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      // Create vertices
      std::vector< Point > V;
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        V.push_back( p );
      }
      // create 0-convex or fully convex set.
      std::vector< Point > X;
      bool force_pconvexity = rand01() < pconvexity_probability;
      if ( force_pconvexity )
        X = dconv.envelope( V );
      else
        {
          auto P = dconv.CvxH( V );
          P.getPoints( X );
        }
      // Analyse P-convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_pconvex = pconv.isPConvex( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_pconvex ) );
      if ( force_pconvexity && ! is_pconvex )
        trace.warning() << "Invalid computation of either FC* or P-convexity !" << std::endl;
    }
}
References dim, domain, dt, DGtal::PConvexity< TSpace >::isPConvex(), rand01(), and DGtal::trace.
Referenced by main().
timingsPConvexityNonConvex()
template<Dimension dim> void timingsPConvexityNonConvex (std::vector< std::tuple< std::size_t, double, bool > > & results, std::size_t nb_tries, std::size_t range)
Examples
geometry/volumes/pConvexity-benchmark.cpp.
Definition at line 219 of file pConvexity-benchmark.cpp.
{
  typedef KhalimskySpaceND<dim,int64_t>    KSpace;
  typedef typename KSpace::Point           Point;
  typedef typename KSpace::Space           Space;
  typedef HyperRectDomain< Space >         Domain;
  typedef DigitalConvexity< KSpace >       DConvexity;
  typedef PConvexity< Space >              PConvexity;
  DConvexity dconv( Point::diagonal( -1 ), Point::diagonal( range ) );
  PConvexity pconv;
  Domain     domain( Point::diagonal( 0 ), Point::diagonal( range ) );
  std::cout << "Computing " << nb_tries << " P-convexities in Z" << dim << std::endl;
  for ( auto n = 0; n < nb_tries; ++n )
    {
      double filling_probability = 0.1 + 0.9 * double( n ) / double( nb_tries );
      // Create vertices
      std::set< Point > S;
      std::size_t nb_vertices
        = std::size_t( filling_probability * ceil( pow( range, dim ) ) );
      for ( auto i = 0; i < nb_vertices; i++ ) {
        Point p;
        for ( auto j = 0; j < dim; j++ ) p[ j ] = rand() % range;
        S.insert( p );
      }
      // create digital set.
      std::vector< Point > X( S.cbegin(), S.cend() );
      // Analyse P-convexity
      std::chrono::high_resolution_clock::time_point
        t1 = std::chrono::high_resolution_clock::now();
      bool is_pconvex = pconv.isPConvex( X );
      std::chrono::high_resolution_clock::time_point
        t2 = std::chrono::high_resolution_clock::now();
      double dt = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
      results.push_back( std::make_tuple( X.size(), dt/1e6, is_pconvex ) );
    }
}
References dim, domain, dt, and DGtal::PConvexity< TSpace >::isPConvex().
Referenced by main().