DGtal: Analyzer< KSpace, N > Struct Template Reference
Analyzer< KSpace, N > Struct Template Reference
Public Types
typedef KSpace::Point Point
typedef NeighborhoodConvexityAnalyzer< KSpace, N > NCA
Static Public Member Functions
template<typename ImagePtr>
static std::vector< Point > debug_one (const KSpace &aK, Point p, ImagePtr bimage)
template<typename ImagePtr>
static std::vector< int > run (const KSpace &aK, const std::vector< Point > &pts, ImagePtr bimage)
template<typename ImagePtr>
static void run (std::vector< int > &to_update, const KSpace &aK, const std::vector< Point > &pts, ImagePtr bimage)
Detailed Description
template<typename KSpace, int N>
struct Analyzer< KSpace, N >
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 93 of file fullConvexityAnalysis3D.cpp.
Member Typedef Documentation
NCA
template<typename KSpace, int N> typedef NeighborhoodConvexityAnalyzer< KSpace, N > Analyzer< KSpace, N >::NCA
Definition at line 95 of file fullConvexityAnalysis3D.cpp.
Point
template<typename KSpace, int N> typedef KSpace::Point Analyzer< KSpace, N >::Point
Definition at line 94 of file fullConvexityAnalysis3D.cpp.
Member Function Documentation
debug_one()
template<typename KSpace, int N> template<typename ImagePtr> std::vector< Point > Analyzer< KSpace, N >::debug_one (const KSpace & aK, Point p, ImagePtr bimage) inline static
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 100 of file fullConvexityAnalysis3D.cpp.
  {
    NCA nca( aK.lowerBound(), aK.upperBound(),
             KSpace::dimension <= 2 ? 0 : 10000*KSpace::dimension*N );
    auto& image = *bimage;
    int    geom = 0;
    nca.setCenter( p, image );
    bool  cvx = nca.isFullyConvex( true );
    bool ccvx = nca.isComplementaryFullyConvex( false );
    auto cfg  = nca.makeConfiguration( nca.configuration(), true, false );
    std::vector< Point > localCompX;
    nca.getLocalCompX( localCompX, false );
    std::cout << "InC=" << nca.configuration() << std::endl;
    std::cout << "Cfg=" << cfg << std::endl;
    for ( auto q : localCompX ) std::cout << q;
    std::cout << std::endl;
    geom = ( cvx ? 0x1 : 0x0 ) | ( ccvx ? 0x2 : 0x0 );
    std::cout << "cvx=" << cvx << " ccvx=" << ccvx << std::endl;
    std::cout << "geom=" << geom << std::endl;
    return localCompX;
  }
References DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::configuration(), DGtal::KhalimskySpaceND< 3, Integer >::dimension, DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::getLocalCompX(), image(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::KhalimskySpaceND< dim, TInteger >::lowerBound(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::makeConfiguration(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::setCenter(), and DGtal::KhalimskySpaceND< dim, TInteger >::upperBound().
run() [1/2]
template<typename KSpace, int N> template<typename ImagePtr> std::vector< int > Analyzer< KSpace, N >::run (const KSpace & aK, const std::vector< Point > & pts, ImagePtr bimage) inline static
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 125 of file fullConvexityAnalysis3D.cpp.
  {
    NCA nca( aK.lowerBound(), aK.upperBound(), 0 );
    // KSpace::dimension <= 2 ? 0 : 10000*KSpace::dimension*N );
    auto& image = *bimage;
    std::vector<int> result;
    std::map< Point, int > computed;
    int geom;
    int i  = 0;
    int nb = pts.size();
    int  nb_cvx = 0;
    int nb_ccvx = 0;
    for ( auto p : pts )
      {
        if ( i % 100 == 0 ) trace.progressBar( i, nb );
        auto it = computed.find( p );
        if ( it == computed.end() )
          {
            nca.setCenter( p, image );
            bool  cvx = nca.isFullyConvex( true );
            bool ccvx = nca.isComplementaryFullyConvex( false );
            if ( cvx  ) nb_cvx  += 1;
            if ( ccvx ) nb_ccvx += 1;
            geom = ( cvx ? 0x1 : 0x0 ) | ( ccvx ? 0x2 : 0x0 );
            computed[ p ] = geom;
          }
        else geom = it->second;
        result.push_back( geom );
        i++;
      }
    trace.info() << "nb_cvx=" << nb_cvx << " nb_ccvx=" << nb_ccvx << std::endl;
    return result;
  }
References image(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::KhalimskySpaceND< dim, TInteger >::lowerBound(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::setCenter(), DGtal::trace, and DGtal::KhalimskySpaceND< dim, TInteger >::upperBound().
Referenced by main(), and MultiScaleAnalyzer< KSpace, N >::multiscale_run().
run() [2/2]
template<typename KSpace, int N> template<typename ImagePtr> void Analyzer< KSpace, N >::run (std::vector< int > & to_update, const KSpace & aK, const std::vector< Point > & pts, ImagePtr bimage) inline static
Definition at line 162 of file fullConvexityAnalysis3D.cpp.
  {
    NCA nca( aK.lowerBound(), aK.upperBound() );
    // KSpace::dimension <= 2 ? 0 : 10000*KSpace::dimension*N );
    auto& image = *bimage;
    std::map< Point, int > computed;
    int geom;
    int i  = 0;
    int nb = pts.size();
    for ( auto p : pts )
      {
        if ( i % 100 == 0 ) trace.progressBar( i, nb );
        auto it = computed.find( p );
        if ( it == computed.end() )
          {
            nca.setCenter( p, image );
            bool  cvx = ( to_update[ i ] & 0x1 )
              ? nca.isFullyConvex( true )
              : false;
            bool ccvx = ( to_update[ i ] & 0x2 )
              ? nca.isComplementaryFullyConvex( false )
              : false;
            geom = ( cvx ? 0x1 : 0x0 ) | ( ccvx ? 0x2 : 0x0 );
            computed[ p ] = geom;
          }
        else geom = it->second;
        to_update[ i++ ] = geom;
      }
  }
References image(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isComplementaryFullyConvex(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::isFullyConvex(), DGtal::KhalimskySpaceND< dim, TInteger >::lowerBound(), DGtal::NeighborhoodConvexityAnalyzer< TKSpace, K >::setCenter(), DGtal::trace, and DGtal::KhalimskySpaceND< dim, TInteger >::upperBound().
The documentation for this struct was generated from the following file:
fullConvexityAnalysis3D.cpp