DGtal: DGtal::VolWriter< TImage, TFunctor > Struct Template Reference
DGtal::VolWriter< TImage, TFunctor > Struct Template Reference
Aim: Export a 3D Image using the Vol formats.
#include <DGtal/io/writers/VolWriter.h>
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef TFunctor Functor
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< TFunctor, Value, unsigned char >))
BOOST_STATIC_ASSERT (TImage::Domain::dimension==3)
Static Public Member Functions
static bool exportVol (const std::string &filename, const Image &aImage, const bool compressed=true, const Functor &aFunctor=Functor())
Detailed Description
template<typename TImage, typename TFunctor = functors::Identity>
struct DGtal::VolWriter< TImage, TFunctor >
Aim: Export a 3D Image using the Vol formats.
Description of template struct 'VolWriter'
A functor can be specified to convert image values to Vol values (unsigned char).
Template Parameters
TImage the Image type.
TFunctor the type of functor used in the export.
Examples
tutorial-examples/FMMErosion.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 68 of file VolWriter.h.
Member Typedef Documentation
Functor
template<typename TImage, typename TFunctor = functors::Identity> typedef TFunctor DGtal::VolWriter< TImage, TFunctor >::Functor
Definition at line 73 of file VolWriter.h.
Image
template<typename TImage, typename TFunctor = functors::Identity> typedef TImage DGtal::VolWriter< TImage, TFunctor >::Image
Definition at line 71 of file VolWriter.h.
Value
template<typename TImage, typename TFunctor = functors::Identity> typedef TImage::Value DGtal::VolWriter< TImage, TFunctor >::Value
Definition at line 72 of file VolWriter.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TImage, typename TFunctor = functors::Identity> DGtal::VolWriter< TImage, TFunctor >::BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< TFunctor, Value, unsigned char >))
BOOST_STATIC_ASSERT()
template<typename TImage, typename TFunctor = functors::Identity> DGtal::VolWriter< TImage, TFunctor >::BOOST_STATIC_ASSERT (TImage::Domain::dimension = =3)
exportVol()
template<typename TImage, typename TFunctor = functors::Identity> bool DGtal::VolWriter< TImage, TFunctor >::exportVol (const std::string & filename, const Image & aImage, const bool compressed = true, const Functor & aFunctor = Functor()) static
Export an Image with the Vol format.
Parameters
filename name of the output file
aImage the image to export
compressed boolean to decide wether the vol must be compressed or not
aFunctor functor used to cast image values
Returns
true if no errors occur.
Examples
images/raw2HDF5.cpp.
Referenced by HDF5_3D2vol(), testConsistence(), testImplicitShape3D(), and testVolReader().
The documentation for this struct was generated from the following file:
VolWriter.h