DGtal: MyDrawStyleCustomFillColor Struct Reference
MyDrawStyleCustomFillColor Struct Reference
Public Member Functions
MyDrawStyleCustomFillColor (const Color &c)
virtual void setStyle (Board2D &aboard) const
Public Member Functions inherited from DGtal::DrawableWithBoard2D
virtual ~DrawableWithBoard2D ()
Data Fields
Color myColor
Detailed Description
Definition at line 525 of file testObject.cpp.
Constructor & Destructor Documentation
MyDrawStyleCustomFillColor()
MyDrawStyleCustomFillColor::MyDrawStyleCustomFillColor (const Color & c) inline
Definition at line 528 of file testObject.cpp.
    : myColor( c )
  {}
References myColor.
Member Function Documentation
setStyle()
virtual void MyDrawStyleCustomFillColor::setStyle (Board2D &) const inline virtual
Operation to override. Does nothing by default.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 531 of file testObject.cpp.
  {
    aboard.setFillColor( myColor );
    aboard.setPenColorRGBi( 0, 0, 0 );
    aboard.setLineStyle( LibBoard::Shape::SolidStyle );
    aboard.setLineWidth( 1.0 );
  }
References myColor, LibBoard::Board::setFillColor(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), and LibBoard::Board::setPenColorRGBi().
Field Documentation
myColor
Color MyDrawStyleCustomFillColor::myColor
Definition at line 527 of file testObject.cpp.
Referenced by MyDrawStyleCustomFillColor(), and setStyle().
The documentation for this struct was generated from the following file:
testObject.cpp