DGtal: DGtal::concepts::CUnaryFunctor< X, A &, R & > Struct Template Reference
DGtal::concepts::CUnaryFunctor< X, A &, R & > Struct Template Reference
#include <DGtal/base/CUnaryFunctor.h>
Public Member Functions
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Member Functions
template<typename T>
T & getRef (T &t)
Private Attributes
X x
A a
R r
Detailed Description
template<typename X, typename A, typename R>
struct DGtal::concepts::CUnaryFunctor< X, A &, R & >
Definition at line 112 of file CUnaryFunctor.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename X, typename A, typename R> DGtal::concepts::CUnaryFunctor< X, A &, R & >::BOOST_CONCEPT_USAGE (CUnaryFunctor< X, A &, R & >) inline
Definition at line 118 of file CUnaryFunctor.h.
    {
      ConceptUtils::sameType( getRef(r), x.operator() ( getRef(a) ) );
    }
References a, getRef(), r, DGtal::concepts::ConceptUtils::sameType(), and x.
getRef()
template<typename X, typename A, typename R> template<typename T> T & DGtal::concepts::CUnaryFunctor< X, A &, R & >::getRef (T & t) inline private
Definition at line 130 of file CUnaryFunctor.h.
    {
      return t;
    }
Referenced by BOOST_CONCEPT_USAGE().
Field Documentation
a
template<typename X, typename A, typename R> A DGtal::concepts::CUnaryFunctor< X, A &, R & >::a private
Definition at line 125 of file CUnaryFunctor.h.
Referenced by BOOST_CONCEPT_USAGE().
r
template<typename X, typename A, typename R> R DGtal::concepts::CUnaryFunctor< X, A &, R & >::r private
Definition at line 126 of file CUnaryFunctor.h.
Referenced by BOOST_CONCEPT_USAGE().
x
template<typename X, typename A, typename R> X DGtal::concepts::CUnaryFunctor< X, A &, R & >::x private
Definition at line 124 of file CUnaryFunctor.h.
Referenced by BOOST_CONCEPT_USAGE().
The documentation for this struct was generated from the following file:
CUnaryFunctor.h