DGtal: LibBoard::ShapeList Struct Reference
LibBoard::ShapeList Struct Reference
A group of shapes.
#include <Board/ShapeList.h>
Public Member Functions
ShapeList (int depth=-1)
ShapeList (const ShapeList &other)
~ShapeList ()
const std::string & name () const
ShapeList & clear ()
Point center () const
Shape & rotate (double angle, const Point &center)
ShapeList rotated (double angle, const Point &center)
Shape & rotate (double angle)
ShapeList rotated (double angle)
Shape & translate (double dx, double dy)
ShapeList translated (double dx, double dy)
Shape & scale (double sx, double sy)
Shape & scale (double s)
ShapeList scaled (double sx, double sy)
ShapeList scaled (double s)
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
virtual int minDepth () const
virtual int maxDepth () const
void shiftDepth (int shift)
Shape * clone () const
ShapeList & operator= (const ShapeList &other)
ShapeList & operator<< (const Shape &shape)
ShapeList & operator+= (const Shape &shape)
ShapeList & insert (const Shape &shape, int depth)
ShapeList & dup (unsigned int copies=1)
template<typename T>
T & last (const unsigned int position=0)
Shape & last (const unsigned int position=0)
Shape & top ()
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Member Functions
void addShape (const Shape &shape, double scaleFactor)
void free ()
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes
std::vector< Shape * > _shapes
int _nextDepth
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Detailed Description
A group of shapes.
The ShapeList structure.
Definition at line 28 of file ShapeList.h.
Constructor & Destructor Documentation
ShapeList() [1/2]
LibBoard::ShapeList::ShapeList (int depth = -1) inline
Definition at line 6 of file ShapeList.h.
Referenced by addShape(), LibBoard::Board::Board(), clone(), LibBoard::Group::Group(), LibBoard::Group::Group(), maxDepth(), minDepth(), operator+=(), operator<<(), operator=(), rotated(), rotated(), scaled(), scaled(), ShapeList(), and translated().
ShapeList() [2/2]
LibBoard::ShapeList::ShapeList (const ShapeList & other)
Definition at line 62 of file ShapeList.cpp.
                                              : Shape( other )
{
    if ( ! other._shapes.size() ) return;
    _shapes.resize( other._shapes.size(), 0 );
    std::vector<Shape*>::iterator t = _shapes.begin();
    std::vector<Shape*>::const_iterator i = other._shapes.begin();
    std::vector<Shape*>::const_iterator end = other._shapes.end();
    while ( i != end ) {
        *t = (*i)->clone();
        ++i;
        ++t;
    }
}
References _shapes, LibBoard::Shape::Shape(), and ShapeList().
~ShapeList()
LibBoard::ShapeList::~ShapeList ()
Definition at line 37 of file ShapeList.cpp.
{
    free();
}
References free().
Member Function Documentation
addShape()
void LibBoard::ShapeList::addShape (const Shape & shape, double scaleFactor) protected
Definition at line 122 of file ShapeList.cpp.
{
    if ( typeid( shape ) == typeid( ShapeList ) ) {
        // Insertion on top, respecting the same depth order.
        const ShapeList & sl = dynamic_cast<const ShapeList &>( shape );
        std::vector<Shape*> shapes = sl._shapes;
        stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
        std::vector<Shape*>::iterator i = shapes.begin();
        std::vector<Shape*>::iterator end = shapes.end();
        while ( i != end ) {
            Shape * s = (*i)->clone();
            s->depth( _nextDepth-- );
            if ( scaleFactor != 1.0 )
                s->scaleAll( scaleFactor );
            _shapes.push_back( s );
            ++i;
        }
    } else {
        Shape * s = shape.clone();
        if ( s->depth() == -1 )
            s->depth( _nextDepth-- );
        if ( scaleFactor != 1.0 )
            s->scaleAll( scaleFactor );
        _shapes.push_back( s );
        if ( typeid( shape ) == typeid( Group ) ) {
            _nextDepth = dynamic_cast<const Group&>(shape).minDepth() - 1;
        }
    }
}
References _nextDepth, _shapes, LibBoard::Shape::clone(), LibBoard::Shape::depth(), minDepth(), LibBoard::Shape::scaleAll(), LibBoard::Shape::Shape(), LibBoard::shapeGreaterDepth(), and ShapeList().
Referenced by LibBoard::Board::operator<<().
boundingBox()
Rect LibBoard::ShapeList::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 379 of file ShapeList.cpp.
{
    Rect r;
    std::vector< Shape* >::const_iterator i = _shapes.begin();
    std::vector< Shape* >::const_iterator end = _shapes.end();
    if ( i == end ) return r;
    r = (*i)->boundingBox();
    ++i;
    while ( i != end ) {
        r = r || (*i)->boundingBox();
        ++i;
    }
    return r;
}
References _shapes.
Referenced by LibBoard::Group::boundingBox(), LibBoard::Board::drawBoundingBox(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), and LibBoard::Board::saveTikZ().
center()
Point LibBoard::ShapeList::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Definition at line 192 of file ShapeList.cpp.
{
    std::vector<Shape*>::const_iterator i = _shapes.begin();
    std::vector<Shape*>::const_iterator end = _shapes.end();
    double f = 1.0 / _shapes.size();
    Point r(0,0);
    while ( i != end ) {
        r += f * (*i)->center();
        ++i;
    }
    return r;
}
References _shapes.
Referenced by LibBoard::Board::clear(), LibBoard::Board::rotate(), LibBoard::Group::rotate(), rotate(), rotated(), LibBoard::Board::scale(), LibBoard::Board::scale(), LibBoard::Group::scale(), LibBoard::Group::scale(), and scale().
clear()
ShapeList & LibBoard::ShapeList::clear ()
Definition at line 43 of file ShapeList.cpp.
{
    free();
    _shapes.clear();
    _nextDepth = std::numeric_limits<int>::max() - 1;
    return *this;
}
References _nextDepth, _shapes, and free().
Referenced by LibBoard::Board::clear().
clone()
Shape * LibBoard::ShapeList::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Definition at line 456 of file ShapeList.cpp.
{
    return new ShapeList( *this );
}
References ShapeList().
dup()
ShapeList & LibBoard::ShapeList::dup (unsigned int copies = 1)
Duplicates the last inserted shape.
Parameters
copies The number of copies.
Definition at line 153 of file ShapeList.cpp.
{
    if ( ! _shapes.size() ) {
        warning << "dup() called with an empty list of shapes.\n";
        return *this;
    }
    while ( count-- ) {
        (*this) << (*_shapes.back());
    }
    return *this;
}
References _shapes, and LibBoard::warning.
flushCairo()
void LibBoard::ShapeList::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 347 of file ShapeList.cpp.
{
    std::vector< Shape* > shapes = _shapes;
    stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
    std::vector< Shape* >::const_iterator i = shapes.begin();
    std::vector< Shape* >::const_iterator end = shapes.end();
    while ( i != end ) {
        (*i)->flushCairo( cr, transform );
        ++i;
    }
}
References _shapes, and LibBoard::shapeGreaterDepth().
flushFIG()
void LibBoard::ShapeList::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Definition at line 315 of file ShapeList.cpp.
{
    std::vector< Shape* > shapes = _shapes;
    stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
    std::vector< Shape* >::const_iterator i = shapes.begin();
    std::vector< Shape* >::const_iterator end = shapes.end();
    while ( i != end ) {
        (*i)->flushFIG( stream, transform, colormap );
        ++i;
    }
}
References _shapes, and LibBoard::shapeGreaterDepth().
Referenced by LibBoard::Group::flushFIG().
flushPostscript()
void LibBoard::ShapeList::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 300 of file ShapeList.cpp.
{
    std::vector< Shape* > shapes = _shapes;
    stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
    std::vector< Shape* >::const_iterator i = shapes.begin();
    std::vector< Shape* >::const_iterator end = shapes.end();
    stream << "%%% Begin ShapeList\n";
    while ( i != end ) {
        (*i++)->flushPostscript( stream, transform );
    }
    stream << "%%% End ShapeList\n";
}
References _shapes, flushPostscript(), and LibBoard::shapeGreaterDepth().
Referenced by LibBoard::Group::flushPostscript(), and flushPostscript().
flushSVG()
void LibBoard::ShapeList::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 330 of file ShapeList.cpp.
{
    std::vector< Shape* > shapes = _shapes;
    stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
    std::vector< Shape* >::const_iterator i = shapes.begin();
    std::vector< Shape* >::const_iterator end = shapes.end();
    //stream << "<g>\n";
    while ( i != end ) {
        (*i)->flushSVG( stream, transform );
        ++i;
    }
    //stream << "</g>\n";
}
References _shapes, and LibBoard::shapeGreaterDepth().
Referenced by LibBoard::Group::flushSVG().
flushTikZ()
void LibBoard::ShapeList::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 363 of file ShapeList.cpp.
{
    std::vector< Shape* > shapes = _shapes;
    stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
    std::vector< Shape* >::const_iterator i = shapes.begin();
    std::vector< Shape* >::const_iterator end = shapes.end();
    stream << "\\begin{scope}\n";
    while ( i != end ) {
        (*i)->flushTikZ( stream, transform );
        ++i;
    }
    stream << "\\end{scope}\n";
}
References _shapes, and LibBoard::shapeGreaterDepth().
Referenced by LibBoard::Group::flushTikZ().
free()
void LibBoard::ShapeList::free () protected
Free the memory used by the shapes in the shape vector.
Definition at line 52 of file ShapeList.cpp.
{
    std::vector<Shape*>::const_iterator i = _shapes.begin();
    std::vector<Shape*>::const_iterator end = _shapes.end();
    while ( i != end ) {
        delete *i;
        ++i;
    }
}
References _shapes.
Referenced by clear(), LibBoard::Board::operator=(), operator=(), and ~ShapeList().
insert()
ShapeList & LibBoard::ShapeList::insert (const Shape & shape, int depth)
Insert the shape at a given depth. If the shape is ShapeList or a Board, then all shapes above it will be shifted.
Parameters
shape shape
depth depth
Returns
shapelist
Definition at line 184 of file ShapeList.cpp.
{
    warning << "ShapeList::insert() not implemented yet.\n";
    return *this;
}
References LibBoard::Shape::Shape(), and LibBoard::warning.
last() [1/2]
template<typename T> T & LibBoard::ShapeList::last (const unsigned int position = 0)
Return the last inserted shape with its actual type, if specified (otherwise, a Shape &).
Parameters
position The position. 0 is the last inserted shape, 1 is the one before, etc.
Returns
A reference to the addressed shape.
Definition at line 13 of file ShapeList.h.
                   {
Referenced by last(), and top().
last() [2/2]
Shape & LibBoard::ShapeList::last (const unsigned int position = 0)
Definition at line 462 of file ShapeList.cpp.
{
    return last<Shape>( position );
}
References last().
maxDepth()
int LibBoard::ShapeList::maxDepth () const virtual
Definition at line 421 of file ShapeList.cpp.
{
    int res = std::numeric_limits<int>::min();
    int d;
    ShapeList * sl;
    std::vector< Shape* >::const_iterator i = _shapes.begin();
    std::vector< Shape* >::const_iterator end = _shapes.end();
    while ( i != end ) {
        sl = dynamic_cast<ShapeList*>( *i );
        if ( sl ) {
            d = sl->maxDepth();
        } else {
            d = (*i)->depth();
        }
        if ( d > res ) res = d;
        ++i;
    }
    return res;
}
References _shapes, maxDepth(), and ShapeList().
Referenced by maxDepth(), and LibBoard::TransformFIG::setDepthRange().
minDepth()
int LibBoard::ShapeList::minDepth () const virtual
Definition at line 395 of file ShapeList.cpp.
{
    int res = std::numeric_limits<int>::max();
    int d;
    ShapeList * sl;
    std::vector< Shape* >::const_iterator i = _shapes.begin();
    std::vector< Shape* >::const_iterator end = _shapes.end();
    while ( i != end ) {
        sl = dynamic_cast<ShapeList*>( *i );
        if ( sl ) {
            d = sl->minDepth();
        } else {
            d = (*i)->depth();
        }
        if ( d < res ) res = d;
        ++i;
    }
    return res;
}
References _shapes, minDepth(), and ShapeList().
Referenced by addShape(), minDepth(), operator<<(), and LibBoard::TransformFIG::setDepthRange().
name()
const std::string & LibBoard::ShapeList::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name.
Reimplemented from LibBoard::Shape.
Definition at line 32 of file ShapeList.cpp.
{
    return _name;
}
References _name.
operator+=()
ShapeList & LibBoard::ShapeList::operator+= (const Shape & shape)
Adds a shape to the list of shape, always preserving the shape's depth.
Parameters
shape shape to add.
Returns
updated shapelist.
Definition at line 166 of file ShapeList.cpp.
{
    if ( typeid( shape ) == typeid( ShapeList ) ) {
        const ShapeList & sl = dynamic_cast<const ShapeList &>( shape );
        std::vector<Shape*>::const_iterator i = sl._shapes.begin();
        std::vector<Shape*>::const_iterator end = sl._shapes.end();
        while ( i != end ) {
            Shape * s = (*i)->clone();
            _shapes.push_back( s );
            ++i;
        }
    } else {
        _shapes.push_back( shape.clone() );
    }
    return *this;
}
References _shapes, LibBoard::Shape::clone(), LibBoard::Shape::Shape(), and ShapeList().
operator<<()
ShapeList & LibBoard::ShapeList::operator<< (const Shape & shape)
Adds a shape to the shape list. If the shape has no given depth or is a compound shape (ShapeList) then it is placed on top of the shapes stack. Otherwise, the shape depth is left unchanged.
Parameters
shape the shape to add.
Returns
updated shapelist.
Definition at line 93 of file ShapeList.cpp.
{
    if ( typeid( shape ) == typeid( ShapeList ) ) {
        // Insertion on top, respecting the same depth order.
        const ShapeList & sl = dynamic_cast<const ShapeList &>( shape );
        std::vector<Shape*> shapes = sl._shapes;
        stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
        std::vector<Shape*>::iterator i = shapes.begin();
        std::vector<Shape*>::iterator end = shapes.end();
        while ( i != end ) {
            Shape * s = (*i)->clone();
            s->depth( _nextDepth-- );
            _shapes.push_back( s );
            ++i;
        }
    } else {
        Shape * s = shape.clone();
        if ( s->depth() == -1 )
            s->depth( _nextDepth-- );
        _shapes.push_back( s );
        if ( typeid( shape ) == typeid( Group ) ) {
            _nextDepth = dynamic_cast<const Group&>(shape).minDepth() - 1;
        }
    }
    return *this;
}
References _nextDepth, _shapes, LibBoard::Shape::clone(), LibBoard::Shape::depth(), minDepth(), LibBoard::Shape::Shape(), LibBoard::shapeGreaterDepth(), and ShapeList().
operator=()
ShapeList & LibBoard::ShapeList::operator= (const ShapeList & other)
Definition at line 77 of file ShapeList.cpp.
{
    free();
    if ( ! other._shapes.size() ) return *this;
    _shapes.resize( other._shapes.size(), 0 );
    std::vector<Shape*>::iterator t = _shapes.begin();
    std::vector<Shape*>::const_iterator i = other._shapes.begin();
    std::vector<Shape*>::const_iterator end = other._shapes.end();
    while ( i != end ) {
        *t = (*i)->clone();
        ++i;
        ++t;
    }
    return *this;
}
References _shapes, free(), and ShapeList().
Referenced by LibBoard::Group::operator=().
rotate() [1/2]
Shape & LibBoard::ShapeList::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 224 of file ShapeList.cpp.
{
    return ShapeList::rotate( angle, center() );
}
References angle(), center(), and rotate().
rotate() [2/2]
Shape & LibBoard::ShapeList::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 205 of file ShapeList.cpp.
{
    std::vector<Shape*>::iterator i = _shapes.begin();
    std::vector<Shape*>::iterator end = _shapes.end();
    while ( i != end ) {
        (*i)->rotate( angle, rotCenter );
        ++i;
    }
    return *this;
}
References _shapes, and angle().
Referenced by LibBoard::Board::rotate(), LibBoard::Board::rotate(), LibBoard::Group::rotate(), LibBoard::Group::rotate(), rotate(), and rotated().
rotated() [1/2]
ShapeList LibBoard::ShapeList::rotated (double angle)
Definition at line 230 of file ShapeList.cpp.
{
    return static_cast<ShapeList&>( ShapeList( *this ).rotate( angle, center() ) );
}
References angle(), center(), and ShapeList().
rotated() [2/2]
ShapeList LibBoard::ShapeList::rotated (double angle, const Point & center)
Definition at line 217 of file ShapeList.cpp.
{
    ShapeList r( *this );
    return static_cast<ShapeList&>( r.rotate( angle, rotCenter ) );
}
References angle(), rotate(), and ShapeList().
scale() [1/2]
Shape & LibBoard::ShapeList::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 272 of file ShapeList.cpp.
{
    return ShapeList::scale( s, s );
}
References scale().
scale() [2/2]
Shape & LibBoard::ShapeList::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 254 of file ShapeList.cpp.
{
    Point c = center();
    Point delta;
    std::vector<Shape*>::iterator i = _shapes.begin();
    std::vector<Shape*>::iterator end = _shapes.end();
    while ( i != end ) {
        delta = (*i)->center() - c;
        delta.x *= sx;
        delta.y *= sy;
        (*i)->scale( sx, sy );
        delta = ( c + delta ) - (*i)->center();
        (*i++)->translate( delta.x, delta.y );
    }
    return *this;
}
References _shapes, center(), translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by LibBoard::Board::scale(), LibBoard::Board::scale(), LibBoard::Group::scale(), LibBoard::Group::scale(), and scale().
scaleAll()
void LibBoard::ShapeList::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Definition at line 290 of file ShapeList.cpp.
{
    std::vector<Shape*>::iterator i = _shapes.begin();
    std::vector<Shape*>::iterator end = _shapes.end();
    while ( i != end ) {
        (*i++)->scaleAll( s );
    }
}
References _shapes, and scaleAll().
Referenced by scaleAll().
scaled() [1/2]
ShapeList LibBoard::ShapeList::scaled (double s)
Definition at line 284 of file ShapeList.cpp.
{
    return static_cast<ShapeList&>( ShapeList( *this ).scale( s, s ) );
}
References ShapeList().
scaled() [2/2]
ShapeList LibBoard::ShapeList::scaled (double sx, double sy)
Definition at line 278 of file ShapeList.cpp.
{
    return static_cast<ShapeList&>( ShapeList( *this ).scale( sx, sy ) );
}
References ShapeList().
shiftDepth()
void LibBoard::ShapeList::shiftDepth (int shift) virtual
Reimplemented from LibBoard::Shape.
Definition at line 446 of file ShapeList.cpp.
{
    std::vector< Shape* >::const_iterator i = _shapes.begin();
    std::vector< Shape* >::const_iterator end = _shapes.end();
    while ( i != end ) {
        (*i++)->shiftDepth( shift );
    }
}
References _shapes, and shiftDepth().
Referenced by shiftDepth().
top()
Shape & LibBoard::ShapeList::top ()
Convenience function that simply calls last(0).
Returns
top shape.
Definition at line 468 of file ShapeList.cpp.
{
    return last<Shape>( 0 );
}
References last().
translate()
Shape & LibBoard::ShapeList::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 236 of file ShapeList.cpp.
{
    std::vector<Shape*>::iterator i = _shapes.begin();
    std::vector<Shape*>::iterator end = _shapes.end();
    while ( i != end ) {
        (*i)->translate( dx, dy );
        ++i;
    }
    return *this;
}
References _shapes.
Referenced by scale(), LibBoard::Board::translate(), and LibBoard::Group::translate().
translated()
ShapeList LibBoard::ShapeList::translated (double dx, double dy)
Definition at line 248 of file ShapeList.cpp.
{
    return static_cast<ShapeList&>( ShapeList( *this ).translate( dx, dy ) );
}
References ShapeList().
Field Documentation
_name
const std::string LibBoard::ShapeList::_name static private
The generic name of the shape.
Definition at line 163 of file ShapeList.h.
Referenced by name().
_nextDepth
int LibBoard::ShapeList::_nextDepth protected
The depth of the next figure to be added.
Definition at line 170 of file ShapeList.h.
Referenced by addShape(), clear(), LibBoard::Board::drawArc(), LibBoard::Board::drawArrow(), LibBoard::Board::drawBoundingBox(), LibBoard::Board::drawCircle(), LibBoard::Board::drawClosedPolyline(), LibBoard::Board::drawDot(), LibBoard::Board::drawEllipse(), LibBoard::Board::drawImage(), LibBoard::Board::drawLine(), LibBoard::Board::drawPolyline(), LibBoard::Board::drawQuadraticBezierCurve(), LibBoard::Board::drawRectangle(), LibBoard::Board::drawText(), LibBoard::Board::drawText(), LibBoard::Board::drawTriangle(), LibBoard::Board::drawTriangle(), LibBoard::Board::fillCircle(), LibBoard::Board::fillEllipse(), LibBoard::Board::fillGouraudTriangle(), LibBoard::Board::fillPolyline(), LibBoard::Board::fillRectangle(), LibBoard::Board::fillTriangle(), LibBoard::Board::fillTriangle(), and operator<<().
_shapes
std::vector<Shape*> LibBoard::ShapeList::_shapes protected
The vector of shapes.
Definition at line 169 of file ShapeList.h.
Referenced by addShape(), boundingBox(), center(), clear(), LibBoard::Board::drawArc(), LibBoard::Board::drawArrow(), LibBoard::Board::drawBoundingBox(), LibBoard::Board::drawCircle(), LibBoard::Board::drawClosedPolyline(), LibBoard::Board::drawDot(), LibBoard::Board::drawEllipse(), LibBoard::Board::drawImage(), LibBoard::Board::drawLine(), LibBoard::Board::drawPolyline(), LibBoard::Board::drawQuadraticBezierCurve(), LibBoard::Board::drawRectangle(), LibBoard::Board::drawText(), LibBoard::Board::drawText(), LibBoard::Board::drawTriangle(), LibBoard::Board::drawTriangle(), dup(), LibBoard::Board::fillCircle(), LibBoard::Board::fillEllipse(), LibBoard::Board::fillGouraudTriangle(), LibBoard::Board::fillPolyline(), LibBoard::Board::fillRectangle(), LibBoard::Board::fillTriangle(), LibBoard::Board::fillTriangle(), flushCairo(), flushFIG(), flushPostscript(), flushSVG(), flushTikZ(), free(), maxDepth(), minDepth(), operator+=(), operator<<(), LibBoard::Board::operator=(), operator=(), rotate(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::saveTikZ(), scale(), scaleAll(), ShapeList(), shiftDepth(), and translate().
The documentation for this struct was generated from the following files:
ShapeList.h
ShapeList.cpp