DGtal: DGtal::KhalimskyCell< dim, TInteger > Struct Template Reference
DGtal::KhalimskyCell< dim, TInteger > Struct Template Reference
Represents an (unsigned) cell in a cellular grid space by its Khalimsky coordinates.
#include <DGtal/topology/KhalimskySpaceND.h>
Public Types
using Integer = TInteger
using UnsignedInteger = typename NumberTraits<Integer>::UnsignedVersion
using Point = PointVector< dim, Integer >
using PreCell = KhalimskyPreCell< dim, Integer >
using CellularGridSpace = KhalimskySpaceND< dim, TInteger >
using PreCellularGridSpace = KhalimskyPreSpaceND< dim, TInteger >
using Self = KhalimskyCell< dim, Integer >
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
Integer must be a model of the concept CInteger.
operator PreCell const & () const
Constant conversion to KhalimskyPreCell.
PreCell const & preCell () const
Returns the underlying constant pre-cell.
KhalimskyCell (Integer dummy=0)
Default constructor.
KhalimskyCell (const KhalimskyCell &other)=default
Copy constructor.
KhalimskyCell & operator= (const KhalimskyCell &other)=default
Copy operator.
KhalimskyCell (KhalimskyCell &&other)=default
Move constructor.
KhalimskyCell & operator= (KhalimskyCell &&other)=default
Move operator.
bool operator== (const KhalimskyCell &other) const
Equality operator.
bool operator!= (const KhalimskyCell &other) const
Difference operator.
bool operator< (const KhalimskyCell &other) const
Inferior operator. (lexicographic order).
std::string className () const
Return the style name used for drawing this object.
Private Member Functions
KhalimskyCell (const Point &aPoint)
Explicit constructor from its Khalimsky coordinates.
KhalimskyCell (const PreCell &aCell)
Explicit constructor from a KhalimskyPreCell.
operator PreCell & ()
Mutable conversion to KhalimskyPreCell.
Private Attributes
PreCell myPreCell
Underlying pre-cell.
Friends
class KhalimskySpaceND< dim, TInteger >
class KhalimskySpaceNDHelper< CellularGridSpace >
Detailed Description
template<Dimension dim, typename TInteger = DGtal::int32_t>
struct DGtal::KhalimskyCell< dim, TInteger >
Represents an (unsigned) cell in a cellular grid space by its Khalimsky coordinates.
Template Parameters
dim the dimension of the digital space.
TInteger the Integer class used to specify the arithmetic computations (default type = int32).
Definition at line 82 of file KhalimskySpaceND.h.
Member Typedef Documentation
CellularGridSpace
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::CellularGridSpace = KhalimskySpaceND< dim, TInteger >
Definition at line 95 of file KhalimskySpaceND.h.
Integer
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::Integer = TInteger
Definition at line 91 of file KhalimskySpaceND.h.
Point
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::Point = PointVector< dim, Integer >
Definition at line 93 of file KhalimskySpaceND.h.
PreCell
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::PreCell = KhalimskyPreCell< dim, Integer >
Definition at line 94 of file KhalimskySpaceND.h.
PreCellularGridSpace
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::PreCellularGridSpace = KhalimskyPreSpaceND< dim, TInteger >
Definition at line 96 of file KhalimskySpaceND.h.
Self
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::Self = KhalimskyCell< dim, Integer >
Definition at line 97 of file KhalimskySpaceND.h.
UnsignedInteger
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::KhalimskyCell< dim, TInteger >::UnsignedInteger = typename NumberTraits<Integer>::UnsignedVersion
Definition at line 92 of file KhalimskySpaceND.h.
Constructor & Destructor Documentation
KhalimskyCell() [1/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::KhalimskyCell (const Point & aPoint) explicit private
Explicit constructor from its Khalimsky coordinates.
Parameters
aPoint Its Khalimsky coordinates as a point.
KhalimskyCell() [2/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::KhalimskyCell (const PreCell & aCell) explicit private
Explicit constructor from a KhalimskyPreCell.
Parameters
aCell a pre-cell.
KhalimskyCell() [3/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::KhalimskyCell (Integer dummy = 0) explicit
Default constructor.
KhalimskyCell() [4/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::KhalimskyCell (const KhalimskyCell< dim, TInteger > & other) default
Copy constructor.
Parameters
other any other cell.
KhalimskyCell() [5/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::KhalimskyCell (KhalimskyCell< dim, TInteger > && other) default
Move constructor.
Parameters
other any other cell.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
Integer must be a model of the concept CInteger.
className()
template<Dimension dim, typename TInteger = DGtal::int32_t> std::string DGtal::KhalimskyCell< dim, TInteger >::className () const
Return the style name used for drawing this object.
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
Referenced by main(), and main().
operator PreCell &()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::operator PreCell & () explicit private
Mutable conversion to KhalimskyPreCell.
operator PreCell const &()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::KhalimskyCell< dim, TInteger >::operator PreCell const & () const
Constant conversion to KhalimskyPreCell.
operator!=()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::KhalimskyCell< dim, TInteger >::operator!= (const KhalimskyCell< dim, TInteger > & other) const
Difference operator.
Parameters
other any other cell.
operator<()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::KhalimskyCell< dim, TInteger >::operator< (const KhalimskyCell< dim, TInteger > & other) const
Inferior operator. (lexicographic order).
Parameters
other any other cell.
operator=() [1/2]
template<Dimension dim, typename TInteger = DGtal::int32_t> KhalimskyCell & DGtal::KhalimskyCell< dim, TInteger >::operator= (const KhalimskyCell< dim, TInteger > & other) default
Copy operator.
Parameters
other any other cell.
operator=() [2/2]
template<Dimension dim, typename TInteger = DGtal::int32_t> KhalimskyCell & DGtal::KhalimskyCell< dim, TInteger >::operator= (KhalimskyCell< dim, TInteger > && other) default
Move operator.
Parameters
other any other cell.
operator==()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::KhalimskyCell< dim, TInteger >::operator== (const KhalimskyCell< dim, TInteger > & other) const
Equality operator.
Parameters
other any other cell.
preCell()
template<Dimension dim, typename TInteger = DGtal::int32_t> PreCell const & DGtal::KhalimskyCell< dim, TInteger >::preCell () const
Returns the underlying constant pre-cell.
Referenced by boost::hash< DGtal::KhalimskyCell< dim, TInteger > >::operator()(), and std::hash< DGtal::KhalimskyCell< dim, TInteger > >::operator()().
Friends And Related Symbol Documentation
KhalimskySpaceND< dim, TInteger >
template<Dimension dim, typename TInteger = DGtal::int32_t> friend class KhalimskySpaceND< dim, TInteger > friend
Definition at line 86 of file KhalimskySpaceND.h.
KhalimskySpaceNDHelper< CellularGridSpace >
template<Dimension dim, typename TInteger = DGtal::int32_t> friend class KhalimskySpaceNDHelper< CellularGridSpace > friend
Definition at line 86 of file KhalimskySpaceND.h.
Field Documentation
myPreCell
template<Dimension dim, typename TInteger = DGtal::int32_t> PreCell DGtal::KhalimskyCell< dim, TInteger >::myPreCell private
Underlying pre-cell.
Definition at line 105 of file KhalimskySpaceND.h.
The documentation for this struct was generated from the following file:
KhalimskySpaceND.h