DGtal: DGtal::HalfEdgeDataStructure::Edge Struct Reference
DGtal::HalfEdgeDataStructure::Edge Struct Reference
#include <DGtal/topology/HalfEdgeDataStructure.h>
Public Member Functions
VertexIndex & start ()
const VertexIndex & start () const
VertexIndex & end ()
const VertexIndex & end () const
Edge ()
Edge (VertexIndex vi, VertexIndex vj)
bool operator< (const Edge &other) const
Data Fields
VertexIndex v [2]
The two vertex indices.
Detailed Description
Represents an unoriented edge as two vertex indices, the first lower than the second.
Definition at line 126 of file HalfEdgeDataStructure.h.
Constructor & Destructor Documentation
Edge() [1/2]
DGtal::HalfEdgeDataStructure::Edge::Edge () inline
Definition at line 137 of file HalfEdgeDataStructure.h.
      {
        v[0] = v[1] = -1;
      }
References v.
Referenced by operator<().
Edge() [2/2]
DGtal::HalfEdgeDataStructure::Edge::Edge (VertexIndex vi, VertexIndex vj) inline
Definition at line 141 of file HalfEdgeDataStructure.h.
      {
        if ( vi <= vj ) { v[0] = vi; v[1] = vj; }
        else            { v[0] = vj; v[1] = vi; }
      }
References v.
Member Function Documentation
end() [1/2]
VertexIndex & DGtal::HalfEdgeDataStructure::Edge::end () inline
Definition at line 134 of file HalfEdgeDataStructure.h.
{ return v[1]; }
References v.
Referenced by operator<().
end() [2/2]
const VertexIndex & DGtal::HalfEdgeDataStructure::Edge::end () const inline
Definition at line 135 of file HalfEdgeDataStructure.h.
{ return v[1]; }
References v.
operator<()
bool DGtal::HalfEdgeDataStructure::Edge::operator< (const Edge & other) const inline
Definition at line 146 of file HalfEdgeDataStructure.h.
      {
        return ( start() < other.start() )
          || ( ( start() == other.start() ) && ( end() < other.end() ) );
      }
References Edge(), end(), and start().
start() [1/2]
VertexIndex & DGtal::HalfEdgeDataStructure::Edge::start () inline
Definition at line 131 of file HalfEdgeDataStructure.h.
{ return v[0]; }
References v.
Referenced by operator<().
start() [2/2]
const VertexIndex & DGtal::HalfEdgeDataStructure::Edge::start () const inline
Definition at line 132 of file HalfEdgeDataStructure.h.
{ return v[0]; }
References v.
Field Documentation
v
VertexIndex DGtal::HalfEdgeDataStructure::Edge::v[2]
The two vertex indices.
Definition at line 129 of file HalfEdgeDataStructure.h.
Referenced by Edge(), Edge(), end(), end(), start(), and start().
The documentation for this struct was generated from the following file:
HalfEdgeDataStructure.h