DGtal: DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face Struct Reference
DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face Struct Reference
#include <DGtal/topology/DigitalSurface.h>
Public Member Functions
Face (const UmbrellaState &aState, unsigned int nb, bool aIsClosed)
bool isClosed () const
bool operator== (const Face &other) const
bool operator< (const Face &other) const
Data Fields
UmbrellaState state
unsigned int nbVertices
number of vertices incident to face.
bool closed
tells if the face is closed or open.
Detailed Description
template<typename TDigitalSurfaceContainer>
struct DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face
Defines a face on the digital surface, i.e. an umbrella (open or closed) around a pivot cell (n-3-cell). To be able to compare faces, the face is characterized by one of its possible states. If the face is closed, the representative state is the smallest one. If the face is open, the representative state is the first (applying previous() does not move).
Definition at line 278 of file DigitalSurface.h.
Constructor & Destructor Documentation
Face()
template<typename TDigitalSurfaceContainer> DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::Face (const UmbrellaState & aState, unsigned int nb, bool aIsClosed) inline
Definition at line 283 of file DigitalSurface.h.
        : state( aState ), nbVertices( nb ), closed( aIsClosed )
      {}
References closed, nbVertices, and state.
Referenced by operator<(), and operator==().
Member Function Documentation
isClosed()
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::isClosed () const inline
Definition at line 287 of file DigitalSurface.h.
      { return closed; }
References closed.
operator<()
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::operator< (const Face & other) const inline
Definition at line 293 of file DigitalSurface.h.
      {
        return state < other.state;
      }
References Face(), and state.
operator==()
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::operator== (const Face & other) const inline
Definition at line 289 of file DigitalSurface.h.
      {
        return state == other.state;
      }
References Face(), and state.
Field Documentation
closed
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::closed
tells if the face is closed or open.
Definition at line 282 of file DigitalSurface.h.
Referenced by Face(), and isClosed().
nbVertices
template<typename TDigitalSurfaceContainer> unsigned int DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::nbVertices
number of vertices incident to face.
Definition at line 281 of file DigitalSurface.h.
Referenced by Face().
state
template<typename TDigitalSurfaceContainer> UmbrellaState DGtal::DigitalSurface< TDigitalSurfaceContainer >::Face::state
stores a state from which the whole umbrella can be recomputed.
Definition at line 279 of file DigitalSurface.h.
Referenced by Face(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
DigitalSurface.h