DGtal: DGtal::GenericReader< TContainer, 3, TValue > Struct Template Reference
DGtal::GenericReader< TContainer, 3, TValue > Struct Template Reference
#include <DGtal/io/readers/GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename, unsigned int x=0, unsigned int y=0, unsigned int z=0)
template<typename TFunctor>
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor, unsigned int x=0, unsigned int y=0, unsigned int z=0)
static TContainer importWithColorFunctor (const std::string &filename, const TFunctor &aFunctor, std::vector< unsigned int > dimSpace=std::vector< unsigned int >())
Detailed Description
template<typename TContainer, typename TValue>
struct DGtal::GenericReader< TContainer, 3, TValue >
GenericReader Template partial specialisation for volume images of dimension 3
Definition at line 212 of file GenericReader.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TContainer, typename TValue> DGtal::GenericReader< TContainer, 3, TValue >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
import()
template<typename TContainer, typename TValue> TContainer DGtal::GenericReader< TContainer, 3, TValue >::import (const std::string & filename, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) static
Import a volume image file. For the special format of raw image, the default parameter x,y, z need to be updated according to the dimension if the image.
Parameters
filename the image filename to be imported.
x the size in the x direction.
y the size in the y direction.
z the size in the z direction.
importWithColorFunctor()
TContainer DGtal::GenericReader< TContainer, Tdim, TValue >::importWithColorFunctor (const std::string & filename, const TFunctor & aFunctor, std::vector< unsigned int > dimSpace = std::vector<unsigned int>()) inline static
Import a volume nd image file by specifying a value functor.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TValue , TContainer::Value >)
Parameters
dimSpace a vector containing the n dimensional image size.
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
Definition at line 174 of file GenericReader.h.
    {
      BOOST_CONCEPT_ASSERT(
      (concepts::CUnaryFunctor<TFunctor, DGtal::Color,
                               typename TContainer::Value>));
      DGtal::IOException dgtalio;
      const std::string extension =
      filename.substr( filename.find_last_of( "." ) + 1 );
      if ( extension == "raw" )
      {
        for ( unsigned int i = 0; i < dimSpace.size(); i++ )
          ASSERT( dimSpace[ i ] != 0 );
        typename TContainer::Point const pt;
        for ( unsigned int i = 0; i < dimSpace.size(); i++ )
          pt[ i ]            = dimSpace[ i ];
        return RawReader<TContainer, TFunctor>::template importRaw<
        DGtal::Color>( filename, pt, aFunctor );
      }
      trace.error() << "Extension " << extension
                    << " not yet implemented in DGtal GenericReader."
                    << std::endl;
      throw dgtalio;
    }
importWithValueFunctor()
template<typename TContainer, typename TValue> template<typename TFunctor> TContainer DGtal::GenericReader< TContainer, 3, TValue >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) inline static
Import an image file by specifying a value functor (used for gray scale image format: vol, longvol, pgm3D, raw).
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, unsigned char , TContainer::Value >).
Parameters
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
x x
y y
z z
Definition at line 245 of file GenericReader.h.
      {
        BOOST_CONCEPT_ASSERT((  concepts::CUnaryFunctor<TFunctor, unsigned char, typename TContainer::Value > )) ;
        DGtal::IOException dgtalio;
        const std::string extension = filename.substr(filename.find_last_of(".") + 1);
        if ( extension == "vol" )
          {
            return VolReader<TContainer, TFunctor>::importVol( filename, aFunctor );
          }
        else if ( extension == "longvol" )
          {
            return LongvolReader<TContainer, TFunctor>::importLongvol( filename, aFunctor  );
          }
        else if ( extension == "pgm3d" || extension == "pgm3D" || extension == "p3d" || extension == "pgm" )
          {
            return PGMReader<TContainer, TFunctor>::importPGM3D(filename, aFunctor);
          }
        else if ( extension == "raw" )
          {
            ASSERT( x != 0 && y != 0 && z != 0 );
            typename TContainer::Point const pt (x, y, z);
            return RawReader< TContainer, TFunctor >::template importRaw<TValue>( filename, pt, aFunctor  );
          }
#ifdef  DGTAL_WITH_HDF5
        if ( extension == "h5" )
          return HDF5Reader<TContainer, TFunctor>::importHDF5_3D(filename, "UInt8Array3D", aFunctor);
#endif
#ifdef  DGTAL_WITH_ITK
        if ( extension == "dcm" )
          {
            return DicomReader<TContainer, TFunctor>::importDicom(filename, aFunctor);
          }
        else if (std::find(ITK_IO_IMAGE_EXT.begin(), ITK_IO_IMAGE_EXT.end(), extension) != ITK_IO_IMAGE_EXT.end() )
           {
            return ITKReader<TContainer>::importITK( filename, aFunctor );
          }
#endif
        trace.error() << "Extension " << extension<< " in 3D, not yet implemented in DGtal GenericReader." << std::endl;
        throw dgtalio;
      }
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::DicomReader< TImageContainer, TFunctor >::importDicom(), DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5_3D(), DGtal::ITKReader< TImage >::importITK(), DGtal::LongvolReader< TImageContainer, TFunctor >::importLongvol(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM3D(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::ITK_IO_IMAGE_EXT, and DGtal::trace.
The documentation for this struct was generated from the following file:
GenericReader.h