DGtal: testProjection.cpp File Reference
testProjection.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/SurfelAdjacency.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/helpers/BoundaryPredicate.h"
#include "DGtal/topology/SetOfSurfels.h"
#include "DGtal/topology/SCellsFunctors.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtalCatch.h"
Data Structures
struct AngleLessCell
Functions
double angle (const DGtal::Z2i::RealPoint &point)
double angle (const DGtal::Z2i::KSpace &kspace, const DGtal::Z2i::SCell &cell, const double h)
template<typename Shape>
void digitize (Shape &shape, std::vector< SCell > &sCells0, std::vector< SCell > &sCells1, KSpace &kspace, const double h)
template<typename Shape>
bool test_shape (Shape &shape, const double h, const double epsilon)
TEST_CASE ("Projection test on various shapes")
Variables
Domain domain
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Thomas Caissard (thoma.nosp@m.s.ca.nosp@m.issar.nosp@m.d@li.nosp@m.ris.c.nosp@m.nrs..nosp@m.fr)
Date
2016/05/05
Tests of projections functions in starshape.
This file is part of the DGtal library.
Definition in file testProjection.cpp.
Function Documentation
angle() [1/2]
double angle (const DGtal::Z2i::KSpace & kspace, const DGtal::Z2i::SCell & cell, const double h)
Definition at line 63 of file testProjection.cpp.
{
  DGtal::CanonicSCellEmbedder<DGtal::Z2i::KSpace> emb(kspace);
  return angle(h * emb(cell));
}
References angle().
angle() [2/2]
double angle (const DGtal::Z2i::RealPoint & point)
Definition at line 56 of file testProjection.cpp.
{
  double angle = atan2(point[1], point[0]);
  if(angle < 0.) angle += 2. * M_PI;
  return angle;
}
References angle().
Referenced by LibBoard::Board::addDuplicates(), angle(), angle(), DGtal::NormalCycleFormula< RealPoint, RealVector >::anisotropicCurvatureH1(), DGtal::NormalCycleFormula< RealPoint, RealVector >::anisotropicCurvatureH2(), LibBoard::Arrow::Arrow(), DGtal::functors::BackwardRigidTransformation2D< Space >::BackwardRigidTransformation2D(), DGtal::functors::BackwardRigidTransformation3D< Space >::BackwardRigidTransformation3D(), LibBoard::Board::clear(), LibBoard::Dot::Dot(), LibBoard::Rectangle::flushCairo(), LibBoard::Rectangle::flushSVG(), DGtal::functors::ForwardRigidTransformation2D< Space >::ForwardRigidTransformation2D(), DGtal::functors::ForwardRigidTransformation3D< Space >::ForwardRigidTransformation3D(), LibBoard::Line::Line(), main(), AngleLessCell::operator()(), LibBoard::Board::rotate(), LibBoard::Board::rotate(), LibBoard::Circle::rotate(), LibBoard::Circle::rotate(), LibBoard::Dot::rotate(), LibBoard::Ellipse::rotate(), LibBoard::Ellipse::rotate(), LibBoard::GouraudTriangle::rotate(), LibBoard::GouraudTriangle::rotate(), LibBoard::Group::rotate(), LibBoard::Group::rotate(), LibBoard::Line::rotate(), LibBoard::Line::rotate(), LibBoard::Path::rotate(), LibBoard::Path::rotate(), LibBoard::Point::rotate(), LibBoard::Point::rotate(), LibBoard::Polyline::rotate(), LibBoard::Polyline::rotate(), LibBoard::Shape::rotate(), LibBoard::Shape::rotate(), LibBoard::ShapeList::rotate(), LibBoard::ShapeList::rotate(), LibBoard::Text::rotate(), LibBoard::Text::rotate(), LibBoard::Arrow::rotated(), LibBoard::Arrow::rotated(), LibBoard::Board::rotated(), LibBoard::Board::rotated(), LibBoard::Circle::rotated(), LibBoard::Circle::rotated(), LibBoard::Dot::rotated(), LibBoard::Ellipse::rotated(), LibBoard::Ellipse::rotated(), LibBoard::GouraudTriangle::rotated(), LibBoard::GouraudTriangle::rotated(), LibBoard::Group::rotated(), LibBoard::Group::rotated(), LibBoard::Line::rotated(), LibBoard::Line::rotated(), LibBoard::Path::rotated(), LibBoard::Path::rotated(), LibBoard::Point::rotated(), LibBoard::Point::rotated(), LibBoard::Polyline::rotated(), LibBoard::Polyline::rotated(), LibBoard::Rectangle::rotated(), LibBoard::Rectangle::rotated(), LibBoard::ShapeList::rotated(), LibBoard::ShapeList::rotated(), LibBoard::Text::rotated(), LibBoard::Text::rotated(), LibBoard::Triangle::rotated(), LibBoard::Shape::rotateDeg(), LibBoard::Shape::rotateDeg(), LibBoard::Board::setLineJoin(), TEST_CASE(), and DGtal::NormalCycleFormula< RealPoint, RealVector >::twiceMeanCurvature().
digitize()
template<typename Shape> void digitize (Shape & shape, std::vector< SCell > & sCells0, std::vector< SCell > & sCells1, KSpace & kspace, const double h)
Definition at line 91 of file testProjection.cpp.
{
  // -------------------------------------------------------------------------- Type declaring
  typedef typename DGtal::GaussDigitizer<Space, Shape> Digitizer;
  typedef SurfelAdjacency<2> SurfelAdj;
  typedef Surfaces<KSpace> Surf;
  sCells0.clear();
  sCells1.clear();
  // -------------------------------------------------------------------------- Creating the shape
  Digitizer digitizer;
  digitizer.attach(shape);
  digitizer.init(shape.getLowerBound() + Vector(-1,-1), shape.getUpperBound() + Vector(1,1), h);
  domain = digitizer.getDomain();
  kspace.init(digitizer.getLowerBound(), digitizer.getUpperBound(), true);
  const SurfelAdj surfel_adjacency(true);
  const KSpace::SCell cell_bel = Surf::findABel(kspace, digitizer);
  Surf::track2DBoundary(sCells1, kspace, surfel_adjacency, digitizer, cell_bel);
  {
    typedef std::vector<Point> Points;
    Points points;
    Surf::track2DBoundaryPoints(points, kspace, surfel_adjacency, digitizer, cell_bel);
    const KSpace::SCell point_ref = kspace.sCell(Point(0,0));
    for(Points::const_iterator pi = points.begin(), pe = points.end(); pi != pe; ++pi) sCells0.push_back(kspace.sCell(*pi, point_ref));
  }
  std::sort(sCells0.begin(), sCells0.end(), AngleLessCell(kspace, h));
  std::sort(sCells1.begin(), sCells1.end(), AngleLessCell(kspace, h));
  ASSERT(sCells0.size() == sCells1.size());
}
References domain, DGtal::Astroid2D< TSpace >::getLowerBound(), DGtal::Astroid2D< TSpace >::getUpperBound(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), and DGtal::KhalimskySpaceND< dim, TInteger >::sCell().
Referenced by main(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and test_shape().
TEST_CASE()
TEST_CASE ("Projection test on various shapes")
Definition at line 169 of file testProjection.cpp.
{
  typedef Ball2D<Space> Ball;
  const Ball ball(Point(0,0), 1.0);
  typedef Flower2D<Space> Flower2D;
  const Flower2D flower2D(Point(0,0), 1., 0.3, 5, 0.);
  typedef AccFlower2D<Space> AccFlower2D;
  const AccFlower2D accFlower2D(Point(0,0), 1., 0.3, 5, 0.);
  typedef Ellipse2D<Space> Ellipse2D;
  const Ellipse2D ellipse2D(Point(0,0), 1., 0.4, 0.2);
  double h = 0.1;
  SECTION( "Actual test" )
  {
      while(h > 0.01)
      {
        REQUIRE( test_shape( ball, h, h * 0.01 ) );
        REQUIRE( test_shape( flower2D, h, h * 0.01 ) );
        REQUIRE( test_shape( ellipse2D, h, h * 0.01 ) );
        h /= 1.3;
      }
  }
}
References REQUIRE(), SECTION(), and test_shape().
test_shape()
template<typename Shape> bool test_shape (Shape & shape, const double h, const double epsilon)
Definition at line 127 of file testProjection.cpp.
{
  std::vector<SCell> sCells0, sCells1;
  KSpace kspace;
  digitize(shape, sCells0, sCells1, kspace, h);
  CanonicSCellEmbedder<KSpace> canonicSCellEmbedder(kspace);
  for(unsigned int i = 0; i < sCells0.size(); i++)
  {
        functors::SCellToInnerPoint<KSpace> sCellToInnerPoint(kspace);
    functors::SCellToOuterPoint<KSpace> sCellToOuterPoint(kspace);
    auto prev = ( i + sCells0.size() - 3 ) % sCells0.size(), next = (i + 3) % sCells0.size();
    RealPoint inner_prev = sCellToInnerPoint( sCells0[prev] );
    RealPoint outer_prev = sCellToOuterPoint( sCells0[prev] );
    RealPoint inner_next = sCellToInnerPoint( sCells0[next] );
    RealPoint outer_next = sCellToOuterPoint( sCells0[next] );
    inner_prev *= h;
    inner_next *= h;
    outer_prev *= h;
    outer_next *= h;
    RealPoint q_prev = shape.findIntersection(inner_prev, outer_prev, epsilon);
    RealPoint q_next = shape.findIntersection(inner_next, outer_next, epsilon);
    RealPoint p = shape.closestPointWithWitnesses(h * canonicSCellEmbedder( sCells0[i] ), q_prev, q_next, 300);
    const double norm2 = (p - h * canonicSCellEmbedder( sCells0[i]) ).norm();
    if ( norm2 > sqrt(2.) * h)
        return false;
  }
  return true;
}
References DGtal::StarShaped2D< TSpace >::closestPointWithWitnesses(), digitize(), and DGtal::StarShaped2D< TSpace >::findIntersection().
Referenced by TEST_CASE().
Variable Documentation
domain
Domain domain
Examples
arithmetic/lower-integer-convex-hull.cpp, dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusChladni.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, doc-examples/demo-kernel-1.cpp, doc-examples/kernelDomain.cpp, doc-examples/range.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/volumes/distance/distancetransform3D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/voronoimap2D.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/pConvexity-benchmark.cpp, graph/graphTraversal.cpp, images/exampleConstImageAdapter.cpp, images/extract2DSlicesImagesFrom3D.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/logoDGtal.cpp, io/viewDualSurface.cpp, io/viewers/demo-kernel-2.cpp, io/viewers/viewer3D-1-points.cpp, io/viewers/viewer3D-2-sets.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-4-modes.cpp, io/viewers/viewer3D-5-colors.cpp, io/viewers/viewer3D-6-clipping.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, shapes/exampleMeshVoxelizer.cpp, topology/3dBorderExtraction.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-1-3d.cpp, topology/ctopo-1.cpp, topology/ctopo-1s-3d.cpp, topology/cubical-complex-illustrations.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/homotopicThinning3D.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, and tutorial-examples/FMMErosion.cpp.
Definition at line 88 of file testProjection.cpp.
Referenced by alphaShape(), DGtal::SetFromImage< TSet >::append(), ArrayImageAdapter_example(), basicUsage(), DGtal::BoundedLatticePolytope< Space >::BoundedLatticePolytope(), DGtal::BoundedRationalPolytope< Space >::BoundedRationalPolytope(), DGtal::ConvexCellComplex< TPoint >::cellLatticePolytope(), checkChordGenericStandardPlaneComputer(), checkCOBAGenericStandardPlaneComputer(), cmpTranslatedFFT(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), convexHull(), Fixture_complex_diamond::create_set(), Fixture_complex_fig4::create_set(), Fixture_isthmus::create_set(), Fixture_X::create_set(), digitize(), displayPredicate(), displaySimplicityTable(), displaySimplicityTable(), DGtal::IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, TDomain > >::DistanceFunctor::DistanceFunctor(), DGtal::IteratorCompletionTraits< MyImage< T, N > >::DistanceFunctor::DistanceFunctor(), DGtal::Display3D< Space, KSpace >::draw(), drawArithmeticalDSL(), estimatorOnShapeDigitization(), example(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleUpdate(), Fixture_object_diamond_with_hole::Fixture_object_diamond_with_hole(), for(), generateRefImage(), DGtal::functions::generateSimplicityTable(), DGtal::functions::generateVoxelComplexTable(), DGtal::Shortcuts< Z3i::KSpace >::getKSpace(), image(), DGtal::BoundedLatticePolytope< Space >::init(), DGtal::BoundedRationalPolytope< Space >::init(), DGtal::DiscreteExteriorCalculus< 2, dimension, LinearAlgebra >::initKSpace(), laplace_sphere(), laplacian(), lightBetween(), localDualVolume(), main(), main(), main(), main(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeDoubleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeFloatImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), moduleImages_example(), Object3D(), Objects2D::Objects2D(), pointsInStandardPlane(), refImage(), REQUIRE(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), DGtal::SetValueIterator< TImage, typename Domain::ConstReverseIterator >::SetValueIterator(), showGreedySegmantation(), sum_fn_on_domain(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), test_g_f_fm1(), test_image(), test_linear_ring(), test_linear_structure(), test_manual_operators_2d(), test_manual_operators_3d(), test_range_constRange(), testAPI(), testBIGINTEGERSpace(), testBoard2D(), testBoard2DCustomStyle(), testBreadthFirstPropagation(), testCellDrawOnBoard(), testCombinatorialSurface(), testCompareEstimator(), testCompareExactBruteForce(), testCompareExactInexact(), testCompareInexactBruteForce(), testConsistence(), testCreate(), testDepthFirstPropagation(), testDigitalSetBoardSnippet(), testDigitalSetBoundary(), testDigitalSetDomain(), testDigitalSetDraw(), testDigitalSetSelector(), testDigitalSurface(), testDigitalSurfaceBoostGraphInterface(), testDigitization(), testDistancePropagation(), testDistanceTransformND(), testDraw(), testDSS4drawing(), testDSS8drawing(), testDTFromSet(), testEmbedder(), testExactMetricBalls(), testExpander(), testFindABel(), testFindABel(), testHashTree(), testHashTree2D(), testImageCopy(), testImageCopyShort(), testImageOnRef(), testImageScan(), testImplicitShape(), testImplicitShape3D(), testInexactMetricBalls(), testIterator(), testIteratorHelper(), testIteratorHelper(), testIteratorHelperImpl(), testITKMethod(), testKanungo2D(), testLayers(), testObject(), testObject3D(), testObjectBorder(), testObjectGraph(), testOrderingDigitalSurfaceFacesAroundVertex(), testProjector(), testRWIssue254(), testScan(), testSetTable(), testSimple(), testSimple2D(), testSimple3D(), testSimple4D(), testSimpleExpander(), testSimplePoints2D(), testSimplePoints3D(), testSimpleRandom2D(), testSimpleRandom3D(), testSurfelAdjacency(), testTrueLocalEstimatorOnShapeDigitization(), testUmbrellaComputer(), testVoronoiCovarianceMeasure(), testVoronoiMap(), testWriteAndRead(), timingsFullConvexity(), timingsFullConvexityFast(), timingsFullConvexityFastNonConvex(), timingsFullConvexityNonConvex(), timingsPConvexity(), and timingsPConvexityNonConvex().