DGtal: testDistanceTransformation.cpp File Reference
testDistanceTransformation.cpp File Reference
DGtal Test Files
#include <iostream>
#include <iomanip>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/geometry/volumes/distance/DistanceTransformation.h"
#include "DGtal/geometry/volumes/distance/VoronoiMap.h"
#include "DGtal/geometry/volumes/distance/ExactPredicateLpSeparableMetric.h"
#include "DGtal/geometry/volumes/distance/InexactPredicateLpSeparableMetric.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/io/colormaps/GrayscaleColorMap.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/images/SimpleThresholdForegroundPredicate.h"
Functions
template<typename Image>
void randomSeeds (Image &input, const unsigned int nb, const int value)
bool testDistanceTransformation ()
bool testDistanceTransformationNeg ()
bool testDTFromSet ()
bool testDistanceTransformationBorder ()
bool testDistanceTransformation3D ()
bool testChessboard ()
template<typename Space, int norm>
bool testCompareExactInexact (unsigned int size, unsigned int nb)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2010/09/30
Functions for testing class DistanceTransformation.
This file is part of the DGtal library.
Definition in file testDistanceTransformation.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 628 of file testDistanceTransformation.cpp.
References testChessboard(), testCompareExactInexact(), testDistanceTransformation(), testDistanceTransformation3D(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDTFromSet(), and DGtal::trace.
randomSeeds()
template<typename Image> void randomSeeds (Image & input, const unsigned int nb, const int value)
Examples
geometry/volumes/distance/distancetransform2D.cpp, and geometry/volumes/distance/distancetransform3D.cpp.
Definition at line 60 of file testDistanceTransformation.cpp.
References dim, DGtal::Image< TImageContainer >::domain(), DGtal::HyperRectDomain< TSpace >::lowerBound(), DGtal::Image< TImageContainer >::setValue(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Referenced by testChessboard(), and testDistanceTransformationBorder().
testChessboard()
bool testChessboard ()
Definition at line 468 of file testDistanceTransformation.cpp.
References LibBoard::Board::clear(), DGtal::Display2DFactory::drawImage(), image(), randomSeeds(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::trace, and LibBoard::Board::UCentimeter.
Referenced by main().
testCompareExactInexact()
template<typename Space, int norm> bool testCompareExactInexact (unsigned int size, unsigned int nb)
Definition at line 575 of file testDistanceTransformation.cpp.
References dim, DGtal::SpaceND< 3, Integer >::dimension, domain, and DGtal::trace.
Referenced by main().
testDistanceTransformation()
bool testDistanceTransformation ()
Example of a test. To be completed.
Definition at line 85 of file testDistanceTransformation.cpp.
References LibBoard::Board::clear(), DGtal::Display2DFactory::drawImage(), dt, image(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::trace, and LibBoard::Board::UCentimeter.
Referenced by main().
testDistanceTransformation3D()
bool testDistanceTransformation3D ()
Example of a test. To be completed.
Definition at line 417 of file testDistanceTransformation.cpp.
References dt, image(), and DGtal::trace.
Referenced by main().
testDistanceTransformationBorder()
bool testDistanceTransformationBorder ()
Example of a test. To be completed.
Definition at line 344 of file testDistanceTransformation.cpp.
References LibBoard::Board::clear(), DGtal::Display2DFactory::drawImage(), dt, image(), randomSeeds(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::trace, and LibBoard::Board::UCentimeter.
Referenced by main().
testDistanceTransformationNeg()
bool testDistanceTransformationNeg ()
Example of a test. To be completed.
Definition at line 201 of file testDistanceTransformation.cpp.
References LibBoard::Board::clear(), DGtal::Display2DFactory::drawImage(), dt, image(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::trace, and LibBoard::Board::UCentimeter.
Referenced by main().
testDTFromSet()
bool testDTFromSet ()
Definition at line 287 of file testDistanceTransformation.cpp.
References LibBoard::Board::clear(), domain, DGtal::Display2DFactory::drawImage(), dt, DGtal::Shapes< TDomain >::euclideanShaper(), DGtal::AccFlower2D< TSpace >::getLowerBound(), DGtal::AccFlower2D< TSpace >::getUpperBound(), LibBoard::Board::saveSVG(), and DGtal::trace.
Referenced by main().