DGtal: testSimpleRandomAccessRangeFromPoint.cpp File Reference
testSimpleRandomAccessRangeFromPoint.cpp File Reference
DGtal Test Files
#include "DGtalCatch.h"
#include <DGtal/kernel/SpaceND.h>
#include <DGtal/kernel/domains/HyperRectDomain.h>
#include <DGtal/kernel/domains/Linearizer.h>
#include <DGtal/images/ImageContainerBySTLVector.h>
#include <algorithm>
#include <cstddef>
Typedefs
typedef double Value
typedef SpaceND< 2 > Space
typedef HyperRectDomain< Space > Domain
typedef ImageContainerBySTLVector< Domain, Value > Image
typedef Image::Range Range
typedef Image::ConstRange ConstRange
typedef Linearizer< Domain, ColMajorStorage > Linearizer
Functions
const Domain domain (Point(1, 2), Point(6, 5))
REQUIRE (domain.isInside(aPoint))
Image image (domain)
Image refImage (domain)
for (Domain::ConstIterator it=domain.begin(), it_end=domain.end();it !=it_end;++it,++cnt)
SECTION ("Testing constant forward iterators")
SECTION ("Testing constant forward iterators from a point")
SECTION ("Testing mutable forward iterators")
SECTION ("Testing mutable forward iterators from a point")
SECTION ("Testing constant reverse iterators")
SECTION ("Testing constant reverse iterators from a point")
SECTION ("Testing mutable reverse iterators")
SECTION ("Testing mutable reverse iterators from a point")
SECTION ("Testing forward output iterators")
SECTION ("Testing forward output iterators from a point")
SECTION ("Testing reverse output iterators")
SECTION ("Testing reverse output iterators from a point")
SECTION ("Testing constant forward circulators")
SECTION ("Testing constant reverse circulators")
SECTION ("Testing mutable circulators in forward way")
SECTION ("Testing mutable circulators in backward way")
SECTION ("Testing mutable reverse circulators in forward way")
SECTION ("Testing mutable reverse circulators in backward way")
Variables
const Point aPoint (3, 4)
const double hour = 4.29
std::size_t cnt = 0
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Roland Denis (rolan.nosp@m.d.de.nosp@m.nis@u.nosp@m.niv-.nosp@m.smb.f.nosp@m.r)
Date
2015/10/21
This file is part of the DGtal library
Definition in file testSimpleRandomAccessRangeFromPoint.cpp.
Typedef Documentation
ConstRange
typedef Image::ConstRange ConstRange
Definition at line 47 of file testSimpleRandomAccessRangeFromPoint.cpp.
Domain
typedef HyperRectDomain<Space> Domain
Examples
arithmetic/lower-integer-convex-hull.cpp, dec/exampleDECSurface.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/fullConvexityCollapsiblePoints2D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/pConvexity-benchmark.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/graphTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/logoDGtal.cpp, io/viewDualSurface.cpp, io/viewers/viewer3D-1-points.cpp, io/viewers/viewer3D-2-sets.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-4-modes.cpp, io/viewers/viewer3D-5-colors.cpp, io/viewers/viewer3D-6-clipping.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, shapes/exampleMeshVoxelizer.cpp, topology/3dBorderExtraction.cpp, topology/3dKSSurfaceExtraction.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-1-3d.cpp, topology/ctopo-1.cpp, topology/ctopo-1s-3d.cpp, topology/cubical-complex-illustrations.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/homotopicThinning3D.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, and tutorial-examples/FMMErosion.cpp.
Definition at line 44 of file testSimpleRandomAccessRangeFromPoint.cpp.
Image
typedef ImageContainerBySTLVector<Domain, Value> Image
Examples
dec/exampleDECSurface.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/distancetransform3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, graph/volDistanceTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleImageFactoryFromHDF5.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, images/raw2HDF5.cpp, io/digitalSetFromVol.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dBorderExtractionImg.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/freemanChainFromImage.cpp, tutorial-examples/polyhedralizer.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 45 of file testSimpleRandomAccessRangeFromPoint.cpp.
Linearizer
typedef Linearizer<Domain, ColMajorStorage> Linearizer
Definition at line 48 of file testSimpleRandomAccessRangeFromPoint.cpp.
Range
typedef Image::Range Range
Examples
geometry/curves/estimation/exampleCurvature.cpp, and geometry/curves/exampleGridCurve2d.cpp.
Definition at line 46 of file testSimpleRandomAccessRangeFromPoint.cpp.
Space
typedef SpaceND<2> Space
Examples
dec/exampleHeatLaplace.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/pConvexity-benchmark.cpp, and geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp.
Definition at line 42 of file testSimpleRandomAccessRangeFromPoint.cpp.
Value
typedef double Value
Initial value:
{
  using namespace DGtal
Examples
arithmetic/convergents-biginteger.cpp, and arithmetic/convergents.cpp.
Definition at line 41 of file testSimpleRandomAccessRangeFromPoint.cpp.
Function Documentation
domain()
const Domain domain (Point(1, 2) , Point(6, 5))
for()
for (Domain::ConstIterator it = domain.begin(), it_end = domain.end(); it != it_end; ++it, ++ cnt)
Definition at line 60 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      image.setValue(*it, cnt*hour);
      refImage.setValue(*it, cnt*hour);
    }
References cnt, domain, hour, image(), and refImage().
image()
Image image (domain)
Examples
dec/exampleDECSurface.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/distancetransform3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityThinning3D.cpp, graph/volDistanceTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, images/exampleTiledImage.cpp, images/extract2DImagesFrom3D.cpp, images/extract2DSlicesImagesFrom3D.cpp, io/digitalSetFromVol.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dBorderExtractionImg.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/freemanChainFromImage.cpp, tutorial-examples/polyhedralizer.cpp, and tutorial-examples/volDTGranulo.cpp.
References domain.
Referenced by ArrayImageAdapter_example(), BM_Constructor(), BM_Constructor(), BM_DomainScan(), BM_RangeScan(), BM_SetValue(), calc_image_checksum(), checkPowerMap(), Analyzer< KSpace, N >::debug_one(), DGtal::Display3D< Space, KSpace >::draw(), DGtal::Display3D< Space, KSpace >::drawImage(), LibBoard::Image::flushCairo(), for(), get_mean_binarizer_from_an_image(), init_image_getset(), init_image_iter(), main(), main(), main(), main(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeDoubleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeFloatImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), DGtal::Shortcuts< Z3i::KSpace >::makeGrayScaleImage(), moduleImages_example(), randomSeeds(), Analyzer< KSpace, N >::run(), Analyzer< KSpace, N >::run(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), test3d(), test3dSurfaceHelper(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), test_g_f_fm1(), test_image(), test_range_constRange(), testAPI(), testBreadthFirstPropagation(), testChessboard(), testComparison(), testConsistence(), testCreate(), testDepthFirstPropagation(), testDicomReader(), testDicomReaderFromDirectory(), testDisplay(), testDistancePropagation(), testDistanceTransformation(), testDistanceTransformation3D(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDistanceTransformND(), testExplicitDigitalSurface(), testHDF5_3DReader(), testHDF5Reader(), testImageAdapter(), testImageCopy(), testImageCopyShort(), testImageFromSet(), testImageScan(), testImplicitShape3D(), testImportDICOM(), testIOException(), testIterators(), testLightExplicitDigitalSurface(), testLocalConvolutionNormalVectorEstimator(), testLocalConvolutionNormalVectorEstimator(), testLongvol(), testPNM3DASCIIReader(), testPNM3DReader(), testPNMReader(), testPNMWriter(), testPowerMapFromSites(), testReverseDT(), testReverseDTL1(), testRWIssue254(), testSetFromImage(), testSimple(), testSliceImageFromFunctor(), testSpatialInformation(), testVolReader(), and testWriteAndRead().
refImage()
Image refImage (domain)
References domain.
Referenced by for(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), and testWriteAndRead().
REQUIRE()
REQUIRE (domain. isInsideaPoint)
Examples
doc-examples/exampleCatch.cpp.
References aPoint, and domain.
Referenced by cmpSCellsIfInside(), cmpUCellsIfInside(), GIVEN(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), TEMPLATE_TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), testCellDrawOnBoard(), testCellularGridSpaceNDCoFaces(), testCellularGridSpaceNDFaces(), testDirectIncidence(), testFaces(), testFFTScaling(), testFindABel(), testForwardBackwardFFT(), testImageOnRef(), testImportDICOM(), testIncidence(), testIteratorHelper(), testIteratorHelperImpl(), testNeighborhood(), testRawReaderOnRef(), testScan(), testSpatialInformation(), testSpatialInformation(), testSurfelAdjacency(), and testWriteAndRead().
SECTION() [1/18]
SECTION ("Testing constant forward circulators")
Definition at line 259 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      // Reference sum
      Value refSum = 0;
      for ( Image::ConstIterator it = refImage.begin(), it_end = refImage.end(); it != it_end; ++it )
        {
          refSum += 2 * (*it);
        }
      // Sum in forward way
      const Range range = image.range();
      Value sum = 0;
      cnt = 1;
      for ( Range::ConstCirculator it = range.c(); cnt <= 2*domain.size(); ++it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      REQUIRE( std::equal( refImage.begin(), refImage.end(), range.c() ) );
      // Sum in backward way
      sum = 0;
      cnt = 1;
      for ( Range::ConstCirculator it = range.c(); cnt <= 2*domain.size(); --it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      // Sum in forward way
      ConstRange crange = image.constRange();
      sum = 0;
      cnt = 1;
      for ( Range::ConstCirculator it = crange.c(); cnt <= 2*domain.size(); ++it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      REQUIRE( std::equal( refImage.begin(), refImage.end(), crange.c() ) );
      // Sum in backward way
      sum = 0;
      cnt = 1;
      for ( Range::ConstCirculator it = crange.c(); cnt <= 2*domain.size(); --it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
    }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::c(), cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [2/18]
SECTION ("Testing constant forward iterators from a point")
Definition at line 77 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      const Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.end() - range.begin(aPoint)) == domain.size() - Linearizer::getIndex(aPoint, domain) );
      REQUIRE( std::equal( range.begin(aPoint), range.end(), refImage.begin() + Linearizer::getIndex(aPoint, domain) ) );
      ConstRange crange = image.constRange();
      REQUIRE( static_cast<Domain::Size>(crange.end() - crange.begin(aPoint)) == domain.size() - Linearizer::getIndex(aPoint, domain) );
      REQUIRE( std::equal( crange.begin(aPoint), crange.end(), refImage.begin() + Linearizer::getIndex(aPoint, domain) ) );
    }
References aPoint, DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), domain, DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end(), image(), refImage(), and REQUIRE().
SECTION() [3/18]
SECTION ("Testing constant forward iterators")
Examples
doc-examples/exampleCatch.cpp.
Definition at line 66 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      const Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.end() - range.begin()) == domain.size() );
      REQUIRE( std::equal(range.begin(), range.end(), refImage.begin())  );
      ConstRange crange = image.constRange();
      REQUIRE( static_cast<Domain::Size>(crange.end() - crange.begin()) == domain.size() );
      REQUIRE( std::equal(crange.begin(), crange.end(), refImage.begin()) );
    }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), domain, DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end(), image(), refImage(), and REQUIRE().
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), TEMPLATE_TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), TEST_CASE_METHOD(), and TEST_CASE_METHOD().
SECTION() [4/18]
SECTION ("Testing constant reverse circulators")
Definition at line 313 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      // Reference sum
      Value refSum = 0;
      for ( Image::ConstIterator it = refImage.begin(), it_end = refImage.end(); it != it_end; ++it )
        {
          refSum += 2 * (*it);
        }
      // Sum in forward way
      const Range range = image.range();
      Value sum = 0;
      cnt = 1;
      for ( Range::ConstReverseCirculator it = range.rc(); cnt <= 2*domain.size(); ++it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      REQUIRE( std::equal( refImage.rbegin(), refImage.rend(), range.rc() ) );
      // Sum in backward way
      sum = 0;
      cnt = 1;
      for ( Range::ConstReverseCirculator it = range.rc(); cnt <= 2*domain.size(); --it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      // Sum in forward way
      ConstRange crange = image.constRange();
      sum = 0;
      cnt = 1;
      for ( Range::ConstReverseCirculator it = crange.rc(); cnt <= 2*domain.size(); ++it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
      REQUIRE( std::equal( refImage.rbegin(), refImage.rend(), crange.rc() ) );
      // Sum in backward way
      sum = 0;
      cnt = 1;
      for ( Range::ConstReverseCirculator it = crange.rc(); cnt <= 2*domain.size(); --it )
        {
          sum += *it;
          ++cnt;
        }
      REQUIRE( sum == Approx(refSum) );
    }
References cnt, domain, image(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rc(), refImage(), and REQUIRE().
SECTION() [5/18]
SECTION ("Testing constant reverse iterators from a point")
Definition at line 141 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      const Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.rend() - range.rbegin(aPoint)) == Linearizer::getIndex(aPoint, domain) + 1 );
      REQUIRE( std::equal( range.rbegin(aPoint), range.rend(), refImage.rbegin() + (domain.size() - Linearizer::getIndex(aPoint, domain) - 1) ) );
      ConstRange crange = image.constRange();
      REQUIRE( static_cast<Domain::Size>(crange.rend() - crange.rbegin(aPoint)) == Linearizer::getIndex(aPoint, domain) + 1 );
      REQUIRE( std::equal( crange.rbegin(aPoint), crange.rend(), refImage.rbegin() + (domain.size() - Linearizer::getIndex(aPoint, domain) - 1) ) );
    }
References aPoint, domain, image(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin(), refImage(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rend(), and REQUIRE().
SECTION() [6/18]
SECTION ("Testing constant reverse iterators")
Definition at line 130 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      const Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.rend() - range.rbegin()) == domain.size() );
      REQUIRE( std::equal(range.rbegin(), range.rend(), refImage.rbegin()) );
      ConstRange crange = image.constRange();
      REQUIRE( static_cast<Domain::Size>(crange.rend() - crange.rbegin()) == domain.size() );
      REQUIRE( std::equal(crange.rbegin(), crange.rend(), refImage.rbegin()) );
    }
References domain, image(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin(), refImage(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rend(), and REQUIRE().
SECTION() [7/18]
SECTION ("Testing forward output iterators from a point")
Definition at line 211 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(aPoint), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      std::copy( refImage.begin() + Linearizer::getIndex(aPoint, domain), refImage.end(), range.outputIterator(aPoint) );
      REQUIRE( std::equal(range.begin(), range.end(), refImage.begin()) );
    }
References aPoint, cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [8/18]
SECTION ("Testing forward output iterators")
Definition at line 195 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      std::copy( refImage.begin(), refImage.end(), range.outputIterator() );
      REQUIRE( std::equal(range.begin(), range.end(), refImage.begin()) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [9/18]
SECTION ("Testing mutable circulators in backward way")
Definition at line 387 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Range::Circulator it = --range.c(); cnt <= 2*domain.size(); --it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it) + 2*cnt + domain.size());
          ++cnt;
        }
      REQUIRE( std::equal( range.begin(), range.end(), refImage.begin() ) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [10/18]
SECTION ("Testing mutable circulators in forward way")
Definition at line 367 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Range::Circulator it = range.c(); cnt <= 2*domain.size(); ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it) + 2*cnt + domain.size());
          ++cnt;
        }
      REQUIRE( std::equal( range.begin(), range.end(), refImage.begin() ) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [11/18]
SECTION ("Testing mutable forward iterators from a point")
Definition at line 109 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.end() - range.begin(aPoint)) == domain.size() - Linearizer::getIndex(aPoint, domain) );
      cnt = 1;
      for ( Range::Iterator it = range.begin(aPoint), it_end = range.end(); it != it_end; ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(aPoint), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      REQUIRE( std::equal(range.begin(), range.end(), refImage.begin()) );
    }
References aPoint, cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [12/18]
SECTION ("Testing mutable forward iterators")
Definition at line 88 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.end() - range.begin()) == domain.size() );
      cnt = 1;
      for ( Range::Iterator it = range.begin(), it_end = range.end(); it != it_end; ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      REQUIRE( std::equal(range.begin(), range.end(), refImage.begin()) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [13/18]
SECTION ("Testing mutable reverse circulators in backward way")
Definition at line 427 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Range::ReverseCirculator it = --range.rc(); cnt <= 2*domain.size(); --it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstIterator it = domain.begin(), it_end = domain.end(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it) + 2*cnt + domain.size());
          ++cnt;
        }
      REQUIRE( std::equal( range.begin(), range.end(), refImage.begin() ) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [14/18]
SECTION ("Testing mutable reverse circulators in forward way")
Definition at line 407 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Range::ReverseCirculator it = range.rc(); cnt <= 2*domain.size(); ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it) + 2*cnt + domain.size());
          ++cnt;
        }
      REQUIRE( std::equal( range.begin(), range.end(), refImage.begin() ) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [15/18]
SECTION ("Testing mutable reverse iterators from a point")
Definition at line 173 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.rend() - range.rbegin(aPoint)) == Linearizer::getIndex(aPoint, domain) + 1 );
      cnt = 1;
      for ( Range::ReverseIterator it = range.rbegin(aPoint), it_end = range.rend(); it != it_end; ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(aPoint), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      REQUIRE( std::equal(range.rbegin(), range.rend(), refImage.rbegin()) );
    }
References aPoint, cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [16/18]
SECTION ("Testing mutable reverse iterators")
Definition at line 152 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      REQUIRE( static_cast<Domain::Size>(range.rend() - range.rbegin()) == domain.size() );
      cnt = 1;
      for ( Range::ReverseIterator it = range.rbegin(), it_end = range.rend(); it != it_end; ++it )
        {
          *it += cnt++;
        }
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      REQUIRE( std::equal(range.rbegin(), range.rend(), refImage.rbegin()) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [17/18]
SECTION ("Testing reverse output iterators from a point")
Definition at line 243 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(aPoint), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      std::copy( refImage.rbegin() + (domain.size() - Linearizer::getIndex(aPoint, domain) - 1), refImage.rend(), range.routputIterator(aPoint) );
      REQUIRE( std::equal(range.rbegin(), range.rend(), refImage.rbegin()) );
    }
References aPoint, cnt, domain, image(), refImage(), and REQUIRE().
SECTION() [18/18]
SECTION ("Testing reverse output iterators")
Definition at line 227 of file testSimpleRandomAccessRangeFromPoint.cpp.
    {
      Range range = image.range();
      cnt = 1;
      for ( Domain::ConstReverseIterator it = domain.rbegin(), it_end = domain.rend(); it != it_end; ++it )
        {
          refImage.setValue( *it, refImage(*it)+cnt );
          ++cnt;
        }
      std::copy( refImage.rbegin(), refImage.rend(), range.routputIterator() );
      REQUIRE( std::equal(range.rbegin(), range.rend(), refImage.rbegin()) );
    }
References cnt, domain, image(), refImage(), and REQUIRE().
Variable Documentation
aPoint
const Point aPoint(3, 4) (3 , 4)
Referenced by DGtal::PlaneProbingNeighborhood< TPredicate >::absolutePoint(), DGtal::AccFlower2D< TSpace >::AccFlower2D(), DGtal::ConstIterator< InputPoint, Functor >::add(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::addNewAcceptedPoint(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::addNewCandidate(), PointConverter< ColMajorStorage >::apply(), PointConverter< RowMajorStorage >::apply(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::ArithmeticalDSS(), DGtal::ArrayImageIterator< Self >::ArrayImageIterator(), DGtal::Astroid2D< Space >::Astroid2D(), DGtal::Ball2D< TSpace >::Ball2D(), DGtal::Ball3D< TSpace >::Ball3D(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::begin(), DGtal::concepts::CDomainArchetype< TSpace >::begin(), DGtal::ConstRangeFromPointAdapter< TRange, TFunctor, TReturnType >::begin(), DGtal::DefaultConstImageRange< Self >::begin(), DGtal::DefaultImageRange< Self >::begin(), DGtal::DigitalSetDomain< DigitalSet >::begin(), DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< Space >::begin(), DGtal::SimpleRandomAccessConstRangeFromPoint< ConstIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::begin(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::begin(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::begin(), DGtal::TiledImageBidirectionalConstRangeFromPoint< TiledImage >::begin(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::begin(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::begin(), calcPointModuloDomain(), DGtal::RealFFT< HyperRectDomain< TSpace >, T >::calcScaledFreqCoords(), DGtal::RealFFT< HyperRectDomain< TSpace >, T >::calcScaledSpatialCoords(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::computeOneStep(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator::ConstIterator(), DGtal::ArrayImageIterator< Self >::distance_to(), DGtal::Ellipse2D< TSpace >::Ellipse2D(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::end(), DGtal::functors::EqualPointPredicate< TPoint >::EqualPointPredicate(), DGtal::AlphaThickSegmentComputer< InputPoint, ConstIterator >::extendFront(), DGtal::findAndGetValue(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::findBlockCoordsFromPoint(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::findSubDomain(), DGtal::Flower2D< Space >::Flower2D(), DGtal::ImplicitPolynomial3Shape< Space >::gaussianCurvature(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::get(), DGtal::Linearizer< HyperRectDomain< TSpace >, TStorageOrder >::getIndex(), DGtal::Linearizer< HyperRectDomain< TSpace >, TStorageOrder >::getIndex(), DGtal::Linearizer< HyperRectDomain< TSpace >, TStorageOrder >::getIndex(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getKey(), DGtal::ImageCacheReadPolicyFIFO< TImageContainer, TImageFactory >::getPage(), DGtal::ImageCacheReadPolicyLAST< TImageContainer, TImageFactory >::getPage(), DGtal::ReverseDistanceTransformation< TWeightImage, TPSeparableMetric, TImageContainer >::getPowerVector(), DGtal::RealFFT< HyperRectDomain< TSpace >, T >::getScaledFreqValue(), DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::getValue(), MyImage< T, N >::getValue(), DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::getVoronoiSite(), DGtal::ImplicitPolynomial3Shape< Space >::gradient(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::SpanIterator::ImageContainerBySTLVector< Domain, Value >, DGtal::PointVector< Calculus::dimensionAmbient, Scalar >::inf(), DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::NotAbovePredicate::inPlane(), DGtal::PlaneProbingParallelepipedEstimator< DigitalPlane, mode >::inPlane(), DGtal::insertAndAlwaysSetValue(), DGtal::insertAndSetValue(), DGtal::Morton< THashKey, TPoint >::interleaveBits(), DGtal::PlaneProbingR1Neighborhood< TPredicate >::intersectSphereRay(), DGtal::AlphaThickSegmentComputer< InputPoint, ConstIterator >::isExtendableFront(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::isInDSL(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::isInDSL(), DGtal::ArithmeticalDSSComputer< ConstIterator, TInteger, adjacency >::isInDSL(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::isInDSS(), DGtal::ArithmeticalDSSComputer< ConstIterator, TInteger, adjacency >::isInDSS(), DGtal::Naive3DDSSComputer< ConstIterator, TInteger, connectivity >::isInDSS(), DGtal::StandardDSS6Computer< ConstIterator, TInteger, connectivity >::isInDSS(), DGtal::ImplicitHyperCube< TSpace >::isInside(), DGtal::ImplicitNorm1Ball< TSpace >::isInside(), DGtal::ImplicitPolynomial3Shape< Space >::isInside(), DGtal::ImplicitRoundedHyperCube< TSpace >::isInside(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::isLowerLeaningPoint(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::isUpperLeaningPoint(), DGtal::PlaneProbingR1Neighborhood< TPredicate >::isValidIntersectSphereRay(), DGtal::KhalimskyCell< dim, Integer >::KhalimskyCell(), DGtal::KhalimskyPreCell< dim, Integer >::KhalimskyPreCell(), DGtal::Lemniscate2D< Space >::Lemniscate2D(), DGtal::ImplicitPolynomial3Shape< Space >::meanCurvature(), DGtal::FreemanChain< Integer >::movePointFromFC(), DGtal::ImplicitPolynomial3Shape< Space >::nearestPoint(), DGtal::NGon2D< TSpace >::NGon2D(), BallFunctor< TPoint >::operator()(), BallPredicate< TPoint >::operator()(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::operator()(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::operator()(), DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::operator()(), DGtal::ConstImageAdapter< Image, Domain, BackwardTrans, Image::Value, Identity >::operator()(), DGtal::DigitalPlanePredicate< Space >::operator()(), DGtal::DigitalSurfacePredicate< Surface >::operator()(), DGtal::DistanceFunctorFromPoint< TImage >::operator()(), DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()(), DGtal::Domain< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::operator()(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()(), DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::operator()(), DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::operator()(), DGtal::functors::FlipDomainAxis< TDomain >::operator()(), DGtal::functors::IntervalForegroundPredicate< Image >::operator()(), DGtal::functors::Point2DEmbedderIn3D< TDomain3D, TInteger >::operator()(), DGtal::functors::PointFunctorFromPointPredicateAndDomain< PointPredicate, Domain, unsigned int >::operator()(), DGtal::functors::PointFunctorHolder< TPoint, TValue, TFunctor >::operator()(), DGtal::functors::Projector< SpaceND< 2, int > >::operator()(), DGtal::functors::SimpleThresholdForegroundPredicate< Image >::operator()(), DGtal::functors::SliceRotator2D< TDomain3D, TInteger >::operator()(), DGtal::Image< TImageContainer >::operator()(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::operator()(), DGtal::ImageContainerBySTLMap< Z2i::Domain, DGtal::int32_t >::operator()(), DGtal::ImageContainerBySTLVector< Domain, Storage * >::operator()(), DGtal::ImageToConstantFunctor< Image, PointPredicate, TValue >::operator()(), DGtal::ImplicitBall< Space >::operator()(), DGtal::ImplicitHyperCube< TSpace >::operator()(), DGtal::ImplicitNorm1Ball< TSpace >::operator()(), DGtal::ImplicitPolynomial3Shape< Space >::operator()(), DGtal::ImplicitRoundedHyperCube< TSpace >::operator()(), DGtal::IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, TDomain > >::DistanceFunctor::operator()(), DGtal::IteratorCompletionTraits< MyImage< T, N > >::DistanceFunctor::operator()(), DGtal::KanungoNoise< TPointPredicate, TDomain, TDigitalSetContainer >::operator()(), DGtal::L1LocalDistance< TImage, TSet >::operator()(), DGtal::L2FirstOrderLocalDistance< TImage, TSet >::operator()(), DGtal::L2FirstOrderLocalDistanceFromCells< TKSpace, TMap, isIndirect >::operator()(), DGtal::L2SecondOrderLocalDistance< TImage, TSet >::operator()(), DGtal::LInfLocalDistance< TImage, TSet >::operator()(), DGtal::ParametricShapeCurvatureFunctor< TParametricShape >::operator()(), DGtal::ParametricShapeTangentFunctor< TParametricShape >::operator()(), DGtal::PlaneProbingParallelepipedEstimator< TPredicate, mode >::NotAbovePredicate::operator()(), DGtal::PowerMap< TWeightImage, TPowerSeparableMetric, TImageContainer >::operator()(), DGtal::PredicateFromOrientationFunctor2< Functor, false, false >::operator()(), DGtal::ReverseDistanceTransformation< TWeightImage, TPSeparableMetric, TImageContainer >::operator()(), DGtal::SpeedExtrapolator< TDistanceImage, TSet, TSpeedFunctor >::operator()(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()(), DGtal::VoronoiMapComplete< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()(), MyImage< T, N >::operator()(), DGtal::DigitalSetInserter< TDigitalSet >::operator=(), DGtal::ImplicitBall< Space >::orientation(), DGtal::ImplicitHyperCube< TSpace >::orientation(), DGtal::ImplicitNorm1Ball< TSpace >::orientation(), DGtal::ImplicitPolynomial3Shape< Space >::orientation(), DGtal::ImplicitRoundedHyperCube< TSpace >::orientation(), DGtal::WindingNumbersShape< TSpace >::orientation(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::orthogonalPosition(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::orthogonalPosition(), DGtal::DefaultImageRange< Self >::outputIterator(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::outputIterator(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::outputIterator(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::outputIterator(), DGtal::PlaneProbingParallelepipedEstimator< DigitalPlane, mode >::PlaneProbingParallelepipedEstimator(), DGtal::PlaneProbingTetrahedronEstimator< NotAbovePredicate, mode >::PlaneProbingTetrahedronEstimator(), DGtal::GridCurve< K2 >::PointVectorTo1SCell(), DGtal::functors::PolarPointComparatorBy2x2DetComputer< TPoint, TDetComputer >::PolarPointComparatorBy2x2DetComputer(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::position(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::position(), DGtal::ArithmeticalDSSComputer< ConstIterator, TInteger, adjacency >::position(), DGtal::ExactPredicateLpPowerSeparableMetric< Space, 2 >::powerDistance(), DGtal::ExactPredicateLpPowerSeparableMetric< TSpace, 2, TPromoted >::powerDistance(), DGtal::ImplicitPolynomial3Shape< Space >::principalCurvatures(), DGtal::ImplicitPolynomial3Shape< Space >::principalDirections(), DGtal::Domain< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::projectPoint(), DGtal::PowerMap< TWeightImage, TPowerSeparableMetric, TImageContainer >::projectPoint(), DGtal::PowerMap< TWeightImage, TPowerSeparableMetric, TImageContainer >::projectPoint(), DGtal::VoronoiMapComplete< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::projectPoint(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::rbegin(), DGtal::ConstRangeFromPointAdapter< TRange, TFunctor, TReturnType >::rbegin(), DGtal::DefaultConstImageRange< Self >::rbegin(), DGtal::DefaultImageRange< Self >::rbegin(), DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rbegin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::rbegin(), DGtal::HyperRectDomain< Space >::rbegin(), DGtal::SimpleRandomAccessConstRangeFromPoint< ConstIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::rbegin(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::rbegin(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::rbegin(), DGtal::TiledImageBidirectionalConstRangeFromPoint< TiledImage >::rbegin(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::rbegin(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::rbegin(), DGtal::ImageCache< OutputImage, ImageFactory, ImageCacheReadPolicy, ImageCacheWritePolicy >::read(), DGtal::PlaneProbingNeighborhood< TPredicate >::relativePoint(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::remainder(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::remainder(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, 4 >::remainder(), DGtal::ArithmeticalDSSComputer< ConstIterator, TInteger, adjacency >::remainder(), DGtal::OneBalancedWordComputer< ConstIterator, Integer >::remainder(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, 4 >::rend(), REQUIRE(), DGtal::DefaultImageRange< Self >::routputIterator(), DGtal::SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor >::routputIterator(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::routputIterator(), DGtal::TiledImageBidirectionalRangeFromPoint< TiledImage >::routputIterator(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), DGtal::RealFFT< HyperRectDomain< TSpace >, T >::setScaledFreqValue(), DGtal::RealFFT< HyperRectDomain< TSpace >, T >::setScaledSpatialLowerBound(), DGtal::ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >::setValue(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::setValue(), DGtal::Image< TImageContainer >::setValue(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::setValue(), DGtal::ImageContainerBySTLMap< Z2i::Domain, DGtal::int32_t >::setValue(), DGtal::ImageContainerBySTLVector< Domain, Storage * >::setValue(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::setValue(), MyImage< T, N >::setValue(), DGtal::SignedKhalimskyCell< dim, Integer >::SignedKhalimskyCell(), DGtal::SignedKhalimskyPreCell< dim, Integer >::SignedKhalimskyPreCell(), DGtal::ImageContainerBySTLVector< Domain, Storage * >::spanBegin(), DGtal::ImageContainerBySTLVector< Domain, Storage * >::spanEnd(), DGtal::detail::squaredNorm(), DGtal::PointVector< Calculus::dimensionAmbient, Scalar >::sup(), TEST_CASE(), testDirectIncidence(), testFaces(), testIncidence(), testNeighborhood(), testSCellsFunctors(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::TiledIterator::TiledIterator(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::update(), DGtal::Preimage2D< StraightLine >::update(), DGtal::ImageCache< OutputImage, ImageFactory, ImageCacheReadPolicy, ImageCacheWritePolicy >::write(), DGtal::ImageCacheWritePolicyWB< TImageContainer, TImageFactory >::writeInPage(), and DGtal::ImageCacheWritePolicyWT< TImageContainer, TImageFactory >::writeInPage().
cnt
std::size_t cnt = 0
Definition at line 59 of file testSimpleRandomAccessRangeFromPoint.cpp.
Referenced by cmpSCellsIfInside(), cmpUCellsIfInside(), for(), main(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), SECTION(), and SECTION().
hour
const double hour = 4.29
Definition at line 58 of file testSimpleRandomAccessRangeFromPoint.cpp.
Referenced by for().