DGtal: testCloneAndAliases.cpp File Reference
testCloneAndAliases.cpp File Reference
DGtal Test Files
#include <cstdio>
#include <cmath>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/base/Clone.h"
#include "DGtal/base/Alias.h"
#include "DGtal/base/ConstAlias.h"
#include "DGtal/helpers/StdDefs.h"
Data Structures
struct A1
struct DByValue
struct DByClone
struct EByAlias
struct EByConstAlias
class MyPoint
struct TriangleByConstReference
struct TriangleByValue
struct TriangleByClone
struct FByCloneHeap
struct FByCloneCowPtr
Typedefs
typedef MyPoint Point
Functions
template<typename Triangle>
double computeTriangles (int size)
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2012/07/02
This file is part of the DGtal library
Definition in file testCloneAndAliases.cpp.
Typedef Documentation
Point
typedef MyPoint Point
Definition at line 185 of file testCloneAndAliases.cpp.
Function Documentation
computeTriangles()
template<typename Triangle> double computeTriangles (int size)
Definition at line 219 of file testCloneAndAliases.cpp.
{
  double total = 0.0;
  Point A( 0, 0 );
  for ( int yb = 0; yb < size; ++yb )
    for ( int xb = 0; xb < size; ++xb )
      {
        Point B( xb, yb );
        for ( int yc = 0; yc < size; ++yc )
          for ( int xc = 0; xc < size; ++xc )
            {
              Point C( xc, yc );
              Triangle T( A, B, C );
              total += T.perimeter();
            }
      }
  return total;
}
Referenced by main().
main()
int main (void)
Definition at line 272 of file testCloneAndAliases.cpp.
{
  unsigned int nb = 0;
  unsigned int nbok = 0;
  trace.beginBlock ( "Number of A1 instances with standard by-value parameter passing." );
  A1 a1( 10 ); // +1/ 0
  DByValue d1( a1 ); //  +2/+1
  trace.info() << "D: d1.value() = " << d1.value() << std::endl;
  ++nb; nbok += A1::nbCreated==3 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Number of A1 instances with explicit by-value parameter passing (Clone)." );
  DByClone dd1( a1 ); // +1/0
  ++nb; nbok += A1::nbCreated==4 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Number of A1 instances with explicit by-reference parameter passing (Alias)." );
  EByAlias e1( a1 ); // +0/0
  ++nb; nbok += A1::nbCreated==4 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Number of A1 instances with explicit by-const reference parameter passing (Alias)." );
  EByConstAlias ee1( a1 ); // +0/0
  ++nb; nbok += A1::nbCreated==4 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Number of A1 instances with explicit by-value parameter passing into heap (Clone)." );
  FByCloneHeap fe1( a1 ); // +1/0
  ++nb; nbok += A1::nbCreated==5 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Number of A1 instances with explicit by-value parameter passing into CowPtr (Clone)." );
  FByCloneCowPtr fe3( a1 ); // +1/0
  ++nb; nbok += A1::nbCreated==6 ? 1 : 0;
  ++nb; nbok += A1::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << A1::nbCreated
               << " nbDeleted=" << A1::nbDeleted << std::endl;
  trace.endBlock();
  int size = 20;
  trace.beginBlock ( "Total perimeter of triangles with by-value parameter passing." );
  double t1 = computeTriangles<TriangleByValue>( size );
  trace.info() << "Perimeter is " << t1 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  int nbC = Point::nbCreated;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with by-const reference parameter passing." );
  double t2 = computeTriangles<TriangleByConstReference>( size );
  trace.info() << "Perimeter is " << t2 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated < nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with by Clone parameter passing." );
  double t3 = computeTriangles<TriangleByClone>( size );
  trace.info() << "Perimeter is " << t3 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated < nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  // These two lines should not compile.
  // Clone<A1> clone1( a1 );
  // Clone<A1> clone2( clone2 );
  return ( nb == nbok ) ? 0 : 1;
}
References computeTriangles(), A1::nbCreated, MyPointD::nbCreated, A1::nbDeleted, MyPointD::nbDeleted, MyPoint::reset(), DGtal::trace, and DByValue::value().