DGtal: testLambdaMST3D.cpp File Reference
testLambdaMST3D.cpp File Reference
DGtal Test Files
#include <iostream>
#include <fstream>
#include <vector>
#include <iterator>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/readers/PointListReader.h"
#include "DGtal/geometry/curves/Naive3DDSSComputer.h"
#include "DGtal/geometry/curves/estimation/LambdaMST3D.h"
#include "DGtal/geometry/curves/estimation/FunctorsLambdaMST.h"
#include "DGtal/geometry/curves/SaturatedSegmentation.h"
Data Structures
class testLambdaMST3D
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, A3SI, France
Date
2014/10/03
Functions for testing class LambdaMST3D.
This file is part of the DGtal library.
Definition in file testLambdaMST3D.cpp.
Function Documentation
main()
int main (int , char **)
Definition at line 163 of file testLambdaMST3D.cpp.
{
    bool res = true;
    testLambdaMST3D testLMST;
    trace.beginBlock ( "Testing LambdaMST3D" );
        trace.beginBlock ( "Testing point only calculation" );
          res &= testLMST.lambda64ByPoint();
          res &= testLMST.lambda64Filtered();
          res &= testLMST.lambdaSinByPoint();
          res &= testLMST.lambdaExpByPoint();
        trace.endBlock();
        trace.beginBlock ( "Testing calculation for whole curve" );
           res &= testLMST.lambda64();
           res &= testLMST.lambdaSin();
           res &= testLMST.lambdaExp();
        trace.endBlock();
    trace.endBlock();
    trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
    return res ? 0 : 1;
}
References testLambdaMST3D::lambda64(), testLambdaMST3D::lambda64ByPoint(), testLambdaMST3D::lambda64Filtered(), testLambdaMST3D::lambdaExp(), testLambdaMST3D::lambdaExpByPoint(), testLambdaMST3D::lambdaSin(), testLambdaMST3D::lambdaSinByPoint(), and DGtal::trace.