DGtal: testSignal.cpp File Reference
testSignal.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/math/Signal.h"
Functions
bool testSignal ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2011/07/06
Functions for testing class Signal.
This file is part of the DGtal library.
Definition in file testSignal.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 78 of file testSignal.cpp.
{
  trace.beginBlock ( "Testing class Signal" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testSignal();
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References testSignal(), and DGtal::trace.
testSignal()
bool testSignal ()
Example of a test. To be completed.
Definition at line 46 of file testSignal.cpp.
{
  trace.beginBlock ( "Testing block ..." );
  //double values[ 8 ] = { 1.0, 5.0, 3.0, 4.3, 6.2, 7.1, 5.7, 8.4 };
  double values[ ] = { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
  Signal<double> signal( values, 8, 2, false, 0.0 );
  trace.info() << "Unperiodic signal" << endl;
  trace.info() << signal << endl;
  for ( unsigned int n = 1; n < 10; ++n )
    {
      Signal<double> Gauss = Signal<double>::G2n( n );
      Signal<double> conv_signal = signal * Gauss;
      trace.info() << conv_signal << endl;
    }
  Signal<double> signal2( values, 8, 2, true, 0.0 );
  trace.info() << "Periodic signal" << endl;
  trace.info() << signal2 << endl;
  for ( unsigned int n = 1; n < 10; ++n )
    {
      Signal<double> Gauss = Signal<double>::G2n( n );
      Signal<double> conv_signal = signal2 * Gauss;
      trace.info() << conv_signal << endl;
    }
  trace.endBlock();
  return true;
}
References DGtal::Signal< TValue >::G2n(), and DGtal::trace.
Referenced by main().