DGtal: viewer3D-4-modes.cpp File Reference
viewer3D-4-modes.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/io/viewers/PolyscopeViewer.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2011/19/03
Simple example of class PolyscopeViewer.
This file is part of the DGtal library.
Definition in file viewer3D-4-modes.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 56 of file viewer3D-4-modes.cpp.
{
  PolyscopeViewer viewer;
  Point p1( -1, -1, -2 );
  Point p2( 2, 2, 3 );
  Point p3( 1, 1, 1 );
  Point p4( 2, -1, 3 );
  Point p5( -1, 2, 3 );
  Point p6( 0, 0, 0 );
  Point p0( 0, 2, 1 );
  Domain domain( p1, p2 );
  viewer << p1 << p2 << p3<< p4<< p5 << p6 << p0;
  viewer << domain;
  // Draws point as balls instead of cubes
  viewer.drawAsBalls();
  viewer << p1 << p2 << p3<< p4<< p5 << p6 << p0;
  viewer << domain;
  // Draws a grid instead of cubes
  viewer.drawAsGrid();
  viewer << domain;
  viewer.show();
  return 0;
}
References domain, DGtal::Display3D< Space, KSpace >::drawAsBalls(), DGtal::Display3D< Space, KSpace >::drawAsGrid(), and DGtal::PolyscopeViewer< Space, KSpace >::show().