DGtal: DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor > Class Template Reference
DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor > Class Template Reference
#include <DGtal/geometry/curves/estimation/SegmentComputerEstimators.h>
Public Types
typedef DSSComputer SegmentComputer
typedef DSSComputer::ConstIterator ConstIterator
typedef double Quantity
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< Functor, SegmentComputer, Quantity >))
CurvatureFromDSSBaseEstimator ()
CurvatureFromDSSBaseEstimator (const CurvatureFromDSSBaseEstimator &other)
CurvatureFromDSSBaseEstimator & operator= (const CurvatureFromDSSBaseEstimator &other)
~CurvatureFromDSSBaseEstimator ()
bool isValid () const
void init (const double h, const ConstIterator &itb, const ConstIterator &ite)
Quantity eval (const ConstIterator &)
template<typename OutputIterator>
OutputIterator eval (const ConstIterator &itb, const ConstIterator &ite, OutputIterator result)
void attach (const SegmentComputer &aSC)
Data Fields
double myH
ConstIterator myBegin
ConstIterator myEnd
const SegmentComputer * mySCPtr
Functor myFunctor
Detailed Description
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength>
class DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >
Description of class 'CurvatureFromDSSBaseEstimator'
Aim: computes a curvature quantity from the length and/or the width of a DSS.
Template Parameters
DSSComputer a model of segment computer devoted to the DSS recognition.
The computation is delegated to a functor.
Template Parameters
Functor a model of unary functor taking a DSS as input and returning a double
This class is a model of CSegmentComputerEstimator
Definition at line 1300 of file SegmentComputerEstimators.h.
Member Typedef Documentation
ConstIterator
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> typedef DSSComputer::ConstIterator DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::ConstIterator
Definition at line 1307 of file SegmentComputerEstimators.h.
Quantity
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> typedef double DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::Quantity
Definition at line 1308 of file SegmentComputerEstimators.h.
SegmentComputer
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> typedef DSSComputer DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::SegmentComputer
Definition at line 1306 of file SegmentComputerEstimators.h.
Constructor & Destructor Documentation
CurvatureFromDSSBaseEstimator() [1/2]
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::CurvatureFromDSSBaseEstimator () inline
Default constructor. NB: not valid.
Definition at line 1342 of file SegmentComputerEstimators.h.
      : myH( 0.0 ), myBegin(), myEnd(), mySCPtr(0), myFunctor()
      {
      }
CurvatureFromDSSBaseEstimator() [2/2]
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::CurvatureFromDSSBaseEstimator (const CurvatureFromDSSBaseEstimator< DSSComputer, Functor > & other) inline
Copy constructor.
Parameters
other the object to copy.
Definition at line 1350 of file SegmentComputerEstimators.h.
      : myH( other.myH ), myBegin( other.myBegin ), myEnd( other.myEnd ),
        mySCPtr( other.mySCPtr ), myFunctor( other.myFunctor )
      {
      }
~CurvatureFromDSSBaseEstimator()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::~CurvatureFromDSSBaseEstimator () inline
Destructor
Definition at line 1374 of file SegmentComputerEstimators.h.
{}
Member Function Documentation
attach()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> void DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::attach (const SegmentComputer & aSC) inline
Attach the estimator to aSC
Parameters
aSC an instance of segment computer.
Definition at line 1512 of file SegmentComputerEstimators.h.
      {
        mySCPtr = &aSC;
        ASSERT( mySCPtr );
      };
BOOST_CONCEPT_ASSERT()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< Functor, SegmentComputer, Quantity >))
eval() [1/2]
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> Quantity DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::eval (const ConstIterator &) inline
Unique estimation
Returns
the estimated quantity
Definition at line 1406 of file SegmentComputerEstimators.h.
      {
        ASSERT( isValid() );
        //types
        typedef typename DSSComputer::Integer Integer;
        typedef typename DSSComputer::Vector Vector;
        //curvature value
        Quantity k = 0;
        //begin and end iterators
        //(back point on the first point)
        //(front point on the last point)
        ConstIterator back = mySCPtr->begin();
        ConstIterator front = mySCPtr->end();
        bool isConnectedAtBack = isNotEmpty(myBegin, back)
          &&((*boost::prior(back)-*back).norm(Vector::L_1) <= NumberTraits<Integer>::ONE);
        bool isConnectedAtFront = isNotEmpty(front, myEnd)
          &&((*boost::prior(front)-*front).norm(Vector::L_1) <= NumberTraits<Integer>::ONE);
        Integer mu = mySCPtr->mu();
        Integer omega = mySCPtr->omega();
        if (isConnectedAtBack)
        {
          --back;
          //parameters
                if (isConnectedAtFront)
          {
            if ((mySCPtr->remainder(*back)<=mu-1)&&
                (mySCPtr->remainder(*front)<=mu-1) )
            {
              //convex
              k = myFunctor(*mySCPtr) / myH;
            }
            else if ( (mySCPtr->remainder(*back)>=mu+omega)&&
                      (mySCPtr->remainder(*front)>=mu+omega) )
            {
              //concave
              k = -myFunctor(*mySCPtr) / myH;
            } //else inflection
              }
          else
          {
            if ( (mySCPtr->remainder(*back)<=mu-1) )
            {
              //convex
              k = myFunctor(*mySCPtr) / myH;
            }
            else if ( (mySCPtr->remainder(*back)>=mu+omega) )
            {
              //concave
              k = -myFunctor(*mySCPtr) / myH;
            } //else inflection
                }
              }
        else if (isConnectedAtFront)
        {
          if ( (mySCPtr->remainder(*front)<=mu-1) )
          {
            //convex
            k = myFunctor(*mySCPtr) / myH;
          }
          else if ( (mySCPtr->remainder(*front)>=mu+omega) )
          {
            //concave
            k = -myFunctor(*mySCPtr) / myH;
          } //else inflection
              } //else cannot be extended: k is set to 0
              return k;
      }
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::eval().
eval() [2/2]
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> template<typename OutputIterator> OutputIterator DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::eval (const ConstIterator & itb, const ConstIterator & ite, OutputIterator result) inline
Estimation for a subrange [itb , ite)
Parameters
itb subrange begin iterator
ite subrange end iterator
result output iterator on the estimated quantity
Returns
the estimated quantity from itb till ite (excluded)
Definition at line 1489 of file SegmentComputerEstimators.h.
      {
              ASSERT( isValid() );
        // do-while loop to deal with the case of a whole circular range
        if (isNotEmpty(itb, ite))
        {
                ConstIterator it = itb;
                do
                {
            *result++ = eval( it );
            ++it;
                } while (it != ite);
              }
        return result;
      }
init()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> void DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::init (const double h, const ConstIterator & itb, const ConstIterator & ite) inline
Initialisation.
Parameters
h grid size
itb begin iterator
ite end iterator
Definition at line 1394 of file SegmentComputerEstimators.h.
      {
        myH = h;
        myBegin = itb;
        myEnd = ite;
        ASSERT( myH > 0 );
      }
isValid()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> bool DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 1380 of file SegmentComputerEstimators.h.
      {
              return (myH > 0)&&(mySCPtr != 0);
      };
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::eval(), and DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::eval().
operator=()
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> CurvatureFromDSSBaseEstimator & DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::operator= (const CurvatureFromDSSBaseEstimator< DSSComputer, Functor > & other) inline
Assignement.
Parameters
other the object to copy.
Definition at line 1359 of file SegmentComputerEstimators.h.
      {
        if (this != &other)
        {
          myH = other.myH;
          myBegin = other.myBegin;
          myEnd = other.myEnd;
          mySCPtr = other.mySCPtr;
          myFunctor = other.myFunctor;
        }
              return *this;
      }
Field Documentation
myBegin
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> ConstIterator DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::myBegin
Begin iterator
Definition at line 1321 of file SegmentComputerEstimators.h.
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::operator=().
myEnd
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> ConstIterator DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::myEnd
End iterator
Definition at line 1325 of file SegmentComputerEstimators.h.
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::operator=().
myFunctor
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> Functor DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::myFunctor
Functor used for the estimation
Definition at line 1333 of file SegmentComputerEstimators.h.
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::eval(), and DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::operator=().
myH
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> double DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::myH
Grid step
Definition at line 1317 of file SegmentComputerEstimators.h.
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::operator=().
mySCPtr
template<typename DSSComputer, typename Functor = detail::CurvatureFromDSSLength> const SegmentComputer* DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, Functor >::mySCPtr
Aliasing pointer on a constant segment computer
Definition at line 1329 of file SegmentComputerEstimators.h.
Referenced by DGtal::detail::CurvatureFromDSSBaseEstimator< DSSComputer, detail::CurvatureFromDSSLength >::operator=().
The documentation for this class was generated from the following file:
SegmentComputerEstimators.h