DGtal: ArrayXYOfList< Value, L, X, Y > Class Template Reference
ArrayXYOfList< Value, L, X, Y > Class Template Reference
Public Member Functions
ArrayXYOfList ()
void clear ()
const Value & value (unsigned int l, unsigned int x, unsigned int y)
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int, unsigned int)
unsigned long long area () const
Private Types
typedef std::pair< DGtal::uint16_t, Value > MyPair
typedef std::forward_list< MyPair > MyList
typedef MyList::iterator Iterator
typedef MyList::const_iterator ConstIterator
Private Attributes
MyList _data [X][Y]
Detailed Description
template<typename Value, unsigned int L, unsigned int X, unsigned int Y>
class ArrayXYOfList< Value, L, X, Y >
Array[X][Y] of forward_list< pair<L,Value> > Another intermediate approach which favors less memory and more computation time.
Approximately same memory usage or 20% more as LabelledMap (for good values of N and M). Approximately 2 to 4 times slower than LabelledMap for most operations.
Note that 2000*2000*32 takes 216Mb.
Definition at line 256 of file testLabelledMap-benchmark.cpp.
Member Typedef Documentation
ConstIterator
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> typedef MyList::const_iterator ArrayXYOfList< Value, L, X, Y >::ConstIterator private
Definition at line 260 of file testLabelledMap-benchmark.cpp.
Iterator
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> typedef MyList::iterator ArrayXYOfList< Value, L, X, Y >::Iterator private
Definition at line 259 of file testLabelledMap-benchmark.cpp.
MyList
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> typedef std::forward_list<MyPair> ArrayXYOfList< Value, L, X, Y >::MyList private
Definition at line 258 of file testLabelledMap-benchmark.cpp.
MyPair
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> typedef std::pair<DGtal::uint16_t, Value> ArrayXYOfList< Value, L, X, Y >::MyPair private
Definition at line 257 of file testLabelledMap-benchmark.cpp.
Constructor & Destructor Documentation
ArrayXYOfList()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> ArrayXYOfList< Value, L, X, Y >::ArrayXYOfList () inline
Definition at line 265 of file testLabelledMap-benchmark.cpp.
  {
  }
Member Function Documentation
area()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned long long ArrayXYOfList< Value, L, X, Y >::area () const inline
Definition at line 379 of file testLabelledMap-benchmark.cpp.
  {
    unsigned long long total = 0;
    for ( unsigned int y = 0; y < Y; ++y )
      for ( unsigned int x = 0; x < X; ++x )
        {
          unsigned int size = nbLabels( x, y );
          total += sizeof( Value* )
            + ( size ) *
            ( sizeof( Value ) // one value per node
              + sizeof( Value* ) // one pointers
              + 2 // uint16_t
              + 8 // dynamic allocation );
              );
        }
    return total;
  }
References nbLabels().
clear()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfList< Value, L, X, Y >::clear () inline
Definition at line 270 of file testLabelledMap-benchmark.cpp.
  {
      for ( unsigned int y = 0; y < Y; ++y )
        for ( unsigned int x = 0; x < X; ++x )
          _data[ x ][ y ].clear();
  }
References _data, and clear().
Referenced by clear().
display()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfList< Value, L, X, Y >::display (ostream & , unsigned int , unsigned int , unsigned int) inline
Definition at line 374 of file testLabelledMap-benchmark.cpp.
  {}
erase()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayXYOfList< Value, L, X, Y >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 291 of file testLabelledMap-benchmark.cpp.
  {
    MyList & list = _data[ x ][ y ];
    Iterator it_prev = list.before_begin();
    Iterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        if ( it->first == l )
          {
            list.erase_after( it_prev );
            return 1;
          }
        it_prev = it;
      }
    return 0;
  }
References _data.
getLabels()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfList< Value, L, X, Y >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 352 of file testLabelledMap-benchmark.cpp.
  {
    labels.clear();
    const MyList & list = _data[ x ][ y ];
    ConstIterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        labels.push_back( (*it).first );
      }
  }
References _data.
hasLabel()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> bool ArrayXYOfList< Value, L, X, Y >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 341 of file testLabelledMap-benchmark.cpp.
  {
    const MyList & list = _data[ x ][ y ];
    ConstIterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        if ( it->first == l ) return true;
      }
    return false;
  }
References _data.
nbLabels()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayXYOfList< Value, L, X, Y >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 364 of file testLabelledMap-benchmark.cpp.
  {
    const MyList & list = _data[ x ][ y ];
    ConstIterator it = list.begin(), it_end = list.end();
    unsigned int n = 0;
    for ( ; it != it_end; ++it )
      ++n;
    return n;
  }
References _data.
Referenced by area().
setValue()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfList< Value, L, X, Y >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 309 of file testLabelledMap-benchmark.cpp.
  {
    MyList & list = _data[ x ][ y ];
    Iterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        if ( it->first == l )
          {
            it->second = val;
            return;
          }
      }
    if ( it == it_end )
        list.emplace_front( std::make_pair( l, val ) );
  }
References _data.
setValueNoNewLabel()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfList< Value, L, X, Y >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 325 of file testLabelledMap-benchmark.cpp.
  {
    MyList & list = _data[ x ][ y ];
    Iterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        if ( it->first == l )
          {
            it->second = val;
            return;
          }
      }
    if ( it == it_end )
      list.emplace_front( std::make_pair( l, val ) );
  }
References _data.
value()
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> const Value & ArrayXYOfList< Value, L, X, Y >::value (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 278 of file testLabelledMap-benchmark.cpp.
  {
    MyList & list = _data[ x ][ y ];
    Iterator it = list.begin(), it_end = list.end();
    for ( ; it != it_end; ++it )
      {
        if ( it->first == l ) return it->second;
      }
    ASSERT ( it == it_end ) ;
    list.emplace_front( std::make_pair( l, Value() ) );
    return list.front().second;
  }
References _data.
Field Documentation
_data
template<typename Value, unsigned int L, unsigned int X, unsigned int Y> MyList ArrayXYOfList< Value, L, X, Y >::_data[X][Y] private
Definition at line 261 of file testLabelledMap-benchmark.cpp.
Referenced by clear(), erase(), getLabels(), hasLabel(), nbLabels(), setValue(), setValueNoNewLabel(), and value().
The documentation for this class was generated from the following file:
testLabelledMap-benchmark.cpp