DGtal: DGtal::Knot_4_3< TSpace > Class Template Reference
DGtal::Knot_4_3< TSpace > Class Template Reference
Aim: Implement a parametrized knot 4, 3.
#include <DGtal/geometry/curves/parametric/Knot_4_3.h>
Public Types
typedef TSpace Space
typedef TSpace::RealPoint RealPoint
typedef TSpace::Point Point
Public Member Functions
~Knot_4_3 ()
Knot_4_3 (long double scale_1, long double scale_2, long double scale_3)
RealPoint x (long double t) const
RealPoint xp (long double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Static Public Member Functions
static double getPeriod ()
Protected Member Functions
Knot_4_3 ()
Private Member Functions
Knot_4_3 (const Knot_4_3 &other)
Knot_4_3 & operator= (const Knot_4_3 &other)
Private Attributes
long double scale [3]
Static Private Attributes
static constexpr double PERIOD = M_PI * 2.0
Detailed Description
template<typename TSpace>
class DGtal::Knot_4_3< TSpace >
Aim: Implement a parametrized knot 4, 3.
Description of class 'Knot_4_3'
Template Parameters
TSpace model of CSpace
Definition at line 59 of file Knot_4_3.h.
Member Typedef Documentation
Point
template<typename TSpace> typedef TSpace::Point DGtal::Knot_4_3< TSpace >::Point
Definition at line 65 of file Knot_4_3.h.
RealPoint
template<typename TSpace> typedef TSpace::RealPoint DGtal::Knot_4_3< TSpace >::RealPoint
Definition at line 64 of file Knot_4_3.h.
Space
template<typename TSpace> typedef TSpace DGtal::Knot_4_3< TSpace >::Space
Definition at line 63 of file Knot_4_3.h.
Constructor & Destructor Documentation
~Knot_4_3()
template<typename TSpace> DGtal::Knot_4_3< TSpace >::~Knot_4_3 () inline
Destructor.
Definition at line 70 of file Knot_4_3.h.
{}
Knot_4_3() [1/3]
template<typename TSpace> DGtal::Knot_4_3< TSpace >::Knot_4_3 (long double scale_1, long double scale_2, long double scale_3)
Constructor.
Parameters
scale_1 x-axis scaling factor
scale_2 y-axis scaling factor
scale_3 z-axis scaling factor
Referenced by Knot_4_3(), and operator=().
Knot_4_3() [2/3]
template<typename TSpace> DGtal::Knot_4_3< TSpace >::Knot_4_3 () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Knot_4_3() [3/3]
template<typename TSpace> DGtal::Knot_4_3< TSpace >::Knot_4_3 (const Knot_4_3< TSpace > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
References Knot_4_3().
Member Function Documentation
getPeriod()
template<typename TSpace> double DGtal::Knot_4_3< TSpace >::getPeriod () static
isValid()
template<typename TSpace> bool DGtal::Knot_4_3< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TSpace> Knot_4_3 & DGtal::Knot_4_3< TSpace >::operator= (const Knot_4_3< TSpace > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References Knot_4_3().
selfDisplay()
template<typename TSpace> void DGtal::Knot_4_3< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace> RealPoint DGtal::Knot_4_3< TSpace >::x (long double t) const
Parameters
t any value.
Returns
the vector (x(t), y(t), z(t))
xp()
template<typename TSpace> RealPoint DGtal::Knot_4_3< TSpace >::xp (long double t) const
Parameters
t any value.
Returns
the vector (x(t)', y(t)', z(t)')
Field Documentation
PERIOD
template<typename TSpace> double DGtal::Knot_4_3< TSpace >::PERIOD = M_PI * 2.0 static constexpr private
Definition at line 148 of file Knot_4_3.h.
scale
template<typename TSpace> long double DGtal::Knot_4_3< TSpace >::scale[3] private
Definition at line 118 of file Knot_4_3.h.
The documentation for this class was generated from the following file:
Knot_4_3.h