DGtal: MyPoint Class Reference
MyPoint Class Reference
Public Member Functions
~MyPoint ()
MyPoint (const MyPoint &other)
MyPoint (int x, int y)
MyPoint operator- (const MyPoint &other) const
double norm () const
~MyPoint ()
MyPoint (const MyPoint &other)
MyPoint (int x, int y)
MyPoint operator- (const MyPoint &other) const
double norm () const
Static Public Member Functions
static void reset ()
static void reset ()
Data Fields
int _x
int _y
Static Public Attributes
static int nbCreated = 0
static int nbDeleted = 0
Detailed Description
Examples
doc-examples/demo-kernel-1.cpp, doc-examples/kernelDomain.cpp, and io/viewers/demo-kernel-2.cpp.
Definition at line 314 of file testClone2.cpp.
Constructor & Destructor Documentation
~MyPoint() [1/2]
MyPoint::~MyPoint () inline
Definition at line 316 of file testClone2.cpp.
  { nbDeleted++; }
References nbDeleted.
MyPoint() [1/4]
MyPoint::MyPoint (const MyPoint & other) inline
Definition at line 318 of file testClone2.cpp.
    : _x( other._x ), _y( other._y )
  { nbCreated++; }
References _x, _y, MyPoint(), and nbCreated.
Referenced by MyPoint(), and operator-().
MyPoint() [2/4]
MyPoint::MyPoint (int x, int y) inline
Definition at line 321 of file testClone2.cpp.
                          : _x( x ), _y( y )
  { nbCreated++; }
References _x, _y, and nbCreated.
~MyPoint() [2/2]
MyPoint::~MyPoint () inline
Definition at line 154 of file testCloneAndAliases.cpp.
  { nbDeleted++; }
References nbDeleted.
MyPoint() [3/4]
MyPoint::MyPoint (const MyPoint & other) inline
Definition at line 156 of file testCloneAndAliases.cpp.
    : _x( other._x ), _y( other._y )
  { nbCreated++; }
References _x, _y, MyPoint(), and nbCreated.
MyPoint() [4/4]
MyPoint::MyPoint (int x, int y) inline
Definition at line 159 of file testCloneAndAliases.cpp.
                          : _x( x ), _y( y )
  { nbCreated++; }
References _x, _y, and nbCreated.
Member Function Documentation
norm() [1/2]
double MyPoint::norm () const inline
Definition at line 327 of file testClone2.cpp.
  {
    double dx = (double) _x;
    double dy = (double) _y;
    return sqrt( dx * dx + dy * dy );
  }
References _x, and _y.
norm() [2/2]
double MyPoint::norm () const inline
Definition at line 165 of file testCloneAndAliases.cpp.
  {
    double dx = (double) _x;
    double dy = (double) _y;
    return sqrt( dx * dx + dy * dy );
  }
References _x, and _y.
operator-() [1/2]
MyPoint MyPoint::operator- (const MyPoint & other) const inline
Definition at line 323 of file testClone2.cpp.
  {
    return MyPoint( _x - other._x, _y - other._y );
  }
References _x, _y, and MyPoint().
operator-() [2/2]
MyPoint MyPoint::operator- (const MyPoint & other) const inline
Definition at line 161 of file testCloneAndAliases.cpp.
  {
    return MyPoint( _x - other._x, _y - other._y );
  }
References _x, _y, and MyPoint().
reset() [1/2]
void MyPoint::reset () inline static
Definition at line 333 of file testClone2.cpp.
  {
    nbCreated = nbDeleted = 0;
  }
References nbCreated, and nbDeleted.
Referenced by main().
reset() [2/2]
void MyPoint::reset () inline static
Definition at line 171 of file testCloneAndAliases.cpp.
  {
    nbCreated = nbDeleted = 0;
  }
References nbCreated, and nbDeleted.
Field Documentation
_x
int MyPoint::_x
Definition at line 337 of file testClone2.cpp.
Referenced by MyPoint(), MyPoint(), norm(), and operator-().
_y
int MyPoint::_y
Definition at line 337 of file testClone2.cpp.
Referenced by MyPoint(), MyPoint(), norm(), and operator-().
nbCreated
int MyPoint::nbCreated = 0 static
Definition at line 339 of file testClone2.cpp.
Referenced by MyPoint(), MyPoint(), and reset().
nbDeleted
int MyPoint::nbDeleted = 0 static
Definition at line 340 of file testClone2.cpp.
Referenced by reset(), and ~MyPoint().
The documentation for this class was generated from the following files:
testClone2.cpp
testCloneAndAliases.cpp