DGtal: MyImage< T, N > Class Template Reference
MyImage< T, N > Class Template Reference
[includes]
Public Types
typedef MyImage< T, N > Self
typedef DGtal::IteratorCompletionTraits< Self >::Iterator Iterator
typedef DGtal::IteratorCompletionTraits< Self >::ConstIterator ConstIterator
typedef T Value
typedef DGtal::SpaceND< N > Space
typedef DGtal::HyperRectDomain< Space > Domain
typedef Space::Point Point
typedef DGtal::Linearizer< Domain, DGtal::ColMajorStorage > Linearizer
Linearization of the points.
Public Types inherited from DGtal::IteratorCompletion< MyImage< T, N > >
typedef IteratorCompletionTraits< MyImage< T, N > >::Iterator Iterator
Mutable iterator type.
typedef IteratorCompletionTraits< MyImage< T, N > >::ConstIterator ConstIterator
Constant iterator type.
typedef IteratorCompletionTraits< MyImage< T, N > >::DistanceFunctor DistanceFunctor
Type of the functor calculating the distance between iterators.
typedef boost::reverse_iterator< Iterator > ReverseIterator
Mutable reverse iterator type.
typedef boost::reverse_iterator< ConstIterator > ConstReverseIterator
Constant reverse iterator type.
typedef SimpleRandomAccessRangeFromPoint< ConstIterator, Iterator, DistanceFunctor > Range
Mutable range type.
typedef SimpleRandomAccessConstRangeFromPoint< ConstIterator, DistanceFunctor > ConstRange
Constant range type.
typedef std::ptrdiff_t Difference
Type of the distance between two iterators.
Public Member Functions
MyImage (Domain const &aDomain=Domain())
~MyImage ()
Value operator() (Point const &aPoint) const
[MyImageHeader]
Value getValue (Point const &aPoint) const
void setValue (Point const &aPoint, Value const &aValue)
Domain const & domain () const
Self & operator= (Self const &other)
Iterator begin ()
[CImageBasicInterface]
ConstIterator begin () const
Iterator end ()
ConstIterator end () const
Public Member Functions inherited from DGtal::IteratorCompletion< MyImage< T, N > >
ReverseIterator rbegin ()
ConstReverseIterator crbegin () const
ReverseIterator rend ()
ConstReverseIterator crend () const
Range range ()
ConstRange constRange () const
Private Attributes
Domain myDomain
[BasicIteratorInterface]
T * myData
Additional Inherited Members
Protected Member Functions inherited from DGtal::IteratorCompletion< MyImage< T, N > >
~IteratorCompletion ()
Protected destructor to avoid memory leak.
Detailed Description
template<typename T, DGtal::Dimension N>
class MyImage< T, N >
[includes]
[includes] [MyImageHeader]
Definition at line 48 of file exampleIteratorCompletion.cpp.
Member Typedef Documentation
ConstIterator
template<typename T, DGtal::Dimension N> typedef DGtal::IteratorCompletionTraits<Self>::ConstIterator MyImage< T, N >::ConstIterator
Definition at line 56 of file exampleIteratorCompletion.cpp.
Domain
template<typename T, DGtal::Dimension N> typedef DGtal::HyperRectDomain<Space> MyImage< T, N >::Domain
Definition at line 60 of file exampleIteratorCompletion.cpp.
Iterator
template<typename T, DGtal::Dimension N> typedef DGtal::IteratorCompletionTraits<Self>::Iterator MyImage< T, N >::Iterator
Definition at line 55 of file exampleIteratorCompletion.cpp.
Linearizer
template<typename T, DGtal::Dimension N> typedef DGtal::Linearizer<Domain, DGtal::ColMajorStorage> MyImage< T, N >::Linearizer
Linearization of the points.
Definition at line 62 of file exampleIteratorCompletion.cpp.
Point
template<typename T, DGtal::Dimension N> typedef Space::Point MyImage< T, N >::Point
Definition at line 61 of file exampleIteratorCompletion.cpp.
Self
template<typename T, DGtal::Dimension N> typedef MyImage<T, N> MyImage< T, N >::Self
Definition at line 54 of file exampleIteratorCompletion.cpp.
Space
template<typename T, DGtal::Dimension N> typedef DGtal::SpaceND<N> MyImage< T, N >::Space
Definition at line 59 of file exampleIteratorCompletion.cpp.
Value
template<typename T, DGtal::Dimension N> typedef T MyImage< T, N >::Value
Definition at line 58 of file exampleIteratorCompletion.cpp.
Constructor & Destructor Documentation
MyImage()
template<typename T, DGtal::Dimension N> MyImage< T, N >::MyImage (Domain const & aDomain = Domain()) inline
Definition at line 65 of file exampleIteratorCompletion.cpp.
    : myDomain(aDomain), myData( new T[ myDomain.size() ] )
    {}
References myData, and myDomain.
~MyImage()
template<typename T, DGtal::Dimension N> MyImage< T, N >::~MyImage () inline
Definition at line 70 of file exampleIteratorCompletion.cpp.
    {
      delete[] myData;
    }
References myData.
Member Function Documentation
begin() [1/2]
template<typename T, DGtal::Dimension N> Iterator MyImage< T, N >::begin () inline
[CImageBasicInterface]
[BasicIteratorInterface]
Definition at line 122 of file exampleIteratorCompletion.cpp.
    {
      return myData;
    }
References myData.
Referenced by operator=().
begin() [2/2]
template<typename T, DGtal::Dimension N> ConstIterator MyImage< T, N >::begin () const inline
Definition at line 128 of file exampleIteratorCompletion.cpp.
    {
      return myData;
    }
References myData.
domain()
template<typename T, DGtal::Dimension N> Domain const & MyImage< T, N >::domain () const inline
Definition at line 98 of file exampleIteratorCompletion.cpp.
    {
      return myDomain;
    }
References myDomain.
Referenced by operator=().
end() [1/2]
template<typename T, DGtal::Dimension N> Iterator MyImage< T, N >::end () inline
Definition at line 134 of file exampleIteratorCompletion.cpp.
    {
      return myData + myDomain.size();
    }
References myData, and myDomain.
Referenced by operator=().
end() [2/2]
template<typename T, DGtal::Dimension N> ConstIterator MyImage< T, N >::end () const inline
Definition at line 140 of file exampleIteratorCompletion.cpp.
    {
      return myData + myDomain.size();
    }
References myData, and myDomain.
getValue()
template<typename T, DGtal::Dimension N> Value MyImage< T, N >::getValue (Point const & aPoint) const inline
Definition at line 86 of file exampleIteratorCompletion.cpp.
    {
      return operator()(aPoint);
    }
References aPoint, and operator()().
operator()()
template<typename T, DGtal::Dimension N> Value MyImage< T, N >::operator() (Point const & aPoint) const inline
[MyImageHeader]
[CImageBasicInterface]
Definition at line 80 of file exampleIteratorCompletion.cpp.
    {
      return myData[ Linearizer::getIndex(aPoint, myDomain) ];
    }
References aPoint, myData, and myDomain.
Referenced by getValue().
operator=()
template<typename T, DGtal::Dimension N> Self & MyImage< T, N >::operator= (Self const & other) inline
Definition at line 104 of file exampleIteratorCompletion.cpp.
    {
      if ( this != &other )
        {
          myDomain = other.domain();
          delete[] myData;
          myData = new Value[ myDomain.size() ];
          std::copy( other.begin(), other.end(), begin() );
        }
      return *this;
    }
References begin(), domain(), end(), myData, and myDomain.
setValue()
template<typename T, DGtal::Dimension N> void MyImage< T, N >::setValue (Point const & aPoint, Value const & aValue) inline
Definition at line 92 of file exampleIteratorCompletion.cpp.
    {
      myData[ Linearizer::getIndex(aPoint, myDomain) ] = aValue;
    }
References aPoint, myData, and myDomain.
Referenced by testImageCopyShort().
Field Documentation
myData
template<typename T, DGtal::Dimension N> T* MyImage< T, N >::myData private
Definition at line 150 of file exampleIteratorCompletion.cpp.
Referenced by begin(), begin(), end(), end(), MyImage(), operator()(), operator=(), setValue(), and ~MyImage().
myDomain
template<typename T, DGtal::Dimension N> Domain MyImage< T, N >::myDomain private
[BasicIteratorInterface]
[PrivateMembers]
Definition at line 149 of file exampleIteratorCompletion.cpp.
Referenced by domain(), end(), end(), MyImage(), operator()(), operator=(), and setValue().
The documentation for this class was generated from the following file:
exampleIteratorCompletion.cpp