DGtal: DGtal::BLUELocalLengthEstimator< TConstIterator > Class Template Reference
DGtal::BLUELocalLengthEstimator< TConstIterator > Class Template Reference
Aim: Best Linear Unbiased Two step length estimator.
#include <DGtal/geometry/curves/estimation/BLUELocalLengthEstimator.h>
Public Types
typedef TConstIterator ConstIterator
typedef double Quantity
Public Types inherited from DGtal::TwoStepLocalLengthEstimator< TConstIterator >
typedef TConstIterator ConstIterator
typedef double Quantity
Public Member Functions
BLUELocalLengthEstimator ()
BLUELocalLengthEstimator (const BLUELocalLengthEstimator &other)=delete
BLUELocalLengthEstimator & operator= (const BLUELocalLengthEstimator &other)=delete
void selfDisplay (std::ostream &out) const
Public Member Functions inherited from DGtal::TwoStepLocalLengthEstimator< TConstIterator >
TwoStepLocalLengthEstimator ()=delete
TwoStepLocalLengthEstimator (const double wdirect, const double wdiag)
~TwoStepLocalLengthEstimator ()=default
TwoStepLocalLengthEstimator (const TwoStepLocalLengthEstimator &other)=delete
TwoStepLocalLengthEstimator & operator= (const TwoStepLocalLengthEstimator &other)=delete
Quantity eval (const ConstIterator &itb, const ConstIterator &ite, const double h=1.) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Detailed Description
template<typename TConstIterator>
class DGtal::BLUELocalLengthEstimator< TConstIterator >
Aim: Best Linear Unbiased Two step length estimator.
Description of template class 'BLUELocalLengthEstimator'
Note
L. Dorst & A.W.M. Smeulders "Length Estimators for Digitized Contours", Computer Vision, Graphics, and Image Processing, vol 40, pp.311-333, 1987
Model of CGlobalCurveGeometricEstimator
Template Parameters
TConstIterator a model of CConstIteratorOnArrows.
Definition at line 69 of file BLUELocalLengthEstimator.h.
Member Typedef Documentation
ConstIterator
template<typename TConstIterator> typedef TConstIterator DGtal::BLUELocalLengthEstimator< TConstIterator >::ConstIterator
Definition at line 76 of file BLUELocalLengthEstimator.h.
Quantity
template<typename TConstIterator> typedef double DGtal::BLUELocalLengthEstimator< TConstIterator >::Quantity
Definition at line 77 of file BLUELocalLengthEstimator.h.
Constructor & Destructor Documentation
BLUELocalLengthEstimator() [1/2]
template<typename TConstIterator> DGtal::BLUELocalLengthEstimator< TConstIterator >::BLUELocalLengthEstimator () inline
Default Constructor.
Definition at line 83 of file BLUELocalLengthEstimator.h.
                              :
      TwoStepLocalLengthEstimator<TConstIterator>(0.948,1.343)
    {}
References DGtal::TwoStepLocalLengthEstimator< TConstIterator >::TwoStepLocalLengthEstimator().
Referenced by BLUELocalLengthEstimator(), and operator=().
BLUELocalLengthEstimator() [2/2]
template<typename TConstIterator> DGtal::BLUELocalLengthEstimator< TConstIterator >::BLUELocalLengthEstimator (const BLUELocalLengthEstimator< TConstIterator > & other) delete
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
References BLUELocalLengthEstimator().
Member Function Documentation
operator=()
template<typename TConstIterator> BLUELocalLengthEstimator & DGtal::BLUELocalLengthEstimator< TConstIterator >::operator= (const BLUELocalLengthEstimator< TConstIterator > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References BLUELocalLengthEstimator().
selfDisplay()
template<typename TConstIterator> void DGtal::BLUELocalLengthEstimator< TConstIterator >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 109 of file BLUELocalLengthEstimator.h.
    {
      out << "[BLUELocalLengthEstimator]";
      if (this->isValid())
        out <<" initialized";
      else
        out<< " not initialized";
    }
References DGtal::TwoStepLocalLengthEstimator< TConstIterator >::isValid().
The documentation for this class was generated from the following file:
BLUELocalLengthEstimator.h