DGtal: DGtal::RosenProffittLocalLengthEstimator< TConstIterator > Class Template Reference
DGtal::RosenProffittLocalLengthEstimator< TConstIterator > Class Template Reference
Aim: Rosen-Proffitt Length Estimator.
#include <DGtal/geometry/curves/estimation/RosenProffittLocalLengthEstimator.h>
Public Types
typedef TConstIterator ConstIterator
typedef double Quantity
Public Types inherited from DGtal::TwoStepLocalLengthEstimator< TConstIterator >
typedef TConstIterator ConstIterator
typedef double Quantity
Public Member Functions
RosenProffittLocalLengthEstimator ()
RosenProffittLocalLengthEstimator (const RosenProffittLocalLengthEstimator &other)=delete
RosenProffittLocalLengthEstimator & operator= (const RosenProffittLocalLengthEstimator &other)=delete
void selfDisplay (std::ostream &out) const
Public Member Functions inherited from DGtal::TwoStepLocalLengthEstimator< TConstIterator >
TwoStepLocalLengthEstimator ()=delete
TwoStepLocalLengthEstimator (const double wdirect, const double wdiag)
~TwoStepLocalLengthEstimator ()=default
TwoStepLocalLengthEstimator (const TwoStepLocalLengthEstimator &other)=delete
TwoStepLocalLengthEstimator & operator= (const TwoStepLocalLengthEstimator &other)=delete
Quantity eval (const ConstIterator &itb, const ConstIterator &ite, const double h=1.) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Detailed Description
template<typename TConstIterator>
class DGtal::RosenProffittLocalLengthEstimator< TConstIterator >
Aim: Rosen-Proffitt Length Estimator.
Description of template class 'RosenProffittLocalLengthEstimator'
Note
T. J. Ellis and D. Proffitt and D. Rosen and W. Rutkowski Measurement of the lengths of digitized curved lines Computer Graphics and Image Processing, Vol. 10, pp. 333-347, August 1979
Model of CGlobalCurveGeometricEstimator
Template Parameters
TConstIterator a model of CConstIteratorOnArrows.
Definition at line 69 of file RosenProffittLocalLengthEstimator.h.
Member Typedef Documentation
ConstIterator
template<typename TConstIterator> typedef TConstIterator DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::ConstIterator
Definition at line 76 of file RosenProffittLocalLengthEstimator.h.
Quantity
template<typename TConstIterator> typedef double DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::Quantity
Definition at line 77 of file RosenProffittLocalLengthEstimator.h.
Constructor & Destructor Documentation
RosenProffittLocalLengthEstimator() [1/2]
template<typename TConstIterator> DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::RosenProffittLocalLengthEstimator () inline
Default Constructor.
Definition at line 83 of file RosenProffittLocalLengthEstimator.h.
                                       :
      TwoStepLocalLengthEstimator<TConstIterator>(M_PI*(sqrt(2.0f)+1.0)/8.0,
              M_PI*(sqrt(2.0f)+2.0)/16.0)
    {}
References DGtal::TwoStepLocalLengthEstimator< TConstIterator >::TwoStepLocalLengthEstimator().
Referenced by operator=(), and RosenProffittLocalLengthEstimator().
RosenProffittLocalLengthEstimator() [2/2]
template<typename TConstIterator> DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::RosenProffittLocalLengthEstimator (const RosenProffittLocalLengthEstimator< TConstIterator > & other) delete
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
References RosenProffittLocalLengthEstimator().
Member Function Documentation
operator=()
template<typename TConstIterator> RosenProffittLocalLengthEstimator & DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::operator= (const RosenProffittLocalLengthEstimator< TConstIterator > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
References RosenProffittLocalLengthEstimator().
selfDisplay()
template<typename TConstIterator> void DGtal::RosenProffittLocalLengthEstimator< TConstIterator >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 110 of file RosenProffittLocalLengthEstimator.h.
    {
      out << "[RosenProffittLocalLengthEstimator]";
      if (this->isValid())
        out <<" initialized";
      else
        out<< " not initialized";
    }
References DGtal::TwoStepLocalLengthEstimator< TConstIterator >::isValid().
The documentation for this class was generated from the following file:
RosenProffittLocalLengthEstimator.h