DGtal: testLambdaMST3D Class Reference
testLambdaMST3D Class Reference
Public Member Functions
testLambdaMST3D ()
bool lambda64ByPoint ()
bool lambda64 ()
bool lambda64Filtered ()
bool lambdaSinByPoint ()
bool lambdaSin ()
bool lambdaExpByPoint ()
bool lambdaExp ()
Private Types
typedef DGtal::Z3i::Point Point
typedef DGtal::Z2i::Point Point2D
typedef std::vector< Point > Range
typedef std::list< Point2D > Range2D
typedef Range::const_iterator ConstIterator
typedef Range2D::const_iterator ConstIterator2D
typedef Naive3DDSSComputer< ConstIterator, int, 8 > SegmentComputer
typedef SaturatedSegmentation< SegmentComputer > Segmentation
typedef ArithmeticalDSSComputer< ConstIterator2D, int, 8 > SegmentComputer2D
typedef SaturatedSegmentation< SegmentComputer2D > Segmentation2D
Private Attributes
Range curve
Detailed Description
Definition at line 55 of file testLambdaMST3D.cpp.
Member Typedef Documentation
ConstIterator
typedef Range::const_iterator testLambdaMST3D::ConstIterator private
Definition at line 61 of file testLambdaMST3D.cpp.
ConstIterator2D
typedef Range2D::const_iterator testLambdaMST3D::ConstIterator2D private
Definition at line 62 of file testLambdaMST3D.cpp.
Point
typedef DGtal::Z3i::Point testLambdaMST3D::Point private
Definition at line 57 of file testLambdaMST3D.cpp.
Point2D
typedef DGtal::Z2i::Point testLambdaMST3D::Point2D private
Definition at line 58 of file testLambdaMST3D.cpp.
Range
typedef std::vector< Point > testLambdaMST3D::Range private
Definition at line 59 of file testLambdaMST3D.cpp.
Range2D
typedef std::list< Point2D > testLambdaMST3D::Range2D private
Definition at line 60 of file testLambdaMST3D.cpp.
Segmentation
typedef SaturatedSegmentation<SegmentComputer> testLambdaMST3D::Segmentation private
Definition at line 64 of file testLambdaMST3D.cpp.
Segmentation2D
typedef SaturatedSegmentation<SegmentComputer2D> testLambdaMST3D::Segmentation2D private
Definition at line 66 of file testLambdaMST3D.cpp.
SegmentComputer
typedef Naive3DDSSComputer< ConstIterator, int, 8 > testLambdaMST3D::SegmentComputer private
Definition at line 63 of file testLambdaMST3D.cpp.
SegmentComputer2D
typedef ArithmeticalDSSComputer< ConstIterator2D, int, 8 > testLambdaMST3D::SegmentComputer2D private
Definition at line 65 of file testLambdaMST3D.cpp.
Constructor & Destructor Documentation
testLambdaMST3D()
testLambdaMST3D::testLambdaMST3D () inline
Definition at line 70 of file testLambdaMST3D.cpp.
  {
    fstream inputStream;
    inputStream.open ( (testPath + "samples/sinus3D.dat").c_str(), std::ios::in );
    try {
      curve = PointListReader<Point>::getPointsFromInputStream ( inputStream );
      if ( curve.size() == 0) throw IOException();
    } catch (DGtal::IOException & ioe) {
      trace.error() << "Size is null." << endl;
    }
  }
References curve, DGtal::PointListReader< TPoint >::getPointsFromInputStream(), and DGtal::trace.
Member Function Documentation
lambda64()
bool testLambdaMST3D::lambda64 () inline
Definition at line 91 of file testLambdaMST3D.cpp.
  {
    Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
    LambdaMST3D < Segmentation > lmst64;
    lmst64.attach ( segmenter );
    lmst64.init ( curve.begin(), curve.end() );
    vector < RealVector > tangent;
    lmst64.eval < back_insert_iterator< vector < RealVector > > > ( curve.begin(), curve.end(), back_insert_iterator< vector < RealVector > > ( tangent ) );
    return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambda64ByPoint()
bool testLambdaMST3D::lambda64ByPoint () inline
Definition at line 81 of file testLambdaMST3D.cpp.
  {
    Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
    LambdaMST3D < Segmentation > lmst64;
    lmst64.attach ( segmenter );
    lmst64.init ( curve.begin(), curve.end() );
    for ( ConstIterator it = curve.begin(); it != curve.end(); ++it )
      lmst64.eval ( *it );
    return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambda64Filtered()
bool testLambdaMST3D::lambda64Filtered () inline
Definition at line 102 of file testLambdaMST3D.cpp.
  {
      Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
      LambdaMST3D < Segmentation, Lambda64Function, DSSLengthLessEqualFilter < SegmentComputer > > lmst64;
      lmst64.attach ( segmenter );
      lmst64.getDSSFilter ( ).init ( 1 );
      lmst64.init ( curve.begin(), curve.end() );
      for ( ConstIterator it = curve.begin(); it != curve.end(); ++it )
          lmst64.eval ( *it );
      return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::getDSSFilter(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambdaExp()
bool testLambdaMST3D::lambdaExp () inline
Definition at line 147 of file testLambdaMST3D.cpp.
  {
      Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
      LambdaMST3D < Segmentation, LambdaExponentialFunction > lmst;
      lmst.attach ( segmenter );
      lmst.init ( curve.begin(), curve.end() );
      vector < RealVector > tangent;
      lmst.eval < back_insert_iterator< vector < RealVector > > > ( curve.begin(), curve.end(), back_insert_iterator< vector < RealVector > > ( tangent ) );
      return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambdaExpByPoint()
bool testLambdaMST3D::lambdaExpByPoint () inline
Definition at line 136 of file testLambdaMST3D.cpp.
  {
      Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
      LambdaMST3D < Segmentation, LambdaExponentialFunction > lmst;
      lmst.attach ( segmenter );
      lmst.init ( curve.begin(), curve.end() );
      for ( ConstIterator it = curve.begin(); it != curve.end(); ++it )
          lmst.eval ( *it );
      return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambdaSin()
bool testLambdaMST3D::lambdaSin () inline
Definition at line 125 of file testLambdaMST3D.cpp.
  {
      Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
      LambdaMST3D < Segmentation, LambdaSinFromPiFunction > lmst;
      lmst.attach ( segmenter );
      lmst.init ( curve.begin(), curve.end() );
      vector < RealVector > tangent;
      lmst.eval < back_insert_iterator< vector < RealVector > > > ( curve.begin(), curve.end(), back_insert_iterator< vector < RealVector > > ( tangent ) );
      return true;
  }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
lambdaSinByPoint()
bool testLambdaMST3D::lambdaSinByPoint () inline
Definition at line 114 of file testLambdaMST3D.cpp.
  {
     Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
     LambdaMST3D < Segmentation, LambdaSinFromPiFunction > lmst;
     lmst.attach ( segmenter );
     lmst.init ( curve.begin(), curve.end() );
     for ( ConstIterator it = curve.begin(); it != curve.end(); ++it )
         lmst.eval ( *it );
     return true;
 }
References DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::attach(), curve, DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::eval(), and DGtal::LambdaMST3DEstimator< TSpace, TSegmentation, Functor, DSSFilter >::init().
Referenced by main().
Field Documentation
curve
Range testLambdaMST3D::curve private
Definition at line 68 of file testLambdaMST3D.cpp.
Referenced by lambda64(), lambda64ByPoint(), lambda64Filtered(), lambdaExp(), lambdaExpByPoint(), lambdaSin(), lambdaSinByPoint(), and testLambdaMST3D().
The documentation for this class was generated from the following file:
testLambdaMST3D.cpp