DGtal: DGtal::LInfLocalDistance< TImage, TSet > Class Template Reference
DGtal::LInfLocalDistance< TImage, TSet > Class Template Reference
Aim: Class for the computation of the LInf-distance at some point p, from the available distance values of some points lying in the 1-neighborhood of p (ie. points at a L1-distance to p equal to 1).
#include <DGtal/geometry/volumes/distance/FMMPointFunctors.h>
Public Types
typedef TImage Image
typedef Image::Point Point
typedef Image::Value Value
typedef TSet Set
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TImage >))
image
BOOST_CONCEPT_ASSERT ((concepts::CDigitalSet< TSet >))
set
BOOST_STATIC_ASSERT ((boost::is_same< Point, typename TSet::Point >::value))
LInfLocalDistance (Image &aImg, TSet &aSet)
LInfLocalDistance (const LInfLocalDistance &other)
LInfLocalDistance & operator= (const LInfLocalDistance &other)
~LInfLocalDistance ()
Value operator() (const Point &aPoint)
void selfDisplay (std::ostream &out) const
Data Fields
Image * myImgPtr
Aliasing pointer on the underlying image.
Set * mySetPtr
Aliasing pointer on the underlying set.
Private Types
typedef std::vector< Value > Values
Private Member Functions
Value compute (Values &aValueList) const
Detailed Description
template<typename TImage, typename TSet>
class DGtal::LInfLocalDistance< TImage, TSet >
Aim: Class for the computation of the LInf-distance at some point p, from the available distance values of some points lying in the 1-neighborhood of p (ie. points at a L1-distance to p equal to 1).
Description of template class 'LInfLocalDistance'
If there is only one available distance value v in the 1-neighborhood of p, the computed value is merely incremented or decremented. Otherwise, it is the maximum over all the available distance value in the 1-neighborhood of p.
It is a model of CPointFunctor.
Template Parameters
TImage model of CImage used for the mapping point-distance value
TSet model of CDigitalSet for storing points whose distance value is known
See also
FMM
Definition at line 357 of file FMMPointFunctors.h.
Member Typedef Documentation
Image
template<typename TImage, typename TSet> typedef TImage DGtal::LInfLocalDistance< TImage, TSet >::Image
Definition at line 365 of file FMMPointFunctors.h.
Point
template<typename TImage, typename TSet> typedef Image::Point DGtal::LInfLocalDistance< TImage, TSet >::Point
Definition at line 366 of file FMMPointFunctors.h.
Set
template<typename TImage, typename TSet> typedef TSet DGtal::LInfLocalDistance< TImage, TSet >::Set
Definition at line 371 of file FMMPointFunctors.h.
Value
template<typename TImage, typename TSet> typedef Image::Value DGtal::LInfLocalDistance< TImage, TSet >::Value
Definition at line 367 of file FMMPointFunctors.h.
Values
template<typename TImage, typename TSet> typedef std::vector<Value> DGtal::LInfLocalDistance< TImage, TSet >::Values private
Definition at line 376 of file FMMPointFunctors.h.
Constructor & Destructor Documentation
LInfLocalDistance() [1/2]
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::LInfLocalDistance (Image & aImg, TSet & aSet)
Constructor from an image and a set. NB: only pointers are stored
Parameters
aImg any distance map
aSet any digital set
Referenced by LInfLocalDistance(), and operator=().
LInfLocalDistance() [2/2]
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::LInfLocalDistance (const LInfLocalDistance< TImage, TSet > & other)
Copy constructor.
Parameters
other the object to clone.
References LInfLocalDistance().
~LInfLocalDistance()
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::~LInfLocalDistance ()
Destructor. Does nothing.
Member Function Documentation
BOOST_CONCEPT_ASSERT() [1/2]
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::BOOST_CONCEPT_ASSERT ((concepts::CDigitalSet< TSet >))
set
BOOST_CONCEPT_ASSERT() [2/2]
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TImage >))
image
BOOST_STATIC_ASSERT()
template<typename TImage, typename TSet> DGtal::LInfLocalDistance< TImage, TSet >::BOOST_STATIC_ASSERT ((boost::is_same< Point, typename TSet::Point >::value))
compute()
template<typename TImage, typename TSet> Value DGtal::LInfLocalDistance< TImage, TSet >::compute (Values & aValueList) const private
Returns the LInf-distance at some point, knowing the distance of its neighbors
Parameters
aValueList the distance of (some of) the neighbors
Returns
the computed distance.
operator()()
template<typename TImage, typename TSet> Value DGtal::LInfLocalDistance< TImage, TSet >::operator() (const Point & aPoint)
LInf-distance computation at aPoint , from the available distance values of the 1-neighbors of aPoint .
Parameters
aPoint the point for which the distance is computed
Returns
the distance value at aPoint.
References aPoint.
operator=()
template<typename TImage, typename TSet> LInfLocalDistance & DGtal::LInfLocalDistance< TImage, TSet >::operator= (const LInfLocalDistance< TImage, TSet > & other)
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
References LInfLocalDistance().
selfDisplay()
template<typename TImage, typename TSet> void DGtal::LInfLocalDistance< TImage, TSet >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Field Documentation
myImgPtr
template<typename TImage, typename TSet> Image* DGtal::LInfLocalDistance< TImage, TSet >::myImgPtr
Aliasing pointer on the underlying image.
Definition at line 381 of file FMMPointFunctors.h.
mySetPtr
template<typename TImage, typename TSet> Set* DGtal::LInfLocalDistance< TImage, TSet >::mySetPtr
Aliasing pointer on the underlying set.
Definition at line 383 of file FMMPointFunctors.h.
The documentation for this class was generated from the following file:
FMMPointFunctors.h