DGtal: dgtalBoard2D-3-custom-classes.cpp File Reference
dgtalBoard2D-3-custom-classes.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/Color.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2010/11/26
An example file named dgtalboard-3-custom-classes.
This file is part of the DGtal library.
Definition in file dgtalBoard2D-3-custom-classes.cpp.
Function Documentation
main()
int main (void)
Definition at line 54 of file dgtalBoard2D-3-custom-classes.cpp.
{
  trace.beginBlock ( "Example dgtalBoard2D-3-custom-classes" );
  Point p1( -3, -2 );
  Point p2( 7, 3 );
  Point p3( 0, 0 );
  Domain domain( p1, p2 );
  Color red( 255, 0, 0 );
  Color dred( 192, 0, 0 );
  Color dgreen( 0, 192, 0 );
  Color blue( 0, 0, 255 );
  Color dblue( 0, 0, 192 );
  Board2D board;
  board << domain
  << CustomStyle( p1.className(), new CustomColors( red, dred ) )
  << p1
  << CustomStyle( p2.className(), new CustomFillColor( dgreen ) )
  << p2
  << CustomStyle( p3.className(),
      new CustomPen( blue, dblue, 6.0,
               Board2D::Shape::SolidStyle,
               Board2D::Shape::RoundCap,
               Board2D::Shape::RoundJoin ) )
  << p3;
  board.saveSVG("dgtalBoard2D-3-custom-classes.svg");
  board.saveEPS("dgtalBoard2D-3-custom-classes.eps");
  board.saveTikZ("dgtalBoard2D-3-custom-classes.tikz");
#ifdef DGTAL_WITH_CAIRO
  board.saveCairo("dgtalBoard2D-3-custom-classes-cairo.pdf", Board2D::CairoPDF);
  board.saveCairo("dgtalBoard2D-3-custom-classes-cairo.png", Board2D::CairoPNG);
  board.saveCairo("dgtalBoard2D-3-custom-classes-cairo.ps", Board2D::CairoPS);
  board.saveCairo("dgtalBoard2D-3-custom-classes-cairo.svg", Board2D::CairoSVG);
#endif
  trace.endBlock();
  return 0;
}
References LibBoard::Board::CairoPDF, LibBoard::Board::CairoPNG, LibBoard::Board::CairoPS, LibBoard::Board::CairoSVG, domain, LibBoard::Shape::RoundCap, LibBoard::Shape::RoundJoin, LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveSVG(), LibBoard::Board::saveTikZ(), LibBoard::Shape::SolidStyle, and DGtal::trace.