DGtal: freemanChainFromImage.cpp File Reference
freemanChainFromImage.cpp File Reference
DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/curves/FreemanChain.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/io/Color.h"
Functions
int main ()
[freemanChainFromImage-displayIncludes]
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2010/12/01
An example of FreemanChain display with background source image.
This file is part of the DGtal library.
Definition in file freemanChainFromImage.cpp.
Function Documentation
main()
int main (void)
[freemanChainFromImage-displayIncludes]
[freemanChainFromImage-imageImport]
[freemanChainFromImage-imageImport]
[freemanChainFromImage-ksspace]
[freemanChainFromImage-ksspace]
[freemanChainFromImage-setAppend]
[freemanChainFromImage-setAppend]
[freemanChainFromImage-displaySet]
[freemanChainFromImage-displaySet]
[freemanChainFromImage-adj]
[freemanChainFromImage-adj]
[freemanChainFromImage-extraction]
[freemanChainFromImage-extraction]
[freemanChainFromImage-fcConstruction]
[freemanChainFromImage-fcConstruction] [freemanChainFromImage-fcdysplay]
[freemanChainFromImage-fcdysplay]
Definition at line 63 of file freemanChainFromImage.cpp.
{
  typedef DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, unsigned char> Image;
  std::string filename =  examplesPath + "samples/circleR10modif.pgm";
  Image image = DGtal::PGMReader<Image>::importPGM(filename);
  Z2i::KSpace ks;
  ks.init( image.domain().lowerBound(), image.domain().upperBound(), true );
  Z2i::DigitalSet set2d (image.domain());
  SetFromImage<Z2i::DigitalSet>::append<Image>(set2d, image, 1, 255);
  Board2D aBoard;
  aBoard << set2d;
  aBoard << image.domain();
  SurfelAdjacency<2> sAdj( true );
  std::vector< std::vector< Z2i::Point >  >  vectContoursBdryPointels;
  Surfaces<Z2i::KSpace>::extractAllPointContours4C( vectContoursBdryPointels,
                ks, set2d, sAdj );
  GradientColorMap<int> cmap_grad( 0, (int)vectContoursBdryPointels.size() );
  cmap_grad.addColor( Color( 50, 50, 255 ) );
  cmap_grad.addColor( Color( 255, 0, 0 ) );
  cmap_grad.addColor( Color( 255, 255, 10 ) );
  cmap_grad.addColor( Color( 25, 255, 255 ) );
  cmap_grad.addColor( Color( 255, 25, 255 ) );
  cmap_grad.addColor( Color( 25, 25, 25 ) );
  for(unsigned int i=0; i<vectContoursBdryPointels.size(); i++){
    //  Constructing and displaying FreemanChains from contours.
    FreemanChain<Z2i::Integer> fc (vectContoursBdryPointels.at(i));
    aBoard << SetMode( fc.className(), "InterGrid" );
    aBoard<< CustomStyle( fc.className(),
            new CustomColors(  cmap_grad(i),  Color::None ) );
    aBoard << fc;
  }
  aBoard.saveEPS("freemanChainFromImage.eps");
  return 0;
}
References DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::addColor(), DGtal::SetFromImage< TSet >::append(), DGtal::FreemanChain< TInteger >::className(), DGtal::Surfaces< TKSpace >::extractAllPointContours4C(), image(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::Color::None, and LibBoard::Board::saveEPS().