DGtal: freemanChainDisplay.cpp File Reference
freemanChainDisplay.cpp File Reference
DGtal Examples
#include <iostream>
#include <fstream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/base/BasicTypes.h"
#include "DGtal/geometry/curves/FreemanChain.h"
#include "DGtal/io/readers/STBReader.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2010/12/01
An example of FreemanChain display with background source image.
This file is part of the DGtal library.
Definition in file freemanChainDisplay.cpp.
Function Documentation
main()
int main (void)
Definition at line 51 of file freemanChainDisplay.cpp.
{
  typedef SpaceND<2> Space2;
  typedef HyperRectDomain<Space2> TDomain;
  //Default image selector = STLVector
  typedef ImageSelector<TDomain, unsigned char>::Type Image;
  // Creating FreemanChain from file
  std::string freemanChainFilename = examplesPath + "samples/contourS.fc";
  fstream fst;
  fst.open (freemanChainFilename.c_str(), ios::in);
  FreemanChain<Space::Integer> fc(fst);
  fst.close();
  // Importing image with MagickReader
  STBReader<Image> reader;
  std::string filenameImage = examplesPath + "samples/contourS.png";
  Image img = reader.import( filenameImage );
  Point ptInf = img.domain().lowerBound();
  Point ptSup = img.domain().upperBound();
  unsigned int width = abs(ptSup[0]-ptInf[0]+1);
  unsigned int height = abs(ptSup[1]-ptInf[1]+1);
  // Draw the freemanchain and the contour
  Board2D dgBoard;
  dgBoard.drawImage(filenameImage, 0,height-1, width, height );
  dgBoard << fc;
  dgBoard.saveEPS("freemanChainDisplay.eps");
  dgBoard.saveSVG("freemanChainDisplay.svg");
  dgBoard.saveFIG("freemanChainDisplay.fig");
  return 0;
}
References DGtal::Image< TImageContainer >::domain(), LibBoard::Board::drawImage(), DGtal::STBReader< TImageContainer, TFunctor >::import(), DGtal::HyperRectDomain< TSpace >::lowerBound(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), and DGtal::HyperRectDomain< TSpace >::upperBound().