DGtal: greedy-plane-segmentation-ex2.cpp File Reference
greedy-plane-segmentation-ex2.cpp File Reference
DGtal Examples
#include <iostream>
#include <vector>
#include <set>
#include <map>
#include <queue>
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/viewers/PolyscopeViewer.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/DigitalSetBoundary.h"
#include "DGtal/graph/BreadthFirstVisitor.h"
#include "DGtal/geometry/surfaces/COBANaivePlaneComputer.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
Data Structures
struct SegmentedPlane
struct VertexSize
Typedefs
typedef DGtal::int64_t InternalInteger
typedef COBANaivePlaneComputer< Z3, InternalInteger > NaivePlaneComputer
typedef DigitalSetBoundary< KSpace, DigitalSet > MyDigitalSurfaceContainer
typedef DigitalSurface< MyDigitalSurfaceContainer > MyDigitalSurface
typedef MyDigitalSurface::ConstIterator ConstIterator
typedef MyDigitalSurface::Vertex Vertex
typedef MyDigitalSurface::SurfelSet SurfelSet
typedef SurfelSet::iterator SurfelSetIterator
typedef BreadthFirstVisitor< MyDigitalSurface > Visitor
Functions
bool operator< (const VertexSize &vs1, const VertexSize &vs2)
int main ()
[greedy-plane-segmentation-ex2-typedefs]
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/10/01
An example file named greedy-plane-segmentation-ex2.
This file is part of the DGtal library.
Definition in file greedy-plane-segmentation-ex2.cpp.
Typedef Documentation
ConstIterator
typedef MyDigitalSurface::ConstIterator ConstIterator
Examples
arithmetic/convergents-biginteger.cpp, arithmetic/convergents.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, geometry/curves/estimation/exampleLMST3DBy2D.cpp, geometry/curves/exampleArithmeticalDSSComputer.cpp, geometry/curves/exampleNaive3DDSSComputer.cpp, geometry/curves/greedyAlphaThickDecomposition.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, io/viewers/viewer3D-7-stdplane.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 90 of file greedy-plane-segmentation-ex2.cpp.
InternalInteger
typedef DGtal::int64_t InternalInteger
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, and geometry/surfaces/greedy-plane-segmentation.cpp.
Definition at line 84 of file greedy-plane-segmentation-ex2.cpp.
MyDigitalSurface
typedef DigitalSurface<MyDigitalSurfaceContainer> MyDigitalSurface
Examples
dec/exampleHeatLaplace.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, graph/volDistanceTraversal.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/digitalSurfaceSlice.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volToOFF.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 89 of file greedy-plane-segmentation-ex2.cpp.
MyDigitalSurfaceContainer
typedef DigitalSetBoundary<KSpace,DigitalSet> MyDigitalSurfaceContainer
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, graph/volDistanceTraversal.cpp, and topology/volBreadthFirstTraversal.cpp.
Definition at line 88 of file greedy-plane-segmentation-ex2.cpp.
NaivePlaneComputer
typedef COBANaivePlaneComputer<Z3,InternalInteger> NaivePlaneComputer
Examples
examples/tutorial-examples/polyhedralizer.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 85 of file greedy-plane-segmentation-ex2.cpp.
SurfelSet
typedef MyDigitalSurface::SurfelSet SurfelSet
Examples
dec/exampleHeatLaplace.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/digitalSurfaceSlice.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volMarchingCubes.cpp, and topology/volToOFF.cpp.
Definition at line 92 of file greedy-plane-segmentation-ex2.cpp.
SurfelSetIterator
typedef SurfelSet::iterator SurfelSetIterator
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, and geometry/surfaces/greedy-plane-segmentation.cpp.
Definition at line 93 of file greedy-plane-segmentation-ex2.cpp.
Vertex
typedef MyDigitalSurface::Vertex Vertex
Definition at line 91 of file greedy-plane-segmentation-ex2.cpp.
Visitor
typedef BreadthFirstVisitor<MyDigitalSurface> Visitor
Examples
examples/tutorial-examples/polyhedralizer.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 94 of file greedy-plane-segmentation-ex2.cpp.
Function Documentation
main()
int main (void)
[greedy-plane-segmentation-ex2-typedefs]
[greedy-plane-segmentation-ex2-parseCommandLine]
[greedy-plane-segmentation-ex2-parseCommandLine]
[greedy-plane-segmentation-ex2-loadVolume]
[greedy-plane-segmentation-ex2-loadVolume]
[greedy-plane-segmentation-ex2-makeSurface]
[greedy-plane-segmentation-ex2-makeSurface]
[greedy-plane-segmentation-ex2-segment]
[greedy-plane-segmentation-ex2-segment]
[greedy-plane-segmentation-ex2-visualization]
[greedy-plane-segmentation-ex2-visualization]
[greedy-plane-segmentation-ex2-freeMemory]
[greedy-plane-segmentation-ex2-freeMemory]
Definition at line 120 of file greedy-plane-segmentation-ex2.cpp.
{
   trace.info() << "Segments the surface at given threshold within given volume into digital planes of rational width num/den." << std::endl;
  // Setting default options: ----------------------------------------------
  // input file used:
   string inputFilename =   examplesPath + "samples/Al.100.vol" ;
    trace.info() << "input file used " << inputFilename << std::endl;
  // parameter threshold
    unsigned int threshold = 0;
    trace.info() << "the value that defines the isosurface in the image (an integer between 0 and 255)= " << threshold<< std::endl;
   // parameter widthNum
   unsigned int widthNum = 1;
   trace.info() << "the numerator of the rational width (a non-null integer) =" << widthNum<< std::endl;
   // parameter widthDen
   unsigned int widthDen = 1;
   trace.info() << "the denominator of the rational width (a non-null integer)= " << widthDen<< std::endl;
  typedef ImageSelector < Domain, int>::Type Image;
  Image image = VolReader<Image>::importVol(inputFilename);
  DigitalSet set3d (image.domain());
  SetFromImage<DigitalSet>::append<Image>(set3d, image, threshold,255);
  trace.beginBlock( "Set up digital surface." );
  // We initializes the cellular grid space used for defining the
  // digital surface.
  KSpace ks;
  bool ok = ks.init( set3d.domain().lowerBound(),
                     set3d.domain().upperBound(), true );
  if ( ! ok ) std::cerr << "[KSpace.init] Failed." << std::endl;
  SurfelAdjacency<KSpace::dimension> surfAdj( true ); // interior in all directions.
  MyDigitalSurfaceContainer* ptrSurfContainer =
    new MyDigitalSurfaceContainer( ks, set3d, surfAdj );
  MyDigitalSurface digSurf( ptrSurfContainer ); // acquired
  trace.endBlock();
  Point p;
  Dimension axis;
  unsigned int j = 0;
  unsigned int nb = digSurf.size();
  // First pass to find biggest planes.
  trace.beginBlock( "1) Segmentation first pass. Computes all planes so as to sort vertices by the plane size." );
  std::map<Vertex,unsigned int> v2size;
  NaivePlaneComputer planeComputer;
  std::priority_queue<VertexSize> Q;
  for ( ConstIterator it = digSurf.begin(), itE= digSurf.end(); it != itE; ++it )
    {
      if ( ( (++j) % 50 == 0 ) || ( j == nb ) ) trace.progressBar( j, nb );
      Vertex v = *it;
      axis = ks.sOrthDir( v );
      planeComputer.init( axis, 500, widthNum, widthDen );
      // The visitor takes care of all the breadth-first traversal.
      Visitor visitor( digSurf, v );
      while ( ! visitor.finished() )
        {
          Visitor::Node node = visitor.current();
          v = node.first;
          axis = ks.sOrthDir( v );
          p = ks.sCoords( ks.sDirectIncident( v, axis ) );
          bool isExtended = planeComputer.extend( p );
          if ( isExtended )
            // surfel is in plane.
            visitor.expand();
          else // surfel is not in plane and should not be used in the visit.
            visitor.ignore();
        }
      Q.push( VertexSize( v, planeComputer.size() ) );
    }
  trace.endBlock();
  trace.beginBlock( "2) Segmentation second pass. Visits vertices from the one with biggest plane to the one with smallest plane." );
  std::set<Vertex> processedVertices;
  std::vector<SegmentedPlane*> segmentedPlanes;
  std::map<Vertex,SegmentedPlane*> v2plane;
  j = 0;
  while ( ! Q.empty() )
    {
      if ( ( (++j) % 50 == 0 ) || ( j == nb ) ) trace.progressBar( j, nb );
      Vertex v = Q.top().v;
      Q.pop();
      if ( processedVertices.find( v ) != processedVertices.end() ) // already in set
        continue; // process to next vertex
      SegmentedPlane* ptrSegment = new SegmentedPlane;
      segmentedPlanes.push_back( ptrSegment ); // to delete them afterwards.
      axis = ks.sOrthDir( v );
      ptrSegment->plane.init( axis, 500, widthNum, widthDen );
      // The visitor takes care of all the breadth-first traversal.
      Visitor visitor( digSurf, v );
      while ( ! visitor.finished() )
        {
          Visitor::Node node = visitor.current();
          v = node.first;
          if ( processedVertices.find( v ) == processedVertices.end() )
            { // Vertex is not in processedVertices
              axis = ks.sOrthDir( v );
              p = ks.sCoords( ks.sDirectIncident( v, axis ) );
              bool isExtended = ptrSegment->plane.extend( p );
              if ( isExtended )
                { // surfel is in plane.
                  processedVertices.insert( v );
                  v2plane[ v ] = ptrSegment;
                  visitor.expand();
                }
              else // surfel is not in plane and should not be used in the visit.
                visitor.ignore();
            }
          else // surfel is already in some plane.
            visitor.ignore();
        }
      // Assign random color for each plane.
      ptrSegment->color = Color( rand() % 256, rand() % 256, rand() % 256, 255 );
    }
  trace.endBlock();
  PolyscopeViewer<> viewer( ks );
  for ( std::map<Vertex,SegmentedPlane*>::const_iterator
          it = v2plane.begin(), itE = v2plane.end();
        it != itE; ++it )
    {
      viewer << it->second->color;
      viewer << ks.unsigns( it->first );
    }
  for ( std::vector<SegmentedPlane*>::iterator
          it = segmentedPlanes.begin(), itE = segmentedPlanes.end();
        it != itE; ++it )
    delete *it;
  segmentedPlanes.clear();
  v2plane.clear();
  viewer.show();
  return 0;
}
References DGtal::SetFromImage< TSet >::append(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::begin(), SegmentedPlane::color, DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::end(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::extend(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::ignore(), image(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::init(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), SegmentedPlane::plane, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirectIncident(), DGtal::PolyscopeViewer< Space, KSpace >::show(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::size(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::size(), DGtal::KhalimskySpaceND< dim, TInteger >::sOrthDir(), DGtal::trace, and DGtal::KhalimskySpaceND< dim, TInteger >::unsigns().
operator<()
bool operator< (const VertexSize & vs1, const VertexSize & vs2) inline
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp.
Definition at line 112 of file greedy-plane-segmentation-ex2.cpp.
{
  return vs1.size < vs2.size;
}
References VertexSize::size.