DGtal: LibBoard Namespace Reference
LibBoard Namespace Reference
Namespaces
namespace Fonts
Data Structures
class Board
Class for EPS, FIG or SVG drawings.
struct Path
A path, according to Postscript and SVG definition.
struct Point
Struct representing a 2D point.
struct Rect
Struct representing a rectangle on the plane.
struct ShapeList
A group of shapes.
struct Group
A group of shapes. A group is basically a ShapeList except that when rendered in either an SVG of a FIG file, it is a true compound element.
struct Shape
Abstract structure for a 2D shape.
struct Dot
A line between two points.
struct Line
A line between two points.
struct Arrow
A line between two points with an arrow at one extremity.
struct Polyline
A polygonal line described by a series of 2D points.
struct Rectangle
A rectangle.
struct Image
Used to draw image in figure.
struct Triangle
A triangle. Basically a Polyline with a convenient constructor.
struct QuadraticBezierCurve
A quadratic Bezier curve having 3 control points. NB. It is also a parabola arc.
struct GouraudTriangle
A triangle with shaded filling according to colors given for each vertex.
struct Ellipse
An ellipse.
struct Circle
A circle.
struct Arc
An arc.
struct Text
A piece of text.
class MessageStream
struct Transform
base class for transforms.
struct TransformEPS
Structure representing a scaling and translation suitable for an EPS output.
struct TransformFIG
Structure representing a scaling and translation suitable for an XFig output.
struct TransformSVG
Structure representing a scaling and translation suitable for an SVG output.
struct TransformCairo
Structure representing a scaling and translation suitable for an Cairo output.
struct TransformTikZ
Structure representing a scaling and translation suitable for an TikZ output.
Functions
Point operator+ (const Point &a, const Point &b)
Point operator- (const Point &a, const Point &b)
double operator* (const Point &a, const Point &b)
Point operator* (const Point &p, double s)
Point operator* (double s, const Point &p)
Point operator/ (const Point &p, double s)
bool operator== (const Point &a, const Point &b)
bool operator!= (const Point &a, const Point &b)
Rect operator|| (const Rect &rectA, const Rect &rectB)
Rect operator&& (const Rect &rectA, const Rect &rectB)
bool shapeGreaterDepth (const Shape *s1, const Shape *s2)
void secured_strncpy (char *dst, const char *src, size_t count)
void secured_ctime (char *str, const time_t *t, size_t count)
Variables
const char * PSFontNames []
const char * XFigPostscriptFontnames []
MessageStream error
MessageStream warning
MessageStream notice
Function Documentation
operator!=()
bool LibBoard::operator!= (const Point & a, const Point & b) inline
Definition at line 184 of file Point.h.
{
  return ( a.x != b.x ) || ( a.y != b.y ) ;
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator&&()
Rect LibBoard::operator&& (const Rect & rectA, const Rect & rectB)
Computes the intersection of two bounding boxes.
Parameters
rectA A first rectangle.
rectB A second rectangle.
Returns
The intersecting rectangle of two bounding boxes.
Definition at line 37 of file Rect.cpp.
{
  Rect rect;
  rect.top = ( rectA.top < rectB.top ) ? rectA.top : rectB.top;
  rect.left = (rectA.left > rectB.left) ? rectA.left : rectB.left;
  if ( rectA.left + rectA.width < rectB.left + rectB.width )
    rect.width = rectA.left + rectA.width - rect.left;
  else
    rect.width = rectB.left + rectB.width - rect.left;
  if ( rectA.top - rectA.height > rectB.top - rectB.height )
    rect.height = rect.top - ( rectA.top - rectA.height );
  else
    rect.height = rect.top - ( rectB.top - rectB.height );
  if ( rect.height < 0 ) rect.height = 0;
  if ( rect.width < 0 ) rect.width = 0;
  return rect;
}
References LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
operator*() [1/3]
double LibBoard::operator* (const Point & a, const Point & b) inline
Definition at line 122 of file Point.h.
{
  return a.x * b.x + a.y * b.y;
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator*() [2/3]
Point LibBoard::operator* (const Point & p, double s) inline
Definition at line 128 of file Point.h.
{
  return Point( p.x * s, p.y * s );
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator*() [3/3]
Point LibBoard::operator* (double s, const Point & p) inline
Definition at line 134 of file Point.h.
{
  return Point( s * p.x, s * p.y );
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator+()
Point LibBoard::operator+ (const Point & a, const Point & b) inline
Definition at line 110 of file Point.h.
{
  return Point( a.x + b.x, a.y + b.y );
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator-()
Point LibBoard::operator- (const Point & a, const Point & b) inline
Definition at line 116 of file Point.h.
{
  return Point( a.x - b.x, a.y - b.y );
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator/()
Point LibBoard::operator/ (const Point & p, double s) inline
Definition at line 140 of file Point.h.
{
  return Point( p.x / s, p.y / s );
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator==()
bool LibBoard::operator== (const Point & a, const Point & b) inline
Definition at line 178 of file Point.h.
{
  return ( a.x == b.x ) && ( a.y == b.y ) ;
}
References LibBoard::Point::x, and LibBoard::Point::y.
operator||()
Rect LibBoard::operator|| (const Rect & rectA, const Rect & rectB)
Computes the bounding box of two bounding boxes.
Parameters
rectA A first rectangle.
rectB A second rectangle.
Returns
The smallest rectangle that contains both rectA and rectB.
Definition at line 20 of file Rect.cpp.
{
  Rect rect;
  rect.top = ( rectA.top > rectB.top ) ? rectA.top : rectB.top;
  rect.left = (rectA.left < rectB.left) ? rectA.left : rectB.left;
  if ( rectA.left + rectA.width > rectB.left + rectB.width )
    rect.width = rectA.left + rectA.width - rect.left;
  else
    rect.width = rectB.left + rectB.width - rect.left;
  if ( rectA.top - rectA.height < rectB.top - rectB.height )
    rect.height = rect.top - ( rectA.top - rectA.height );
  else
    rect.height = rect.top - ( rectB.top - rectB.height );
  return rect;
}
References LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
secured_ctime()
void LibBoard::secured_ctime (char * str, const time_t * t, size_t count) inline
Referenced by LibBoard::Board::saveEPS().
secured_strncpy()
void LibBoard::secured_strncpy (char * dst, const char * src, size_t count) inline
shapeGreaterDepth()
bool LibBoard::shapeGreaterDepth (const Shape * s1, const Shape * s2)
Compares two shapes according to their depths.
Parameters
s1 A pointer to a first shape.
s2 A pointer to a second shape.
Returns
TODO
Definition at line 95 of file Shapes.cpp.
{
    return s1->depth() > s2->depth();
}
References LibBoard::Shape::depth().
Referenced by LibBoard::ShapeList::addShape(), LibBoard::ShapeList::flushCairo(), LibBoard::ShapeList::flushFIG(), LibBoard::ShapeList::flushPostscript(), LibBoard::ShapeList::flushSVG(), LibBoard::ShapeList::flushTikZ(), LibBoard::ShapeList::operator<<(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), and LibBoard::Board::saveTikZ().
Variable Documentation
error
LibBoard::MessageStream LibBoard::error extern
Referenced by testSegmentationLarger().
notice
LibBoard::MessageStream LibBoard::notice extern
PSFontNames
const char * LibBoard::PSFontNames
Definition at line 16 of file PSFonts.cpp.
{
  "Times-Roman",
  "Times-Italic",
  "Times-Bold",
  "Times-Bold-Italic",
  "AvantGarde-Book",
  "AvantGarde-Book-Oblique",
  "AvantGarde-Demi",
  "AvantGarde-Demi-Oblique",
  "Bookman-Light",
  "Bookman-Light-Italic",
  "Bookman-Demi",
  "Bookman-Demi-Italic",
  "Courier",
  "Courier-Oblique",
  "Courier-Bold",
  "Courier-Bold-Oblique",
  "Helvetica",
  "Helvetica-Oblique",
  "Helvetica-Bold",
  "Helvetica-Bold-Oblique",
  "Helvetica-Narrow",
  "Helvetica-Narrow-Oblique",
  "Helvetica-Narrow-Bold",
  "Helvetica-Narrow-Bold-Oblique",
  "New-Century-Schoolbook-Roman",
  "New-Century-Schoolbook-Italic",
  "New-Century-Schoolbook-Bold",
  "New-Century-Schoolbook-Bold-Italic",
  "Palatino-Roman",
  "Palatino-Italic",
  "Palatino-Bold",
  "Palatino-Bold-Italic",
  "Symbol",
  "Zapf-Chancery-Medium-Italic",
  "Zapf-Dingbats"
};
Referenced by LibBoard::Text::flushPostscript(), and LibBoard::Text::flushSVG().
warning
LibBoard::MessageStream LibBoard::warning extern
Referenced by LibBoard::ShapeList::dup(), and LibBoard::ShapeList::insert().
XFigPostscriptFontnames
const char* LibBoard::XFigPostscriptFontnames[] extern