DGtal: shapeGridCurveEstimator.cpp File Reference
shapeGridCurveEstimator.cpp File Reference
DGtal Examples
An example of generating a grid curve from a parametric shape and estimating its length.
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/curves/GridCurve.h"
#include "DGtal/geometry/curves/estimation/TrueGlobalEstimatorOnPoints.h"
#include "DGtal/geometry/curves/estimation/ParametricShapeArcLengthFunctor.h"
#include "DGtal/geometry/curves/estimation/DSSLengthEstimator.h"
#include "DGtal/io/boards/Board2D.h"
Functions
int main ()
Detailed Description
An example of generating a grid curve from a parametric shape and estimating its length.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr)
Date
2010/10/17
This file is part of the DGtal library.
Definition in file shapeGridCurveEstimator.cpp.
Function Documentation
main()
int main (void)
[shapeGridCurveEstimator-dig]
[shapeGridCurveEstimator-dig]
[shapeGridCurveEstimator-prepareTracking]
[shapeGridCurveEstimator-prepareTracking]
[shapeGridCurveEstimator-tracking]
[shapeGridCurveEstimator-tracking]
[shapeGridCurveEstimator-instantiation]
[shapeGridCurveEstimator-instantiation]
[shapeGridCurveEstimator-getRange]
[shapeGridCurveEstimator-getRange]
[shapeGridCurveEstimator-lengthEstimation]
[shapeGridCurveEstimator-lengthEstimation]
[shapeGridCurveEstimator-trueLengthEstimation]
[shapeGridCurveEstimator-trueLengthEstimation]
[shapeGridCurveEstimator-higher]
[shapeGridCurveEstimator-higher]
Definition at line 70 of file shapeGridCurveEstimator.cpp.
{
  //shape
  //implicit digitization of a shape of type Flower
  //into a digital space of type Space
  typedef Flower2D<Z2i::Space> Flower;
  Flower2D<Z2i::Space> flower(Z2i::Point(0,0), 20, 5, 5, 0);
  double h = 1;
  GaussDigitizer<Z2i::Space,Flower> dig;
  dig.attach( flower );
  dig.init( flower.getLowerBound()+Z2i::Vector(-1,-1),
            flower.getUpperBound()+Z2i::Vector(1,1), h );
  //Khalimsky space
  Z2i::KSpace ks;
  ks.init( dig.getLowerBound(), dig.getUpperBound(), true );
  //adjacency (4-connectivity)
  SurfelAdjacency<2> sAdj( true );
  //searching for one boundary element
  Z2i::SCell bel = Surfaces<Z2i::KSpace>::findABel( ks, dig, 1000 );
  //tracking
  std::vector<Z2i::Point> boundaryPoints;
  Surfaces<Z2i::KSpace>
    ::track2DBoundaryPoints( boundaryPoints, ks, sAdj, dig, bel );
  Z2i::Curve c;
  c.initFromPointsVector( boundaryPoints );
  DGtal::Board2D aBoard;
  aBoard << c;
  aBoard.saveEPS("DisplayGridCurve1.eps");
  //range of points
  typedef Z2i::Curve::PointsRange Range;
  Range r = c.getPointsRange();
  //length estimation
  DSSLengthEstimator< Range::ConstCirculator > DSSlength;
  double length1 = DSSlength.eval(r.c(), r.c(), h);
  trace.info() << "Length (h=" << h << "): " << length1 << std::endl;
  typedef ParametricShapeArcLengthFunctor< Flower > Length;
  TrueGlobalEstimatorOnPoints<
    Range::ConstCirculator,
    Flower,
    Length  >  trueLengthEstimator;
  trueLengthEstimator.attach(flower);
  // Note: Not equivalent to eval(r.c(), r.c(), h)
  double trueLength = trueLengthEstimator.eval();
  trace.info() << "ground truth: " << trueLength << std::endl;
  //implicit digitization at higher resolution
  h = 0.1;
  dig.init( flower.getLowerBound()+Z2i::Vector(-1,-1),
            flower.getUpperBound()+Z2i::Vector(1,1), h );
  //a greater domain is needed in the Khalimsky space
  ks.init( dig.getLowerBound(), dig.getUpperBound(), true );
  //searching for one boundary element
  bel = Surfaces<Z2i::KSpace>::findABel( ks, dig, 10000 );
  //tracking
  Surfaces<Z2i::KSpace>
    ::track2DBoundaryPoints( boundaryPoints, ks, sAdj, dig, bel );
  //reset grid curve and its points range
  c.initFromPointsVector( boundaryPoints );
  Range r2 = c.getPointsRange();
  //estimate length
  double length2 = DSSlength.eval(r2.c(), r2.c(), h);
  trace.info() << "Length (h=" << h << "): " << length2 << std::endl;
  aBoard.clear();
  aBoard << c;
  aBoard.saveEPS("DisplayGridCurve01.eps");
  return 0;
}
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::c(), LibBoard::Board::clear(), DGtal::DSSLengthEstimator< TConstIterator >::eval(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::Flower2D< TSpace >::getLowerBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::GridCurve< TKSpace >::getPointsRange(), DGtal::Flower2D< TSpace >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GridCurve< TKSpace >::initFromPointsVector(), LibBoard::Board::saveEPS(), and DGtal::trace.