DGtal: DGtal::HDF5Reader< TImageContainer, TFunctor > Struct Template Reference
DGtal::HDF5Reader< TImageContainer, TFunctor > Struct Template Reference
Aim: Import a HDF5 file.
#include <DGtal/io/readers/HDF5Reader.h>
Public Types
typedef TImageContainer ImageContainer
typedef TImageContainer OutputImage
typedef TImageContainer::Domain Domain
typedef TImageContainer::Domain::Vector Vector
typedef TImageContainer::Value Value
typedef TFunctor Functor
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TImageContainer >))
BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< TFunctor, unsigned char, Value >))
BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
Static Public Member Functions
static ImageContainer importHDF5 (const std::string &aFilename, const std::string &aDataset, const FunctorFunctor &aFunctor=FunctorFunctor(), bool topbotomOrder=true)
static ImageContainer importHDF5_3D (const std::string &aFilename, const std::string &aDataset, const FunctorFunctor &aFunctor=FunctorFunctor())
Detailed Description
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >>
struct DGtal::HDF5Reader< TImageContainer, TFunctor >
Aim: Import a HDF5 file.
Description of class 'HDF5Reader'
Template Parameters
TImageContainer the image container to use.
TFunctor the type of functor used in the import (by default set to functors::Cast< TImageContainer::Value>).
Definition at line 62 of file HDF5Reader.h.
Member Typedef Documentation
Domain
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TImageContainer::Domain DGtal::HDF5Reader< TImageContainer, TFunctor >::Domain
Definition at line 69 of file HDF5Reader.h.
Functor
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TFunctor DGtal::HDF5Reader< TImageContainer, TFunctor >::Functor
Definition at line 72 of file HDF5Reader.h.
ImageContainer
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::ImageContainer
Definition at line 67 of file HDF5Reader.h.
OutputImage
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::OutputImage
Definition at line 68 of file HDF5Reader.h.
Value
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TImageContainer::Value DGtal::HDF5Reader< TImageContainer, TFunctor >::Value
Definition at line 71 of file HDF5Reader.h.
Vector
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> typedef TImageContainer::Domain::Vector DGtal::HDF5Reader< TImageContainer, TFunctor >::Vector
Definition at line 70 of file HDF5Reader.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT() [1/2]
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TImageContainer >))
BOOST_CONCEPT_ASSERT() [2/2]
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_CONCEPT_ASSERT ((concepts::CUnaryFunctor< TFunctor, unsigned char, Value >))
BOOST_STATIC_ASSERT()
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
importHDF5()
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> ImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5 (const std::string & aFilename, const std::string & aDataset, const FunctorFunctor & aFunctor = FunctorFunctor(), bool topbotomOrder = true) static
Main method to import a HDF5 image file with 2D image dataset(s) (8-bit with palette and 24-bit truecolor with INTERLACE_PIXEL) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aDataset the dataset name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to functors::Cast < TImageContainer::Value >.
topbotomOrder if true, the point of coordinate (0,0) will be the bottom left corner image point (default) else the center of image coordinate will be the top left of the image (not usual).
Returns
an instance of the ImageContainer.
Referenced by DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithValueFunctor(), and testHDF5Reader().
importHDF5_3D()
template<typename TImageContainer, typename TFunctor = functors::Cast< typename TImageContainer::Value >> ImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5_3D (const std::string & aFilename, const std::string & aDataset, const FunctorFunctor & aFunctor = FunctorFunctor()) static
Main method to import a HDF5 image file with 3D UInt8 image dataset(s) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aDataset the dataset name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to functors::Cast < TImageContainer::Value >.
Returns
an instance of the ImageContainer.
Referenced by DGtal::GenericReader< TContainer, 3, TValue >::importWithValueFunctor(), and testHDF5_3DReader().
The documentation for this struct was generated from the following file:
HDF5Reader.h