DGtal: BenchInfo Struct Reference
BenchInfo Struct Reference
Public Member Functions
BenchInfo ()
Static Public Attributes
static std::vector< std::vector< Z3i::Point > > shapes
static std::vector< Z3i::Domain > domains
static std::vector< std::string > names
Detailed Description
Definition at line 20 of file benchmarkDigitalSetByOctree.cpp.
Constructor & Destructor Documentation
BenchInfo()
BenchInfo::BenchInfo () inline
Definition at line 26 of file benchmarkDigitalSetByOctree.cpp.
              {
    if (shapes.size() != 0) return;
    const auto polys = SH3::getPolynomialList();
    const double steps[]  = { 1.00, 0.50, 0.25 };
    const double noises[] = { 0.00, 0.10  };
    for (const auto& poly : polys) {
      for (const auto& step : steps) {
        for (const auto& noise : noises) {
          auto params = SH3::defaultParameters();
          params( "polynomial", poly.second )
                ( "gridstep", step)
                ( "noise", noise);
          auto ishape = SH3::makeImplicitShape3D(params);
          auto dshape = SH3::makeDigitizedImplicitShape3D(ishape, params);
          auto nshape = SH3::makeBinaryImage(dshape, params);
          const std::string name = poly.first + "_" + std::to_string(step) + "_" + std::to_string(noise);
          const auto domain = nshape->domain();
          names.push_back(name);
          domains.push_back(nshape->domain());
          shapes.push_back({});
          for (auto it = domain.begin(); it != domain.end(); ++it) {
            if (nshape->operator()(*it) != 0) {
              shapes.back().push_back(*it);
            }
          }
        }
      }
    }
    std::cout << "Shapes: " << std::endl;
    for (const auto& n : names) {
      std::cout << "\t -" << n << std::endl;
    }
  }
References DGtal::Shortcuts< Z3i::KSpace >::defaultParameters(), domain, domains, DGtal::Shortcuts< Z3i::KSpace >::getPolynomialList(), DGtal::Shortcuts< Z3i::KSpace >::makeBinaryImage(), DGtal::Shortcuts< Z3i::KSpace >::makeDigitizedImplicitShape3D(), DGtal::Shortcuts< Z3i::KSpace >::makeImplicitShape3D(), names, and shapes.
Field Documentation
domains
std::vector<Z3i::Domain> BenchInfo::domains inline static
Definition at line 23 of file benchmarkDigitalSetByOctree.cpp.
Referenced by BenchInfo().
names
std::vector<std::string> BenchInfo::names inline static
Definition at line 24 of file benchmarkDigitalSetByOctree.cpp.
Referenced by BenchInfo().
shapes
std::vector<std::vector<Z3i::Point> > BenchInfo::shapes inline static
Definition at line 22 of file benchmarkDigitalSetByOctree.cpp.
Referenced by BenchInfo().
The documentation for this struct was generated from the following file:
benchmarkDigitalSetByOctree.cpp