DGtal: LibBoard::Rectangle Struct Reference
LibBoard::Rectangle Struct Reference
A rectangle.
#include <Board/Shapes.h>
Public Member Functions
Rectangle (double x, double y, double width, double height, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Rectangle (const Rect &rect, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
double x () const
double y () const
double width ()
double height ()
Point topLeft ()
Point topRight ()
Point bottomLeft ()
Point bottomRight ()
Rectangle rotated (double angle, const Point &center) const
Rectangle rotated (double angle) const
Rectangle translated (double dx, double dy) const
Rectangle scaled (double sx, double sy) const
Rectangle scaled (double s) const
void scaleAll (double s)
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rectangle * clone () const
Public Member Functions inherited from LibBoard::Polyline
Polyline (const std::vector< Point > &points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (const Path &path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Point center () const
Polyline & operator<< (const Point &p)
Point & operator[] (const unsigned int n)
Polyline & rotate (double angle, const Point &center)
Polyline rotated (double angle, const Point &center) const
Polyline & rotate (double angle)
Polyline rotated (double angle) const
Polyline & translate (double dx, double dy)
Polyline translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Polyline scaled (double sx, double sy) const
Polyline scaled (double s) const
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
Rect boundingBox () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
bool _isRectangle
Protected Attributes inherited from LibBoard::Polyline
Path _path
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A rectangle.
The rectangle structure.
Definition at line 912 of file Board/Shapes.h.
Constructor & Destructor Documentation
Rectangle() [1/2]
LibBoard::Rectangle::Rectangle (double x, double y, double width, double height, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
References LibBoard::Shape::ButtCap, LibBoard::Shape::depth(), LibBoard::Shape::fillColor(), height(), LibBoard::Shape::MiterJoin, LibBoard::Shape::penColor(), LibBoard::Shape::SolidStyle, width(), x(), and y().
Referenced by clone(), rotated(), rotated(), scaled(), scaled(), and translated().
Rectangle() [2/2]
LibBoard::Rectangle::Rectangle (const Rect & rect, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
References LibBoard::Shape::ButtCap, LibBoard::Shape::depth(), LibBoard::Shape::fillColor(), LibBoard::Shape::MiterJoin, LibBoard::Shape::penColor(), and LibBoard::Shape::SolidStyle.
Member Function Documentation
bottomLeft()
Point LibBoard::Rectangle::bottomLeft () inline
Definition at line 943 of file Board/Shapes.h.
{ return Point(_path[3].x, _path[3].y); }
References LibBoard::Polyline::_path, x(), and y().
bottomRight()
Point LibBoard::Rectangle::bottomRight () inline
Definition at line 944 of file Board/Shapes.h.
{ return Point(_path[2].x, _path[2].y); }
References LibBoard::Polyline::_path, x(), and y().
clone()
Rectangle * LibBoard::Rectangle::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Reimplemented from LibBoard::Polyline.
Definition at line 1921 of file Shapes.cpp.
                       {
    return new Rectangle(*this);
}
References Rectangle().
flushCairo()
void LibBoard::Rectangle::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2010 of file Shapes.cpp.
{
    {
        double x1 = _path[1].x - _path[0].x;
        double y1 = _path[1].y - _path[0].y;
        double x2 = _path[3].x - _path[0].x;
        double y2 = _path[3].y - _path[0].y;
        if ( fabs(x1*x2 + y1*y2) > 0.01  ) {
            Polyline::flushCairo( cr, transform );
            return;
        }
    }
    cairo_save (cr);
      cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
      if ( _path[0].y == _path[1].y )
  cairo_rectangle (cr, transform.mapX( _path[0].x ), transform.mapY( _path[0].y ), transform.scale( _path[1].x - _path[0].x ), transform.scale( _path[0].y - _path[3].y ));
      else
      {
  Point v = _path[1] - _path[0];
        v /= v.norm();
        double angle = ( _path[1].y > _path[0].y ) ? acos( v * Point(1,0) ) : -acos( v * Point( 1, 0 ) );
  // tr
  cairo_translate (cr, transform.mapX( _path[0].x )+transform.scale( _path[1].x - _path[0].x )/2., transform.mapY( _path[0].y )+transform.scale( _path[0].y - _path[3].y )/2.);
  cairo_rotate (cr, angle);
  // tr
  cairo_rectangle (cr, -transform.scale( _path[1].x - _path[0].x )/2., -transform.scale( _path[0].y - _path[3].y )/2., transform.scale( (_path[1] - _path[0]).norm() ), transform.scale( (_path[0] - _path[3]).norm() ));
      }
      if ( filled() )
      {
  if ( _penColor != DGtal::Color::None )
    cairo_fill_preserve (cr);
  else
    cairo_fill (cr);
      }
      //
      if ( _penColor != DGtal::Color::None )
      {
  cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
  cairo_set_line_width (cr, _lineWidth);
  cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
  cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
  setCairoDashStyle (cr, _lineStyle);
  cairo_stroke (cr);
      }
    cairo_restore (cr);
}
References LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Polyline::_path, LibBoard::Shape::_penColor, angle(), LibBoard::Shape::filled(), LibBoard::Polyline::flushCairo(), DGtal::Color::None, LibBoard::Point::norm(), LibBoard::Shape::setCairoDashStyle(), and y().
Referenced by LibBoard::Board::saveCairo().
flushFIG()
void LibBoard::Rectangle::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Reimplemented from LibBoard::Polyline.
Definition at line 1926 of file Shapes.cpp.
{
  if ( _path[0].y != _path[1].y ) {
        Polyline::flushFIG( stream, transform, colormap );
        return;
    }
    if ( _path[0].x != _path[3].x ) {
        Polyline::flushFIG( stream, transform, colormap );
        return;
    }
    {
        double x1 = _path[1].x - _path[0].x;
        double y1 = _path[1].y - _path[0].y;
        double x2 = _path[3].x - _path[0].x;
        double y2 = _path[3].y - _path[0].y;
        if ( fabs(x1*x2 + y1*y2) > 0.01 ) {
            Polyline::flushFIG( stream, transform, colormap );
            return;
        }
    }
    stream << "2 2 " << _lineStyle << " ";
    // Thickness
    stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
    // Pen color
    stream << colormap[ _penColor ] << " ";
    // Fill color
    stream << colormap[ _fillColor ] << " ";
    // Depth
    stream << transform.mapDepth( _depth ) << " ";
    // Pen style
    stream <<  "-1 ";
    // Area fill, style val, join style, cap style, radius, f_arrow, b_arrow, number of points
    if ( filled() )
        stream << "20 " << (_lineStyle?"4.000 ":"0.000 ") << _lineJoin << " " << _lineCap << " -1 0 0 5\n";
    else
        stream << "-1 " << (_lineStyle?"4.000 ":"0.000 ") << _lineJoin << " " << _lineCap << " -1 0 0 5\n";
    stream << "         ";
    _path.flushFIG( stream, transform );
    stream << std::endl;
}
References LibBoard::Shape::_depth, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Polyline::_path, LibBoard::Shape::_penColor, LibBoard::Shape::filled(), LibBoard::Polyline::flushFIG(), x(), and y().
Referenced by LibBoard::Board::saveFIG().
flushSVG()
void LibBoard::Rectangle::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 1971 of file Shapes.cpp.
{
    {
        double x1 = _path[1].x - _path[0].x;
        double y1 = _path[1].y - _path[0].y;
        double x2 = _path[3].x - _path[0].x;
        double y2 = _path[3].y - _path[0].y;
        if ( fabs(x1*x2 + y1*y2) > 0.01  ) {
            Polyline::flushSVG( stream, transform );
            return;
        }
    }
    if ( _path[0].y == _path[1].y ) {
        stream << "<rect x=\"" << transform.mapX( _path[0].x ) << '"'
        << " y=\"" << transform.mapY( _path[0].y )  << '"'
        << " width=\"" << transform.scale( _path[1].x - _path[0].x ) << '"'
        << " height=\"" << transform.scale( _path[0].y - _path[3].y ) << '"'
        << svgProperties( transform )
        << " />" << std::endl;
    } else {
        Point v = _path[1] - _path[0];
        v /= v.norm();
        double angle = ( _path[1].y > _path[0].y ) ? acos( v * Point(1,0) ) : -acos( v * Point( 1, 0 ) );
        angle = ( angle * 180 ) / M_PI;
        stream << "<rect x=\"" << transform.mapX( _path[0].x ) << '"'
        << " y=\"" << transform.mapY( _path[0].y )  << '"'
        << " width=\"" << transform.scale( (_path[1] - _path[0]).norm() ) << '"'
        << " height=\"" << transform.scale( (_path[0] - _path[3]).norm() ) << '"'
        << svgProperties( transform ) << ' '
        << " transform=\"rotate(" << -angle << ", "
        << transform.mapX( _path[0].x ) << ", " << transform.mapY( _path[0].y ) << ") \" "
        << " />" << std::endl;
    }
}
References LibBoard::Polyline::_path, angle(), LibBoard::Polyline::flushSVG(), LibBoard::Point::norm(), LibBoard::Shape::svgProperties(), x(), and y().
Referenced by LibBoard::Board::saveSVG().
flushTikZ()
void LibBoard::Rectangle::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2071 of file Shapes.cpp.
{
    Polyline::flushTikZ( stream, transform );
    return;
    stream << "\\path[" << tikzProperties(transform) << "] ("
      << _path[0].x << ',' << _path[0].y << ')'
      << " rectangle (" << _path[1].x << ',' << _path[3].y << "); ";
}
References LibBoard::Polyline::_path, LibBoard::Polyline::flushTikZ(), and LibBoard::Shape::tikzProperties().
Referenced by LibBoard::Board::saveTikZ().
height()
double LibBoard::Rectangle::height () inline
Definition at line 940 of file Board/Shapes.h.
{ return (_path[0] - _path[3]).norm(); }
References LibBoard::Polyline::_path.
Referenced by LibBoard::Image::Image(), and Rectangle().
name()
const std::string & LibBoard::Rectangle::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Polyline.
Definition at line 1879 of file Shapes.cpp.
{
    return _name;
}
References _name.
rotated() [1/2]
Rectangle LibBoard::Rectangle::rotated (double angle) const
Returns a copy of the arrow, rotated around its center.
Parameters
angle The angle of rotation.
Returns
A copy of the lines, rotated around its center by the given angle.
Definition at line 1891 of file Shapes.cpp.
{
    return static_cast<Rectangle &>( Rectangle(*this).rotate( angle, center() ) );
}
References angle(), LibBoard::Polyline::center(), and Rectangle().
rotated() [2/2]
Rectangle LibBoard::Rectangle::rotated (double angle, const Point & center) const
Returns a copy of the arrow, rotated around a given rotation center.
Parameters
angle The rotation angle.
center The center of rotation.
Returns
The rotated copy of the line.
Definition at line 1885 of file Shapes.cpp.
{
    return static_cast<Rectangle &>( Rectangle(*this).rotate( angle, rotCenter ) );
}
References angle(), and Rectangle().
scaleAll()
void LibBoard::Rectangle::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Reimplemented from LibBoard::Polyline.
Definition at line 1915 of file Shapes.cpp.
{
    _path.scaleAll( s );
}
References LibBoard::Polyline::_path.
scaled() [1/2]
Rectangle LibBoard::Rectangle::scaled (double s) const
Definition at line 1909 of file Shapes.cpp.
{
    return static_cast<Rectangle &>( Rectangle(*this).scale( s, s ) );
}
References Rectangle().
scaled() [2/2]
Rectangle LibBoard::Rectangle::scaled (double sx, double sy) const
Returns a scaled copy of the arrow.
Parameters
sx Scale factor along the x axis.
sy Scale factor along the y axis.
Returns
A scaled copy of the arrow.
Definition at line 1903 of file Shapes.cpp.
{
    return static_cast<Rectangle &>( Rectangle(*this).scale( sx, sy ) );
}
References Rectangle().
topLeft()
Point LibBoard::Rectangle::topLeft () inline
Definition at line 941 of file Board/Shapes.h.
{ return Point(_path[0].x, _path[0].y); }
References LibBoard::Polyline::_path, x(), and y().
topRight()
Point LibBoard::Rectangle::topRight () inline
Definition at line 942 of file Board/Shapes.h.
{ return Point(_path[1].x, _path[1].y); }
References LibBoard::Polyline::_path, x(), and y().
translated()
Rectangle LibBoard::Rectangle::translated (double dx, double dy) const
Returns a translated copy of the arrow.
Parameters
dx The shift along the x axis.
dy The shift along the y axis.
Returns
A translated copy of the line.
Definition at line 1897 of file Shapes.cpp.
{
    return static_cast<Rectangle &>( Rectangle(*this).translate( dx, dy ) );
}
References Rectangle().
width()
double LibBoard::Rectangle::width () inline
Definition at line 939 of file Board/Shapes.h.
{ return (_path[1] - _path[0]).norm(); }
References LibBoard::Polyline::_path.
Referenced by LibBoard::Image::Image(), and Rectangle().
x()
double LibBoard::Rectangle::x () const inline
Definition at line 937 of file Board/Shapes.h.
{ return _path[0].x; }
References LibBoard::Polyline::_path.
Referenced by bottomLeft(), bottomRight(), flushFIG(), LibBoard::Image::flushSVG(), flushSVG(), LibBoard::Image::flushTikZ(), Rectangle(), topLeft(), and topRight().
y()
double LibBoard::Rectangle::y () const inline
Definition at line 938 of file Board/Shapes.h.
{ return _path[0].y; }
References LibBoard::Polyline::_path.
Referenced by bottomLeft(), bottomRight(), flushCairo(), flushFIG(), LibBoard::Image::flushSVG(), flushSVG(), LibBoard::Image::flushTikZ(), Rectangle(), topLeft(), and topRight().
Field Documentation
_isRectangle
bool LibBoard::Rectangle::_isRectangle protected
Definition at line 1017 of file Board/Shapes.h.
_name
const std::string LibBoard::Rectangle::_name static private
The generic name of the shape.
Definition at line 1014 of file Board/Shapes.h.
Referenced by name().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp