DGtal: DGtal::GenericReader< TContainer, 3, DGtal::uint32_t > Struct Template Reference
DGtal::GenericReader< TContainer, 3, DGtal::uint32_t > Struct Template Reference
#include <DGtal/io/readers/GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename, unsigned int x=0, unsigned int y=0, unsigned int z=0)
template<typename TFunctor>
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor, unsigned int x=0, unsigned int y=0, unsigned int z=0)
static TContainer importWithColorFunctor (const std::string &filename, const TFunctor &aFunctor, std::vector< unsigned int > dimSpace=std::vector< unsigned int >())
Detailed Description
template<typename TContainer>
struct DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >
GenericReader Template partial specialisation for volume images with 32 bits values
Definition at line 301 of file GenericReader.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TContainer> DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
import()
template<typename TContainer> TContainer DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::import (const std::string & filename, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) static
Import a volume image file. For the special format of raw image, the default parameter x,y, z need to be updated according to the dimension if the image.
Parameters
filename the image filename to be imported.
x the size in the x direction.
y the size in the y direction.
z the size in the z direction.
importWithColorFunctor()
TContainer DGtal::GenericReader< TContainer, Tdim, DGtal::uint32_t >::importWithColorFunctor (const std::string & filename, const TFunctor & aFunctor, std::vector< unsigned int > dimSpace = std::vector<unsigned int>()) inline static
Import a volume nd image file by specifying a value functor.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TValue , TContainer::Value >)
Parameters
dimSpace a vector containing the n dimensional image size.
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
Definition at line 174 of file GenericReader.h.
    {
      BOOST_CONCEPT_ASSERT(
      (concepts::CUnaryFunctor<TFunctor, DGtal::Color,
                               typename TContainer::Value>));
      DGtal::IOException dgtalio;
      const std::string extension =
      filename.substr( filename.find_last_of( "." ) + 1 );
      if ( extension == "raw" )
      {
        for ( unsigned int i = 0; i < dimSpace.size(); i++ )
          ASSERT( dimSpace[ i ] != 0 );
        typename TContainer::Point const pt;
        for ( unsigned int i = 0; i < dimSpace.size(); i++ )
          pt[ i ]            = dimSpace[ i ];
        return RawReader<TContainer, TFunctor>::template importRaw<
        DGtal::Color>( filename, pt, aFunctor );
      }
      trace.error() << "Extension " << extension
                    << " not yet implemented in DGtal GenericReader."
                    << std::endl;
      throw dgtalio;
    }
importWithValueFunctor()
template<typename TContainer> template<typename TFunctor> TContainer DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) inline static
Import an image file by specifying a value functor (used for gray scale image format: vol, longvol, pgm3D, raw).
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, unsigned char , TContainer::Value >).
Parameters
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
x specify the x image size to be used with raw format.
y specify the y image size to be used with raw format.
z specify the " image size to be used with raw format.
Definition at line 334 of file GenericReader.h.
      {
        BOOST_CONCEPT_ASSERT((  concepts::CUnaryFunctor<TFunctor, DGtal::uint32_t, typename TContainer::Value > )) ;
        DGtal::IOException dgtalio;
        const std::string extension = filename.substr( filename.find_last_of(".") + 1 );
        if ( extension == "longvol" )
          {
            return LongvolReader<TContainer, TFunctor>::importLongvol( filename, aFunctor  );
          }
        else if ( extension == "raw" )
          {
            ASSERT( x != 0 && y != 0 && z != 0 );
            typename TContainer::Point const pt (x, y, z);
            return RawReader< TContainer, TFunctor >::importRaw32 ( filename, pt, aFunctor  );
          }
#ifdef  DGTAL_WITH_ITK
        if ( extension == "dcm" )
          {
            return DicomReader<TContainer, TFunctor>::importDicom(filename, aFunctor);
          }
        else if ( extension == "mha" || extension == "mhd" )
          {
            return ITKReader<TContainer>::importITK( filename, aFunctor );
          }
#endif
        trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
        throw dgtalio;
      }
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::DicomReader< TImageContainer, TFunctor >::importDicom(), DGtal::ITKReader< TImage >::importITK(), DGtal::LongvolReader< TImageContainer, TFunctor >::importLongvol(), DGtal::RawReader< TImageContainer, TFunctor >::importRaw32(), and DGtal::trace.
The documentation for this struct was generated from the following file:
GenericReader.h