DGtal: DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node Struct Reference
DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node Struct Reference
#include <DGtal/graph/DistanceBreadthFirstVisitor.h>
Public Types
typedef std::pair< Vertex, Scalar > Base
Public Member Functions
Node ()=default
Node (const Vertex &v, Scalar d)
bool operator< (const Node &other) const
bool operator<= (const Node &other) const
bool operator== (const Node &other) const
bool operator!= (const Node &other) const
Detailed Description
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet>
struct DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node
The type storing the vertex and its distance. It is also a model of boost::LessComparable, boost::EqualityComparable.
Definition at line 229 of file DistanceBreadthFirstVisitor.h.
Member Typedef Documentation
Base
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> typedef std::pair< Vertex, Scalar > DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::Base
Definition at line 231 of file DistanceBreadthFirstVisitor.h.
Constructor & Destructor Documentation
Node() [1/2]
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::Node () inline default
Referenced by operator!=(), operator<(), operator<=(), and operator==().
Node() [2/2]
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::Node (const Vertex & v, Scalar d) inline
Definition at line 236 of file DistanceBreadthFirstVisitor.h.
        : std::pair< Vertex, Scalar >( v, d )
      {}
Member Function Documentation
operator!=()
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> bool DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::operator!= (const Node & other) const inline
Definition at line 251 of file DistanceBreadthFirstVisitor.h.
      {
        return other.second != second;
      }
References Node().
operator<()
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> bool DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::operator< (const Node & other) const inline
Definition at line 239 of file DistanceBreadthFirstVisitor.h.
      {
        return other.second < second;
      }
References Node().
operator<=()
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> bool DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::operator<= (const Node & other) const inline
Definition at line 243 of file DistanceBreadthFirstVisitor.h.
      {
        return other.second <= second;
      }
References Node().
operator==()
template<typename TGraph, typename TVertexFunctor, typename TMarkSet = typename TGraph::VertexSet> bool DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::Node::operator== (const Node & other) const inline
Definition at line 247 of file DistanceBreadthFirstVisitor.h.
      {
        return other.second == second;
      }
References Node().
The documentation for this struct was generated from the following file:
DistanceBreadthFirstVisitor.h