DGtal: DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge Struct Reference
DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge Struct Reference
#include <DGtal/topology/DigitalSurface.h>
Public Member Functions
Edge (const Vertex &v1, const Vertex &v2)
bool operator== (const Edge &other) const
bool operator< (const Edge &other) const
Data Fields
Vertex vertices [2]
The two vertices.
Detailed Description
template<typename TDigitalSurfaceContainer>
struct DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge
An edge is a unordered pair of vertices. To make comparisons easier, the smallest vertex is stored before the greatest vertex. Note that loops are legal.
Definition at line 192 of file DigitalSurface.h.
Constructor & Destructor Documentation
Edge()
template<typename TDigitalSurfaceContainer> DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge::Edge (const Vertex & v1, const Vertex & v2) inline
Constructor from vertices.
Parameters
v1 the first vertex.
v2 the second vertex.
Definition at line 200 of file DigitalSurface.h.
      {
        if ( v1 <= v2 )
          {
            vertices[ 0 ] = v1;
            vertices[ 1 ] = v2;
          }
        else
          {
            vertices[ 0 ] = v2;
            vertices[ 1 ] = v1;
          }
      }
References vertices.
Referenced by operator<(), and operator==().
Member Function Documentation
operator<()
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge::operator< (const Edge & other) const inline
Definition at line 218 of file DigitalSurface.h.
      {
        return ( vertices[ 0 ] < other.vertices[ 0 ] )
          || ( ( vertices[ 0 ] == other.vertices[ 0 ] )
               && ( vertices[ 1 ] < other.vertices[ 1 ] ) );
      }
References Edge(), and vertices.
operator==()
template<typename TDigitalSurfaceContainer> bool DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge::operator== (const Edge & other) const inline
Definition at line 213 of file DigitalSurface.h.
      {
        return ( vertices[ 0 ] == other.vertices[ 0 ] )
          && ( vertices[ 1 ] == other.vertices[ 1 ] );
      }
References Edge(), and vertices.
Field Documentation
vertices
template<typename TDigitalSurfaceContainer> Vertex DGtal::DigitalSurface< TDigitalSurfaceContainer >::Edge::vertices[2]
The two vertices.
Definition at line 194 of file DigitalSurface.h.
Referenced by Edge(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
DigitalSurface.h