DGtal: LibBoard::Image Struct Reference
LibBoard::Image Struct Reference
Used to draw image in figure.
#include <Board/Shapes.h>
Public Member Functions
Image (double x0, double y0, double width, double height, std::string fileName, int depthValue, double alpha=1.0)
const std::string & name () const
Image * clone () const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Public Member Functions inherited from LibBoard::Rectangle
Rectangle (double x, double y, double width, double height, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Rectangle (const Rect &rect, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
double x () const
double y () const
double width ()
double height ()
Point topLeft ()
Point topRight ()
Point bottomLeft ()
Point bottomRight ()
Rectangle rotated (double angle, const Point &center) const
Rectangle rotated (double angle) const
Rectangle translated (double dx, double dy) const
Rectangle scaled (double sx, double sy) const
Rectangle scaled (double s) const
void scaleAll (double s)
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rectangle * clone () const
Public Member Functions inherited from LibBoard::Polyline
Polyline (const std::vector< Point > &points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (const Path &path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Point center () const
Polyline & operator<< (const Point &p)
Point & operator[] (const unsigned int n)
Polyline & rotate (double angle, const Point &center)
Polyline rotated (double angle, const Point &center) const
Polyline & rotate (double angle)
Polyline rotated (double angle) const
Polyline & translate (double dx, double dy)
Polyline translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Polyline scaled (double sx, double sy) const
Polyline scaled (double s) const
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
Rect boundingBox () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
double _x0
double _y0
double _width
double _height
std::string _filename
double _alpha
Protected Attributes inherited from LibBoard::Rectangle
bool _isRectangle
Protected Attributes inherited from LibBoard::Polyline
Path _path
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
Used to draw image in figure.
The Image structure.
Definition at line 1026 of file Board/Shapes.h.
Constructor & Destructor Documentation
Image()
LibBoard::Image::Image (double x0, double y0, double width, double height, std::string fileName, int depthValue, double alpha = 1.0) inline
Constructs a Image.
Parameters
x0 First coordinate of the start point.
y0 Second coordinate of the start point.
width First coordinate of the end point.
height Second coordinate of the end point.
fileName the image filename.
depthValue The depth of the image.
alpha The image transparency used for display (works only is cairo is installed).
References LibBoard::Rectangle::height(), Image(), and LibBoard::Rectangle::width().
Referenced by Image().
Member Function Documentation
clone()
Image * LibBoard::Image::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Definition at line 639 of file Shapes.cpp.
                   {
  return new Image(*this);
}
flushCairo()
void LibBoard::Image::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 686 of file Shapes.cpp.
{
  int w, h;
  cairo_surface_t *image;
  cairo_save (cr);
  std::string extension = _filename.substr(_filename.find_last_of(".") + 1);
  assert(extension=="png");
  image = cairo_image_surface_create_from_png (_filename.c_str());
  assert(cairo_surface_status (image) == CAIRO_STATUS_SUCCESS);
  w = cairo_image_surface_get_width (image);
  h = cairo_image_surface_get_height (image);
  // tr
  cairo_translate (cr, transform.mapX( _path[0].x ), transform.mapY( _path[0].y ));
  //cairo_scale (cr, transform.scale( _path[1].x - _path[0].x )/w, transform.scale( _path[0].y - _path[3].y )/h);
  cairo_scale (cr, transform.scale( (_path[1] - _path[0]).norm() )/w, transform.scale( (_path[0] - _path[3]).norm() )/h);
  // tr
  cairo_set_source_surface (cr, image, 0, 0);
  cairo_paint_with_alpha(cr, _alpha);
  cairo_surface_destroy (image);
  cairo_restore (cr);
}
References _alpha, _filename, LibBoard::Polyline::_path, and image().
flushFIG()
void LibBoard::Image::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Definition at line 644 of file Shapes.cpp.
{
  stream << "2 5 ";
  // Line style
  stream << _lineStyle << " ";
  // Thickness
  stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
  // Pen color
  stream << colormap[ _penColor ] << " ";
  // Fill color
  stream << "0 ";
  // Depth
  stream << transform.mapDepth( _depth ) << " "
         << "-1 -1 0.000 0 0 -1 0 0 5" << std::endl <<" 0 "
   << _filename << std::endl;
  _path.flushFIG( stream, transform );
  stream << std::endl;
}
References LibBoard::Shape::_depth, _filename, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Polyline::_path, and LibBoard::Shape::_penColor.
flushSVG()
void LibBoard::Image::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 669 of file Shapes.cpp.
{
  stream << "<image x=\"" << transform.mapX( _path[0].x ) << '"'
   << " y=\"" << transform.mapY( _path[0].y )  << '"'
   << " width=\"" << transform.scale( (_path[1] - _path[0]).norm() ) << '"'
   << " height=\"" << transform.scale( (_path[0] - _path[3]).norm() ) << '"'
   << "  xlink:href=\""<< _filename << "\" >"  << std::endl
   << " <title>My image</title>"<<std::endl
       << " </image>" << std::endl;
}
References _filename, LibBoard::Polyline::_path, LibBoard::Rectangle::x(), and LibBoard::Rectangle::y().
flushTikZ()
void LibBoard::Image::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 714 of file Shapes.cpp.
{
  stream << "\\node [below right=0pt] at ("
         << transform.mapX( _path[0].x ) << "pt,"
         << transform.mapY( _path[0].y ) << "pt) {\\pgfimage["
         << "width=" << transform.scale( (_path[1] - _path[0]).norm() ) << "pt,"
         << "height=" << transform.scale( (_path[0] - _path[3]).norm() ) << "pt,"
         << "]{" << _filename << "}};" << std::endl;
}
References _filename, LibBoard::Polyline::_path, LibBoard::Rectangle::x(), and LibBoard::Rectangle::y().
name()
const std::string & LibBoard::Image::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
objet name
Reimplemented from LibBoard::Shape.
Definition at line 633 of file Shapes.cpp.
{
    return _name;
}
References _name.
Field Documentation
_alpha
double LibBoard::Image::_alpha protected
Definition at line 1076 of file Board/Shapes.h.
Referenced by flushCairo().
_filename
std::string LibBoard::Image::_filename protected
Definition at line 1075 of file Board/Shapes.h.
Referenced by flushCairo(), flushFIG(), flushSVG(), and flushTikZ().
_height
double LibBoard::Image::_height protected
Definition at line 1074 of file Board/Shapes.h.
_name
const std::string LibBoard::Image::_name static private
The generic name of the shape.
Definition at line 1068 of file Board/Shapes.h.
Referenced by name().
_width
double LibBoard::Image::_width protected
Definition at line 1073 of file Board/Shapes.h.
_x0
double LibBoard::Image::_x0 protected
First coordinate of the bottom left point.
Definition at line 1071 of file Board/Shapes.h.
_y0
double LibBoard::Image::_y0 protected
Second coordinate of the bottom left point.
Definition at line 1072 of file Board/Shapes.h.
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp