DGtal: DGtal::IntegerConverter< dim, DGtal::int32_t > Struct Template Reference
DGtal::IntegerConverter< dim, DGtal::int32_t > Struct Template Reference
#include <DGtal/kernel/IntegerConverter.h>
Public Types
typedef DGtal::int32_t Integer
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< DGtal::int32_t >))
Static Public Member Functions
static DGtal::int32_t cast (DGtal::int32_t i)
static PointVector< dim, DGtal::int32_t > cast (PointVector< dim, DGtal::int32_t > p)
static DGtal::int32_t cast (DGtal::int64_t i)
static PointVector< dim, DGtal::int32_t > cast (PointVector< dim, DGtal::int64_t > p)
static DGtal::int32_t cast (DGtal::BigInteger i)
static PointVector< dim, DGtal::int32_t > cast (PointVector< dim, DGtal::BigInteger > p)
Detailed Description
template<DGtal::Dimension dim>
struct DGtal::IntegerConverter< dim, DGtal::int32_t >
Allows seamless conversion of integral types and lattice points, while checking for errors when going from a more precise to a less precise type.
Specialized version for int32_t.
Template Parameters
dim static constant of type DGtal::Dimension that specifies the static dimension of the space and thus the number of elements of the Point or Vector.
Definition at line 102 of file IntegerConverter.h.
Member Typedef Documentation
Integer
template<DGtal::Dimension dim> typedef DGtal::int32_t DGtal::IntegerConverter< dim, DGtal::int32_t >::Integer
Definition at line 103 of file IntegerConverter.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
DGtal::IntegerConverter< dim, DGtal::int32_t >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< DGtal::int32_t >))
cast() [1/6]
template<DGtal::Dimension dim> DGtal::int32_t DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (DGtal::BigInteger i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 150 of file IntegerConverter.h.
    {
      auto r = NumberTraits<DGtal::BigInteger>::castToInt64_t(i);
      if ( DGtal::BigInteger( r ) != i )
        trace.warning() << "Bad integer conversion: " << i << " -> " << r
                        << std::endl;
      return (DGtal::int32_t)r;
    }
References DGtal::NumberTraitsImpl< std::decay< T >::type >::castToInt64_t(), and DGtal::trace.
cast() [2/6]
template<DGtal::Dimension dim> DGtal::int32_t DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (DGtal::int32_t i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 107 of file IntegerConverter.h.
    {
      return i;
    }
cast() [3/6]
template<DGtal::Dimension dim> DGtal::int32_t DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (DGtal::int64_t i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 125 of file IntegerConverter.h.
    {
      DGtal::int32_t r = DGtal::int32_t( i );
      if ( DGtal::int64_t( r ) != i )
        trace.warning() << "Bad integer conversion: " << i << " -> " << r
                        << std::endl;
      return r;
    }
References DGtal::trace.
cast() [4/6]
template<DGtal::Dimension dim> PointVector< dim, DGtal::int32_t > DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (PointVector< dim, DGtal::BigInteger > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 165 of file IntegerConverter.h.
    {
      PointVector< dim, DGtal::int32_t > q;
      for ( DGtal::Dimension i = 0; i < dim; i++ )
        q[ i ] = cast( p[ i ] );
      return q;
    }
References DGtal::IntegerConverter< dim, TInteger >::cast(), and dim.
cast() [5/6]
template<DGtal::Dimension dim> PointVector< dim, DGtal::int32_t > DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (PointVector< dim, DGtal::int32_t > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 118 of file IntegerConverter.h.
    {
      return p;
    }
cast() [6/6]
template<DGtal::Dimension dim> PointVector< dim, DGtal::int32_t > DGtal::IntegerConverter< dim, DGtal::int32_t >::cast (PointVector< dim, DGtal::int64_t > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 140 of file IntegerConverter.h.
    {
      PointVector< dim, DGtal::int32_t > q;
      for ( DGtal::Dimension i = 0; i < dim; i++ )
        q[ i ] = cast( p[ i ] );
      return q;
    }
References DGtal::IntegerConverter< dim, TInteger >::cast(), and dim.
The documentation for this struct was generated from the following file:
IntegerConverter.h