DGtal: DGtal::Object< TDigitalTopology, TDigitalSet >::Edge Struct Reference
DGtal::Object< TDigitalTopology, TDigitalSet >::Edge Struct Reference
#include <DGtal/topology/Object.h>
Public Member Functions
Edge ()
Edge (const Vertex &v1, const Vertex &v2, const bool)
Edge (const Vertex &v1, const Vertex &v2)
bool operator== (const Edge &other) const
bool operator!= (const Edge &other) const
bool operator< (const Edge &other) const
Data Fields
Vertex vertices [2]
Detailed Description
template<typename TDigitalTopology, typename TDigitalSet>
struct DGtal::Object< TDigitalTopology, TDigitalSet >::Edge
Definition at line 165 of file Object.h.
Constructor & Destructor Documentation
Edge() [1/3]
template<typename TDigitalTopology, typename TDigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::Edge () inline
Invalid default constructor.
Definition at line 172 of file Object.h.
{}
Referenced by operator!=(), operator<(), and operator==().
Edge() [2/3]
template<typename TDigitalTopology, typename TDigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::Edge (const Vertex & v1, const Vertex & v2, const bool) inline
Constructor from vertices with no auto-order.
Parameters
v1 the first vertex.
v2 the second vertex.
Definition at line 179 of file Object.h.
      {
        vertices[ 0 ] = v1;
        vertices[ 1 ] = v2;
      }
References vertices.
Edge() [3/3]
template<typename TDigitalTopology, typename TDigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::Edge (const Vertex & v1, const Vertex & v2) inline
Constructor from vertices with auto-ordering.
Parameters
v1 the first vertex.
v2 the second vertex.
Note
Edge(v1,v2) = Edge(v2,v1), stored vertices[0] will be the lowest of the two.
Definition at line 190 of file Object.h.
      {
        if ( v1 <= v2 )
        {
          vertices[ 0 ] = v1;
          vertices[ 1 ] = v2;
        }
        else
        {
          vertices[ 0 ] = v2;
          vertices[ 1 ] = v1;
        }
      }
References vertices.
Member Function Documentation
operator!=()
template<typename TDigitalTopology, typename TDigitalSet> bool DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator!= (const Edge & other) const inline
Definition at line 208 of file Object.h.
      {
        return ( vertices[ 0 ] != other.vertices[ 0 ] )
          || ( vertices[ 1 ] != other.vertices[ 1 ] );
      }
References Edge(), and vertices.
operator<()
template<typename TDigitalTopology, typename TDigitalSet> bool DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator< (const Edge & other) const inline
Definition at line 213 of file Object.h.
      {
        return ( vertices[ 0 ] < other.vertices[ 0 ] )
          || ( ( vertices[ 0 ] == other.vertices[ 0 ] )
              && ( vertices[ 1 ] < other.vertices[ 1 ] ) );
      }
References Edge(), and vertices.
operator==()
template<typename TDigitalTopology, typename TDigitalSet> bool DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator== (const Edge & other) const inline
Definition at line 203 of file Object.h.
      {
        return ( vertices[ 0 ] == other.vertices[ 0 ] )
          && ( vertices[ 1 ] == other.vertices[ 1 ] );
      }
References Edge(), and vertices.
Field Documentation
vertices
template<typename TDigitalTopology, typename TDigitalSet> Vertex DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::vertices[2]
Definition at line 167 of file Object.h.
Referenced by Edge(), Edge(), operator!=(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
Object.h