DGtal: DGtal::ITKDicomReader< TImage > Struct Template Reference
DGtal::ITKDicomReader< TImage > Struct Template Reference
Aim: Import a 2D/3D DICOM Image from file series.
#include <DGtal/io/readers/ITKDicomReader.h>
Data Structures
struct Aux
struct Aux< ImageContainerByITKImage< Domain, Value >, Domain, OrigValue, TFunctor, Value >
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef ITKIOTrait< Value >::ValueOut ValueOut
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TImage >))
Static Public Member Functions
template<typename TFunctor = typename ITKIOTrait<typename TImage::Value>::DefaultReadFunctor>
static Image importDICOM (const std::vector< std::string > &filenames, const TFunctor &aFunctor=TFunctor())
Static Private Member Functions
template<typename Domain, typename PixelType>
static ImageContainerByITKImage< Domain, PixelType > importDicomFiles (const std::vector< std::string > &filenames)
template<typename TypeDGtalImage, typename TFunctor>
static Image readDGtalImageFromITKtypes (const std::vector< std::string > &filenames, const TFunctor &aFunctor)
Detailed Description
template<typename TImage>
struct DGtal::ITKDicomReader< TImage >
Aim: Import a 2D/3D DICOM Image from file series.
Description of template class 'ITKDicomReader'
This class requires ITK installation (http://www.itk.org/ITK/resources/software.html) and to compile DGtal with -DDGTAL_WITH_ITK option.
Simple example: (extract from test/io/readers/testITKDicomReader.cpp)
Template Parameters
TImage the Image type.
See also
ITKWriter
ITKIOTrait
Definition at line 81 of file ITKDicomReader.h.
Member Typedef Documentation
Image
template<typename TImage> typedef TImage DGtal::ITKDicomReader< TImage >::Image
Definition at line 83 of file ITKDicomReader.h.
Value
template<typename TImage> typedef TImage::Value DGtal::ITKDicomReader< TImage >::Value
Definition at line 84 of file ITKDicomReader.h.
ValueOut
template<typename TImage> typedef ITKIOTrait<Value>::ValueOut DGtal::ITKDicomReader< TImage >::ValueOut
Definition at line 85 of file ITKDicomReader.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TImage> DGtal::ITKDicomReader< TImage >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TImage >))
importDICOM()
template<typename TImage> template<typename TFunctor = typename ITKIOTrait<typename TImage::Value>::DefaultReadFunctor> Image DGtal::ITKDicomReader< TImage >::importDICOM (const std::vector< std::string > & filenames, const TFunctor & aFunctor = TFunctor()) static
Import an Image from files belonging to the same DICOM serie.
First an ImageContainerByITKImage is constructed by using the source type of the input ITK image, and in a second step the resulting image type is adapted to the TImage type with the use of the given Functor.
Parameters
filenames fullnames of file of a DICOM serie. They may be gathered with an itk::GDCMSeriesFileNames instance.
aFunctor functor used to cast image values.
Template Parameters
TFunctor the type of functor used in the export.
Returns
read image
Referenced by TEST_CASE(), testImportDICOM(), and testSpatialInformation().
importDicomFiles()
template<typename TImage> template<typename Domain, typename PixelType> ImageContainerByITKImage< Domain, PixelType > DGtal::ITKDicomReader< TImage >::importDicomFiles (const std::vector< std::string > & filenames) inline static private
readDGtalImageFromITKtypes()
template<typename TImage> template<typename TypeDGtalImage, typename TFunctor> Image DGtal::ITKDicomReader< TImage >::readDGtalImageFromITKtypes (const std::vector< std::string > & filenames, const TFunctor & aFunctor) static private
Read an DGtal image of type TypeDGtalImage from files belonging to the same DICOM serie.
Parameters
filenames fullnames of file of a DICOM serie. They may be gathered with an itk::GDCMSeriesFileNames instance.
aFunctor functor used to cast image values
Template Parameters
TFunctor the type of functor used in the export.
Returns
read image
The documentation for this struct was generated from the following file:
ITKDicomReader.h