DGtal: Fixture_X Struct Reference
Fixture_X Struct Reference
Public Types
using Point = DGtal::Z3i::Point
using Domain = DGtal::Z3i::Domain
using KSpace = DGtal::Z3i::KSpace
using FixtureDigitalTopology = DGtal::Z3i::DT26_6
using FixtureDigitalSet
using FixtureMap = std::unordered_map<KSpace::Cell, CubicalCellData>
using FixtureComplex = DGtal::VoxelComplex<KSpace>
Public Member Functions
Fixture_X ()
FixtureDigitalSet create_set ()
FixtureComplex & create_complex_from_set (FixtureDigitalSet &input_set)
Data Fields
KSpace ks_fixture
FixtureComplex complex_fixture
FixtureDigitalSet set_fixture
Detailed Description
Definition at line 884 of file testVoxelComplex.cpp.
Member Typedef Documentation
Domain
using Fixture_X::Domain = DGtal::Z3i::Domain
Definition at line 889 of file testVoxelComplex.cpp.
FixtureComplex
using Fixture_X::FixtureComplex = DGtal::VoxelComplex<KSpace>
Definition at line 897 of file testVoxelComplex.cpp.
FixtureDigitalSet
using Fixture_X::FixtureDigitalSet
Initial value:
 DGtal::DigitalSetByAssociativeContainer<
        DGtal::Z3i::Domain,
        std::unordered_set<typename DGtal::Z3i::Domain::Point>>
Definition at line 893 of file testVoxelComplex.cpp.
FixtureDigitalTopology
using Fixture_X::FixtureDigitalTopology = DGtal::Z3i::DT26_6
Definition at line 892 of file testVoxelComplex.cpp.
FixtureMap
using Fixture_X::FixtureMap = std::unordered_map<KSpace::Cell, CubicalCellData>
Definition at line 896 of file testVoxelComplex.cpp.
KSpace
using Fixture_X::KSpace = DGtal::Z3i::KSpace
Definition at line 890 of file testVoxelComplex.cpp.
Point
using Fixture_X::Point = DGtal::Z3i::Point
Definition at line 888 of file testVoxelComplex.cpp.
Constructor & Destructor Documentation
Fixture_X()
Fixture_X::Fixture_X () inline
Definition at line 909 of file testVoxelComplex.cpp.
                : complex_fixture(ks_fixture), set_fixture(create_set()) {
        create_complex_from_set(set_fixture);
    }
References complex_fixture, create_complex_from_set(), create_set(), ks_fixture, and set_fixture.
Member Function Documentation
create_complex_from_set()
FixtureComplex & Fixture_X::create_complex_from_set (FixtureDigitalSet & input_set) inline
Definition at line 967 of file testVoxelComplex.cpp.
{
        ks_fixture.init(input_set.domain().lowerBound(),
                        input_set.domain().upperBound(), true);
        complex_fixture = FixtureComplex(ks_fixture);
        complex_fixture.construct(input_set);
        return complex_fixture;
    }
References complex_fixture, DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), ks_fixture, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Referenced by Fixture_X().
create_set()
FixtureDigitalSet Fixture_X::create_set () inline
Definition at line 916 of file testVoxelComplex.cpp.
{
        using namespace DGtal;
        Point p1(-16, -16, -16);
        Point p2(16, 16, 16);
        Domain domain(p1, p2);
        FixtureDigitalSet a_set(domain);
        std::vector<Point> center_set;
        center_set.reserve(9);
        Point c00(0, 0, 0);
        center_set.push_back(c00);
        Point c01x(-1, 0, 0);
        center_set.push_back(c01x);
        Point c10x(1, 0, 0);
        center_set.push_back(c10x);
        Point c02x(-2, 0, 0);
        center_set.push_back(c02x);
        Point c20x(2, 0, 0);
        center_set.push_back(c20x);
        Point c01y(0, -1, 0);
        center_set.push_back(c01y);
        Point c10y(0, 1, 0);
        center_set.push_back(c10y);
        Point c02y(0, -2, 0);
        center_set.push_back(c02y);
        Point c20y(0, 2, 0);
        center_set.push_back(c20y);
        Point z_pos(0, 0, 1);
        int branch_length(4);
        std::vector<Point> diagonals;
        diagonals.reserve(6);
        for (const auto &p : center_set) {
            diagonals.clear();
            for (int l = 0; l <= branch_length; ++l) {
                diagonals.push_back({l, l, 0});
                diagonals.push_back({l, -l, 0});
                diagonals.push_back({-l, l, 0});
                diagonals.push_back({-l, -l, 0});
                for (int z = -1; z <= 1; ++z)
                    for (const auto &d : diagonals)
                        a_set.insert(p + d + (z * z_pos));
            }
        }
                return a_set;
    }
References domain, and DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insert().
Referenced by Fixture_X().
Field Documentation
complex_fixture
FixtureComplex Fixture_X::complex_fixture
Definition at line 902 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set(), and Fixture_X().
ks_fixture
KSpace Fixture_X::ks_fixture
Definition at line 901 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set(), and Fixture_X().
set_fixture
FixtureDigitalSet Fixture_X::set_fixture
Definition at line 903 of file testVoxelComplex.cpp.
Referenced by Fixture_X().
The documentation for this struct was generated from the following file:
testVoxelComplex.cpp