DGtal: testConstImageAdapter.cpp File Reference
testConstImageAdapter.cpp File Reference
DGtal Test Files
A test file for ConstImageAdapter.
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigTest.h"
#include "DGtal/base/BasicFunctors.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/ConstImageAdapter.h"
Functions
template<typename R>
void displayRange (const R &r)
int main (int argc, char **argv)
Detailed Description
A test file for ConstImageAdapter.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/02/13
Author
Martial Tola (marti.nosp@m.al.t.nosp@m.ola@l.nosp@m.iris.nosp@m..cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/10/12
This file is part of the DGtal library.
Definition in file testConstImageAdapter.cpp.
Function Documentation
displayRange()
template<typename R> void displayRange (const R & r)
Examples
io/viewers/viewer3D-7-stdplane.cpp.
Definition at line 52 of file testConstImageAdapter.cpp.
{
  typedef typename R::ConstIterator I;
  for (I it = r.begin(), itEnd = r.end();
       it != itEnd; ++it)
    {
      trace.info() << *it << " ";
    }
  trace.info() << std::endl;
}
References DGtal::trace.
main()
int main (int argc, char ** argv)
[ConstImageAdapterConstruction]
[ConstImageAdapterConstruction]
[ConstImageAdapterRange]
[ConstImageAdapterRange]
Definition at line 64 of file testConstImageAdapter.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Test for ConstImageAdapter" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  using namespace Z2i;
  trace.beginBlock("Image creation");
  //domain
  const Integer size = 5;
  Point p = Point::diagonal(0);
  Point q = Point::diagonal(size-1);
  Domain d(p,q);
  //image
  typedef ImageSelector<Domain, int >::Type Image;
  Image img(d);
  //fill
  const int maximalValue = size*size;
  Image::Range::OutputIterator it = img.range().outputIterator();
  for (int i = 0; i < maximalValue; ++i)
    *it++ = i;
  //display values
  Image::ConstRange r = img.constRange();
  std::copy( r.begin(), r.end(), std::ostream_iterator<int>(cout,", ") );
  cout << endl;
  trace.endBlock();
  const int thresholdValue = maximalValue/2;
  trace.beginBlock("Implicit thresholding");
  functors::Identity g;
  DGtal::functors::Thresholder<Image::Value> t( thresholdValue );
  typedef ConstImageAdapter<Image, Domain, functors::Identity, bool, DGtal::functors::Thresholder<Image::Value> > MyConstImageAdapter;
  BOOST_CONCEPT_ASSERT(( concepts::CConstImage< MyConstImageAdapter > ));
  MyConstImageAdapter a(img, d, g, t);
  //display values
  ConstImageAdapter<Image, Domain, functors::Identity, bool, DGtal::functors::Thresholder<Image::Value> >::ConstRange
    ra = a.constRange();
  std::copy( ra.begin(), ra.end(), std::ostream_iterator<int>(cout,", ") );
  cout << endl;
  std::vector<int> to_vector(25);
  std::copy(ra.begin(), ra.end(), to_vector.begin());
  for (int i = 0; i < 25; i++)
  {
    if (i<=12)
    {
     if (to_vector[i]==1)
     {
      cout << "ok, ";
      nbok +=  1 ; nb++;
     }
     else
     {
      cout << "!ok, ";
      nb++;
     }
    }
    else
    {
     if (to_vector[i]==0)
     {
      cout << "ok, ";
      nbok +=  1 ; nb++;
     }
     else
     {
      cout << "!ok, ";
      nb++;
     }
    }
  }
  cout << endl;
  trace.endBlock();
  bool res = (nbok == nb);
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), DGtal::Image< TImageContainer >::constRange(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end(), g(), DGtal::SimpleRandomAccessRangeFromPoint< TConstIterator, TIterator, DistanceFunctor >::outputIterator(), DGtal::Image< TImageContainer >::range(), and DGtal::trace.