DGtal: testStandardDSLQ0-smartDSS-benchmark.cpp File Reference
testStandardDSLQ0-smartDSS-benchmark.cpp File Reference
DGtal Test Files
#include <cstdlib>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/CPointPredicate.h"
#include "DGtal/arithmetic/IntegerComputer.h"
#include "DGtal/arithmetic/SternBrocot.h"
#include "DGtal/arithmetic/Pattern.h"
#include "DGtal/arithmetic/StandardDSLQ0.h"
Functions
template<typename DSL>
bool checkSubStandardDSLQ0 (const DSL &D, const typename DSL::Point &A, const typename DSL::Point &B)
template<typename Fraction>
bool testSubStandardDSLQ0 (unsigned int nbtries, typename Fraction::Integer moda, typename Fraction::Integer modb, typename Fraction::Integer modx)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/03/05
Functions for testing class SternBrocot.
This file is part of the DGtal library.
Definition in file testStandardDSLQ0-smartDSS-benchmark.cpp.
Function Documentation
checkSubStandardDSLQ0()
template<typename DSL> bool checkSubStandardDSLQ0 (const DSL & D, const typename DSL::Point & A, const typename DSL::Point & B)
Definition at line 49 of file testStandardDSLQ0-smartDSS-benchmark.cpp.
{
  DSL S = D.smartDSS( A, B );
  // std::cout << D.a() << " " << D.b() << " " << D.mu() << " "
  //           << S.a() << " " << S.b() << " " << S.mu() << " "
  //           << A[0] << " " << A[1] << " " << B[0] << " " << B[1]
  //           << std::endl;
  return true;
}
Referenced by testSubStandardDSLQ0().
main()
int main (int argc, char ** argv)
Definition at line 115 of file testStandardDSLQ0-smartDSS-benchmark.cpp.
{
  typedef SternBrocot<DGtal::int64_t,DGtal::int32_t> SB;
  typedef SB::Fraction Fraction;
  typedef Fraction::Integer Integer;
  unsigned int nbtries = ( argc > 1 ) ? atoi( argv[ 1 ] ) : 10000;
  // Integer moda = ( argc > 2 ) ? atoll( argv[ 2 ] ) : 100000000000;
  // Integer modb = ( argc > 3 ) ? atoll( argv[ 3 ] ) : 100000000000;
  // Integer modx = ( argc > 4 ) ? atoll( argv[ 4 ] ) : 1000;
  // testSubStandardDSLQ0<Fraction>( nbtries, moda, modb, modx );
  Integer modb = 1000000000000;
  Integer moda = modb;
  for(Integer modx = 10; modx < modb/2;modx*=2)
    {
      testSubStandardDSLQ0<Fraction>( nbtries, moda, modb, modx );
    }
 return 0;
}
References testSubStandardDSLQ0().
testSubStandardDSLQ0()
template<typename Fraction> bool testSubStandardDSLQ0 (unsigned int nbtries, typename Fraction::Integer moda, typename Fraction::Integer modb, typename Fraction::Integer modx)
Definition at line 64 of file testStandardDSLQ0-smartDSS-benchmark.cpp.
{
  typedef StandardDSLQ0<Fraction> DSL;
  typedef typename Fraction::Integer Integer;
  typedef typename DSL::Point Point;
  IntegerComputer<Integer> ic;
  //std::cout << "# a b mu a1 b1 mu1 Ax Ay Bx By" << std::endl;
  clock_t timeBegin, timeEnd;
  timeBegin = clock();
  for ( unsigned int i = 0; i < nbtries; ++i )
    {
      Integer b( rand() % modb + 1 );
      Integer a( rand() % b + 1 );
      if ( ic.gcd( a, b ) == 1 )
        {
          for ( Integer mu = 0; mu < 5; ++mu )
            {
              DSL D( a, b, rand() % (moda+modb) );
              for ( Integer x = 0; x < 10; ++x )
                {
                  Integer x1 = rand() % modx;
                  Integer x2 = x1 + 1 + ( rand() % modx );
                  Point A = D.lowestY( x1 );
                  Point B = D.lowestY( x2 );
                  checkSubStandardDSLQ0<DSL>( D, A, B );
                }
            }
        }
    }
  timeEnd = clock();
  long double CPUTime;
  CPUTime =  ((double)timeEnd-(double)timeBegin)/((double)CLOCKS_PER_SEC);
  //std::cout << "SmartDSS: CPU Time ellapsed = " << CPUTime << " - Time/test = = " << (long double) CPUTime/(nbtries*5*10) << std::endl;
  std::cout << modx  << " " << (long double) CPUTime/(nbtries*5*10) << std::endl;
return true;
}
References checkSubStandardDSLQ0(), and DGtal::IntegerComputer< TInteger >::gcd().