DGtal: testRigidTransformation2D.cpp File Reference
testRigidTransformation2D.cpp File Reference
DGtal Test Files
#include <iostream>
#include <cmath>
#include <DGtal/images/ImageSelector.h>
#include <DGtal/images/ImageContainerBySTLVector.h>
#include "DGtal/images/ConstImageAdapter.h"
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/images/RigidTransformation2D.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/io/writers/GenericWriter.h"
Data Structures
class testRigidTransformation2D
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, France
Date
2014/06/26
Functions for testing class testRigidTransformation2D.
This file is part of the DGtal library.
Definition in file testRigidTransformation2D.cpp.
Function Documentation
main()
int main (int , char **)
Definition at line 139 of file testRigidTransformation2D.cpp.
{
  bool res = true;
  testRigidTransformation2D rigidTest;
  trace.beginBlock ( "Testing RigidTransformation2D" );
    res &= rigidTest.forwardTransformationBinary();
    res &= rigidTest.backwardTransformationBinary();
    res &= rigidTest.backwardTransformationGray();
    res &= rigidTest.forwardTransformationGray();
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References testRigidTransformation2D::backwardTransformationBinary(), testRigidTransformation2D::backwardTransformationGray(), testRigidTransformation2D::forwardTransformationBinary(), testRigidTransformation2D::forwardTransformationGray(), and DGtal::trace.