DGtal: testArithmeticalDSSComputerOnSurfels.cpp File Reference
testArithmeticalDSSComputerOnSurfels.cpp File Reference
DGtal Test Files
#include <iostream>
#include <string>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/helpers/Shortcuts.h"
#include "DGtal/topology/DigitalSurface2DSlice.h"
#include "ConfigTest.h"
#include "DGtalCatch.h"
#include "DGtal/geometry/curves/ArithmeticalDSSComputer.h"
#include "DGtal/geometry/surfaces/ArithmeticalDSSComputerOnSurfels.h"
#include "DGtal/geometry/curves/SaturatedSegmentation.h"
Data Structures
struct Slice
Typedefs
using KSpace = Z3i::KSpace
using SH3 = Shortcuts<KSpace>
using Surfel = KSpace::SCell
using SegmentComputerOnSurfels = ArithmeticalDSSComputerOnSurfels<KSpace, std::vector<Surfel>::const_iterator, int>
using SegmentationSurfels = SaturatedSegmentation<SegmentComputerOnSurfels>
using SegmentComputer = ArithmeticalDSSComputer<std::vector<Z2i::Point>::const_iterator, int, 4>
using Segmentation = SaturatedSegmentation<SegmentComputer>
Functions
std::pair< KSpace, Slice > getSlice (std::string const &shape="ellipsoid", double gridstep=1.0)
std::vector< Z2i::Point > extractPoints (SegmentComputerOnSurfels const &sc, Slice const &slice)
TEST_CASE ("Testing ArithmeticalDSSComputerOnSurfels")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jocelyn Meyron (jocel.nosp@m.yn.m.nosp@m.eyron.nosp@m.@lir.nosp@m.is.cn.nosp@m.rs.f.nosp@m.r) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2021/02/12
Functions for testing class DGtal::ArithmeticalDSSComputerOnSurfels.
This file is part of the DGtal library.
Definition in file testArithmeticalDSSComputerOnSurfels.cpp.
Typedef Documentation
KSpace
using KSpace = Z3i::KSpace
Examples
dec/exampleHeatLaplace.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/pConvexity-benchmark.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/volDistanceTraversal.cpp, io/viewDualSurface.cpp, io/viewers/viewer3D-10-interaction.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dKSSurfaceExtraction.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-1-3d.cpp, topology/ctopo-1.cpp, topology/ctopo-1s-3d.cpp, topology/cubical-complex-collapse.cpp, topology/cubical-complex-illustrations.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, topology/volTrackBoundary.cpp, tutorial-examples/FMMErosion.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 48 of file testArithmeticalDSSComputerOnSurfels.cpp.
Segmentation
using Segmentation = SaturatedSegmentation<SegmentComputer>
Examples
geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, and geometry/curves/exampleFrechetShortcut.cpp.
Definition at line 56 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentationSurfels
using SegmentationSurfels = SaturatedSegmentation<SegmentComputerOnSurfels>
Definition at line 53 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentComputer
using SegmentComputer = ArithmeticalDSSComputer<std::vector<Z2i::Point>::const_iterator, int, 4>
Examples
geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, and geometry/curves/exampleArithDSS3d.cpp.
Definition at line 55 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentComputerOnSurfels
using SegmentComputerOnSurfels = ArithmeticalDSSComputerOnSurfels<KSpace, std::vector<Surfel>::const_iterator, int>
Definition at line 52 of file testArithmeticalDSSComputerOnSurfels.cpp.
SH3
using SH3 = Shortcuts<KSpace>
Definition at line 49 of file testArithmeticalDSSComputerOnSurfels.cpp.
Surfel
using Surfel = KSpace::SCell
Examples
examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/dvcm-3d.cpp, topology/digitalSurfaceSlice.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 50 of file testArithmeticalDSSComputerOnSurfels.cpp.
Function Documentation
extractPoints()
std::vector< Z2i::Point > extractPoints (SegmentComputerOnSurfels const & sc, Slice const & slice)
Definition at line 95 of file testArithmeticalDSSComputerOnSurfels.cpp.
{
    std::vector<Z2i::Point> points;
    auto initialPoints = sc.getProjectedPointsFromSurfel(slice.start);
    points.push_back(initialPoints.first);
    points.push_back(initialPoints.second);
    for (auto sit = slice.contour.begin() + 1; sit != slice.contour.end(); ++sit)
    {
        Surfel s = *sit;
        auto pt = sc.getNextProjectedPoint(s);
        points.push_back(pt);
    }
    return points;
}
References Slice::contour, DGtal::ArithmeticalDSSComputerOnSurfels< TKSpace, TIterator, TInteger >::getNextProjectedPoint(), DGtal::ArithmeticalDSSComputerOnSurfels< TKSpace, TIterator, TInteger >::getProjectedPointsFromSurfel(), and Slice::start.
Referenced by TEST_CASE().
getSlice()
std::pair< KSpace, Slice > getSlice (std::string const & shape = "ellipsoid", double gridstep = 1.0)
Definition at line 66 of file testArithmeticalDSSComputerOnSurfels.cpp.
{
    using SurfaceSlice = DigitalSurface2DSlice<SH3::DigitalSurface::DigitalSurfaceTracker>;
    auto params = SH3::defaultParameters();
    params("polynomial", shape)("gridstep", gridstep);
    auto implicit_shape = SH3::makeImplicitShape3D(params);
    auto digitized_shape = SH3::makeDigitizedImplicitShape3D(implicit_shape, params);
    auto binary_image = SH3::makeBinaryImage(digitized_shape, params);
    auto kspace = SH3::getKSpace(binary_image, params);
    auto surface = SH3::makeDigitalSurface(binary_image, kspace, params);
    Surfel surfel = Surfaces<KSpace>::findABel(kspace, *binary_image, 10000);
    KSpace::DirIterator q1 = kspace.sDirs(surfel);
    KSpace::DirIterator q2 = kspace.sOrthDirs(surfel);
    Dimension dim1 = *q1, dim2 = *q2;
    auto tracker = surface->container().newTracker(surfel);
    SurfaceSlice surfaceSlice(tracker, dim1);
    delete tracker;
    std::vector<Surfel> contour(surfaceSlice.begin(), surfaceSlice.end());
    Slice slice{dim1, dim2, surfel, contour};
    return { kspace, slice };
}
References binary_image, DGtal::Shortcuts< KSpace >::defaultParameters(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::Shortcuts< KSpace >::getKSpace(), DGtal::Shortcuts< KSpace >::makeBinaryImage(), DGtal::Shortcuts< KSpace >::makeDigitalSurface(), DGtal::Shortcuts< KSpace >::makeDigitizedImplicitShape3D(), DGtal::Shortcuts< KSpace >::makeImplicitShape3D(), and surface.
Referenced by TEST_CASE().
TEST_CASE()
TEST_CASE ("Testing ArithmeticalDSSComputerOnSurfels")
Definition at line 114 of file testArithmeticalDSSComputerOnSurfels.cpp.
{
    // Construct and extract a slice of a digital surface
    KSpace kspace;
    Slice slice;
    std::tie(kspace, slice) = getSlice();
    // Do a segmentation using the surfel class
    SegmentComputerOnSurfels recognitionAlgorithmSurfels(kspace, slice.dim1, slice.dim2);
    SegmentationSurfels segmentationSurfels(slice.contour.begin(), slice.contour.end(), recognitionAlgorithmSurfels);
    // Extract the projected points
    std::vector<Z2i::Point> points = extractPoints(recognitionAlgorithmSurfels, slice);
    // Do a segmentation on the projected points
    SegmentComputer recognitionAlgorithm;
    Segmentation segmentation(points.begin(), points.end(), recognitionAlgorithm);
    // The two segmentations must be the same
    bool allEqual = true;
    auto segIt = segmentation.begin();
    auto segSurfelIt = segmentationSurfels.begin();
    while (segIt != segmentation.end() && segSurfelIt != segmentationSurfels.end()) {
      allEqual = allEqual && (segIt->primitive() == segSurfelIt->primitive());
      ++segIt;
      ++segSurfelIt;
    }
    REQUIRE(allEqual);
}
References DGtal::SaturatedSegmentation< TSegmentComputer >::begin(), Slice::contour, Slice::dim1, Slice::dim2, DGtal::SaturatedSegmentation< TSegmentComputer >::end(), extractPoints(), getSlice(), and REQUIRE().