DGtal: testClone2.cpp File Reference
testClone2.cpp File Reference
DGtal Test Files
#include <cstdio>
#include <cmath>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/base/CountedPtr.h"
#include "DGtal/base/CountedPtrOrPtr.h"
#include "DGtal/base/CountedConstPtrOrConstPtr.h"
#include "DGtal/base/CowPtr.h"
#include "DGtal/base/Clone.h"
#include "DGtal/base/Alias.h"
#include "DGtal/base/ConstAlias.h"
#include "DGtal/helpers/StdDefs.h"
Data Structures
class DGtal::NClone< T >
struct DummyTbl
struct CloneToValueMember
struct CloneToCountedMember
struct CloneToCowMember
struct CloneToPtrMember
struct AliasToRefMember
struct AliasToPtrMember
struct AliasToCountedPtrOrPtrMember
struct AliasToConstRefMember
struct ConstAliasToConstRefMember
struct ConstAliasToConstPtrMember
struct ConstAliasToCountedConstPtrOrConstPtrMember
class MyPoint
class MyPointD
struct TriangleByConstReference
struct TriangleByValue
struct TriangleByClone
struct TriangleByCloneAndCow
Namespaces
namespace DGtal
DGtal is the top-level namespace which contains all DGtal functions and types.
Typedefs
typedef MyPointD Point
Functions
template<typename Triangle>
double computeTriangles (int size)
template<typename Triangle>
double computeTrianglesByCowPtr (int size)
bool testAliasCases ()
bool testConstAliasCases ()
bool testCloneCases ()
bool testCloneTimings ()
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2012/07/02
This file is part of the DGtal library
Definition in file testClone2.cpp.
Typedef Documentation
Point
typedef MyPointD Point
Examples
arithmetic/lower-integer-convex-hull.cpp, dec/exampleDECSurface.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, doc-examples/exampleCatch.cpp, examples/io/external-viewers/polyscope/exampleGenericLatticeConvexHull3D.cpp, examples/io/external-viewers/polyscope/exampleGenericLatticeConvexHull4D.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, geometry/curves/estimation/exampleLMST3DBy2D.cpp, geometry/curves/exampleArithDSS3d.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleDSLSubsegment.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/tools/checkLatticeBallQuickHull.cpp, geometry/tools/determinant/exampleInHalfPlane.cpp, geometry/tools/exampleAffineGeometry.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/exampleGenericLatticeConvexHull.cpp, geometry/tools/exampleLatticeBallDelaunay2D.cpp, geometry/tools/exampleLatticeBallDelaunay3D.cpp, geometry/tools/exampleLatticeBallQuickHull3D.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount2D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount3D.cpp, geometry/volumes/exampleBoundedLatticePolytopeCount4D.cpp, geometry/volumes/fullConvexityAnalysis3D.cpp, geometry/volumes/fullConvexityLUT2D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/fullConvexityThinning3D.cpp, geometry/volumes/pConvexity-benchmark.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, graph/graphTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleRigidtransformation3d.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/exampleBezierCurve.cpp, io/boards/logoDGtal.cpp, io/viewDualSurface.cpp, io/viewers/viewer3D-1-points.cpp, io/viewers/viewer3D-10-interaction.cpp, io/viewers/viewer3D-2-sets.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-4-modes.cpp, io/viewers/viewer3D-5-colors.cpp, io/viewers/viewer3D-6-clipping.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, shapes/exampleMeshVoxelizer.cpp, shapes/mesh3DConstructionAndVisualisation.cpp, topology/3dBorderExtraction.cpp, topology/3dKSSurfaceExtraction.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/ctopo-1-3d.cpp, topology/ctopo-1.cpp, topology/ctopo-1s-3d.cpp, topology/cubical-complex-collapse.cpp, topology/cubical-complex-illustrations.cpp, topology/frontierAndBoundary.cpp, topology/generateSimplicityTables2D.cpp, topology/homotopicThinning3D.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 381 of file testClone2.cpp.
Function Documentation
computeTriangles()
template<typename Triangle> double computeTriangles (int size)
Definition at line 426 of file testClone2.cpp.
{
  double total = 0.0;
  Point A( 0, 0 );
  for ( int yb = 0; yb < size; ++yb )
    for ( int xb = 0; xb < size; ++xb )
      {
        Point B( xb, yb );
        for ( int yc = 0; yc < size; ++yc )
          for ( int xc = 0; xc < size; ++xc )
            {
              Point C( xc, yc );
              Triangle T( A, B, C );
              total += T.perimeter();
            }
      }
  return total;
}
Referenced by testCloneTimings().
computeTrianglesByCowPtr()
template<typename Triangle> double computeTrianglesByCowPtr (int size)
Definition at line 447 of file testClone2.cpp.
{
  double total = 0.0;
  CowPtr<Point> A( new Point( 0, 0 ) );
  for ( int yb = 0; yb < size; ++yb )
    for ( int xb = 0; xb < size; ++xb )
      {
        CowPtr<Point> B( new Point( xb, yb ) );
        for ( int yc = 0; yc < size; ++yc )
          for ( int xc = 0; xc < size; ++xc )
            {
              CowPtr<Point> C( new Point( xc, yc ) );
              Triangle T( A, B, C );
              total += T.perimeter();
            }
      }
  return total;
}
Referenced by testCloneTimings().
main()
int main (void)
Definition at line 945 of file testClone2.cpp.
{
  bool ok = true
    && testCloneCases()
    && testCloneTimings()
    && testAliasCases()
    && testConstAliasCases();
  return ok ? 0 : 1;
}
References testAliasCases(), testCloneCases(), testCloneTimings(), and testConstAliasCases().
testAliasCases()
bool testAliasCases ()
Alias: Performs without unnecessary duplicates "parameter -> member data"
A& -> A& // no duplication (checked)
A* -> A& // no duplication, exception if null (checked)
A& -> A* // no duplication (checked)
A* -> A* // no duplication (checked)
CountedPtr -> CountedPtr // shared (checked)
CountedPtr -> CowPtr // shared (not logical, but not preventable). (checked)
Definition at line 475 of file testClone2.cpp.
{
  unsigned int nb = 0;
  unsigned int nbok = 0;
  DummyTbl a1( 100, 10 ); // +1/0
  DummyTbl* ptr_a2 = new DummyTbl( 100, 18 ); // +1/0
  CountedPtr<DummyTbl> counted_a1( new DummyTbl( 100, 12 ) ); // +1/0
  DummyTbl::reset();
  trace.beginBlock ( "Testing class Alias." );
  /*
     - A& -> A&                       // no duplication
     - A* -> A&                       // no duplication, exception if null
     - A& -> A*                       // no duplication
     - A* -> A*                       // no duplication
     - CountedPtr<A> -> CountedPtr<A> // shared
  */
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl& to DummyTbl& member. no duplication (0/0)" );
  AliasToRefMember c00( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c00.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl* to DummyTbl& member. no duplication (0/0)" );
  AliasToRefMember c10( ptr_a2 ); // 0/0
  trace.info() << "D: d1.value() = " << c10.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl& to DummyTbl* member. no duplication (0/0)" );
  AliasToPtrMember c01( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c01.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl* to DummyTbl* member. no duplication (0/0)" );
  AliasToPtrMember c11( ptr_a2 ); // 0/0
  trace.info() << "D: d1.value() = " << c11.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl& to CountedPtrOrPtr<DummyTbl> member. no duplication (0/0)" );
  AliasToCountedPtrOrPtrMember c06( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c06.value() << std::endl;
  trace.info() << c06.myDummyTbl << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Alias: #DummyTbl with DummyTbl* to CountedPtrOrPtr<DummyTbl> member. no duplication (0/0)" );
  AliasToCountedPtrOrPtrMember c16( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c16.value() << std::endl;
  trace.info() << c16.myDummyTbl << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  // const DummyTbl& const_a1 = a1;
  // AliasToRefMember c02( const_a1 ); // does not execute.
  // const DummyTbl* const_ptr_a1 = &a1;
  // AliasToRefMember c05( const_ptr_a1 ); // does not execute.
  trace.endBlock();
  delete ptr_a2;
  return nbok == nb;
}
References AliasToCountedPtrOrPtrMember::myDummyTbl, DummyTbl::nbCreated, DummyTbl::nbDeleted, DummyTbl::reset(), DGtal::trace, AliasToCountedPtrOrPtrMember::value(), AliasToPtrMember::value(), and AliasToRefMember::value().
Referenced by main().
testCloneCases()
bool testCloneCases ()
Clone: Performs without unnecessary duplicates "parameter -> member data"
const A & -> A // immediate duplication (checked)
A* -> A // immediate duplication, acquired and deleted. (checked)
CountedPtr -> A // immediate duplication (checked)
CowPtr -> A // immediate duplication (checked)
A&& -> A // move into member (checked)
const A & -> CowPtr // immediate duplication (checked)
A* -> CowPtr // acquired (checked)
CountedPtr -> CowPtr // lazy duplication (checked)
CowPtr -> CowPtr // lazy duplication (checked)
A&& -> CowPtr // move into member (checked)
const A & -> A* // immediate duplication, should be deleted at the end. (checked)
A* -> A* // acquired, should be deleted at the end. (checked)
CountedPtr -> A* // immediate duplication, should be deleted at the end. (checked)
CowPtr -> A* // immediate duplication, should be deleted at the end. (checked)
A&& -> A* // move into member, should be deleted at the end. (checked)
Definition at line 691 of file testClone2.cpp.
{
  unsigned int nb = 0;
  unsigned int nbok = 0;
  DummyTbl a1( 50, 10 ); // +1/0
  CowPtr<DummyTbl> cow_a1( new DummyTbl( 50, 5 ) ); // +1/0
  CountedPtr<DummyTbl> counted_a1( new DummyTbl( 50, 12 ) ); // +1/0
  DummyTbl::reset();
  trace.beginBlock ( "Testing class Clone." );
  trace.beginBlock ( "Clone: #DummyTbl with (const DummyTbl &) to DummyTbl member. Duplication (+1/0)" );
  CloneToValueMember c00( a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c00.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==1 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (CountedPtr<DummyTbl>) to DummyTbl member. Duplication (+1/0)" );
  CloneToValueMember c30( a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c30.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==2 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (const DummyTbl &) to CountedPtr<DummyTbl> member. Duplication (+1/0)" );
  CloneToCountedMember c03( a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c03.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==3 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (const DummyTbl &) to CowPtr<DummyTbl> member. Duplication (+1/0)" );
  CloneToCowMember c02( a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c02.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==4 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (CowPtr<DummyTbl> &) to CowPtr<DummyTbl> member. Lazy duplication (0/0)" );
  CloneToCowMember c22( cow_a1 ); // +0/0
  trace.info() << "D: d1.value() = " << c22.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==4 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  c22.setValue( 17 );
  trace.info() << "D: d1.setValue( 17 ) -> now duplicating " << std::endl;
  trace.info() << "D: d1.value() = " << c22.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==5 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (CountedPtr<DummyTbl> &) to CowPtr<DummyTbl> member. Lazy duplication (0/0)" );
  CloneToCowMember c32( counted_a1 ); // +0/0
  trace.info() << "D: d1.value() = " << c32.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==5 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  c32.setValue( 21 );
  trace.info() << "D: d1.setValue( 21 ) -> now duplicating " << std::endl;
  trace.info() << "D: d1.value() = " << c32.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==6 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl*) to DummyTbl member. Acquisition, duplication, delete (+2/+1)" );
  CloneToValueMember c10( new DummyTbl( 50, 2 ) ); // +2/+1
  trace.info() << "D: d1.value() = " << c10.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==8 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl*) to CowPtr<DummyTbl> member. Acquisition, no duplication (+1/0)" );
  CloneToCowMember c12( new DummyTbl( 50, 15 ) ); // +1/0
  trace.info() << "D: d1.value() = " << c12.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==9 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (const DummyTbl&) to DummyTbl* member. Duplication (+1/0)" );
  CloneToPtrMember c01( a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c01.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==10 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl*) to DummyTbl* member. Acquisition (+1/0)" );
  CloneToPtrMember c11( new DummyTbl( 50, 42 ) ); // +1/0
  trace.info() << "D: d1.value() = " << c11.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==11 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (CowPtr<DummyTbl>) to DummyTbl* member. Duplication (+1/0)" );
  CloneToPtrMember c21( cow_a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c21.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==12 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (CountedPtr<DummyTbl>) to DummyTbl* member. Duplication (+1/0)" );
  CloneToPtrMember c31( counted_a1 ); // +1/0
  trace.info() << "D: d1.value() = " << c31.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==13 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl &&) to DummyTbl member. Duplication by move (+2/+1/+1)" );
  CloneToValueMember c40( DummyTbl( 50, -4 ) ); // +2/+1/+1
  trace.info() << "D: d1.value() = " << c40.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==15 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==2 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbMoved==1 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted
               << " nbMoved=" << DummyTbl::nbMoved
               << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl &&) to CowPtr<DummyTbl> member. Duplication by move (+2/+1/+1)" );
  CloneToCowMember c42( DummyTbl( 50, -9 ) ); // +2/+1/+1
  trace.info() << "D: d1.value() = " << c42.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==17 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==3 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbMoved==2 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted
               << " nbMoved=" << DummyTbl::nbMoved
               << std::endl;
  trace.endBlock();
  trace.beginBlock ( "Clone: #DummyTbl with (DummyTbl &&) to DummyTbl* member. Duplication by move (+2/+1/+1)" );
  CloneToCowMember c41( DummyTbl( 50, -12 ) ); // +2/+1/+1
  trace.info() << "D: d1.value() = " << c41.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==19 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==4 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbMoved==3 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted
               << " nbMoved=" << DummyTbl::nbMoved
               << std::endl;
  trace.endBlock();
  trace.endBlock();
  return nbok == nb;
}
References DummyTbl::nbCreated, DummyTbl::nbDeleted, DummyTbl::nbMoved, DummyTbl::reset(), CloneToCowMember::setValue(), DGtal::trace, CloneToCountedMember::value(), CloneToCowMember::value(), CloneToPtrMember::value(), and CloneToValueMember::value().
Referenced by main().
testCloneTimings()
bool testCloneTimings ()
Definition at line 882 of file testClone2.cpp.
{
  unsigned int nb = 0;
  unsigned int nbok = 0;
  int size = 10;
  trace.beginBlock ( "Testing Clone timings." );
  trace.beginBlock ( "Total perimeter of triangles with by-value parameter passing." );
  double t1 = computeTriangles<TriangleByValue>( size );
  trace.info() << "Perimeter is " << t1 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  int nbC = Point::nbCreated;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with by-const reference parameter passing." );
  double t2 = computeTriangles<TriangleByConstReference>( size );
  trace.info() << "Perimeter is " << t2 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated < nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with by Clone parameter passing." );
  double t4 = computeTriangles<TriangleByClone>( size );
  trace.info() << "Perimeter is " << t4 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated <= nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with by CloneAndCow parameter passing." );
  double t5 = computeTriangles<TriangleByCloneAndCow>( size );
  trace.info() << "Perimeter is " << t5 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated < nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  trace.beginBlock ( "Total perimeter of triangles with CowPtr by CloneAndCow parameter passing." );
  double t6 = computeTrianglesByCowPtr<TriangleByCloneAndCow>( size );
  trace.info() << "Perimeter is " << t6 << std::endl;
  ++nb; nbok += Point::nbCreated == Point::nbDeleted ? 1 : 0;
  ++nb; nbok += Point::nbCreated < nbC ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " Point nbCreated=" << Point::nbCreated
               << " nbDeleted=" << Point::nbDeleted << std::endl;
  Point::reset();
  trace.endBlock();
  trace.endBlock();
  return nb == nbok;
}
References computeTriangles(), computeTrianglesByCowPtr(), MyPointD::nbCreated, MyPointD::nbDeleted, MyPointD::reset(), and DGtal::trace.
Referenced by main().
testConstAliasCases()
bool testConstAliasCases ()
ConstAlias: Performs without unnecessary duplicates "parameter -> member data"
const A & -> const A & // no duplication (checked)
const A* -> const A & // no duplication, exception if null (checked)
const A & -> const A* // no duplication (checked)
const A* -> const A* // no duplication (checked)
CountedPtr -> CowPtr // potential lazy duplication (checked)
CowPtr -> CowPtr // potential lazy duplication (checked)
Definition at line 574 of file testClone2.cpp.
{
  unsigned int nb = 0;
  unsigned int nbok = 0;
  DummyTbl a1( 100, 10 ); // +1/0
  DummyTbl* ptr_a2 = new DummyTbl( 100, 18 ); // +1/0
  CountedPtr<DummyTbl> counted_a1( new DummyTbl( 100, 12 ) ); // +1/0
  CowPtr<DummyTbl> cow_a1( new DummyTbl( 100, 16 ) ); // +1/0
  DummyTbl::reset();
  trace.beginBlock ( "Testing class ConstAlias." );
  /*
     - const A & -> const A &     // no duplication
     - const A* -> const A &      // no duplication, exception if null
     - const A & -> const A*      // no duplication
     - const A* -> const A*       // no duplication
     - CountedPtr<A> -> CowPtr<A> // potential lazy duplication
     - CowPtr<A> -> CowPtr<A>     // potential lazy duplication
  */
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl& to const DummyTbl& member. no duplication (0/0)" );
  ConstAliasToConstRefMember c00( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c00.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl* to const DummyTbl& member. no duplication (0/0)" );
  ConstAliasToConstRefMember c10( ptr_a2 ); // 0/0
  trace.info() << "D: d1.value() = " << c10.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl& to const DummyTbl* member. no duplication (0/0)" );
  ConstAliasToConstPtrMember c01( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c01.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl* to const DummyTbl* member. no duplication (0/0)" );
  ConstAliasToConstPtrMember c11( ptr_a2 ); // 0/0
  trace.info() << "D: d1.value() = " << c11.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl* to CountedConstPtrOrConstPtr<DummyTbl> member. No duplication (0/0)" );
  ConstAliasToCountedConstPtrOrConstPtrMember c17( ptr_a2 ); // 0/0
  trace.info() << "D: d1.value() = " << c17.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with const DummyTbl& to CountedConstPtrOrConstPtr<DummyTbl> member. No duplication (0/0)" );
  ConstAliasToCountedConstPtrOrConstPtrMember c07( a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c07.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  trace.beginBlock ( "ConstAlias: #DummyTbl with CountedPtr<DummyTbl> to CountedConstPtrOrConstPtr<DummyTbl> member. No duplication (0/0)" );
  ConstAliasToCountedConstPtrOrConstPtrMember c37( counted_a1 ); // 0/0
  trace.info() << "D: d1.value() = " << c37.value() << std::endl;
  ++nb; nbok += DummyTbl::nbCreated==0 ? 1 : 0;
  ++nb; nbok += DummyTbl::nbDeleted==0 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ")"
               << " nbCreated=" << DummyTbl::nbCreated
               << " nbDeleted=" << DummyTbl::nbDeleted << std::endl;
  trace.endBlock();
  // These lines do not compile.
  // DummyTbl& ref_a1 = ConstAlias<DummyTbl>( a1 );
  // DummyTbl* ptr_a1( & ConstAlias<DummyTbl>( a1 ) );
  trace.endBlock();
  delete ptr_a2;
  return nbok == nb;
}
References DummyTbl::nbCreated, DummyTbl::nbDeleted, DummyTbl::reset(), DGtal::trace, ConstAliasToConstPtrMember::value(), ConstAliasToConstRefMember::value(), and ConstAliasToCountedConstPtrOrConstPtrMember::value().
Referenced by main().