DGtal: testVoronoiMapComplete.cpp File Reference
testVoronoiMapComplete.cpp File Reference
DGtal Test Files
#include <limits>
#include <unordered_set>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtalCatch.h"
#include "DGtal/geometry/volumes/distance/VoronoiMapComplete.h"
#include "DGtal/geometry/volumes/distance/VoronoiMap.h"
Typedefs
typedef Z2i::DigitalSet DigitalSet
typedef Z2i::Point Point
typedef Z2i::Domain Domain
typedef VoronoiMapComplete< Z2i::Space, DigitalSet, Z2i::L2Metric > CompleteVMap
typedef VoronoiMap< Z2i::Space, DigitalSet, Z2i::L2Metric > VMap
typedef ImageContainerBySTLVector< HyperRectDomain< Z2i::Space >, std::unordered_set< Z2i::Point > > TImageContainer
Functions
TImageContainer * brut_force_voronoi_map_complete (DigitalSet &set)
TEST_CASE ("Testing VoronoiMapComplete 2D")
TEST_CASE ("No sites")
TEST_CASE ("Testing Timings")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Robin Lamy
Date
2021/07/20
Functions for testing class VoronoiMapComplete.
This file is part of the DGtal library.
Definition in file testVoronoiMapComplete.cpp.
Typedef Documentation
CompleteVMap
typedef VoronoiMapComplete<Z2i::Space, DigitalSet, Z2i::L2Metric> CompleteVMap
Definition at line 44 of file testVoronoiMapComplete.cpp.
DigitalSet
typedef Z2i::DigitalSet DigitalSet
Examples
arithmetic/lower-integer-convex-hull.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/fullConvexityThinning3D.cpp, graph/graphTraversal.cpp, graph/volDistanceTraversal.cpp, images/exampleConstImageAdapter.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/viewers/viewer3D-2-sets.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-6-clipping.cpp, shapes/exampleMeshVoxelizer.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/3dBorderExtraction.cpp, topology/3dKSSurfaceExtraction.cpp, topology/area-estimation-with-digital-surface.cpp, topology/area-estimation-with-indexed-digital-surface.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/digitalSurfaceSlice.cpp, topology/generateSimplicityTables2D.cpp, topology/homotopicThinning3D.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, and topology/volTrackBoundary.cpp.
Definition at line 40 of file testVoronoiMapComplete.cpp.
Domain
typedef Z2i::Domain Domain
Definition at line 42 of file testVoronoiMapComplete.cpp.
Point
typedef Z2i::Point Point
Definition at line 41 of file testVoronoiMapComplete.cpp.
TImageContainer
typedef ImageContainerBySTLVector<HyperRectDomain<Z2i::Space>, std::unordered_set<Z2i::Point> > TImageContainer
Definition at line 48 of file testVoronoiMapComplete.cpp.
VMap
typedef VoronoiMap<Z2i::Space, DigitalSet, Z2i::L2Metric> VMap
Definition at line 45 of file testVoronoiMapComplete.cpp.
Function Documentation
brut_force_voronoi_map_complete()
TImageContainer * brut_force_voronoi_map_complete (DigitalSet & set)
Definition at line 50 of file testVoronoiMapComplete.cpp.
{
  TImageContainer * voronoi_map = new TImageContainer( set.domain() );
  std::vector<Point> Sites;
  // Getting all voronoi sites in one vector
  for ( Point point : set.domain() )
  {
    if ( !set( point ) )
    {
      Sites.push_back( point );
    }
  }
  std::cout << std::endl;
  for ( Point point : set.domain() )
  {
    std::unordered_set<Point> voronoi_points;
    double voronoi_distance =
    std::numeric_limits<int>::max(); // maximum int value
    for ( Point site : Sites )
    {
      if ( ( point - site ).norm() < voronoi_distance )
      {
        voronoi_points.clear();
        voronoi_points.insert( site );
        voronoi_distance = ( point - site ).norm();
      }
      else if ( ( point - site ).norm() == voronoi_distance )
      {
        voronoi_points.insert( site );
      }
    }
    voronoi_map->setValue( point, voronoi_points );
  }
  return voronoi_map;
}
References DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), and DGtal::ImageContainerBySTLVector< TDomain, TValue >::setValue().
Referenced by TEST_CASE().
TEST_CASE() [1/3]
TEST_CASE ("No sites")
Random set generation
Definition at line 189 of file testVoronoiMapComplete.cpp.
{
  Point lowerBound( 0, 0 ), upperBound( 255, 255 );
  Domain domain( lowerBound, upperBound );
  DigitalSet set( domain );
  trace.beginBlock( "Complete Map (no site)" );
  CompleteVMap vmap( set.domain(), set, Z2i::l2Metric );
  trace.endBlock();
  trace.beginBlock( "Partial Map (no site)" );
  VMap partialmap( set.domain(), set, Z2i::l2Metric );
  trace.endBlock();
}
References DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), domain, DGtal::Z2i::l2Metric, and DGtal::trace.
TEST_CASE() [2/3]
TEST_CASE ("Testing Timings")
Random set generation
Definition at line 206 of file testVoronoiMapComplete.cpp.
{
  Point lowerBound( 0, 0 ), upperBound( 255, 255 );
  Domain domain( lowerBound, upperBound );
  DigitalSet set( domain );
  int point_setup_index = 0;
  int x;
  int y;
  while ( point_setup_index < 5000 )
  {
    x = rand() % 256;
    y = rand() % 256;
    set.insert( Point( x, y ) );
    point_setup_index++;
  }
  std::cout << std::endl;
  trace.beginBlock( "Complete Map" );
  CompleteVMap vmap( set.domain(), set, Z2i::l2Metric );
  trace.endBlock();
  size_t maxsize = 0;
  for ( auto & v : vmap.constRange() )
    maxsize = std::max( maxsize, v.size() );
  trace.info() << "Max number of co-cyclic points = " << maxsize << std::endl;
  trace.beginBlock( "Partial Map" );
  VMap partialmap( set.domain(), set, Z2i::l2Metric );
  trace.endBlock();
}
References DGtal::VoronoiMapComplete< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::constRange(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), domain, DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insert(), DGtal::Z2i::l2Metric, and DGtal::trace.
TEST_CASE() [3/3]
TEST_CASE ("Testing VoronoiMapComplete 2D")
Random set generation
Voronoi Map Complete from class generation
Voronoi Map Complete from brut force generation
Definition at line 91 of file testVoronoiMapComplete.cpp.
{
  Point lowerBound( 0, 0 ), upperBound( 31, 31 );
  Domain domain( lowerBound, upperBound );
  DigitalSet set( domain );
  int point_setup_index = 0;
  int x;
  int y;
  while ( point_setup_index < 400 )
  {
    x = rand() % 32;
    y = rand() % 32;
    set.insert( Point( x, y ) );
    point_setup_index++;
  }
  CompleteVMap vmap( set.domain(), set, Z2i::l2Metric );
  TImageContainer * brut_force_vmap = brut_force_voronoi_map_complete( set );
  SECTION(
  "Testing that VoronoiMapComplete class gives the right voronoi sites sets" )
  {
    for ( Point point : set )
    {
      std::unordered_set<Point> brut_force_set =
      brut_force_vmap->operator()( point );
      CompleteVMap::Value class_set = vmap( point );
      // Cheking that all voronoi sites from the brut force set are in the
      // algorithm set
      for ( Point voronoi_point : brut_force_set )
      {
        REQUIRE( std::find( class_set.begin(), class_set.end(),
                            voronoi_point ) != class_set.end() );
      }
      // Cheking that all voronoi sites from the algorithm set are in the brut
      // force set
      for ( Point voronoi_point : class_set )
      {
        REQUIRE( std::find( brut_force_set.begin(), brut_force_set.end(),
                            voronoi_point ) != brut_force_set.end() );
      }
    }
  }
  SECTION(
  "Testing Complete Voronoi Map from Discrete Bisector Function paper" )
  {
    Point _lowerBound( 0, 0 ), _upperBound( 6, 7 );
    Domain _domain( _lowerBound, _upperBound );
    DigitalSet _set( _domain );
    for ( Point point : _set.domain() )
    {
      if ( point != Point( 1, 0 ) && point != Point( 5, 0 ) &&
           point != Point( 2, 2 ) && point != Point( 4, 4 ) &&
           point != Point( 0, 6 ) && point != Point( 6, 6 ) &&
           point != Point( 3, 7 ) )
        _set.insert( point );
    }
    TImageContainer * brutForceVoronoiMap =
    brut_force_voronoi_map_complete( _set );
    CompleteVMap _vmap( _set.domain(), _set, Z2i::l2Metric );
    for ( Point point : _set )
    {
      std::unordered_set<Point> brut_force_set =
      brutForceVoronoiMap->operator()( point );
      CompleteVMap::Value class_set = _vmap( point );
      // Cheking that all voronoi sites from the brut force set are in the
      // algorithm set
      for ( Point voronoi_point : brut_force_set )
        REQUIRE( std::find( class_set.begin(), class_set.end(),
                            voronoi_point ) != class_set.end() );
      // Cheking that all voronoi sites from the algorithm set are in the brut
      // force set
      for ( Point voronoi_point : class_set )
        REQUIRE( std::find( brut_force_set.begin(), brut_force_set.end(),
                            voronoi_point ) != brut_force_set.end() );
    }
  }
}
References brut_force_voronoi_map_complete(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), domain, DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insert(), DGtal::Z2i::l2Metric, REQUIRE(), and SECTION().