DGtal: viewDualSurface.cpp File Reference
viewDualSurface.cpp File Reference
DGtal Examples
#include <iostream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "ConfigExamples.h"
#include "DGtal/io/viewers/PolyscopeViewer.h"
Data Structures
struct LessThanOnFace< Vector >
struct ConfigPointPredicate< Vector >
Functions
template<typename Vector>
Vector wedge (const Vector &v1, const Vector &v2)
template<typename Vector>
void naiveConvexHull (std::vector< std::vector< unsigned int > > &indices, const std::vector< Vector > &points, bool left_handed)
double rescale (double x)
template<typename Viewer, typename Vector>
void viewPolygons (Viewer &viewer, const std::vector< std::vector< unsigned int > > &indices, const std::vector< Vector > &points)
template<typename Vector>
unsigned int dim (const Vector &z)
template<typename Vector>
unsigned int openDim (const Vector &z)
template<typename Vector>
Vector lower (const Vector &z, unsigned int k)
template<typename Vector>
Vector upper (const Vector &z, unsigned int k)
template<typename Vector>
unsigned int nbLighted (std::map< Vector, bool > &f, const Vector &z)
template<typename Vector>
bool lightBetween (std::map< Vector, bool > &f, const Vector &z)
template<typename Vector>
bool lightMax (std::map< Vector, bool > &f, const Vector &z)
template<typename Vector>
bool lightMinMax (std::map< Vector, bool > &f, const Vector &z)
template<typename Vector>
bool lightMaxMin (std::map< Vector, bool > &f, const Vector &z)
template<typename Vector>
bool lightEpsilon (std::map< Vector, bool > &f, const Vector &z, unsigned int epsilon)
template<typename Vector>
void fillCfg (std::map< Vector, bool > &f, const Vector &z, unsigned int cfg)
template<typename Vector>
void localDualVolume (std::vector< Vector > &points, std::map< Vector, bool > &f, const Vector &z)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Date
2011/03/25
An example file named viewDualSurface.
This file is part of the DGtal library.
Definition in file viewDualSurface.cpp.
Function Documentation
dim()
template<typename Vector> unsigned int dim (const Vector & z)
Definition at line 173 of file viewDualSurface.cpp.
{
  unsigned int d = 0;
  for ( unsigned int i = 0; i < Vector::dimension; ++i )
    if ( ( z[ i ] % 2 ) == 1 ) ++d;
  return d;
}
References DGtal::PointVector< dim, Integer >::dimension.
fillCfg()
template<typename Vector> void fillCfg (std::map< Vector, bool > & f, const Vector & z, unsigned int cfg)
Examples
io/viewDualSurface.cpp.
Definition at line 336 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 )
    {
      f[ z ] = (cfg == 1);
      //std::cerr << "f[" << z << "] = " << f[ z ] << std::endl;
    }
  else
    {
      unsigned n = 1 << ( d - 1 );
      unsigned int cfgLow = 0;
      unsigned int cfgUp  = 0;
      for ( unsigned int j = 0; j < n; ++j )
        {
          cfgLow += ( cfg & 1 ) << j;
          cfg >>= 1;
          cfgUp += ( cfg & 1 ) << j;
          cfg >>= 1;
        }
      unsigned int i = openDim( z );
      fillCfg( f, lower( z, i ), cfgLow );
      fillCfg( f, upper( z, i ), cfgUp );
    }
}
References dim, fillCfg(), lower(), openDim(), and upper().
Referenced by fillCfg(), and main().
lightBetween()
template<typename Vector> bool lightBetween (std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 217 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ];
  else if ( d == 1 )
    {
      unsigned int i = openDim( z );
      return f[ lower( z, i ) ] || f[ upper( z, i ) ];
    }
  else
    {
      Vector v1, v2;
      for ( unsigned int i = 0; i < Vector::dimension; ++i )
        {
          v1[ i ] = ( ( z[ i ] % 2 ) == 1 ) ? z[ i ] - 1 : z[ i ];
          v2[ i ] = ( ( z[ i ] % 2 ) == 1 ) ? z[ i ] + 1 : z[ i ];
        }
      Domain domain( v1, v2 );
      for ( Domain::ConstIterator it = domain.begin(), itE = domain.end();
            it != itE; ++it )
        {
          if ( *it == z ) break;
          Point zp = z*2 - *it;
          // std::cerr << *it << " <--> " << zp << std::endl;
          if ( lightBetween( f, *it ) && lightBetween( f, zp ) )
            return true;
        }
      return false;
    }
}
References dim, DGtal::PointVector< dim, Integer >::dimension, domain, lightBetween(), lower(), openDim(), and upper().
Referenced by lightBetween(), and main().
lightEpsilon()
template<typename Vector> bool lightEpsilon (std::map< Vector, bool > & f, const Vector & z, unsigned int epsilon)
Examples
io/viewDualSurface.cpp.
Definition at line 308 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ];
  else
    {
      Vector tmp( z );
      bool eps_d = ( ( epsilon >> (d-1)) & 1 ) != 0;
      bool val = eps_d ? true : false;
      for ( unsigned i = 0; i < d; ++i )
        {
          unsigned int k = openDim( tmp );
          tmp = lower( tmp, k );
          if ( eps_d )
            val = val && ( lightEpsilon( f, lower( z, k ), epsilon )
                           || lightEpsilon( f, upper( z, k ), epsilon ) );
          else
            val = val || ( lightEpsilon( f, lower( z, k ), epsilon )
                           && lightEpsilon( f, upper( z, k ), epsilon ) );
        }
      return val;
    }
}
References dim, lightEpsilon(), lower(), openDim(), and upper().
Referenced by lightEpsilon().
lightMax()
template<typename Vector> bool lightMax (std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 252 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ];
  else if ( d == 1 )
    {
      unsigned int i = openDim( z );
      return f[ lower( z, i ) ] || f[ upper( z, i ) ];
    }
  else // if ( d > 1 )
    {
      unsigned int n = nbLighted( f, z );
      return n >= 2;
    }
}
References dim, lower(), nbLighted(), openDim(), and upper().
lightMaxMin()
template<typename Vector> bool lightMaxMin (std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 288 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ];
  else
    {
      Vector tmp( z );
      bool val = false;
      for ( unsigned i = 0; i < d; ++i )
        {
          unsigned int k = openDim( tmp );
          tmp = lower( tmp, k );
          val = val || ( lightMaxMin( f, lower( z, k ) ) && lightMaxMin( f, upper( z, k ) ) );
        }
      return val;
    }
}
References dim, lightMaxMin(), lower(), openDim(), and upper().
Referenced by lightMaxMin().
lightMinMax()
template<typename Vector> bool lightMinMax (std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 269 of file viewDualSurface.cpp.
{
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ];
  else
    {
      Vector tmp( z );
      bool val = true;
      for ( unsigned i = 0; i < d; ++i )
        {
          unsigned int k = openDim( tmp );
          tmp = lower( tmp, k );
          val = val && ( lightMinMax( f, lower( z, k ) ) || lightMinMax( f, upper( z, k ) ) );
        }
      return val;
    }
}
References dim, lightMinMax(), lower(), openDim(), and upper().
Referenced by lightMinMax().
localDualVolume()
template<typename Vector> void localDualVolume (std::vector< Vector > & points, std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 365 of file viewDualSurface.cpp.
{
  points.clear();
  Z3i::Domain domain( z, z + Vector::diagonal(1) );
  for ( Z3i::Domain::ConstIterator it = domain.begin(), itE = domain.end();
        it != itE; ++it )
    {
      if ( f[ *it ] ) points.push_back( *it );
    }
}
References DGtal::PointVector< dim, Integer >::diagonal(), and domain.
Referenced by main().
lower()
template<typename Vector> Vector lower (const Vector & z, unsigned int k)
Examples
geometry/volumes/distance/voronoimap2D.cpp, and io/viewDualSurface.cpp.
Definition at line 189 of file viewDualSurface.cpp.
{
  Vector z2( z );
  --z2[ k ];
  return z2;
}
Referenced by DGtal::ExactPredicateLpPowerSeparableMetric< Space, 2 >::binarySearchHidden(), DGtal::ExactPredicateLpPowerSeparableMetric< TSpace, 2, TPromoted >::binarySearchHidden(), DGtal::ExactPredicateLpSeparableMetric< TSpace, 2, TRawValue >::binarySearchHidden(), DGtal::ExactPredicateLpSeparableMetric< TSpace, p, RawValue >::binarySearchHidden(), DGtal::InexactPredicateLpSeparableMetric< TSpace, TValue >::binarySearchHidden(), DGtal::SeparableMetricAdapter< TMetric >::binarySearchHidden(), DGtal::concepts::CDigitalSetArchetype< TDomain >::computeBoundingBox(), DGtal::DigitalSetByAssociativeContainer< Domain, std::unordered_set< typename Domain::Point > >::computeBoundingBox(), DGtal::DigitalSetBySTLSet< Domain, Compare >::computeBoundingBox(), DGtal::DigitalSetBySTLVector< Domain >::computeBoundingBox(), DGtal::DigitalSetFromMap< Image >::computeBoundingBox(), fillCfg(), DGtal::HyperRectDomain_Iterator< Point >::HyperRectDomain_Iterator(), DGtal::HyperRectDomain_subIterator< Point >::HyperRectDomain_subIterator(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::KhalimskySpaceND(), lightBetween(), lightEpsilon(), lightMax(), lightMaxMin(), lightMinMax(), main(), nbLighted(), DGtal::KhalimskyPreSpaceND< 2, Integer >::sNext(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::sNext(), DGtal::KhalimskyPreSpaceND< 2, Integer >::uNext(), and DGtal::KhalimskySpaceND< dimAmbient, TInteger >::uNext().
main()
int main (int argc, char ** argv)
Definition at line 391 of file viewDualSurface.cpp.
{
  typedef KSpace::CellSet CellSet;
  KSpace KS;
  PolyscopeViewer<Z3i::Space,Z3i::KSpace> viewer(KS);
  viewer.allowReuseList = true;
  DGtal::Color fillColor( 200, 200, 220, 255 );
  DGtal::Color surfelColor( 255, 0, 0, 150 );
  DGtal::Color voxelColor( 150, 150, 0, 150 );
  // Create lists for display:
  // List will inherit current parameters of viewer
  viewer << surfelColor;
  std::string surfels = viewer.newQuadList("Surfels");
  viewer << voxelColor;
  std::string polys = viewer.newPolygonList("Polygons");
  std::vector<Vector> pts;
  unsigned int cfg = argc > 1 ? atoi( argv[1] ) : 0;
  unsigned int cfg2 = argc > 2 ? atoi( argv[2] ) : 255;
  std::map< Vector, bool > f;
  for ( unsigned int y = 0; (y < 16) && (cfg <= cfg2); ++y )
    for ( unsigned int x = 0; (x < 16) && (cfg <= cfg2); ++x, ++cfg )
      {
        Vector offset( x*6, y*6, 0 );
        fillCfg( f, offset + Vector( 1, 1, 1 ), cfg );
        Domain domain( offset + Vector( 0, 0, 0), offset + Vector( 2, 2, 2 ) );
        KSpace K;
        K.init( Vector( 0, 0, 0), Vector( 2, 2, 2 ), true );
        ConfigPointPredicate<Vector> cpp( f, offset );
        CellSet aBoundary;
        Surfaces<KSpace>::uMakeBoundary( aBoundary, K, cpp, Vector( 0, 0, 0), Vector( 1, 1, 1 ) );
        viewer.setCurrentList(surfels);
        for ( CellSet::const_iterator it = aBoundary.begin(), itE = aBoundary.end();
              it != itE; ++it )
          {
            viewer << surfelColor;
            viewer << KS.uTranslation( *it, offset/2 );
          }
        for ( Domain::ConstIterator it = domain.begin(), itE = domain.end();
              it != itE; ++it )
          {
            // lightEpsilon( f, *it, 5 ); // {1,-1,1}=5 // interesting
            f[ *it ] = lightBetween( f, *it );
          }
        viewer << fillColor;
        std::vector< std::vector< unsigned int > > indices;
        Domain domain2( offset + Vector( 0, 0, 0), offset + Vector( 1, 1, 1 ) );
        viewer.setCurrentList(polys);
        for ( Domain::ConstIterator it = domain.begin(), itE = domain.end();
              it != itE; ++it )
          {
            localDualVolume( pts, f, *it );
            indices.clear();
            naiveConvexHull( indices, pts, false ); // right_handed
            viewPolygons( viewer, indices, pts );
          }
      }
  viewer.show();
  return 0;
}
References DGtal::Display3D< Space, KSpace >::allowReuseList, domain, fillCfg(), K, lightBetween(), localDualVolume(), naiveConvexHull(), DGtal::Display3D< Space, KSpace >::newPolygonList(), DGtal::Display3D< Space, KSpace >::newQuadList(), DGtal::Display3D< Space, KSpace >::setCurrentList(), DGtal::PolyscopeViewer< Space, KSpace >::show(), DGtal::Surfaces< TKSpace >::uMakeBoundary(), DGtal::KhalimskySpaceND< dim, TInteger >::uTranslation(), and viewPolygons().
naiveConvexHull()
template<typename Vector> void naiveConvexHull (std::vector< std::vector< unsigned int > > & indices, const std::vector< Vector > & points, bool left_handed)
Examples
io/viewDualSurface.cpp.
Definition at line 80 of file viewDualSurface.cpp.
{
  typedef typename Vector::Component Scalar;
  // Checks all triplets of points.
  std::vector< unsigned int > aFace;
  for ( unsigned int i1 = 0; i1 < points.size(); ++i1 )
    for ( unsigned int i2 = 0; i2 < points.size(); ++i2 )
      if ( i1 != i2 )
        for ( unsigned int i3 = i1 > i2 ? i1+1 : i2+1; i3 < points.size(); ++i3 )
          {
            Vector P12 = points[ i2 ] - points[ i1 ];
            Vector P13 = points[ i3 ] - points[ i1 ];
            Vector N = wedge( P12, P13 );
            if ( N == Vector::zero ) continue;
            unsigned int nbBadPos = 0;
            for ( unsigned int i4 = 0; i4 < points.size(); ++i4 )
              {
                Vector P14 = points[ i4 ] - points[ i1 ];
                Scalar c = N.dot( P14 );
                if ( c == 0 ) aFace.push_back( i4 );
                else if ( ( left_handed && ( c > 0 ) )
                          || ( ! left_handed && ( c < 0 ) ) )
                  ++nbBadPos;
              }
            if ( nbBadPos == 0 )
              {
                LessThanOnFace<Vector> LTOF( N, points[ aFace[ 0 ] ], points );
                std::sort( ++aFace.begin(), aFace.end(), LTOF );
                indices.push_back( aFace );
              }
            aFace.clear();
          }
  // purge faces.
  for ( unsigned int i = 0; i < indices.size(); ++i )
    {
      auto s = indices[ i ].size();
      for ( unsigned int j = i+1; j < indices.size(); )
        {
          if ( indices[ j ].size() == s )
            {
              bool equal = true;
              for ( unsigned int k = 0; equal && ( k < s ); ++k )
                if ( indices[ i ][ k ] != indices[ j ][ k ] )
                  equal = false;
              if ( equal )
                {
                  std::swap( indices[ j ], indices.back() );
                  indices.pop_back();
                }
              else
                ++j;
            }
          else ++j;
        }
    }
}
References wedge(), and DGtal::PointVector< dim, Integer >::zero.
Referenced by main().
nbLighted()
template<typename Vector> unsigned int nbLighted (std::map< Vector, bool > & f, const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 204 of file viewDualSurface.cpp.
{ // z of dim >=2
  unsigned int d = dim( z );
  if ( d == 0 ) return f[ z ] ? 1 : 0;
  unsigned int i = openDim( z );
  return nbLighted( f, lower( z, i ) )
    + nbLighted( f, upper( z, i ) );
}
References dim, lower(), nbLighted(), openDim(), and upper().
Referenced by lightMax(), and nbLighted().
openDim()
template<typename Vector> unsigned int openDim (const Vector & z)
Examples
io/viewDualSurface.cpp.
Definition at line 182 of file viewDualSurface.cpp.
{
  for ( unsigned int i = 0; i < Vector::dimension; ++i )
    if ( ( z[ i ] % 2 ) == 1 ) return i;
  return Vector::dimension;
}
References DGtal::PointVector< dim, Integer >::dimension.
Referenced by fillCfg(), lightBetween(), lightEpsilon(), lightMax(), lightMaxMin(), lightMinMax(), and nbLighted().
rescale()
double rescale (double x)
Examples
io/viewDualSurface.cpp.
Definition at line 140 of file viewDualSurface.cpp.
{
  return ( x - 1.0 ) * 0.5 + 0.5;
}
Referenced by viewPolygons().
upper()
template<typename Vector> Vector upper (const Vector & z, unsigned int k)
Examples
geometry/volumes/distance/voronoimap2D.cpp, and io/viewDualSurface.cpp.
Definition at line 196 of file viewDualSurface.cpp.
{
  Vector z2( z );
  ++z2[ k ];
  return z2;
}
Referenced by DGtal::ExactPredicateLpPowerSeparableMetric< Space, 2 >::binarySearchHidden(), DGtal::ExactPredicateLpPowerSeparableMetric< TSpace, 2, TPromoted >::binarySearchHidden(), DGtal::ExactPredicateLpSeparableMetric< TSpace, 2, TRawValue >::binarySearchHidden(), DGtal::ExactPredicateLpSeparableMetric< TSpace, p, RawValue >::binarySearchHidden(), DGtal::InexactPredicateLpSeparableMetric< TSpace, TValue >::binarySearchHidden(), DGtal::SeparableMetricAdapter< TMetric >::binarySearchHidden(), DGtal::concepts::CDigitalSetArchetype< TDomain >::computeBoundingBox(), DGtal::DigitalSetByAssociativeContainer< Domain, std::unordered_set< typename Domain::Point > >::computeBoundingBox(), DGtal::DigitalSetBySTLSet< Domain, Compare >::computeBoundingBox(), DGtal::DigitalSetBySTLVector< Domain >::computeBoundingBox(), DGtal::DigitalSetFromMap< Image >::computeBoundingBox(), fillCfg(), DGtal::HyperRectDomain_Iterator< Point >::HyperRectDomain_Iterator(), DGtal::HyperRectDomain_subIterator< Point >::HyperRectDomain_subIterator(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::init(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::KhalimskySpaceND(), lightBetween(), lightEpsilon(), lightMax(), lightMaxMin(), lightMinMax(), main(), nbLighted(), DGtal::KhalimskyPreSpaceND< 2, Integer >::sNext(), DGtal::KhalimskySpaceND< dimAmbient, TInteger >::sNext(), DGtal::KhalimskyPreSpaceND< 2, Integer >::uNext(), and DGtal::KhalimskySpaceND< dimAmbient, TInteger >::uNext().
viewPolygons()
template<typename Viewer, typename Vector> void viewPolygons (Viewer & viewer, const std::vector< std::vector< unsigned int > > & indices, const std::vector< Vector > & points)
Examples
io/viewDualSurface.cpp.
Definition at line 147 of file viewDualSurface.cpp.
{
  typedef typename Viewer::RealPoint RealPoint;
  std::vector<RealPoint> pts3d;
  for ( unsigned int f = 0; f < indices.size(); ++f )
    {
      pts3d.clear();
      RealPoint P;
      for ( unsigned int v = 0; v < indices[ f ].size(); ++v )
        {
          unsigned int i = indices[ f ][ v ];
          P[0] = rescale( points[ i ][ 0 ] );
          P[1] = rescale( points[ i ][ 1 ] );
          P[2] = rescale( points[ i ][ 2 ] );
          pts3d.push_back( P );
        }
      viewer.drawPolygon( pts3d );
    }
}
References DGtal::Display3D< Space, KSpace >::drawPolygon(), and rescale().
Referenced by main().
wedge()
template<typename Vector> Vector wedge (const Vector & v1, const Vector & v2)
Examples
io/viewDualSurface.cpp.
Definition at line 54 of file viewDualSurface.cpp.
{
  return Vector( v1[ 1 ] * v2[ 2 ] - v1[ 2 ] * v2[ 1 ],
                 v1[ 2 ] * v2[ 0 ] - v1[ 0 ] * v2[ 2 ],
                 v1[ 0 ] * v2[ 1 ] - v1[ 1 ] * v2[ 0 ] );
}
Referenced by naiveConvexHull(), and LessThanOnFace< Vector >::operator()().