DGtal: viewer3D-10-interaction.cpp File Reference
viewer3D-10-interaction.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/viewers/PolyscopeViewer.h"
Data Structures
struct MyCallback
Typedefs
typedef PolyscopeViewer< Space, KSpace > MyViewer
typedef MyViewer::Callback Callback
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Bertrand Kerautret (bertr.nosp@m.and..nosp@m.kerau.nosp@m.tret.nosp@m.@lori.nosp@m.a.fr) LORIA (CNRS, UMR 7503), University of Lorraine, France
Date
2014/10/12
Simple example of class PolyscopeViewer.
This file is part of the DGtal library.
Definition in file viewer3D-10-interaction.cpp.
Typedef Documentation
Callback
typedef MyViewer::Callback Callback
Examples
io/viewers/viewer3D-10-interaction.cpp.
Definition at line 65 of file viewer3D-10-interaction.cpp.
MyViewer
typedef PolyscopeViewer<Space,KSpace> MyViewer
Examples
io/viewers/viewer3D-10-interaction.cpp, topology/3dBorderExtraction.cpp, topology/ctopo-1-3d.cpp, topology/ctopo-1s-3d.cpp, topology/ctopo-2-3d.cpp, and topology/cubical-complex-collapse.cpp.
Definition at line 64 of file viewer3D-10-interaction.cpp.
Function Documentation
main()
int main (void)
Definition at line 82 of file viewer3D-10-interaction.cpp.
{
  Point p1( 0, 0, 0 );
  Point p2( 5, 5 ,5 );
  Point p3( 2, 3, 4 );
  KSpace K;
  K.init( p1, p2, true );
  Point v1 = Z3i::Point(10, 10,10);
  Point v2 = Z3i::Point(9, 9, 9);
  Point v3 = Z3i::Point(11, 11,11);
  MyViewer viewer( K );
  viewer.setCallback(new MyCallback);
  Z3i::SCell surfel1 = K.sCell( Point( 1, 1, 2 ), KSpace::POS );
  Z3i::SCell surfel2 = K.sCell( Point( 3, 3, 4 ), KSpace::NEG );
  Z3i::SCell surfel3 = K.sCell( Point( 5, 6, 5 ), KSpace::POS );
  viewer.draw(surfel1, "Surfel 1");
  viewer.draw(surfel2, "Surfel 2");
  viewer << Point(0, 0, 1) << Point(1, 1, 2);
  viewer.show();
  return 0;
}
References DGtal::Display3D< Space, KSpace >::draw(), K, DGtal::KhalimskySpaceND< 3, Integer >::NEG, DGtal::KhalimskySpaceND< 3, Integer >::POS, DGtal::PolyscopeViewer< Space, KSpace >::setCallback(), and DGtal::PolyscopeViewer< Space, KSpace >::show().