DGtal: DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node Class Reference
DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node Class Reference
#include <DGtal/images/ImageContainerByHashTree.h>
Public Member Functions
Node (Value aValue, HashKey key)
Node * getNext ()
void setNext (Node *next)
HashKey getKey ()
Value & getObject ()
~Node ()
Protected Attributes
HashKey myKey
Node * myNext
Value myData
Detailed Description
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t>
class DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node
An internal class that corresponds to a node of a linked list (as the hashTable points to linked lists to handle collisions). Each element in the container is placed in a Node.
Definition at line 621 of file ImageContainerByHashTree.h.
Constructor & Destructor Documentation
Node()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node (Value aValue, HashKey key) inline
Construtctor: create pair (aValue, key)
Parameters
aValue First value
key key in the hashtree
Definition at line 631 of file ImageContainerByHashTree.h.
      {
        myData = aValue;
        myKey = key;
      }
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey.
~Node()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::~Node () inline
Definition at line 673 of file ImageContainerByHashTree.h.
{ }
Member Function Documentation
getKey()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey () inline
Returns
the key associated to a Node.
Definition at line 660 of file ImageContainerByHashTree.h.
      {
        return myKey;
      }
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode().
getNext()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> Node * DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext () inline
Returns
the next pair (aValue, key) in the list.
Definition at line 640 of file ImageContainerByHashTree.h.
      {
        return myNext;
      }
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode().
getObject()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> Value & DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject () inline
Returns
the object (aValue) associated to a Node.
Definition at line 669 of file ImageContainerByHashTree.h.
      {
        return myData;
      }
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator*().
setNext()
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> void DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext (Node * next) inline
Insert the pair (value,key) next in the node list
Parameters
next a pointer to a pair (value,key) (Node).
Definition at line 651 of file ImageContainerByHashTree.h.
      {
        myNext = next;
      }
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext.
Field Documentation
myData
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> Value DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData protected
Definition at line 677 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node().
myKey
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey protected
Definition at line 675 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node().
myNext
template<typename TDomain , typename TValue , typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext protected
Definition at line 676 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext().
The documentation for this class was generated from the following file:
ImageContainerByHashTree.h