DGtal: dgtalCalculus-poisson.cpp File Reference
dgtalCalculus-poisson.cpp File Reference
DGtal Examples
#include <iostream>
#include <DGtal/base/Common.h>
#include <DGtal/helpers/StdDefs.h>
#include <DGtal/helpers/Shortcuts.h>
#include <DGtal/helpers/ShortcutsGeometry.h>
#include <DGtal/shapes/SurfaceMesh.h>
#include <DGtal/geometry/surfaces/DigitalSurfaceRegularization.h>
#include <DGtal/dec/PolygonalCalculus.h>
#include <DGtal/math/linalg/DirichletConditions.h>
#include <polyscope/polyscope.h>
#include <polyscope/surface_mesh.h>
#include <polyscope/point_cloud.h>
#include <Eigen/Dense>
#include <Eigen/Sparse>
Typedefs
typedef Shortcuts< Z3i::KSpace > SH3
typedef ShortcutsGeometry< Z3i::KSpace > SHG3
typedef SurfaceMesh< RealPoint, RealVector > SurfMesh
typedef std::size_t Index
Functions
void computeLaplace ()
void myCallback ()
int main ()
Variables
polyscope::SurfaceMesh * psMesh
SurfMesh surfmesh
float scale = 0.1
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2021/09/02
This file is part of the DGtal library.
Definition in file dgtalCalculus-poisson.cpp.
Typedef Documentation
Index
typedef std::size_t Index
Definition at line 52 of file dgtalCalculus-poisson.cpp.
SH3
typedef Shortcuts<Z3i::KSpace> SH3
Definition at line 48 of file dgtalCalculus-poisson.cpp.
SHG3
typedef ShortcutsGeometry<Z3i::KSpace> SHG3
Definition at line 49 of file dgtalCalculus-poisson.cpp.
SurfMesh
typedef SurfaceMesh< RealPoint, RealVector > SurfMesh
Definition at line 51 of file dgtalCalculus-poisson.cpp.
Function Documentation
computeLaplace()
void computeLaplace ()
[PolyDEC-init]
[PolyDEC-init]
Definition at line 58 of file dgtalCalculus-poisson.cpp.
{
  typedef PolygonalCalculus<SH3::RealPoint,SH3::RealVector> PolyDEC;
  typedef DirichletConditions< EigenLinearAlgebraBackend >  DC;
  PolyDEC calculus(surfmesh);
  PolyDEC::SparseMatrix L = calculus.globalLaplaceBeltrami();
  PolyDEC::Form g = calculus.form0();
  DC::IntegerVector b = DC::IntegerVector::Zero( g.rows() );
  //We set values on the boundary
  auto boundaryEdges = surfmesh.computeManifoldBoundaryEdges();
  std::cout<< "Number of boundary edges= "<<boundaryEdges.size()<<std::endl;
  auto pihVertex=[&](const SurfMesh::Vertex &v){return  cos(scale*(surfmesh.position(v)[0]))*(scale*surfmesh.position(v)[1]);};
  for(auto &e: boundaryEdges)
  {
    auto adjVertices = surfmesh.edgeVertices(e);
    g(adjVertices.first)  = pihVertex(adjVertices.first);
    g(adjVertices.second) = pihVertex(adjVertices.second);
    b(adjVertices.first)  = 1;
    b(adjVertices.second) = 1;
  }
  // Solve Δu=0 with g as boundary conditions
  PolyDEC::Solver solver;
  PolyDEC::SparseMatrix L_dirichlet = DC::dirichletOperator( L, b );
  solver.compute( L_dirichlet );
  ASSERT(solver.info()==Eigen::Success);
  PolyDEC::Form g_dirichlet = DC::dirichletVector( L, g, b, g );
  PolyDEC::Form x_dirichlet = solver.solve( g_dirichlet );
  PolyDEC::Form u = DC::dirichletSolution( x_dirichlet, b, g );
  psMesh->addVertexScalarQuantity("g", g);
  psMesh->addVertexScalarQuantity("u", u);
}
References calculus, DGtal::SurfaceMesh< TRealPoint, TRealVector >::computeManifoldBoundaryEdges(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::edgeVertices(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::form0(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::globalLaplaceBeltrami(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::position(), psMesh, and surfmesh.
Referenced by myCallback().
main()
int main (void)
Definition at line 104 of file dgtalCalculus-poisson.cpp.
{
  auto params = SH3::defaultParameters() | SHG3::defaultParameters() |  SHG3::parametersGeometryEstimation();
  auto h=.7   ; //gridstep
  params( "polynomial", "0.1*y*y -0.1*x*x - 2.0*z" )( "gridstep", h );
  auto implicit_shape  = SH3::makeImplicitShape3D  ( params );
  auto digitized_shape = SH3::makeDigitizedImplicitShape3D( implicit_shape, params );
  auto K               = SH3::getKSpace( params );
  auto binary_image    = SH3::makeBinaryImage( digitized_shape, params );
  auto surface         = SH3::makeDigitalSurface( binary_image, K, params );
  auto primalSurface   = SH3::makePrimalSurfaceMesh(surface);
  //Need to convert the faces
  std::vector<std::vector<SH3::SurfaceMesh::Vertex>> faces;
  std::vector<RealPoint> positions = primalSurface->positions();
  for(auto face= 0 ; face < primalSurface->nbFaces(); ++face)
    faces.push_back(primalSurface->incidentVertices( face ));
  surfmesh = SurfMesh(positions.begin(),
                      positions.end(),
                      faces.begin(),
                      faces.end());
  psMesh = polyscope::registerSurfaceMesh("digital surface", positions, faces);
  // Initialize polyscope
  polyscope::init();
  // Set the callback function
  polyscope::state::userCallback = myCallback;
  polyscope::show();
  return EXIT_SUCCESS;
}
References binary_image, DGtal::Shortcuts< TKSpace >::defaultParameters(), DGtal::ShortcutsGeometry< TKSpace >::defaultParameters(), DGtal::Shortcuts< TKSpace >::getKSpace(), K, DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeDigitalSurface(), DGtal::Shortcuts< TKSpace >::makeDigitizedImplicitShape3D(), DGtal::Shortcuts< TKSpace >::makeImplicitShape3D(), DGtal::Shortcuts< TKSpace >::makePrimalSurfaceMesh(), myCallback(), DGtal::ShortcutsGeometry< TKSpace >::parametersGeometryEstimation(), psMesh, surface, and surfmesh.
myCallback()
void myCallback ()
Definition at line 97 of file dgtalCalculus-poisson.cpp.
{
  ImGui::SliderFloat("Phi scale", &scale, 0., 10.);
  if(ImGui::Button("Compute Laplace problem"))
    computeLaplace();
}
References computeLaplace().
Referenced by main().
Variable Documentation
psMesh
polyscope::SurfaceMesh* psMesh
Definition at line 54 of file dgtalCalculus-poisson.cpp.
Referenced by computeLaplace(), and main().
scale
float scale = 0.1
Definition at line 56 of file dgtalCalculus-poisson.cpp.
surfmesh
SurfMesh surfmesh
Definition at line 55 of file dgtalCalculus-poisson.cpp.
Referenced by computeLaplace(), and main().