DGtal: dgtalCalculus-single.cpp File Reference
dgtalCalculus-single.cpp File Reference
DGtal Examples
#include <iostream>
#include <DGtal/base/Common.h>
#include <DGtal/helpers/StdDefs.h>
#include <DGtal/helpers/Shortcuts.h>
#include <DGtal/helpers/ShortcutsGeometry.h>
#include <DGtal/shapes/SurfaceMesh.h>
#include <DGtal/geometry/surfaces/DigitalSurfaceRegularization.h>
#include <DGtal/dec/PolygonalCalculus.h>
#include <polyscope/polyscope.h>
#include <polyscope/surface_mesh.h>
#include <polyscope/point_cloud.h>
#include <polyscope/curve_network.h>
#include <Eigen/Dense>
#include <Eigen/Sparse>
Typedefs
typedef Shortcuts< Z3i::KSpace > SH3
typedef ShortcutsGeometry< Z3i::KSpace > SHG3
typedef SurfaceMesh< RealPoint, RealVector > SurfMesh
typedef SurfMesh::Vertices Vertices
typedef SurfMesh::RealPoint RealPoint
typedef SurfMesh::Face Face
typedef SurfMesh::Vertex Vertex
Functions
void initPhi ()
void initQuantities ()
int main ()
Variables
polyscope::SurfaceMesh * psMesh
polyscope::PointCloud * psVertices
polyscope::CurveNetwork * psBoundary
SurfMesh surfmesh
PolygonalCalculus< SH3::RealPoint, SH3::RealVector >::Vector phiEigen
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2021/09/02
This file is part of the DGtal library.
Definition in file dgtalCalculus-single.cpp.
Typedef Documentation
Face
typedef SurfMesh::Face Face
Definition at line 53 of file dgtalCalculus-single.cpp.
RealPoint
typedef SurfMesh::RealPoint RealPoint
Definition at line 52 of file dgtalCalculus-single.cpp.
SH3
typedef Shortcuts<Z3i::KSpace> SH3
Definition at line 47 of file dgtalCalculus-single.cpp.
SHG3
typedef ShortcutsGeometry<Z3i::KSpace> SHG3
Definition at line 48 of file dgtalCalculus-single.cpp.
SurfMesh
typedef SurfaceMesh< RealPoint, RealVector > SurfMesh
Definition at line 50 of file dgtalCalculus-single.cpp.
Vertex
typedef SurfMesh::Vertex Vertex
Definition at line 54 of file dgtalCalculus-single.cpp.
Vertices
typedef SurfMesh::Vertices Vertices
Definition at line 51 of file dgtalCalculus-single.cpp.
Function Documentation
initPhi()
void initPhi ()
Definition at line 65 of file dgtalCalculus-single.cpp.
{
  phiEigen.resize(5);
  phiEigen << 1.0, 2.0, 0.0, 5.0 ,1.5;
  psMesh->addVertexScalarQuantity("Phi", phiEigen);
  psVertices->addScalarQuantity("Phi", phiEigen);
}
References phiEigen, psMesh, and psVertices.
Referenced by main().
initQuantities()
void initQuantities ()
Definition at line 74 of file dgtalCalculus-single.cpp.
{
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector> calculus(surfmesh);
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector> gradients;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector> cogradients;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Real3dPoint> normals;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Real3dPoint> vectorArea;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Real3dPoint> centroids;
  std::vector<double> faceArea;
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Face f = 0; //Id of the face
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector grad = calculus.gradient(f) * phiEigen;
  gradients.push_back( grad );
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector cograd =  calculus.coGradient(f) * phiEigen;
  cogradients.push_back( cograd );
  normals.push_back(calculus.faceNormalAsDGtalVector(f));
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector vA = calculus.vectorArea(f);
  vectorArea.push_back({vA(0) , vA(1), vA(2)});
  faceArea.push_back( calculus.faceArea(f));
  centroids.push_back( calculus.centroidAsDGtalPoint(f) );
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector dPhi = calculus.D(f)*phiEigen;
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector av = calculus.A(f)*phiEigen;
  psMesh->addFaceVectorQuantity("Gradients", gradients);
  psMesh->addFaceVectorQuantity("co-Gradients", cogradients);
  psMesh->addFaceVectorQuantity("Normals", normals);
  psMesh->addFaceScalarQuantity("Face area", faceArea);
  psMesh->addFaceVectorQuantity("Vector area", vectorArea);
  psBoundary->addEdgeScalarQuantity("d0*phi", dPhi);
  psBoundary->addEdgeScalarQuantity("A*phi", av);
  //Face centroid
  polyscope::registerPointCloud("Centroids", centroids);
  //Flat Sharp
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector v(3);
  v << 50,-50,-100;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector> someV={v};
  psMesh->addFaceVectorQuantity("A vector", someV);
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector flat = calculus.flat(f)*v;
  psBoundary->addEdgeScalarQuantity("flat (1-form)", flat);
  PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector sharp = calculus.sharp(f)*flat;
  std::vector<PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector> sharpRes={sharp};
  psMesh->addFaceVectorQuantity("Sharp", sharpRes);
}
References DGtal::PolygonalCalculus< TRealPoint, TRealVector >::A(), calculus, DGtal::PolygonalCalculus< TRealPoint, TRealVector >::centroidAsDGtalPoint(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::coGradient(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::D(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::faceArea(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::faceNormalAsDGtalVector(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::flat(), DGtal::PolygonalCalculus< TRealPoint, TRealVector >::gradient(), phiEigen, psBoundary, psMesh, DGtal::PolygonalCalculus< TRealPoint, TRealVector >::sharp(), surfmesh, and DGtal::PolygonalCalculus< TRealPoint, TRealVector >::vectorArea().
Referenced by main().
main()
int main (void)
Definition at line 130 of file dgtalCalculus-single.cpp.
{
  std::vector<RealPoint> positions={ {0,0,0},{20,0,0}, {20,10,0}, {10,8,5}, {0,15,1} };
  std::vector<std::vector<size_t>> faces={ {0,1,2,3,4} };
  surfmesh = SurfMesh(positions.begin(),
                      positions.end(),
                      faces.begin(),
                      faces.end());
  psVertices = polyscope::registerPointCloud("Vertices", positions);
  std::vector<std::array<size_t,2>> edges={{0,1},{1,2},{2,3},{3,4},{4,0} };
  psBoundary = polyscope::registerCurveNetwork("Edges", positions, edges);
  // Initialize polyscope
  polyscope::init();
  psMesh = polyscope::registerSurfaceMesh("Single face", positions, faces);
  initPhi();
  initQuantities();
  polyscope::show();
  return EXIT_SUCCESS;
}
References initPhi(), initQuantities(), psBoundary, psMesh, psVertices, and surfmesh.
Variable Documentation
phiEigen
PolygonalCalculus<SH3::RealPoint,SH3::RealVector>::Vector phiEigen
Definition at line 63 of file dgtalCalculus-single.cpp.
Referenced by initPhi(), and initQuantities().
psBoundary
polyscope::CurveNetwork* psBoundary
Definition at line 60 of file dgtalCalculus-single.cpp.
Referenced by initQuantities(), and main().
psMesh
polyscope::SurfaceMesh* psMesh
Definition at line 58 of file dgtalCalculus-single.cpp.
Referenced by initPhi(), initQuantities(), and main().
psVertices
polyscope::PointCloud* psVertices
Definition at line 59 of file dgtalCalculus-single.cpp.
Referenced by initPhi(), and main().
surfmesh
SurfMesh surfmesh
Definition at line 62 of file dgtalCalculus-single.cpp.
Referenced by initQuantities(), and main().