DGtal: examplePointFunctorHolder.cpp File Reference
examplePointFunctorHolder.cpp File Reference
DGtal Examples
An example file for DGtal::functors::PointFunctorHolder.
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/kernel/PointFunctorHolder.h"
#include "DGtal/geometry/volumes/distance/DistanceTransformation.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include <boost/algorithm/minmax_element.hpp>
Functions
int main ()
Detailed Description
An example file for DGtal::functors::PointFunctorHolder.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Roland Denis (denis.nosp@m.@mat.nosp@m.h.uni.nosp@m.v-ly.nosp@m.on1.f.nosp@m.r) CNRS, Institut Camille Jordan (UMR 5208), Université Lyon 1, France
Date
2018/11/23
This file is part of the DGtal library.
Definition in file examplePointFunctorHolder.cpp.
Function Documentation
main()
int main (void)
[examplePointFunctorHolder-hold]
[examplePointFunctorHolder-hold]
[examplePointFunctorHolder-DT]
[examplePointFunctorHolder-DT]
[examplePointFunctorHolder-DTvis]
[examplePointFunctorHolder-DTvis]
Definition at line 52 of file examplePointFunctorHolder.cpp.
{
  auto mickey = functors::holdPointFunctor<Z2i::Point>(
    [] ( Z2i::Point const& pt ) {
      return
           (pt - Z2i::Point(0, -5)).norm() > 3
        && (    pt.norm() <= 20
             || (pt - Z2i::Point(-18,21)).norm() <= 10
             || (pt - Z2i::Point( 18,21)).norm() <= 10
           );
    });
  Z2i::Domain domain( Z2i::Point(-35,-25), Z2i::Point(35, 35) );
  using DTL2 = DistanceTransformation<Z2i::Space, decltype(mickey), Z2i::L2Metric>;
  DTL2 dt( domain, mickey, Z2i::l2Metric );
  DTL2::Value maxDT = *boost::first_max_element( dt.constRange().begin(), dt.constRange().end() );
  using HueTwice = HueShadeColorMap<DTL2::Value, 1>;
  Board2D aBoard;
  aBoard << domain;
  Display2DFactory::drawImage<HueTwice>(aBoard, dt, 0, maxDT);
  aBoard.saveEPS("examplePointFunctorHolder.eps");
  return 0;
}
References domain, DGtal::Display2DFactory::drawImage(), dt, DGtal::functors::holdPointFunctor(), DGtal::Z2i::l2Metric, DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm(), and LibBoard::Board::saveEPS().