DGtal: DGtal::Z2i Namespace Reference
DGtal::Z2i Namespace Reference
Z2i this namespace gathers the standard of types for 2D imagery.
Typedefs
typedef DGtal::int32_t Integer
typedef SpaceND< 2, Integer > Space
typedef Space Z2
typedef KhalimskySpaceND< 2, Integer > KSpace
typedef KSpace K2
typedef KSpace::Cell Cell
typedef KSpace::SCell SCell
typedef KSpace::Cells Cells
typedef KSpace::SCells SCells
typedef KhalimskyPreSpaceND< 2, Integer > KPreSpace
typedef KPreSpace KP2
typedef KPreSpace::Cell PreCell
typedef KPreSpace::SCell SPreCell
typedef KPreSpace::Cells PreCells
typedef KPreSpace::SCells SPreCells
typedef MetricAdjacency< Space, 1 > Adj4
typedef MetricAdjacency< Space, 2 > Adj8
typedef DigitalTopology< Adj4, Adj8 > DT4_8
typedef DigitalTopology< Adj8, Adj4 > DT8_4
typedef Space::Point Point
typedef Space::Vector Vector
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
typedef HyperRectDomain< Space > Domain
typedef DigitalSetSelector< Domain, BIG_DS+HIGH_BEL_DS >::Type DigitalSet
typedef Object< DT4_8, DigitalSet > Object4_8
typedef Object< DT4_8, DigitalSet >::ComplementObject ComplementObject4_8
typedef Object< DT4_8, DigitalSet >::SmallObject SmallObject4_8
typedef Object< DT4_8, DigitalSet >::SmallComplementObject SmallComplementObject4_8
typedef Object< DT8_4, DigitalSet > Object8_4
typedef Object< DT8_4, DigitalSet >::ComplementObject ComplementObject8_4
typedef Object< DT8_4, DigitalSet >::SmallObject SmallObject8_4
typedef Object< DT8_4, DigitalSet >::SmallComplementObject SmallComplementObject8_4
typedef GridCurve< K2 > Curve
typedef ExactPredicateLpSeparableMetric< Space, 2 > L2Metric
typedef ExactPredicateLpSeparableMetric< Space, 1 > L1Metric
typedef ExactPredicateLpPowerSeparableMetric< Space, 2 > L2PowerMetric
typedef ExactPredicateLpPowerSeparableMetric< Space, 1 > L1PowerMetric
Variables
static const Adj4 adj4
static const Adj8 adj8
static const DT4_8 dt4_8 = DT4_8(adj4, adj8, JORDAN_DT)
static const DT8_4 dt8_4 = DT8_4(adj8, adj4, JORDAN_DT)
static const L2Metric l2Metric
static const L1Metric l1Metric
static const L2PowerMetric l2PowerMetric
static const L1PowerMetric l1PowerMetric
Detailed Description
Z2i this namespace gathers the standard of types for 2D imagery.
This namespace gathers all standard type definitions as well as some static instances for using a 2D digital space with integers represented by 'int'. It is useful for a developer who wants to develop an application in the 2D plane and who does not wish to tune specifically the possible types.
This is the standard set of types for 2D imagery.
Todo
Once stabilized, provide a Z2l (for int64) and a Z2I (for arbitrary integers).
Typedef Documentation
Adj4
typedef MetricAdjacency< Space, 1> DGtal::Z2i::Adj4
Standard 4-neighborhood for a 2D digital space.
Definition at line 90 of file StdDefs.h.
Adj8
typedef MetricAdjacency< Space, 2> DGtal::Z2i::Adj8
Standard 8-neighborhood for a 2D digital space.
Definition at line 92 of file StdDefs.h.
Cell
typedef KSpace::Cell DGtal::Z2i::Cell
Definition at line 79 of file StdDefs.h.
Cells
typedef KSpace::Cells DGtal::Z2i::Cells
Definition at line 81 of file StdDefs.h.
ComplementObject4_8
typedef Object<DT4_8,DigitalSet>::ComplementObject DGtal::Z2i::ComplementObject4_8
Definition at line 102 of file StdDefs.h.
ComplementObject8_4
typedef Object<DT8_4,DigitalSet>::ComplementObject DGtal::Z2i::ComplementObject8_4
Definition at line 106 of file StdDefs.h.
Curve
typedef GridCurve<K2> DGtal::Z2i::Curve
Definition at line 116 of file StdDefs.h.
DigitalSet
typedef DigitalSetSelector<Domain,BIG_DS+HIGH_BEL_DS>::Type DGtal::Z2i::DigitalSet
Definition at line 100 of file StdDefs.h.
Domain
typedef HyperRectDomain< Space > DGtal::Z2i::Domain
Definition at line 99 of file StdDefs.h.
DT4_8
typedef DigitalTopology< Adj4, Adj8 > DGtal::Z2i::DT4_8
Definition at line 93 of file StdDefs.h.
DT8_4
typedef DigitalTopology< Adj8, Adj4 > DGtal::Z2i::DT8_4
Definition at line 94 of file StdDefs.h.
Integer
typedef DGtal::int32_t DGtal::Z2i::Integer
Definition at line 74 of file StdDefs.h.
K2
typedef KSpace DGtal::Z2i::K2
Definition at line 78 of file StdDefs.h.
KP2
typedef KPreSpace DGtal::Z2i::KP2
Definition at line 84 of file StdDefs.h.
KPreSpace
typedef KhalimskyPreSpaceND< 2, Integer > DGtal::Z2i::KPreSpace
Definition at line 83 of file StdDefs.h.
KSpace
typedef KhalimskySpaceND< 2, Integer > DGtal::Z2i::KSpace
Definition at line 77 of file StdDefs.h.
L1Metric
typedef ExactPredicateLpSeparableMetric<Space,1> DGtal::Z2i::L1Metric
Definition at line 119 of file StdDefs.h.
L1PowerMetric
typedef ExactPredicateLpPowerSeparableMetric<Space,1> DGtal::Z2i::L1PowerMetric
Definition at line 121 of file StdDefs.h.
L2Metric
typedef ExactPredicateLpSeparableMetric<Space,2> DGtal::Z2i::L2Metric
Definition at line 118 of file StdDefs.h.
L2PowerMetric
typedef ExactPredicateLpPowerSeparableMetric<Space,2> DGtal::Z2i::L2PowerMetric
Definition at line 120 of file StdDefs.h.
Object4_8
typedef Object<DT4_8, DigitalSet> DGtal::Z2i::Object4_8
Definition at line 101 of file StdDefs.h.
Object8_4
typedef Object<DT8_4, DigitalSet> DGtal::Z2i::Object8_4
Definition at line 105 of file StdDefs.h.
Point
typedef Space::Point DGtal::Z2i::Point
Definition at line 95 of file StdDefs.h.
PreCell
typedef KPreSpace::Cell DGtal::Z2i::PreCell
Definition at line 85 of file StdDefs.h.
PreCells
typedef KPreSpace::Cells DGtal::Z2i::PreCells
Definition at line 87 of file StdDefs.h.
RealPoint
typedef Space::RealPoint DGtal::Z2i::RealPoint
Definition at line 97 of file StdDefs.h.
RealVector
typedef Space::RealVector DGtal::Z2i::RealVector
Definition at line 98 of file StdDefs.h.
SCell
typedef KSpace::SCell DGtal::Z2i::SCell
Definition at line 80 of file StdDefs.h.
SCells
typedef KSpace::SCells DGtal::Z2i::SCells
Definition at line 82 of file StdDefs.h.
SmallComplementObject4_8
typedef Object<DT4_8,DigitalSet>::SmallComplementObject DGtal::Z2i::SmallComplementObject4_8
Definition at line 104 of file StdDefs.h.
SmallComplementObject8_4
typedef Object<DT8_4,DigitalSet>::SmallComplementObject DGtal::Z2i::SmallComplementObject8_4
Definition at line 108 of file StdDefs.h.
SmallObject4_8
typedef Object<DT4_8,DigitalSet>::SmallObject DGtal::Z2i::SmallObject4_8
Definition at line 103 of file StdDefs.h.
SmallObject8_4
typedef Object<DT8_4,DigitalSet>::SmallObject DGtal::Z2i::SmallObject8_4
Definition at line 107 of file StdDefs.h.
Space
typedef SpaceND< 2, Integer > DGtal::Z2i::Space
Definition at line 75 of file StdDefs.h.
SPreCell
typedef KPreSpace::SCell DGtal::Z2i::SPreCell
Definition at line 86 of file StdDefs.h.
SPreCells
typedef KPreSpace::SCells DGtal::Z2i::SPreCells
Definition at line 88 of file StdDefs.h.
Vector
typedef Space::Vector DGtal::Z2i::Vector
Definition at line 96 of file StdDefs.h.
Z2
typedef Space DGtal::Z2i::Z2
Definition at line 76 of file StdDefs.h.
Variable Documentation
adj4
const Adj4 DGtal::Z2i::adj4 static
Definition at line 111 of file StdDefs.h.
Referenced by testDraw(), testObject(), and testSimpleExpander().
adj8
const Adj8 DGtal::Z2i::adj8 static
Definition at line 112 of file StdDefs.h.
Referenced by testDraw(), testObject(), and testSimpleExpander().
dt4_8
const DT4_8 DGtal::Z2i::dt4_8 = DT4_8(adj4, adj8, JORDAN_DT) static
Definition at line 113 of file StdDefs.h.
Referenced by main(), testBreadthFirstPropagation(), testDepthFirstPropagation(), testDistancePropagation(), testLayers(), testSetTable(), testSimpleExpander(), and testSimplePoints2D().
dt8_4
const DT8_4 DGtal::Z2i::dt8_4 = DT8_4(adj8, adj4, JORDAN_DT) static
Definition at line 114 of file StdDefs.h.
Referenced by main(), testLayers(), testSimpleExpander(), and testSimplePoints2D().
l1Metric
const L1Metric DGtal::Z2i::l1Metric static
Definition at line 124 of file StdDefs.h.
Referenced by main(), and main().
l1PowerMetric
const L1PowerMetric DGtal::Z2i::l1PowerMetric static
Definition at line 126 of file StdDefs.h.
l2Metric
const L2Metric DGtal::Z2i::l2Metric static
Definition at line 123 of file StdDefs.h.
Referenced by main(), main(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
l2PowerMetric
const L2PowerMetric DGtal::Z2i::l2PowerMetric static
Definition at line 125 of file StdDefs.h.