DGtal: DGtal::IntegerConverter< dim, TInteger > Struct Template Reference
DGtal::IntegerConverter< dim, TInteger > Struct Template Reference
----------— INTEGER/POINT CONVERSION SERVICES -----------------—
#include <DGtal/kernel/IntegerConverter.h>
Public Types
typedef TInteger Integer
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
Static Public Member Functions
static Integer cast (Integer i)
static PointVector< dim, Integer > cast (PointVector< dim, Integer > p)
Detailed Description
template<DGtal::Dimension dim, typename TInteger>
struct DGtal::IntegerConverter< dim, TInteger >
----------— INTEGER/POINT CONVERSION SERVICES -----------------—
Allows seamless conversion of integral types and lattice points, while checking for errors when going from a more precise to a less precise type.
Generic version allowing only the identity cast.
Template Parameters
dim static constant of type DGtal::Dimension that specifies the static dimension of the space and thus the number of elements of the Point or Vector.
TInteger an integral type, a model of concepts::CInteger
Examples
geometry/tools/checkLatticeBallQuickHull.cpp.
Definition at line 116 of file IntegerConverter.h.
Member Typedef Documentation
Integer
template<DGtal::Dimension dim, typename TInteger > typedef TInteger DGtal::IntegerConverter< dim, TInteger >::Integer
Definition at line 118 of file IntegerConverter.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<DGtal::Dimension dim, typename TInteger > DGtal::IntegerConverter< dim, TInteger >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
cast() [1/2]
template<DGtal::Dimension dim, typename TInteger > static Integer DGtal::IntegerConverter< dim, TInteger >::cast (Integer i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 122 of file IntegerConverter.h.
    {
      return i;
    }
Referenced by DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast(), DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast(), DGtal::IntegerConverter< dim, DGtal::int32_t >::cast(), DGtal::IntegerConverter< dim, DGtal::int32_t >::cast(), DGtal::IntegerConverter< dim, DGtal::int64_t >::cast(), DGtal::IntegerConverter< dim, DGtal::int64_t >::cast(), DGtal::ConvexHullCommonKernel< dim, TCoordinateInteger, TInternalInteger >::compute(), DGtal::ConvexHullCommonKernel< dim, TCoordinateInteger, TInternalInteger >::compute(), DGtal::ConvexHullCommonKernel< dim, TCoordinateInteger, TInternalInteger >::height(), DGtal::ConvexHullCommonKernel< dim, TCoordinateInteger, TInternalInteger >::intercept(), and DGtal::ConvexHullCommonKernel< dim, TCoordinateInteger, TInternalInteger >::normal().
cast() [2/2]
template<DGtal::Dimension dim, typename TInteger > static PointVector< dim, Integer > DGtal::IntegerConverter< dim, TInteger >::cast (PointVector< dim, Integer > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 133 of file IntegerConverter.h.
    {
      return p;
    }
The documentation for this struct was generated from the following file:
IntegerConverter.h