DGtal: DGtal::HyperRectDomain< TSpace >::ConstSubRange Struct Reference
DGtal::HyperRectDomain< TSpace >::ConstSubRange Struct Reference
Aim: range through some subdomain of all the points in the domain. Defines a constructor taking a domain in parameter plus some additional parameters to specify the subdomain, begin and end methods returning ConstIterator, and rbegin and rend methods returning ConstReverseIterator.
#include <DGtal/kernel/domains/HyperRectDomain.h>
Public Types
typedef HyperRectDomain_subIterator< Point > ConstIterator
typedef HyperRectDomain_ReverseIterator< ConstIterator > ConstReverseIterator
Public Member Functions
ConstSubRange (const HyperRectDomain< TSpace > &domain, const std::vector< Dimension > &permutation, const Point &startingPoint)
ConstSubRange (const HyperRectDomain< TSpace > &domain, std::initializer_list< Dimension > permutation, const Point &startingPoint)
ConstSubRange (const HyperRectDomain< TSpace > &domain, Dimension adim, const Point &startingPoint)
ConstSubRange (const HyperRectDomain< TSpace > &domain, Dimension adim1, Dimension adim2, const Point &startingPoint)
ConstSubRange (const HyperRectDomain< TSpace > &domain, Dimension adim1, Dimension adim2, Dimension adim3, const Point &startingPoint)
ConstIterator begin () const
ConstIterator begin (const Point &aPoint) const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
Private Attributes
Point myLowerBound
Lower bound of the subrange.
Point myUpperBound
Upper bound of the subrange.
Point myStartingPoint
Starting point of the subrange.
std::vector< Dimension > myPermutation
Permutation on dimensions used in the subrange.
Detailed Description
template<typename TSpace>
struct DGtal::HyperRectDomain< TSpace >::ConstSubRange
Aim: range through some subdomain of all the points in the domain. Defines a constructor taking a domain in parameter plus some additional parameters to specify the subdomain, begin and end methods returning ConstIterator, and rbegin and rend methods returning ConstReverseIterator.
Description of class 'ConstSubRange'
Definition at line 249 of file HyperRectDomain.h.
Member Typedef Documentation
ConstIterator
template<typename TSpace > typedef HyperRectDomain_subIterator<Point> DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstIterator
Definition at line 251 of file HyperRectDomain.h.
ConstReverseIterator
template<typename TSpace > typedef HyperRectDomain_ReverseIterator<ConstIterator> DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstReverseIterator
Definition at line 252 of file HyperRectDomain.h.
Constructor & Destructor Documentation
ConstSubRange() [1/5]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange (const HyperRectDomain< TSpace > & domain, const std::vector< Dimension > & permutation, const Point & startingPoint) inline
ConstSubRange constructor from a given domain.
Parameters
domain the domain.
permutation a vector containing the dimensions used for the subrange. Dimensions are iterated in the given order.
startingPoint the initial point.
Precondition
startingPoint must belong to the range.
Definition at line 262 of file HyperRectDomain.h.
        : myLowerBound(domain.myLowerBound),
          myUpperBound(domain.myUpperBound),
          myStartingPoint(startingPoint)
        {
          ASSERT_MSG(
              domain.isInside(startingPoint) || startingPoint == myLowerBound || startingPoint == myUpperBound,
              "The point must be inside the given domain or be equal to one of his bound."
          );
          myPermutation.reserve( permutation.size() );
          std::copy(permutation.begin(), permutation.end(), std::back_inserter(myPermutation));
          myLowerBound.partialCopyInv(myStartingPoint, myPermutation);
          myUpperBound.partialCopyInv(myStartingPoint, myPermutation);
        }
References domain, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::partialCopyInv().
ConstSubRange() [2/5]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange (const HyperRectDomain< TSpace > & domain, std::initializer_list< Dimension > permutation, const Point & startingPoint) inline
ConstSubRange constructor from a given domain.
Parameters
domain the domain.
permutation an initializer_list containing the dimensions used for the subrange. Dimensions are iterated in the given order.
startingPoint the initial point.
Precondition
startingPoint must belong to the range.
Definition at line 288 of file HyperRectDomain.h.
        : myLowerBound(domain.myLowerBound),
          myUpperBound(domain.myUpperBound),
          myStartingPoint(startingPoint)
        {
          ASSERT_MSG(
              domain.isInside(startingPoint) || startingPoint == myLowerBound || startingPoint == myUpperBound,
              "The point must be inside the given domain or be equal to one of his bound."
          );
          myPermutation.reserve( permutation.size() );
          for ( const unsigned int *c = permutation.begin(); c != permutation.end(); ++c )
            {
              myPermutation.push_back( *c );
            }
          myLowerBound.partialCopyInv(myStartingPoint, myPermutation);
          myUpperBound.partialCopyInv(myStartingPoint, myPermutation);
        }
References domain, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::partialCopyInv().
ConstSubRange() [3/5]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange (const HyperRectDomain< TSpace > & domain, Dimension adim, const Point & startingPoint) inline
ConstSubRange constructor from a given domain for one dimension.
Parameters
domain the domain.
adim the dimension used for the subrange.
startingPoint the initial point.
Precondition
startingPoint must belong to the range.
Definition at line 316 of file HyperRectDomain.h.
        : myLowerBound(domain.myLowerBound),
          myUpperBound(domain.myUpperBound),
          myStartingPoint(startingPoint)
        {
          ASSERT_MSG(
              domain.isInside(startingPoint) || startingPoint == myLowerBound || startingPoint == myUpperBound,
              "The point must be inside the given domain or be equal to one of his bound."
          );
          myPermutation.push_back( adim );
          myLowerBound.partialCopyInv(myStartingPoint, myPermutation);
          myUpperBound.partialCopyInv(myStartingPoint, myPermutation);
        }
References domain, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::partialCopyInv().
ConstSubRange() [4/5]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange (const HyperRectDomain< TSpace > & domain, Dimension adim1, Dimension adim2, const Point & startingPoint) inline
ConstSubRange constructor from a given domain for two dimensions.
Parameters
domain the domain.
adim1 the first dimension used for the subrange.
adim2 the second dimension used for the subrange.
startingPoint the initial point.
Precondition
startingPoint must belong to the range.
Definition at line 341 of file HyperRectDomain.h.
        : myLowerBound(domain.myLowerBound),
          myUpperBound(domain.myUpperBound),
          myStartingPoint(startingPoint)
        {
          ASSERT_MSG(
              domain.isInside(startingPoint) || startingPoint == myLowerBound || startingPoint == myUpperBound,
              "The point must be inside the given domain or be equal to one of his bound."
          );
          myPermutation.push_back( adim1 );
          myPermutation.push_back( adim2 );
          myLowerBound.partialCopyInv(myStartingPoint, myPermutation);
          myUpperBound.partialCopyInv(myStartingPoint, myPermutation);
        }
References domain, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::partialCopyInv().
ConstSubRange() [5/5]
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange (const HyperRectDomain< TSpace > & domain, Dimension adim1, Dimension adim2, Dimension adim3, const Point & startingPoint) inline
ConstSubRange constructor from a given domain for two dimensions.
Parameters
domain the domain.
adim1 the first dimension used for the subrange.
adim2 the second dimension used for the subrange.
adim3 the third dimension used for the subrange.
startingPoint the initial point.
Precondition
startingPoint must belong to the range.
Definition at line 368 of file HyperRectDomain.h.
        : myLowerBound(domain.myLowerBound),
          myUpperBound(domain.myUpperBound),
          myStartingPoint(startingPoint)
        {
          ASSERT_MSG(
              domain.isInside(startingPoint) || startingPoint == myLowerBound || startingPoint == myUpperBound,
              "The point must be inside the given domain or be equal to one of his bound."
          );
          myPermutation.push_back( adim1 );
          myPermutation.push_back( adim2 );
          myPermutation.push_back( adim3 );
          myLowerBound.partialCopyInv(myStartingPoint, myPermutation);
          myUpperBound.partialCopyInv(myStartingPoint, myPermutation);
        }
References domain, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound, and DGtal::PointVector< dim, TEuclideanRing, TContainer >::partialCopyInv().
Member Function Documentation
begin() [1/2]
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin () const inline
begin method.
Returns
ConstIterator on the beginning of the range.
Definition at line 391 of file HyperRectDomain.h.
        {
          return ConstIterator(myLowerBound, myLowerBound, myUpperBound, myPermutation);
        }
References DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, and DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound.
Referenced by DGtal::ImageFactoryFromHDF5< TImageContainer >::flushImage(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::rbegin(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::rend().
begin() [2/2]
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin (const Point & aPoint) const inline
begin method from a given point.
Parameters
aPoint the initial point.
Returns
a ConstIterator initialized to aPoint.
Precondition
aPoint must belong to the range.
Definition at line 402 of file HyperRectDomain.h.
        {
          ASSERT(aPoint.partialEqualInv(myLowerBound, myPermutation) );
          ASSERT_MSG(
            ( myLowerBound.isLower(aPoint) && aPoint.isLower(myUpperBound) ) || aPoint == myLowerBound || aPoint == myUpperBound,
            "The point must be inside the given domain or be equal to one of his bound."
          );
          return ConstIterator(aPoint, myLowerBound, myUpperBound, myPermutation);
        }
References aPoint(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::isLower(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, and DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound.
end()
template<typename TSpace > ConstIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::end () const inline
end method.
Returns
ConstIterator on the end of the range.
Definition at line 417 of file HyperRectDomain.h.
        {
          ConstIterator it = ConstIterator(myUpperBound, myLowerBound, myUpperBound, myPermutation);
          ++it;
          return it;
        }
References DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound, DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation, and DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound.
Referenced by DGtal::ImageFactoryFromHDF5< TImageContainer >::flushImage(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::rbegin().
rbegin() [1/2]
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::rbegin () const inline
reverse begin method.
Returns
ConstIterator on the beginning of the reverse range.
Definition at line 428 of file HyperRectDomain.h.
        {
          return ConstReverseIterator(end());
        }
References DGtal::HyperRectDomain< TSpace >::ConstSubRange::end().
rbegin() [2/2]
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::rbegin (const Point & aPoint) const inline
reverse begin method from a given point.
Parameters
aPoint the initial point.
Returns
a ConstIterator initialized to aPoint.
Precondition
aPoint must belong to the range.
Definition at line 439 of file HyperRectDomain.h.
        {
          ConstIterator it(begin(aPoint));
          ++it;
          return ConstReverseIterator(it);
        }
References aPoint(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin().
rend()
template<typename TSpace > ConstReverseIterator DGtal::HyperRectDomain< TSpace >::ConstSubRange::rend () const inline
reverse end method.
Returns
ConstIterator on the end of the reverse range.
Definition at line 450 of file HyperRectDomain.h.
        {
          return ConstReverseIterator(begin());
        }
References DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin().
Field Documentation
myLowerBound
template<typename TSpace > Point DGtal::HyperRectDomain< TSpace >::ConstSubRange::myLowerBound private
Lower bound of the subrange.
Definition at line 457 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::end().
myPermutation
template<typename TSpace > std::vector<Dimension> DGtal::HyperRectDomain< TSpace >::ConstSubRange::myPermutation private
Permutation on dimensions used in the subrange.
Definition at line 463 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::end().
myStartingPoint
template<typename TSpace > Point DGtal::HyperRectDomain< TSpace >::ConstSubRange::myStartingPoint private
Starting point of the subrange.
Definition at line 461 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange().
myUpperBound
template<typename TSpace > Point DGtal::HyperRectDomain< TSpace >::ConstSubRange::myUpperBound private
Upper bound of the subrange.
Definition at line 459 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::begin(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), DGtal::HyperRectDomain< TSpace >::ConstSubRange::ConstSubRange(), and DGtal::HyperRectDomain< TSpace >::ConstSubRange::end().
The documentation for this struct was generated from the following file:
HyperRectDomain.h