DGtal: testCOBAGenericNaivePlaneComputer-benchmark.cpp File Reference
testCOBAGenericNaivePlaneComputer-benchmark.cpp File Reference
DGtal Test Files
#include <cstdlib>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/math/Statistic.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/kernel/CPointPredicate.h"
#include "DGtal/geometry/surfaces/COBAGenericNaivePlaneComputer.h"
Functions
template<typename Integer >
Integer getRandomInteger (const Integer &first, const Integer &after_last)
template<typename Integer , typename NaivePlaneComputer >
bool checkGenericPlane (Integer a, Integer b, Integer c, Integer d, int diameter, unsigned int nbpoints, Statistic< double > &stats)
template<typename NaivePlaneComputer >
bool checkGenericPlanes (unsigned int nbplanes, int diameter, unsigned int nbpoints, Statistic< double > &stats)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/03/05
Functions for testing class COBAGenericNaivePlaneComputer.
This file is part of the DGtal library.
Definition in file testCOBAGenericNaivePlaneComputer-benchmark.cpp.
Function Documentation
checkGenericPlane()
template<typename Integer , typename NaivePlaneComputer > bool checkGenericPlane (Integer a, Integer b, Integer c, Integer d, int diameter, unsigned int nbpoints, Statistic< double > & stats)
Checks the naive plane d <= ax+by+cz <= d + max(|a|,|b|,|c|)-1
Definition at line 59 of file testCOBAGenericNaivePlaneComputer-benchmark.cpp.
{
  typedef typename NaivePlaneComputer::Point Point;
  typedef typename Point::Component PointInteger;
  IntegerComputer<Integer> ic;
  Integer absA = ic.abs( a );
  Integer absB = ic.abs( b );
  Integer absC = ic.abs( c );
  Integer x, y, z;
  Dimension axis;
  if ( ( absA >= absB ) && ( absA >= absC ) )
    axis = 0;
  else if ( ( absB >= absA ) && ( absB >= absC ) )
    axis = 1;
  else
    axis = 2;
  Point p;
  NaivePlaneComputer plane;
  plane.init( diameter, 1, 1 );
  // Checks that points within the naive plane are correctly recognized.
  unsigned int nb = 0;
  unsigned int nbok = 0;
  unsigned int nbchanges = 0;
  auto complexity = plane.complexity();
  while ( nb != nbpoints )
    {
      p[ 0 ] = getRandomInteger<PointInteger>( -diameter+1, diameter );
      p[ 1 ] = getRandomInteger<PointInteger>( -diameter+1, diameter );
      p[ 2 ] = getRandomInteger<PointInteger>( -diameter+1, diameter );
      x = (Integer) p[ 0 ];
      y = (Integer) p[ 1 ];
      z = (Integer) p[ 2 ];
      switch ( axis ) {
        case 0: p[ 0 ] = static_cast<typename Point::Component>(NumberTraits<Integer>::castToInt64_t( ic.ceilDiv( d - b * y - c * z, a ) )); break;
        case 1: p[ 1 ] = static_cast<typename Point::Component>(NumberTraits<Integer>::castToInt64_t( ic.ceilDiv( d - a * x - c * z, b ) )); break;
        case 2: p[ 2 ] = static_cast<typename Point::Component>(NumberTraits<Integer>::castToInt64_t( ic.ceilDiv( d - a * x - b * y, c ))); break;
      }
      bool ok = plane.extend( p ); // should be ok
      ++nb; nbok += ok ? 1 : 0;
      if ( ! ok )
        {
          std::cerr << "[ERROR] p=" << p << " NOT IN plane=" << plane << std::endl;
          break;
        }
      if ( plane.complexity() != complexity )
        {
          complexity = plane.complexity();
          ++nbchanges;
        }
    }
  stats.addValue( (double) nbchanges );
  return nb == nbok;
}
References DGtal::IntegerComputer< TInteger >::abs(), DGtal::Statistic< TQuantity >::addValue(), DGtal::IntegerComputer< TInteger >::ceilDiv(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::complexity(), DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::extend(), getRandomInteger(), and DGtal::COBANaivePlaneComputer< TSpace, TInternalInteger >::init().
Referenced by checkGenericPlanes().
checkGenericPlanes()
template<typename NaivePlaneComputer > bool checkGenericPlanes (unsigned int nbplanes, int diameter, unsigned int nbpoints, Statistic< double > & stats)
Definition at line 117 of file testCOBAGenericNaivePlaneComputer-benchmark.cpp.
{
  //using namespace Z3i;
  typedef typename NaivePlaneComputer::InternalInteger Integer;
  unsigned int nb = 0;
  unsigned int nbok = 0;
  for ( unsigned int nbp = 0; nbp < nbplanes; ++nbp )
    {
      Integer a = getRandomInteger<Integer>( (Integer) 0, (Integer) diameter / 2 );
      Integer b = getRandomInteger<Integer>( (Integer) 0, (Integer) diameter / 2 );
      Integer c = getRandomInteger<Integer>( (Integer) 0, (Integer) diameter / 2 );
      Integer d = getRandomInteger<Integer>( (Integer) 0, (Integer) diameter / 2 );
      if ( ( a != 0 ) || ( b != 0 ) || ( c != 0 ) )
        {
          ++nb; nbok += checkGenericPlane<Integer, NaivePlaneComputer>( a, b, c, d, diameter, nbpoints, stats ) ? 1 : 0;
          if ( nb != nbok )
            {
              std::cerr << "[ERROR] for plane " << a << " * x + "
                        << b << " * y + " << c << " * z = " << d << std::endl;
              break;
            }
        }
    }
  return nb == nbok;
}
References checkGenericPlane(), and getRandomInteger().
Referenced by main().
getRandomInteger()
template<typename Integer > Integer getRandomInteger (const Integer & first, const Integer & after_last)
Definition at line 48 of file testCOBAGenericNaivePlaneComputer-benchmark.cpp.
{
  Integer r = (Integer) rand();
  return ( r % (after_last - first) ) + first;
}
Referenced by checkGenericPlane(), and checkGenericPlanes().
main()
int main (int argc, char ** argv)
Definition at line 148 of file testCOBAGenericNaivePlaneComputer-benchmark.cpp.
{
  using namespace Z3i;
  Statistic<double> stats;
  unsigned int nbtries = ( argc > 1 ) ? atoi( argv[ 1 ] ) : 100;
  unsigned int nbpoints = ( argc > 2 ) ? atoi( argv[ 2 ] ) : 100;
  unsigned int diameter = ( argc > 3 ) ? atoi( argv[ 3 ] ) : 100;
  std::cout << "# Usage: " << argv[0] << " <nbtries> <nbpoints> <diameter>." << std::endl;
  std::cout << "# Test class COBAGenericNaivePlaneComputer. Points are randomly chosen in [-diameter,diameter]^3." << std::endl;
  std::cout << "# Integer nbtries nbpoints diameter time/plane(ms) E(comp) V(comp)" << std::endl;
 // Max diameter is ~20 for int32_t, ~500 for int64_t, any with BigInteger.
  trace.beginBlock ( "Testing class COBAGenericNaivePlaneComputer" );
  bool res = true
    && checkGenericPlanes<COBAGenericNaivePlaneComputer<Z3, DGtal::BigInteger> >( nbtries, diameter, nbpoints, stats );
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  long t = trace.endBlock();
  stats.terminate();
  std::cout << "BigInteger" << " " << stats.samples()
            << " " << nbpoints
            << " " << diameter
            << " " << ( (double) t / (double) stats.samples() )
            << " " << stats.mean()
            << " " << stats.variance()
            << std::endl;
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), checkGenericPlanes(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Statistic< TQuantity >::mean(), DGtal::Statistic< TQuantity >::samples(), DGtal::Statistic< TQuantity >::terminate(), DGtal::trace, and DGtal::Statistic< TQuantity >::variance().