DGtal: testMeshReader.cpp File Reference
testMeshReader.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/shapes/Mesh.h"
#include "DGtal/io/readers/MeshReader.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigTest.h"
Typedefs
typedef Point3D Point
Functions
bool testMeshReader ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2012/07/04
Functions for testing class MeshReader.
This file is part of the DGtal library.
Definition in file testMeshReader.cpp.
Typedef Documentation
Point
typedef Point3D Point
Definition at line 74 of file testMeshReader.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 157 of file testMeshReader.cpp.
{
  trace.beginBlock ( "Testing class MeshReader" );
  trace.info() << "Args:";
  for ( int i = 0; i < argc; ++i )
    trace.info() << " " << argv[ i ];
  trace.info() << endl;
  bool res = testMeshReader(); // && ... other tests
  trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
  trace.endBlock();
  return res ? 0 : 1;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testMeshReader(), and DGtal::trace.
testMeshReader()
bool testMeshReader ()
Example of a test. To be completed.
Definition at line 90 of file testMeshReader.cpp.
{
  unsigned int nbok = 0;
  unsigned int nb = 0;
  trace.beginBlock ( "Testing block ..." );
  nb++;
  std::string filenameOFF = testPath + "samples/box.off";
  Mesh<Point> a3DMesh;
  bool importOK = a3DMesh << filenameOFF;
  nbok += importOK ? 1 : 0;
  nb++;
  Mesh<Point>::MeshFace aFace = a3DMesh.getFace(0);
  bool isWellImported = (a3DMesh.nbVertex()==8) &&  (a3DMesh.nbFaces()==6) && (aFace.size()==4) && (aFace.at(0)==0);
  nbok+=isWellImported? 1: 0;
  trace.info() << "(" << nbok << "/" << nb << ") "
    << "true == true" << std::endl;
  nb++;
  std::string filenameOFS = testPath + "samples/testMesh.ofs";
  Mesh<Point> a3DMesh2;
  bool importOK2=  a3DMesh2 << filenameOFS;
  nbok += importOK2 ? 1 : 0;
  nb++;
  std::string filenameOBJ = testPath + "samples/testObj.obj";
  Mesh<Point> a3DMesh3;
  bool importOK3=  a3DMesh3 << filenameOBJ;
  nbok += importOK3 ? 1 : 0;
  nb++;
  bool importOK4 = a3DMesh3.getFaceColor(0) == DGtal::Color::Red &&
                   a3DMesh3.getFaceColor(5) == DGtal::Color::Purple;
  nbok += importOK4 ? 1 : 0;
  nb++;
  Mesh<Point>::MeshFace aFace2 = a3DMesh2.getFace(0);
  bool isWellImported2 = (a3DMesh2.nbVertex()==32) &&  (a3DMesh2.nbFaces()==60) && (aFace2.size()==3) && (aFace2.at(0)==0);
  nbok+=isWellImported2? 1: 0;
  nb++;
  std::string filenameOBJrel = testPath + "samples/testObjRel.obj";
  Mesh<Point> a3DMesh4;
  bool importOK5 =  a3DMesh4 << filenameOBJrel;
  nbok += importOK5 ? 1 : 0;
  nb++;
  bool importOK6 = a3DMesh4.getFaceColor(0) == DGtal::Color::Red &&
                   a3DMesh4.getFaceColor(5) == DGtal::Color::Purple;
  nbok += importOK6 ? 1 : 0;
  trace.info() << "(" << nbok << "/" << nb << ") "
    << "true == true" << std::endl;
  trace.endBlock();
  return nbok == nb;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Mesh< TPoint >::getFace(), DGtal::Mesh< TPoint >::getFaceColor(), DGtal::Trace::info(), DGtal::Mesh< TPoint >::nbFaces(), DGtal::Mesh< TPoint >::nbVertex(), DGtal::Color::Purple, DGtal::Color::Red, and DGtal::trace.
Referenced by main().